### PR TITLE
Fix look_to resulting in NaN rotations

### LINKED ISSUE #3736: NaN when `looking_at` is called with `Transform`'s origin as target
## Bevy version
0.5 and 0.6

## Operating system & version
Linux Mint 20.2

## What you did

I modified the 3D Scene example so line 42 read as,
`transform: Transform::from_xyz(0.0, 0.0, 0.0).looking_at(Vec3::ZERO, Vec3::Y),`

As you can see, the origin of the transform is the same as where it's set to look.

## What you expected to happen

Default to either current Quat or the unit matrix.

## What actually happened

Printing the debug value of that particular transform produced,
`Mut(Transform { translation: Vec3(NaN, NaN, NaN), rotation: Quat(NaN, NaN, NaN, NaN), scale: Vec3(1.0, 1.0, 1.0) })`

and attempting to further modify it resulted in no change (as expected, given what's happening).

## Additional information

-

### LINKED ISSUE #7802: Camera3dBundle doesn't render anything when looking from above
## Bevy version

0.9.1

## \[Optional\] Relevant system information

If you cannot get Bevy to build or run on your machine, please include:

- the Rust version you're using (you can get this by running `cargo --version`)
  - Bevy relies on the "latest stable release" of Rust
  - nightly should generally work, but there are sometimes regressions: please let us know!
- the operating system or browser used, including its version
  - e.g. Windows 10, Ubuntu 18.04, iOS 14

If your bug is rendering-related, copy the adapter info that appears when you run Bevy.

`AdapterInfo { name: "NVIDIA GeForce RTX 3080", vendor: 4318, device: 8710, device_type: DiscreteGpu, driver: "NVIDIA", driver_info: "528.49", backend: Vulkan }`

You should also consider testing the examples of our upstream dependencies to help isolate any setup-specific issue:

- [`wgpu`](https://github.com/gfx-rs/wgpu) for rendering problems
- [`winit`](https://github.com/rust-windowing/winit) for input and window management
- [`gilrs`](https://docs.rs/gilrs/latest/gilrs/) for gamepad inputs

## What you did

Minimal code example demonstrating the issue:

```
use bevy::prelude::*;

fn main() {
    App::new()
        .add_plugins(DefaultPlugins)
        .add_startup_system(setup)
        .run();
}

fn setup(
    mut commands: Commands,
    mut meshes: ResMut<Assets<Mesh>>,
    mut materials: ResMut<Assets<StandardMaterial>>,
) {
    commands.spawn(Camera3dBundle {
        transform: Transform::from_xyz(0., 5., 0.).looking_at(Vec3::new(0.0, 0.0, 0.0), Vec3::Y),
        ..default()
    });

    // plane
    commands.spawn(PbrBundle {
        mesh: meshes.add(Mesh::from(shape::Plane { size: 5.0 })),
        material: materials.add(Color::rgb(0.3, 0.5, 0.3).into()),
        ..default()
    });

    commands.spawn(PbrBundle {
        mesh: meshes.add(Mesh::from(shape::Cube { size: 1.0 })),
        material: materials.add(Color::rgb(0.8, 0.7, 0.6).into()),
        transform: Transform::from_xyz(0.0, 0.5, 0.0),
        ..default()
    });
}
```

When you change from_xyz(0., 5., 0.) to from_xyz(0., 5., 1.) you see everything fine. Expected to see an overhead view with from_xyz(0., 5., 0.) - instead got a gray screen.

## Additional information

Other information that can be used to further reproduce or isolate the problem.
This commonly includes:

- screenshots
- logs
- theories about what might be going wrong
- workarounds that you used
- links to related bugs, PRs or discussions

### PR DESCRIPTION
**Pull request by mockersf**
# Objective

- Fixes #7802, Fixes #3736
- Alternative to #6136 

## Solution

- if direction is parallel to up, use an orthogonal vector
- if direction is zero, use Z

### CODE REVIEW

**Review by nicopap — APPROVED** [review]
This is like Elm deciding that `1 / 0 = 0`, it might not comply with the purely theoretical definition, but I personally think that functional beats pure. Especially if the selected fallback direction is clearly defined.

File: crates/bevy_transform/src/components/transform.rs [hunk 1]
```diff
@@ -325,17 +333,28 @@ impl Transform {
...
+    /// It is also not possible when the direction provided is zero. In this case, the Z axis will be used as the "forward" direction.
     #[inline]
     pub fn look_to(&mut self, direction: Vec3, up: Vec3) {
-        let forward = -direction.normalize();
-        let right = up.cross(forward).normalize();
+        let forward = -direction.try_normalize().unwrap_or(Vec3::Z);
+        let right = up
+            .cross(forward)
+            .try_normalize()
+            .unwrap_or_else(|| up.any_orthogonal_vector());
```
Comment (devil-ira) [inline crates/bevy_transform/src/components/transform.rs:357]:
```suggestion
            .unwrap_or_else(|| up.any_orthonormal_vector());
```
`any_orthogonal_vector()` might not return a normalized vector.

Also, should we check whether `up` is normalized and non-zero as well?

Comment (mockersf) [reply crates/bevy_transform/src/components/transform.rs:357]: `any_orthonormal_vector` only does if `up` is normalized, otherwise it returns garbage

**Review by devil-ira — APPROVED** [review]

File: crates/bevy_transform/src/components/transform.rs (hunk 1 above)
Comment (devil-ira) [reply crates/bevy_transform/src/components/transform.rs]: Looks like the docs for `any_orthonormal_vector` are wrong then

File: crates/bevy_transform/src/components/transform.rs [hunk 2]
```diff
@@ -120,6 +120,11 @@ impl Transform {
 
     /// Returns this [`Transform`] with a new rotation so that [`Transform::forward`]
     /// points towards the `target` position and [`Transform::up`] points towards `up`.
+    ///
+    /// In some cases it's not possible to construct a rotation. Another axis will be picked in those cases:
+    /// * if `target` is the same as the transtorm translation, `Vec3::Z` is used instead
```
Comment (LiamGallagher737) [inline crates/bevy_transform/src/components/transform.rs:125]:
```suggestion
    /// * if `target` is the same as the transform translation, `Vec3::Z` is used instead
```

File: crates/bevy_transform/src/components/transform.rs [hunk 3]
```diff
@@ -120,6 +120,11 @@ impl Transform {
 
     /// Returns this [`Transform`] with a new rotation so that [`Transform::forward`]
     /// points towards the `target` position and [`Transform::up`] points towards `up`.
+    ///
+    /// In some cases it's not possible to construct a rotation. Another axis will be picked in those cases:
```
Comment (james7132) [inline crates/bevy_transform/src/components/transform.rs:124]: I wonder if this means we should be returning `Result<Self, SomeError>` instead, seems odd to silently fail here.

**Review by james7132 — CHANGES_REQUESTED** [review]

File: crates/bevy_transform/src/components/transform.rs (hunk 3 above)
Comment (alice-i-cecile) [reply crates/bevy_transform/src/components/transform.rs:124]: IMO we're not silently failing: we're performing a "best-attempt". I'd be open to `try` variants too.

Comment (mockersf) [reply crates/bevy_transform/src/components/transform.rs:124]: I would prefer to work by default, instead of having to add unwrap / error management everywhere this pops up
