### PR TITLE
Move sprite batches to resource

### LINKED ISSUE #16867: the render layers: they are broken
## Bevy version

0.15

## What you did

1. I rendered a bird into RenderLayers 0 and another into RenderLayers 0 and 1.
2. Camera A has RenderLayers 0
3. Camera B has RenderLayers 1 and a RenderTarget Image.

## What went wrong

We expect to see both birds on Camera A and only one bird on Camera B, which is drawn as an ImageNode to display the RenderTarget contents.

Instead we see... a random combination of birds on both cameras. ?!?

Example code is here: https://github.com/dead-money/bevy_render_layers_broken

Every few seconds the example despawns everything and recreates the scene. You'll see arbitrary results.

### PR DESCRIPTION
**Pull request by tychedelia**
# Objective

Currently, `prepare_sprite_image_bind_group` spawns sprite batches onto an individual representative entity of the batch. This poses significant problems for multi-camera setups, since an entity may appear in multiple phase instances.

## Solution

Instead, move batches into a resource that is keyed off the view and the representative entity. Long term we should switch to mesh2d and use the existing BinnedRenderPhase functionality rather than naively queueing into transparent and doing our own ad-hoc batching logic.

Fixes #16867, #17351

## Testing

Tested repros in above issues.

### CODE REVIEW

**Comment by tychedelia** [comment]
I guess this is technically a breaking change but can probably be safely picked into `0.15.2`. Your call @alice-i-cecile.

**Comment by hukasu** [comment]
Ran codes provided by each of the linked issues and they seem to work as intended now

**Review by hukasu — COMMENTED** [review]
While i was looking for info on the issues, i saw line 565
```
let index = extracted_sprite.original_entity.unwrap_or(*entity).index();
```
should the value inside the `unwrap_or` be `main_entity.id()`?

**Comment by tychedelia** [comment]
> While i was looking for info on the issues, i saw line 565
> 
> ```
> let index = extracted_sprite.original_entity.unwrap_or(*entity).index();
> ```
> 
> should the value inside the `unwrap_or` be `main_entity.id()`?

Yes, the `original_entity` field in `ExtractedSprite` should likely be `MainEntity`, but that's unrelated to the issue here and mostly a correctness issue (it's easy to accidentally use a `RenderEntity` for something that's keyed off of `MainEntity`, e.g.).

File: crates/bevy_sprite/src/render/mod.rs [hunk 1]
```diff
@@ -650,7 +653,8 @@ pub fn prepare_sprite_image_bind_groups(
 
     let image_bind_groups = &mut *image_bind_groups;
 
-    for transparent_phase in phases.values_mut() {
+    for (retained_view, transparent_phase) in phases.iter_mut() {
+        let mut batch_key = None;
```
Comment (hukasu) [inline crates/bevy_sprite/src/render/mod.rs:657]: I dislike how the way the flow of the method requires that this is initialized with `None`, i would personally collect all distinct phase items into something like a `HashMap<AssetId<Image>, Vec<Entity>>`

Comment (superdump) [reply crates/bevy_sprite/src/render/mod.rs:657]: Without having reminded myself of how this code works, not having thought enough about what you mean, using HashMap to hold collections of entities with not-highly-optimised keys seems likely to introduce significant performance regressions.

**Comment by superdump** [comment]
Do you have any Tracy traces to show the performance of bevymark using the sprite mode with say 100-150k sprites?

File: crates/bevy_sprite/src/render/mod.rs [hunk 2]
```diff
@@ -483,7 +484,10 @@ pub struct SpriteViewBindGroup {
     pub value: BindGroup,
 }
 
-#[derive(Component, PartialEq, Eq, Clone)]
+#[derive(Resource, Deref, DerefMut, Default)]
+pub struct SpriteBatches(HashMap<(RetainedViewEntity, MainEntity), SpriteBatch>);
```
Comment (superdump) [inline crates/bevy_sprite/src/render/mod.rs:488]: Do we have an optimised hash of a pair of entities yet? If not then perhaps we need one? In the degenerate case with one batch per sprite I suppose this would hurt. But, sprites should use sprite sheets so that should not happen for large numbers of sprites in practice.

Comment (tychedelia) [reply crates/bevy_sprite/src/render/mod.rs:488]: I think using `EntityHash` should work no matter how many entities you use in the key. I'll include that instead of the default hasher and confirm.

**Comment by tychedelia** [comment]
This appears to be solidly faster, which is somewhat surprising to me but maybe the cost of batch spawning is a lot greater than even all the hashing?

image

File: crates/bevy_sprite/src/render/mod.rs [hunk 3]
```diff
@@ -771,7 +776,7 @@ pub fn prepare_sprite_image_bind_groups(
             transparent_phase.items[batch_item_index]
                 .batch_range_mut()
                 .end += 1;
-            batches.last_mut().unwrap().1.range.end += 1;
+            batches.get_mut(&batch_key.unwrap()).unwrap().range.end += 1;
```
Comment (ickshonpe) [inline crates/bevy_sprite/src/render/mod.rs:779]: Could add a `current_batch` variable containing a reference to the current `SpriteBatch` in the sprite batches map and avoid the extra hashmap look up here each iteration.

File: crates/bevy_sprite/src/render/mod.rs (hunk 2 above)
Comment (tychedelia) [reply crates/bevy_sprite/src/render/mod.rs:488]: This didn't seem to matter in my testing.

File: crates/bevy_sprite/src/render/mod.rs (hunk 3 above)
Comment (tychedelia) [reply crates/bevy_sprite/src/render/mod.rs]: This was a substantial improvement, now compared to main:

image

File: crates/bevy_sprite/src/render/mod.rs [hunk 4]
```diff
@@ -690,8 +694,7 @@ pub fn prepare_sprite_image_bind_groups(
                     });
 
                 batch_item_index = item_index;
-                batches.push((
-                    item.entity(),
+                current_batch = Some(batches.entry((*retained_view, item.main_entity())).insert(
```
Comment (ickshonpe) [inline crates/bevy_sprite/src/render/mod.rs:697]: Do we need to use the whole `RetainedViewEntity` as a key, it seems like just using `retained_view.main_entity` would be enough to avoid collisions?

Comment (tychedelia) [reply crates/bevy_sprite/src/render/mod.rs:697]: I think it probably would be fine, especially because this is not yet retained and we are rebuilding this every frame, but we're moving towards using `RetainedViewEntity` everywhere for safety reasons. In my brief benching, using just the `MainEntity` didn't seem to have a notable performance impact.

**Review by hukasu — APPROVED** [review]

**Review by ickshonpe — APPROVED** [review]
Looks good. The batches aren't overwritten any more, the example from #17351 works correctly now.
