### PR TITLE
Fix example game of life

### LINKED ISSUE #9353: Potentially incorrect barrier in Game of Life example
## Bevy version

git (but any that contain the game of life example have the issue)

## What you did

The `game_of_life.wgsl` compute shader example uses a barrier in an attempt to synchronize all threads before writing to the storage texture:

https://github.com/bevyengine/bevy/blob/42098192c228bd1329ff9ff1a4848c030ec171ec/assets/shaders/game_of_life.wgsl#L63-L65

This synchronization is needed because all threads also *read* from the same texture (from various pixels that are written to by other invocations).

## What went wrong

To my knowledge, GPU barriers only affect threads *within a single workgroup*, but not those in different workgroups (that would require running an *unbounded* number of threads until they reach the barrier, saving their state, and then resuming them later). The shader uses 8x8 threads per workgroup, but runs on a texture that is much larger.

The potential impact of this is that a workgroup might read from pixels that were already written to by a different workgroup (outside of its 8x8 pixel block), leading to incorrect simulation results. Not the end of the world, but an example meant for teaching should probably get this right.

AFAIK the only way to correctly implement game of life in a compute shader is by using *two* textures and flipping between them every simulation step. That implementation wouldn't need a barrier at all, which is by far the simplest barrier to reason about :)

### PR DESCRIPTION
**Pull request by mockersf**
# Objective

- Example `compute_shader_game_of_life` is random and not following the rules of the game of life: at each steps, it randomly reads some pixel of the current step and some of the previous step instead of only from the previous step
- Fixes #9353 

## Solution

- Adopted from #9678 
- Added a switch of the texture displayed every frame otherwise the game of life looks wrong
- Added a way to display the texture bigger so that I could manually check everything was right

### CODE REVIEW

File: examples/shader/compute_shader_game_of_life.rs [hunk 1]
```diff
@@ -94,29 +121,93 @@ impl Plugin for GameOfLifeComputePlugin {
...
+                binding: 1,
+                visibility: ShaderStages::COMPUTE,
+                ty: BindingType::StorageTexture {
+                    access: StorageTextureAccess::WriteOnly,
+                    format: TextureFormat::R32Float,
+                    view_dimension: TextureViewDimension::D2,
+                },
+                count: None,
+            },
+        ]
```
Comment (IceSentry) [inline examples/shader/compute_shader_game_of_life.rs:178]:
```suggestion
        vec![
            texture_storage_2d(TextureFormat::R32Float, StorageTextureAccess::ReadOnly)
                .build(0, ShaderStages::COMPUTE),
            texture_storage_2d(TextureFormat::R32Float, StorageTextureAccess::WriteOnly)
                .build(1, ShaderStages::COMPUTE),
        ]
```

You could replace this with those helpers from `BindGroupLayoutEntries`. I just noticed it's not possible to use the full entries api here because you can't get the actual vec of entries easily, so I'll need to fix that.

File: examples/shader/compute_shader_game_of_life.rs [hunk 2]
```diff
@@ -129,7 +204,7 @@ struct GameOfLifePipeline {
 impl FromWorld for GameOfLifePipeline {
     fn from_world(world: &mut World) -> Self {
         let render_device = world.resource::<RenderDevice>();
-        let texture_bind_group_layout = GameOfLifeImage::bind_group_layout(render_device);
+        let texture_bind_group_layout = GameOfLifeImages::bind_group_layout(render_device);
```
Comment (IceSentry) [inline examples/shader/compute_shader_game_of_life.rs:206]: You could remove the entire AsBindGroup impl and use this instead: 
```suggestion
        let texture_bind_group_layout = render_device.create_bind_group_layout(
            "GameOfLifeImages",
            &BindGroupLayoutEntries::sequential(
                ShaderStages::COMPUTE,
                (
                    texture_storage_2d(TextureFormat::R32Float, StorageTextureAccess::ReadOnly),
                    texture_storage_2d(TextureFormat::R32Float, StorageTextureAccess::WriteOnly),
                ),
            ),
        );
```

File: examples/shader/compute_shader_game_of_life.rs [hunk 3]
```diff
@@ -94,29 +121,77 @@ impl Plugin for GameOfLifeComputePlugin {
...
+    let view_a = gpu_images.get(&game_of_life_images.texture_a).unwrap();
+    let view_b = gpu_images.get(&game_of_life_images.texture_b).unwrap();
+    let bind_group_0 = render_device.create_bind_group(
+        None,
+        &pipeline.texture_bind_group_layout,
+        &BindGroupEntries::sequential((
+            BindingResource::TextureView(&view_a.texture_view),
+            BindingResource::TextureView(&view_b.texture_view),
+        )),
+    );
```
Comment (IceSentry) [inline examples/shader/compute_shader_game_of_life.rs:184]:
```suggestion
    let bind_group_0 = render_device.create_bind_group(
        None,
        &pipeline.texture_bind_group_layout,
        &BindGroupEntries::sequential((&view_a.texture_view, &view_b.texture_view)),
    );
```

You don't need to wrap it in a `BindingResource::TextureView`

File: examples/shader/compute_shader_game_of_life.rs [hunk 4]
```diff
@@ -94,29 +121,77 @@ impl Plugin for GameOfLifeComputePlugin {
...
+    let bind_group_1 = render_device.create_bind_group(
         None,
         &pipeline.texture_bind_group_layout,
-        &BindGroupEntries::single(&view.texture_view),
+        &BindGroupEntries::sequential((
+            BindingResource::TextureView(&view_b.texture_view),
+            BindingResource::TextureView(&view_a.texture_view),
+        )),
```
Comment (IceSentry) [inline examples/shader/compute_shader_game_of_life.rs:191]:
```suggestion
        &BindGroupEntries::sequential((&view_b.texture_view, &view_a.texture_view)),
```

File: examples/shader/compute_shader_game_of_life.rs [hunk 5]
```diff
@@ -52,19 +61,37 @@ fn setup(mut commands: Commands, mut images: ResMut<Assets<Image>>) {
...
         sprite: Sprite {
             custom_size: Some(Vec2::new(SIZE.0 as f32, SIZE.1 as f32)),
             ..default()
         },
-        texture: image.clone(),
+        texture: image0.clone(),
+        transform: Transform {
+            scale: Vec3::splat(DISPLAY_FACTOR as f32),
+            ..default()
+        },
```
Comment (IceSentry) [inline examples/shader/compute_shader_game_of_life.rs:75]:
```suggestion
        transform: Transform::from_scale(Vec3::splat(DISPLAY_FACTOR as f32)),
```

**Review by IceSentry — APPROVED** [review]
LGTM

**Review by afonsolage — APPROVED** [review]
