### PR TITLE
Split CursorOptions off of Window

### LINKED ISSUE #19627: Bevy caches invalid cursor settings
## Bevy version

0.16.2

## What you did

Setting the cursor grab mode to `Locked` twice has no effect, as Bevy does not tell winit about this change when the user changes the grab mode to the same value twice.

## What went wrong

There are some situations where Bevy thinks the cursor is in one state, but it is in another. A prime example is https://github.com/bevyengine/bevy/issues/8949. So, I want to force winit to try to lock the cursor again. However, Bevy stops me, as it thinks that the cursor is already locked. Instead, I need to first change the lock mode to a placeholder setting to clear the cache, then use the real setting

### PR DESCRIPTION
**Pull request by janhohenheim**
# Objective

- Fixes #19627 
- Tackles part of #19644 
- Supersedes #19629
- `Window` has become a very very very big component
- As such, our change detection does not *really* work on it, as e.g. moving the mouse will cause a change for the entire window
- We circumvented this with a cache
- But, some things *shouldn't* be cached as they can be changed from outside the user's control, notably the cursor grab mode on  web
- So, we need to disable the cache for that
- But because change detection is broken, that would result in the cursor grab mode being set every frame the mouse is moved
- That is usually *not* what a dev wants, as it forces the cursor to be locked even when the end-user is trying to free the cursor on the browser
  - the cache in this situation is invalid due to #8949

## Solution

- Split `Window` into multiple components, each with working change detection
- Disable caching of the cursor grab mode
  - This will only attempt to force the grab mode when the `CursorOptions` were touched by the user, which is *much* rarer than simply moving the mouse.
- If this PR is merged, I'll do the exact same for the other constituents of `Window` as a follow-up

## Testing

- Ran all the changed examples

### CODE REVIEW

**Review by alice-i-cecile — COMMENTED** [review]
I don't have the bandwidth to immediately review this in detail, but I like this direction. Required components are great here, and working change detection is very desirable!

File: crates/bevy_window/src/lib.rs [hunk 1]
```diff
@@ -76,6 +77,13 @@ pub struct WindowPlugin {
     /// [`exit_on_all_closed`].
     pub primary_window: Option<Window>,
 
+    /// Settings for the cursor on the primary window.
+    ///
+    /// Defaults to `Some(CursorOptions::default())`.
+    ///
+    /// Has no effect if [`WindowPlugin::primary_window`] is `None`.
+    pub primary_cursor_options: Option<CursorOptions>,
```
Comment (janhohenheim) [inline crates/bevy_window/src/lib.rs:85]: I left this in for parity with the existing API, but since it's a required component, we could also omit it and let the user override it in an observer for `OnAdd, PrimaryWindow`

File: crates/bevy_winit/src/system.rs [hunk 2]
```diff
@@ -281,10 +283,12 @@ pub(crate) fn despawn_windows(
 }
 
 /// The cached state of the window so we can check which properties were changed from within the app.
-#[derive(Debug, Clone, Component)]
-pub struct CachedWindow {
-    pub window: Window,
-}
+#[derive(Debug, Clone, Component, Deref, DerefMut)]
+pub(crate) struct CachedWindow(Window);
```
Comment (janhohenheim) [inline crates/bevy_winit/src/system.rs:287]: Making this `pub(crate)` is not breaking, it was already de facto on that visibility.

File: crates/bevy_window/src/lib.rs (hunk 1 above)
Comment (ickshonpe) [inline crates/bevy_window/src/lib.rs:85]: It's a bit tangential but I don't really like how in the window module we use "cursor" to refer to the mouse pointer and in the UI and picking modules we use "pointer". I'd prefer using "pointer" consistently.

**Review by ickshonpe — APPROVED** [review]
Looks good. The changes make sense and I didn't see any problems with any of the examples I tried.

File: crates/bevy_window/src/lib.rs (hunk 1 above)
Comment (janhohenheim) [reply crates/bevy_window/src/lib.rs:85]: That's a very good point. I'll open an issue for unifying terminology later :)

Comment (janhohenheim) [reply crates/bevy_window/src/lib.rs:85]: Done and already resolved: https://github.com/bevyengine/bevy/issues/19688#issuecomment-2978560419

**Comment by alice-i-cecile** [comment]
@janhohenheim ping me when you're ready to try re-merging this.

**Comment by janhohenheim** [comment]
@alice-i-cecile now :)
