### PR TITLE
Fix phantom key presses in winit on focus change (#13299)

### LINKED ISSUE #13299: Phantom key presses on window focus change (alt+tab, etc)
## Bevy version

0.13.2

## Relevant system information

ArchLinux with i3wm window manager alongside KDE using X11

## What you did

I press Alt+Tab to change focus to my bevy application.

## What went wrong

I expected this to change focus to my application, and nothing else.

What happend: It caused a key press event of the TAB key and triggered the application action associated with the TAB key.

This happens with any key that is used for focus switching. For example, if I use my window manager's "alt+w" key binding to switch to the workspace of the game, it registers as a key press of the "w" key, which causes my character to unintentionally move forward.

Worse yet, those keys get stuck in a "permanently pressed" state, triggering the actions forever, until I press the respective key once again.

This is driving me crazy as I switch focus back/forth between my bevy application a lot.

## Additional information / Cause

This is caused by bevy erroneously interpreting winit's "synthetic" key presses as real key presses.

If I add a check for [is_synthetic](https://docs.rs/winit/0.30.0/winit/event/enum.WindowEvent.html#variant.KeyboardInput.field.is_synthetic) in [bevy's winit KeyboardInput event handler](https://github.com/bevyengine/bevy/blob/aa80e2d658ed1b84787fd512839a8c84238979ef/crates/bevy_winit/src/lib.rs#L447):

```rust
WindowEvent::KeyboardInput { ref event, is_synthetic, .. } => {
    if !is_synthetic {
        if event.state.is_pressed() {
            if let Some(char) = &event.text {
                let char = char.clone();
                app.send_event(ReceivedCharacter { window, char });
            }
        }
        app.send_event(converters::convert_keyboard_input(event, window));
    }
}
```

then the phantom key press events disappear in my application.

This is likely not the full solution though. While the phantom key **press** events are a clear bug, the phantom key **release** events might serve a purpose and possibly should be exposed. See https://github.com/rust-windowing/winit/issues/3543#issuecomment-1973024673

If you decide to not filter out synthetic keys, please at least expose the fact that they are synthetic to the user so we can filter them out ourselves. This would be suboptimal solution, but better than nothing.

- Relevant winit example: [control_flow](https://github.com/rust-windowing/winit/blob/ab33fb8eda45f9a23587465d787a70a309c67ec4/examples/control_flow.rs) (or any other that responds to key presses)
- Relevant bevy example: [keyboard_input_events](https://github.com/bevyengine/bevy/blob/d9d305dab5b3b7a12a634ea7adb5c5a4c6406ec1/examples/input/keyboard_input_events.rs)
- Relevant winit bug report: https://github.com/rust-windowing/winit/issues/3691
- Relevant winit discussion: https://github.com/rust-windowing/winit/issues/3543

If I can help in any way with solving this, don't hesitate to ask.

Thank you.

P.S. here's an analogous fix in another UI framework: https://github.com/lapce/floem/pull/387

### PR DESCRIPTION
**Pull request by hut**
# Objective

Fixes #13299

On Linux/X11, changing focus into a winit window will produce winit KeyboardInput events with a "is_synthetic=true" flag that are not intended to be used. Bevy erroneously passes them on to the user, resulting in phantom key presses.

## Solution

This patch properly filters out winit KeyboardInput events with "is_synthetic=true".

For example, pressing Alt+Tab to focus a bevy winit window results in a permanently stuck Tab key until the user presses Tab once again to produce a winit KeyboardInput release event. The Tab key press event that causes this problem is "synthetic", should not be used according to the winit devs, and simply ignoring it fixes this problem.

Synthetic key **releases** are still evaluated though, as they are essential for correct release key handling. For example, if the user binds the key combination Alt+1 to the action "move the window to workspace 1", places the bevy game in workspace 2, focuses the game and presses Alt+1, then the key release event for the "1" key will be synthetic. If we would filter out all synthetic keys, the bevy game would think that the 1 key remains pressed forever, until the user manually presses+releases the key again inside bevy.

Reference: https://docs.rs/winit/0.30.0/winit/event/enum.WindowEvent.html#variant.KeyboardInput.field.is_synthetic
Relevant discussion: https://github.com/rust-windowing/winit/issues/3543

## Testing

Tested with the "keyboard_input_events" example. Entering/exiting the window with various keys, as well as changing its workspace, produces the correct press/release events.

### CODE REVIEW

File: crates/bevy_winit/src/state.rs [hunk 1]
```diff
@@ -223,16 +223,22 @@ impl<T: Event> ApplicationHandler<T> for WinitAppRunnerState<T> {
...
-                    if let Some(char) = &event.text {
-                        let char = char.clone();
-                        #[allow(deprecated)]
-                        self.winit_events.send(ReceivedCharacter { window, char });
+            WindowEvent::KeyboardInput {
+                ref event,
+                is_synthetic,
+                ..
+            } => {
+                if !(is_synthetic && event.state == ElementState::Pressed) {
```
Comment (alice-i-cecile) [inline crates/bevy_winit/src/state.rs:231]: The check here and immediately below about whether the event state is pressed seem redundant to me.

**Comment by alice-i-cecile** [comment]
I think we should do this! Those docs should be clearer though; lemme make a PR. There seems to be a minor redundancy in your code, but once that's cleared up it LGTM.

**Comment by hut** [comment]
I added a call to is_pressed() instead of comparing to ElementState::Pressed, is shorter and avoids an import.

And the ifs do seem redundant, but I stared long at the code and can't see a way to eliminate the duplicate check for is_pressed() though, because statement A uses an AND operation on the two conditions, and statement B uses an OR operation, see below:

```rust
// if !synthetic || !pressed
if !(is_synthetic && event.state.is_pressed()) {
    // if !synthetic && pressed
    if event.state.is_pressed() { // "Statement A"
        if let Some(char) = &event.text {
            let char = char.clone();
            #[allow(deprecated)]
            self.winit_events.send(ReceivedCharacter { window, char });
        }
    }
    // if !synthetic || !pressed
    self.winit_events // "Statement B"
        .send(converters::convert_keyboard_input(event, window));
}
```

The best I can think of is to store the result of event.state.is_pressed() in a variable to avoid computing it twice. Is that what you mean? Though I figure the rust compiler would optimize that for us anyway.

Open to suggestions.

**Comment by hut** [comment]
Also I want to say: Thanks so much for working on this! It's been a major pain in the neck for me for months ♥

**Comment by IceSentry** [comment]
How about this? To me that's easier to follow

```rust
if !is_synthetic {
    if event.state.is_pressed() {
        if let Some(char) = &event.text {
            let char = char.clone();
            #[allow(deprecated)]
            self.winit_events.send(ReceivedCharacter { window, char });
        }
    } else {
        self.winit_events.send(converters::convert_keyboard_input(event, window));
    }
}
```

I have absolutely 0 context but you could also flip is_synthetic to early return if that's in a function.

**Comment by IceSentry** [comment]
I think this would work?

```rust
match (is_synthetic, event.state.is_pressed()) {
    (false, true) => {
        if let Some(char) = &event.text {
            let char = char.clone();
            #[allow(deprecated)]
            self.winit_events.send(ReceivedCharacter { window, char });
        }
    }
    (false, _) | (_, false) => self
        .winit_events
        .send(converters::convert_keyboard_input(event, window)),
    _ => {}
}
```

**Review by alice-i-cecile — APPROVED** [review]
I think I like the match solution better, but this is fine to merge and a good fix.

**Comment by IceSentry** [comment]
And final one

```rust
        if !is_synthetic && event.state.is_pressed()) {
            if let Some(char) = &event.text {
                let char = char.clone();
                #[allow(deprecated)]
                self.winit_events.send(ReceivedCharacter { window, char });
            }
        } else if !synthetic || !event.state.is_pressed() {
            self.winit_events.send(converters::convert_keyboard_input(event, window)); 
        }
```

This might be abit clearer in this case, and the is_pressed is cheap enough to not matter

**Comment by alice-i-cecile** [comment]
> Also, I'm not sure why there's an allow(deprecated) in there. If you remove that and do the char.clone() in the send() it becomes one line

`ReceivedCharacter` is currently deprecated.

**Comment by hut** [comment]
@IceSentry careful, your variants change the logic. Note that there is no `else` before statement B in the original code. The code using `match`, as well as the "final one" with the `else if` will only run EITHER statement A OR statement B.

But there is a case where *both* statements should be run: When `!is_synthetic && event.state.is_pressed()`.

Your "final" variant can easily be fixed by removing the `else`. But I think `match` won't work here.

-----

But let me outline the reasoning behind my own variant. I think there's value in separating the "quirky" handling of synthetic key press events from the original, "normal" code that handles key presses. The first line:

```rust
if !(is_synthetic && event.state.is_pressed()) {
```

is basically saying: "If it's a synthetic key press, don't do anything at all."

This is the main idea of the patch. To discard synthetic key presses. IMO it should be made clear that we are working around something quirky, rather than mixing the quirk-handling with our "normal" logic.

Everything inside this "if" is just the same code as before the patch.

I have just added some comments, perhaps this makes it more clear:

```rust
// Winit sends "synthetic" key press events when the window gains focus. These
// should not be handled, so we only process key events if they are not synthetic
// key presses. "synthetic" key release events should still be handled though, for
// properly releasing keys when the window loses focus.
if !(is_synthetic && event.state.is_pressed()) {
    // Process the keyboard input event, as long as it's not a synthetic key press.
    if event.state.is_pressed() {
        if let Some(char) = &event.text {
            let char = char.clone();
            #[allow(deprecated)]
            self.winit_events.send(ReceivedCharacter { window, char });
        }
    }
    self.winit_events
        .send(converters::convert_keyboard_input(event, window));
}
```

Eventually, [winit will probably remove this quirkiness](https://github.com/rust-windowing/winit/issues/3543) and we can simply delete the `if !is_synthetic_key_press {` line to restore normality.

**Comment by hut** [comment]
Let's merge this? @IceSentry @alice-i-cecile

**Comment by alice-i-cecile** [comment]
Needs a second review; I'll ask around :)

**Review by kristoff3r — APPROVED** [review]
LGTM
