### PR TITLE
Move `WindowPlugin` exit systems to `Last`

### LINKED ISSUE #11874: Window despawns before `PostUpdate`
## Bevy version

main (https://github.com/bevyengine/bevy/commit/1d5388eded1f999d7bfca0bea40011a1f60fac76)

## What you did

Create a system that queries for `Window` in the `PostUpdate` system

## What went wrong

This line right here in `WindowPlugin`:
https://github.com/bevyengine/bevy/blob/1d5388eded1f999d7bfca0bea40011a1f60fac76/crates/bevy_window/src/lib.rs#L126

The system that despawns the window entity runs during the `Update` system, this means there could be a situation where the window entity does not exist during the `PostUpdate` schedule. This happened to me and it caused a panic.

## Additional information

This could be solved by putting the `close_when_requested` system in the `Last` or `PostUpdate` schedules instead. I don't know which is better though.

### PR DESCRIPTION
**Pull request by doonv**
# Objective

Fix #11874.

## Solution

Old me said that he had problems fixing this, but I just changed the exit systems to `Last` and I have encountered no issues.

## Testing

CI passes.
I ran several examples including `multiple_windows` and I did the same changes to 0.18.1 and tested it with my library, I found no errors while closing the window in both cases.

### CODE REVIEW

File: crates/bevy_window/src/system.rs [hunk 1]
```diff
@@ -3,6 +3,11 @@ use crate::{ClosingWindow, PrimaryWindow, Window, WindowCloseRequested};
 use bevy_app::AppExit;
 use bevy_ecs::prelude::*;
 
+/// A [`SystemSet`] for the system that exits the application.
+/// Which can be either [`exit_on_all_closed`] or [`exit_on_primary_closed`].
+#[derive(SystemSet, Debug, Clone, PartialEq, Eq, Hash)]
+pub struct ExitSystem;
```
Comment (shunkie) [inline crates/bevy_window/src/system.rs]:
```suggestion
pub struct ExitSystems;
```
Currently, almost all implementations of `SystemSet` in Bevy have the Systems suffix.

**Review by xremming — APPROVED** [review]

**Comment by hymm** [comment]
What platform did you test on? Has this been tested on other os's?

**Review by hukasu — APPROVED** [review]

**Comment by doonv** [comment]
> What platform did you test on? Has this been tested on other os's?

I personally tested on Arch Linux. But GitHub actions also tested on Windows and MacOS.
