### PR TITLE
Don't consider despawns as invalidating `EntityWorldMut`

### LINKED ISSUE #19828: Hooks and observers that run on spawn and immediately despawn their entity are unsound
## Bevy version

0.16.1 and main branch

## What you did

Attempted to despawn an entity from an insert hook, which triggered a debug panic in `EntityWorldMut::new`. For example:

```rust
use bevy::ecs::{
    component::{Component, HookContext},
    world::{DeferredWorld, World},
};

#[derive(Component)]
#[component(on_insert = on_insert_a)]
struct A;

fn on_insert_a(mut world: DeferredWorld, HookContext { entity, .. }: HookContext) {
    // This causes a panic in debug builds, but not in release builds.
    world.commands().entity(entity).despawn();
}

fn main() {
    let mut world = World::new();
    world.spawn(A);
}
```

## What went wrong

When an entity is immediately despawned by a hook or observer, this flush in `World::spawn_with_caller`:
https://github.com/bevyengine/bevy/blob/479c93d72bb8de9b13de8989b3d8b09ff1ce132e/crates/bevy_ecs/src/world/mod.rs#L1182-L1185

Invalidates this safety guarantee a few lines later:
https://github.com/bevyengine/bevy/blob/479c93d72bb8de9b13de8989b3d8b09ff1ce132e/crates/bevy_ecs/src/world/mod.rs#L1187-L1188

### PR DESCRIPTION
**Pull request by ElliottjPierce**
# Objective

#19451 changed how entities handle spawning and despawning. 
One of those changes introduced the idea that despawning an entity from commands while holding an `EntityWorldMut` of that entity made that `EntityWorldMut` invalid and panicked when that happend.

Fixes #19828.

## Solution

Handle these despawns in the same way as despawning without freeing.
This means an `EntityWorldMut` can no longer assume its `EntityId` is valid; 
it can not assume that its generation is up to date.
AFAIK, this restriction doesn't introduce any new or exciting ways for this to fail.
It just delays the panics for some cases.
For example, despawning from commands and then attempting an insert will panic later (at the insert) instead of earlier (at the despawn).

## Testing

- CI

### CODE REVIEW

**Comment by ElliottjPierce** [comment]
This might also mean we could revert #22437, but there are other reasons to keep it.

**Comment by mgi388** [comment]
@ElliottjPierce FYI here are the unit tests I had from investigation (I think more or less the same idea as your PR). I had an observer test as well as a hook one but I am not sure if you need both so I will leave that with you:

```rust
/// Tests that inserting a component with a hook that queues a despawn
/// command doesn't panic in `update_location`. Instead, the entity should
/// be marked as despawned and subsequent operations can check
/// `is_despawned()`.
#[test]
fn insert_with_hook_that_despawns_entity_does_not_panic() {
    #[derive(Component)]
    #[component(on_add = on_add_despawn)]
    struct DespawnOnAdd;

    fn on_add_despawn(mut world: DeferredWorld, context: HookContext) {
        // Queue a despawn command that will run during flush().
        world.commands().entity(context.entity).despawn();
    }

    let mut world = World::new();

    // Spawn an entity and then insert a component that will despawn it via
    // a hook.
    let entity = world.spawn_empty().id();

    // Get an EntityWorldMut and insert the component.
    let mut entity_mut = world.entity_mut(entity);
    entity_mut.insert(DespawnOnAdd);

    // The entity should now be marked as despawned.
    assert!(entity_mut.is_despawned());

    // Verify the entity is actually gone from the world.
    assert!(world.get_entity(entity).is_err());
}

/// Tests that inserting a component with an observer that queues a despawn
/// command doesn't panic in `update_location`.
#[test]
fn insert_with_observer_that_despawns_entity_does_not_panic() {
    #[derive(Component)]
    struct TriggerDespawn;

    let mut world = World::new();

    // Add an observer that despawns the entity when TriggerDespawn is
    // added.
    world.add_observer(|add: On<Add, TriggerDespawn>, mut commands: Commands| {
        commands.entity(add.event_target()).despawn();
    });

    // Spawn an entity and then insert a component that will despawn it via
    // observer.
    let entity = world.spawn_empty().id();

    // Get an EntityWorldMut and insert the component.
    let mut entity_mut = world.entity_mut(entity);
    entity_mut.insert(TriggerDespawn);

    // The entity should now be marked as despawned.
    assert!(entity_mut.is_despawned());

    // Verify the entity is actually gone from the world.
    assert!(world.get_entity(entity).is_err());
}
```

~And the diff for Bevy 0.18 (main is now slightly different I believe):~ Edit: Actually I didn't use `get_spawned` so mine could be wrong.

```diff
diff --git a/crates/bevy_ecs/src/world/entity_access/world_mut.rs b/crates/bevy_ecs/src/world/entity_access/world_mut.rs
index b8a816d84..dc0cd24e3 100644
--- a/crates/bevy_ecs/src/world/entity_access/world_mut.rs
+++ b/crates/bevy_ecs/src/world/entity_access/world_mut.rs
@@ -1801,9 +1801,11 @@ impl<'w> EntityWorldMut<'w> {
     ///
     /// This is *only* required when using the unsafe function [`EntityWorldMut::world_mut`],
     /// which enables the location to change.
+    ///
+    /// If the entity was despawned (e.g., by a command that ran during a flush), this will
+    /// set the location to `None`, which can be checked via [`EntityWorldMut::is_despawned`].
     pub fn update_location(&mut self) {
-        self.location = self.world.entities().get(self.entity)
-            .expect("Attempted to update the location of a despawned entity, which is impossible. This was the result of performing an operation on this EntityWorldMut that queued a despawn command");
+        self.location = self.world.entities().get(self.entity).ok().flatten();
     }

     /// Returns if the entity has been despawned.
```

**Comment by mgi388** [comment]
Actually I didn't use `get_spawned` so mine could be wrong.

**Comment by grind086** [comment]
This also looks like it fixes #19828 (unless it was already fixed?)

**Comment by ElliottjPierce** [comment]
> This also looks like it fixes #19828 (unless it was already fixed?)

This just made things more exciting! Yeah, this should fix that now. I just added some checks to make sure bundle affects respect that the entity might not be spawned.

File: crates/bevy_ecs/src/world/entity_access/world_mut.rs [hunk 1]
```diff
@@ -1813,9 +1836,11 @@ impl<'w> EntityWorldMut<'w> {
     ///
     /// This is *only* required when using the unsafe function [`EntityWorldMut::world_mut`],
     /// which enables the location to change.
+    ///
+    /// Note that if the entity is not spawned for any reason,
+    /// this will have a location of `None`, leading some methods to panic.
     pub fn update_location(&mut self) {
-        self.location = self.world.entities().get(self.entity)
-            .expect("Attempted to update the location of a despawned entity, which is impossible. This was the result of performing an operation on this EntityWorldMut that queued a despawn command");
+        self.location = self.world.entities().get_spawned(self.entity).ok();
```
Comment (chescock) [inline crates/bevy_ecs/src/world/entity_access/world_mut.rs:1835]: I agree that this restores the original behavior!  

Combining this diff with [the one in #19451](https://github.com/bevyengine/bevy/pull/19451/changes#diff-552c55aa6414cab3b9bd36c78c849e4874e7adaa74b99f6bacf7cc39fdd086e4R1707) gives

```diff
-        self.location = self.world.entities().get(self.entity);
+        self.location = self.world.entities().get_spawned(self.entity).ok();
```

It looks like that PR changed all the `get` calls other than this one to `get_spawned`, so the new code here is consistent with everything else.  

The only difference in this PR is the behavior if the entity has the wrong generation, and the old `get` method returned `None` there, so using `None` again now should restore the original behavior.

File: crates/bevy_ecs/src/world/entity_access/world_mut.rs [hunk 2]
```diff
@@ -1540,6 +1558,11 @@ impl<'w> EntityWorldMut<'w> {
     /// This returns the new [`Entity`], which you must manage.
     /// Note that this still increases the generation to differentiate different spawns of the same row.
     ///
+    /// Additionally, keep in mind the limitations documented in the type-level docs.
+    /// Unless you have full knowledge of this [`EntityWorldMut`]'s lifetime,
+    /// you may not assume that nothing else has taken responsibility of this [`Entity`].
+    /// If you are not careful, this could cause a double free.
```
Comment (chescock) [inline crates/bevy_ecs/src/world/entity_access/world_mut.rs:1556]: How can this cause a double free?  This method consumes the `EntityWorldMut` by value, so I would think the caller *would* have full knowledge of the lifetime.

File: crates/bevy_ecs/src/spawn.rs [hunk 3]
```diff
@@ -336,12 +336,16 @@ impl<R: Relationship, L: SpawnableList<R>> DynamicBundle for SpawnRelatedBundle<
         // SAFETY: The value was not moved out in `get_components`, only borrowed, and thus should still
         // be valid and initialized.
         let effect = unsafe { ptr.assume_init() };
+        bevy_ptr::deconstruct_moving_ptr!({
```
Comment (chescock) [inline crates/bevy_ecs/src/spawn.rs:339]: Why did you move this call outside of the `world_scope`?  

I think it's a no-op pointer cast, so it's not a big deal either way.

File: crates/bevy_ecs/src/bundle/mod.rs [hunk 4]
```diff
@@ -287,6 +287,8 @@ pub trait DynamicBundle: Sized {
     ///  - If any part of `ptr` is to be accessed in this function, it must *not* be dropped at any point in
     ///    `get_components`. Calling [`bevy_ptr::deconstruct_moving_ptr`] in `get_components` automatically
     ///    ensures this is the case.
+    ///  - Note that `entity` may already have been despawned by hooks or observers at this point,
```
Comment (chescock) [inline crates/bevy_ecs/src/bundle/mod.rs:290]: Oh, nobody is ever going to remember to check this :).  

I wonder whether we want a rule that we just skip bundle effects if a hook or observer despawns an entity.  Then we could do the check once in the engine and it would be solved everywhere.  But maybe there are use cases where we'd still want effects to run?  

Or maybe we want to pass an `Option<&mut EntityWorldMut>` to make it more obvious that it's a case they have to handle?  Oh, but then they don't have access to the world anymore, so I guess it would need to be some kind of `Result<&mut EntityWorldMut, SomethingElseWithTheDataYouNeed>`, which starts getting kind of ridiculous.  

Or maybe it just doesn't matter, since third-party bundle effects are supposed to be pretty rare.  

Either way, this seems like the right change for now!

File: crates/bevy_ecs/src/world/entity_access/world_mut.rs [hunk 5]
```diff
@@ -39,6 +39,25 @@ use core::{any::TypeId, marker::PhantomData, mem::MaybeUninit};
...
+/// You can check this via [`is_despawned`](Self::is_despawned).
+/// Using an [`EntityWorldMut`] of a despawned entity may panic in some contexts, so read method documentation carefully.
+///
+/// If this points to a not spawned entity (see [`EntityNotSpawnedError`](crate::entity::EntityNotSpawnedError)),
+/// this has no way of knowing why it is not spawned or its "unspawned state".
+/// For example, if the entity is not spawned, this will not know if that is because the entity is not yet spawned or if it was spawned and was later despawned.
+/// If it was despawned, this can not know who was responsible to free the [`Entity`].
+/// Further, the [`Entity`] this points to may no longer be valid;
+/// its [`EntityGeneration`](crate::entity::EntityGeneration) may not be up to date.
+/// Keep these limitations in mind when use this type in the context of unknown code.
```
Comment (chescock) [inline crates/bevy_ecs/src/world/entity_access/world_mut.rs]: I don't think I understand what this paragraph is trying to teach me.  

I understand the first and last paragraphs: If I didn't just get the `EntityWorldMut` from the world, I should call `is_despawned` or accept that I might get panics.  

The middle paragraph is telling me that `EntityWorldMut` can't distinguish not-spawned-yet from spawned-then-despawned entities, but I guess I don't know why I would *need* to distinguish those for the sorts of things I'd use this type for.

File: crates/bevy_ecs/src/world/entity_access/world_mut.rs (hunk 2 above)
Comment (ElliottjPierce) [reply crates/bevy_ecs/src/world/entity_access/world_mut.rs:1556]: What if this is called from a hook or something? The caller needs to know that nothing else has freed the entity. If the entity was still spawned before this call, that's trivial to satisfy. But if not, the caller needs to know that nothing in a "on remove" hook or something already despawned the entity and freed the entity. This is why we still need those extra checks in `despawn`. 

This *is* confusing, and it's one of those edge cases this introduces. We might need a better way of communicating this.

File: crates/bevy_ecs/src/spawn.rs (hunk 3 above)
Comment (ElliottjPierce) [reply crates/bevy_ecs/src/spawn.rs:339]: I moved it out to make sure it was dropped even when the entity was not spawned. But I'm no expert with these pointer types. Maybe it's unnecessary?

File: crates/bevy_ecs/src/bundle/mod.rs (hunk 4 above)
Comment (ElliottjPierce) [reply crates/bevy_ecs/src/bundle/mod.rs:290]: Yeah. I agree that an option or result would be nice, but then, it would be nice everywhere that uses `EntityWorldMut`, so...

And I don't think we can skip this when the entity is despawned because the safety requirements say this must be called.

File: crates/bevy_ecs/src/world/entity_access/world_mut.rs (hunk 5 above)
Comment (ElliottjPierce) [reply crates/bevy_ecs/src/world/entity_access/world_mut.rs]: Yeah, this is not useful to 90% of users, but for people using `spawn_at` in hooks maybe or if they are freeing entities themselves, this is important to note. 

For example, let's say in response to a spawn, an observer despawns the entity without freeing it, then spawns a new entity at the same id. And lets say that during that `despawn_no_free`, another hook runs and sees that it is not spawned. That hook can not assume that this is because the entity was despawned. In this case, it is just not yet spawned because of the `spawn_at` that's going to happen right after. So the hook couldn't say "I guess the entity is despawned, let's queue a command to do some clean up work." If it did, it would be cleaning up the newly spawned entity, which is still there.

These are really tricky edge cases that this introduces. It's probably fine though. It won't affect most users; just has some super strange implications for some super specific cases. I can't think of a way this would actually affect users, but who knows.

File: crates/bevy_ecs/src/world/entity_access/world_mut.rs (hunk 2 above)
Comment (chescock) [reply crates/bevy_ecs/src/world/entity_access/world_mut.rs:1556]: > What if this is called from a hook or something?

I think hooks only have `&mut EntityWorldMut`, so they can't call `despawn_no_free(self)`.  They can use `reborrow_scope` to get a nested `EntityWorldMut`... but that updates `location` on the original `&mut EntityWorldMut` when the scope returns, so it would get set to `None` and everything else would panic.  

... Oh, wait, no, `despawn_no_free_with_caller` *doesn't* panic if the location is invalid.  So if you `despawn_no_free` inside of a `reborrow_scope` and *again* outside of the scope, then it will return the same `Entity` twice.  

Maybe `despawn_no_free` should return a `Result`, and not give you back the `Entity` if the entity had already been despawned?  Anyway, that's outside of the scope of this PR.

File: crates/bevy_ecs/src/spawn.rs (hunk 3 above)
Comment (chescock) [reply crates/bevy_ecs/src/spawn.rs:339]: > I moved it out to make sure it was dropped even when the entity was not spawned. But I'm no expert with these pointer types. Maybe it's unnecessary?

I believe it's unnecessary.  But it's also harmless!  

The goal for `deconstruct_moving_ptr!` is to work exactly like ordinary destructuring.  Dropping a `MovingPtr` will call the destructor on the owned type, so in one case we drop the whole `SpawnRelatedBundle` and in the other case we drop the individual fields, which amounts to the same thing.

File: crates/bevy_ecs/src/world/entity_access/world_mut.rs (hunk 5 above)
Comment (chescock) [reply crates/bevy_ecs/src/world/entity_access/world_mut.rs]: > For example, let's say in response to a spawn, an observer despawns the entity without freeing it, then spawns a new entity at the same id. And lets say that during that `despawn_no_free`, another hook runs and sees that it is not spawned. That hook can not assume that this is because the entity was despawned. In this case, it is just not yet spawned because of the `spawn_at` that's going to happen right after. So the hook couldn't say "I guess the entity is despawned, let's queue a command to do some clean up work." If it did, it would be cleaning up the newly spawned entity, which is still there.

Ow.  I hope nobody is trying to do that!  

I think that example might actually work fine if the first hook queued both the `despawn_no_free` and `spawn_at`.  The `despawn_no_free` would flush commands from the second hook before returning, so the new entity wouldn't exist yet and wouldn't get mistakenly cleaned up.  You have to be a little bit more evil, and have a *despawn hook* queue the respawn.  That way, you can have the command to respawn the entity run in between the cleanup hook and its commands!

Comment (ElliottjPierce) [reply crates/bevy_ecs/src/world/entity_access/world_mut.rs]: Yeah, it would take some serious effort to break this, but it's not impossible.

Comment (chescock) [reply crates/bevy_ecs/src/world/entity_access/world_mut.rs]: > That way, you can have the command to respawn the entity run in between the cleanup hook and its commands!

... oh, wait, no, that's still fine, because `despawn_no_free` still increments the generation.  The `EntityIndex` is re-used, but the original `Entity` will still appear despawned, right?  

> These are really tricky edge cases that this introduces. It's probably fine though. It won't affect most users; just has some super strange implications for some super specific cases. I can't think of a way this would actually affect users, but who knows.

I guess my point is that if we can't actually tell users how it will affect them, or what they should do to handle those cases, then it might be more clear to just leave this paragraph out :).

Comment (ElliottjPierce) [reply crates/bevy_ecs/src/world/entity_access/world_mut.rs]: Honestly fair. I'll remove it.
