### PR TITLE
Fix runtime required components not registering correctly

### LINKED ISSUE #16406: Runtime required components do not work correctly for components added through `#[require(...)]`
## Bevy version

Bevy 0.15.0-rc.3

## What you did

I have a component, let's say `A`, that requires another component `B` using `#[require(B)]`. `B` then requires another component `C`, but the requirement is registered in a plugin using `app.register_required_components::<B, C>()`.

## What went wrong

When I spawn an entity with `A`, `C` is not added!

Here's a simple test that fails:

```rust
#[test]
fn runtime_required_components() {
    // `A` requires `B` directly.
    #[derive(Component)]
    #[require(B)]
    struct A;

    #[derive(Component, Default)]
    struct B;

    #[derive(Component, Default)]
    struct C;

    let mut world = World::new();

    // `B` requires `C` with runtime registration.
    // This *fails*, but not when using `#[require(C)]` for `B`.
    world.register_required_components::<B, C>();

    // Adding runtime registration for `A -> B` also doesn't help if done after `B -> C`,
    // but it *does* work if done before.
    let _ = world.try_register_required_components::<A, B>();

    let entity = world.spawn(A).id();
    assert!(world.entity(entity).get::<C>().is_some());
}
```

If the entity is spawned with `B` directly, it *does* work:

```rust
#[test]
fn runtime_required_components_2() {
    #[derive(Component)]
    #[require(B)]
    struct A;

    #[derive(Component, Default)]
    struct B;

    #[derive(Component, Default)]
    struct C;

    let mut world = World::new();

    world.register_required_components::<B, C>();

    let _ = world.try_register_required_components::<A, B>();

    let id = world.spawn(B).id();
    assert!(world.entity(id).get::<C>().is_some());
}
```

This implies that the problem is related to runtime requirements not being properly propagated up the inheritance tree if the higher levels use `#[require(...)]`, or if the higher level requirement is added after the lower level requirement.

### PR DESCRIPTION
**Pull request by andriyDev**
# Objective

- Fixes #16406 
- Fixes an issue where registering a "deeper" required component, then a "shallower" required component, would result in the wrong required constructor being used for the root component.

## Solution

- Make `register_required_components` add any "parent" of a component as `required_by` to the new "child".
- Assign the depth of the `requiree` plus 1 as the depth of a new runtime required component.

## Testing

- Added two new tests.

### CODE REVIEW

File: crates/bevy_ecs/src/component.rs [hunk 1]
```diff
@@ -1065,16 +1065,22 @@ impl Components {
...
                 // SAFETY: The component is in the list of required components, so it must exist already.
                 let required_components = unsafe {
                     self.get_required_components_mut(required_by_id)
                         .debug_checked_unwrap()
                 };
 
+                let depth = required_components.0.get(&requiree).expect("requiree is required by required_by_id, so its required_components must include requiree").inheritance_depth;
+
                 // Register the original required component for the requiree.
                 // The inheritance depth is `1` since this is a component required by the original requiree.
```
Comment (Jondolf) [inline crates/bevy_ecs/src/component.rs:1082]: This comment is now outdated

Comment (andriyDev) [reply crates/bevy_ecs/src/component.rs]: Fixed.

**Review by Jondolf — APPROVED** [review]

**Review by alice-i-cecile — APPROVED** [review]
