### PR TITLE
Warn, not panic, on invalid fonts

### LINKED ISSUE #22475: example system_fonts crashes on macOS and Linux
## Bevy version and features

- main after #22403 

## What you did

`cargo run --example system_fonts`

## What went wrong

crash on macOS:

```
thread 'Compute Task Pool (1)' (628567) panicked at crates/bevy_math/src/rects/rect.rs:100:9:
Rect size must be positive
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Encountered a panic in system `Enable the debug feature to see the name`!

thread 'Compute Task Pool (6)' (628572) panicked at crates/bevy_ui/src/widget/text.rs:378:21:
Fatal error when processing text: failed to get scaled glyph image for cache key: CacheKey { font_id: ID(InnerId(611v1)), glyph_id: 65535, font_size_bits: 1109393408, x_bin: Zero, y_bin: Zero, font_weight: Weight(400), flags: CacheKeyFlags(0x0) }.
```

crash on Linux:

```
thread 'Compute Task Pool (1)' (9642) panicked at crates/bevy_ui/src/widget/text.rs:378:21:
Fatal error when processing text: failed to get scaled glyph image for cache key: CacheKey { font_id: ID(InnerId(1v1)), glyph_id: 3, font_size_bits: 1101004800, x_bin: Zero, y_bin: Zero, font_weight: Weight(400), flags: CacheKeyFlags(0x0) }.
```

### PR DESCRIPTION
**Pull request by ickshonpe**
# Objective

Fix panics due to invalid legacy fonts that we can't generate glyph images from.

Fixes #22475

## Solution
* In `text_system` and `update_text2d_layout`, instead of panicking on `TextError::FailedToGetGlyphImage`, `warn_once` and clear the text layout.

* Given an invalid font, Cosmic Text returns an invalid text layout with infinite text bounds. If Cosmic Text returns non-finite bounds, return a zero size from the `buffer_dimensions` function.

* Added a `get_face_details` method to `CosmicFontSystem` to provide better info for the warning messages.

`buffer_dimensions` probably should be reworked to return a `Result`, with the text systems emitting a warning on invalid layout bounds. Not so important though, left for a follow up.

## Testing

The `system_fonts` example should no longer panic now. Instead the text with the invalid font is not rendered:

system-fonts-list-fixed

One of the problematic fonts:
https://github.com/justrajdeep/fonts/blob/master/NISC18030.ttf

### CODE REVIEW

File: crates/bevy_text/src/pipeline.rs [hunk 1]
```diff
@@ -34,6 +34,83 @@ impl Default for CosmicFontSystem {
     }
 }
 
+impl CosmicFontSystem {
+    /// get information about a font face
```
Comment (alice-i-cecile) [inline crates/bevy_text/src/pipeline.rs]:
```suggestion
    /// Get information about a font face, if it exists
```

**Review by alice-i-cecile — APPROVED** [review]
A small docs nit, but that's easily resolved. I like the font face details a lot: that's a nice little helper regardless.

Eliminating the panic here is good: this doesn't need to be fatal. I'd prefer if other panics here were also reduced (broken fonts don't need to crash the whole application), but that's fine for now.
