### PR TITLE
Fix dragging-over panic

### LINKED ISSUE #21998: Panic when a drag starts over an already hovered entity
## Bevy version and features

Bevy main

## What you did

Run one of these examples and try and drag something:

```
cargo run --example standard_widgets --features="experimental_bevy_ui_widgets"
```

```
cargo run --example ui_drag_and_drop
````

## What went wrong

`picking_events` doesn't add a dragged over entity to the `dragged_over` map in `PointerButtonState` if the drag started with the dragged over entity already hovered . This causes a panic when the pointer is moved and `picking_events` tries to update the `dragging_over` state for the hovered entity.

### PR DESCRIPTION
**Pull request by ickshonpe**
# Objective

Problems:

* If a drag starts over a hovered entity, `picking_events` doesn't add the hovered entity to the `dragging_over` map in `PointerButtonState`. This causes a panic when the pointer is moved and `picking_events` tries to update the non-existant `dragging_over` state for the hovered entity.

* `DragEnter` isn't dispatched on `DragStart`. This doesn't seem ideal. The drag isn't crossing a geometric boundary, but it is causing the dragged over entities to enter into a dragged over state.

Fixes #21998

## Solution

* Update the `dragging_state` for all hovered entities every frame, before handling any `PointerInput`s.
* Reworked the `DragEnter` dispatch logic.  `DragEnter` now also fires when a drag starts over an already hovered entity.

## Testing

The examples using drag events should no longer panic:

```
cargo run --example standard_widgets --features="experimental_bevy_ui_widgets"
```

```
cargo run --example ui_drag_and_drop
````

### CODE REVIEW

File: crates/bevy_picking/src/events.rs [hunk 1]
```diff
@@ -528,31 +528,33 @@ pub fn pointer_events(
...
-                    "Unable to get location for pointer {:?} during pointer over",
-                    pointer_id
-                );
-                continue;
-            };
-
-            // Possibly send DragEnter events
-            for button in PointerButton::iter() {
-                let state = pointer_state.get_mut(pointer_id, button);
+        // Continue if the pointer does not a valid location.
```
Comment (kfc35) [inline crates/bevy_picking/src/events.rs]:
```suggestion
        // Continue if the pointer does not have a valid location.
```

File: crates/bevy_picking/src/events.rs [hunk 2]
```diff
@@ -766,7 +798,6 @@ pub fn pointer_events(
                             .flat_map(|h| h.iter().map(|(entity, data)| (*entity, data.to_owned())))
                             .filter(|(hovered_entity, _)| *hovered_entity != *drag_target)
                         {
-                            *state.dragging_over.get_mut(&hovered_entity).unwrap() = hit.clone();
```
Comment (kfc35) [inline crates/bevy_picking/src/events.rs:774]: So this was the line that caused the panic. Is it valid to delete this line? Is it because it’s redundant now with the logic you put in?

Comment (ickshonpe) [reply crates/bevy_picking/src/events.rs:774]: Yep, this line was a fix for another bug: https://github.com/bevyengine/bevy/issues/21849. It's redundant with this PR as the `dragging_over` states are already updated before the `PointerInput`s are processed.

**Comment by kfc35** [comment]
I checked out the branch and confirmed that the examples listed in the `testing` section no longer panic with drag-and-drops
