### PR TITLE
moved Debug from derive to impl_ptr in bevy_ptr

### LINKED ISSUE #17988: Change #[derive(Debug)] to manual impl for certain bevy_ptr types
## What problem does this solve or what need does it fill?

`#[derive(Debug)]` places incorrect bounds on its debug implementation in certain cases involving generics. In particular, it requires that all generic parameters implement Debug.

This means that the Debug implementations for `Ptr`, `PtrMut` and `OwningPtr` do not function because they require `A: Debug`, and as neither `Aligned` nor `Unaligned` implement Debug, it is impossible to satisfy the trait bounds.

The outcome of this is that the following code:
```rust
#[derive(Debug)]
struct PtrWrapper<'a> {
    ptr: bevy_ptr::Ptr<'a>,
}
```
results in the following error
```
error[E0277]: `Aligned` doesn't implement `Debug`
 --> src/lib.rs:3:5
  |
1 | #[derive(Debug)]
  |          ----- in this derive macro expansion
2 | struct PtrWrapper<'a> {
3 |     ptr: bevy_ptr::Ptr<'a>,
  |     ^^^^^^^^^^^^^^^^^^^^^^ `Aligned` cannot be formatted using `{:?}` because it doesn't implement `Debug`
  |
  = help: the trait `Debug` is not implemented for `Aligned`
  = help: the trait `Debug` is implemented for `Ptr<'_, A>`
  = note: this error originates in the derive macro `Debug` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0277`.
error: could not compile `playground` (lib) due to 1 previous error

```

## What solution would you like?

Implement Debug for the affected types manually by deferring to the Debug implementation on `NonNull`:

```rust
impl core::fmt::Debug for Ptr<'_> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> Result<(), core::fmt::Error> {
        core::fmt::Debug::fmt(self.0, f)
    }
}
```

## What alternative(s) have you considered?

- Users of the library can work around the broken implementation, by manually implementing Debug for their types. (not preferred because it just ignores the problem)
- Use [`derive_more::Debug`](https://docs.rs/derive_more/latest/derive_more/derive.Debug.html), which does not use the incorrect trait bounds. (not preferred because it adds a dependency)

### PR DESCRIPTION
**Pull request by mysteriouslyseeing**
# Objective

Fixes #17988

## Solution

Added two Debug impls to the `impl_ptr` macro - one for Aligned and one for Unaligned.

## Testing

No tests have been added. Would a test guaranteeing debug layout be appropriate?

---

## Showcase

The debug representation of a `Ptr<'_, Aligned>` follows. `PtrMut` and `OwningPtr` are similar.

`Ptr<Aligned>(0x0123456789ab)`

### CODE REVIEW

File: crates/bevy_ptr/src/lib.rs [hunk 1]
```diff
@@ -265,6 +263,19 @@ macro_rules! impl_ptr {
                 Pointer::fmt(&self.0, f)
             }
         }
+
+        impl Debug for $ptr<'_, Aligned> {
```
Comment (MrGVSV) [inline crates/bevy_ptr/src/lib.rs:267]: I’m in favor of the manual implementation, but I feel like we should also derive `Debug` on `Aligned` and `Unaligned`.

This will make it easy for users who define their own generic wrappers to derive `Debug` rather than also needing a manual implementation.

**Review by alice-i-cecile — APPROVED** [review]

File: crates/bevy_ptr/src/lib.rs (hunk 1 above)
Comment (mysteriouslyseeing) [reply crates/bevy_ptr/src/lib.rs:267]: Would it make sense to add most/all of the derives, then? The same issue with derive bounds exists for all std derive macros, IIRC

**Review by MrGVSV — APPROVED** [review]
