### PR TITLE
Make `AppExit` more specific about exit reason.

### LINKED ISSUE #13017: Add `ExitCode` to `AppExit`
> > Is there a way around that? Otherwise I'm not sure if that change is worth it.
>
> Perhaps `AppExit` can be modified to be `AppExit(ExitCode)`, but that's probably worth it's own issue and PR.

_Originally posted by @BD103 in https://github.com/bevyengine/bevy/issues/12305#issuecomment-1987035205_

[On Discord](https://discord.com/channels/691052431525675048/692572690833473578/1230442854304710657), a crash in the render world exits with an exit code of 0, while it should return a number greater than 0.

One solution to this is to add the [`ExitCode`](https://doc.rust-lang.org/stable/std/process/struct.ExitCode.html) struct to `AppExit`, so exiting can specify whether it was a `ExitCode::SUCCESS` (the default) or a `ExitCode::FAILURE`.

### PR DESCRIPTION
**Pull request by Brezak**
# Objective

Closes #13017.

## Solution

- Make `AppExit` a enum with a `Success` and `Error` variant.
- Make `App::run()` return a `AppExit` if it ever returns.
- Make app runners return a `AppExit` to signal if they encountered a error.

---

### Added

- [`App::should_exit`](https://example.org/)
- [`AppExit`](https://docs.rs/bevy/latest/bevy/app/struct.AppExit.html) to the `bevy` and `bevy_app` preludes,

### Changed

- [`AppExit`](https://docs.rs/bevy/latest/bevy/app/struct.AppExit.html) is now a enum with 2 variants (`Success` and `Error`).
- The app's [runner function](https://docs.rs/bevy/latest/bevy/app/struct.App.html#method.set_runner) now has to return a `AppExit`.
- [`App::run()`](https://docs.rs/bevy/latest/bevy/app/struct.App.html#method.run) now also returns the `AppExit` produced by the runner function.

## Migration Guide

- Replace all usages of [`AppExit`](https://docs.rs/bevy/latest/bevy/app/struct.AppExit.html) with `AppExit::Success` or `AppExit::Failure`.
- Any custom app runners now need to return a `AppExit`. We suggest you return a `AppExit::Error` if any `AppExit` raised was a Error. You can use the new [`App::should_exit`](https://example.org/) method.
- If not exiting from `main` any other way. You should return the `AppExit` from `App::run()` so the app correctly returns a error code if anything fails e.g.
```rust
fn main() -> AppExit {
    App::new()
        //Your setup here...
        .run()
}
```

### CODE REVIEW

**Comment by Brezak** [comment]
`AppExit` doesn't contain a [`ExitCode`](https://doc.rust-lang.org/stable/std/process/struct.ExitCode.html) as was suggested as we can't check if they're an error.

File: crates/bevy_app/src/app.rs [hunk 1]
```diff
@@ -862,16 +865,42 @@ fn run_once(mut app: App) {
...
 /// This event can be used to detect when an exit is requested. Make sure that systems listening
 /// for this event run before the current update ends.
-#[derive(Event, Debug, Clone, Default)]
-pub struct AppExit;
+#[derive(Event, Debug, Clone, Default, PartialEq, Eq)]
+pub enum AppExit {
+    /// [`App`] exited without any problems.
+    #[default]
+    Success,
+    /// [`App`] experienced unhandleable error.
```
Comment (alice-i-cecile) [inline crates/bevy_app/src/app.rs:892]:
```suggestion
    /// The [`App`] experienced an unhandleable error.
```

**Comment by alice-i-cecile** [comment]
This design is really nice! I like the approach taken, and the integration with the std::ExitCode is a great idea.

File: crates/bevy_app/src/app.rs [hunk 2]
```diff
@@ -862,16 +865,42 @@ fn run_once(mut app: App) {
...
 /// for this event run before the current update ends.
-#[derive(Event, Debug, Clone, Default)]
-pub struct AppExit;
+#[derive(Event, Debug, Clone, Default, PartialEq, Eq)]
+pub enum AppExit {
+    /// [`App`] exited without any problems.
+    #[default]
+    Success,
+    /// The [`App`] experienced an unhandleable error.
+    Error,
```
Comment (mockersf) [inline crates/bevy_app/src/app.rs:893]: could you make this variant hold a status code, and return it?

Comment (Brezak) [reply crates/bevy_app/src/app.rs:893]: We could. I just don't think it's a good idea. Status codes aren't very standardized e.g. anything above 255 might get trucated on linux (see [`process:exit` platform-specific behaviour](https://doc.rust-lang.org/std/process/struct.ExitCode.html#differences-from-processexit)). The std's solution is [`ExitCode`](https://doc.rust-lang.org/std/process/struct.ExitCode.html#differences-from-processexit) but I don't think letting people produce a `AppExit::Error(ExitCode::Success)` makes much sense.

Comment (mockersf) [reply crates/bevy_app/src/app.rs:893]: then a `NonZeroU8`?

**Comment by Brezak** [comment]
https://github.com/bevyengine/bevy/blob/8db3d1dbfafa34fac2a4121721867d3955b47525/crates/bevy_app/src/app.rs#L865-L867

Regarding this function. I don't know why for example the schedule runner [uses it's own `ManualEventReader`](https://github.com/bevyengine/bevy/blob/8db3d1dbfafa34fac2a4121721867d3955b47525/crates/bevy_app/src/schedule_runner.rs#L85) to keep track of app exit events but I feel like it's important. If anybody could explain why I'd like to add it to the documentation and make `should_exit_manual` the preferred way to check for `AppExit` events.

**Comment by alice-i-cecile** [comment]
Manual event readers are required when working with exclusive world access, such as when `App` is involved. `EventReader` caches a `Local`, so it's trickier to initialize.

We could use one-shot systems these days, but I'm not sure it would be an improvement.

**Comment by Brezak** [comment]
> Manual event readers are required when working with exclusive world access, such as when `App` is involved. `EventReader` caches a `Local`, so it's trickier to initialize.
> 
> We could use one-shot systems these days, but I'm not sure it would be an improvement.

The question is why do our app runners maintain event reader state at all. Both the [`witnit_runner`](https://github.com/bevyengine/bevy/blob/e00effa1e9b4893f89ae3d8af9a87a085a25d2a6/crates/bevy_winit/src/lib.rs#L340) and the [`schedule_runner`](https://github.com/bevyengine/bevy/blob/e00effa1e9b4893f89ae3d8af9a87a085a25d2a6/crates/bevy_app/src/schedule_runner.rs#L85) maintain a `ManualEventReader` between updates. Couldn't we just construct a `ManualEventReader` in-situ. The only reason I see that one would maintain a `ManualEventReader` between updates is to skip already read events, but all our app runners exit immediately a `AppExit` happens in a update. There are no events for them to skip.

File: crates/bevy_app/src/app.rs [hunk 3]
```diff
@@ -862,27 +899,94 @@ fn run_once(mut app: App) {
...
+    Success,
+    /// The [`App`] experienced an unhandleable error.
+    /// Holds the exit code we expect our app to return.
+    Error(NonZeroU8),
+}
+
+impl AppExit {
+    /// Creates a [`AppExit::Error`] with a error code of 1.
+    #[must_use]
+    pub fn error() -> Self {
```
Comment (BD103) [inline crates/bevy_app/src/app.rs:934]:
```suggestion
    pub const fn error() -> Self {
```

File: crates/bevy_app/src/app.rs [hunk 4]
```diff
@@ -862,27 +899,94 @@ fn run_once(mut app: App) {
...
+        Self::Error(NonZeroU8::MIN)
+    }
+
+    /// Returns `true` if `self` is a [`AppExit::Success`].
+    #[must_use]
+    pub fn is_success(&self) -> bool {
```
Comment (BD103) [inline crates/bevy_app/src/app.rs:940]:
```suggestion
    pub const fn is_success(&self) -> bool {
```

File: crates/bevy_app/src/app.rs [hunk 5]
```diff
@@ -862,27 +899,94 @@ fn run_once(mut app: App) {
...
+        matches!(self, AppExit::Success)
+    }
+
+    /// Returns `true` if `self` is a [`AppExit::Error`].
+    #[must_use]
+    pub fn is_error(&self) -> bool {
```
Comment (BD103) [inline crates/bevy_app/src/app.rs:946]:
```suggestion
    pub const fn is_error(&self) -> bool {
```

File: crates/bevy_app/src/app.rs [hunk 6]
```diff
@@ -862,27 +899,94 @@ fn run_once(mut app: App) {
...
+        matches!(self, AppExit::Error(_))
+    }
+
+    /// Creates a [`AppExit`] from a code.
+    ///
+    /// When code is 0 a [`AppExit::Success`] is constructed otherwise a
+    /// [`AppExit::Error`] is constructed.
+    #[must_use]
+    pub fn from_code(code: u8) -> Self {
```
Comment (BD103) [inline crates/bevy_app/src/app.rs:955]:
```suggestion
    pub const fn from_code(code: u8) -> Self {
```

File: crates/bevy_winit/src/lib.rs [hunk 7]
```diff
@@ -350,8 +366,14 @@ fn handle_winit_event(
         }
         runner_state.redraw_requested = true;
 
+        // BEFORE_MERGE(Brezak): Consider replacing after discussion and before pr.
```
Comment (BD103) [inline crates/bevy_winit/src/lib.rs:369]: Adding a comment to this so we don't forget about it :)

File: crates/bevy_winit/src/lib.rs [hunk 8]
```diff
@@ -797,9 +822,16 @@ fn run_app_update_if_should(
             }
         }
 
+        // BEFORE_MERGE(Brezak): Consider replacing after discussion and before pr.
```
Comment (BD103) [inline crates/bevy_winit/src/lib.rs:825]: Same likewise :)

**Review by BD103 — APPROVED** [review]
I'm a big fan of this change, thanks for working on it! I have a few suggestions for making some `AppExit` methods `const`, but they're non-blocking.

The only other thing I want to bring up are the two `BEFORE_MERGE` comments, just so they don't get skipped. :)

**Review by alice-i-cecile — APPROVED** [review]

**Comment by alice-i-cecile** [comment]
Thank you to everyone involved with the authoring or reviewing of this PR! This work is relatively important and needs release notes! Head over to https://github.com/bevyengine/bevy-website/issues/1300 if you'd like to help out.
