### PR TITLE
Fix dof and background motion vectors on webgpu

### LINKED ISSUE #20459: The combination of TAA + SSAO + Skybox is broken on WebGPU
## Bevy version

0.17.0-dev and 0.16.0

## Relevant system information

```ignore
`AdapterInfo { name: "", vendor: 0, device: 0, device_type: Other, driver: "", driver_info: "", backend: BrowserWebGpu }`
```

Running on Google Chrome Version 138.0.7204.168 on Fedora Linux 42, using the Wayland + Vulkan + WebGPU flags

## What you did

```rust
use bevy::{
    anti_aliasing::taa::TemporalAntiAliasing, core_pipeline::Skybox,
    pbr::ScreenSpaceAmbientOcclusion, prelude::*,
};

fn main() {
    App::new()
        .add_plugins(DefaultPlugins)
        .add_systems(Startup, setup)
        .run();
}

fn setup(
    mut commands: Commands,
    mut meshes: ResMut<Assets<Mesh>>,
    mut materials: ResMut<Assets<StandardMaterial>>,
    assets: Res<AssetServer>,
) {
    commands.spawn((
        Mesh3d(meshes.add(Cuboid::default())),
        MeshMaterial3d(materials.add(Color::WHITE)),
    ));

    commands.spawn((
        Camera3d::default(),
        Transform::from_xyz(0.0, 2.0, 10.0).looking_at(Vec3::ZERO, Vec3::Y),
        Msaa::Off,
        // Disable any of the following components to fix the blackscreen on Wasm
        Skybox {
            image: assets.load("textures/Ryfjallet_cubemap_bc7.ktx2"),
            brightness: 800.0,
            ..default()
        },
        ScreenSpaceAmbientOcclusion::default(),
        TemporalAntiAliasing::default(),
    ));
}
```

Then run it on WebGPU using
```bash
bevy run --features bevy/webgpu web
```
and natively using
```bash
bevy run
```

## What went wrong

WebGPU gives me a backscreen:

Image

Native runs fine:

Image

## Additional information

Closeup of logs:

Image

Interestingly, the logs suggest that SSAO is not supported on WebGPU anyways, which would have led me to the belief that SSAO is simply ignored / disabled on WebGPU. Indeed this *seems* to be the case, until we use the combo described above.

### PR DESCRIPTION
**Pull request by beicause**
# Objective

WebGPU-only fix extracted from #22554 and #22555. Fixes #20459

## Solution

Fix normal + motion vector prepass by setting write mask to empty. This is a firefox/wgpu bug that it's not validated https://github.com/gfx-rs/wgpu/issues/9147, but chromium does.

Fix dof with bokeh mode. I guess it's `naga_oil` bug but I'm not sure.

## Testing

I tested dof and skybox examples on web.

### CODE REVIEW

File: crates/bevy_core_pipeline/src/prepass/background_motion_vectors.rs [hunk 1]
```diff
@@ -150,6 +150,11 @@ impl SpecializedRenderPipeline for BackgroundMotionVectorsPipeline {
     type Key = BackgroundMotionVectorsPipelineKey;
 
     fn specialize(&self, key: Self::Key) -> RenderPipelineDescriptor {
+        let mut targets = prepass_target_descriptors(key.normal_prepass, true, false);
+        if let Some(normal) = &mut targets[0] {
```
Comment (eswartz) [inline crates/bevy_core_pipeline/src/prepass/background_motion_vectors.rs]: This makes sense, but looks like a potentially fragile change, since this assumption (that the 0'th entry is the `ColorTargetState` for normals) might change unexpectedly in the future. Perhaps add a line like:
```debug_assert!(normal.format == NORMAL_PREPASS_FORMAT)```
to ensure that any unexpected reordering of the returned vector will be caught in the future?

File: crates/bevy_post_process/src/dof/mod.rs [hunk 2]
```diff
@@ -642,8 +637,8 @@ impl SpecializedRenderPipeline for DepthOfFieldPipeline {
                 entry_point: Some(match key.pass {
                     DofPass::GaussianHorizontal => "gaussian_horizontal".into(),
                     DofPass::GaussianVertical => "gaussian_vertical".into(),
-                    DofPass::BokehPass0 => "bokeh_pass_0".into(),
-                    DofPass::BokehPass1 => "bokeh_pass_1".into(),
+                    DofPass::BokehPass0 => "bokeh_pass_a".into(),
```
Comment (eswartz) [inline crates/bevy_post_process/src/dof/mod.rs]: I saw this from #22554, but the fix doesn't seem to make sense in any case (esp. without renaming the `DofPass` enums to match). Are they still necessary?

**Review by alice-i-cecile — APPROVED** [review]

File: crates/bevy_post_process/src/dof/mod.rs (hunk 2 above)
Comment (eswartz) [inline crates/bevy_post_process/src/dof/mod.rs:642]: It might be good to either rename the `DofPass` enum to match the number -> letter change, or add a comment explaining why they need to differ, as explained in #22554. (I tried reverting the change and saw the mysterious shader build errors you mentioned there.)

**Review by eswartz — COMMENTED** [review]
I ran the two mentioned examples using `bevy run --example {skybox,depth_of_field} -Fwebgpu,free_camera web` under Google Chrome Version 147.0.7727.116 (Official Build) (64-bit) on Linux/X11 with the webgpu options enabled.

They work!

File: crates/bevy_core_pipeline/src/prepass/background_motion_vectors.rs (hunk 1 above)
Comment (beicause) [reply crates/bevy_core_pipeline/src/prepass/background_motion_vectors.rs]: Actually it doesn't matter whether attachment 0 is normal.

Since the shader only outputs to attachment 1, the write masks of other non-None attachments need to be empty.

Comment (eswartz) [reply crates/bevy_core_pipeline/src/prepass/background_motion_vectors.rs]: Interesting. Are you saying that the other write masks need to be reset as well?

If so, I wonder, should `prepass_target_descriptors` accept a `writes_...: bool` argument for the phases that might be writeable or not? 

(That function is `pub` but undocumented. I'm not sure if it's "really" API or just there because of the cross-crate usage rules.)

**Review by eswartz — CHANGES_REQUESTED** [review]
Eep, this consistently generates

```
@ 127.0.0.1:4000/build/skybox.js:3678
 ERROR crates/bevy_render/src/error_handler.rs:114 Caught rendering error: Color target has no corresponding fragment stage output but writeMask (ColorWriteMask::(Red|Green|Blue|Alpha)) is not zero. - While validating targets[0] framebuffer output. - While validating fragment state. - While calling [Device].CreateRenderPipeline([RenderPipelineDescriptor ""background_motion_vectors_pipeline""]).
127.0.0.1:4000/:1 Color target has no corresponding fragment stage output but writeMask (ColorWriteMask::(Red|Green|Blue|Alpha)) is not zero.
 - While validating targets[0] framebuffer output.
 - While validating fragment state.
 - While calling [Device].CreateRenderPipeline([RenderPipelineDescriptor ""background_motion_vectors_pipeline""]).
```

via `bevy  run --example skybox -Fwebgpu,free_camera web`

(`depth_of_field` does work though)

**Review by eswartz — APPROVED** [review]
All better now :)
