### PR TITLE
Pad out binding arrays to their full length if partially bound binding arrays aren't supported.

### LINKED ISSUE #18098: Broken rendering on GPUs that don't support PARTIALLY_BOUND_BINDING_ARRAY
## Bevy version

`73ffd9a508301816a3e4ab8ceaf07daaafa5ec01`

## \[Optional\] Relevant system information

```
2025-03-01T03:35:15.663809Z  INFO bevy_diagnostic::system_information_diagnostics_plugin::internal: SystemInfo { os: "Windows 11 Home", kernel: "26100", cpu: "Intel(R) Core(TM) Ultra 7 155H", core_count: "16", memory: "15.5 GiB" }
2025-03-01T03:35:17.507977Z  INFO bevy_render::renderer: AdapterInfo { name: "Intel(R) Arc(TM) Graphics", vendor: 32902, device: 32085, device_type: IntegratedGpu, driver: "Intel Corporation", driver_info: "101.6458", backend: Vulkan }
```

## What you did

Run 3d_scene example

## What went wrong
```
thread 'Compute Task Pool (11)' panicked at D:\packages\cargo\registry\src\index.crates.io-1949cf8c6b5b557f\wgpu-24.0.1\src\backend\wgpu_core.rs:1187:26:   
wgpu error: Validation Error

Caused by:
  In Device::create_bind_group, label = 'StandardMaterial'
    Binding count declared with exactly 2048 items, but 6 items were provided


note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Encountered a panic in system `bevy_pbr::material::prepare_material_bind_groups<bevy_pbr::pbr_material::StandardMaterial>`!
```

## Additional information

Some kind of rendering code needs to be checking that https://docs.rs/wgpu/latest/wgpu/struct.Features.html#associatedconstant.PARTIALLY_BOUND_BINDING_ARRAY is supported.

### PR DESCRIPTION
**Pull request by pcwalton**
I mistakenly thought that with the wgpu upgrade we'd have `PARTIALLY_BOUND_BINDING_ARRAY` everywhere. Unfortunately this is not the case. This PR adds a workaround back in.

Closes #18098.

### CODE REVIEW

File: crates/bevy_pbr/src/material_bind_groups.rs [hunk 1]
```diff
@@ -1319,14 +1344,21 @@ where
...
                         .iter()
                         .map(|maybe_bindless_binding| match *maybe_bindless_binding {
                             Some(ref bindless_binding) => &bindless_binding.resource,
                             None => &**fallback_sampler,
                         })
                         .collect();
+
+                    if let Some(required_binding_array_size) = required_binding_array_size {
+                        while sampler_bindings.len() < required_binding_array_size as usize {
+                            sampler_bindings.push(&**fallback_sampler);
```
Comment (JMS55) [inline crates/bevy_pbr/src/material_bind_groups.rs:1358]: Using `vec.extend(iter::repeat(fallback).take(n))` will be a little bit clearer here imo.

Comment (pcwalton) [reply crates/bevy_pbr/src/material_bind_groups.rs:1358]: Did the PR work for you?

**Comment by JMS55** [comment]
Didn't work :(

```
2025-03-03T05:38:04.982853Z ERROR wgpu::backend::wgpu_core: Handling wgpu errors as fatal by default    

thread 'Compute Task Pool (6)' panicked at D:\packages\cargo\registry\src\index.crates.io-1949cf8c6b5b557f\wgpu-24.0.1\src\backend\wgpu_core.rs:1187:26:    
wgpu error: Validation Error

Caused by:
  In Device::create_bind_group, label = 'StandardMaterial'
    Binding count declared with exactly 2048 items, but 1 items were provided


note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Encountered a panic in system `bevy_pbr::material::prepare_material_bind_groups<bevy_pbr::pbr_material::StandardMaterial>`!
```

I would also be totally fine with a patch to just disable bindless on systems without PARTIALLY_BOUND_BINDING_ARRAY support.

**Comment by pcwalton** [comment]
Someone who can repro will have to fix it then. Doesn't make sense for me to back and forth.

File: crates/bevy_pbr/src/material_bind_groups.rs (hunk 1 above)
Comment (JMS55) [reply crates/bevy_pbr/src/material_bind_groups.rs:1358]: No, see below comment.

**Comment by JMS55** [comment]
If you want to reproduce on your machine, you can remove PARTIALLY_BOUND_BINDING_ARRAY from the requested device features. Bevy enables everything supported (minus RT and primary mappable buffers) by default, but you can modify that.

File: crates/bevy_pbr/src/material_bind_groups.rs (hunk 1 above)
Comment (pcwalton) [reply crates/bevy_pbr/src/material_bind_groups.rs:1358]: BTW your suggestion isn't quite correct, but I can do what I think you meant.

**Comment by pcwalton** [comment]
Ok, it should work now.

**Review by JMS55 — APPROVED** [review]

**Review by superdump — APPROVED** [review]
