### PR TITLE
Fix alignment on ios simulator

### LINKED ISSUE #10165: iOS 17 mobile example simulator crash.
## Bevy version

v0.12.0-dev(de8a6007b7df5bd961511cd321344157fb4b531f)

## What you did

Try to build the mobile example with XCode and launch it on the simulator.

## What went wrong

It crashed with the next messages:

```
-[MTLDebugRenderCommandEncoder validateCommonDrawErrors:]:5775: failed assertion `Draw Errors Validation
Fragment Function(fragment_): the offset into the buffer _naga_oil_mod_MJSXM6K7OBRHEOR2NVSXG2C7OZUWK527MJUW4ZDJNZTXG_memberfog that is bound at buffer index 6 must be a multiple of 256 but was set to 448.
```

## Additional information

https://github.com/bevyengine/bevy/assets/3709476/6ee2129e-d124-46b7-b247-c6af7b0ed487

### PR DESCRIPTION
**Pull request by mockersf**
# Objective

- Fix #10165 
- On iOS simulator on apple silicon Macs, shader validation is going through the host, but device limits are reported for the device. They sometimes differ, and cause the validation to crash on something that should work
```
-[MTLDebugRenderCommandEncoder validateCommonDrawErrors:]:5775: failed assertion `Draw Errors Validation
Fragment Function(fragment_): the offset into the buffer _naga_oil_mod_MJSXM6K7OBRHEOR2NVSXG2C7OZUWK527MJUW4ZDJNZTXG_memberfog that is bound at buffer index 6 must be a multiple of 256 but was set to 448.
```

## Solution

- Add a custom flag when building for the simulator and override the buffer alignment

### CODE REVIEW

File: examples/mobile/build_rust_deps.sh [hunk 1]
```diff
@@ -48,8 +48,8 @@ for arch in $ARCHS; do
         # Hardware iOS targets
         cargo rustc --crate-type staticlib --lib $RELFLAG --target aarch64-apple-ios
       else
-        # M1 iOS simulator -- currently in Nightly only and requires to build `libstd`
-        cargo rustc --crate-type staticlib --lib $RELFLAG --target aarch64-apple-ios-sim
+        # M1 iOS simulator
+        RUSTFLAGS=--cfg=ios_simulator cargo rustc --crate-type staticlib --lib $RELFLAG --target aarch64-apple-ios-sim
```
Comment (james7132) [inline examples/mobile/build_rust_deps.sh:52]: Not a fan of needing to specify this, since this breaks into the realm of relying on users' development environment configuration, which is notoriously hard to tame and account for. Is there another way around this?

Comment (mockersf) [reply examples/mobile/build_rust_deps.sh:52]: I think the other ways that could work is a manual feature to add to the mobile example, and bubble it to bevy, then bevy_internal, then bevy_render, and enable it when building for the simulator, or a build script. The only difference that I could find when building for the simulator is the target triple is not the same, but that's only exposed to build  scripts.

Comment (robtfm) [reply examples/mobile/build_rust_deps.sh:52]: imo in this particular case it's probably fine. it only affects the simulator, and it should be temporary.

might be nice to add something to the example std-output on ios to declare whether it's enabled or not, just for some extra breadcrumbs.

**Review by robtfm — APPROVED** [review]

**Review by superdump — APPROVED** [review]
@mockersf I think this is fine but up to you if you want to merge or find a better way of dealing with the environment variable.

File: examples/mobile/build_rust_deps.sh (hunk 1 above)
Comment (mockersf) [reply examples/mobile/build_rust_deps.sh:52]: @james7132 is that OK for you? Building for iOS needs custom scripts anyway

Comment (james7132) [reply examples/mobile/build_rust_deps.sh:52]: If it's likely to be temporary and we can't avoid custom build scripts, I'm more OK with it. Just didn't want to unnecessarily complicate the build process.

Comment (james7132) [reply examples/mobile/build_rust_deps.sh:52]: One thing to try if only the target triple changes might be to add a .cargo/config.toml line that adds the flag for that target triple.

https://doc.rust-lang.org/cargo/reference/config.html

Says here that a specific target triple can be used to specify rustc flags.

Comment (mockersf) [reply examples/mobile/build_rust_deps.sh]: that looks better, and it works! thanks

**Review by superdump — APPROVED** [review]

**Comment by superdump** [comment]
@james7132 @mockersf good to merge now?

**Review by james7132 — APPROVED** [review]
