### PR TITLE
Fix lightmaps freeing the wrong slab on removal.

### LINKED ISSUE #20688: Lightmap creation fails with panic index out of bounds in Bevy 0.16+
## Bevy version and features

- Originally seen when I was migrating to Bevy 0.16.
- But I also made a repro for Bevy 0.17-dev/main based off 5df73e138.

## Relevant system information

```
INFO bevy_diagnostic::system_information_diagnostics_plugin::internal: SystemInfo { os: "macOS 15.5 Sequoia", kernel: "24.5.0", cpu: "Apple M1 Max", core_count: "10", memory: "64.0 GiB" }
INFO bevy_render::renderer: AdapterInfo { name: "Apple M1 Max", vendor: 0, device: 0, device_type: IntegratedGpu, driver: "", driver_info: "", backend: Metal }
INFO bevy_render::batching::gpu_preprocessing: GPU preprocessing is fully supported on this device.
INFO bevy_winit::system: Creating new window lightmaps_bug (0v0)
```

## What you did

- I came across the bug in my game by spawning a level.
- Then exiting the level—all level entities and related asset handles are torn down.
- Then load a second level.
- The game crashes.

## What went wrong

Panic:

```
thread '<unnamed>' (569947307) panicked at crates/bevy_pbr/src/lightmap/mod.rs:372:35:
index out of bounds: the len is 2 but the index is 2
stack backtrace:
```

That's https://github.com/bevyengine/bevy/blob/90c5c123c64537dbdef19674676096177cb5acbb/crates/bevy_pbr/src/lightmap/mod.rs#L371-L372.

## Additional information

- I made a repro. I think it's not quite the most minimal repro you could create, but you can reliably use it to repro.
- Drop the code over `lightsmaps.rs` example and run it: `cargo run --example lightmaps`
- Press `SPACE`.
- Then press `A`.
- Then just wait a few moments for the crash. It crashes after the log `Phase 0: Creating 16 lightmaps with SAME asset (cycle 1)`.
- Even though the lightmaps themselves don't look correct in the example, I don't think that is relevant for the underlying bug which is an index out of bounds issue. Happy to be proven wrong here, but I think the meshes I set up are still valid for lightmaps, it's just that they don't _look_ good _at all_.
- When you follow those steps, the output is as follows:

<details>

<summary>Expand to show panic</summary>

```
2025-08-21T05:34:33.265718Z  INFO bevy_diagnostic::system_information_diagnostics_plugin::internal: SystemInfo { os: "macOS 15.5 Sequoia", kernel: "24.5.0", cpu: "Apple M1 Max", core_count: "10", memory: "64.0 GiB" }
2025-08-21T05:34:33.384958Z  INFO bevy_render::renderer: AdapterInfo { name: "Apple M1 Max", vendor: 0, device: 0, device_type: IntegratedGpu, driver: "", driver_info: "", backend: Metal }
2025-08-21T05:34:33.783514Z  INFO bevy_render::batching::gpu_preprocessing: GPU preprocessing is fully supported on this device.
2025-08-21T05:34:33.833472Z  INFO bevy_winit::system: Creating new window lightmaps_bug (0v0)
Creating 12 lightmaps...
Auto-cycle: true
Phase 1: Removing 5 lightmaps
Phase 2: Adding 8 lightmaps with DIFFERENT assets
Phase 3: Removing all lightmaps
Phase 4: Forcing asset cleanup by removing handles
Phase 5: Creating lightmaps after cleanup
Phase 0: Creating 16 lightmaps with SAME asset (cycle 1)

thread '<unnamed>' (569947307) panicked at crates/bevy_pbr/src/lightmap/mod.rs:372:35:
index out of bounds: the len is 2 but the index is 2
stack backtrace:
   0:        0x105af4c7c - std::backtrace_rs::backtrace::libunwind::trace::he513207b4e19acf1
                               at /rustc/2fd855fbfc8239285aa2d596f76a8cc75e17ce02/library/std/src/../../backtrace/src/backtrace/libunwind.rs:117:9
   1:        0x105af4c7c - std::backtrace_rs::backtrace::trace_unsynchronized::h9ef16a62789b800c
                               at /rustc/2fd855fbfc8239285aa2d596f76a8cc75e17ce02/library/std/src/../../backtrace/src/backtrace/mod.rs:66:14
   2:        0x105af4c7c - std::sys::backtrace::_print_fmt::h18461d452462c56f
                               at /rustc/2fd855fbfc8239285aa2d596f76a8cc75e17ce02/library/std/src/sys/backtrace.rs:66:9
   3:        0x105af4c7c - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h06e089ac2c39de74
                               at /rustc/2fd855fbfc8239285aa2d596f76a8cc75e17ce02/library/std/src/sys/backtrace.rs:39:26
   4:        0x105b12a7c - core::fmt::rt::Argument::fmt::h2ddfe79356c7d9c6
                               at /rustc/2fd855fbfc8239285aa2d596f76a8cc75e17ce02/library/core/src/fmt/rt.rs:173:76
   5:        0x105b12a7c - core::fmt::write::heedfdc3fd98812b6
                               at /rustc/2fd855fbfc8239285aa2d596f76a8cc75e17ce02/library/core/src/fmt/mod.rs:1468:25
   6:        0x105af1e8c - std::io::default_write_fmt::h1b415dea951b13de
                               at /rustc/2fd855fbfc8239285aa2d596f76a8cc75e17ce02/library/std/src/io/mod.rs:639:11
   7:        0x105af1e8c - std::io::Write::write_fmt::h21d8b41e1b6cb009
                               at /rustc/2fd855fbfc8239285aa2d596f76a8cc75e17ce02/library/std/src/io/mod.rs:1954:13
   8:        0x105af4b30 - std::sys::backtrace::BacktraceLock::print::h125cd1052eccd321
                               at /rustc/2fd855fbfc8239285aa2d596f76a8cc75e17ce02/library/std/src/sys/backtrace.rs:42:9
   9:        0x105af6388 - std::panicking::default_hook::{{closure}}::hec4af4ffb73bfb90
                               at /rustc/2fd855fbfc8239285aa2d596f76a8cc75e17ce02/library/std/src/panicking.rs:301:27
  10:        0x105af6204 - std::panicking::default_hook::h562cbeab09f51a92
                               at /rustc/2fd855fbfc8239285aa2d596f76a8cc75e17ce02/library/std/src/panicking.rs:328:9
  11:        0x1055a5b2c - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h5b3616a74cbc6d69
                               at /me/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/src/rust/library/alloc/src/boxed.rs:1985:9
  12:        0x1055ad604 - bevy_ecs::error::bevy_error::bevy_error_panic_hook::{{closure}}::h86306e13ace39253
                               at /code/bevy/crates/bevy_ecs/src/error/bevy_error.rs:162:9
  13:        0x105af6ef0 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::ha26dec2233204781
                               at /rustc/2fd855fbfc8239285aa2d596f76a8cc75e17ce02/library/alloc/src/boxed.rs:1985:9
  14:        0x105af6ef0 - std::panicking::panic_with_hook::he9f4569172ea2020
                               at /rustc/2fd855fbfc8239285aa2d596f76a8cc75e17ce02/library/std/src/panicking.rs:842:13
  15:        0x105af6ad4 - std::panicking::begin_panic_handler::{{closure}}::h32a2ba9ef96b6e3d
                               at /rustc/2fd855fbfc8239285aa2d596f76a8cc75e17ce02/library/std/src/panicking.rs:707:13
  16:        0x105af5118 - std::sys::backtrace::__rust_end_short_backtrace::hba3b5c2962f7ee0f
                               at /rustc/2fd855fbfc8239285aa2d596f76a8cc75e17ce02/library/std/src/sys/backtrace.rs:174:18
  17:        0x105af67b0 - __rustc[afa1a629380cfd82]::rust_begin_unwind
                               at /rustc/2fd855fbfc8239285aa2d596f76a8cc75e17ce02/library/std/src/panicking.rs:698:5
  18:        0x105d0f518 - core::panicking::panic_fmt::h562d2c2343c636bd
                               at /rustc/2fd855fbfc8239285aa2d596f76a8cc75e17ce02/library/core/src/panicking.rs:75:14
  19:        0x105d0f698 - core::panicking::panic_bounds_check::h4c4cb38bec554f6c
                               at /rustc/2fd855fbfc8239285aa2d596f76a8cc75e17ce02/library/core/src/panicking.rs:280:5
  20:        0x101bca9b8 - <usize as core::slice::index::SliceIndex<[T]>>::index_mut::hfb8653d9fa05eb77
                               at /me/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/slice/index.rs:280:14
  21:        0x101bf6418 - core::slice::index::<impl core::ops::index::IndexMut<I> for [T]>::index_mut::h4466e9d05f51186d
                               at /me/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/slice/index.rs:30:15
  22:        0x101bf6418 - <alloc::vec::Vec<T,A> as core::ops::index::IndexMut<I>>::index_mut::h42a275302b5f7d42
                               at /me/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/src/rust/library/alloc/src/vec/mod.rs:3579:9
  23:        0x10179d300 - bevy_pbr::lightmap::RenderLightmaps::allocate::hb214df6567a147ec
                               at /code/bevy/crates/bevy_pbr/src/lightmap/mod.rs:372:35
  24:        0x10179ce18 - bevy_pbr::lightmap::extract_lightmaps::hcb714c566415425d
                               at /code/bevy/crates/bevy_pbr/src/lightmap/mod.rs:232:30
  25:        0x1017e11dc - core::ops::function::FnMut::call_mut::h19aa48c9261c79a7
                               at /me/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/function.rs:168:5
  26:        0x1018f131c - core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut::ha1c194a643c55f2e
                               at /me/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/function.rs:301:21
  27:        0x10164623c - <Func as bevy_ecs::system::function_system::SystemParamFunction<fn(F0,F1,F2,F3,F4) .> Out>>::run::call_inner::h562135861536565b
                               at /code/bevy/crates/bevy_ecs/src/system/function_system.rs:924:21
  28:        0x1018f1074 - <Func as bevy_ecs::system::function_system::SystemParamFunction<fn(F0,F1,F2,F3,F4) .> Out>>::run::h4d10db5f9f07ce8d
                               at /code/bevy/crates/bevy_ecs/src/system/function_system.rs:927:17
  29:        0x10160a090 - <bevy_ecs::system::function_system::FunctionSystem<Marker,Out,F> as bevy_ecs::system::system::System>::run_unsafe::h2d45a70a993cda8a
                               at /code/bevy/crates/bevy_ecs/src/system/function_system.rs:709:29
  30:        0x1055ee188 - bevy_ecs::schedule::executor::__rust_begin_short_backtrace::run_unsafe::h6729036baec7964f
                               at /code/bevy/crates/bevy_ecs/src/schedule/executor/mod.rs:265:29
  31:        0x10575f324 - bevy_ecs::schedule::executor::multi_threaded::ExecutorState::spawn_system_task::{{closure}}::{{closure}}::h3064a851da8d365e
                               at /code/bevy/crates/bevy_ecs/src/schedule/executor/multi_threaded.rs:684:25
  32:        0x105720ec8 - core::ops::function::FnOnce::call_once::h72d81e8d0718519b
                               at /me/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/function.rs:253:5
  33:        0x105787004 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hd5455dee5354a106
                               at /me/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/panic/unwind_safe.rs:272:9
  34:        0x1056285e0 - std::panicking::catch_unwind::do_call::h1f37a42916db8101
                               at /me/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/panicking.rs:590:40
  35:        0x1056bf5c0 - ___rust_try
  36:        0x1056bf3e8 - std::panicking::catch_unwind::hc77c3a4b6b85034e
                               at /me/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/panicking.rs:553:19
  37:        0x1056bf3e8 - std::panic::catch_unwind::he636cb9bd6f71ed9
                               at /me/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/panic.rs:357:14
  38:        0x10575f220 - bevy_ecs::schedule::executor::multi_threaded::ExecutorState::spawn_system_task::{{closure}}::hed914c117d3e1d5b
                               at /code/bevy/crates/bevy_ecs/src/schedule/executor/multi_threaded.rs:677:23
  39:        0x105786d1c - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::future::future::Future>::poll::h21e18915aadbf732
                               at /me/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/panic/unwind_safe.rs:297:9
  40:        0x1056371c0 - <futures_lite::future::CatchUnwind<F> as core::future::future::Future>::poll::{{closure}}::h59f95786b53b1789
                               at /me/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/futures-lite-2.6.1/src/future.rs:653:53
  41:        0x105787114 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hedd3fd426e78fa97
                               at /me/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/panic/unwind_safe.rs:272:9
  42:        0x105628938 - std::panicking::catch_unwind::do_call::h9fc89212cc417e83
                               at /me/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/panicking.rs:590:40
  43:        0x1056bf5c0 - ___rust_try
  44:        0x1056bf218 - std::panicking::catch_unwind::he9e018be1bfb9cdc
                               at /me/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/panicking.rs:553:19
  45:        0x1056bf218 - std::panic::catch_unwind::ha6b9cc37bff767df
                               at /me/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/panic.rs:357:14
  46:        0x105637020 - <futures_lite::future::CatchUnwind<F> as core::future::future::Future>::poll::hbeb2014ce3f42d4d
                               at /me/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/futures-lite-2.6.1/src/future.rs:653:9
  47:        0x1057432a8 - <async_executor::AsyncCallOnDrop<Fut,Cleanup> as core::future::future::Future>::poll::hddab41b773344f11
                               at /me/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/async-executor-1.13.2/src/lib.rs:1179:31
  48:        0x1056c9f78 - async_task::raw::RawTask<F,T,S,M>::run::{{closure}}::hd43a90a32862aad4
                               at /me/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/async-task-4.7.1/src/raw.rs:550:21
  49:        0x1057246f4 - core::ops::function::FnOnce::call_once::hf0cfd5cae8689fe1
                               at /me/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/function.rs:253:5
  50:        0x105786fa4 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::ha391f93043f70ce8
                               at /me/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/panic/unwind_safe.rs:272:9
  51:        0x105628994 - std::panicking::catch_unwind::do_call::ha4eeb13dca4f04ad
                               at /me/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/panicking.rs:590:40
  52:        0x1056bf5c0 - ___rust_try
  53:        0x1056bee48 - std::panicking::catch_unwind::hf1d19c8a7573a4b3
                               at /me/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/panicking.rs:553:19
  54:        0x1056bee48 - std::panic::catch_unwind::h504979384bc6439c
                               at /me/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/panic.rs:357:14
  55:        0x1056c67cc - async_task::raw::RawTask<F,T,S,M>::run::h7d7c5f06875ebe76
                               at /me/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/async-task-4.7.1/src/raw.rs:549:23
  56:        0x1057d8b1c - async_task::runnable::Runnable<M>::run::h7b9ebbd2fdfd3e82
                               at /me/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/async-task-4.7.1/src/runnable.rs:781:18
  57:        0x103823d14 - async_executor::State::run::{{closure}}::{{closure}}::h04b767631e7d4e9a
                               at /me/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/async-executor-1.13.2/src/lib.rs:745:30
  58:        0x10365d9a0 - <futures_lite::future::Or<F1,F2> as core::future::future::Future>::poll::h40de70d6542f928f
                               at /me/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/futures-lite-2.6.1/src/future.rs:454:46
  59:        0x1038232ec - async_executor::State::run::{{closure}}::had432afb420b67c3
                               at /me/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/async-executor-1.13.2/src/lib.rs:752:32
  60:        0x103826df8 - async_executor::Executor::run::{{closure}}::he1048596468449c2
                               at /me/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/async-executor-1.13.2/src/lib.rs:343:34
  61:        0x1037fb020 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::future::future::Future>::poll::h1e30f4c0bec0512b
                               at /me/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/panic/unwind_safe.rs:297:9
  62:        0x10365edec - <futures_lite::future::CatchUnwind<F> as core::future::future::Future>::poll::{{closure}}::h7e41570834f5cd98
                               at /me/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/futures-lite-2.6.1/src/future.rs:653:53
  63:        0x1037fb634 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h63fda015f6503fe3
                               at /me/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/panic/unwind_safe.rs:272:9
  64:        0x103a4094c - std::panicking::catch_unwind::do_call::h9a1208e499707a34
                               at /me/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/panicking.rs:590:40
  65:        0x1036b1e18 - ___rust_try
  66:        0x1036b17c8 - std::panicking::catch_unwind::hf873cfec10de16ab
                               at /me/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/panicking.rs:553:19
  67:        0x1036b17c8 - std::panic::catch_unwind::h8713a95640d29e4a
                               at /me/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/panic.rs:357:14
  68:        0x10365e44c - <futures_lite::future::CatchUnwind<F> as core::future::future::Future>::poll::h340d6eb478559e64
                               at /me/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/futures-lite-2.6.1/src/future.rs:653:9
  69:        0x1039cfec0 - bevy_tasks::task_pool::TaskPool::execute_global_scope::{{closure}}::{{closure}}::h137aed486c5151d4
                               at /code/bevy/crates/bevy_tasks/src/task_pool.rs:526:22
  70:        0x10365dec4 - <futures_lite::future::Or<F1,F2> as core::future::future::Future>::poll::ha707715fca462b4e
                               at /me/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/futures-lite-2.6.1/src/future.rs:454:46
  71:        0x1039cf8cc - bevy_tasks::task_pool::TaskPool::execute_global_scope::{{closure}}::h1df7ea0dd9566a7d
                               at /code/bevy/crates/bevy_tasks/src/task_pool.rs:530:41
  72:        0x1039d3914 - bevy_tasks::task_pool::TaskPool::scope_with_executor_inner::{{closure}}::h8bb06dba4668b5e3
                               at /code/bevy/crates/bevy_tasks/src/task_pool.rs:457:89
  73:        0x10365c3ac - futures_lite::future::block_on::{{closure}}::h5077ab09b83afe42
                               at /me/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/futures-lite-2.6.1/src/future.rs:96:35
  74:        0x1037a0438 - std::thread::local::LocalKey<T>::try_with::h579c771f5ecadb22
                               at /me/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/thread/local.rs:315:12
  75:        0x10379fb94 - std::thread::local::LocalKey<T>::with::hcdf3833d4ab7a9fe
                               at /me/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/thread/local.rs:279:20
  76:        0x10365b850 - futures_lite::future::block_on::h6e4f87c3c508d9b0
                               at /me/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/futures-lite-2.6.1/src/future.rs:75:11
  77:        0x1039d20bc - bevy_tasks::task_pool::TaskPool::scope_with_executor_inner::hd1fe685c9880d919
                               at /code/bevy/crates/bevy_tasks/src/task_pool.rs:413:13
  78:        0x1039d5afc - bevy_tasks::task_pool::TaskPool::scope::{{closure}}::h44a0d6141ce8afe2
                               at /code/bevy/crates/bevy_tasks/src/task_pool.rs:316:18
  79:        0x1037a07fc - std::thread::local::LocalKey<T>::try_with::hd2d1cd03b05e2b12
                               at /me/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/thread/local.rs:315:12
  80:        0x10379fc7c - std::thread::local::LocalKey<T>::with::hf55dbd87ac9b42a5
                               at /me/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/thread/local.rs:279:20
  81:        0x1039d5a54 - bevy_tasks::task_pool::TaskPool::scope::he1d0bee7bb04566b
                               at /code/bevy/crates/bevy_tasks/src/task_pool.rs:315:31
  82:        0x103883448 - <bevy_render::pipelined_rendering::PipelinedRenderingPlugin as bevy_app::plugin::Plugin>::cleanup::{{closure}}::h6ce6220c6c4566ae
                               at /code/bevy/crates/bevy_render/src/pipelined_rendering.rs:157:22
  83:        0x1036a80f8 - std::sys::backtrace::__rust_begin_short_backtrace::hfe9fb3466a9b210a
                               at /me/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/sys/backtrace.rs:158:18
  84:        0x1037125b8 - std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}::h78d5f90398e0661d
                               at /me/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/thread/mod.rs:559:17
  85:        0x1037fb450 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h1a15b237b66a327c
                               at /me/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/panic/unwind_safe.rs:272:9
  86:        0x103a402d0 - std::panicking::catch_unwind::do_call::h154f1ae3740d1dc0
                               at /me/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/panicking.rs:590:40
  87:        0x103712638 - ___rust_try
  88:        0x103712258 - std::panicking::catch_unwind::h22e4fc8c1fd396bf
                               at /me/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/panicking.rs:553:19
  89:        0x103712258 - std::panic::catch_unwind::h627a5beb3d45758a
                               at /me/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/panic.rs:357:14
  90:        0x103712258 - std::thread::Builder::spawn_unchecked_::{{closure}}::hb0e1d8383ab1f6b3
                               at /me/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/thread/mod.rs:557:30
  91:        0x103670fb0 - core::ops::function::FnOnce::call_once{{vtable.shim}}::hf1a4afde25510172
                               at /me/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/function.rs:253:5
  92:        0x105af9110 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h680f3ff107785cd8
                               at /rustc/2fd855fbfc8239285aa2d596f76a8cc75e17ce02/library/alloc/src/boxed.rs:1971:9
  93:        0x105af9110 - std::sys::pal::unix::thread::Thread::new::thread_start::h2690b7c9f92b1d1f
                               at /rustc/2fd855fbfc8239285aa2d596f76a8cc75e17ce02/library/std/src/sys/pal/unix/thread.rs:107:17
  94:        0x19600ac0c - __pthread_cond_wait
Encountered a panic in system `bevy_pbr::lightmap::extract_lightmaps`!
2025-08-21T05:36:51.917608Z  WARN bevy_ecs::world::command_queue: CommandQueue has un-applied commands being dropped. Did you forget to call SystemState::apply?
2025-08-21T05:36:51.917653Z  WARN bevy_ecs::world::command_queue: CommandQueue has un-applied commands being dropped. Did you forget to call SystemState::apply?
2025-08-21T05:36:51.917663Z  WARN bevy_ecs::world::command_queue: CommandQueue has un-applied commands being dropped. Did you forget to call SystemState::apply?
2025-08-21T05:36:51.917684Z  WARN bevy_ecs::world::command_queue: CommandQueue has un-applied commands being dropped. Did you forget to call SystemState::apply?
2025-08-21T05:36:51.917698Z  WARN bevy_ecs::world::command_queue: CommandQueue has un-applied commands being dropped. Did you forget to call SystemState::apply?
2025-08-21T05:36:51.917707Z  WARN bevy_ecs::world::command_queue: CommandQueue has un-applied commands being dropped. Did you forget to call SystemState::apply?
2025-08-21T05:36:51.917720Z  WARN bevy_ecs::world::command_queue: CommandQueue has un-applied commands being dropped. Did you forget to call SystemState::apply?
2025-08-21T05:36:51.917727Z  WARN bevy_ecs::world::command_queue: CommandQueue has un-applied commands being dropped. Did you forget to call SystemState::apply?
2025-08-21T05:36:51.917739Z  WARN bevy_ecs::world::command_queue: CommandQueue has un-applied commands being dropped. Did you forget to call SystemState::apply?
2025-08-21T05:36:51.917773Z  WARN bevy_ecs::world::command_queue: CommandQueue has un-applied commands being dropped. Did you forget to call SystemState::apply?
2025-08-21T05:36:51.917779Z  WARN bevy_ecs::world::command_queue: CommandQueue has un-applied commands being dropped. Did you forget to call SystemState::apply?
2025-08-21T05:36:51.917788Z  WARN bevy_ecs::world::command_queue: CommandQueue has un-applied commands being dropped. Did you forget to call SystemState::apply?
2025-08-21T05:36:51.917794Z  WARN bevy_ecs::world::command_queue: CommandQueue has un-applied commands being dropped. Did you forget to call SystemState::apply?
2025-08-21T05:36:51.917804Z  WARN bevy_ecs::world::command_queue: CommandQueue has un-applied commands being dropped. Did you forget to call SystemState::apply?
2025-08-21T05:36:51.917867Z  WARN bevy_ecs::world::command_queue: CommandQueue has un-applied commands being dropped. Did you forget to call SystemState::apply?
2025-08-21T05:36:51.917878Z  WARN bevy_ecs::world::command_queue: CommandQueue has un-applied commands being dropped. Did you forget to call SystemState::apply?
2025-08-21T05:36:51.917887Z  WARN bevy_ecs::world::command_queue: CommandQueue has un-applied commands being dropped. Did you forget to call SystemState::apply?
2025-08-21T05:36:51.917896Z  WARN bevy_ecs::world::command_queue: CommandQueue has un-applied commands being dropped. Did you forget to call SystemState::apply?
2025-08-21T05:36:51.917903Z  WARN bevy_ecs::world::command_queue: CommandQueue has un-applied commands being dropped. Did you forget to call SystemState::apply?
2025-08-21T05:36:51.917910Z  WARN bevy_ecs::world::command_queue: CommandQueue has un-applied commands being dropped. Did you forget to call SystemState::apply?
2025-08-21T05:36:51.917916Z  WARN bevy_ecs::world::command_queue: CommandQueue has un-applied commands being dropped. Did you forget to call SystemState::apply?
2025-08-21T05:36:51.917933Z  WARN bevy_ecs::world::command_queue: CommandQueue has un-applied commands being dropped. Did you forget to call SystemState::apply?
2025-08-21T05:36:51.917947Z  WARN bevy_ecs::world::command_queue: CommandQueue has un-applied commands being dropped. Did you forget to call SystemState::apply?
2025-08-21T05:36:51.917962Z  WARN bevy_ecs::world::command_queue: CommandQueue has un-applied commands being dropped. Did you forget to call SystemState::apply?
2025-08-21T05:36:51.917968Z  WARN bevy_ecs::world::command_queue: CommandQueue has un-applied commands being dropped. Did you forget to call SystemState::apply?
2025-08-21T05:36:51.917974Z  WARN bevy_ecs::world::command_queue: CommandQueue has un-applied commands being dropped. Did you forget to call SystemState::apply?
2025-08-21T05:36:51.917980Z  WARN bevy_ecs::world::command_queue: CommandQueue has un-applied commands being dropped. Did you forget to call SystemState::apply?
2025-08-21T05:36:51.917988Z  WARN bevy_ecs::world::command_queue: CommandQueue has un-applied commands being dropped. Did you forget to call SystemState::apply?
2025-08-21T05:36:51.918012Z  WARN bevy_ecs::world::command_queue: CommandQueue has un-applied commands being dropped. Did you forget to call SystemState::apply?
2025-08-21T05:36:51.918021Z  WARN bevy_ecs::world::command_queue: CommandQueue has un-applied commands being dropped. Did you forget to call SystemState::apply?
2025-08-21T05:36:51.918036Z  WARN bevy_ecs::world::command_queue: CommandQueue has un-applied commands being dropped. Did you forget to call SystemState::apply?
2025-08-21T05:36:51.918050Z  WARN bevy_ecs::world::command_queue: CommandQueue has un-applied commands being dropped. Did you forget to call SystemState::apply?
2025-08-21T05:36:51.918055Z  WARN bevy_ecs::world::command_queue: CommandQueue has un-applied commands being dropped. Did you forget to call SystemState::apply?
2025-08-21T05:36:51.918088Z  WARN bevy_ecs::world::command_queue: CommandQueue has un-applied commands being dropped. Did you forget to call SystemState::apply?
2025-08-21T05:36:51.918094Z  WARN bevy_ecs::world::command_queue: CommandQueue has un-applied commands being dropped. Did you forget to call SystemState::apply?
2025-08-21T05:36:51.918102Z  WARN bevy_ecs::world::command_queue: CommandQueue has un-applied commands being dropped. Did you forget to call SystemState::apply?
2025-08-21T05:36:51.918111Z  WARN bevy_ecs::world::command_queue: CommandQueue has un-applied commands being dropped. Did you forget to call SystemState::apply?
2025-08-21T05:36:51.918140Z  WARN bevy_ecs::world::command_queue: CommandQueue has un-applied commands being dropped. Did you forget to call SystemState::apply?
2025-08-21T05:36:51.918160Z  WARN bevy_ecs::world::command_queue: CommandQueue has un-applied commands being dropped. Did you forget to call SystemState::apply?
2025-08-21T05:36:51.918167Z  WARN bevy_ecs::world::command_queue: CommandQueue has un-applied commands being dropped. Did you forget to call SystemState::apply?
2025-08-21T05:36:51.918175Z  WARN bevy_ecs::world::command_queue: CommandQueue has un-applied commands being dropped. Did you forget to call SystemState::apply?
2025-08-21T05:36:51.918185Z  WARN bevy_ecs::world::command_queue: CommandQueue has un-applied commands being dropped. Did you forget to call SystemState::apply?
2025-08-21T05:36:51.918193Z  WARN bevy_ecs::world::command_queue: CommandQueue has un-applied commands being dropped. Did you forget to call SystemState::apply?
2025-08-21T05:36:51.918231Z  WARN bevy_ecs::world::command_queue: CommandQueue has un-applied commands being dropped. Did you forget to call SystemState::apply?
2025-08-21T05:36:51.918243Z  WARN bevy_ecs::world::command_queue: CommandQueue has un-applied commands being dropped. Did you forget to call SystemState::apply?
2025-08-21T05:36:51.918250Z  WARN bevy_ecs::world::command_queue: CommandQueue has un-applied commands being dropped. Did you forget to call SystemState::apply?
2025-08-21T05:36:51.918259Z  WARN bevy_ecs::world::command_queue: CommandQueue has un-applied commands being dropped. Did you forget to call SystemState::apply?
2025-08-21T05:36:51.918281Z  WARN bevy_ecs::world::command_queue: CommandQueue has un-applied commands being dropped. Did you forget to call SystemState::apply?
2025-08-21T05:36:52.138362Z ERROR winit::platform_impl::macos::event_handler: tried to run event handler, but no handler was set
```

</details>

<details>

<summary>Expand to show repro code to drop over lightmaps.rs</summary>

```rust
//! Reproduction of the lightmaps index out of bounds bug.
//! This example creates many lightmaps and then creates/destroys them
//! to trigger the bug.

use argh::FromArgs;
use bevy::{
    asset::Handle,
    core_pipeline::prepass::{DeferredPrepass, DepthPrepass, MotionVectorPrepass},
    image::Image,
    input::{keyboard::KeyCode, ButtonInput},
    mesh::VertexAttributeValues,
    pbr::{DefaultOpaqueRendererMethod, Lightmap},
    prelude::*,
};
use bevy_render::render_resource::Extent3d;

/// Demonstrates lightmaps bug reproduction
#[derive(FromArgs, Resource)]
struct Args {
    /// enables deferred shading
    #[argh(switch)]
    deferred: bool,
    /// enables bicubic filtering
    #[argh(switch)]
    bicubic: bool,
}

#[derive(Resource, Default)]
struct State {
    cycle_count: u32,
    lightmap_entities: Vec<Entity>,
    lightmap_handles: Vec<Handle<Image>>,
}

fn main() {
    #[cfg(not(target_arch = "wasm32"))]
    let args: Args = argh::from_env();
    #[cfg(target_arch = "wasm32")]
    let args: Args = Args::from_args(&[], &[]).unwrap();

    let mut app = App::new();
    app.add_plugins(DefaultPlugins)
        .insert_resource(AmbientLight::NONE)
        .init_resource::<State>();

    if args.deferred {
        app.insert_resource(DefaultOpaqueRendererMethod::deferred());
    }

    app.insert_resource(args)
        .add_systems(Startup, setup)
        .add_systems(Update, (handle_input, auto_cycle))
        .run();
}

fn setup(mut commands: Commands, args: Res<Args>) {
    // Camera
    let mut camera = commands.spawn((
        Camera3d::default(),
        Transform::from_xyz(0.0, 5.0, 10.0).looking_at(Vec3::ZERO, Vec3::Y),
    ));

    if args.deferred {
        camera.insert((
            DepthPrepass,
            MotionVectorPrepass,
            DeferredPrepass,
            Msaa::Off,
        ));
    }

    // Instructions
    commands.spawn((
        Text::new("Press SPACE to create lightmaps\nThen press 'A' to auto-cycle\nThis should trigger the lightmap bug"),
        Node {
            position_type: PositionType::Absolute,
            top: Val::Px(10.0),
            left: Val::Px(10.0),
            ..default()
        },
        TextColor(Color::WHITE),
    ));
}

#[derive(Resource)]
struct AutoCycle {
    timer: Timer,
    active: bool,
    phase: u32,
}

impl Default for AutoCycle {
    fn default() -> Self {
        Self {
            timer: Timer::from_seconds(1.0, TimerMode::Repeating),
            active: false,
            phase: 0,
        }
    }
}

fn auto_cycle(
    time: Res<Time>,
    mut auto_cycle: Local<AutoCycle>,
    mut state: ResMut<State>,
    mut commands: Commands,
    mut images: ResMut<Assets<Image>>,
    mut meshes: ResMut<Assets<Mesh>>,
    mut materials: ResMut<Assets<StandardMaterial>>,
    keyboard: Res<ButtonInput<KeyCode>>,
    args: Res<Args>,
) {
    if keyboard.just_pressed(KeyCode::KeyA) {
        auto_cycle.active = !auto_cycle.active;
        println!("Auto-cycle: {}", auto_cycle.active);
    }

    if !auto_cycle.active {
        return;
    }

    auto_cycle.timer.tick(time.delta());

    if auto_cycle.timer.just_finished() {
        auto_cycle.phase += 1;

        match auto_cycle.phase % 6 {
            0 => {
                println!(
                    "Phase 0: Creating 16 lightmaps with SAME asset (cycle {})",
                    state.cycle_count
                );

                // Create a dummy lightmap image.
                let lightmap_handle = if state.lightmap_handles.is_empty() {
                    let mut image = Image::default();
                    image.resize(Extent3d {
                        width: 32,
                        height: 32,
                        depth_or_array_layers: 1,
                    });
                    let handle = images.add(image);
                    state.lightmap_handles.push(handle.clone());
                    handle
                } else {
                    state.lightmap_handles[0].clone()
                };

                for i in 0..16 {
                    let entity = create_lightmapped_cube(
                        &mut commands,
                        &mut meshes,
                        &mut materials,
                        &lightmap_handle,
                        &args,
                        i as f32 * 2.0,
                    );
                    state.lightmap_entities.push(entity);
                }
            }
            1 => {
                println!("Phase 1: Removing 5 lightmaps");
                let len = state.lightmap_entities.len();
                let entities_to_remove: Vec<_> =
                    state.lightmap_entities.drain(0..5.min(len)).collect();

                for entity in entities_to_remove {
                    commands.entity(entity).despawn();
                }
            }
            2 => {
                println!("Phase 2: Adding 8 lightmaps with DIFFERENT assets");
                for i in 0..8 {
                    // Create new unique lightmap images.
                    let mut image = Image::default();
                    image.resize(Extent3d {
                        width: 64,
                        height: 64,
                        depth_or_array_layers: 1,
                    });
                    let lightmap_handle = images.add(image);
                    state.lightmap_handles.push(lightmap_handle.clone());

                    let entity = create_lightmapped_cube(
                        &mut commands,
                        &mut meshes,
                        &mut materials,
                        &lightmap_handle,
                        &args,
                        20.0 + i as f32 * 2.0,
                    );
                    state.lightmap_entities.push(entity);
                }
            }
            3 => {
                println!("Phase 3: Removing all lightmaps");
                for entity in state.lightmap_entities.drain(..) {
                    commands.entity(entity).despawn();
                }
            }
            4 => {
                println!("Phase 4: Forcing asset cleanup by removing handles");
                state.lightmap_handles.clear();
            }
            5 => {
                println!("Phase 5: Creating lightmaps after cleanup");
                for i in 0..12 {
                    let mut image = Image::default();
                    image.resize(Extent3d {
                        width: 128,
                        height: 128,
                        depth_or_array_layers: 1,
                    });
                    let lightmap_handle = images.add(image);
                    state.lightmap_handles.push(lightmap_handle.clone());

                    let entity = create_lightmapped_cube(
                        &mut commands,
                        &mut meshes,
                        &mut materials,
                        &lightmap_handle,
                        &args,
                        i as f32 * 3.0,
                    );
                    state.lightmap_entities.push(entity);
                }
                state.cycle_count += 1;
            }
            _ => {}
        }
    }
}

fn handle_input(
    mut commands: Commands,
    mut state: ResMut<State>,
    mut images: ResMut<Assets<Image>>,
    mut meshes: ResMut<Assets<Mesh>>,
    mut materials: ResMut<Assets<StandardMaterial>>,
    keyboard: Res<ButtonInput<KeyCode>>,
    args: Res<Args>,
) {
    if keyboard.just_pressed(KeyCode::Space) {
        println!("Creating 12 lightmaps...");
        for i in 0..12 {
            let mut image = Image::default();
            image.resize(Extent3d {
                width: 32,
                height: 32,
                depth_or_array_layers: 1,
            });
            let lightmap_handle = images.add(image);
            state.lightmap_handles.push(lightmap_handle.clone());

            let entity = create_lightmapped_cube(
                &mut commands,
                &mut meshes,
                &mut materials,
                &lightmap_handle,
                &args,
                i as f32 * 2.0,
            );
            state.lightmap_entities.push(entity);
        }
    }
}

fn create_lightmapped_cube(
    commands: &mut Commands,
    meshes: &mut ResMut<Assets<Mesh>>,
    materials: &mut ResMut<Assets<StandardMaterial>>,
    lightmap_handle: &Handle<Image>,
    args: &Args,
    x_pos: f32,
) -> Entity {
    let mut material = StandardMaterial::default();
    material.lightmap_exposure = 250.0;

    // Create a cube mesh with UV_B coordinates.
    let mut mesh = Mesh::from(Cuboid::new(1.0, 1.0, 1.0));

    // Add UV_B coordinates (using the same as UV_A for simplicity).
    if let Some(VertexAttributeValues::Float32x2(uvs)) = mesh.attribute(Mesh::ATTRIBUTE_UV_0) {
        mesh.insert_attribute(Mesh::ATTRIBUTE_UV_1, uvs.clone());
    }

    commands
        .spawn((
            Mesh3d(meshes.add(mesh)),
            MeshMaterial3d(materials.add(material)),
            Transform::from_xyz(x_pos, 0.0, 0.0),
            Lightmap {
                image: lightmap_handle.clone(),
                bicubic_sampling: args.bicubic,
                ..default()
            },
        ))
        .id()
}
```

</details>

### LINKED ISSUE #21551: Left shift arithmetic overflow in `bevy_pbr::lightmap`
## Bevy version

- Bevy 0.17.2

#### Features

- `bevy_reflect`: `features = ["glam"]`
- `bevy_math`: `features = ["serialize", "bevy_reflect"]`

I would be surprised if these are related, but they are included for completeness.

#### Adapter info

```ignore
AdapterInfo { name: "Intel(R) Graphics (RPL-P)", vendor: 32902, device: 42912, device_type: IntegratedGpu, driver: "Intel open-source Mesa driver", driver_info: "Mesa 22.3.6", backend: Vulkan }
```

## What you did

Using `bevy_trenchbroom` to load BSP files into Bevy. Specifically, the lightmaps are from `bevy_trenchbroom::bsp::lighting::types::AnimatedLighting`.

- [ ] _TODO_: Investigate exactly how the lightmaps end up in `bevy_pbr`.

## What went wrong

I get a panic in `bevy_pbr` seemingly at random, with the following message:

```ignore
thread 'Compute Task Pool (6)' (442851) panicked at /home/eira/Github/bevy/crates/bevy_pbr/src/lightmap/mod.rs:421:37:
attempt to shift left with overflow
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Encountered a panic in system `bevy_pbr::lightmap::extract_lightmaps`!
```

It does not seem to be related to which map I try to load, as the same map may sometimes cause the crash and sometimes not. I originally thought it was due to https://github.com/bevyengine/bevy/issues/12756 causing Bevy to load the same map multiple times (and therefore creating too many copies of the lightmap), but even after applying https://github.com/bevyengine/bevy/pull/20449 locally (which fixes the issue) the crash in the lightmap allocation appears to still happen. It also appears to occasionally happen when loading the first map, which could rule out the possibility of the old map not being fully deloaded before the next is loaded. 

The path shows a local checkout of Bevy due to applying #20449. Otherwise the branch is identical to the `release-0.17.2` branch, specifically commit 566358363126dd69f6e457e47f306c68f8041d2a.

## Additional information

It's possible that this is a bug in `bevy_trenchbroom`, but I have not yet had time to investigate that. Either way, this seems like it should cause Bevy to produce an error message rather than hard-crashing. If I have time I'll try to put together a quick fix that at least prevents the panic.

### PR DESCRIPTION
**Pull request by andriyDev**
# Objective

- Fixes #21551.
- Fixes #20688.

## Solution

- Insert slab_index instead of slot_index into free_slabs.

## Testing

Ran the repro in #20688 and it works!

### CODE REVIEW

**Comment by eira-fransham** [comment]
Hard to know for certain because it was always intermittent but this appears to close https://github.com/bevyengine/bevy/issues/21551

File: crates/bevy_pbr/src/lightmap/mod.rs [hunk 1]
```diff
@@ -417,6 +417,10 @@ impl LightmapSlab {
     }
 
     fn allocate(&mut self, image_id: AssetId<Image>) -> LightmapSlotIndex {
+        assert!(
+            !self.is_full(),
+            "Attempting to allocate on a full lightmap slab"
```
Comment (eira-fransham) [inline crates/bevy_pbr/src/lightmap/mod.rs:422]: Maybe worth making this an error return (or potentially `error!` + return `Option`) instead of a panic? This is already better than the status quo so if it'd require a large amount of extra work to convert this from a panic into an error then maybe it's fine to keep it like this and just put in an issue to make it more resilient later.

**Comment by mgi388** [comment]
I wonder if this fixes https://github.com/bevyengine/bevy/issues/20688 too? That issue has a minimal repro included

File: crates/bevy_pbr/src/lightmap/mod.rs (hunk 1 above)
Comment (andriyDev) [reply crates/bevy_pbr/src/lightmap/mod.rs:422]: Personally I don't think these kinds of invariants are worth returning an error. This is an error localized to this type, and ignoring it would leave the lightmaps in a corrupted state anyway.

IMO results should be for cases where the "responsibility" is more global. This problem is so localized, I don't think it's worth it.

**Comment by andriyDev** [comment]
@mgi388 good catch! Looks like this PR does fix that as well (I tested the repro). I'll add that to the description.

File: crates/bevy_pbr/src/lightmap/mod.rs (hunk 1 above)
Comment (tychedelia) [reply crates/bevy_pbr/src/lightmap/mod.rs:422]: we might consider making it just `debug_assert` to make release builds panic safe but agree that this seems like a hard invariant

**Review by tychedelia — APPROVED** [review]
Nice catch, makes sense.

**Review by alice-i-cecile — APPROVED** [review]

File: crates/bevy_pbr/src/lightmap/mod.rs (hunk 1 above)
Comment (eira-fransham) [reply crates/bevy_pbr/src/lightmap/mod.rs:422]: Ok cool, IMO there's no issue so long as the intention is for this type to maintain this invariant before this method is called (i.e. that this isn't something that a user can hit by just adding a bunch of lightmaps to a scene or whatever)
