### PR TITLE
Delay asset hot reloading

### LINKED ISSUE #5631: asset server: hot reload of shaders crashes app
## Bevy version

0.8

## Relevant system information

Rust 1.62.1
Windows 10

## What you did

I tried to modify shaders at runtime and sometimes got the following error:
```
ERROR wgpu::backend::direct: Handling wgpu errors as fatal by default
thread 'Compute Task Pool (2)' panicked at 'wgpu error: Validation Error

Caused by:
    In Device::create_render_pipeline
      note: label = `opaque_mesh_pipeline`
    error matching VERTEX shader requirements against the pipeline
    unable to find entry point 'vertex'
```

I've created a repo to simulate the error here:
https://github.com/c-antin/bevy_asset_server_watch_for_changes_shader_bug

### PR DESCRIPTION
**Pull request by JMS55**
# Objective

- Fix #5631 

## Solution

- Wait 50ms (configurable) after the last modification event before reloading an asset.

---

## Changelog

- `AssetPlugin::watch_for_changes` is now a `ChangeWatcher` instead of a `bool`
- Fixed https://github.com/bevyengine/bevy/issues/5631

## Migration Guide
- Replace `AssetPlugin::watch_for_changes: true` with e.g. `ChangeWatcher::with_delay(Duration::from_millis(200))`

### CODE REVIEW

File: crates/bevy_asset/src/io/file_asset_io.rs [hunk 1]
```diff
@@ -199,13 +201,18 @@ pub fn filesystem_watcher_system(asset_server: Res<AssetServer>) {
...
-                        }
+                        // When an asset is modified, note down the timestamp
+                        changed.insert(to_reload.to_owned(), Instant::now());
                     }
                 }
             }
+
+            // Reload all assets whose last modification was at least 200ms ago
+            for (to_reload, _) in changed.drain_filter(|_, last_modified| {
+                last_modified.elapsed() >= Duration::from_millis(200)
```
Comment (alice-i-cecile) [inline crates/bevy_asset/src/io/file_asset_io.rs:212]: This needs a comment justifying why it's needed + why this time period was chosen.

**Review by alice-i-cecile — CHANGES_REQUESTED** [review]

File: crates/bevy_asset/src/io/file_asset_io.rs (hunk 1 above)
Comment (JMS55) [reply crates/bevy_asset/src/io/file_asset_io.rs]: Added docs. 50ms was chosen arbitrarily.

File: crates/bevy_asset/src/io/file_asset_io.rs [hunk 2]
```diff
@@ -199,13 +203,22 @@ pub fn filesystem_watcher_system(asset_server: Res<AssetServer>) {
...
             }
         }
+
+        // Reload all assets whose last modification was at least 50ms ago.
+        //
+        // When changing and then saving a shader, several modification events are sent in short succession.
+        // Unless we wait until we are sure the shader is finished being modified (and that there will be no more events coming),
+        // we will sometimes get a crash when trying to reload a partially-modified shader.
+        for (to_reload, _) in changed.drain_filter(|_, last_modified| {
+            last_modified.elapsed() >= Duration::from_millis(50)
```
Comment (mockersf) [inline crates/bevy_asset/src/io/file_asset_io.rs:219]: this value will heavily depend on the setup of the user and should be configurable

Comment (JMS55) [reply crates/bevy_asset/src/io/file_asset_io.rs]: What's the best way to get the value from the plugin into the system?

Comment (alice-i-cecile) [reply crates/bevy_asset/src/io/file_asset_io.rs]: Store it in a resource, which is initialized by the plugin.

Comment (mockersf) [reply crates/bevy_asset/src/io/file_asset_io.rs]: No need for a resource here, you can add a parameter to the plugin under feature flag, pass it around when creating the `FileAssetIo` https://github.com/bevyengine/bevy/blob/main/crates/bevy_asset/src/lib.rs#L89, and store it there https://github.com/bevyengine/bevy/blob/main/crates/bevy_asset/src/io/file_asset_io.rs#L41. You already retrieve the `filesystem_watcher` in the watch system, this will be just next to it.

Comment (mockersf) [reply crates/bevy_asset/src/io/file_asset_io.rs]: @JMS55 implemented my suggestion in https://github.com/JMS55/bevy/pull/11

**Comment by alice-i-cecile** [comment]
@JMS55 can you update your PR description to describe the small breaking changes?

**Comment by JMS55** [comment]
@alice-i-cecile I updated the PR description. Not sure if there are other breaking changes, lmk if so.

**Comment by mockersf** [comment]
I don't think I'm qualified to review this PR objectively as I wrote a part of it

**Review by mockersf — COMMENTED** [review]
@alice-i-cecile I don't think I'm qualified to review this PR objectively as I wrote a part of it

**Review by paul-hansen — APPROVED** [review]
