### PR TITLE
Fix depth prepass with msaa on webgpu

### LINKED ISSUE #19148: Reading depth prepass in shader extension broken on webgpu
## What you did

I've got a shader extension for `StandardMaterial` which reads the depth prepass texture and spits it straight into the output:
```wgsl
#import bevy_pbr::{
    forward_io::VertexOutput,
    mesh_view_bindings::globals,
    prepass_utils,
}

@fragment
fn fragment(
    in: VertexOutput,
) -> @location(0) vec4<f32> {
    let ndc_terrain_depth = bevy_pbr::prepass_utils::prepass_depth(in.position, 0u);

    return vec4<f32>(ndc_terrain_depth);
}
```

This works fine on native, but breaks on webgpu.

I've got a repro at https://github.com/OptimisticPeach/depth_bug_example (a total of 100 lines of code between rs and wgsl).

After cloning, you should be able to `cargo run`, and see that it works fine natively.

However if you do `cargo run --target wasm32-unknown-unknown` (this requires `wasm-server-runner` from crates.io, so `cargo install wasm-server-runner`), and then open the server on chrome, I get the following error:

Image

## What went wrong

It seems like for some reason the depth prepass texture isn't being bound while running this example on webgpu, despite it being bound just fine natively.

### LINKED ISSUE #19177: Forward decals are broken on Web
## Bevy version

0.16.0

## Relevant system information

Using 
- Firefox 138.0.1 (64-bit) 
- Chromium Version 136.0.7103.92 (Official Build) (64-bit)

on Fedora

WebGL2:
```ignore
 AdapterInfo { name: "ANGLE (AMD, AMD Radeon RX 7900 XTX (radeonsi navi31 LLVM 19.1.7), OpenGL 4.6)", vendor: 4098, device: 0, device_type: Other, driver: "", driver_info: "WebGL 2.0 (OpenGL ES 3.0 Chromium)", backend: Gl }
```

WebGPU:
```ignore
AdapterInfo { name: "", vendor: 0, device: 0, device_type: Other, driver: "", driver_info: "", backend: BrowserWebGpu }
```

## What you did

Opened https://bevyengine.org/examples-webgpu/3d-rendering/decal/ on Firefox using WebGL2, on Chrome using WebGL2, and on Chrome using WebGPU

## What went wrong

Nothing is rendered on WebGL2, the console says
```
Tex storage 2D multisample is not supported
```

On WebGPU, nothing is rendered until I move the mouse, at which point a rendered image flashes in for a split second:

https://github.com/user-attachments/assets/f462bca2-ff6b-49d3-be93-5db8474cf6f5

The console tells me:

```
Binding doesn't exist in [BindGroupLayoutInternal "mesh_view_layout"].
 - While validating that the entry-point's declaration for @group(0) @binding(28) matches [BindGroupLayoutInternal "mesh_view_layout"]
 - While validating the entry-point's compatibility for group 0 with [BindGroupLayoutInternal "mesh_view_layout"]
 - While validating fragment stage ([ShaderModule (unlabeled)], entryPoint: "fragment").
 - While validating fragment state.
 - While calling [Device].CreateRenderPipeline([RenderPipelineDescriptor ""forward_decal_pbr_alpha_blend_mesh_pipeline""]).

250[Invalid RenderPipeline "forward_decal_pbr_alpha_blend_mesh_pipeline"] is invalid.
 - While encoding [RenderPassEncoder "main_transparent_pass_3d"].SetPipeline([Invalid RenderPipeline "forward_decal_pbr_alpha_blend_mesh_pipeline"]).
 - While finishing [CommandEncoder (unlabeled)].

249[Invalid CommandBuffer] is invalid.
 - While calling [Queue].Submit([[CommandBuffer], [CommandBuffer "prepass_command_encoder" from CommandEncoder "prepass_command_encoder"], [CommandBuffer "shadow_pass_command_encoder" from CommandEncoder "shadow_pass_command_encoder"], [CommandBuffer "shadow_pass_command_encoder" from CommandEncoder "shadow_pass_command_encoder"], [CommandBuffer "shadow_pass_command_encoder" from CommandEncoder "shadow_pass_command_encoder"], [CommandBuffer "shadow_pass_command_encoder" from CommandEncoder "shadow_pass_command_encoder"], [CommandBuffer "shadow_pass_command_encoder" from CommandEncoder "shadow_pass_command_encoder"], [CommandBuffer "shadow_pass_command_encoder" from CommandEncoder "shadow_pass_command_encoder"], [CommandBuffer], [CommandBuffer "main_opaque_pass_3d_command_encoder" from CommandEncoder "main_opaque_pass_3d_command_encoder"], [Invalid CommandBuffer]])

decal/:1 WebGPU: too many warnings, no more warnings will be reported to the console for this GPUDevice.
```

## Additional information

The 0.16 announcement post [says](https://bevyengine.org/news/bevy-0-16/#decals):

> Ultimately, forward decals offer broader hardware and driver support, while clustered decals are higher quality and don't require the creation of bounding geometry, improving performance. Currently clustered decals require bindless textures and thus don't support WebGL2, WebGPU, iOS and Mac targets. Forward decals are available on these targets.

So I would have expected this to work

### PR DESCRIPTION
**Pull request by beicause**
# Objective

Fixes #19148.
Should fix #19177, too, because wgpu webgl2 just doesn't support sampling depth or creating multisampled texture with `TEXTURE_BINDING`.

## Solution

`feature="webgl"` and `feature="webgpu"` can enable together(webgpu overrides webgl), so we should bind multisampled depth texture even `webgl` feature is enabled.

## Testing

Run `decal` example

### CODE REVIEW

**Comment by JMS55** [comment]
Rather than using cfg, we should be checking adapter info for the current backend imo.

**Comment by beicause** [comment]
> Rather than using cfg, we should be checking adapter info for the current backend imo.

This might not be necessary and is beyond the scope of this PR. We use feature gating for webgl/webgpu in many places and it doesn't have runtime checks overhead.

File: crates/bevy_pbr/src/render/mesh_view_bindings.rs [hunk 1]
```diff
@@ -733,8 +732,7 @@ pub fn prepare_mesh_view_bind_groups(
 
             // When using WebGL, we can't have a depth texture with multisampling
```
Comment (JMS55) [inline crates/bevy_pbr/src/render/mesh_view_bindings.rs]: Comment needs updating

Comment (beicause) [reply crates/bevy_pbr/src/render/mesh_view_bindings.rs]: This comment is still correct. What needs to be updated?

Edit: I forgot that. It's updated now.
