### PR TITLE
Fix errors when disabling gpu clustering

### LINKED ISSUE #23208: Rendering broken on android since GPU clustering for lights
## Bevy version and features

- main since #23036

## What you did

Run the Android example on a few devices

## What went wrong

Crashes on:
- Android 12.0 / Google Pixel 6
- Android 13.0 / Google Pixel 7
- Android 14.0 / Google Pixel 8
- Android 15.0 / Google Pixel 9
- Android 13.0 / OnePlus 11R

```
Caught rendering error: Validation Error

Caused by:
  In Device::create_bind_group_layout, label = 'clustering count pass bind group layout'
    Binding 1 entry is invalid
      Features Features { features_wgpu: FeaturesWGPU(VERTEX_WRITABLE_STORAGE), features_webgpu: FeaturesWebGPU(0x0) } are required but not enabled on the device
Caught rendering error: Validation Error

Caused by:
  In Device::create_bind_group, label = 'clustering count pass bind group'
    BindGroupLayout with 'clustering count pass bind group layout' label is invalid
```

Wrong lighting on:
- Android 13.0 / Samsung Galaxy S23
- Android 15.0 / Samsung Galaxy S25
- Android 14.0 / OnePlus 12R

Image

Working correctly on:
- Android 14.0 / Samsung Galaxy S24

Image

### PR DESCRIPTION
**Pull request by beicause**
# Objective

Fix errors when disabling gpu clustering. Fixes #23208.

## Solution

~Set cluster buffer bindings correctly.~ Allow writing cluster on cpu buffer if gpu clustering is disabled.

## Testing

Tested mobile example on android.

### CODE REVIEW

File: crates/bevy_pbr/src/cluster/mod.rs [hunk 1]
```diff
@@ -57,6 +57,35 @@ pub const GPU_CLUSTERING_INITIAL_Z_SLICE_LIST_CAPACITY: usize = 1024;
...
 pub const GPU_CLUSTERING_INITIAL_INDEX_LIST_CAPACITY: usize = 65536;
 
+pub(crate) fn gpu_clustering_supported(adapter: &RenderAdapter, device: &RenderDevice) -> bool {
+    // We need to support compute shaders to use GPU clustering. To deal with
+    // the `WGPU_SETTINGS_PRIO="webgl2"` environment setting, we check the
+    // `RenderDevice` limits in addition to the `RenderAdapter`.
+    //
+    // Some android devices report the capabilities and limits wrong, so we can't rely on them.
+    // See <https://github.com/bevyengine/bevy/issues/23208> for Android issues
+    !cfg!(target_os = "android")
```
Comment (ChristopherBiscardi) [inline crates/bevy_pbr/src/cluster/mod.rs]:
```suggestion
    !(cfg!(target_os = "android") || cfg!(target_os = "ios"))
```

If this gets a target_os for ios as well, it fixes #23428 for the ios simulator as well

Comment (beicause) [reply crates/bevy_pbr/src/cluster/mod.rs]: I'm unable to test if #23428 is fixed. It may work without gating ios or ios simulator.

Comment (ChristopherBiscardi) [reply crates/bevy_pbr/src/cluster/mod.rs]: sorry, I could've been more clear. 

What I mean is that I tested this PR by running `make` in the `examples/mobile` directory, and observed the problem from #23428 in the simulator. Then I applied the fix suggested here, which removed the issue.

@mockersf might be able to confirm on an actual device, although I don't think the issue appears on their actual ios device.

Comment (beicause) [reply crates/bevy_pbr/src/cluster/mod.rs]: Does it only apply to ios simulator? If so we can use `target_abi = "sim"`. But I'm not sure why it can't work.

**Comment by beicause** [comment]
I realized this is may not be the correct approach. This PR forcing non-GPU clustering to use UBO, but before GPU clustering #23036 we can use SSBO.

Edit: Resolved

File: crates/bevy_pbr/src/cluster/mod.rs (hunk 1 above)
Comment (mockersf) [reply crates/bevy_pbr/src/cluster/mod.rs]: https://github.com/gfx-rs/wgpu/issues/7057
the iOS simulator has some weird behaviour about GPU validation, something like it's reporting limits available by the host machine by using validation from an actual devices, which are not the same, and this causes a few features to break. so yes for limiting by the target_abi, we already do in a few places

**Review by mockersf — APPROVED** [review]
