### PR TITLE
Fix FPS overlay system ordering ambiguity

### LINKED ISSUE #22571: FPS Overlay plugin system ambiguity
## Bevy version and features

0.18

## Issue

```
WARN bevy_ecs::schedule::schedule: Update schedule built successfully, however: 3 pairs of systems with conflicting data access have indeterminate execution order. Consider adding `before`, `after`, or `ambiguous_with` relationships between these:
 -- update_text and customize_overlay (in set (customize_overlay, toggle_display))
    conflict on: ["bevy_text::text_access::TextIterScratch", "bevy_ui::widget::text::Text", "bevy_text::text::TextFont", "bevy_text::text::TextColor", "bevy_text::text::LineHeight", "bevy_text::text::TextSpan"]
 -- update_text and update_stats
    conflict on: ["bevy_text::text_access::TextIterScratch", "bevy_ui::widget::text::Text", "bevy_text::text::TextFont", "bevy_text::text::TextColor", "bevy_text::text::LineHeight", "bevy_text::text::TextSpan"]
 -- customize_overlay (in set (customize_overlay, toggle_display)) and update_stats
    conflict on: ["bevy_text::text_access::TextIterScratch", "bevy_ui::widget::text::Text", "bevy_text::text::TextFont", "bevy_text::text::TextColor", "bevy_text::text::LineHeight", "bevy_text::text::TextSpan"]
```

My update stats system:

```rust
fn update_stats(
    stats: Res<Stats>,
    query: Query<Entity, With<StatsText>>,
    mut writer: TextUiWriter, // I think this is the problem?
)  { ... }
```

## Resolution

Ideally the FPS Overlay plugin systems wouldn't conflict with any systems. Or maybe there's something I should be doing to avoid the warnings? I enabled them like this:
```rust
        for schedule in MainScheduleOrder::default().labels {
            app.edit_schedule(schedule, |schedule| {
                schedule.set_build_settings(ScheduleBuildSettings {
                    ambiguity_detection: LogLevel::Warn,
                    ..default()
                });
            });
        }
```

### PR DESCRIPTION
**Pull request by JWSong**
# Objective

Fixes #22571 

## Solution

Added `FpsOverlaySystems` system set and explicitly ordered `customize_overlay` to run before `update_text`. This gets rid of the internal ambiguity warnings and also gives users a way to order their own systems against the overlay.

## Testing

Ran locally with ambiguity warnings enabled - no more internal overlay warnings. Didn't add a unit test since scheduling order is tricky to test in isolation.
To verify:
- Enable `ScheduleBuildSettings` ambiguity warnings.
- Add a user system that uses `TextUiWriter`.
- Run an app with `FpsOverlayPlugin` and confirm no overlay-related ambiguity warnings.

### CODE REVIEW

**Review by ickshonpe — CHANGES_REQUESTED** [review]
Tried this with the `fps_overlay` example but still got a reported conflict with `update_time_values` over `FpsOverlayConfig`. 

`FpsOverlaySystems::Customize` should be scheduled before `update_time_values` as well, I guess?

**Comment by JWSong** [comment]
Good catch, thanks! Pushed a follow-up that adds update_frame_time_values to UpdateText as well - tested with the example and the conflict seems to be resolved now.

File: crates/bevy_dev_tools/src/frame_time_graph/mod.rs [hunk 1]
```diff
@@ -37,7 +40,10 @@ impl Plugin for FrameTimeGraphPlugin {
         }
 
         app.add_plugins(UiMaterialPlugin::<FrametimeGraphMaterial>::default())
-            .add_systems(Update, update_frame_time_values);
+            .add_systems(
+                Update,
+                update_frame_time_values.in_set(FpsOverlaySystems::UpdateText),
```
Comment (ickshonpe) [inline crates/bevy_dev_tools/src/frame_time_graph/mod.rs:45]: I don't think there are any remaining problems, but I'm a bit unclear as to whether `FrameTimeGraphPlugin` is meant to be able to run independently of `FpsOverlayPlugin` or not. I guess it doesn't matter for this PR.
