### PR TITLE
Revert "don't use bevy_pbr for base bevy_gizmos plugin"

### LINKED ISSUE #18325: Example 3d_viewport_to_world: gizmo is displayed in the wrong position
## Bevy version

- 0.16.0-dev

## Relevant system information
- cargo 1.87.0-nightly (ab1463d63 2025-03-08)
- KDE 6.3.3
- SystemInfo { os: "Linux (openSUSE Tumbleweed 20250313)", kernel: "6.13.6-1-default", cpu: "13th Gen Intel(R) Core(TM) i7-13700KF", core_count: "16", memory: "62.6 GiB" }
- AdapterInfo { name: "NVIDIA GeForce RTX 4070 Ti SUPER", vendor: 4318, device: 9989, device_type: DiscreteGpu, driver: "NVIDIA", driver_info: "570.124.04", backend: Vulkan }

## What you did
Example 3d_viewport_to_world of the bevy crate executed without changing the code.

## What went wrong

If it's not clear, break this out into:

- what were you expecting?
The same behavior is expected as in the previous versions, as the example code has only changed slightly.

- what actually happened?
The position of the gizmo is displayed incorrectly (left top corner) in the wrong position in version bevy 0.16.0-dev. The previous versions bevy 0.14.0 and 0.15.0 worked successfully. Tested with Wayland and X11, but no difference was found.

## Additional information

The values of the variables `cursor_position`, `point` and the output of 
`Isometry3d::new(
        point + ground.up() * 0.01,
        Quat::from_rotation_arc(Vec3::Z, ground.up().as_vec3()),
    )` are identical in all bevy versions.

`// Draw a circle just above the ground plane at that position.
Line: 43 gizmos.circle(..., 0.2, Color::WHITE);` must  be the problem.

Image

### PR DESCRIPTION
**Pull request by mockersf**
# Objective

- #17581 broke gizmos
- Fixes #18325

## Solution

- Revert #17581 
- Add gizmos to testbed

## Testing

- Run any example with gizmos, it renders correctly

### CODE REVIEW

**Comment by IceSentry** [comment]
Uh, I'm not sure that PR was the issue? I mean, yes it broke gizmos when it was merged, but when it was created it didn't break like that. I think it might have been an issue with the merge to main but the original PR was correct.

**Comment by mockersf** [comment]
> Uh, I'm not sure that PR was the issue? I mean, yes it broke gizmos when it was merged, but when it was created it didn't break like that. I think it might have been an issue with the merge to main but the original PR was correct.

Yup, main probably changed something between the time it was opened and when it was merged, so it should be redone for current main

**Comment by alice-i-cecile** [comment]
Agreed on needing a redo. Let's revert for now though.

**Review by alice-i-cecile — APPROVED** [review]

File: examples/testbed/2d.rs [hunk 1]
```diff
@@ -265,3 +269,19 @@ mod sprite {
...
+
+mod gizmos {
+    use bevy::{color::palettes::css::*, prelude::*};
+
+    pub fn setup(mut commands: Commands) {
+        commands.spawn((Camera2d, StateScoped(super::Scene::Gizmos)));
+    }
+
+    pub fn draw_gizmos(mut gizmos: Gizmos) {
+        // gizmos.line_2d(Vec2::ZERO, Vec2::new(100.0, 100.0), RED);
```
Comment (mockersf) [inline examples/testbed/2d.rs:281]:
```suggestion
```

**Review by andriyDev — APPROVED** [review]
