### PR TITLE
bevy_reflect: Opt-out attribute for `TypePath`

### LINKED ISSUE #9094: TypePath required for generic #[reflect(ignore)] field
## Bevy version

Bevy 0.11

## What you did

I'm working on a PR to update leafwing-input-manager: https://github.com/Leafwing-Studios/leafwing-input-manager/pull/364

## What went wrong
Leafwing input manager has a struct ActionState that takes a generic that is used on a `#[reflect(ignore)]` PhantomData field:
```rust
#[derive(Resource, Component, Clone, Debug, PartialEq, Serialize, Deserialize, Reflect)]
pub struct ActionState<A: Actionlike> {
    /// The [`ActionData`] of each action
    ///
    /// The position in this vector corresponds to [`Actionlike::index`].
    action_data: Vec<ActionData>,
    #[reflect(ignore)]
    _phantom: PhantomData<A>,
}
```

We are getting an error when registering this type with bevy saying our generic type must implement TypePath.
This seems potentially limiting to the end users of LWIM and I'm not sure it was intended as it isn't mentioned in migration guides.
Is this restriction something that could be lifted?

## Additional info
There's a conversation about this on the LWIM PR starting here: 
https://github.com/Leafwing-Studios/leafwing-input-manager/pull/364#issuecomment-1628136788

To try this out, you can checkout the branch for that PR and remove the TypePath requirement I added from this line:
https://github.com/Leafwing-Studios/leafwing-input-manager/blob/7fb55b001a4aa949b1863dd2e0007d9512960625/src/lib.rs#L81

Here's the line and error we are getting:
https://github.com/Leafwing-Studios/leafwing-input-manager/blob/dfbe44b22fae01434737fb498dfb10d5ca20057d/src/plugin.rs#L146
```rust
        app.register_type::<ActionState<A>>()
```

```
error[E0277]: the trait bound `A: TypePath` is not satisfied
   --> src\plugin.rs:146:29
    |
146 |         app.register_type::<ActionState<A>>()
    |                             ^^^^^^^^^^^^^^ the trait `TypePath` is not implemented for `A`
    |
note: required for `ActionState<A>` to implement `GetTypeRegistration`
   --> src\action_state.rs:85:80
    |
85  | #[derive(Resource, Component, Clone, Debug, PartialEq, Serialize, Deserialize, Reflect)]
    |                                                                                ^^^^^^^ unsatisfied trait bound introduced in this `derive` macro
86  | pub struct ActionState<A: Actionlike> {
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
note: required by a bound in `App::register_type`
   --> D:\Packages\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_app-0.11.0\src\app.rs:816:29
    |
816 |     pub fn register_type<T: bevy_reflect::GetTypeRegistration>(&mut self) -> &mut Self {
    |                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ required by this bound in `App::register_type`
    = note: this error originates in the derive macro `Reflect` (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider further restricting this bound
    |
82  | impl<A: Actionlike + bevy::reflect::TypePath> Plugin for InputManagerPlugin<A> {
    |                    +++++++++++++++++++++++++
```

### PR DESCRIPTION
**Pull request by MrGVSV**
# Objective

Fixes #9094

## Solution

Takes a bit from [this](https://github.com/bevyengine/bevy/issues/9094#issuecomment-1629333851) comment as well as a [comment](https://discord.com/channels/691052431525675048/1002362493634629796/1128024873260810271) from @soqb.

This allows users to opt-out of the `TypePath` implementation that is automatically generated by the `Reflect` derive macro, allowing custom `TypePath` implementations.

```rust
#[derive(Reflect)]
#[reflect(type_path = false)]
struct Foo<T> {
    #[reflect(ignore)]
    _marker: PhantomData<T>,
}

struct NotTypePath;

impl<T: 'static> TypePath for Foo<T> {
    fn type_path() -> &'static str {
        std::any::type_name::<Self>()
    }

    fn short_type_path() -> &'static str {
        static CELL: GenericTypePathCell = GenericTypePathCell::new();
        CELL.get_or_insert::<Self, _>(|| {
            bevy_utils::get_short_name(std::any::type_name::<Self>())
        })
    }

    fn crate_name() -> Option<&'static str> {
        Some("my_crate")
    }

    fn module_path() -> Option<&'static str> {
        Some("my_crate::foo")
    }

    fn type_ident() -> Option<&'static str> {
        Some("Foo")
    }
}

// Can use `TypePath`
let _ = <Foo<NotTypePath> as TypePath>::type_path();

// Can register the type
let mut registry = TypeRegistry::default();
registry.register::<Foo<NotTypePath>>();
```

#### Type Path Stability

The stability of type paths mainly come into play during serialization. If a type is moved between builds, an unstable type path may become invalid.

Users that opt-out of `TypePath` and rely on something like `std::any::type_name` as in the example above, should be aware that this solution removes the stability guarantees. Deserialization thus expects that type to never move. If it does, then the serialized type paths will need to be updated accordingly.

If a user depends on stability, they will need to implement that stability logic manually (probably by looking at the expanded output of a typical `Reflect`/`TypePath` derive). This could be difficult for type parameters that don't/can't implement `TypePath`, and will need to make heavy use of string parsing and manipulation to achieve the same effect (alternatively, they can choose to simply exclude any type parameter that doesn't implement `TypePath`).

---

## Changelog

- Added the `#[reflect(type_path = false)]` attribute to opt out of the `TypePath` impl when deriving `Reflect`

### CODE REVIEW

**Review by paul-hansen — APPROVED** [review]
I like this solution a lot! Fixes the problem, doesn't require wrappers, still just as easy to use in normal use cases 👍 

I made a PR to leafwing input testing this out here: https://github.com/Leafwing-Studios/leafwing-input-manager/pull/366 Didn't have any issues using it.

I couldn't find anything in the code to complain about, all looks great!

**Comment by Bluefinger** [comment]
I gave this a spin, and I guess `#[reflect_value]` also works with `#[reflect_value(type_path = false)]`, since I was able to get my tests passing with `bevy_rand`. Works nicely for my use case! So if this merges for 10.1, then this will unblock `bevy_rand`'s upgrade path for sure.

File: crates/bevy_reflect/src/lib.rs [hunk 1]
```diff
@@ -1863,6 +1864,54 @@ bevy_reflect::tests::should_reflect_debug::Test {
         let _ = <Recurse<Recurse<()>> as TypePath>::type_path();
     }
 
+    #[test]
+    fn can_opt_out_type_path() {
```
Comment (Bluefinger) [inline crates/bevy_reflect/src/lib.rs:1868]: Maybe add a test for `reflect_value` since this is affected by the changes too.

**Review by Bluefinger — APPROVED** [review]

**Review by soqb — APPROVED** [review]
overall this LGTM, this works to resolve one issue but if this is merged with type path part 2 as it is it will be a stability hole (using `std::any::type_name`).

i wonder if (soon in the future) we could add an associated constant like the following:
```rust
trait TypePath {
    const TYPE_PATH_IS_STABLE: bool = false;
}
```
which would let us to panic upon (de)serialization.

**Comment by MrGVSV** [comment]
> overall this LGTM, this works to resolve one issue but if this is merged with type path part 2 as it is it will be a stability hole (using `std::any::type_name`).

Yeah. Maybe if we want to be super clear, I could add a warning in the docs to let users know that this is generally recommended against.

But yeah, for any type that can't effectively be (de)serialized, I don't think type name stability will be a major issue.

**Comment by Bluefinger** [comment]
> overall this LGTM, this works to resolve one issue but if this is merged with type path part 2 as it is it will be a stability hole (using `std::any::type_name`).
> 
> i wonder if (soon in the future) we could add an associated constant like the following:
> 
> ```rust
> trait TypePath {
>     const TYPE_PATH_IS_STABLE: bool = false;
> }
> ```
> 
> which would let us to panic upon (de)serialization.

The issue with that is a library like [`bevy_rand`](https://github.com/Bluefinger/bevy_rand) becomes unusable in the future in its current state, because `rand` types don't implement `TypePath` and newtyping will basically be forced onto users. I would like to avoid that if possible, else if not possible, I'd have to resort to macros to remove some of that boilerplate. Not ideal in my eyes for something that should be plug and play.

**Comment by soqb** [comment]
i agree that this fix is absolutely necessary for `bevy_rand`, however that implies that the types cannot ever have a stable type path.

i feel very strongly that we *should not* allow serialisation on types that do not have stable type path, so we cannot allow serialisation on the type with the offending error in `bevy_rand`. is that a dealbreaker?

**Comment by Bluefinger** [comment]
> i feel very strongly that we _should not_ allow serialisation on types that do not have stable type path, so we cannot allow serialisation on the type parameter with the offending error in `bevy_rand`. is that a dealbreaker?

Yes, because being able to serialise/deserialise the PRNG is a huge part of being able to store/send/reload a game's state (including its PRNG states) for determinism. Implementing a replay feature that is able to replay a game's 'random' parts, like crits, rolls, etc, requires that you are able to serialise/deserialise the PRNG, and `bevy_rand` component/resource types rely on the type parameter to determine which kind of PRNG is being used. For something like `ChaCha8Rng`, it's not just the seed you need to serialise, but also the stream and word position values. Different PRNGs have different states (`WyRand` is pretty much just a `u64` value, `ChaCha` is a 256-bit state, etc), so to be able to ensure when we have multiple clients synced to the same exact PRNG state, or loading a saved game, that we are initialising the game state (PRNG included) to be exactly what was saved. Not including the type means we are having a lossy conversion, or are straight-up unable to save/restore PRNGs.

So in summary, for `bevy_rand`, we can't not avoid serialising/deserialising the part that isn't `TypePath` stable, otherwise it pretty much kills the point of the crate.

**Comment by Bluefinger** [comment]
Ultimately though, if it must be no other way, then `bevy_rand` will have to be a very different sort of crate. It won't be a nice generic shim to plug any PRNG in, I'd have to provide concrete types, but that does mean `bevy_rand` won't be plug and play with the rest of the `rand` ecosystem, it would only support the PRNGs that I implement types for. But this also makes it not so nice for anything that tries to bring in external types from other rust crates into `bevy`.

**Comment by paul-hansen** [comment]
It should be noted that the example in the original post can be achieved in Bevy 0.11.0 already, you just have to manually implement Reflect instead of deriving it. This PR just allows you to disable the automatic implementation of TypePath when you derive Reflect. It doesn't introduce any stability issues that aren't already there.
Here's the same example working with Bevy 0.11.0 by implementing Reflect manually: https://gist.github.com/paul-hansen/c47f6af05732c0c03230fad5027f55e4

I think this PR could also be helpful for cases where there might be another crate that implements a stable type path and we want to implement TypePath using the methods that crate provides. So I don't really see this PR as solely helping negative use cases.

That said, I'm thinking I'll probably not use this for LWIM after all as serializing input maps is a core feature so it would benefit from the stability that TypePath brings for the same reasons that Bevy does. (I'm open to discussion on this though. Feel free to use [the LWIM PR](https://github.com/Leafwing-Studios/leafwing-input-manager/pull/366))

**Review by cart — APPROVED** [review]
I think enabling opting out here is reasonable, but I also think it seems weird to not capitalize on our ability to make the top level type's path "as stable as possible". I think ideally in these cases the developer only needs to fill in the type path for the generic type. (which could be done by passing in a function to the derive):

```rust
#[derive(Reflect)]
#[type_path(T = get_t_type_path())]
struct MyType<T> {}
```

I also suspect that 99% of these cases will want to fall back to `type_name`. Feels like we could make this easier than "implement TypePath manually".

```rust
#[derive(Reflect)]
#[unstable_type_path(T)]
struct MyType<T> {}
```
But this seems ok for 0.11.1
