### PR TITLE
Disable gpu clustering on android

### LINKED ISSUE #23208: Rendering broken on android since GPU clustering for lights
## Bevy version and features

- main since #23036

## What you did

Run the Android example on a few devices

## What went wrong

Crashes on:
- Android 12.0 / Google Pixel 6
- Android 13.0 / Google Pixel 7
- Android 14.0 / Google Pixel 8
- Android 15.0 / Google Pixel 9
- Android 13.0 / OnePlus 11R

```
Caught rendering error: Validation Error

Caused by:
  In Device::create_bind_group_layout, label = 'clustering count pass bind group layout'
    Binding 1 entry is invalid
      Features Features { features_wgpu: FeaturesWGPU(VERTEX_WRITABLE_STORAGE), features_webgpu: FeaturesWebGPU(0x0) } are required but not enabled on the device
Caught rendering error: Validation Error

Caused by:
  In Device::create_bind_group, label = 'clustering count pass bind group'
    BindGroupLayout with 'clustering count pass bind group layout' label is invalid
```

Wrong lighting on:
- Android 13.0 / Samsung Galaxy S23
- Android 15.0 / Samsung Galaxy S25
- Android 14.0 / OnePlus 12R

Image

Working correctly on:
- Android 14.0 / Samsung Galaxy S24

Image

### PR DESCRIPTION
**Pull request by mockersf**
# Objective

- GPU clustering of lights have issues on some android devices
- Fixes #23208

## Solution

- Disable GPU clustering on android

### CODE REVIEW

File: crates/bevy_pbr/src/cluster/mod.rs [hunk 1]
```diff
@@ -71,10 +71,13 @@ pub(crate) fn make_global_cluster_settings(world: &World) -> GlobalClusterSettin
     // We need to support compute shaders to use GPU clustering. To deal with
     // the `WGPU_SETTINGS_PRIO="webgl2"` environment setting, we check the
     // `RenderDevice` limits in addition to the `RenderAdapter`.
-    let gpu_clustering_supported = adapter
-        .get_downlevel_capabilities()
-        .flags
-        .contains(DownlevelFlags::COMPUTE_SHADERS)
+    // Some android devices report the capabilities and limits wrong, so we can't rely on them.
+    // See <https://github.com/bevyengine/bevy/issues/23208> for Android issues
+    let gpu_clustering_supported = cfg!(target_os = "android")
```
Comment (DGriffin91) [inline crates/bevy_pbr/src/cluster/mod.rs]: Is this backward from what was intended?

Comment (mockersf) [reply crates/bevy_pbr/src/cluster/mod.rs]: yup 🤦

Comment (mockersf) [inline crates/bevy_pbr/src/cluster/mod.rs]:
```suggestion
    let gpu_clustering_supported = !cfg!(target_os = "android")
```
