### PR TITLE
Fix GLTF files being broken when loaded from custom asset sources.

### LINKED ISSUE #10903: Custom asset source does not work with GLTF
## Bevy version

Recent main: d2614f2d802d0fb8000821a81553b600cc85f734

## What you did

Added a custom asset source and tried loading a GLTF with it.
Loading simple assets (e.g. single file images) works fine.

## What went wrong

It finds the gltf file, but fails to load the `scene.bin` mentioned within the GLTF.

### Logs

```log
2023-12-07T13:22:34.813576Z ERROR bevy_asset::server: Failed to load asset 'gltf://FlightHelmet.gltf' with asset loader 'bevy_gltf::loader::GltfLoader': failed to read bytes from an asset path: path not found: <path>/bevy/assets/FlightHelmet.bin
2023-12-07T13:22:34.813584Z ERROR bevy_asset::server: Failed to load asset 'gltf://FlightHelmet.gltf' with asset loader 'bevy_gltf::loader::GltfLoader': failed to read bytes from an asset path: path not found: <path>/bevy/assets/FlightHelmet.bin
```

### Minimal reproduction

_Make a folder foo and copy-paste the flight helmet files into it first._

```rust
use bevy::asset::io::*;
use bevy::{gltf::Gltf, prelude::*};

pub struct GltfFailomatic;

impl Plugin for GltfFailomatic {
    fn build(&self, app: &mut App) {
        app.register_asset_source(
            AssetSourceId::from("gltf"),
            AssetSource::build().with_reader(AssetSource::get_default_reader("foo".into())),
        );
    }
}
fn main() {
    App::new()
        .add_plugins((GltfFailomatic, DefaultPlugins))
        .add_systems(Startup, (setup, setup2))
        .run();
}

fn setup(asset_server: Res<AssetServer>) {
    let _: Handle<Gltf> = asset_server.load("gltf://FlightHelmet.gltf");
}

fn setup2(asset_server: Res<AssetServer>) {
    let _: Handle<Scene> = asset_server.load("gltf://FlightHelmet.gltf#Scene0");
}

```

It seems when loading the `scene.bin` it tries look in the default asset source instead of the one used for the GLTF "parent asset".

### PR DESCRIPTION
**Pull request by andriyDev**
# Objective

- Fixes #10903

## Solution

- Stop using `Path::join` for joining asset paths and instead use `AssetPath::resolve_embed`.

## Testing

- Added 2 tests!

### CODE REVIEW

**Comment by andriyDev** [comment]
As an aside, I think we should remove `LoadContext::path` and just stick to supporting `LoadContext::asset_path`. It seems like a footgun to provide the `std::path::Path` since they don't work with custom asset soruces. If a user who needs the raw `Path`, they can just do `context.asset_path().path()`.

That's for a future PR though.

File: crates/bevy_gltf/src/loader/mod.rs [hunk 1]
```diff
@@ -103,13 +99,19 @@ pub enum GltfError {
     /// Unsupported buffer format.
     #[error("unsupported buffer format")]
     BufferFormatUnsupported,
+    /// The buffer URI was unable to be resolved wrt the asset path.
```
Comment (mockersf) [inline crates/bevy_gltf/src/loader/mod.rs]: Loved the WRT54G!
No extra acronym please :)
```suggestion
    /// The buffer URI was unable to be resolved with regards to the asset path.
```

File: crates/bevy_gltf/src/loader/mod.rs [hunk 2]
```diff
@@ -103,13 +99,19 @@ pub enum GltfError {
...
+    #[error("invalid buffer uri: {0}. asset path error={1}")]
+    InvalidBufferUri(String, ParseAssetPathError),
     /// Invalid image mime type.
     #[error("invalid image mime type: {0}")]
     #[from(ignore)]
     InvalidImageMimeType(String),
     /// Error when loading a texture. Might be due to a disabled image file format feature.
     #[error("You may need to add the feature for the file format: {0}")]
     ImageError(#[from] TextureError),
+    /// The image URI was unable to be resolved wrt the asset path.
```
Comment (mockersf) [inline crates/bevy_gltf/src/loader/mod.rs]:
```suggestion
    /// The image URI was unable to be resolved with regards to the asset path.
```

**Comment by viridia** [comment]
Yes, please, kill it with fire!

File: crates/bevy_gltf/src/loader/mod.rs (hunk 1 above)
Comment (andriyDev) [reply crates/bevy_gltf/src/loader/mod.rs]: Done.

File: crates/bevy_gltf/src/loader/mod.rs (hunk 2 above)
Comment (andriyDev) [reply crates/bevy_gltf/src/loader/mod.rs]: Done.

**Review by mockersf — APPROVED** [review]

**Review by ChristopherBiscardi — APPROVED** [review]

**Comment by andriyDev** [comment]
Wow that random flake actually caught another issue! Apparently materials are doing their own load of the textures, but this load always just fetches the handle from the previous texture loads (since we're still holding those handles).

I've now checked to make sure there are no other `join`s so we shouldn't have any more of these issues.

As an aside, I don't think there's a need for us to be doing a second load for the materials. We should just propagate the texture handles through to these functions so they can get the texture handles that way. Having the loads just happen to call the same path seems incredibly brittle. Another PR though haha.

Edit: I looked into why we need a second load for the materials. The problem is that we **only** update the dependencies of a subasset if there is a load involved. If we just passed in the texture handles, we wouldn't get that load, so our material wouldn't have the texture as a dependency, meaning the is_loaded_with_dependencies check would be wrong. We should probably just be calling `VisitDependencies` in the load_context to solve this at some point.
