### PR TITLE
Fix untyped labeled asset loading

### LINKED ISSUE #10436: load_untyped has issues loading scenes from gltf files
## Bevy version

0.12.0

## What you did

Load a scene using `AssetServer#load_untyped`

The following code crashes with a type Id miss match:
```rust
use std::any::TypeId;
use bevy::asset::LoadedUntypedAsset;
use bevy::gltf::Gltf;
use bevy::prelude::*;

fn main() {
    App::new()
        .add_plugins(DefaultPlugins)
        .add_systems(Startup, load)
        .run();
}

#[derive(Resource)]
struct MyHandle(Handle<LoadedUntypedAsset>);

fn load(mut commands: Commands, asset_server: Res<AssetServer>) {
    println!("untyped {:?} scene {:?} gltf {:?}", TypeId::of::<LoadedUntypedAsset>(), TypeId::of::<Scene>(), TypeId::of::<Gltf>());
    commands.insert_resource(MyHandle(asset_server.load_untyped("models/AlienCake/alien.glb#Scene0")))
}
```
The app does not crash when directly loading the asset as a `Handle<Scene>` (as expected).

## What went wrong

This crashes because at some point it expects a handle Id to have a different type id than it actually has (seems to be `Gltf` instead of the expected `Scene`).

Log and partial stack trace from running the code above as an example:
```log
2023-11-08T16:58:33.116118Z  INFO bevy_winit::system: Creating new window "App" (0v0)
2023-11-08T16:58:33.116695Z  INFO winit::platform_impl::platform::x11::window: Guessed window scale factor: 1    
2023-11-08T16:58:33.320571Z  INFO bevy_render::renderer: AdapterInfo { name: "NVIDIA RTX 2000 Ada Generation Laptop GPU", vendor: 4318, device: 10424, device_type: DiscreteGpu, driver: "NVIDIA", driver_info: "535.129.03", backend: Vulkan }
untyped TypeId { t: 52159753730012975514151558583186680988 } scene TypeId { t: 312902742491752564684897985457935864593 } gltf TypeId { t: 129217342951176499515112392938364371523 }
2023-11-08T16:58:33.575293Z  INFO bevy_diagnostic::system_information_diagnostics_plugin::internal: SystemInfo { os: "Linux 22.04 Ubuntu", kernel: "6.2.0-36-generic", cpu: "13th Gen Intel(R) Core(TM) i9-13950HX", core_count: "24", memory: "62.5 GiB" }
thread 'main' panicked at /home/niklas/code/bevy/crates/bevy_asset/src/id.rs:266:9:
assertion `left == right` failed: The target AssetId<bevy_scene::scene::Scene>'s TypeId does not match the TypeId of this UntypedAssetId
  left: TypeId { t: 129217342951176499515112392938364371523 }
 right: TypeId { t: 312902742491752564684897985457935864593 }
stack backtrace:
  <-- snip assert failure/panicing and unwinding --> 
  18:     0x55c495afe2c9 - bevy_asset::id::UntypedAssetId::typed::h23a6c230e3c26f34
                               at /home/niklas/code/bevy/crates/bevy_asset/src/id.rs:266:9
  19:     0x55c494f3b3b9 - <A as bevy_asset::loader::AssetContainer>::insert::h699f3d5e5a4a5014
                               at /home/niklas/code/bevy/crates/bevy_asset/src/loader.rs:238:50
  20:     0x55c497093e92 - bevy_asset::server::info::AssetInfos::process_asset_load::h1bfe159cce1417a5
                               at /home/niklas/code/bevy/crates/bevy_asset/src/server/info.rs:309:9
  21:     0x55c49711bb8d - bevy_asset::server::handle_internal_asset_events::{{closure}}::h50063b5502c785a4
                               at /home/niklas/code/bevy/crates/bevy_asset/src/server/mod.rs:856:21
  22:     0x55c497027e88 - bevy_ecs::world::World::resource_scope::h49aa2bd32f19e8ad
                               at /home/niklas/code/bevy/crates/bevy_ecs/src/world/mod.rs:1571:22
  23:     0x55c49702d05b - bevy_asset::server::handle_internal_asset_events::h323538561b60f547
                               at /home/niklas/code/bevy/crates/bevy_asset/src/server/mod.rs:851:5
  <-- snip system calling --> 
Encountered a panic in exclusive system `bevy_asset::server::handle_internal_asset_events`!
Encountered a panic in system `bevy_app::main_schedule::Main::run_main`!
```

## Additional information

This currently breaks loading scenes in `bevy_asset_loader`

### PR DESCRIPTION
**Pull request by cart**
# Objective

Fixes #10436
Alternative to #10465 

## Solution

`load_untyped_async` / `load_internal` currently has a bug. In `load_untyped_async`, we pass None into `load_internal` for the `UntypedHandle` of the labeled asset path. This results in a call to `get_or_create_path_handle_untyped` with `loader.asset_type_id()`
This is a new code path that wasn't hit prior to the newly added `load_untyped` because `load_untyped_async` was a private method only used in the context of the `load_folder` impl (which doesn't have labels)

The fix required some refactoring to catch that case and defer handle retrieval. I have also made `load_untyped_async` public as it is now "ready for public use" and unlocks new scenarios.

### CODE REVIEW

**Comment by alice-i-cecile** [comment]
@Selene-Amanita, can you test and review this please?

File: crates/bevy_asset/src/server/mod.rs [hunk 1]
```diff
@@ -379,35 +379,48 @@ impl AssetServer {
...
-                requested: handle.type_id(),
-                actual_asset_name: loader.asset_type_name(),
-                loader_name: loader.type_name(),
-            });
-        }
-
-        if !should_load && !force {
-            return Ok(handle);
-        }
+        let handle = if let Some((handle, should_load)) = handle_result {
```
Comment (cart) [inline crates/bevy_asset/src/server/mod.rs:407]: Realized one hangup with this approach: this means that loading a labeled untyped asset multiple times won't always "early out" for duplicate asset loads. If a second duplicate request for a labeled untyped asset is made before the labeled asset handle is allocated in the AssetLoader, a second load of the root asset will occur.

This isn't broken, but it is suboptimal / undesirable behavior. I'm not sure we can fix this without changing how handles work.

Notably, I think moving to "assets as entities" (or an equivalent "universal id with indirection" system) resolves this problem because you no longer need to know the type to allocate an identifier. This would also allow us to "de-async-ify" untyped asset loading, which is one of the pain points people are experiencing with Bevy Asset V2.

However for a patch release, I think these changes are probably still the move (unless we can find a way to prevent double-loads). I'll give this a bit more thought / if anyone else has ideas let me know.

**Comment by Braymatter** [comment]
Looks good to me

File: crates/bevy_asset/src/server/info.rs [hunk 2]
```diff
@@ -167,20 +170,25 @@ impl AssetInfos {
...
+        unwrap_with_context(result, type_name).unwrap()
     }
 
     /// Retrieves asset tracking data, or creates it if it doesn't exist.
     /// Returns true if an asset load should be kicked off
     pub fn get_or_create_path_handle_internal(
         &mut self,
         path: AssetPath<'static>,
-        type_id: TypeId,
+        type_id: Option<TypeId>,
```
Comment (alice-i-cecile) [inline crates/bevy_asset/src/server/info.rs:188]: Technically this a breaking change, but I'm fine with it in a bug fix.

Actually, why is this "internal" method pub at all?

File: crates/bevy_asset/src/server/info.rs [hunk 3]
```diff
@@ -624,13 +637,22 @@ pub(crate) enum HandleLoadingMode {
 #[error("Cannot allocate a handle because no handle provider exists for asset type {0:?}")]
 pub struct MissingHandleProviderError(TypeId);
 
-fn unwrap_with_context<T>(
-    result: Result<T, MissingHandleProviderError>,
+#[derive(Error, Debug)]
+pub enum GetOrCreateHandleInternalError {
```
Comment (alice-i-cecile) [inline crates/bevy_asset/src/server/info.rs:641]: Doc strings would be nice here? This is kind of a weird error type, and it's not clear how one might extend it or use it elsewhere.

File: crates/bevy_asset/src/server/mod.rs (hunk 1 above)
Comment (alice-i-cecile) [reply crates/bevy_asset/src/server/mod.rs:407]: I'm fine to ship with this behavior, especially for a patch release.

File: crates/bevy_asset/src/server/mod.rs [hunk 4]
```diff
@@ -281,7 +281,7 @@ impl AssetServer {
     }
 
     #[must_use = "not using the returned strong handle may result in the unexpected release of the asset"]
-    pub(crate) async fn load_untyped_async<'a>(
+    pub async fn load_untyped_async<'a>(
```
Comment (NiklasEi) [inline crates/bevy_asset/src/server/mod.rs:284]: Now that it's public, we could add some docs and maybe point to the alternative API that "hides" the async.

File: crates/bevy_asset/src/server/mod.rs (hunk 1 above)
Comment (NiklasEi) [reply crates/bevy_asset/src/server/mod.rs:407]: Shall we open an issue to keep track of this?

**Review by NiklasEi — APPROVED** [review]
I verified that this fixes the original problem and the changes look fine to me.

File: crates/bevy_asset/src/server/mod.rs (hunk 1 above)
Comment (cart) [reply crates/bevy_asset/src/server/mod.rs:412]: Opened an issue and added a note to the code!

File: crates/bevy_asset/src/server/info.rs (hunk 2 above)
Comment (cart) [reply crates/bevy_asset/src/server/info.rs:188]: Very good question! Sadly closing this up would be a breaking change so probably shouldn't happen in a patch release :)

Comment (cart) [reply crates/bevy_asset/src/server/info.rs:188]: Although I guess we're already breaking it. Screw it lets close it up. Theres no way anyone is using this.

**Review by alice-i-cecile — APPROVED** [review]
