### PR TITLE
Make scene handling of entity references robust

### LINKED ISSUE #4793: DynamicScenes contain invalid Entity references
## Bevy version

Commit hash: 15acd6f45deb3cd21d1f3a9e7d39d135068f09c5 (post v0.7.0)

## Bug description

Minimal example
<details>

  ```rust
  use bevy::{ecs::entity::EntityMap, prelude::*};

  fn main() {
    App::new()
      .add_plugins(DefaultPlugins)
      .add_startup_system(save_scene_system)
      .run();
  }

  #[derive(Resource)]
  pub struct StoredScene(Option<DynamicScene>);

  fn save_scene_system(world: &mut World) {
    let mut scene_world = World::new();

    // Uncomment the following lines to cause the bug!
    let child = scene_world.spawn(()).id();
    scene_world.despawn(child);

    let child = scene_world.spawn(()).id();

    scene_world.spawn(()).push_children(&[child]);

    let type_registry = world.resource::<AppTypeRegistry>();
    let scene = DynamicScene::from_world(&scene_world, type_registry);

    println!("{}", scene.serialize_ron(type_registry).unwrap());

    scene
      .write_to_world(world, &mut EntityMap::default())
      .unwrap();
  }

  ```
</details>

When applying `DynamicScene`s to a world using write_to_world, the operation will sometimes panic.
(more specifically, it will crash if the DynamicScene was created from any entities with a generation != 0 which belong to a hierarchy)

## Cause

DynamicScenes store entities without their generation, which makes sense because the simple ids are transiently unique.

However, `Entity`s stored in components (such as `Parent` or `Children`) still contain the generation.

This means that upon applying the `DynamicScene`, the mapping phase of write_to_world will try to map the "generationful" `Entity`s and will fail to find them in the map (because the map only has a 0-generation for its keys).

### Important note

OUTDATED
~~I believe most people never encounter this problem, because DynamicScenes are mainly used alongside serialization, and serialization of an `Entity` strips it of its generation already. (I didn't find where in the codebase but it's what I deduce)~~

UPDATE:
The workaround above no longer works as per #6194 

## Proposed fix

OUTDATED
~~I believe we would simply need to add a prior mapping phase in DynamicScene::from_world to strip the generation of all `Entity`s contained in components.
I will file a PR soon. Nevermind, I am not well-enough versed in the deep arts of reflection~~

UPDATE:
Since the arguments in #6194 are convincing that serializing the generation is useful, I think we need another solution.
Possibly, storing the generation in the DynamicScenes

### PR DESCRIPTION
**Pull request by Illiux**
# Objective

- Handle dangling entity references inside scenes
- Handle references to entities with generation > 0 inside scenes
- Fix a latent bug in `Parent`'s `MapEntities` implementation, which would, if the parent was outside the scene, cause the scene to be loaded into the new world with a parent reference potentially pointing to some random entity in that new world.
- Fixes #4793 and addresses #7235 

## Solution

- DynamicScenes now identify entities with a `Entity` instead of a u32, therefore including generation
- `World` exposes a new `reserve_generations` function that despawns an entity and advances its generation by some extra amount.
- `MapEntities` implementations have a new `get_or_reserve` function available that will always return an `Entity`, establishing a new mapping to a dead entity when the entity they are called with is not in the `EntityMap`. Subsequent calls with that same `Entity` will return the same newly created dead entity reference, preserving equality semantics.
- As a result, after loading a scene containing references to dead entities (or entities otherwise outside the scene), those references will all point to different generations on a single entity id in the new world.

---

### Changed
- In serialized scenes, entities are now identified by a u64 instead of a u32.
- In serialized scenes, components with entity references now have those references serialize as u64s instead of structs.
### Fixed
- Scenes containing components with entity references will now deserialize and add to a world reliably.

## Migration Guide

- `MapEntities` implementations must change from a `&EntityMap` parameter to a `&mut EntityMapper` parameter and can no longer return a `Result`. Finally, they should switch from calling `EntityMap::get` to calling `EntityMapper::get_or_reserve`.

### CODE REVIEW

File: crates/bevy_ecs/src/entity/map_entities.rs [hunk 1]
```diff
@@ -70,6 +70,55 @@ pub struct EntityMap {
     map: HashMap<Entity, Entity>,
 }
 
+pub struct EntityMapper<'m> {
```
Comment (alice-i-cecile) [inline crates/bevy_ecs/src/entity/map_entities.rs:73]: Doc strings needed.

File: crates/bevy_ecs/src/entity/map_entities.rs [hunk 2]
```diff
@@ -70,6 +70,55 @@ pub struct EntityMap {
...
+    map: &'m mut EntityMap,
+    dead_start: Entity,
+    generations: u32,
+}
+
+impl<'m> EntityMapper<'m> {
+    /// Reserves the allocated dead entities within the world.
```
Comment (alice-i-cecile) [inline crates/bevy_ecs/src/entity/map_entities.rs:80]: It's unclear what "dead" means here.

File: crates/bevy_ecs/src/entity/map_entities.rs [hunk 3]
```diff
@@ -70,6 +70,55 @@ pub struct EntityMap {
     map: HashMap<Entity, Entity>,
 }
 
+pub struct EntityMapper<'m> {
+    map: &'m mut EntityMap,
+    dead_start: Entity,
```
Comment (alice-i-cecile) [inline crates/bevy_ecs/src/entity/map_entities.rs:75]: Doc strings on all these fields too: this is complex, even if it's internal.

File: crates/bevy_ecs/src/entity/map_entities.rs [hunk 4]
```diff
@@ -70,6 +70,55 @@ pub struct EntityMap {
...
+
+        self.map.insert(entity, new);
+
+        new
+    }
+}
+
+impl<'m> Drop for EntityMapper<'m> {
+    fn drop(&mut self) {
+        assert_eq!(
```
Comment (alice-i-cecile) [inline crates/bevy_ecs/src/entity/map_entities.rs:115]: I'm unsure about panicking here. Can you justify why it needs to panic with a comment?

File: crates/bevy_ecs/src/entity/map_entities.rs [hunk 5]
```diff
@@ -122,4 +171,17 @@ impl EntityMap {
     pub fn iter(&self) -> impl Iterator<Item = (Entity, Entity)> + '_ {
         self.map.iter().map(|(from, to)| (*from, *to))
     }
+
+    /// Gets an [`EntityMapper`] for allocating new dead entities.
+    ///
+    /// # Safety
+    /// If this function is called, [`EntityMapper::save()`] _must_ be subsequently called after mapping.
```
Comment (alice-i-cecile) [inline crates/bevy_ecs/src/entity/map_entities.rs:178]: This isn't a safety concern in the way Rusts uses `unsafe`. Very much worth calling out, but unfortunately we can't / shouldn't make this `unsafe`.

My kingdom for new colors of unsafe...

File: crates/bevy_ecs/src/world/mod.rs [hunk 6]
```diff
@@ -946,8 +962,8 @@ impl World {
         match self.get_resource() {
             Some(x) => x,
             None => panic!(
-                "Requested resource {} does not exist in the `World`.
```
Comment (alice-i-cecile) [inline crates/bevy_ecs/src/world/mod.rs:949]: I'm unsure if removing trailing whitespace will do what we want. Either way, this is noise in a tricky PR: can you please remove this set of changes?

File: crates/bevy_scene/src/dynamic_scene.rs [hunk 7]
```diff
@@ -29,7 +29,7 @@ pub struct DynamicScene {
 /// A reflection-powered serializable representation of an entity and its components.
 pub struct DynamicEntity {
     /// The transiently unique identifier of a corresponding `Entity`.
-    pub entity: u32,
+    pub entity: u64,
```
Comment (alice-i-cecile) [inline crates/bevy_scene/src/dynamic_scene.rs:32]: At this point, why not store a proper `Entity` here?

File: crates/bevy_scene/src/dynamic_scene.rs [hunk 8]
```diff
@@ -29,7 +29,7 @@ pub struct DynamicScene {
 /// A reflection-powered serializable representation of an entity and its components.
 pub struct DynamicEntity {
     /// The transiently unique identifier of a corresponding `Entity`.
```
Comment (alice-i-cecile) [inline crates/bevy_scene/src/dynamic_scene.rs:31]: This doc string could be more helpful and clear.

**Review by alice-i-cecile — CHANGES_REQUESTED** [review]
Very much like the technical elements of the changes, but this is rather tricky, so I'm being strict on code quality / docs.

File: crates/bevy_scene/src/dynamic_scene.rs (hunk 7 above)
Comment (Illiux) [reply crates/bevy_scene/src/dynamic_scene.rs:32]: A benefit to doing it this way is that it's backwards compatible with existing scenes in most scene formats. They'll deserialize as <whatever>v0 as they do today, and as a side effect using an `Entity` here will increase the blast radius somewhat (breaks more existing tests and, if I recall correctly, examples). I also kinda prefer the serialization from `to_bits` instead of the struct serialization you get from putting an `Entity` here as it's more succinct and generation/id should be internal anyway.

File: crates/bevy_ecs/src/world/mod.rs (hunk 6 above)
Comment (Illiux) [reply crates/bevy_ecs/src/world/mod.rs:949]: Yup, I didn't notice this get in here and I have my editor set to do this automatically.

File: crates/bevy_ecs/src/entity/map_entities.rs [hunk 9]
```diff
@@ -70,6 +70,55 @@ pub struct EntityMap {
...
+    dead_start: Entity,
+    generations: u32,
+}
+
+impl<'m> EntityMapper<'m> {
+    /// Reserves the allocated dead entities within the world.
+    pub fn save(mut self, world: &mut World) {
+        if self.generations == 0 {
+            return;
+        }
```
Comment (Illiux) [inline crates/bevy_ecs/src/entity/map_entities.rs:84]: Leaving a comment for myself here as I noticed this when going over feedback - this short-circuit forgets to despawn the entity

File: crates/bevy_ecs/src/entity/map_entities.rs (hunk 4 above)
Comment (Illiux) [reply crates/bevy_ecs/src/entity/map_entities.rs:115]: I'll put a comment in the code too, but I was concerned that were `save()` not called and the application to continue, the resulting bugs would be weird and subtle, since you'd end up with entity references pointing at _future_ generations, so in some applications they would initially function alright but suddenly point to a living entity later on in the application. I suspect that would result in quite maddening behavior to root cause, so I wanted to fail-fast and immediately panic rather than leave the application in that state. Does that seem sensible?

File: crates/bevy_scene/src/dynamic_scene.rs (hunk 7 above)
Comment (alice-i-cecile) [reply crates/bevy_scene/src/dynamic_scene.rs:32]: Okay, I'm happy with that justification.

File: crates/bevy_ecs/src/entity/map_entities.rs (hunk 5 above)
Comment (SkiFire13) [reply crates/bevy_ecs/src/entity/map_entities.rs:178]: Maybe this could be rewritten with a closure based API?

```rust
pub fn with_mapper<R>(&mut self, world: &mut World, f: impl FnOnce(&mut EntityMapper, &mut World) -> R) -> R {
    let mut mapper = EntityMapper {
        map: self,
        dead_start: world.spawn_empty().id(),
        generations: 0,
    };
    let result = f(&mut mapper, world);
    mapper.save(world);
    result
}
```

Comment (Illiux) [reply crates/bevy_ecs/src/entity/map_entities.rs:178]: I like the idea of going with the closure based API.

File: crates/bevy_ecs/src/entity/map_entities.rs (hunk 4 above)
Comment (Illiux) [reply crates/bevy_ecs/src/entity/map_entities.rs:115]: This is mooted by going with the closure-based API suggested below.

File: crates/bevy_scene/src/dynamic_scene.rs (hunk 7 above)
Comment (Shatur) [reply crates/bevy_scene/src/dynamic_scene.rs:32]: I would use `Entity` for clarity.

Comment (Illiux) [reply crates/bevy_scene/src/dynamic_scene.rs:33]: In that case would it maybe be reasonable to also change `Entity` to (de)serialize as `to_bits` and `from_bits`?

Comment (Shatur) [reply crates/bevy_scene/src/dynamic_scene.rs:33]: What benefits does it provide?

Comment (Illiux) [reply crates/bevy_scene/src/dynamic_scene.rs:33]: In this context, the aforementioned backwards compatibility with existing scenes is a direct technical benefit. But in general, it keeps generation/index a little more internal, since `Entity` should be treated as an opaque identifier by users and, probably, by anything outside `bevy_ecs`, at least in my opinion. Within bevy itself, the only place generation or index is used outside `bevy_ecs` at the moment is a tiny bit of `bevy_sprite`. It'd actually be quite possible to move the accessors to `pub(crate)`.

Comment (Illiux) [reply crates/bevy_scene/src/dynamic_scene.rs:33]: Oh actually, I suppose if we switch to `Entity` and change the serialization it breaks backwards compatibility anyway because it'd change how component entity references serialize. So the only thing that doesn't break compatibility is the current `u64` approach.

**Review by alice-i-cecile — COMMENTED** [review]
Much better docs, and I really like the closure based API. Why not bake this in directly to `EntityMap`? It's unclear when you would be okay to forgo the guarantees provided here.

File: crates/bevy_scene/src/dynamic_scene.rs (hunk 7 above)
Comment (Shatur) [reply crates/bevy_scene/src/dynamic_scene.rs:33]: I would break the compatibility. We did it literally in the previous release. But it will result in a cleaner API.

**Comment by Illiux** [comment]
> Much better docs, and I really like the closure based API. Why not bake this in directly to `EntityMap`? It's unclear when you would be okay to forgo the guarantees provided here.

I'm not sure I see a good way to do that that both preserves safety and doesn't make the API more awkward. Baked into `EntityMap` we either have an extra bit of state (has a `dead_start` or doesn't, making `dead_start` have to be `Option<Entity>`) or we push the initialization and saving out to code setting up the `EntityMap`. In the first case, the result would be `get_or_alloc` either panicking or returning `Option<Entity>` instead of entity. In the second we can't use the closure approach to ensure safety anymore. Also in the first case, it becomes possible to bypass `with_mapper`.

File: crates/bevy_scene/src/dynamic_scene.rs (hunk 7 above)
Comment (Illiux) [reply crates/bevy_scene/src/dynamic_scene.rs]: Okay I went with that. I still think changing `Entity`'s serialization is probably worth doing but it doesn't need to be coupled with this change.

**Comment by cart** [comment]
Making this controversial because this is taking scene ids in a new-ish direction. Scenes should have "virtual self contained identity spaces" that don't (necessarily) correspond to real world entities. Introducing generation (especially for "top level" entities in the scene) makes the scene format longer / harder to read and compose (just look at the diffs in the scene files). Generation isn't a useful part of the of "scene mental model". Introducing generation also encourages people to think about "runtime ids" as the same thing as scene ids.

There _is_ definitely an issue in the current approach when it comes to uniqueness. `( id: 4, gen: 0)` and `(id: 4, gen: 1)` should not be considered the same thing. And dandling ids _should_ be accounted for.

Some alternative ideas to consider:

* Serialize scene entity ids as u64s (laid out as `[id_u32][generation_u32]`). Treat that as just a simpler encoding of `(id: u32, generation: u32)`
* When serializing, just create a brand new `Entity->SceneId` mapping and allocate new SceneIds as new entities are encountered.

Curious what the reflection SMEs think: @MrGVSV @jakobhellermann

**Comment by Illiux** [comment]
> * Serialize scene entity ids as u64s (laid out as `[id_u32][generation_u32]`). Treat that as just a simpler encoding of `(id: u32, generation: u32)`

Amusingly, this is actually what the initial version of this PR did (well, almost: it was `[generation_u32][id_u32]` since it used the existing `Entity::to_bits()`). Check out the now-resolved thread off the first comment alice left on `dynamic_scene.rs`. I think it makes sense for `Entity` to serialize like this everywhere, though I was going to put that into a separate PR.

> * When serializing, just create a brand new Entity->SceneId mapping and allocate new SceneIds as new entities are encountered.

This is very difficult to do because we currently can't look inside components with entity references when serializing, and so we can't allocate SceneIds for dangling references. It would be a much, much larger change to start doing that. We could serialize the entity IDs as SceneIds but the component entity references would still be `Entity`.

**Comment by Illiux** [comment]
I went ahead an added a commit that goes back to serializing entity identifiers as u64s, but via changing the implementation of `Serialize` and `Deserialize` on `Entity` so that the API improvements in `DynamicScene` are retained and component entity references are also similarly affected.

File: crates/bevy_ecs/src/entity/mod.rs [hunk 10]
```diff
@@ -110,7 +110,7 @@ type IdCursor = isize;
 /// [`EntityCommands`]: crate::system::EntityCommands
 /// [`Query::get`]: crate::system::Query::get
 /// [`World`]: crate::world::World
-#[derive(Clone, Copy, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
+#[derive(Clone, Copy, Eq, Hash, Ord, PartialEq, PartialOrd)]
```
Comment (Shatur) [inline crates/bevy_ecs/src/entity/mod.rs:113]: Please, remove serde macro dependency on `bevy_ecs` since it no longer needed.

**Comment by djeedai** [comment]
> I went ahead and added a commit that goes back to serializing entity identifiers as u64s, but via changing the implementation of `Serialize` and `Deserialize` on `Entity` instead of the earlier approach via holding a u64 in `DynamicEntity`. This way, the API improvements in `DynamicScene` are retained and component entity references are also similarly affected.

Well, as cart explained above and I coincidentally tried to explain on Discord, using `Entity` instead of `u64` is confusing because it makes it look like we somewhat care about the exact `Entity` value. We don't; we just need a unique identifier, and keeping `u64` is more clear in my opinion.

> This is very difficult to do because we currently can't look inside components with entity references when serializing, and so we can't allocate SceneIds for dangling references nor serialize component entity references as SceneIds.

Can't we bake that logic into the serialization implementation of `Entity`?

File: crates/bevy_ecs/src/entity/mod.rs [hunk 11]
```diff
@@ -590,6 +609,22 @@ impl Entities {
         self.meta.get_unchecked_mut(index as usize).location = location;
     }
 
+    /// Increments the generation of a despawned [`Entity`]. This may only be called on an entity
+    /// index corresponding to an entity that once existed and has since been freed.
+    pub(crate) fn reserve_generations(&mut self, index: u32, generations: u32) -> bool {
```
Comment (djeedai) [inline crates/bevy_ecs/src/entity/mod.rs:614]: Maybe keep the convention of prefixing methods returning a boolean result with `try_`?

**Review by djeedai — COMMENTED** [review]
Fine as a quick fix, but I'm not a huge fan of doubling the size of all serialized entities just to guarantee unicity inside a serialized blob. If we prove that there's no other way then fine, but I'm not sure we've explored enough alternatives like remapping on serialization, or patching after serialization.

**Comment by Illiux** [comment]
> Can't we bake that logic into the serialization implementation of Entity?

Not without very significant complexity and tradeoffs, as far as I can tell. To map within serialization would require extra state on the serializer used within `Entity` in order to store the mapping table, which in turn means that we couldn't implement the `serde` traits. That would have major fallout, causing any component with an `Entity` in it to also be unable to implement `Serialize` or `Deserialize` and bevy to basically have to roll its own serialization. This is made especially worse because components don't need to be serialized directly via bevy reflection, they can delegate to `Serialize`/`Deserialize`.

> Look like we somewhat care about the exact Entity value. We don't;

Currently, we actually do. The components contained in that `Vec<Box<dyn Reflect>>` just underneath `pub entity: Entity` in `DynamicEntity` can contain `Entity`s inside them, and they have to exactly match the top-level entity identifiers in the scene.

File: crates/bevy_ecs/src/entity/mod.rs (hunk 11 above)
Comment (Illiux) [reply crates/bevy_ecs/src/entity/mod.rs:614]: Is that a convention bevy holds to? Right now we have `World::despawn` instead of `World::try_despawn`, for instance.

Comment (alice-i-cecile) [reply crates/bevy_ecs/src/entity/mod.rs:614]: Only loosely :( It's a good convention, although I like it even better when it returns results.

Comment (djeedai) [reply crates/bevy_ecs/src/entity/mod.rs:614]: Yes, it's also present in the standard library, and in other languages like C#. I generally like using it if I can to make the returned `bool` a bit more self-documented.

**Comment by djeedai** [comment]
> which in turn means that we couldn't implement the serde traits.

We already have the problem with deserialization though, where we need the type registry for example to correctly deserialize dynamic objects. So are we gaining much by restricting ourselves in the serialization side only?

> We support several different serialized formats (ron, messagepack, postcard, bincode). This seems nightmarish.

I didn't mean patching the final blob, but rather the intermediate memory representation in serde's data model, which is independent of the format. But maybe that's not possible?

> Currently, we actually do. The components contained in that Vec<Box<dyn Reflect>> just underneath pub entity: Entity in DynamicEntity can contain Entitys inside them, and they have to exactly match the top-level entity identifiers in the scene.

As far as I understand that's incorrect, the _serialized_ representation of the `Entity` reference in the serialized component has to match the one of the serialized `Entity` itself. But nothing forces that representation to be `(id, generation)`. It could be any unique identifier, even a linearly allocated index. It's just that `[id][generation]` is a convenient candidate because it can be derived from the `Entity` without further context. A linearly allocated index or a GUID would require a stateful serialization.

> If worlds can contain u32::MAX entities with u32::MAX generations on each of them, then you need just as many bits in the scene format if you want to be able to save every possible world.

But that's just unrealistic. Except for stale references which I hope are a minority, each ID is present as a single generation in the `World` at a given time. So a full `u64` is overkill.

File: crates/bevy_ecs/src/entity/mod.rs (hunk 11 above)
Comment (djeedai) [reply crates/bevy_ecs/src/entity/mod.rs:614]: That's a minor suggestion though feel free to ignore.

**Comment by Illiux** [comment]
> > which in turn means that we couldn't implement the serde traits.
> 
> We already have the problem with deserialization though, where we need the type registry for example to correctly deserialize dynamic objects. So are we gaining much by restricting ourselves in the serialization side only?

The type registry is passed around in both serialization and deserialization, and the extra state represented by a mapping table could be too. Where it isn't passed is where `bevy_reflect` delegates to serde implementations via `reflect_value`. What you'd be losing is `reflect_value` support for any component containing an entity reference. That seems to me to be a rather enormous loss. `bevy_reflect` would also have to become explicitly aware of this mapping and introduce special handling for `Entity` (which right now is itself handled via `reflect_value`), representing a good bit of  new complexity and some extra coupling (at the moment, `bevy_reflect` doesn't even reference `Entity` anywhere). If we go this route a thread-local static is probably the better solution, ugly as it would be. That or working with serde to try to upstream some kind of better stateful (de)serialization support. The upshot of this would be making `MapEntities` unnecessary though.

> > We support several different serialized formats (ron, messagepack, postcard, bincode). This seems nightmarish.
> 
> I didn't mean patching the final blob, but rather the intermediate memory representation in serde's data model, which is independent of the format. But maybe that's not possible?

I'm not sure whether or not this is possible.

> > Currently, we actually do. The components contained in that Vec<Box> just underneath pub entity: Entity in DynamicEntity can contain Entitys inside them, and they have to exactly match the top-level entity identifiers in the scene.
> 
> As far as I understand that's incorrect, the _serialized_ representation of the `Entity` reference in the serialized component has to match the one of the serialized `Entity` itself. But nothing forces that representation to be `(id, generation)`. It could be any unique identifier, even a linearly allocated index. It's just that `[id][generation]` is a convenient candidate because it can be derived from the `Entity` without further context. A linearly allocated index or a GUID would require a stateful serialization.

Here I am talking about `DynamicScene` and `DynamicEntity` which are a pre-serialized representation. `DynamicEntity` should hold an `Entity` as its ID because the `dyn Reflect` objects in its component list hold `Entity` in their fields. Any mapping would happen after this point. Right now it's far downstream in `MapEntities` but in some world where the mapping is handled in (de)serialization, `DynamicScene` is going to be before that mapping in the serialization case and after the corresponding mapping in the deserialization case. Thus, it should hold `Entity`.

> > If worlds can contain u32::MAX entities with u32::MAX generations on each of them, then you need just as many bits in the scene format if you want to be able to save every possible world.
> 
> But that's just unrealistic. Except for stale references which I hope are a minority, each ID is present as a single generation in the `World` at a given time. So a full `u64` is overkill.

A world could potentially contain u32::MAX stale references to different generations on the same index. I think that if you can represent it in a world you should be able to represent it in a scene. It's unrealistic to actually have u32::MAX entities, but is that an argument for using a u16 in the scene representation? The fact of the matter is that the ID space for entities consists of u64::MAX possible IDs. And really, I don't think anything outside `bevy_ecs` should be looking at generation or index anyway, rendering `Entity` a 64-bit wide identifier. The stale reference use case cannot be sidelined, and the ID space of references is 64 bits wide due to their ability to refer to dead entities, despite the id space of living entities being only 32 bits wide.

File: crates/bevy_ecs/src/entity/mod.rs (hunk 11 above)
Comment (Illiux) [reply crates/bevy_ecs/src/entity/mod.rs:614]: I was copying the pattern in `despawn` since `reserve_generations` is sort of an extension of it. I'll maybe switch this to returning a result or at least rename it.

**Comment by Illiux** [comment]
I've spent a few hours reading code and contemplating things and have some further thoughts.

> > > which in turn means that we couldn't implement the serde traits.
> > 
> > 
> > We already have the problem with deserialization though, where we need the type registry for example to correctly deserialize dynamic objects. So are we gaining much by restricting ourselves in the serialization side only?
> 
> The type registry is passed around in both serialization and deserialization, and the extra state represented by a mapping table could be too. Where it isn't passed is where `bevy_reflect` delegates to serde implementations via `reflect_value`. What you'd be losing is `reflect_value` support for any component containing an entity reference. That seems to me to be a rather enormous loss. `bevy_reflect` would also have to become explicitly aware of this mapping and introduce special handling for `Entity` (which right now is itself handled via `reflect_value`), representing a good bit of new complexity and some extra coupling (at the moment, `bevy_reflect` doesn't even reference `Entity` anywhere). If we go this route a thread-local static is probably the better solution, ugly as it would be. That or working with serde to try to upstream some kind of better stateful (de)serialization support. The upshot of this would be making `MapEntities` unnecessary though.

The thread-local solution actually doesn't seem so bad, though it has some tradeoffs. One of those is a good deal more internal complexity, though it would be possible to remove the need for `MapEntities`. 

> > > If worlds can contain u32::MAX entities with u32::MAX generations on each of them, then you need just as many bits in the scene format if you want to be able to save every possible world.
> > 
> > 
> > But that's just unrealistic. Except for stale references which I hope are a minority, each ID is present as a single generation in the `World` at a given time. So a full `u64` is overkill.
> 
> A world could potentially contain u32::MAX stale references to different generations on the same index. I think that if you can represent it in a world you should be able to represent it in a scene. It's unrealistic to actually have u32::MAX entities, but is that an argument for using a u16 in the scene representation? The fact of the matter is that the ID space for entities consists of u64::MAX possible IDs. And really, I don't think anything outside `bevy_ecs` should be looking at generation or index anyway, rendering `Entity` a 64-bit wide identifier. The stale reference use case cannot be sidelined, and the ID space of references is 64 bits wide due to their ability to refer to dead entities, despite the id space of living entities being only 32 bits wide.

I've realized that what I wrote here is false, or at least misleading. The approach in this PR allows for only `u32::MAX - 1` dead references before the allocation method in `EntityMapper` runs out of space, not the full 64 bits of id space `Entity` represents. Second, because it's true that `u32` is enough to represent the space of living entities, it should be enough for the `entity` field on `DynamicEntity`. More bits would be necessary only for component entity references. I do think that ability to match the ID space of a world is a plus factor for potential solutions.

The existing `MapEntities` trait turns out to be enough to do the needed mapping if it's used between `DynamicScene` construction and scene serialization.

##### Thread local (de)serializer state

The thread local approach seems worth prototyping, and I have an idea for it that seems to have a decent balance of tradeoffs, one of the largest being that it adds a lot of complexity internal to bevy. The sketch of it is as follows:

* Scenes represent top-level entity IDs as u32
* Component entity references are represented as i64, where positive numbers are living entities and negative are dead
  * i32 could also be used but this has further tradeoffs
* `Entities` gets a new method that gets an allocator struct, capable of allocating new living and dead entity IDs that can be later saved back to the original `Entities` struct so long as no other allocations have happened in-between

Serialization would look roughly like:

1. Top-level Entity IDs are assigned to integer IDs ascending from 0
2. They are then used to initialize an entity map, mapping from source world `Entity` IDs to i64 destination IDs
4. The map is saved to a thread local `RefCell`
5. Serialization happens
    1. Inside `Entity`'s `Serialize` implementation, component entity refs get mapped to existing IDs in the map, and new IDs are allocated descending from -1 if no entry is present
6. The thread local is unset

Deserialization would look roughly like:

1. The above struct gets set to a thread local `RefCell`
1. Deserialization happens
    1. Inside `Entity`'s `Deserialize` implementation, component entity refs get mapped to IDs in the destination world
1. The thread local is unset and the allocator saved back to the world
1. Top-level entity ids are mapped using the mappings established in the allocator, and entities that are not present are spawned as new entities in the world
1. Deserialized, entity mapped components are added to the all the living entities

This approach would have some nice upsides:
* u32 entity IDs
* No need for manual implementation of `MapEntities`
* Retention of equality semantics between all saved component entity references

And some downsides I can think of:
* Complexity, though most of it is internal
* If entities are serialized without a mapping established, they must either fail to serialize or the mapping must be optional
  * If the mapping is optional, they need to have a 64-bit wide output to accommodate the fallback behavior
* If one wants to reattach scene entities to existing world entities, it will be a decently more involved process due to needing to be aware of the ID mapping that results from serialization.

**Comment by Azorlogh** [comment]
> Second, because it's true that u32 is enough to represent the space of living entities, it should be enough for the entity field on DynamicEntity

But then we still need to know which generations are valid right? (maybe I misunderstood)

I'm in favour of just serializing the full entity for now (what this PR is doing), since that already unblocks big issues currently affecting most scenes, and it seems to me that the remaining issues are mainly about philosophical separation and the footgunish nature of storing raw `Entity`s.

File: crates/bevy_scene/src/dynamic_scene.rs [hunk 12]
```diff
@@ -28,8 +28,9 @@ pub struct DynamicScene {
 
 /// A reflection-powered serializable representation of an entity and its components.
 pub struct DynamicEntity {
-    /// The transiently unique identifier of a corresponding `Entity`.
-    pub entity: u32,
+    /// The identifier of the entity, unique within a scene (and the world it may have been generated from).
+    /// Components containing entitiy references will identify their referant via this identifier.
```
Comment (MrGVSV) [inline crates/bevy_scene/src/dynamic_scene.rs:32]: > Components containing entitiy references will identify their referant via this identifier.

This is a little difficult to understand. What does it mean for a component to identify other entities identifiers using this entity identifier? I'm also not sure if you mean "referent" (the receiver of the entity) or "referrer" (the giver of the entity). I might suggest using simpler terms to describe what you mean here.

File: crates/bevy_scene/src/dynamic_scene.rs [hunk 13]
```diff
@@ -28,8 +28,9 @@ pub struct DynamicScene {
...
+    pub entity: Entity,
```
Comment (MrGVSV) [inline crates/bevy_scene/src/dynamic_scene.rs:33]: Nit: I know there's talks of "scene entity" vs "real entity". Does this entity fall into either of those? Does it not matter and/or is it not guaranteed?

If it does matter, might be worth adding a doc comment on it.

File: crates/bevy_scene/src/dynamic_scene_builder.rs [hunk 14]
```diff
@@ -31,7 +31,7 @@ use std::collections::BTreeMap;
 /// let dynamic_scene = builder.build();
 /// ```
 pub struct DynamicSceneBuilder<'w> {
-    extracted_scene: BTreeMap<u32, DynamicEntity>,
+    extracted_scene: BTreeMap<u64, DynamicEntity>,
```
Comment (MrGVSV) [inline crates/bevy_scene/src/dynamic_scene_builder.rs:34]: Is it more performant to convert the `Entity` to `u64` rather than just using `Entity` as the key?

File: crates/bevy_window/src/window.rs [hunk 15]
```diff
@@ -55,10 +55,10 @@ impl WindowRef {
 }
 
 impl MapEntities for WindowRef {
-    fn map_entities(&mut self, entity_map: &EntityMap) -> Result<(), MapEntitiesError> {
+    fn map_entities(&mut self, entity_map: &mut EntityMapper) -> Result<(), MapEntitiesError> {
```
Comment (MrGVSV) [inline crates/bevy_window/src/window.rs:58]: Nit: To match the new trait method declaration, this should be `entity_mapper`.

**Review by MrGVSV — COMMENTED** [review]
Been a little busy so I haven't gone through much of the discussion yet, so I'll just leave some code comments for now and come back later to leave any additional remarks.

Overall, it seems like a better way of handling the generations in scenes and mapping them to their destination worlds.

Most of my comments for now are related to documentation and clarity for users. Additionally, it could be nice to see other tests outside the `scene.rs` module (e.g. `entity/map_entities.rs`, `world/mod.rs`, etc.) that test specific parts of these changes. This can be especially helpful if parts are ever used in other contexts aside from Bevy scenes.

**Comment by Aceeri** [comment]
I would like to add a usecase here of where I am trying to send a DynamicScene over a network to patch existing entities/spawn new ones and in this case dangling references could more easily happen just by virtue of latency. E.g. if one entity 4 is spawned and has components on it and is sent over, then that entity is despawned on the server but a new one is created with the same index, we now have a weird situation.

Right now I'm working around this by essentially having a completely separate necessary component on all entities of `ServerEntity(u64)` and a custom write to world function for dynamic scene.

**Comment by Shatur** [comment]
> I am trying to send a DynamicScene over a network to patch existing entities/spawn 

A bit offtopic, but I would recommend you to create a new type for this. Because you will need to send deletions / insertions somehow. Just implement `MapEntities` trait (a built-in trait by Bevy) for it.

**Comment by Aceeri** [comment]
> > I am trying to send a DynamicScene over a network to patch existing entities/spawn
> 
> A bit off-topic, but I would recommend you to create a new type for this. Because you will need to send deletions / insertions somehow. Just implement `MapEntities` trait (a built-in trait by Bevy) for it.

I mean sure but I am still effectively doing the exact same thing as DynamicScene. In fact I basically have just copy pasted the write to world code. I want to consolidate my replication into just use Reflect

**Comment by Testare** [comment]
Is this PR still live?

I've put out a PR in the same space, also dealing with `MapEntities` (#7570). It basically makes sure that when a scene is loaded/reloaded, that MapEntities only gets applied to the components it loaded from the scene. It does this by adding a method to `ReflectMapEntities` to only apply to certain entities, not all values in the EntityMap, since ReflectMapEntities is already a per-component struct. This is currently a problem with the fact that `Parent` components are added to scene objects without a parent to point at the DynamicScene entity, and those parent components are being hit by the MapEntity behavior when a scene is reloaded.

But I'm wondering if you're doing things so that world entities generated from scenes are dependably unique, this might not be necessary?

File: crates/bevy_ecs/src/reflect.rs [hunk 16]
```diff
@@ -406,26 +406,27 @@ impl_from_reflect_value!(Entity);
...
     fn from_type() -> Self {
         ReflectMapEntities {
-            map_entities: |world, entity_map| {
-                for entity in entity_map.values() {
+            map_entities: |world, entity_mapper| {
+                let entities = entity_mapper.get_map().values().collect::<Vec<Entity>>();
+                for entity in entities.iter().cloned() {
                     if let Some(mut component) = world.get_mut::<C>(entity) {
-                        component.map_entities(entity_map)?;
+                        component.map_entities(entity_mapper)?;
```
[the remark this answers is not in the document]
Comment (Illiux) [reply crates/bevy_ecs/src/reflect.rs:432]: If I understand you right, what you're really trying to get at is if the closure should be specialized to return a result so that the rest of `with_mapper` can react to it. I think no, in that saving the mapper should really always happen even if there was an error somewhere in mapping. Saving the mapper just actually allocates in the world the ids that it handed out in mapping, and this should always happen.

When mapping fails for whatever reason we're left in a bad state, with things only partially mapped and possibly pointing at entities that already exist in the destination world. What we might consider doing, though, is just making it so that mapping isn't allowed to fail. With `get_or_alloc` now existing I can't think of a good reason to ever call `get` or ever to return an error from a `MapEntities` implementation, but I wasn't sure if there was some weird use case I was missing and didn't want to unnecessarily expand the blast radius. That would be reasonable to just go ahead and do though.

File: crates/bevy_ecs/src/world/mod.rs [hunk 17]
```diff
@@ -608,6 +608,22 @@ impl World {
         }
     }
 
+    /// Despawns the given `entity`, if it exists, and reserves a number of subsequent generations.
+    ///
+    /// This function serves an extremely narrow use case of allocating a series of entity IDs that are
+    /// guaranteed to never refer to a live entity. This functionality is useful primarily for mapping references
+    /// to dead entities into a new world alongside a [`crate::entity::MapEntities`] implementation.
+    ///
+    /// See [`Self::despawn()`] for usage.
```
[the remark this answers is not in the document]
Comment (Illiux) [reply crates/bevy_ecs/src/world/mod.rs:642]: Ended up just copying down the relevant bits from `despawn`s doc

File: crates/bevy_scene/src/dynamic_scene.rs (hunk 13 above)
Comment (Illiux) [reply crates/bevy_scene/src/dynamic_scene.rs:33]: `Entity` is just an identifier, and the only constraint here is that it must be consistent with the references that exist within components in the scene. I guess that makes it a "scene entity" though scenes themselves are sort of like worlds that organize their entity data differently than a `World`. That constraint is what I was trying to indicate with the sentence you commented on above.

File: crates/bevy_scene/src/dynamic_scene_builder.rs (hunk 14 above)
Comment (Illiux) [reply crates/bevy_scene/src/dynamic_scene_builder.rs:34]: Nope, this was just missed when shuffling between `Entity` and `u64` across different PR revisions.

**Comment by Illiux** [comment]
> Is this PR still live?

Yes, it just took me a bit to get back to it.

> I've put out a PR in the same space, also dealing with `MapEntities` (#7570). It basically makes sure that when a scene is loaded/reloaded, that MapEntities only gets applied to the components it loaded from the scene. It does this by adding a method to `ReflectMapEntities` to only apply to certain entities, not all values in the EntityMap, since ReflectMapEntities is already a per-component struct. This is currently a problem with the fact that `Parent` components are added to scene objects without a parent to point at the DynamicScene entity, and those parent components are being hit by the MapEntity behavior when a scene is reloaded.
> 
> But I'm wondering if you're doing things so that world entities generated from scenes are dependably unique, this might not be necessary?

What this PR will do is make it so that, so long as something implements `MapEntities`, all of its `Entity` identifiers will reliably point to unique entities in the destination world, whether they point to dead or living entities. So, I think it addresses a different problem then your PR, as your PR has to do with applying over existing entities in the scene and this one addresses dealing with entity references inside scene components that point outside the scene.

File: crates/bevy_ecs/src/entity/map_entities.rs [hunk 18]
```diff
@@ -122,4 +171,73 @@ impl EntityMap {
...
+        let mut map = EntityMap::default();
+        let mut world = World::new();
+        let mut mapper = EntityMapper::new(&mut map, &mut world);
+
+        let mapped_ent = Entity::new(FIRST_IDX, 0);
+        let dead_ref = mapper.get_or_alloc(mapped_ent);
+
+        // Should persist the allocated mapping from the previous line
+        assert_eq!(dead_ref, mapper.get_or_alloc(mapped_ent));
+        // Should re-use the same index for further dead refs
```
Comment (Shatur) [inline crates/bevy_ecs/src/entity/map_entities.rs:216]: I would move these explanations into `assert_eq` for a nice error message.

File: crates/bevy_ecs/src/entity/mod.rs [hunk 19]
```diff
@@ -590,6 +609,22 @@ impl Entities {
         self.meta.get_unchecked_mut(index as usize).location = location;
     }
 
+    /// Increments the generation of a despawned [`Entity`]. This may only be called on an entity
+    /// index corresponding to an entity that once existed and has since been freed.
```
Comment (Shatur) [inline crates/bevy_ecs/src/entity/mod.rs:613]: How about something like this?
```suggestion
    /// Increments the `generation` of a despawned `index`. Next spawned entities with this `index` will count `generation` starting from the specified value + 1.
    ///
    /// Does nothing if such an entity with this `index` has not yet been despawned yet.
```

File: crates/bevy_ecs/src/entity/map_entities.rs [hunk 20]
```diff
@@ -56,20 +36,92 @@ pub trait MapEntities {
...
+    map: &'m mut EntityMap,
+    /// A base [`Entity`] used to allocate new references.
+    dead_start: Entity,
+    /// The number of generations this mapper has allocated thus far.
+    generations: u32,
+}
+
+impl<'m> EntityMapper<'m> {
+    /// Returns the corresponding mapped entity or allocates a new dead entity if it is absent.
+    pub fn get_or_alloc(&mut self, entity: Entity) -> Entity {
```
Comment (Shatur) [inline crates/bevy_ecs/src/entity/map_entities.rs:76]: I'm not sure if I like `allocate` word here. I would use something like `reserve` as in `Commands`.

File: crates/bevy_ecs/src/entity/map_entities.rs [hunk 21]
```diff
@@ -56,20 +36,92 @@ pub trait MapEntities {
...
+    /// Gets a mutable reference to the underlying [`EntityMap`]
+    pub fn get_map_mut(&'m mut self) -> &'m mut EntityMap {
+        self.map
+    }
+
+    /// Creates a new [`EntityMapper`], spawning a temporary base [`Entity`] in the provided [`World`]
+    fn new(map: &'m mut EntityMap, world: &mut World) -> Self {
+        Self {
+            map,
+            dead_start: world.spawn_empty().id(),
```
Comment (Shatur) [inline crates/bevy_ecs/src/entity/map_entities.rs:106]: Spawning a new entity here is a little hacky. Can we get a new index from `Commands`?

File: crates/bevy_ecs/src/entity/map_entities.rs [hunk 22]
```diff
@@ -122,4 +171,73 @@ impl EntityMap {
...
+    /// Creates an [`EntityMapper`] from this [`EntityMap`] and scoped to the provided [`World`], then calls the
+    /// provided function with it. This allows one to allocate new entity references in the provided `World` that are
+    /// guaranteed to never point at a living entity now or in the future. This functionality is useful for safely
+    /// mapping entity identifiers that point at entities outside the source world.
+    ///
+    /// # Arguments
+    ///
+    /// * `world` - The world the entities are being mapped into.
+    /// * `f` - A function to call within the scope of the passed world. Its return value is then returned from
+    ///         `world_scope` as the generic type parameter `R`.
```
Comment (Shatur) [inline crates/bevy_ecs/src/entity/map_entities.rs:184]: I would add this description to the text above and remove the whole `Arguments` section.

File: crates/bevy_ecs/src/world/mod.rs [hunk 23]
```diff
@@ -633,6 +633,22 @@ impl World {
...
     }
 
+    /// Despawns the given `entity`, if it exists, and reserves a number of subsequent generations. This will also
+    /// remove all of the entity's [Component]s. Returns `true` if the `entity` is successfully despawned and the
+    /// generations successfully reserved, and `false` if the `entity` does not exist or reservation failed.
+    ///
+    /// This function serves an extremely narrow use case of allocating a series of entity IDs that are
+    /// guaranteed to never refer to a live entity. This functionality is useful primarily for mapping references
+    /// to dead entities into a new world alongside a [`crate::entity::MapEntities`] implementation.
+    pub(crate) fn try_reserve_generations(&mut self, entity: Entity, generations: u32) -> bool {
```
Comment (Shatur) [inline crates/bevy_ecs/src/world/mod.rs:643]: I would put this inside `finish`. Doesn't make much sense as a standalone function.

**Review by Shatur — CHANGES_REQUESTED** [review]
I like this change. The PR fixes an important bug. But I have some suggestions.

File: crates/bevy_ecs/src/entity/map_entities.rs [hunk 24]
```diff
@@ -56,20 +36,92 @@ pub trait MapEntities {
...
     map: HashMap<Entity, Entity>,
 }
 
+/// A wrapper for [`EntityMap`], augmenting it with the ability to allocate new [`Entity`] references in a destination
+/// world. These newly allocated references are guaranteed to never point to any living entity in that world.
+///
+/// References are allocated by returning increasing generations starting from an internally initialized base
+/// [`Entity`]. After it is finished being used by [`MapEntities`] implementations, this entity is despawned and the
+/// requisite number of generations reserved.
+pub struct EntityMapper<'m> {
```
Comment (nicopap) [inline crates/bevy_ecs/src/entity/map_entities.rs:65]: Nit, format: This `struct` block was inserted between the declaration of `struct EntityMap` and its following `impl` block, could you move back the `impl EntityMap` block right after the `struct EntityMap`?

File: crates/bevy_ecs/src/entity/map_entities.rs [hunk 25]
```diff
@@ -91,11 +143,8 @@ impl EntityMap {
     }
 
     /// Returns the corresponding mapped entity.
-    pub fn get(&self, entity: Entity) -> Result<Entity, MapEntitiesError> {
-        self.map
-            .get(&entity)
-            .cloned()
-            .ok_or(MapEntitiesError::EntityNotFound(entity))
+    pub fn get(&self, entity: Entity) -> Option<Entity> {
+        self.map.get(&entity).cloned()
```
Comment (nicopap) [inline crates/bevy_ecs/src/entity/map_entities.rs:147]: Nit:
```suggestion
        self.map.get(&entity).copied()
```

File: crates/bevy_ecs/src/reflect.rs [hunk 26]
```diff
@@ -408,29 +408,25 @@ impl_from_reflect_value!(Entity);
...
 
 impl<C: Component + MapEntities> FromType<C> for ReflectMapEntities {
     fn from_type() -> Self {
         ReflectMapEntities {
-            map_entities: |world, entity_map| {
-                for entity in entity_map.values() {
+            map_entities: |world, entity_mapper| {
+                let entities = entity_mapper.get_map().values().collect::<Vec<Entity>>();
+                for entity in entities.iter().cloned() {
                     if let Some(mut component) = world.get_mut::<C>(entity) {
```
Comment (nicopap) [inline crates/bevy_ecs/src/reflect.rs:426]: Nit:
```suggestion
                for entity in &entities {
                    if let Some(mut component) = world.get_mut::<C>(*entity) {
```

File: crates/bevy_scene/src/serde.rs [hunk 27]
```diff
@@ -535,6 +557,57 @@ mod tests {
...
+            .query_filtered::<&MyEntityRef, Without<Foo>>()
+            .get_single(&dst_world)
+            .unwrap()
+            .0;
+        let foo = dst_world
+            .query_filtered::<Entity, With<Foo>>()
+            .get_single(&dst_world)
+            .unwrap();
+
+        assert_eq!(foo, bar_to_foo);
```
Comment (nicopap) [inline crates/bevy_scene/src/serde.rs:604]: Could you do the `bar_to_foo.0` in the `assert_eq!` rather than when assigning to `bar_to_foo`? I think it makes the test a bit easier to understand, as the type structure is easier to parse at a glance.

File: crates/bevy_ecs/src/entity/map_entities.rs [hunk 28]
```diff
@@ -56,20 +36,92 @@ pub trait MapEntities {
...
+    /// Returns the corresponding mapped entity or allocates a new dead entity if it is absent.
+    pub fn get_or_alloc(&mut self, entity: Entity) -> Entity {
+        if let Some(mapped) = self.map.get(entity) {
+            return mapped;
+        }
+
+        let new = Entity {
+            generation: self.dead_start.generation + self.generations,
+            index: self.dead_start.index,
+        };
```
Comment (nicopap) [inline crates/bevy_ecs/src/entity/map_entities.rs:84]: Clarity: Could you write a short comment reminding people that those entities are _specifically made to not represent any valid entity_?

File: crates/bevy_window/src/window.rs [hunk 29]
```diff
@@ -55,14 +55,13 @@ impl WindowRef {
...
+    fn map_entities(&mut self, entity_mapper: &mut EntityMapper) {
         match self {
             Self::Entity(entity) => {
-                *entity = entity_map.get(*entity)?;
-                Ok(())
+                *entity = entity_mapper.get_or_alloc(*entity);
             }
-            Self::Primary => Ok(()),
-        }
+            Self::Primary => (),
```
Comment (nicopap) [inline crates/bevy_window/src/window.rs:63]: Nit:
```suggestion
            Self::Primary => {},
```

**Review by nicopap — CHANGES_REQUESTED** [review]
Yeah, need to address @Shatur 's comments and I think this can be merged. As noted earlier in the discussion, this stems mostly from serialization of entities being entirely stateless, so it's impossible to translate an `Entity` from the `World` into something more meaningful in the scene. I think this should be adopted until we get around to implement a, possibly more complex, but more distinct id type for entities in scene.

File: crates/bevy_ecs/src/entity/map_entities.rs (hunk 21 above)
Comment (Illiux) [reply crates/bevy_ecs/src/entity/map_entities.rs:106]: Since getting rid of `try_reserve_generations` meant coupling this directly with `Entities` anyway, I went with getting a new index via `Entities::alloc()`.

File: crates/bevy_ecs/src/entity/mod.rs (hunk 19 above)
Comment (Illiux) [reply crates/bevy_ecs/src/entity/mod.rs:619]: Especially given the changes I've just made to `EntityMapper` I don't know if I want to use spawn/despawn language in here. That seems to imply a bit more work happening than what actually happens now. I'll use alloc/free to match the other methods in `Entities`

Comment (Illiux) [reply crates/bevy_ecs/src/entity/mod.rs:619]: Also, `starting from the specified value + 1` isn't technically true because the generation may have already been nonzero when this method was called. I'll clarify that

**Review by Shatur — APPROVED** [review]

File: crates/bevy_scene/src/dynamic_scene_builder.rs [hunk 30]
```diff
@@ -113,14 +113,14 @@ impl<'w> DynamicSceneBuilder<'w> {
         let type_registry = self.type_registry.read();
 
         for entity in entities {
-            let index = entity.index();
+            let index = entity;
```
Comment (MrGVSV) [inline crates/bevy_scene/src/dynamic_scene_builder.rs:116]: Nit: We can probably just get rid of this `index` variable entirely.

File: crates/bevy_scene/src/dynamic_scene.rs [hunk 31]
```diff
@@ -28,8 +28,11 @@ pub struct DynamicScene {
 
 /// A reflection-powered serializable representation of an entity and its components.
 pub struct DynamicEntity {
-    /// The transiently unique identifier of a corresponding `Entity`.
-    pub entity: u32,
+    /// The identifier of the entity, unique within a scene (and the world it may have been generated from).
+    ///
+    /// Components in the scene that reference other entities reference them through this identifier, and so this
+    /// identifier must be consistent with the references contained within components.
```
Comment (MrGVSV) [inline crates/bevy_scene/src/dynamic_scene.rs:34]: Nit: This is still a bit confusing to me. Could it be simpler to state something like:
```suggestion
    /// Components that reference this entity must consistently use this identifier.
```

Or maybe I'm missing something?

**Review by MrGVSV — APPROVED** [review]
The reflection-related changes look good and the PR overall seems to provide a much nicer way of dealing with this issue. I'll approve based on that, but my knowledge of ECS is limited and I'm unsure of the consequences/implications of this approach (if any), so please take with a grain of salt!

**Review by nicopap — APPROVED** [review]

**Comment by cart** [comment]
(moved back to the 0.10 milestone, but it might be too late at this point so no promises!)

**Comment by james7132** [comment]
Moving this to 0.11 as it seems like we're going to be shipping 0.10 early today, and this isn't ready yet for a merge.

**Comment by Shatur** [comment]
> and this isn't ready yet for a merge.

But looks like comments were addressed. Or you mean that the approach is controversial?
I just think scene loading can't be broken more. This PR fixes a pretty serious bug with scene loading.

**Comment by nicopap** [comment]
Need to resolve conflicts and this seems ready for a final review/merge, right?

**Review by alice-i-cecile — APPROVED** [review]
@Illiux once this is rebased I think we can merge this ASAP

File: crates/bevy_scene/src/dynamic_scene_builder.rs [hunk 32]
```diff
@@ -122,9 +122,7 @@ impl<'w> DynamicSceneBuilder<'w> {
     pub fn extract_entities(&mut self, entities: impl Iterator<Item = Entity>) -> &mut Self {
         let type_registry = self.type_registry.read();
 
-        for entity in entities {
-            let index = entity.index();
-
+        for index in entities {
```
Comment (Shatur) [inline crates/bevy_scene/src/dynamic_scene_builder.rs:125]:
```suggestion
        for entity in entities {
```

File: crates/bevy_scene/src/dynamic_scene_builder.rs [hunk 33]
```diff
@@ -134,7 +132,7 @@ impl<'w> DynamicSceneBuilder<'w> {
                 components: Vec::new(),
             };
 
-            let entity = self.original_world.entity(entity);
+            let entity = self.original_world.entity(index);
```
Comment (Shatur) [inline crates/bevy_scene/src/dynamic_scene_builder.rs:135]:
```suggestion
            let original_entity = self.original_world.entity(entity);
```

File: crates/bevy_scene/src/serde.rs [hunk 34]
```diff
@@ -273,7 +274,7 @@ impl<'a, 'de> Visitor<'de> for SceneEntitiesVisitor<'a> {
 }
 
 pub struct SceneEntityDeserializer<'a> {
-    pub id: u32,
+    pub id: Entity,
```
Comment (Shatur) [inline crates/bevy_scene/src/serde.rs:277]:
```suggestion
    pub entity: Entity,
```

File: crates/bevy_scene/src/serde.rs [hunk 35]
```diff
@@ -296,7 +297,7 @@ impl<'a, 'de> DeserializeSeed<'de> for SceneEntityDeserializer<'a> {
 }
 
 struct SceneEntityVisitor<'a> {
-    pub id: u32,
+    pub id: Entity,
```
Comment (Shatur) [inline crates/bevy_scene/src/serde.rs:300]:
```suggestion
    pub entity: Entity,
```

File: crates/bevy_ecs/src/world/mod.rs [hunk 36]
```diff
@@ -996,8 +996,8 @@ impl World {
         match self.get_resource_mut() {
             Some(x) => x,
             None => panic!(
-                "Requested resource {} does not exist in the `World`.
```
Comment (Shatur) [inline crates/bevy_ecs/src/world/mod.rs:999]: Looks like you forgot to remove changes in this file.

**Review by Shatur — CHANGES_REQUESTED** [review]
Added a few very minor suggestions.

**Review by Shatur — APPROVED** [review]
