### PR TITLE
Fix num_cascades in split_screen exmample for WebGL

### LINKED ISSUE #14595: Shadow clipped/not shown for split_screen example on WebGL
## Bevy version

Bevy 0.14

## Relevant system information

Confirmed on Firefox and Edge at least. Does not happen on WebGPU or native Windows.

image

```ignore
`AdapterInfo { name: "ANGLE (NVIDIA, NVIDIA GeForce GTX 980 Direct3D11 vs_5_0 ps_5_0), or similar", vendor: 4318, device: 0, device_type: Other, driver: "WebGL", driver_info: "2.0", backend: Gl }`
```

## What you did

Run https://bevyengine.org/examples/3d-rendering/split-screen/
(also I rotated foxes to show clipping effect)

## Additional information

This warning was logged:
> crates/bevy_pbr/src/render/light.rs:593 The number of cascades configured for a directional light exceeds the supported limit of 1.

I tried running the example with `num_cascades` changed to 1, and the shadow indeed seems to be fixed.

### PR DESCRIPTION
**Pull request by akimakinai**
# Objective

- Fixes #14595

## Solution

- Use `num_cascades: 1` in WebGL build. `CascadeShadowConfigBuilder::default()` gives this number in WebGL: https://github.com/bevyengine/bevy/blob/8235daaea0e3aa930e34c57887e1ffea08a8150a/crates/bevy_pbr/src/light/mod.rs#L241-L248

## Testing

- Tested the modified example in WebGL with Firefox/Chrome

### CODE REVIEW

**Review by Olle-Lukowski — APPROVED** [review]

File: examples/3d/split_screen.rs [hunk 1]
```diff
@@ -41,7 +41,16 @@ fn setup(
             ..default()
         },
         cascade_shadow_config: CascadeShadowConfigBuilder {
-            num_cascades: 2,
+            num_cascades: if cfg!(all(
+                feature = "webgl2",
+                target_arch = "wasm32",
+                not(feature = "webgpu")
+            )) {
+                // Currently limited to 1 cascade in WebGL
```
Comment (JMS55) [inline examples/3d/split_screen.rs:49]:
```suggestion
                // Limited to 1 cascade in WebGL
```

Small nit, but this is very unlikely to ever change.

**Review by JMS55 — APPROVED** [review]

**Review by Olle-Lukowski — APPROVED** [review]

**Review by mockersf — APPROVED** [review]
