### PR TITLE
disable gpu preprocessing on android with Adreno 730 GPU and earilier

### LINKED ISSUE #14146: Crash on Android on 0.14
## Bevy version

0.14

## What you did

I updated bevy version to 0.14

## What went wrong
Android game will crash, which didn't on 0.13

## Additional information
Here is the crash dump
[org.bevyengine.roundyproduction_2024-07-05T13_59_.log](https://github.com/user-attachments/files/16105479/org.bevyengine.roundyproduction_2024-07-05T13_59_.log)

### PR DESCRIPTION
**Pull request by Litttlefish**
# Objective

Fix #14146 

## Solution

Expansion of #13323 , excluded Adreno 730 and earlier.

## Testing

Tested on android device(Adreno 730) that used to crash

### CODE REVIEW

**Comment by eero-lehtinen** [comment]
This limits too much because 740 is proven to work https://github.com/bevyengine/bevy/pull/13323#issuecomment-2105665001, and 750 works for me.

**Comment by Litttlefish** [comment]
> This limits too much because 740 is proven to work [#13323 (comment)](https://github.com/bevyengine/bevy/pull/13323#issuecomment-2105665001), and 750 works for me.

I've changed it to only disble on 6xx and 730 now

**Comment by eero-lehtinen** [comment]
There are also 702, 710, 720, 725 that I think are safe to assume don't work either because they are older. https://en.wikipedia.org/wiki/Adreno#Adreno_700_series

**Comment by eero-lehtinen** [comment]
So I would check that the second number is 3 or less.

**Comment by Litttlefish** [comment]
> So I would check that the second number is 3 or less.

My assumption is GPU earlier than 730(probably, since there Adreno 740 is used for 8Gen2 series) doesn't support it, so I used this

But Adreno 720 is used in 7Gen3, which probably should support it🤔needs more testing to confirm

**Comment by eero-lehtinen** [comment]
Yeah looks like 732 and 735 are very new as well

**Review by eero-lehtinen — APPROVED** [review]

**Comment by Litttlefish** [comment]
> Yeah looks like 732 and 735 are very new as well

Anyways I excluded 720, since it probably supports gpu preprocessing, I'll let it for others to test

**Comment by eero-lehtinen** [comment]
Also I'm pretty sure 740 doesn't support gpu processing, it just reports it correctly.

File: crates/bevy_render/src/batching/gpu_preprocessing.rs [hunk 1]
```diff
@@ -226,8 +226,13 @@ impl FromWorld for GpuPreprocessingSupport {
         let device = world.resource::<RenderDevice>();
 
         if device.limits().max_compute_workgroup_size_x == 0 ||
-            // filter lower end / older devices on Android as they crash when using GPU preprocessing
-            (cfg!(target_os = "android") && adapter.get_info().name.starts_with("Adreno (TM) 6"))
+            // filter some Qualcomm devices on Android as they crash when using GPU preprocessing
+            (cfg!(target_os = "android") && {
+                let name = adapter.get_info().name;
+                name.strip_prefix("Adreno (TM) ").is_some_and(|version|
+                    version != "720" && version.parse::<u16>().unwrap() <= 730
```
Comment (mockersf) [inline crates/bevy_render/src/batching/gpu_preprocessing.rs:233]: this would greatly benefit from a comment explaining why it's done this way

**Review by mockersf — APPROVED** [review]

File: crates/bevy_render/src/batching/gpu_preprocessing.rs [hunk 2]
```diff
@@ -226,8 +226,14 @@ impl FromWorld for GpuPreprocessingSupport {
...
 
         if device.limits().max_compute_workgroup_size_x == 0 ||
-            // filter lower end / older devices on Android as they crash when using GPU preprocessing
-            (cfg!(target_os = "android") && adapter.get_info().name.starts_with("Adreno (TM) 6"))
+            // filter some Qualcomm devices on Android as they crash when using GPU preprocessing
+            (cfg!(target_os = "android") && {
+                let name = adapter.get_info().name;
+                // filter out Adreno 730 and earlier GPUs (except 720, it's newer than 730)
+                name.strip_prefix("Adreno (TM) ").is_some_and(|version|
+                    version != "720" && version.parse::<u16>().unwrap() <= 730
```
Comment (eero-lehtinen) [inline crates/bevy_render/src/batching/gpu_preprocessing.rs:234]: Unwrap here is bad if adreno includes letters in the version number later or something. `unwrap_or` or another `is_some_and` would be better.

Comment (Litttlefish) [reply crates/bevy_render/src/batching/gpu_preprocessing.rs]: I think we can discard those non-numeric result anyways, since it will always newer than 730, so I changed unwrap to is_ok_and
