### PR TITLE
Fix default UI node size

### LINKED ISSUE #291: Node size computed incorrectly(?) on cross axis for AlignItems::Stretch
Here is a CodeSandbox showing how `flex-basis` and `align-items: stretch` works: https://codesandbox.io/s/stoic-turing-tdyz7?file=/index.html

Note that by default `align-items` is `stretch` in browsers and also in the [Stretch](https://vislyhq.github.io/stretch/docs/rust/) library which Bevy UI is based on.

I am trying to reproduce the above CodeSandbox using Bevy UI: https://github.com/stefee/bevy/commit/33bdca418f1944ed05daf9e8c1e96217106e32ff

```rust
use bevy::prelude::*;

fn main() {
    env_logger::init();

    App::build()
        .add_resource(bevy::window::WindowDescriptor {
            width: 1920,
            height: 1080,
            title: "Bevy UI Storybook Prototype".to_string(),
            ..Default::default()
        })
        .add_resource(bevy::render::pass::ClearColor(Color::rgb(1.0, 1.0, 1.0)))
        .add_default_plugins()
        .add_startup_system(setup.system())
        .run();
}

fn setup(
    mut commands: Commands,
    _asset_server: Res<AssetServer>,
    mut materials: ResMut<Assets<ColorMaterial>>,
) {
    commands
        // ui camera
        .spawn(UiCameraComponents::default())
        .spawn(NodeComponents {
            style: Style {
                size: Size::new(Val::Px(200.0), Val::Px(200.0)),
                align_items: AlignItems::Stretch,
                ..Default::default()
            },
            material: materials.add(Color::rgb(1.0, 0.0, 1.0).into()),
            ..Default::default()
        })
        .with_children(|parent| {
            parent
                .spawn(NodeComponents {
                    style: Style {
                        flex_basis: Val::Percent(50.0),
                        ..Default::default()
                    },
                    material: materials.add(Color::rgb(1.0, 0.0, 0.0).into()),
                    ..Default::default()
                })
                .spawn(NodeComponents {
                    style: Style {
                        flex_basis: Val::Percent(50.0),
                        ..Default::default()
                    },
                    material: materials.add(Color::rgb(0.0, 1.0, 0.0).into()),
                    ..Default::default()
                });
        });
}
```

The above code results in a purple square – the parent node is visible but not the child nodes, because the child nodes have a height of 0.

Height in this case corresponds to the "cross axis" in the flex model, and the child node should have cross axis size of 100% when `AlignItems::Stretch` is used. (See [Guide to Flexbox](https://css-tricks.com/snippets/css/a-guide-to-flexbox/)).

### Workaround

The current workaround is to specify a `size` as well as (or instead of) `flex_basis`.

```rust
                .spawn(NodeComponents {
                    style: Style {
                        size: Size::new(Val::Percent(100.0), Val::Percent(100.0)),
                        flex_basis: Val::Percent(50.0),
                        ..Default::default()
                    },
                    material: materials.add(Color::rgb(1.0, 0.0, 0.0).into()),
                    ..Default::default()
                })
```

The problem with this is that width and height do not respect flex direction, so if you were to change flex direction (e.g. from row to column) you would need to also swap the width and height properties.

Also, if you were to change the parent to use something other than `AlignItems::Stretch` you would then need to update the child sizes as well to get the desired effect.

### Update 24/08/18

@harrywincup found a better workaround of using `Val::Auto` for the child node size.

```rust
                .spawn(NodeComponents {
                    style: Style {
                        size: Size::new(Val::Auto, Val::Auto),
                        flex_basis: Val::Percent(50.0),
                        ..Default::default()
                    },
                    material: materials.add(Color::rgb(1.0, 0.0, 0.0).into()),
                    ..Default::default()
                })
```

This has the same result as the above workaround, but with the advantage that flex direction is respected and `AlignItems` behaviour works as expected.

I've opened a PR to make `Val::Auto` the default value for `style.size`. 👉  #304

### PR DESCRIPTION
**Pull request by stefee**
Fixes #291

This changes the default node size (width and height) to `Auto` instead of `Undefined` to match [the Stretch implementation](https://github.com/vislyhq/stretch/blob/6879b9a1cf3c244430bbf8b88bf205c614d72562/src/style.rs#L247).

See comment https://github.com/bevyengine/bevy/issues/291#issuecomment-678807641, I think the solution in this comment would be better, but currently doesn't work with how the crates are structured.

### CODE REVIEW

File: crates/bevy_ui/src/flex/convert.rs [hunk 1]
```diff
@@ -17,13 +17,25 @@ where
     }
 }
 
-fn from_size<T, U>(size: Size<U>) -> stretch::geometry::Size<T>
+fn from_size<T>(size: Size<Val>) -> stretch::geometry::Size<T>
 where
-    T: From<U>,
+    T: From<Val>,
 {
+    let width = if let Val::Undefined = size.width {
```
Comment (stefee) [inline crates/bevy_ui/src/flex/convert.rs:24]: This will prevent users from overriding size to `Undefined` as well as changing the default behaviour. Perhaps this is not desirable?

Comment (stefee) [reply crates/bevy_ui/src/flex/convert.rs:24]: I actually think we need to keep `Undefined` as an option, so we need should try to find a way to write `impl Default for Size<Val>`. @cart do you have any ideas for how to do this without conflicting with `impl<T> std::default::Default for bevy_math::Size<T>` and also to avoid the `only traits defined in the current crate can be implemented for arbitrary types` error?

Comment (cart) [reply crates/bevy_ui/src/flex/convert.rs:24]: Yeah this is a little tough. If we could use the nightly "specialization" rust features, we would be able to override the default for this specific generic type. Sadly we can't do that so we'll need to get creative. The current approach seems a little bit hack-ey, but off the top of my head I don't have a nice solution. I suppose we could remove the "default" Size<T> impl and then explicitly implement defaults per-type (ex: Size<Val> , Size<f32>, etc). I'm not a huge fan, but I think I prefer it to the current approach. I guess lets do that for now and we can revisit this later if it comes up.

Comment (stefee) [reply crates/bevy_ui/src/flex/convert.rs:24]: Yes, I think that is probably the best way to solve this.

This fixes the conflict issue, but it doesn't fix the `only traits defined in the current crate can be implemented for arbitrary types` problem. (I think this is a case of the "orphan rule"?)

I am actually surprised that this is an issue, I thought this would have been covered by [the relaxed restrictions on implementing traits in Rust 1.41.0](https://blog.rust-lang.org/2020/01/30/Rust-1.41.0.html#relaxed-restrictions-when-implementing-traits) but I guess not. 😕 ❓

Comment (stefee) [reply crates/bevy_ui/src/flex/convert.rs:24]: We might need to re-define the `Size` struct type locally rather than importing it from `bevy_math`.

Comment (stefee) [reply crates/bevy_ui/src/flex/convert.rs:24]: By the way, I think this bug and the compile errors are both potentially signs of this being implemented in an overly generic way. So I don't mind the idea of explicitly setting all the default values per-type. I think that approach is possibly less error-prone.

Comment (cart) [reply crates/bevy_ui/src/flex/convert.rs:24]: weird. I was certain that pattern was supported. 

I think the fix here might be to just change the default values for Style.size:

```rust

impl Default for Style {
    fn default() -> Self {
        Self {
            display: Default::default(),
            position_type: Default::default(),
            direction: Default::default(),
            flex_direction: Default::default(),
            flex_wrap: Default::default(),
            align_items: Default::default(),
            align_self: Default::default(),
            align_content: Default::default(),
            justify_content: Default::default(),
            position: Default::default(),
            margin: Default::default(),
            padding: Default::default(),
            border: Default::default(),
            flex_grow: 0.0,
            flex_shrink: 1.0,
            flex_basis: Val::Auto,
            // change to these
            size: Size::new(Val::Auto, Val::Auto),
            min_size: Size::new(Val::Auto, Val::Auto),
            max_size: Size::new(Val::Auto, Val::Auto),
            aspect_ratio: Default::default(),
        }
    }
}

```

Then we can still use the generic type "everywhere". We

Comment (stefee) [reply crates/bevy_ui/src/flex/convert.rs:24]: Ohh of course. That makes sense. Thanks for your help, I’ll update my PR later today.

**Comment by cart** [comment]
Thanks! This looks good to go!
