### PR TITLE
BRP allow spawning/inserting Components with only `Reflect`

### LINKED ISSUE #20952: BRP Issue: Components with only `Reflect` cannot be spawned/inserted
## Bevy version and features

- version: 0.16.1 but i believe the issue still persists
- no features

## What you did

using the bevy remote protocol, if i try to `bevy/spawn` or `bevy/insert` on a Component and do not derive `Deserialize` and reflect `Deserialize` it gets an error

here's the report i came up with

### The Problem
In Bevy 0.16.1, components that only derive `Reflect` (without `Serialize`/`Deserialize`) fail to spawn via BRP with the error:
```
Unknown component type: `bevy_reflect::DynamicStruct`
```

### Root Cause Analysis

When `process_remote_spawn_request` receives a spawn request:

1. **`deserialize_components`** creates a `TypedReflectDeserializer` and calls `deserialize()`

2. The deserializer checks for:
   - `ReflectDeserialize` (requires `#[derive(Deserialize)]` + `#[reflect(Deserialize)]`)
   - `ReflectDeserializeWithRegistry` (requires manual registration)
   
3. **Without these traits**, it falls back to `deserialize_struct()` which creates a `DynamicStruct` - a generic container that *knows* it represents the actual type via `set_represented_type()`

4. This `DynamicStruct` is passed to **`insert_reflected_components`** which calls:
   ```rust
   get_reflect_component(type_registry, reflected.reflect_type_path())
   ```

5. **The bug**: `reflect_type_path()` on `DynamicStruct` returns `"bevy_reflect::DynamicStruct"` (from `impl_type_path!` macro) instead of the represented type's path

6. `get_reflect_component` fails because `"bevy_reflect::DynamicStruct"` isn't registered as a component

### The Fix

In `insert_reflected_components`, check for a represented type first:

```rust
fn insert_reflected_components(
    type_registry: &TypeRegistry,
    mut entity_world_mut: EntityWorldMut,
    reflect_components: Vec<Box<dyn PartialReflect>>,
) -> AnyhowResult<()> {
    for reflected in reflect_components {
        let type_path = if let Some(represented_type_info) = reflected.get_represented_type_info() {
            represented_type_info.type_path()  // Use the actual component type
        } else {
            reflected.reflect_type_path()      // Fallback for non-dynamic types
        };
        
        let reflect_component = get_reflect_component(type_registry, type_path)?;
        reflect_component.insert(&mut entity_world_mut, &*reflected, type_registry);
    }

    Ok(())
}
```

### Verification

I've tested this fix on Bevy 0.16.1 and confirmed it works - components with only `Reflect` can now be successfully spawned and inserted via BRP.

### Help requested
I'm not a bevy contributor and i don't know the rules - mostly i'm concerned while that this is just a few lines of code to fix in an existing function i want to make sure that it's the right few lines of code. Not being a bevy_remote or bevy_reflect developer I would love it if someone who was could look at this issue and fix it correctly.

It's a big issue for me and I would love it if it this could make it into 17 as a bug fix.

### PR DESCRIPTION
**Pull request by Leinnan**
# Objective

Fixes #20952

## Solution

Improve flow for getting type path. Add new test to make sure it will work later on. 

## Testing

New test is added to confirm that the solution works, I wrote the test first to check if I have the same issue as described in report. It was that and the fix was provided by @natepiano so my work here is mostly test.

### CODE REVIEW

**Comment by SkiFire13** [comment]
Can we also update `TypedReflectDeserializer` to use `ReflectFromReflect` if present, so that we improve the UX for all users of `TypedReflectDeserializer` and not just BRP?

File: crates/bevy_remote/src/builtin_methods.rs [hunk 1]
```diff
@@ -1557,8 +1557,12 @@ fn insert_reflected_components(
...
     for reflected in reflect_components {
-        let reflect_component =
-            get_reflect_component(type_registry, reflected.reflect_type_path())?;
+        let type_path = if let Some(represented_type_info) = reflected.get_represented_type_info() {
+            represented_type_info.type_path() // Use the actual component type
+        } else {
+            reflected.reflect_type_path() // Fallback for non-dynamic types
+        };
+        let reflect_component = get_reflect_component(type_registry, type_path)?;
         reflect_component.insert(&mut entity_world_mut, &*reflected, type_registry);
```
Comment (ChristopherBiscardi) [inline crates/bevy_remote/src/builtin_methods.rs]: if there a reason we don't get rid of all of this code and use `insert_reflect` instead? https://docs.rs/bevy/0.16.1/bevy/prelude/struct.EntityWorldMut.html#method.insert_reflect

**Comment by natepiano** [comment]
any chance this one will make it into 0.17?

**Comment by janhohenheim** [comment]
I'm in favor. This is low-risk and just expands existing functionality @alice-i-cecile 
But I'll let you make the call

**Comment by natepiano** [comment]
thanks - and I'd argue more than expands, technically true, but as it stands the ergonomics are terrible for Components to require these derives in order for brp methods bevy/spawn and bevy/insert to work.  Thanks much!

**Review by ChristopherBiscardi — APPROVED** [review]
the insert_reflect change is a good bugfix afaict since previously this codepath was using a custom implementation of a function that already existed, but I haven't had a chance to run the code and test it.

**Comment by janhohenheim** [comment]
I'll take the liberty of putting it in the milestone, feel free to remove it again :P

**Comment by Leinnan** [comment]
@alice-i-cecile  any idea why bot did remove it from queue?

**Comment by janhohenheim** [comment]
IIRC CI is borked in general due to new stable lints. Don't quote me on this

**Comment by natepiano** [comment]
Laugh. That caught me too. So many lints. So little time.
