### PR TITLE
Fix viewport_to_world for orthographic cameras and add regression tests

### LINKED ISSUE #20762: viewport_to_world bug
Bevy version 0.17.0-dev

I'm having issues in my project since commit 84cb25595f1a5b5c2a2aee47f70a9fd982c19238 where some entities won't be rendered.

`viewport_to_world` is the only change in that commit. I don't understand its code well enough but I can show the function now returns values that differ from what it returned on the previous commit in the 2D case. In that case, the `Dir3` returned has the same `origin` but its `direction` has an opposite z coordinate. The doc says the direction returned should be (0,0,-1) if the camera's projection is orthographic which was the case before. On a side note, the x and y coordinates are not zero anymore but I don't know if this is a concern. There seems to be no problem in the 3D case.

### PR DESCRIPTION
**Pull request by atlv24**
# Objective

- Fixes #20762

## Solution

- Orthographic directions behave differently, and need the point-difference. We can still avoid the matrix compose and world translation precision losses though.

## Testing

- Added regression tests

### CODE REVIEW

**Review by alice-i-cecile — APPROVED** [review]

**Comment by alice-i-cecile** [comment]
Thanks @gwafotapa for testing on `main` :) If you're comfortable, I would love a review.

File: crates/bevy_camera/src/camera.rs [hunk 1]
```diff
@@ -610,28 +610,27 @@ impl Camera {
...
 
-        let ndc_point_near = (rect_relative * 2. - Vec2::ONE).extend(1.0).into();
+        let ndc_point_near = ndc_xy.extend(1.0).into();
+        // Using EPSILON because an ndc with Z = 0 returns NaNs.
+        let ndc_point_far = ndc_xy.extend(f32::EPSILON).into();
+        let view_from_clip = self.computed.clip_from_view.inverse();
+        let world_from_view = camera_transform.affine();
         // We multiply the point by `view_from_clip` and then `world_from_view` in sequence to avoid the precision loss
         // (and performance penalty) incurred by pre-composing an affine transform with a projective transform.
         // Additionally, we avoid adding and subtracting translation to the direction component to maintain precision.
```
Comment (IceSentry) [inline crates/bevy_camera/src/camera.rs:625]: The comments is not valid anymore

Comment (atlv24) [reply crates/bevy_camera/src/camera.rs:625]: It is still valid

Comment (atlv24) [reply crates/bevy_camera/src/camera.rs:625]: The point here is we arent adding world translation into the points until we want an origin, this way we're not contaminating direction precision with world translation. (it should be invariant, direction precision would degrade far from the origin otherwise)

**Comment by mockersf** [comment]
Could you update the PR so that the title will be more explicit on the bug fixed in the commit log?

File: crates/bevy_camera/src/camera.rs [hunk 2]
```diff
@@ -610,28 +610,27 @@ impl Camera {
         let target_rect = self
             .logical_viewport_rect()
             .ok_or(ViewportConversionError::NoViewportSize)?;
-        let mut rect_relative = (viewport_position - target_rect.min) / target_rect.size();
+        let rect_relative = (viewport_position - target_rect.min) / target_rect.size();
+        let mut ndc_xy = rect_relative * 2. - Vec2::ONE;
         // Flip the Y co-ordinate origin from the top to the bottom.
```
Comment (gwafotapa) [inline crates/bevy_camera/src/camera.rs]: That comment should be updated or removed.

File: crates/bevy_camera/src/camera.rs (hunk 1 above)
Comment (IceSentry) [reply crates/bevy_camera/src/camera.rs:625]: Yeah, sorry, I completely misread the comment and the code. Makes sense to me now. For some reason I didn't see all the `world_from_view` so I thought it was outdated.

File: crates/bevy_camera/src/camera.rs [hunk 3]
```diff
@@ -910,3 +909,91 @@ impl CameraMainTextureUsages {
...
+        };
+        camera.computed.target_info = Some(RenderTargetInfo {
+            physical_size: viewport.physical_size,
+            scale_factor: 1.0,
+        });
+        projection.update(
+            viewport.physical_size.x as f32,
+            viewport.physical_size.y as f32,
+        );
+        camera.computed.clip_from_view = match &camera.sub_camera_view {
```
Comment (gwafotapa) [inline crates/bevy_camera/src/camera.rs]: The `match` is unnecessary. `camera.sub_camera_view` is always `None`. Unless we're worried that its default value might change in the future.

File: crates/bevy_camera/src/camera.rs (hunk 2 above)
Comment (atlv24) [reply crates/bevy_camera/src/camera.rs]: Its still relevant, it applies to the line below it.

File: crates/bevy_camera/src/camera.rs (hunk 3 above)
Comment (atlv24) [reply crates/bevy_camera/src/camera.rs]: True, I just copy pasted it from camera_update system

File: crates/bevy_camera/src/camera.rs [hunk 4]
```diff
@@ -910,3 +909,91 @@ impl CameraMainTextureUsages {
...
+            Some(sub_view) => projection.get_clip_from_view_for_sub(sub_view),
+            None => projection.get_clip_from_view(),
+        };
```
Comment (atlv24) [inline crates/bevy_camera/src/camera.rs]:
```suggestion
        camera.computed.clip_from_view = projection.get_clip_from_view();
```

File: crates/bevy_camera/src/camera.rs (hunk 2 above)
Comment (gwafotapa) [reply crates/bevy_camera/src/camera.rs]: But it's not accurate anymore. It's not the origin that is flipped now but the coordinate itself. And where explaining that `y = 1 - y` flipped the origin, I'm not sure saying that `y = -y` flips Y really adds value.

Comment (atlv24) [reply crates/bevy_camera/src/camera.rs]: okay i get what you're pointing out, one sec.
