### PR TITLE
Fix sparse buffer error on devices with low storage buffer limits

### LINKED ISSUE #23404: `max_storage_buffers_per_shader_stage` limit isn't checked when updating sparse buffer
## Bevy version and features

- main after https://github.com/bevyengine/bevy/pull/23242

## What you did

```sh
WGPU_SETTINGS_PRIO=webgl2 cargo r --example 3d_scene
```
Or run the example on webgl2

## What went wrong

```
2026-03-18T06:05:58.637742Z ERROR bevy_render::error_handler: Caught rendering error: Validation Error

Caused by:
  In Device::create_bind_group_layout, label = 'sparse buffer update bind group layout'
    Too many bindings of type StorageBuffers in Stage ShaderStages(COMPUTE), limit is 0, count was 3. Check the limit `max_storage_buffers_per_shader_stage` passed to `Adapter::request_device`

2026-03-18T06:05:58.680247Z ERROR bevy_render::error_handler: Caught rendering error: Validation Error

Caused by:
  In Device::create_pipeline_layout
    BindGroupLayout with 'sparse buffer update bind group layout' label is invalid

2026-03-18T06:05:58.680400Z ERROR bevy_render::error_handler: Caught rendering error: Validation Error

Caused by:
  In Device::create_compute_pipeline, label = 'sparse buffer update pipeline'
    PipelineLayout with '' label is invalid
```

### PR DESCRIPTION
**Pull request by MarelGuy**
## Objective

Prevents a validation error where max_storage_buffers_per_shader_stage is less than 3 when using sparse buffers.

Fixes #23404

## Solution

 - Added a hardware limit check inside the `FromWorld` implementation for `SparseBufferUpdatePipelines`.
 - Wrapped the pipeline's layout and shader fields in Options.
 - Updated `AtomicSparseBufferVec::write_buffers` to pass the `RenderDevice `into the `should_perform_full_reupload` check. If the storage buffer limit is too low, the buffer now falls back to `write_entire_buffer`.

## Testing

- Did you test these changes? If so, how?
All commands below were ran with and without `WGPU_SETTINGS_PRIO=webgl2`:
cargo test -p bevy_render
cargo r --example 3d_gizmos --features free_camera
cargo r --example 3d_rotation
cargo r --example 3d_scene
cargo r --example 3d_shapes
cargo r --example 3d_text_gizmos
cargo r --example 3d_viewport_to_world 

- Are there any parts that need more testing?
Not that i reckon
- How can other people (reviewers) test your changes? Is there anything specific they need to know?
Run the test written above
- If relevant, what platforms did you test these changes on, and are there any important ones you can't test?
Tested locally on Linux 6.19.8-1-cachyos using an NVIDIA RTX 4070 Super and an AMD Ryzen 9 9950X. Could not test on other systems or hardware.

### CODE REVIEW

File: crates/bevy_render/src/render_resource/sparse_buffer_vec.rs [hunk 1]
```diff
@@ -276,6 +276,21 @@ fn clear_sparse_buffer_jobs(mut sparse_buffer_update_jobs: ResMut<SparseBufferUp
 
 impl FromWorld for SparseBufferUpdatePipelines {
     fn from_world(world: &mut World) -> Self {
+        let render_device = world.resource::<RenderDevice>();
+        let limit = render_device.limits().max_storage_buffers_per_shader_stage;
+
+        if limit < 3 {
+            warn!(
+                "Sparse buffer updates disabled. RenderDevice lacks support: max_storage_buffers_per_shader_stage ({}) < 3.",
+                limit
```
Comment (pcwalton) [inline crates/bevy_render/src/render_resource/sparse_buffer_vec.rs:285]: I think I'd change this to `info!()` as we don't want developers to assume that there's something wrong.
