### PR TITLE
Don't overalign aligned values in `gpu_readback::align_byte_size`

### LINKED ISSUE #16992: Incorrect alignment with `RenderDevice::align_copy_bytes_per_row` when using `Readback::texture`
## Bevy version

v0.15.0

```ignore
AdapterInfo { name: "AMD Radeon RX 6700 XT (RADV NAVI22)", vendor: 4098, device: 29663, device_type: DiscreteGpu, driver: "radv", driver_info: "Mesa 24.2.6", backend: Vulkan }
```

## What you did

Please excuse my messy code 😅 

```rust
fn main() {
    App::new()
        .add_plugins(DefaultPlugins.set(ImagePlugin::default_nearest()))
        .add_systems(Startup, setup)
        .run();
}

fn setup(
    mut commands: Commands,
    asset_server: Res<AssetServer>,
    mut images: ResMut<Assets<Image>>,
) {
    let bake_layer = RenderLayers::layer(1);

    let size = Extent3d {
        width: 128,
        height: 128,
        ..default()
    };
    let mut image = Image::new_fill(
        size,
        TextureDimension::D2,
        &[0, 0, 0, 0],
        TextureFormat::Bgra8UnormSrgb,
        RenderAssetUsages::default(),
    );
    image.texture_descriptor.usage = TextureUsages::TEXTURE_BINDING
        | TextureUsages::COPY_DST
        | TextureUsages::COPY_SRC
        | TextureUsages::RENDER_ATTACHMENT;

    let image_handle = images.add(image);

    commands.spawn((
        Camera3d::default(),
        Transform::from_xyz(0.5, 0.0, -0.91)
            .with_rotation(Quat::from_rotation_x(-50.5f32.to_radians())),
        Projection::Orthographic(OrthographicProjection {
            scaling_mode: ScalingMode::WindowSize,
            scale: 1.0 / 64.0,
            near: -128.0,
            ..OrthographicProjection::default_3d()
        }),
        Camera {
            target: image_handle.clone().into(),
            clear_color: Color::NONE.into(),
            ..default()
        },
        bake_layer.clone().with(0),
    ));

    commands.spawn((
        DirectionalLight {
            illuminance: light_consts::lux::OVERCAST_DAY,
            shadows_enabled: true,
            ..default()
        },
        Transform {
            translation: Vec3::new(0.0, 10.0, 0.0),
            rotation: Quat::from_rotation_x(-PI / 2.0)
                * Quat::from_rotation_z(39.5f32.to_radians()),
            ..default()
        },
        CascadeShadowConfigBuilder {
            first_cascade_far_bound: 4.0,
            maximum_distance: 10.0,
            ..default()
        }
        .build(),
        bake_layer.clone(),
    ));
    let handle = asset_server.load(GltfAssetLabel::Scene(0).from_asset("tile/example.glb"));

    commands.spawn((SceneRoot(handle), bake_layer.clone()));

    commands.spawn(Sprite::from_image(image_handle.clone()));
    commands.spawn((
        Camera2d,
        Camera {
            order: 1,
            ..default()
        },
        OrthographicProjection {
            ..OrthographicProjection::default_2d()
        },
    ));

    commands
        .spawn(Readback::texture(image_handle.clone()))
        .observe(move |trigger: Trigger<ReadbackComplete>| {
            let row_bytes = size.width as usize * 4;
            let aligned_row_bytes = RenderDevice::align_copy_bytes_per_row(row_bytes) as usize;

            let image_data = &trigger.event().0;
            let image_data = image_data
                .chunks(aligned_row_bytes)
                .take(size.height as usize)
                .flat_map(|row| &row[..row_bytes.min(row.len())])
                .cloned()
                .collect();
            let image = Image::new(
                size,
                TextureDimension::D2,
                image_data,
                TextureFormat::Bgra8UnormSrgb,
                RenderAssetUsages::default(),
            );
            let image = image.try_into_dynamic().unwrap();
            image.save("tmp.png").unwrap();
        });
}

```

## What went wrong

If it's not clear, break this out into:

- what were you expecting? a proper image
  - Image
- what actually happened? weird interlaced image
  - Image

## Additional information

The proper image was generated with this alignment function derived from the `headless_render` example
```rust
pub(crate) fn align_byte_size(value: u32) -> u32 {
    let align = wgpu::COPY_BYTES_PER_ROW_ALIGNMENT;
    value + (align - (value % align))
}
```
Compare to [`RenderDevice::align_copy_bytes_per_row`](https://github.com/bevyengine/bevy/blob/64efd08e13c55598587f3071070f750f8945e28e/crates/bevy_render/src/renderer/render_device.rs#L234C1-L238C6) which contains an extra `% align`

### PR DESCRIPTION
**Pull request by Brezak**
# Objective

Fix alignment calculations in our rendering code.
Fixes #16992 

The `gpu_readback::align_byte_size` function incorrectly rounds aligned values to the next alignment.
If we assume the alignment to be 256 (because that's what wgpu says it its) the function would align 0 to 256, 256 to 512, etc...

## Solution

Forward the `gpu_readback::align_byte_size` to `RenderDevice::align_copy_bytes_per_row` so we don't implement the same method twice.
Simplify `RenderDevice::align_copy_bytes_per_row`.

## Testing

Ran the code provided in #16992 to see if the issue has been solved + added a test to check if `align_copy_bytes_per_row` returns the correct values.

### CODE REVIEW

File: crates/bevy_render/src/gpu_readback.rs [hunk 1]
```diff
@@ -349,7 +349,7 @@ fn map_buffers(mut readbacks: ResMut<GpuReadbacks>) {
 // Utils
 
 pub(crate) fn align_byte_size(value: u32) -> u32 {
```
Comment (alice-i-cecile) [inline crates/bevy_render/src/gpu_readback.rs:351]: Can you add basic doc strings to this function? It's hard to validate that this is doing what it says it should without them :)

File: crates/bevy_render/src/renderer/render_device.rs [hunk 2]
```diff
@@ -231,10 +231,16 @@ impl RenderDevice {
         buffer.map_async(map_mode, callback);
     }
 
+    // Aligns `row_bytes` to [`wgpu::COPY_BYTES_PER_ROW_ALIGNMENT`]
```
Comment (alice-i-cecile) [inline crates/bevy_render/src/renderer/render_device.rs:234]: A little more detail about what "aligning" is would be helpful here.

File: crates/bevy_render/src/gpu_readback.rs (hunk 1 above)
Comment (Brezak) [reply crates/bevy_render/src/gpu_readback.rs:352]: Done. I've also tried to divine what the other util methods do.

**Review by alice-i-cecile — APPROVED** [review]
Good fix, and the docs are much appreciated. One tiny PR at a time we'll make Bevy's rendering approachable...

File: crates/bevy_render/src/renderer/render_device.rs [hunk 3]
```diff
@@ -231,10 +231,16 @@ impl RenderDevice {
         buffer.map_async(map_mode, callback);
     }
 
+    // Rounds up `row_bytes` to be a multiple of [`wgpu::COPY_BYTES_PER_ROW_ALIGNMENT`].
     pub fn align_copy_bytes_per_row(row_bytes: usize) -> usize {
```
Comment (BenjaminBrienen) [inline crates/bevy_render/src/renderer/render_device.rs:235]: Can this be const?

**Review by BenjaminBrienen — APPROVED** [review]

**Review by BenjaminBrienen — APPROVED** [review]
Epic
