### PR TITLE
Fix GLTF scene dependencies and make full scene renders predictable

### LINKED ISSUE #10688: Race condition in assets loading
## Bevy version

0.12

## What you did

My game have a plugin that generates preview images for buttons from 3D models. And I migrated from 0.11 to 0.12.

## What went wrong

I noticed that my preview generation plugin sometimes generates empty images. I looked into it deeper and discovered that `AssetServer` sometimes returns `LoadState::Loaded` too early.

## Additional information

I managed to extract and simplify this logic into a minimal project that reproduces the issue: [assets_render.zip](https://github.com/bevyengine/bevy/files/13432070/assets_render.zip)

If you run it, you will see that some generated images are empty (sometimes happens on second run on my machine, but usually always happen):
image

If you disable `multi-threaded` feature in `Cargo.toml`, all images will be rendered correctly:
image

### PR DESCRIPTION
**Pull request by cart**
# Objective

Fixes #10688

There were a number of issues at play:

1. The GLTF loader was not registering Scene dependencies properly. They were being registered at the root instead of on the scene assets. This made `LoadedWithDependencies` fire immediately on load.
2. Recursive labeled assets _inside_ of labeled assets were not being loaded. This only became relevant for scenes after fixing (1) because we now add labeled assets to the nested scene `LoadContext` instead of the root load context. I'm surprised nobody has hit this yet. I'm glad I caught it before somebody hit it.
3. Accessing "loaded with dependencies" state on the Asset Server is boilerplatey + error prone (because you need to manually query two states).

## Solution

1. In GltfLoader, use a nested LoadContext for scenes and load dependencies through that context.
2. In the `AssetServer`, load labeled assets recursively.
3. Added a simple `asset_server.is_loaded_with_dependencies(id)`

I also added some docs to `LoadContext` to help prevent this problem in the future.

---

## Changelog

- Added `AssetServer::is_loaded_with_dependencies`
- Fixed GLTF Scene dependencies
- Fixed nested labeled assets not being loaded

### CODE REVIEW

**Review by djeedai — APPROVED** [review]
Looks good, but any chance we add tests for some of these things so they don't regress in the future?

File: crates/bevy_asset/src/loader.rs [hunk 1]
```diff
@@ -353,6 +353,11 @@ impl<'a> LoadContext<'a> {
 
     /// This will add the given `asset` as a "labeled [`Asset`]" with the `label` label.
     ///
+    /// Warning: this will not assign dependencies to the given `asset`. If adding an asset
```
Comment (Nilirad) [inline crates/bevy_asset/src/loader.rs:356]: The warning word can either be capitalized or

Comment (djeedai) [reply crates/bevy_asset/src/loader.rs:356]: Looks important enough for correctness to be a heading, good catch.

Comment (alice-i-cecile) [reply crates/bevy_asset/src/loader.rs:356]:
```suggestion
    /// # Warning
    ///
    /// This will not assign dependencies to the given `asset`. If adding an asset
```

File: crates/bevy_asset/src/server/mod.rs [hunk 2]
```diff
@@ -711,6 +711,13 @@ impl AssetServer {
             .unwrap_or(RecursiveDependencyLoadState::NotLoaded)
     }
 
+    /// Returns true if the asset and all of its dependencies (recursive) have been loaded.
```
Comment (alice-i-cecile) [inline crates/bevy_asset/src/server/mod.rs:714]: Might be worth linking to this from the standard `is_loaded` method.

**Review by alice-i-cecile — APPROVED** [review]

**Comment by cart** [comment]
> Looks good, but any chance we add tests for some of these things so they don't regress in the future?

I'm on board for more tests, but that will require engineering effort that would otherwise delay 0.12.1 so I'm not going to block on that.
