### PR TITLE
Have `System::run_unsafe` return `Result`.

### LINKED ISSUE #18796: Eager system parameter validation causes issues with combinator and piped systems
> For some history, see https://github.com/bevyengine/bevy/pull/16638#issuecomment-2526191119:
> 
> In a combination system, like `a.and(b)` or `a.pipe(b)` we're running param checks for _all_ systems before running any of them. This results in `resource_exists::<MyRes>.and(do_stuff)` failing params, because `do_stuff` doesn't have `MyRes` even though it wouldn't run because of failed condition. 
> ...
> Since combination systems are incomplete, let's just ensure the first system (or _the_ system, if no combinations are used) works correctly with fallible params, do not check params for subsequent ones and just let app crash like it did in 0.14. In 0.16 we can ship the correct param checking behavior, where we do it directly before running a system.

 _Originally posted by @chescock in [#18755](https://github.com/bevyengine/bevy/issues/18755#issuecomment-2784816916)_

The same problem occurs with combinator systems, particularly when using the short-circuiting `and` behavior. The same bug as in #18755 exists for combinator systems, but fixing it breaks much more normal use cases (and one of our doc tests!).

## Proposed solution

In order to resolve this (and other issues, see #8857, #2381), we need to retain the unique identity of systems even when piped.

> we can ship the correct param checking behavior, where we do it directly before running a system.

This is the ideal solution, but can't work with the current architecture. These systems, from the perspective of the schedule (and thus the executor), are only one system.

### LINKED ISSUE #19722: Fallible one-shot systems silently swallow errors
>  I see it got merged, but I don't think that PR quite works the way we want.  It lets you use any output type with commands.run_system_cached, but it just drops the output with ;.  So if you pass a fallible system and it fails, it will silently drop the Result::Err, and not pass it to the error handler.

From @chescock about #19678.

### PR DESCRIPTION
**Pull request by chescock**
# Objective

Allow combinator and pipe systems to delay validation of the second system, while still allowing the second system to be skipped.  

Fixes #18796

Allow fallible systems to be used as one-shot systems, reporting errors to the error handler when used through commands.  

Fixes #19722

Allow fallible systems to be used as run conditions, including when used with combinators.  Alternative to #19580.

Always validate parameters when calling the safe `run_without_applying_deferred`, `run`, and `run_readonly` methods on a `System`.  

## Solution

Have `System::run_unsafe` return a `Result`.  

We want pipe systems to run the first system before validating the second, since the first system may affect whether the second system has valid parameters.  But if the second system skips then we have no output value to return!  So, pipe systems must return a `Result` that indicates whether the second system ran.  

But if we just make pipe systems have `Out = Result<B::Out>`, then chaining `a.pipe(b).pipe(c)` becomes difficult.  `c` would need to accept the `Result` from `a.pipe(b)`, which means it would likely need to return `Result` itself, giving `Result<Result<Out>>`!  

Instead, we make *all* systems return a `Result`!  We move the handling of fallible systems from `IntoScheduleConfigs` and `IntoObserverSystem` to `SystemParamFunction` and `ExclusiveSystemParamFunction`, so that an infallible system can be wrapped before being passed to a combinator.  

As a side effect, this enables fallible systems to be used as run conditions and one-shot systems.  

Now that the safe `run_without_applying_deferred`, `run`, and `run_readonly` methods return a `Result`, we can have them perform parameter validation themselves instead of requiring each caller to remember to call them.  `run_unsafe` will continue to not validate parameters, since it is used in the multi-threaded executor when we want to validate and run in separate tasks.

Note that this makes type inference a little more brittle.  A function that returns `Result<T>` can be considered either a fallible system returning `T` or an infallible system returning `Result<T>` (and this is important to continue supporting `pipe`-based error handling)!  So there are some cases where the output type of a system can no longer be inferred.  It will work fine when directly adding to a schedule, since then the output type is fixed to `()` (or `bool` for run conditions).  And it will work fine when `pipe`ing to a system with a typed input parameter.

I used a dedicated `RunSystemError` for the error type instead of plain `BevyError` so that skipping a system does not box an error or capture a backtrace.

### CODE REVIEW

File: crates/bevy_ecs/src/schedule/condition.rs [hunk 1]
```diff
@@ -1211,10 +1211,10 @@ where
...
     fn combine(
         input: <Self::In as SystemInput>::Inner<'_>,
-        a: impl FnOnce(SystemIn<'_, A>) -> A::Out,
-        b: impl FnOnce(SystemIn<'_, B>) -> B::Out,
-    ) -> Self::Out {
-        a(input) || b(input)
+        a: impl FnOnce(SystemIn<'_, A>) -> Result<A::Out, RunSystemError>,
+        b: impl FnOnce(SystemIn<'_, A>) -> Result<B::Out, RunSystemError>,
+    ) -> Result<Self::Out, RunSystemError> {
+        Ok(a(input)? || b(input)?)
```
[the remark this answers is not in the document]
Comment (alice-i-cecile) [reply crates/bevy_ecs/src/schedule/condition.rs:1217]: I was told this short-circuiting was preferable in review to avoid breaking existing code and reduce pointless failures.

I'm not sure I agree still, but it's best to split that change out.

[the remark this answers is not in the document]
Comment (chescock) [reply crates/bevy_ecs/src/schedule/condition.rs:1217]: > I was told this short-circuiting was preferable in review to avoid breaking existing code and reduce pointless failures.
> 
> I'm not sure I agree still, but it's best to split that change out.

Sorry, I don't quite follow.  What would you like me to split out?  

The core change here is making `System::run` return a `Result`, so we have to do *something* to handle the case where fallible systems are used with an `or` combinator.  Adding `?`s and wrapping it in `Ok` seemed like the simplest change, and was consistent with the other combinators, so that's what I did.  But it's also kind of weird, so I wanted to highlight it.  

I *think* the only behavior change to existing code is that a failing `Single` or `Populated` in the second system will now return `Err` and be treated as `false`, while before this it would skip validation entirely and then panic.

**Comment by chescock** [comment]
Okay, I got this working again!  My original approach conflicted with the changes for hotpatching, but I managed to make a simpler approach work that removes the conflict.  

I did run into a few conflicts with other recent PRs that were making fallible systems work in more places.  I mostly reverted them in the hope that this PR supersedes them, but tried to take any unit tests.  

#19678 made one-shot systems accept any output type.  When combined with this PR, passing a `Result` was ambiguous as to whether it was a fallible system returning `()` or an infallible system returning `Result`.  But we don't actually *want* to allow systems to return a `Result` that is silently dropped, as noted in #19722.  So I reverted #19678, and added another unit test showing that errors are passed to the error handler.  

#19553 made conditions accept `Result<bool, BevyError>` and `Result<(), BevyError>`, but treated errors as `false` without passing them to the error handler.  This PR instead passes them to the error handler, and then removes support for `()`.  

One of the goals of this PR is to treat returned errors through the same path as parameter validation errors, so treating them differently in conditions would be inconsistent.  In particular, pipe and combinator systems return validation errors from the second system as errors, so `run_if(a.and(b))` will report validation errors from `b` as errors.  If we ignored returned errors in conditions, then we would wind up ignoring validation errors from `b`.  

But based on the comments in #19403, I expect that change to be controversial.

File: crates/bevy_ecs/src/observer/runner.rs [hunk 2]
```diff
@@ -64,37 +68,23 @@ pub(super) fn observer_system_runner<E: Event, B: Bundle, S: ObserverSystem<E, B
...
-                        e.into(),
-                        ErrorContext::Observer {
-                            name: (*system).name(),
-                            last_run: (*system).get_last_run(),
-                        },
-                    );
-                }
-            }
-        }
+        if let Err(RunSystemError::Failed(err)) = (*system)
```
Comment (NthTensor) [inline crates/bevy_ecs/src/observer/runner.rs:71]: Idly interested in benchmarks of this. Removing the branch here should be net positive.

File: crates/bevy_ecs/src/system/system.rs [hunk 3]
```diff
@@ -382,34 +401,57 @@ impl RunSystemOnce for &mut World {
...
-        /// The identifier of the system that was run.
-        system: DebugName,
-        /// The returned parameter validation error.
-        err: SystemParamValidationError,
-    },
+    /// This is not considered an error.
+    Skipped(SystemParamValidationError),
+    /// System returned an error or failed required parameter validation.
+    Failed(BevyError),
+}
```
Comment (NthTensor) [inline crates/bevy_ecs/src/system/system.rs:416]: Ooh I prefer this framing. There's been some ambiguity with what returning `Result::Err` from a system really means. Is it an error, or is it just part of normal control flow. This tells us: The system failed to complete, which is explicitly an error.

Comment (alice-i-cecile) [reply crates/bevy_ecs/src/system/system.rs:416]: I like this framing too.

File: crates/bevy_ecs/src/system/system.rs [hunk 4]
```diff
@@ -382,34 +401,57 @@ impl RunSystemOnce for &mut World {
...
-            })?;
-        Ok(system.run(input, self))
+        system.run(input, self)
     }
 }
 
 /// Running system failed.
-#[derive(Error, Debug)]
+#[derive(Debug)]
 pub enum RunSystemError {
```
Comment (NthTensor) [inline crates/bevy_ecs/src/system/system.rs:410]: Bikeshed: Might we want to call this `RunSystemResult` or something? It has `Error` in the name and then the next line says "this is not considered an error".

Comment (chescock) [reply crates/bevy_ecs/src/system/system.rs:410]: > It has `Error` in the name and then the next line says "this is not considered an error".

Hah!  Fair :).  

> Might we want to call this `RunSystemResult` or something? 

I would like that in isolation, but `Result<Out, RunSystemResult>` seems odd.  

I'm happy to change it if there is a strong alternative, but I might be too stuck thinking that the thing that goes in a `Result::Err` is an "error" to come up with a better name myself.

File: crates/bevy_ecs/src/schedule/condition.rs (hunk 1 above)
[the remark this answers is not in the document]
Comment (alice-i-cecile) [reply crates/bevy_ecs/src/schedule/condition.rs:1218]: My preference was to leave the behavior completely unchanged in this PR. That said, I prefer this behavior and won't block on it.

**Review by alice-i-cecile — APPROVED** [review]
I prefer the framing, it plugs multiple consistency holes in our API design, it's noticeably simpler and the migration guide is excellent. Very nice work; merging.
