### PR TITLE
Fixes panic when using Option<Gizmos>

### LINKED ISSUE #14949: Optional `SystemParam` (especially gizmos)
## What problem does this solve or what need does it fill?
Gizmos cannot be used optionally in system parameters, which is annoying if you want to configurably not have rendering enabled for a game. E.g. for a headless server.

## What solution would you like?
`impl<Config, Clear> SystemParam for Option<Gizmos<Config, Clear>> { ... }`

*Potentially* implementing forwarding methods to the underlying methods, but that is a lot of boilerplate... I could do it, just not sure whether this usecase is worth that maintenance burden.

## What alternative(s) have you considered?
Removing the gizmos entirely, but that is just kind of sad since it adds a lot of useful information when I am using a non-headless mode.

### PR DESCRIPTION
**Pull request by kfc35**
# Objective

- Fixes #14949 
- Currently an `Option<Gizmos>` causes a panic when the config group backing `Gizmos` has not been initialized. The desired behavior is to have it be `None` instead of course.

## Solution

`Gizmos` is a non `#[derive]`'d `SystemParam` that requires its 
- `GizmoConfigGroup` to have an entry in `GizmoConfigStore`
- Various `GizmoStorage`s to be inserted as resources.

In order to support a non-panicking `Option<Gizmos>` `SystemParam` in a non-intrusive way for users when the Gizmo Config Group has not been set up intentionally, this PR:
- Adds ergonomic methods to get a group’s config fallibly to the `GizmoConfigStore`
- Changes the `validate_param` method of `Gizmos` to return an error in the event that it could not find its own config in the `GizmoConfigStore`
- Changes the `apply` method of `GizmoBuffer` to only apply changes if the `GizmoStorage` for the config group exists. 

## Testing

I modified the 2d gizmos example (`cargo run --example 2d_gizmos`) by:
- commenting out the init of the custom gizmo group `// .init_gizmo_group::<MyRoundGizmos>()`
- Using options (i.e. `Option<Gizmos>` and `Option<Gizmos<MyRoundGizmos>>`) for the two `Gizmos` system parameters in `draw_example_collection` and requiring `my_gizmos_option.is_some()` before using an unwrapped `my_gizmos` to draw things.
- Using the new `GizmoConfigStore` method `try_config_mut` when trying to get the config for `MyRoundGizmos`, and only proceeding to change its settings if `my_config_option.is_some()`

There are no crashes. Default Gizmos continue to be drawn, and `MyRoundGizmos` are not drawn. Changing the settings still works for default gizmos, and has no effect if they were to be applied to `MyRoundGizmos`. There seems to be no deterioration in performance for the example.

### CODE REVIEW

File: crates/bevy_gizmos/src/gizmos.rs [hunk 1]
```diff
@@ -348,11 +365,12 @@ where
     Clear: 'static + Send + Sync,
 {
     fn apply(&mut self, _system_meta: &SystemMeta, world: &mut World) {
-        let mut storage = world.resource_mut::<GizmoStorage<Config, Clear>>();
-        storage.list_positions.append(&mut self.list_positions);
-        storage.list_colors.append(&mut self.list_colors);
-        storage.strip_positions.append(&mut self.strip_positions);
-        storage.strip_colors.append(&mut self.strip_colors);
+        if let Some(mut storage) = world.get_resource_mut::<GizmoStorage<Config, Clear>>() {
```
Comment (kfc35) [inline crates/bevy_gizmos/src/gizmos.rs:370]: Note to self that I need to also make this change to `queue()` #22800

File: crates/bevy_gizmos/src/gizmos.rs [hunk 2]
```diff
@@ -230,9 +230,26 @@ where
...
+                &mut state.state,
+                system_meta,
+                world,
+                world.change_tick(),
+            )
+        };
+        // This if-block is to accommodate an Option<Gizmos> SystemParam.
+        // The user may decide not to initialize a gizmo group, so its config will not exist.
+        if f1.into_inner().try_config::<Config>().is_none() {
+            Err(SystemParamValidationError::skipped::<Self>(
```
Comment (chescock) [inline crates/bevy_gizmos/src/gizmos.rs]: This should probably be `invalid`, to preserve the existing behavior of plain `Gizmos` parameters failing with a helpful message.  Using `skipped` here will cause systems to silently be skipped if the validation fails.  

`Option<Gizmos>` will still work, since it converts either kind of error to `None`.  And users who do want the skipping behavior can get it using `If<Gizmos>`.  

```suggestion
            Err(SystemParamValidationError::invalid::<Self>(
```

File: crates/bevy_gizmos/src/gizmos.rs [hunk 3]
```diff
@@ -230,9 +230,26 @@ where
...
+                format!("Requested config {} does not exist in `GizmoConfigStore`! Did you forget to add it using `app.init_gizmo_group<T>()`?", 
+                Config::type_path())))
+        } else {
+            // SAFETY: Delegated to existing `SystemParam` implementation.
+            unsafe {
+                GizmosState::<Config, Clear>::validate_param(&mut state.state, system_meta, world)
```
Comment (chescock) [inline crates/bevy_gizmos/src/gizmos.rs]: I think you want to call `validate_param` *before* `get_param`, and early-out with `?` if it fails.  If the `GizmoConfigStore` resource is missing, then the `Res` in `GizmosState` will report the error through `validate_param`, but will panic if you call `get_param`.

**Review by chescock — COMMENTED** [review]
Oh, sorry for closing #14949 early!  I'm not familiar with gizmos, and assumed the only failure case was that the `GizmoConfigStore` resource didn't exist.

File: crates/bevy_gizmos/src/gizmos.rs [hunk 4]
```diff
@@ -230,9 +230,28 @@ where
...
+            GizmosState::<Config, Clear>::get_param(
+                &mut state.state,
+                system_meta,
+                world,
+                world.change_tick(),
+            )
+        };
+        // This if-block is to accommodate an Option<Gizmos> SystemParam.
+        // The user may decide not to initialize a gizmo group, so its config will not exist.
+        if f1.into_inner().get_config::<Config>().is_none() {
```
Comment (chescock) [inline crates/bevy_gizmos/src/gizmos.rs]: Very minor nit, but I bet you can leave off `into_inner()` and rely on the `Deref` impl.  

... Although you *do* need it in `get_param`, so maybe it's more consistent to use it here, too.

```suggestion
        if f1.get_config::<Config>().is_none() {
```
