### PR TITLE
Warn about missing `StatesPlugin` when installing states

### LINKED ISSUE #13874: [Bug?] State is not updated when manually updating App
## Bevy version

v0.14.0-rc.2

## What you did

My library has a similar to the following test code, but it failed after I updated the bevy version from v0.13.2 to v0.14.0-rc2.

```rust
use bevy::prelude::*;

fn main() {
    let mut app = App::new();
    app.add_plugins(MinimalPlugins);
    app.init_resource::<StateChanged>();
    app.init_state::<GameState>();
    app.add_systems(Update, wait_state);
    app.update();
    assert!(!app.world().resource::<StateChanged>().0);
    app.insert_state(GameState::InGame);
    app.update();
    // panic!! 
    assert!(app.world().resource::<StateChanged>().0);
}

#[derive(Resource, Default, Debug)]
struct StateChanged(bool);

#[derive(Eq, PartialEq, Debug, Default, Copy, Clone, Hash, States)]
enum GameState {
    #[default]
    Title,
    InGame,
}

fn wait_state(
    mut changed: ResMut<StateChanged>,
    state: Res<State<GameState>>,
) {
    if matches!(state.get(), GameState::InGame) {
        changed.0 = true;
    }
}
```

## What went wrong

Console output: 
```shell
thread 'main' panicked at src\main.rs:19:5:
assertion failed: app.world().resource::<StateChanged>().0
```

### PR DESCRIPTION
**Pull request by MiniaczQ**
# Objective

- Fixes #13874

## Solution

- Confirm that the `StatesPlugin` is installed when trying to add states.
- Skipped for state scoped entities, since those will warn about missing states.

### CODE REVIEW

**Review by alice-i-cecile — APPROVED** [review]
Great, I think that's a clean solution. Much better than docs!

File: crates/bevy_state/src/app.rs [hunk 1]
```diff
@@ -57,8 +57,16 @@ pub trait AppExtStates {
     fn enable_state_scoped_entities<S: States>(&mut self) -> &mut Self;
 }
 
+/// Separate function to only warn once for all state installation methods.
+fn ensure_states_plugin_is_installed(app: &SubApp) {
```
Comment (benfrankel) [inline crates/bevy_state/src/app.rs:61]: Nit: Technically this doesn't _ensure_ that the plugin is installed, since the plugin will still not be installed after calling this function. I'd give this a more accurate name like `warn_if_no_states_plugin`.

**Review by benfrankel — CHANGES_REQUESTED** [review]

File: crates/bevy_state/src/app.rs (hunk 1 above)
Comment (MiniaczQ) [reply crates/bevy_state/src/app.rs:61]: fair

**Review by benfrankel — APPROVED** [review]
