### PR TITLE
change 'collapse_type_name' to retain enum types

### LINKED ISSUE #9509: System set names are too aggressively stripped when reporting system order ambiguities
## Bevy version

0.11

## What you did

Enable [system 

## What went wrong

```rust
2023-08-20T17:23:10.908705Z  WARN bevy_ecs::schedule::schedule: 1 pairs of systems with conflicting data access have indeterminate execution order. Consider adding `before`, `after`, or `ambiguous_with` relationships between these:
 -- update_action_state<PlayerAction> (in set Update) and ui_focus_system (in set Focus)
    conflict on: ["bevy_ui::focus::Interaction"]
 ```
 
## Additional information

The set names should be [`InputManagerSystem::Update`](https://docs.rs/leafwing-input-manager/0.10.0/leafwing_input_manager/plugin/enum.InputManagerSystem.html) and [`UiSystem::Focus`](https://docs.rs/bevy/latest/bevy/ui/enum.UiSystem.html) instead.

These are much clearer.

Note that this bug is due to `get_short_name` not differentiating between the `::` used for enum variants correctly. The enum type should be retained, while other module path info is stripped.

### PR DESCRIPTION
**Pull request by EmiOnGit**
# Objective

Fixes #9509 

## Solution
We use the assumption, that enum types are uppercase in contrast to module names.
[`collapse_type_name`](crates/bevy_util/src/short_names) is now retaining the second last segment, if it starts with a uppercase character.

### CODE REVIEW

**Review by alice-i-cecile — APPROVED** [review]
Nice fix and great tests. Thanks!

File: crates/bevy_utils/src/short_names.rs [hunk 1]
```diff
@@ -59,7 +59,20 @@ pub fn get_short_name(full_name: &str) -> String {
...
-    string.split("::").last().unwrap()
+    // Enums types are retained.
+    // As heuristic, we assume the enum type to be uppercase.
+    let mut segments = string.rsplit("::");
+    let (last, second_last): (&str, Option<&str>) = (segments.next().unwrap(), segments.next());
+    let Some(second_last) = second_last else {
+        return last;
+    };
+
+    if second_last.starts_with(|c: char| c.is_uppercase()) {
```
Comment (nicopap) [inline crates/bevy_utils/src/short_names.rs:70]: This is more in line with common rust usage.

```suggestion
    if second_last.starts_with(char::is_uppercase) {
```

**Review by nicopap — APPROVED** [review]
lgtm. Just a nit.
