### PR TITLE
Poll system information in separate tasks

### LINKED ISSUE #12848: SystemInformationDiagnosticsPlugin is slow due to `sysinfo` crate
## Bevy version

0.13.1

## Relevant system information

- OS: Windows 11
- Processor: AMD Ryzen 9 7950X3D 16-Core Processor

## What you did

Add the `bevy::diagnostic::SystemInformationDiagnosticsPlugin` plugin.

## What went wrong

The `diagnostic_system` of the `SystemInformationDiagnosticsPlugin` takes around 4ms on my system, which makes it unsuitable to use while measuring performance.

## Additional information

Noticed this, as I used this with `iyes_perf_ui` and could not get more than 200FPS.

### PR DESCRIPTION
**Pull request by Brezak**
# Objective

Reading system information severely slows down the update loop.
Fixes #12848.

## Solution

Read system info in a separate thread.

## Testing

- Open the scene 3d example
-  Add `FrameTimeDiagnosticsPlugin`, `SystemInformationDiagnosticsPlugin` and `LogDiagnosticsPlugin` to the app.
- Add this system to the update schedule to disable Vsync on the main window
```rust
fn change_window_mode(mut windows: Query<&mut Window, Added<Window>>) {
    for mut window in &mut windows {
        window.present_mode = PresentMode::AutoNoVsync;
    }
}
```
- Read the fps values in the console before and after this PR.

On my PC I went from around 50 fps to around 1150 fps.

---

### Changed

- The `SystemInformationDiagnosticsPlugin` now reads system data separate of the update cycle.

### Added 

-  The `EXPECTED_SYSTEM_INFORMATION_INTERVAL` constant which defines how often we read system diagnostic data.

### CODE REVIEW

**Review by IceSentry — COMMENTED** [review]
I don't think this should be implemented with a thread only used for that. I feel like it should use bevy's task system and create a new task based on the polling rate.

**Comment by IceSentry** [comment]
The sleep also doesn't take into account the time it took to get the info so it will sleep for longer than necessary. Which is another reason why using a thread + sleep isn't great.

**Comment by Brezak** [comment]
> I don't think this should be implemented with a thread only used for that. I feel like it should use bevy's task system and create a new task based on the polling rate.

Do we have a equivalent of smol's [`unblock`](https://docs.rs/smol/latest/smol/fn.unblock.html) or tokio's [`spawn_blocking`](https://docs.rs/tokio/latest/tokio/task/fn.spawn_blocking.html)? sysinfo doesn't support async and from my understanding spawning a blocking task could block the whole task pool.

**Comment by IceSentry** [comment]
Here's more or less what I had in mind. I tested it and it works like I would expect.

```rust
 pub(crate) fn diagnostic_system(
        mut diagnostics: Diagnostics,
        mut sysinfo: Local<Option<Arc<Mutex<System>>>>,
        mut tasks: Local<Vec<Task<SysinfoRefreshData>>>,
        mut last_refresh: Local<Option<Instant>>,
    ) {
        if sysinfo.is_none() {
            *sysinfo = Some(Arc::new(Mutex::new(System::new_with_specifics(
                RefreshKind::new()
                    .with_cpu(CpuRefreshKind::new().with_cpu_usage())
                    .with_memory(MemoryRefreshKind::everything()),
            ))));
        }
        let Some(sys) = sysinfo.as_mut() else {
            error!("sysinfo should have been created at this point");
            return;
        };
        if last_refresh.is_none() {
            *last_refresh = Some(Instant::now());
        }
        let Some(last_refresh) = last_refresh.as_mut() else {
            error!("last_refresh should have been created at this point");
            return;
        };

        let thread_pool = AsyncComputeTaskPool::get();

        // Only queue a new system refresh task when necessary
        // Queueing earlier than that will not give new data
        if last_refresh.elapsed() > sysinfo::MINIMUM_CPU_UPDATE_INTERVAL {
            let sys = sys.clone();
            let task = thread_pool.spawn(async move {
                let mut sys = sys.lock().unwrap();

                sys.refresh_cpu_specifics(CpuRefreshKind::new().with_cpu_usage());
                sys.refresh_memory();
                let current_cpu_usage = sys.global_cpu_info().cpu_usage();
                // `memory()` fns return a value in bytes
                let total_mem = sys.total_memory() as f64 / BYTES_TO_GIB;
                let used_mem = sys.used_memory() as f64 / BYTES_TO_GIB;
                let current_used_mem = used_mem / total_mem * 100.0;

                SysinfoRefreshData {
                    current_cpu_usage,
                    current_used_mem,
                }
            });
            tasks.push(task);
            *last_refresh = Instant::now();
        }

        let mut tasks_completed = vec![];
        for (i, mut task) in tasks.iter_mut().enumerate() {
            let Some(refresh_data) = block_on(future::poll_once(&mut task)) else {
                continue;
            };
            tasks_completed.push(i);

            diagnostics.add_measurement(&SystemInformationDiagnosticsPlugin::CPU_USAGE, || {
                refresh_data.current_cpu_usage as f64
            });
            diagnostics.add_measurement(&SystemInformationDiagnosticsPlugin::MEM_USAGE, || {
                refresh_data.current_used_mem
            });
        }
        for task_completed in tasks_completed {
            drop(tasks.remove(task_completed));
        }
    }
```

There might be a better way to do this without `Arc<Mutex<System>> `and all those `Local`, but that's the rough outline of what I meant. 

The idea is to queue a small task every time you want to refresh the system data. I don't _think_ it will block the main thread using this approach, but I'm not entirely sure. At least it doesn't poll every frame though. It might be better to do the polling and task clean up in a separate system too, not sure.

**Comment by Brezak** [comment]
I've tough about it a don't think launching multiple tasks will work. If a task gets stuck reading data for at least the time it takes to generate one + margin (e.g. the system took to long to get the data) we're likely to violate the minimum cpu update interval.

```
1. Task0 is spawned and takes a while to finish

Task0 ~~~

2. Task1 gets spawned but Task0 isn't finished

Task0 ~~~ Task1

3. Task0 finishes a while after Task1 was spawned.

Task0 ~~~ Task1 ~|
                             ^
     Task0 has finished, Task1 has started immediately after

4. worst case Task1 finishes before another task can spawn

Task0 ~~~ Task1 ~|~| Task2 
                             ^ |
      Task0 has finished, Task1 has started
                                 |
                                ^
                       Task1 has finished
                       
5. Task2 gets to start immediately

Task0 ~~~ Task1 ~|~| Task2 
                             ^ |    |
      Task0 has finished, Task1 has started
                              |  |    |
                              | ^   |
                       Task1 has finished
                              |      |
                              |     ^
                        Task2 has started
                              |      |
                             ^~~^
            The time it took Task2 to start after Task1 started is less than MINIMUM_CPU_UPDATE_INTERVAL.
            It's output will be garbage.
            
```

**Comment by IceSentry** [comment]
The minimum time interval is 100ms on linux and 200ms on everything else. I doubt it would ever take more than that to get the cpu info, but if we want to protect against it we could add a timestamp to the task and check that it hasn't been longer than the minimum and drop it if it has. We could also just hardcode it to 200ms to stay on the safer side.

File: crates/bevy_diagnostic/src/system_information_diagnostics_plugin.rs [hunk 1]
```diff
@@ -46,6 +47,13 @@ pub struct SystemInfo {
     pub memory: String,
 }
 
+/// The expected interval at which system information will be queried and generated.
+///
+/// The system diagnostic plugin doesn't work in all situations. In those situations this value will
+/// bet set to None.
+pub const EXPECTED_SYSTEM_INFORMATION_INTERVAL: Option<Duration> =
+    internal::EXPECTED_SYSTEM_INFORMATION_INTERVAL;
```
Comment (BD103) [inline crates/bevy_diagnostic/src/system_information_diagnostics_plugin.rs:55]: Could this be `pub use` instead?

```rust
pub use self::internal::EXPECTED_SYSTEM_INFORMATION_INTERVAL;
```

**Comment by IceSentry** [comment]
Another solution could be to not spawn any task and just do it at a fixed interval in a regular system. The system will run in parallel so it won't block any work, the only issue is if it takes longer than the duration of a frame to sample the cpu. We could detect that and start logging errors if it happen or maybe even stop sampling the cpu if it does it multiple times

**Comment by IceSentry** [comment]
Okay, nevermind, it takes 5ms on my machine to refresh the cpu data so we probably shouldn't do that in a system.

File: crates/bevy_diagnostic/src/system_information_diagnostics_plugin.rs [hunk 2]
```diff
@@ -46,6 +45,12 @@ pub struct SystemInfo {
     pub memory: String,
 }
 
+/// The expected interval at which system information will be queried and generated.
+///
+/// The system diagnostic plugin doesn't work in all situations. In those situations this value will
+/// bet set to None.
+pub use internal::EXPECTED_SYSTEM_INFORMATION_INTERVAL;
```
Comment (IceSentry) [inline crates/bevy_diagnostic/src/system_information_diagnostics_plugin.rs:52]: Why does this need to be exposed?

File: crates/bevy_diagnostic/src/system_information_diagnostics_plugin.rs [hunk 3]
```diff
@@ -67,41 +80,94 @@ pub mod internal {
...
+        let last_refresh = last_refresh.get_or_insert_with(Instant::now);
+
+        let thread_pool = AsyncComputeTaskPool::get();
+
+        // Only queue a new system refresh task when necessary
+        // Queueing earlier than that will not give new data
+        if last_refresh.elapsed() > sysinfo::MINIMUM_CPU_UPDATE_INTERVAL
+            // These tasks don't yield and will take up all of the task pool's
+            // threads if we don't limit their amount.
+            && tasks.tasks.len() * 2 < available_parallelism()
```
Comment (IceSentry) [inline crates/bevy_diagnostic/src/system_information_diagnostics_plugin.rs:134]: I assume this is done to avoid the issue you mentioned, but I'm not sure I understand what it's doing.

File: crates/bevy_diagnostic/src/system_information_diagnostics_plugin.rs [hunk 4]
```diff
@@ -67,41 +80,94 @@ pub mod internal {
...
+                    current_used_mem,
+                }
+            });
+            tasks.tasks.push(task);
+            *last_refresh = Instant::now();
+        }
+    }
+
+    fn read_diagnostic_tasks(mut diagnostics: Diagnostics, mut tasks: ResMut<SysinfoTasks>) {
+        tasks.tasks.retain_mut(|task| {
```
Comment (IceSentry) [inline crates/bevy_diagnostic/src/system_information_diagnostics_plugin.rs:159]: `retain_mut` is way better than the weird thing I did in my snippet 😅I didn't remember what that api was called.

File: crates/bevy_diagnostic/src/system_information_diagnostics_plugin.rs (hunk 3 above)
Comment (IceSentry) [reply crates/bevy_diagnostic/src/system_information_diagnostics_plugin.rs:134]: Nevermind, I get it now, it just took a while to process for some reason 😅

**Review by IceSentry — APPROVED** [review]
Not sure about the exposed constant, but everything else LGTM

File: crates/bevy_diagnostic/src/system_information_diagnostics_plugin.rs (hunk 2 above)
Comment (Brezak) [reply crates/bevy_diagnostic/src/system_information_diagnostics_plugin.rs:52]: It's mostly a way to expose the fact that system diagnostics will be generated somewhat slowly.

Comment (IceSentry) [reply crates/bevy_diagnostic/src/system_information_diagnostics_plugin.rs:52]: Oh, in that case I'd prefer if that was documented directly on the plugin docs so it's a bit more visible. I mean, this can stay here, but it should also be documented on the plugin

Comment (alice-i-cecile) [inline crates/bevy_diagnostic/src/system_information_diagnostics_plugin.rs:52]:
```suggestion
use internal::EXPECTED_SYSTEM_INFORMATION_INTERVAL;
```

File: crates/bevy_diagnostic/src/system_information_diagnostics_plugin.rs [hunk 5]
```diff
@@ -145,14 +211,20 @@ pub mod internal {
...
+        app.add_systems(Startup, setup_system);
     }
 
-    pub(crate) fn diagnostic_system() {
-        // no-op
+    fn setup_system() {
+        bevy_utils::tracing::warn!("This platform and/or configuration is not supported!");
     }
 
+    pub const EXPECTED_SYSTEM_INFORMATION_INTERVAL: Option<Duration> = None;
```
Comment (alice-i-cecile) [inline crates/bevy_diagnostic/src/system_information_diagnostics_plugin.rs:226]:
```suggestion
    const EXPECTED_SYSTEM_INFORMATION_INTERVAL: Option<Duration> = None;
```

**Review by alice-i-cecile — CHANGES_REQUESTED** [review]
Agreed on the exposed constant: remove it and optionally try and document this more in the plugin docs. Once that's done this LGTM and I'll merge.

**Review by alice-i-cecile — APPROVED** [review]

**Comment by alice-i-cecile** [comment]
Once CI is green I'll merge this :)

File: crates/bevy_diagnostic/src/system_information_diagnostics_plugin.rs [hunk 6]
```diff
@@ -4,6 +4,9 @@ use bevy_ecs::system::Resource;
 
 /// Adds a System Information Diagnostic, specifically `cpu_usage` (in %) and `mem_usage` (in %)
 ///
+/// Note that gather system information is a time intensive task and therefore can't be done on every frame.
```
Comment (IceSentry) [inline crates/bevy_diagnostic/src/system_information_diagnostics_plugin.rs:7]:
```suggestion
/// Note that gathering system information is a time intensive task and therefore can't be done on every frame.
```
