### PR TITLE
don't overflow when relations are empty

### LINKED ISSUE #18890: `EntityWorldMut::insert_children` panics on index 0
## Bevy version
0.16.0-rc.5

## Relevant system information

- cargo 1.86.0 (adf9b6ad1 2025-02-28) and cargo 1.88.0-nightly (0e93c5bf6 2025-04-05)
- Ubuntu 24.04.2 LTS

## What you did

```rust
use bevy::prelude::*;

fn main() {
    App::new()
        .add_plugins(DefaultPlugins)
        .add_systems(
            Startup,
            (
                |world: &mut World| {
                    let child = world.spawn_empty().id();
                    let mut parent = world.spawn_empty();
                    parent.insert_children(0, &[child]);
                    println!("{:?}", parent.get::<Children>().unwrap());
                },
            ),
        )
        .run();
}
```

output
```
thread 'main' panicked at /home/avi/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/bevy_ecs-0.16.0-rc.5/src/relationship/relationship_source_collection.rs:216:35:
attempt to subtract with overflow
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Encountered a panic in system `test::main::{{closure}}`!
Encountered a panic in system `bevy_app::main_schedule::Main::run_main`!
double free or corruption (fasttop)
Aborted (core dumped)
```

## Additional information
works on 0.15.3 on both stable and nightly

### PR DESCRIPTION
**Pull request by mockersf**
# Objective

- Fixes #18890 

## Solution

- Don't overflow when substracting, bound at 0

## Testing

- Reproducer from the issue now works

### CODE REVIEW

**Review by databasedav — APPROVED** [review]

File: crates/bevy_ecs/src/relationship/relationship_source_collection.rs [hunk 1]
```diff
@@ -213,15 +213,15 @@ impl OrderedRelationshipSourceCollection for Vec<Entity> {
...
         if let Some(entity) = self.pop() {
-            let index = index.min(self.len() - 1);
+            let index = index.min(self.len().saturating_sub(1));
             self.insert(index, entity);
         }
     }
 
     fn place(&mut self, entity: Entity, index: usize) {
         if let Some(current) = <[Entity]>::iter(self).position(|e| *e == entity) {
             // The len is at least 1, so the subtraction is safe.
```
Comment (mgi388) [inline crates/bevy_ecs/src/relationship/relationship_source_collection.rs:223]: This comment suggests the `- 1` should always be safe, so does it indicate something else wrong?

Noting that I approve of the change to `saturating_sub` generally.

Comment (janhohenheim) [reply crates/bevy_ecs/src/relationship/relationship_source_collection.rs:223]: This line here IMO cannot fail, as the `position` call cannot return `Some` if there are no items to filter. 
The bugfix is thus in the other line that was changed.

**Review by janhohenheim — APPROVED** [review]
Makes sense!

File: crates/bevy_ecs/src/relationship/relationship_source_collection.rs (hunk 1 above)
Comment (mgi388) [reply crates/bevy_ecs/src/relationship/relationship_source_collection.rs:223]: Ah ok that makes sense. This line was just changed while he was here.
