### PR TITLE
Fix `ambiguous_with` breaking run conditions

### LINKED ISSUE #9114: `ambiguous_with` breaks run conditions
## Bevy version

0.11

## What you did

I migrated my project to bevy 0.11 and noticed a system in Last started misbehaving despite having the configuration for the set it was in in all schedules.

This is the most simplified version of my code that still produces the bug
```rust
#[derive(States, Default, Clone, PartialEq, Eq, Debug, Hash)]
pub enum ConnectionState {
    #[default]
    Menu,
    Connecting,
    Connected,
}

#[derive(SystemSet, Clone, PartialEq, Eq, Debug, Hash)]
pub enum ConnectionSet {
    Menu,
    Connecting,
    Connected,
}

fn main() {
    fn configure_connecting_sets(schedule: &mut Schedule) {
        schedule.configure_set(ConnectionSet::Connected.run_if(in_state(ConnectionState::Connected)));
    }

    let mut app = App::new();

    app.add_state::<ConnectionState>();

    for label in app.world.resource::<bevy::app::MainScheduleOrder>().labels.to_vec() {
        println!("{:?}", label);
        app.edit_schedule(label.dyn_clone(), configure_connecting_sets);
    }

    app.
        .add_plugins(MinimalPlugins.build().disable::<bevy::app::ScheduleRunnerPlugin>())
        .add_plugins(bevy::asset::AssetPlugin::default())
        .add_plugins(bevy::a11y::AccessibilityPlugin)
        .add_plugins(bevy::input::InputPlugin::default())
        .add_plugins(bevy::window::WindowPlugin::default())
        .add_plugins(bevy::winit::WinitPlugin::default())

        .add_systems(Update, (|| {println!("This should not run in Update");}).in_set(ConnectionSet::Connected))
        .add_systems(Last, (|| {println!("This should not run in Last");}).in_set(ConnectionSet::Connected))

        .run();
}
```

## What went wrong

The above code should output:
```
First
PreUpdate
StateTransition
RunFixedUpdateLoop
Update
PostUpdate
Last
```
and then stop.

Instead, if the `WinitPlugin` is enabled it also outputs this every frame:
```
This should not run in Last
````

Since the runcondition of the set that system is in is not met, it should not be printing this. Especially considering it only happens in Last while Update works as expected. If the `WinitPlugin` is disabled and the `ScheduleRunnerPlugin` is turned back on this problem is gone.

### PR DESCRIPTION
**Pull request by geieredgar**
# Objective

- Fixes #9114

## Solution

Inside `ScheduleGraph::build_schedule()` the variable `node_count = self.systems.len() + self.system_sets.len()` is used to calculate the indices for the `reachable` bitset derived from `self.hierarchy.graph`. However, the number of nodes inside `self.hierarchy.graph` does not always correspond to `self.systems.len() + self.system_sets.len()` when `ambiguous_with` is used, because an ambiguous set is added to `system_sets` (because we need an `NodeId` for the ambiguity graph) without adding a node to `self.hierarchy`. 

In this PR, we rename `node_count` to the more descriptive name `hg_node_count` and set it to `self.hierarchy.graph.node_count()`.

### CODE REVIEW

**Review by maniwani — APPROVED** [review]
Nice catch! Your assessment seems correct to me. Even though it's very subtle, I'm a little surprised this bug went unnoticed until now. Thank you for solving this so quickly.

**Review by JoJoJet — APPROVED** [review]

File: crates/bevy_ecs/src/schedule/schedule.rs [hunk 1]
```diff
@@ -1570,3 +1570,29 @@ impl ScheduleBuildSettings {
...
+
+#[cfg(test)]
+mod tests {
+    use crate::{
+        self as bevy_ecs,
+        schedule::{IntoSystemConfigs, IntoSystemSetConfig, Schedule, SystemSet},
+        world::World,
+    };
+
+    #[test]
```
Comment (james7132) [inline crates/bevy_ecs/src/schedule/schedule.rs:1582]:
```suggestion
    // regression test for https://github.com/bevyengine/bevy/issues/9114
    #[test]
```

**Review by james7132 — APPROVED** [review]
