### PR TITLE
Fix rust beta lints

### LINKED ISSUE #14517: Main branch fails to compile on Rust beta.
## Weekly CI run has failed.
[The offending run.](https://github.com/bevyengine/bevy/actions/runs/10143837232)

### PR DESCRIPTION
**Pull request by BD103**
# Objective

- Fixes #14517.

## Solution

- Replace two instances of `map()` with `inspect()`.
- `#[allow(dead_code)]` on `Bundle` derive macro tests.

## Testing

You need to install the beta toolchain, since these lints are not stable yet.

```bash
cargo +beta clippy --workspace
cargo +beta test --workspace
```

### CODE REVIEW

File: crates/bevy_ecs/src/lib.rs [hunk 1]
```diff
@@ -1749,16 +1749,4 @@ mod tests {
     #[allow(dead_code)]
     #[derive(Component)]
     struct ComponentB(u32);
-
-    #[derive(Bundle)]
```
Comment (alice-i-cecile) [inline crates/bevy_ecs/src/lib.rs:1753]: These should be marked as allow dead code instead like their siblings IMO. These are compilation tests primarily.

**Review by alice-i-cecile — CHANGES_REQUESTED** [review]

File: crates/bevy_ecs/src/lib.rs (hunk 1 above)
Comment (BD103) [reply crates/bevy_ecs/src/lib.rs:1753]: Sounds good! Added back :)

**Review by tychedelia — APPROVED** [review]

**Review by richchurcher — APPROVED** [review]
Checked (Arch 6.10.0, nightly 1.82.0) and passing.
