### PR TITLE
check root node for animations

### LINKED ISSUE #8357: AnimationPlayer can play unrelated AnimationClips
bevy version: main commit dff071c2a

## What you did

I tried to play a `Handle<AnimationClip>` which animates X (using entity path) on a `AnimationPlayer` component of entity Y, and the animation played.

## What went wrong

The animation played, when the given animation is not supposed to work with this entity. the issue lies in

https://github.com/bevyengine/bevy/blob/d623731e2c0f4c5ce4213a30685e73e190db60b4/crates/bevy_animation/src/lib.rs#L273-L284

The name of the root entity is entirely dismissed.

I have three different animated meshes, each with their own `AnimationPlayer` component.
I have a collection of `Handle<AnimationClip>`, each `AnimationClip` is relevant to a single of three meshes (`AnimationClip` even contains a path to the animated entities).
I can call `AnimationPlayer::play` on component of entity 1, with an `Handle<AnimationClip>` containing an animation for entity 2.
This is wrong, it should be impossible to do that.

## Ideal implementation

It is possible to check for compatibility in `find_bone`, return `None` and print a warning, but ideally, the `AnimationPlayer::play` method should be able to fail if given the wrong `Handle<AnimationClip>`, and users should be given a way to test for animation compatibility. This way, it's actually possible to do something about it.

## Additional information

This was found it because using the wrong animation on the wrong entity causes a panic with morph targets.

### PR DESCRIPTION
**Pull request by robtfm**
# Objective

fixes #8357 

gltf animations can affect multiple "root" nodes (i.e. top level nodes within a gltf scene). 

the current loader adds an AnimationPlayer to each root node which is affected by any animation. when a clip which affects multiple root nodes is played on a root node player, the root node name is not checked, leading to potentially incorrect weights being applied.
also, the `AnimationClip::compatible_with` method will never return true for those clips, as it checks that all paths start with the root node name - not all paths start with the same name so it can't return true.

## Solution

- check the first path node name matches the given root
- change compatible_with to return true if `any` match is found

a better alternative would probably be to attach the player to the scene root instead of the first child, and then walk the full path from there. this would be breaking (and would stop multiple animations that *don't* overlap from being played concurrently), but i'm happy to modify to that if it's preferred.

### CODE REVIEW

**Comment by nicopap** [comment]
Could you add the "Fixes #8357"?

File: crates/bevy_animation/src/lib.rs [hunk 1]
```diff
@@ -295,8 +295,18 @@ fn entity_from_path(
...
+
+    let mut parts = path.parts.iter().enumerate();
+
+    // check the first name is the root node which we already have
+    let Some((_, root_name)) = parts.next() else {
+        return None;
+    };
+    if names.get(current_entity) != Ok(root_name) {
+        return None;
+    }
```
Comment (nicopap) [inline crates/bevy_animation/src/lib.rs:307]: Could we conceivably log a `warn!` if this fails? It's kinda nasty to set an animation and not see anything happening and not having a clue why.

**Review by nicopap — APPROVED** [review]

File: crates/bevy_animation/src/lib.rs [hunk 2]
```diff
@@ -601,7 +601,10 @@ fn apply_animation(
         }
 
         if !any_path_found {
-            warn!("Animation player on {:?} did not match any entity paths.", root);
+            warn!(
+                "Animation player on {:?} did not match any entity paths.",
+                root
+            );
```
Comment (nicopap) [inline crates/bevy_animation/src/lib.rs:607]:
```suggestion
            warn!("Animation player on {root:?} did not match any entity paths.");
```

File: crates/bevy_animation/src/lib.rs (hunk 1 above)
Comment (mockersf) [inline crates/bevy_animation/src/lib.rs:307]:
```suggestion
    if names.get(current_entity).ok() != parts.next().map(|(_, part)| part) {
        return None;
    };
```
Just a style nit, but I would prefer this

**Review by mockersf — APPROVED** [review]

File: crates/bevy_animation/src/lib.rs (hunk 1 above)
Comment (robtfm) [reply crates/bevy_animation/src/lib.rs:307]: it's slightly different semantically - this would pass if parts is empty and the node has no name. neither of those things can happen via the gltf loader but could happen for clips/players constructed another way.

could maybe go with `if names.get(current_entity) != Ok(parts.next()?.1) {` ... i'm not sure it's nicer.
