### PR TITLE
Detect cubemap for dds textures

### LINKED ISSUE #10049: DDS loading does not recognize cubemap imports
##  Bevy and version information:
Tested on both recent bevy master and on 0.11.3

`AdapterInfo { name: "NVIDIA GeForce RTX 4080", vendor: 4318, device: 9988, device_type: DiscreteGpu, driver: "NVIDIA", driver_info: "537.13", backend: Vulkan }`

## What you did

I tried to use DDS cubemap textures for skyboxes and envmap textures.

## What went wrong
```
2023-10-08T18:55:09.680963Z ERROR wgpu::backend::direct: Handling wgpu errors as fatal by default    
thread 'Compute Task Pool (7)' panicked at 'wgpu error: Validation Error

Caused by:
    In Device::create_bind_group
      note: label = `skybox_bind_group`
    Texture binding 0 expects dimension = Cube, but given a view with dimension = D2

', ...\wgpu-0.16.3\src\backend\direct.rs:3019:5
```
## Additional information
I have observed this issue with files output by <https://github.com/dariomanesku/cmftStudio> and ones output by <https://developer.nvidia.com/nvidia-texture-tools-exporter>. Using the Nvidia tool I've resaved my DDS file from cmft as a KTX2, and bevy loads that without issue. I then resaved it as .dds using the Nvidia tool, with otherwise the same settings, including set to export as cubemap. The resulting DDS file still has the error.

I'm attaching a zip that includes that working KTX2 skybox and the Nvidia-produced DDS saved from it.

[skyboxes.zip](https://github.com/bevyengine/bevy/files/12841506/skyboxes.zip)

### PR DESCRIPTION
**Pull request by Kanabenki**
# Objective

- Closes #10049.
- Detect DDS texture containing a cubemap or a cubemap array.

## Solution

- When loading a dds texture, the header capabilities are checked for the cubemap flag. An error is returned if not all faces are provided.

---

### Added

- Added a new texture error `TextureError::IncompleteCubemap`, used for dds cubemap textures containing less than 6 faces, as that is not supported on modern graphics APIs.

### Fixed

- DDS cubemaps are now loaded as cubemaps instead of 2D textures.

## Migration Guide

If you are matching on a `TextureError`, you will need to add a new branch to handle `TextureError::IncompleteCubemap`.

### CODE REVIEW

**Comment by alice-i-cecile** [comment]
Technically breaking as a variant was added to a public enum.

**Review by alice-i-cecile — APPROVED** [review]

File: crates/bevy_render/src/texture/dds.rs [hunk 1]
```diff
@@ -18,14 +20,29 @@ pub fn dds_buffer_to_image(
...
     let mut image = Image::default();
+    let is_cubemap = dds.header.caps2.contains(Caps2::CUBEMAP);
+    let mut depth_or_array_layers = if dds.get_num_array_layers() > 1 {
+        dds.get_num_array_layers()
+    } else {
+        dds.get_depth()
+    };
+    if is_cubemap {
+        if !dds.header.caps2.contains(
+            Caps2::CUBEMAP_NEGATIVEX
```
Comment (alice-i-cecile) [inline crates/bevy_render/src/texture/dds.rs:31]: Is this the right logic? It looks like this will return ture if *any* of these faces are found, but we want to return true only if *all* of the faces are found.

Comment (Kanabenki) [reply crates/bevy_render/src/texture/dds.rs:31]: I think that's correct, this create a `Caps2` bitflag containing all directions (with each being a distinct bit), so if one is missing it will return false. Just checked to be sure:

```rust
    let all = Caps2::CUBEMAP_NEGATIVEX
        | Caps2::CUBEMAP_NEGATIVEY
        | Caps2::CUBEMAP_NEGATIVEZ
        | Caps2::CUBEMAP_POSITIVEX
        | Caps2::CUBEMAP_POSITIVEY
        | Caps2::CUBEMAP_POSITIVEZ;
    dbg!(Caps2::CUBEMAP_NEGATIVEX.contains(all));
    dbg!(all.contains(all));
```
returns `false` then `true`, as expected.

Comment (Kanabenki) [reply crates/bevy_render/src/texture/dds.rs:31]: Additionally, there should be a `CUBEMAP_ALLFACES` flag that OR all directions according to [this DDS doc](https://learn.microsoft.com/en-us/windows/win32/direct3ddds/dds-header), I'll see if I can add it to `ddsfile`.

**Review by superdump — APPROVED** [review]
