### PR TITLE
fix panic when moving child

### LINKED ISSUE #8337: `update_old_parent` Doesn't check to see if parent actually exists.
## Bevy version
0.10.1 

## What you did
I have a setup like this:
```
- parent 1
  - child 1
```

## What went wrong
I have a change like this:
```
1. Spawn parent 2
2. despawn parent 1
3. add child 1 as a child of parent 2
```

And I get this error:
`thread 'main' panicked at 'Entity 43v0 does not exist'`

## Additional information

It looks like we just need to check if the parent exists.

### PR DESCRIPTION
**Pull request by B-Reif**
# Objective
When changing an Entity's `Parent` to a new one from an old `Parent` that doesn't exist, Bevy panics. Fixes #8337.

## Solution

Use `get_entity_mut` instead of `entity_mut` in `remove_from_children`.

### CODE REVIEW

**Review by devil-ira — APPROVED** [review]

File: crates/bevy_hierarchy/src/child_builder.rs [hunk 1]
```diff
@@ -41,11 +41,12 @@ fn update_parent(world: &mut World, child: Entity, new_parent: Entity) -> Option
 ///
 /// Removes the [`Children`] component from the parent if it's empty.
 fn remove_from_children(world: &mut World, parent: Entity, child: Entity) {
-    let mut parent = world.entity_mut(parent);
-    if let Some(mut children) = parent.get_mut::<Children>() {
-        children.0.retain(|x| *x != child);
-        if children.is_empty() {
-            parent.remove::<Children>();
+    if let Some(mut parent) = world.get_entity_mut(parent) {
+        if let Some(mut children) = parent.get_mut::<Children>() {
```
Comment (james7132) [inline crates/bevy_hierarchy/src/child_builder.rs:45]: Might be a good spot to use `let ... else` to avoid rightward drift.

**Comment by JoJoJet** [comment]
Can you add a regression test? Something based on https://github.com/bevyengine/bevy/issues/8337#issuecomment-1501162706 would be good.

**Comment by B-Reif** [comment]
> Can you add a regression test? Something based on [#8337 (comment)](https://github.com/bevyengine/bevy/issues/8337#issuecomment-1501162706) would be good.

Sure thing.

**Review by JoJoJet — APPROVED** [review]

File: crates/bevy_hierarchy/src/child_builder.rs [hunk 2]
```diff
@@ -653,6 +656,22 @@ mod tests {
         );
     }
 
+    #[test]
```
Comment (james7132) [inline crates/bevy_hierarchy/src/child_builder.rs:659]:
```suggestion
    // regression test for https://github.com/bevyengine/bevy/pull/8346
    #[test]
```

**Review by james7132 — APPROVED** [review]
