### PR TITLE
#14143 - fix bevy_ui padding

### LINKED ISSUE #14143: Padding in `Style` no longer works in 0.14
## Bevy version

0.14

## What went wrong
I upgraded bevy to 0.14, after migration and launching the game I found out that ui that used `Padding` in style no longer works
图片

## Additional information

workaround can be switch padding to margin, but it's better to get it fixed.

### PR DESCRIPTION
**Pull request by Nihilistas**
# Objective

fixes #14143

## Solution

- removed the temporary blocker if statement when setting padding in `Style`
- adjusted the `layout_location` and `layout_size` so they use `layout.padding` which we already get from Taffy

## Testing

- this is the test code I used:
```rust
use bevy::prelude::*;

fn main() {
    App::new()
        .add_plugins(DefaultPlugins)
        .add_systems(Startup, setup)
        .run();
}

fn setup(
    mut commands: Commands,
    asset_server: Res<AssetServer>,
){
    let font = asset_server.load("fonts/FiraSans-Bold.ttf");
    commands.spawn(Camera2dBundle::default());

    commands
        .spawn(NodeBundle {
            style: Style {
                width: Val::Px(200.),
                height: Val::Px(100.),
                align_items: AlignItems::Center,
                justify_content: JustifyContent::Center,
                align_self: AlignSelf::Center,
                justify_self: JustifySelf::Center,
                ..Default::default()
            },
            background_color: BackgroundColor(Color::srgb(0.,1., 1.)),
            ..Default::default()
        })
        .with_children(|builder| {
            builder.spawn((TextBundle::from_section(
                    "Hello World",
                    TextStyle {
                        font,
                        font_size: 32.0,
                        color: Color::WHITE,
                        },
                ).with_style(Style {
                    padding: UiRect::all(Val::Px(10.)),
                    width: Val::Px(100.),
                    height: Val::Px(100.),
                    ..Default::default()
                }).with_background_color(Color::srgb(1.,0., 0.)),
            ));
            // spawn an image bundle
            builder.spawn(ImageBundle {
                style: Style {
                    padding: UiRect::all(Val::Px(10.)),
                    width: Val::Px(100.),
                    height: Val::Px(100.),
                    ..Default::default()
                },
                image: asset_server.load("square.png").into(),
                ..Default::default()
            });
        });
}
```

- I tested 5 cases: 10px padding from all sides, and 10px padding from left, right, bottom, and top separately

- **For reviewers**: please check more cases or try to run it on some more complicated real-world UI

## Showcase

Screenshot 2024-08-16 at 09 28 04
Screenshot 2024-08-16 at 09 28 47
Screenshot 2024-08-16 at 09 45 16
Screenshot 2024-08-16 at 09 45 36
Screenshot 2024-08-16 at 09 45 58

### CODE REVIEW

File: crates/bevy_ui/src/layout/convert.rs [hunk 1]
```diff
@@ -93,18 +93,12 @@ pub fn from_style(
...
-            taffy::Rect::zero()
-        } else {
-            style
-                .padding
-                .map_to_taffy_rect(|m| m.into_length_percentage(context))
-        },
+        padding: style
+            .padding
+            .map_to_taffy_rect(|m| m.into_length_percentage(context)),
         // Ignore border for leaf nodes as it isn't implemented in the rendering engine.
```
Comment (alice-i-cecile) [inline crates/bevy_ui/src/layout/convert.rs:99]: For follow-up: I don't think this is true any more.

**Review by alice-i-cecile — APPROVED** [review]

**Review by nicoburns — APPROVED** [review]
Seems good. I think it should be pretty easy to make the borders work too. IIRC there is a check somewhere in the border rendering code that filters put leaf nodes that could be removed.

**Comment by Nihilistas** [comment]
> Seems good. I think it should be pretty easy to make the borders work too. IIRC there is a check somewhere in the border rendering code that filters put leaf nodes that could be removed.

@nicoburns 
I never noticed what was wrong with them in the first place. Do you have an already-existing issue link I could refer to for a separate PR later on if I end up fixing it?

**Comment by alice-i-cecile** [comment]
There's no open issue for this as far as I'm aware, but I would love to see that in follow-up.
