### PR TITLE
Fix issue with `Option` serialization

### LINKED ISSUE #10499: Nested structs cause DynamicScene to fail to deserialize
## Bevy version

`0.12.0`

## What you did

```rust
use bevy::{
    prelude::*,
    scene::{
        serde::{
            SceneDeserializer,
            SceneSerializer,
        },
        DynamicEntity,
    },
};
use serde::{
    de::DeserializeSeed,
    Serialize,
};

#[derive(Component, Default, Reflect)]
#[reflect(Component)]
struct Parent {
    value: Option<Child>,
}

#[derive(Reflect)]
struct Child {
    value: u32,
}

fn main() {
    let mut app = App::new();

    app.add_plugins(MinimalPlugins);

    app.register_type::<Parent>()
        .register_type::<Child>()
        .register_type::<Option<Child>>();

    let world = &mut app.world;

    let registry = world.resource::<AppTypeRegistry>();

    let scene = DynamicScene {
        resources: vec![],
        entities: vec![DynamicEntity {
            entity: Entity::from_raw(0),
            components: vec![Parent { value: None }.clone_value()],
        }],
    };

    let ser = SceneSerializer::new(&scene, registry);

    let mut buf = Vec::new();

    ser.serialize(&mut serde_json::Serializer::new(&mut buf))
        .expect("Failed to serialize");

    let de = SceneDeserializer {
        type_registry: &registry.read(),
    };

    de.deserialize(&mut serde_json::Deserializer::from_slice(&buf))
        .expect("Failed to deserialize");
}
```

## What went wrong

`Failed to deserialize: Error("invalid type: string \"None\", expected reflected struct value")`

## Additional information

This is also triggered by built-in types like `Sprite`.

Related: #6891

### PR DESCRIPTION
**Pull request by hankjordan**
# Objective

- Fix #10499 

## Solution

- Use `.get_represented_type_info()` module path and type ident instead of `.reflect_*` module path and type ident when serializing the `Option` enum

---

## Changelog

- Fix serialization bug
- Add simple test
  - Add `serde_json` dev dependency
  - Add `serde` with `derive` feature dev dependency (wouldn't compile for me without it)

### CODE REVIEW

File: crates/bevy_reflect/src/serde/ser.rs [hunk 1]
```diff
@@ -881,4 +895,43 @@ mod tests {
 
         assert_eq!(expected, bytes);
     }
+
+    #[test]
+    fn should_serialize_dynamic() {
```
Comment (MrGVSV) [inline crates/bevy_reflect/src/serde/ser.rs:900]: Could we rename this to be specific to `Option` since that's a special case in the serializer logic?
```suggestion
    fn should_serialize_dynamic_option() {
```

File: crates/bevy_reflect/Cargo.toml [hunk 2]
```diff
@@ -42,6 +42,8 @@ smol_str = { version = "0.2.0", optional = true }
 ron = "0.8.0"
 rmp-serde = "1.1"
 bincode = "1.3"
+serde_json = "1.0"
+serde = { version = "1", features = ["derive"] }
```
Comment (MrGVSV) [inline crates/bevy_reflect/Cargo.toml:46]: What was the compile error that required this addition?

Comment (hankjordan) [reply crates/bevy_reflect/Cargo.toml:46]:
```
error: cannot find derive macro `Deserialize` in this scope
    --> crates/bevy_reflect/src/serde/de.rs:1165:41
     |
1165 |     #[derive(Reflect, Debug, PartialEq, Deserialize)]
     |                                         ^^^^^^^^^^^
     |
note: `Deserialize` is imported here, but it is only a trait, without a derive macro
    --> crates/bevy_reflect/src/serde/de.rs:1114:9
     |
1114 |     use serde::Deserialize
...
```

Comment (MrGVSV) [reply crates/bevy_reflect/Cargo.toml:46]: Weird. I think CI should catch that if it's truly not compiling. But seeing as this is a dev-dependency, I suppose it doesn't hurt to add it.

**Review by MrGVSV — APPROVED** [review]
Not able to test this against the issue myself but the code looks good! Thanks for adding tests!

File: crates/bevy_reflect/src/serde/ser.rs [hunk 3]
```diff
@@ -317,8 +317,16 @@ impl<'a> Serialize for EnumSerializer<'a> {
 
         match variant_type {
             VariantType::Unit => {
-                if self.enum_value.reflect_module_path() == Some("core::option")
-                    && self.enum_value.reflect_type_ident() == Some("Option")
+                if self
+                    .enum_value
+                    .get_represented_type_info()
```
Comment (MrGVSV) [inline crates/bevy_reflect/src/serde/ser.rs:322]: Actually I just realized that we get the represented type info a few lines up. We should reuse that value to reduce the performance cost of calling `Reflect::get_represented_type_info`.

Comment (alice-i-cecile) [reply crates/bevy_reflect/src/serde/ser.rs:322]: This PR looks good to me other than this suggestion :) Let me know when that's done and I can merge it in.

Comment (hankjordan) [reply crates/bevy_reflect/src/serde/ser.rs]: fixed

File: crates/bevy_reflect/src/serde/ser.rs [hunk 4]
```diff
@@ -317,8 +317,13 @@ impl<'a> Serialize for EnumSerializer<'a> {
 
         match variant_type {
             VariantType::Unit => {
-                if self.enum_value.reflect_module_path() == Some("core::option")
-                    && self.enum_value.reflect_type_ident() == Some("Option")
+                let table = self
+                    .enum_value
+                    .get_represented_type_info()
+                    .map(|i| i.type_path_table());
```
Comment (MrGVSV) [inline crates/bevy_reflect/src/serde/ser.rs:323]: Sorry, what I meant to say was that we fetch the represented type on line 289: https://github.com/bevyengine/bevy/blob/61b83cfc0780cc2b86561cb3f8c7512037f09fca/crates/bevy_reflect/src/serde/ser.rs#L289-L294

So we can use that value instead of doing a second call.
```suggestion
                let table = type_info.map(|i| i.type_path_table());
```

File: crates/bevy_reflect/src/serde/ser.rs [hunk 5]
```diff
@@ -352,10 +357,13 @@ impl<'a> Serialize for EnumSerializer<'a> {
             }
             VariantType::Tuple if field_len == 1 => {
                 let field = self.enum_value.field_at(0).unwrap();
-                if self
+                let table = self
                     .enum_value
-                    .reflect_type_path()
-                    .starts_with("core::option::Option")
+                    .get_represented_type_info()
+                    .map(|i| i.type_path_table());
```
Comment (MrGVSV) [inline crates/bevy_reflect/src/serde/ser.rs:363]: Same here. We can reuse the existing `type_info` variable.

**Review by MrGVSV — CHANGES_REQUESTED** [review]

**Review by MrGVSV — APPROVED** [review]

**Review by alice-i-cecile — APPROVED** [review]
