### PR TITLE
Stepping disabled performance fix 

### LINKED ISSUE #11932: Noticeable schedules running overhead
## Bevy version 0.13

* Original: 0.12.1 release from Cargo.
* Current: 0.13.0 release from Cargo.

## Relevant system information

Please include:

* The Rust version you're using: 1.76
* the operating system or browser used, including its version
  * Windows 11, Ubuntu 22.04

## What's performing poorly?

The schedule is running slower than before, which slowed down my program by 20%. This can impact the performance of real-time simulation applications and may significantly lower the performance when you scale the systems with more schedule plans.

It can be reproduced by running empty schedules:
```rust
use std::time::Instant;

use bevy_ecs::schedule;
use bevy_app::prelude::*;

fn main() {
    let mut app = bevy_app::App::default();
    app.add_schedule(schedule::Schedule::new(First));
    app.add_schedule(schedule::Schedule::new(PreUpdate));
    app.add_schedule(schedule::Schedule::new(Update));
    app.add_schedule(schedule::Schedule::new(PostUpdate));
    app.add_schedule(schedule::Schedule::new(Last));
    let now = Instant::now();
    for _i in 0..20_000_000 {
        app.update();
    }
    println!("{}", now.elapsed().as_micros() as f64 / 1e6);
  
}
```
Performance table for this code:
With LTO = yes
Test Case | Time | Slow Down
-- | -- | --
bevy_ecs 0.12.1 | 13.694943 | 0%
bevy_ecs 0.13, default-features = false | 14.759885 | 7.778%
bevy_ecs 0.13  | 15.566676 | 13.7%

With LTO turned-off 
Test Case | Time | Slow Down
-- | -- | --
bevy_ecs 0.12.1 | 15.359637	 | 0%
bevy_ecs 0.13, default-features = false | 16.61063 | 8%
bevy_ecs 0.13  | 17.642636	| 14.9%

The slowing down is obvious, and I don't use the profiler because such overhead is not caused by user systems.

### PR DESCRIPTION
**Pull request by dmlary**
# Objective

* Fixes #11932 (performance impact when stepping is disabled)

## Solution

The `Option<FixedBitSet>` argument added to `ScheduleExecutor::run()` in #8453 caused a measurable performance impact even when stepping is disabled.  This can be seen by the benchmark of running `Schedule:run()` on an empty schedule in a tight loop (https://github.com/bevyengine/bevy/issues/11932#issuecomment-1950970236).    

I was able to get the same performance results as on 0.12.1 by changing the argument
`ScheduleExecutor::run()` from `Option<FixedBitSet>` to `Option<&FixedBitSet>`.  The down-side of this change is that `Schedule::run()` now takes about 6% longer (3.7319 ms vs 3.9855ns) when stepping is enabled

---

## Changelog
* Change `ScheduleExecutor::run()` `_skipped_systems` from `Option<FixedBitSet>` to `Option<&FixedBitSet>`
* Added a few benchmarks to measure `Schedule::run()` performance with various executors

### CODE REVIEW

File: crates/bevy_ecs/src/schedule/executor/multi_threaded.rs [hunk 1]
```diff
@@ -189,26 +189,27 @@ impl SystemExecutor for MultiThreadedExecutor {
...
 
-            // Finally, we need to clear all skipped systems from the ready
-            // list.
-            //
-            // We invert the skipped system mask to get the list of systems
-            // that should be run.  Then we bitwise AND it with the ready list,
-            // resulting in a list of ready systems that aren't skipped.
-            skipped_systems.toggle_range(..);
-            self.ready_systems &= skipped_systems;
+            // // Finally, we need to clear all skipped systems from the ready
```
Comment (AxiomaticSemantics) [inline crates/bevy_ecs/src/schedule/executor/multi_threaded.rs:205]: Some stray comment directives here

File: crates/bevy_ecs/src/schedule/executor/mod.rs [hunk 2]
```diff
@@ -21,7 +21,7 @@ pub(super) trait SystemExecutor: Send + Sync {
     fn run(
         &mut self,
         schedule: &mut SystemSchedule,
-        skip_systems: Option<FixedBitSet>,
+        skip_systems: Option<&FixedBitSet>,
```
Comment (AxiomaticSemantics) [inline crates/bevy_ecs/src/schedule/executor/mod.rs:24]: Nit, I'd like if the skip_systems argument came after world since it's conditionally used. No big deal either way though.

**Comment by alice-i-cecile** [comment]
Can you split out the removal from the default features? I'd like to ship this in 0.13.1, and that will be a breaking change.

**Comment by dmlary** [comment]
> Can you split out the removal from the default features? I'd like to ship this in 0.13.1, and that will be a breaking change.

Will do

**Review by AxiomaticSemantics — CHANGES_REQUESTED** [review]
LGTM as far as a solution to the regression at hand.

File: crates/bevy_ecs/src/schedule/executor/mod.rs (hunk 2 above)
Comment (dmlary) [reply crates/bevy_ecs/src/schedule/executor/mod.rs:24]: Yea, that makes sense.  I swapped them.

**Review by AxiomaticSemantics — APPROVED** [review]
This resolves any concerns I had.

**Review by james7132 — APPROVED** [review]
The performance hit when enabling skipping is unfortunate but likely acceptable given its use as a debugging tool.
