### PR TITLE
fix: correctly handle UI outline scale

### LINKED ISSUE #12566: `DebugUiPlugin` draws rectangles in wrong position when scale factor is not 1.0
## Bevy version

main

## Relevant system information

```
AdapterInfo { name: "Apple M1 Max", vendor: 0, device: 0, device_type: IntegratedGpu, driver: "", driver_info: "", backend: Metal }
SystemInfo { os: "MacOS 14.2.1 ", kernel: "23.2.0", cpu: "Apple M1 Max", core_count: "10", memory: "64.0 GiB" }
```

## What you did

- Have high DPI display, or override default scale factor.
- `cargo run --example ui --features=bevy_dev_tools`

## What went wrong

image

### PR DESCRIPTION
**Pull request by notmd**
# Objective

- The UI outline in the new dev tools does not handle scale correctly when the scale is not 1. It looks like the `GlobalTransform` already handles `scale`. Fix #12566 
- To reproduce make sure your screen scale is not 1 and run `cargo run --example ui --features bevy/bevy_dev_tools`
- I'm not really familiar with Bevy UI internal so please review this carefully.

## Solution
- Dont apply `window_scale` when calculating `LayoutRect` scale
---
#### Question about UI Node with custom scale: 
- How do we expect the outline when the UI Node is spawn with custom transform
Eg: `Transform::from_scale(Vec3::splat(1.5))`. Related discussion in Discord https://discord.com/channels/691052431525675048/743663673393938453/1219575406986788864

Before
image
After 
image

### CODE REVIEW

File: crates/bevy_dev_tools/src/debug_overlay/mod.rs [hunk 1]
```diff
@@ -200,7 +200,6 @@ fn outline_roots(
         );
     }
     let window_scale = window.get_single().map_or(1., Window::scale_factor);
-    let scale_factor = window_scale * outline.ui_scale.0;
```
[the remark this answers is not in the document]
Comment (notmd) [reply crates/bevy_dev_tools/src/debug_overlay/mod.rs:203]: Yep I figured out that when the compiler complains about unused code. I just updated the code to handle it. Also, update the example to manually control the `UiScale`.

File: examples/ui/ui.rs [hunk 2]
```diff
@@ -17,7 +17,7 @@ fn main() {
         // Only run the app when there is user input. This will significantly reduce CPU/GPU use.
         .insert_resource(WinitSettings::desktop_app())
         .add_systems(Startup, setup)
-        .add_systems(Update, mouse_scroll);
+        .add_systems(Update, (mouse_scroll, update_ui_scale));
```
Comment (pablo-lua) [inline examples/ui/ui.rs:20]: I'm not sure about updating this example: There is already a specific example to ui_scaling, with the same name I think, so this can be controversial. My idea for now is leaving as it is and add an example to this tool  on the dev_tools dir as follow up.

File: crates/bevy_dev_tools/src/debug_overlay/mod.rs [hunk 3]
```diff
@@ -200,7 +200,7 @@ fn outline_roots(
...
+    let scale_factor = outline.ui_scale.0;
```
Comment (pablo-lua) [inline crates/bevy_dev_tools/src/debug_overlay/mod.rs:203]: We can remove this variable definition if we want.

**Review by pablo-lua — APPROVED** [review]
Looks good. Just a comment here, otherwise LGTM

File: crates/bevy_dev_tools/src/debug_overlay/mod.rs (hunk 3 above)
Comment (notmd) [reply crates/bevy_dev_tools/src/debug_overlay/mod.rs:203]: I think it's fine, `scale_factor` is used 2 time on line 243 and 245.

**Review by matiqo15 — APPROVED** [review]

**Comment by notmd** [comment]
@pablo-lua I got the solution for `Node` that has custom `transform` like `Transform::from_scale(Vec3::splat(2))`. Should I include it in this PR or the follow up?

**Comment by pablo-lua** [comment]
> Include it in this PR or the follow up?

I'm not sure I understand the problem here. Maybe you can open a issue about it first? The problem is: When using ui nodes, we aren't expecting transforms to work: The transform is updated [here](https://github.com/bevyengine/bevy/blob/main/crates/bevy_ui/src/layout/mod.rs#L272), outside of user range of manipulation, So if you found some problem here, that can be a strange issue. 
But, for sure, out of scope in this PR as we are fixing another problem.

**Comment by notmd** [comment]
I created the issue here https://github.com/bevyengine/bevy/issues/12576
