### PR TITLE
Bubble sync points if `ignore_deferred`, do not ignore if target system is exclusive

### LINKED ISSUE #17828: Unflushed commands before exclusive system when configured with `*_ignore_deferred`
## Bevy version

I saw this behavior at around 0.14 I think but only now got around making a minimal reproducible example on `main`, or at least a fairly recent commit behind `main`.

## What you did

I ran this code:

```rs
use bevy::prelude::*;

#[derive(Resource)]
struct InsertTest;

fn insert_system(mut commands: Commands) {
    commands.insert_resource(InsertTest);
}
fn assert_system(world: &mut World) {
    assert!(world.contains_resource::<InsertTest>())
}

fn main() {
    App::new()
        .add_systems(
            Update, 
            (insert_system, assert_system).chain_ignore_deferred()
        )
        .update();
}
```

## What went wrong

`assert_system` is an exclusive system, therefore it is expected that the command in `insert_system` is flushed before it runs. The assertion should not fail but it does.

## Additional information

I did some extensive testing and noticed that this bug occurs no matter how I do this configuration as long I make use of the `_ignore_deferred` variants. The following table lists these configurations and gives each a number because that matters for another observation I elaborate further down.

| inserting config by | asserting config by | config | test |
| - | - | - | - | 
| system | system | `after_ignore_deferred` | ❌ `1` |
| system | system | `before_ignore_deferred` | ❌ `2` |
| system | system | `chain_ignore_deferred` | ❌ `3` |
| system | set | `after_ignore_deferred` | ❌ `4` |
| system | set | `before_ignore_deferred` | ❌ `5` |
| set | system | `after_ignore_deferred` | ❌ `6` |
| set | system | `before_ignore_deferred` | ❌ `7` |
| set | set | `after_ignore_deferred` | ❌ `8` |
| set | set | `before_ignore_deferred` | ❌ `9` |
| set | set | `chain_ignore_deferred` | ❌ `10` |

For example the configuration... 
```rs
(insert_system, assert_system).chain_ignore_deferred()
```
... is the third row in the table, where "inserting config by" with "system" means that the first element in the chain tuple is the system, and "asserting config by" with "system" means that the second element in the tuple is also the system itself.

"set" means if the argument is a set, so a `configure_sets` with this configuration... 
```rs
(SetWithInsertSystem, SetWithAssertSystem).chain_ignore_deferred()
```
... is the last row.

`chain` cannot mix systems and sets, but `before` and `after` can mix, therefore these have more rows.

**General observations regarding the two system:**
- the tests do not fail if `insert_system` is exclusive
- the tests do not fail if `insert_system` is exclusive and `assert_system` is not exclusive

### Third system affecting the outcome of the tests

Now I am adding a third, empty system and order them after the two above. I observed that this results in some test going green suddenly.

```rs
fn third() {}
```

| insert-assert config by | third config by | config | ✅ fixes the failing test of ... |
| - | - | - | - | 
| each system | system | `after` | `1` ` ` `3` `4` ` ` ` ` `7` `8` `9` `10` |
| config tuple | system | `before` | `1` ` ` `3` `4` ` ` ` ` `7` `8` `9` `10`  |
| config tuple | system | `chain` | ` ` ` ` ` ` `4` ` ` ` ` `7` `8` `9` `10` |
| each system | set | `after` |`1` `2` `3` ` ` `5` `6` ` ` `8` `9` `10` |
| config tuple | set | `before` | `1` ` ` `3` `4` ` ` ` ` `7` `8` `9` `10` |
| set | system | `after` | `1` `2` `3` `4` `5` ` ` `7` `8` `9` `10` |
| set | system | `before` | `1` `2` `3` ` ` `5` `6` ` ` ` ` ` ` `  ` |
| set | set | `after`| `1` `2` `3` ` ` `5` `6` ` ` ` ` ` ` `  ` |
| set | set | `before` | `1` `2` `3` ` ` `5` `6` ` ` ` ` ` ` `  ` |
| set | set | `chain`| `1` `2` `3` ` ` `5` `6` ` ` ` ` ` ` `  ` |

For example this is the first row with `3`...
```rs
fn main() {
    App::new()
        .add_systems(
            Update, 
            (
                (insert_system, assert_system).chain_ignore_deferred(),
                third.after(insert_system).after(assert_system)
            )
        )
        .update();
}
```
... and this the second row with `3` ...
```rs
fn main() {
    App::new()
        .add_systems(
            Update, 
            (
                (insert_system, assert_system)
                    .chain_ignore_deferred().before(third),
                third
            )
        )
        .update();
}
```
... which both no longer fail.

**General observations regarding the third system:**
- it does not matter if `third` is exclusive or not
- If `third` is configured with `_ignore_deferred` variants, it does not affect the results of the first tests
- If `third` is put before the two, not after, it does not affect the result of the first tests

### Test file

I generated the tests with [this file](https://gist.github.com/urben1680/f6b323b9e70e1f9c9375123990de31b2) which also tests many other combinations that do not fail. It might come useful for testing fixes for this issue. Sorry if it looks horribly, that is how I generate tests. 🫣 Also worth noting that I double-checked that like 5 times but mistakes may only come up with a sixth time. I am just comfortable enough to list the results.

### PR DESCRIPTION
**Pull request by urben1680**
# Objective

Fixes #17828

This fixes two bugs:

1. Exclusive systems should see the effect of all commands queued to that point. That does not happen when the system is configured with `*_ignore_deferred` which may lead to surprising situations. These configurations should not behave like that.
2. If `*_ignore_deferred` is used, no sync point may be added at all **after** the config. Currently this can happen if the last nodes in that config have no deferred parameters themselves. Instead, sync points should always be added after such a config, so long systems have deferred parameters.

## Solution

1. When adding sync points on edges, do not consider `AutoInsertApplyDeferredPass::no_sync_edges` if the target is an exclusive system.
2. when going through the nodes in a directed way, store the information that `AutoInsertApplyDeferredPass::no_sync_edges` suppressed adding a sync point at the target node. Then, when the target node is evaluated later by the iteration and that prior suppression was the case, the target node will behave like it has deferred parameters even if the system itself does not.

## Testing

I added a test for each bug, please let me know if more are wanted and if yes, which cases you would want to see.
These tests also can be read as examples how the current code would fail.

### CODE REVIEW

**Comment by urben1680** [comment]
Tagging @hymm as the original author of the modified file. :wave:

**Review by alice-i-cecile — CHANGES_REQUESTED** [review]
I'd like the tests to be more explicit about what the final inferred schedule looks like, and why that schedule is correct.

**Comment by urben1680** [comment]
> I'd like the tests to be more explicit about what the final inferred schedule looks like, and why that schedule is correct.

As in doing more assertions on the schedule's internal values or adding more comments?

Btw I think there is some other problem to address. As it is now, bubbling a sync point further up means more than one sync point could be generated if there is more than one outgoing edge. But that makes no sense, the original system that wants it's commands applied needs only one sync point.

I try to think what to do here. Until then I put this one into draft again.

**Comment by alice-i-cecile** [comment]
More comments mostly :) I had a hard time following what the internal logic of the tests were, and why they were correct.

**Comment by urben1680** [comment]
I was unable to trigger any issues I assumed to be there so I decided to not change my approach.

File: crates/bevy_ecs/src/schedule/auto_insert_apply_deferred.rs [hunk 1]
```diff
@@ -82,33 +81,45 @@ impl ScheduleBuildPass for AutoInsertApplyDeferredPass {
...
             for target in dependency_flattened.neighbors_directed(*node, Direction::Outgoing) {
-                let add_sync_on_edge = add_sync_after
-                    && !is_apply_deferred(graph.systems[target.index()].get().unwrap())
-                    && !self.no_sync_edges.contains(&(*node, target));
+                let mut add_sync_on_edge = add_sync_after;
+                let mut add_syncs_after_target = false;
+
+                if add_sync_on_edge {
+                    let target_system = graph.systems[target.index()].get().unwrap();
+                    add_sync_on_edge &= !is_apply_deferred(target_system);
```
Comment (urben1680) [inline crates/bevy_ecs/src/schedule/auto_insert_apply_deferred.rs:102]:
```suggestion
                    add_sync_on_edge = !is_apply_deferred(target_system);
```

File: crates/bevy_ecs/src/schedule/auto_insert_apply_deferred.rs [hunk 2]
```diff
@@ -23,25 +23,25 @@ use super::{
...
-            .or_else(|| {
+            .unwrap_or_else(|| {
                 let node_id = self.add_auto_sync(graph);
-                self.auto_sync_node_ids.insert(distance, node_id);
-                Some(node_id)
+                self.auto_sync_node_ids.push(node_id);
+                node_id
             })
-            .unwrap()
     }
```
Comment (urben1680) [inline crates/bevy_ecs/src/schedule/auto_insert_apply_deferred.rs:45]: (Sorry I keep making commits to this PR, I can't help and notice things to tweak)

I noticed that `auto_sync_node_ids` can be a vector:

- The first call to this method is always with a  distance of 1. 
  - `distances_and_pending_sync` is empty at the beginning or has distances with zero values stored
  - If this method is called for the first time, then only when such a zero value was increased from zero and then stored in `distances_and_pending_sync`
- This method is always called with a distance value that is at most 1 higher than it was ever called with before.
  - All unique distances in `distances_and_pending_sync` larger than zero caused a sync point to be buffered here
  - As `target_distance` is increased by `1` at most, a missing sync point for that distance can be easily generated with a single additional push

So I decided to make this method take an `usize` index and offset it by 1 at the calling site.

File: crates/bevy_ecs/src/schedule/schedule.rs [hunk 3]
```diff
@@ -2140,6 +2140,52 @@ mod tests {
...
+            |mut commands: Commands| commands.insert_resource(Resource1),
+            || {},
+        )
+            .chain_ignore_deferred();
+
+        // This chain is configured to add a sync point before the last system, but that would not happen if only the
+        // no-op system in `insert_resource_config` was evaluated as that one has no deferred parameters.
+        // So despite having no direct edge from the system that queues the command to the system that attempts to read
+        // the resource, a sync point is still added between the two tuple elements by the command system's has_deferred
+        // bubbling up to the no-op system.
```
Comment (andriyDev) [inline crates/bevy_ecs/src/schedule/schedule.rs:2182]: Just to be clear, previously no sync point would be generated since "system 1" is ignore_deferred against "system 2" and "system 2" has no deferred commands to apply before "system 3"? And now, "system 1" basically signals "system 2" that there are still pending commands?

File: crates/bevy_ecs/src/schedule/auto_insert_apply_deferred.rs [hunk 4]
```diff
@@ -82,39 +82,53 @@ impl ScheduleBuildPass for AutoInsertApplyDeferredPass {
...
+
+                let target_system = graph.systems[target.index()].get().unwrap();
+
+                if is_apply_deferred(target_system) {
+                    // if target system is `ApplyDeferred` there is no point in adding another sync point
+                    continue;
+                }
+
+                if !target_system.is_exclusive() && self.no_sync_edges.contains(&(*node, target)) {
+                    // add sync point on a later edge
```
Comment (andriyDev) [inline crates/bevy_ecs/src/schedule/auto_insert_apply_deferred.rs:118]: Can we make this comment a little more descriptive? e.g., "`node` has deferred commands to apply, but this edge is a no sync edge. Mark the target node as 'delaying' those commands to a future edge".

File: crates/bevy_ecs/src/schedule/auto_insert_apply_deferred.rs [hunk 5]
```diff
@@ -23,25 +23,25 @@ use super::{
...
 pub struct IgnoreDeferred;
 
 impl AutoInsertApplyDeferredPass {
-    /// Returns the `NodeId` of the cached auto sync point. Will create
-    /// a new one if needed.
-    fn get_sync_point(&mut self, graph: &mut ScheduleGraph, distance: u32) -> NodeId {
+    /// Returns the `NodeId` of the cached auto sync point. Will create a new one if needed.
+    ///
+    /// Is expected to be called with an index not larger than the amount of cached sync points so far.
+    fn get_sync_point(&mut self, graph: &mut ScheduleGraph, index: usize) -> NodeId {
```
Comment (andriyDev) [inline crates/bevy_ecs/src/schedule/auto_insert_apply_deferred.rs:36]: Should we maybe add an assert (or maybe just a debug_assert) that the `index <= auto_sync_node_ids.len()`?

File: crates/bevy_ecs/src/schedule/auto_insert_apply_deferred.rs (hunk 2 above)
Comment (hymm) [reply crates/bevy_ecs/src/schedule/auto_insert_apply_deferred.rs:45]: I'm not sure if this change is worth it. This isn't particularly perf sensitive code and it adds a invariant that the sync's are added in topological order, which might not always be the case.

File: crates/bevy_ecs/src/schedule/schedule.rs (hunk 3 above)
Comment (urben1680) [reply crates/bevy_ecs/src/schedule/schedule.rs:2182]: Correct. I take your confusion that I try to make this comment more clear.

File: crates/bevy_ecs/src/schedule/auto_insert_apply_deferred.rs (hunk 2 above)
Comment (urben1680) [reply crates/bevy_ecs/src/schedule/auto_insert_apply_deferred.rs]: That is a good point, I reverted this change.

File: crates/bevy_ecs/src/schedule/auto_insert_apply_deferred.rs (hunk 5 above)
Comment (urben1680) [reply crates/bevy_ecs/src/schedule/auto_insert_apply_deferred.rs]: I reverted this back to a HashMap

File: crates/bevy_ecs/src/schedule/auto_insert_apply_deferred.rs (hunk 2 above)
Comment (andriyDev) [reply crates/bevy_ecs/src/schedule/auto_insert_apply_deferred.rs]: I personally don't agree with this revert, it actually made it much more clear in my head that we are always only adding the next necessary sync point. 

Regardless, this could be a follow-up PR so I don't think we should block this PR on it.

**Comment by urben1680** [comment]
Merged @andriyDev's changes into this PR. I must confess both our changes together make this hard to understand. I probably will try to make everything clearer, maybe with more comments, other variable names or such stuff.

If someone has good ideas to make this more clear, please write them in a comment. :smiley:

**Review by alice-i-cecile — APPROVED** [review]
Good test comments now! Thanks for tackling some cleanup work while you were here; I agree that this was getting quite tricky to follow 😅
