### PR TITLE
Fix Added behaviour with QueryOne get

### LINKED ISSUE #541: Added<X> not properly filtered in QueryOne.get() and Query.get() methods
With the following standalone testcase, after the second iteration when Added counting becomes 0, I think we should also see both boolean be false.
The second boolean, being based QueryOne.get() has been reported by @cart to behave incorrectly in #488.
But I suspect the first one, based onQuery.get()  should also return false ?

```rust
use bevy::prelude::*;

fn main() {
    App::build()
        .add_default_plugins()
        .add_startup_system(startup_system.system())
        .add_system(normal_system.system())
        .run();
}

struct Comp {}
/// Startup systems are run exactly once when the app starts up.
/// They run right before "normal" systems run.
fn startup_system(mut commands: Commands) {
    commands.spawn((Comp {},));
    let entity = commands.current_entity().unwrap();
    commands.insert_resource(entity);
}

fn normal_system(
    entity: Res<Entity>,
    mut query: Query<(&Comp,)>,
    mut query_added: Query<(Added<Comp>,)>,
) {
    let mut n_comp = 0;
    let mut n_added = 0;
    for (_comp,) in &mut query.iter() {
        n_comp += 1;
    }
    for (_comp,) in &mut query_added.iter() {
        n_added += 1;
    }
    let found1 = query_added.get::<Comp>(*entity).is_some();
    let mut one = query_added.entity(*entity).unwrap();
    let found2 = one.get().is_some();
    println!(
        "Count: {}, Added: {}, query.get {} query.entity.get {}",
        n_comp, n_added, found1, found2
    );
}
```

### PR DESCRIPTION
**Pull request by Bobox214**
Trying to fix #541

### CODE REVIEW

File: crates/bevy_ecs/src/system/query.rs [hunk 1]
```diff
@@ -54,9 +54,18 @@ impl<'a, Q: HecsQuery> Query<'a, Q> {
...
+                        location.index,
+                    )
+                    .map_or(true, |f| f.should_skip())
+                    {
+                        Err(QueryError::ComponentError(ComponentError::NoSuchEntity))
+                    } else {
+                        self.world
+                            .get_ref_at_location_unchecked(location)
+                            .map_err(QueryError::ComponentError)
+                    }
```
Comment (Bobox214) [inline crates/bevy_ecs/src/system/query.rs:68]: I am clearly not confident on this part of PR and would gladly have a thorough review here.

Comment (cart) [reply crates/bevy_ecs/src/system/query.rs:68]: Hmm this has significant performance implicantions because we are now doing a "full lookup" of every component storage in the query. I'm not sure thats worth the tradeoff when we can use "Query One" when this behavior is required.

I'm down to merge the "query one" part of this PR now, but this change will require some serious thought / im pretty sure its not worth it.

Comment (Bobox214) [reply crates/bevy_ecs/src/system/query.rs:68]: Ok, I see.
This is effectively not worth it.
In my case I have created all the camera I need in a startup components.

Comment (Bobox214) [reply crates/bevy_ecs/src/system/query.rs:68]: Ok, I see and will update the PR to only include the query_one part.

**Review by cart — APPROVED** [review]
