### PR TITLE
Fix vignette docstring to match default values

### LINKED ISSUE #22677: Docs about Vignette default values differ from the actual
## Bevy version and features

main

## What went wrong

See https://github.com/bevyengine/bevy/blob/main/crates/bevy_post_process/src/effect_stack/vignette.rs, the default values is different from docs. I'm not sure about the correct default values for these settings.

### PR DESCRIPTION
**Pull request by glennDittmann**
# Objective
Update docstrings to match the actual default values defined as `const`s in the code. 

Fixes #22677 

## Solution
/

## Testing
/

### CODE REVIEW

File: crates/bevy_post_process/src/effect_stack/vignette.rs [hunk 1]
```diff
@@ -45,25 +45,25 @@ pub struct Vignette {
...
     ///
-    /// The default value is 1.00
+    /// The default value is 0.75
     pub radius: f32,
     /// The softness of the edge between the clear and dark areas.
     ///
     /// Range: `0.01` (Sharp edge) to `1.0+` (Very soft edge)
     ///
-    /// The default value is 0.50
+    /// The default value is 5.0
```
Comment (glennDittmann) [inline crates/bevy_post_process/src/effect_stack/vignette.rs:60]: is it a a `bevy` styleguide that only the `1.00` should be written with two digits after the comma? 
Or should it actually be `5.00` here and in the definition of the default smoothness (line 20) ?

Comment (alice-i-cecile) [reply crates/bevy_post_process/src/effect_stack/vignette.rs:60]: Generally we're not too picky here. I don't like the extra 0s though, and would stick with e.g. 5.0 for floats.

**Review by alice-i-cecile — APPROVED** [review]

File: crates/bevy_post_process/src/effect_stack/vignette.rs (hunk 1 above)
Comment (glennDittmann) [reply crates/bevy_post_process/src/effect_stack/vignette.rs:60]: okay, thanks :)

Comment (IceSentry) [reply crates/bevy_post_process/src/effect_stack/vignette.rs:60]: Yeah, the `.00` feels a bit weird

**Review by IceSentry — APPROVED** [review]
I would prefer if evertyhing used `.0` but other than that LGTM

File: crates/bevy_post_process/src/effect_stack/vignette.rs (hunk 1 above)
Comment (glennDittmann) [reply crates/bevy_post_process/src/effect_stack/vignette.rs:60]: okay, i have updated it too only use one trailing zero :)
