### PR TITLE
Fix rendering of sprites, text, and meshlets after #12582.

### LINKED ISSUE #12935: Sprite example broken after #12582: Divide the single `VisibleEntities` list
## Bevy version

The release number or commit hash of the version you're using.

5caf085da (from #12582)

## Relevant system information

```
INFO bevy_diagnostic::system_information_diagnostics_plugin::internal: SystemInfo { os: "MacOS 14.2.1 ", kernel: "23.2.0", cpu: "Apple M1 Max", core_count: "10", memory: "64.0 GiB" }
INFO bevy_render::renderer: AdapterInfo { name: "Apple M1 Max", vendor: 0, device: 0, device_type: IntegratedGpu, driver: "", driver_info: "", backend: Metal }
INFO bevy_winit::system: Creating new window "App" (Entity { index: 0, generation: 1 })
```

## What you did

```
$ RUST_BACKTRACE=full MTL_HUD_ENABLED= cargo run --example sprite
```

## What went wrong

Looks like this:

image

## Additional information

Works before this commit on 5c3ae32ab:

```
$ git checkout 5c3ae32ab
$ RUST_BACKTRACE=full MTL_HUD_ENABLED= cargo run --example sprite
```

image

### PR DESCRIPTION
**Pull request by pcwalton**
`Sprite`, `Text`, and `Handle<MeshletMesh>` were types of renderable entities that the new segregated visible entity system didn't handle, so they didn't appear.

Because `bevy_text` depends on `bevy_sprite`, and the visibility computation of text happens in the latter crate, I had to introduce a new marker component, `SpriteSource`. `SpriteSource` marks entities that aren't themselves sprites but become sprites during rendering. I added this component to `Text2dBundle`. Unfortunately, this is technically a breaking change, although I suspect it won't break anybody in practice except perhaps editors.

Fixes #12935.

### Changed

* `Text2dBundle` now includes a new marker component, `SpriteSource`. Bevy uses this internally to optimize visibility calculation.

## Migration Guide

* `Text` now requires a `SpriteSource` marker component in order to appear. This component has been added to `Text2dBundle`.

### CODE REVIEW

**Review by superdump — COMMENTED** [review]
Not a thorough review but looks ok. Nothing controversial in my opinion. Noting this in case others get to it more thoroughly before me.

**Review by alice-i-cecile — APPROVED** [review]

**Review by Elabajaba — APPROVED** [review]
It fixes the bug for me.

It'd be nice if there was a way to collapse this into a 1 or 2 liner somehow, but not essential.

```rust
                check_visibility::<WithMeshletMesh>
                    .in_set(VisibilitySystems::CheckVisibility)
                    .after(VisibilitySystems::CalculateBounds)
                    .after(VisibilitySystems::UpdateOrthographicFrusta)
                    .after(VisibilitySystems::UpdatePerspectiveFrusta)
                    .after(VisibilitySystems::UpdateProjectionFrusta)
                    .after(VisibilitySystems::VisibilityPropagate)
                    .after(TransformSystem::TransformPropagate),
```

File: crates/bevy_sprite/src/lib.rs [hunk 1]
```diff
@@ -69,6 +71,22 @@ pub enum SpriteSystem {
     ComputeSlices,
 }
 
+/// A component that marks entities that aren't themselves sprites but become
+/// sprites during rendering.
+///
+/// Right now, this is used for `Text`.
+#[derive(Component, Reflect, Clone, Copy, Debug, Default)]
+#[reflect(Component, Default)]
+pub struct SpriteSource;
```
Comment (Elabajaba) [inline crates/bevy_sprite/src/lib.rs:80]: I don't quite understand why we need this, but I also couldn't get this working with just `Text` so I assume it's necessary.

File: crates/bevy_text/src/lib.rs [hunk 2]
```diff
@@ -101,6 +107,13 @@ impl Plugin for TextPlugin {
                         // will never modify a pre-existing `Image` asset.
                         .ambiguous_with(CameraUpdateSystem),
                     remove_dropped_font_atlas_sets,
+                    check_visibility::<WithText>
```
Comment (Elabajaba) [inline crates/bevy_text/src/lib.rs:110]: Is this necessary if we're already doing a `check_visibility` on it with the `SpriteSource` component?

File: crates/bevy_sprite/src/lib.rs (hunk 1 above)
Comment (pcwalton) [reply crates/bevy_sprite/src/lib.rs:80]: Hmm, actually I think I came up with a way to make that no longer necessary. I'll try it tonight.

Comment (pcwalton) [reply crates/bevy_sprite/src/lib.rs:80]: Actually, never mind, it'd be uglier than the current solution.

The problem is that `Text` uses the sprite visibility checking system. But that system can't name `Text` as it's an upstream crate. So we need some marker component that the sprite visibility checker can name.

Comment (pcwalton) [reply crates/bevy_sprite/src/lib.rs:80]: BTW, the idea I had was to introduce a "label" type that's different from the component type. That way `Sprite` and `Text` would have the same label. But then you'd need two `check_visibility` systems, one for each component, that together populate the *same* `VisibleEntities` list. I think that's uglier than just using `SpriteSource`.

File: crates/bevy_text/src/lib.rs (hunk 2 above)
Comment (pcwalton) [reply crates/bevy_text/src/lib.rs]: Good point, it isn't necessary. I removed it.
