### PR TITLE
UI borders and outlines clipping fix

### LINKED ISSUE #15502: Border / radius doesn't respect full Node size.
## Bevy version

0.14.2

## What you did

I use rounded borders on UI elements.

## What went wrong

When there is not enough space for the entire Node to be visible, the node is squished. This is extremely visible with rounded borders, as the rounding gets distorted and remain fully on screen.

- what were you expecting?

Node should be clipped

- what actually happened?

Node get squished.

## Additional information

This is with flex shrink: 0. I think rendering uses the visible clip rect as if it was the full UV 0-1 range, rather than clamping the UV to the visible portion.

The effect is clearly visible on the radio buttons in the gif below, but also notice the button corners remaining on-screen as well:

border_radius_squish

### PR DESCRIPTION
**Pull request by ickshonpe**
# Objective

fixes #15502

Clipped borders and outlines aren't drawn correctly.

### Borders aren't clipped

Spawn two nodes with the same dimensions and border thickness, but clip on of the nodes so that only its top left quarter is visible:

clip

You can see that instead of clipping the border, instead the border is scaled to fit inside of the unclipped section.

```rust
use bevy::color::palettes::css::BLUE;
use bevy::prelude::*;
use bevy::winit::WinitSettings;

fn main() {
    App::new()
        .add_plugins(DefaultPlugins)
        .insert_resource(WinitSettings::desktop_app())
        .add_systems(Startup, setup)
        .run();
}

fn setup(mut commands: Commands) {
    commands.spawn(Camera2d);
    commands
        .spawn(Node {
            width: Val::Percent(100.),
            height: Val::Percent(100.),
            justify_content: JustifyContent::Center,
            align_items: AlignItems::Center,
            ..Default::default()
        })
        .with_children(|commands| {
            commands
                .spawn(Node {
                    column_gap: Val::Px(10.),
                    ..Default::default()
                })
                .with_children(|commands| {
                    commands
                        .spawn(Node {
                            width: Val::Px(100.),
                            height: Val::Px(100.),
                            overflow: Overflow::clip(),
                            ..Default::default()
                        })
                        .with_child((
                            Node {
                                position_type: PositionType::Absolute,
                                width: Val::Px(100.),
                                height: Val::Px(100.),
                                border: UiRect::all(Val::Px(10.)),
                                ..Default::default()
                            },
                            BackgroundColor(Color::WHITE),
                            BorderColor(BLUE.into()),
                        ));

                    commands
                        .spawn(Node {
                            width: Val::Px(50.),
                            height: Val::Px(50.),
                            overflow: Overflow::clip(),
                            ..Default::default()
                        })
                        .with_child((
                            Node {
                                position_type: PositionType::Absolute,
                                width: Val::Px(100.),
                                height: Val::Px(100.),
                                border: UiRect::all(Val::Px(10.)),
                                ..Default::default()
                            },
                            BackgroundColor(Color::WHITE),
                            BorderColor(BLUE.into()),
                        ));
                });
        });
}
```

You can also see this problem in the `overflow` example. If you hover over any of the clipped nodes you'll see that the outline only wraps the visible section of the node

### Outlines are clipped incorrectly

A UI nodes Outline's are drawn outside of its bounds, so applying the local clipping rect to the outline doesn't make any sense.
Instead an `Outline` should be clipped using its parent's clipping rect.

## Solution

* Pass the `point` value into the vertex shader instead of calculating it in the shader.
* In `extract_uinode_borders` use the parents clipping rect when clipping outlines.

The extra parameter isn't a great solution I think, but I wanted to fix borders for the 0.15 release and this is the most minimal approach I could think of without replacing the whole shader and prepare function. 

 ## Showcase

clipp

### CODE REVIEW

**Comment by ickshonpe** [comment]
I'll update the docs for the new paramater in a few hours, got some errands I need to run.

**Review by BenjaminBrienen — APPROVED** [review]

**Review by JMS55 — APPROVED** [review]

File: crates/bevy_ui/src/render/mod.rs [hunk 1]
```diff
@@ -768,6 +775,8 @@ struct UiVertex {
     pub border: [f32; 4],
     /// Size of the UI node.
     pub size: [f32; 2],
+    /// Postion relative to the center of the UI node.
```
Comment (alice-i-cecile) [inline crates/bevy_ui/src/render/mod.rs:778]:
```suggestion
    /// Position relative to the center of the UI node.
```
