### PR TITLE
`EditableText` change detection using `parley::Generation`

### LINKED ISSUE #23793: `TextEdit::SelectAll` and `TextEdit::CollapseSelection` do not affect highlighting
## Bevy version and features

- 0.19-dev c040d76
- Using feature experimental_bevy_feathers

## \[Optional\] Relevant system information

If you cannot get Bevy to build or run on your machine, please include:

- macOS Tahoe 26.4.1
- rustc 1.94.1

If your bug is rendering-related, copy the adapter info that appears when you run Bevy.

```ignore
AdapterInfo { name: "Apple M5", vendor: 0, device: 0, device_type: IntegratedGpu, device_pci_bus_id: "", driver: "", driver_info: "", backend: Metal, subgroup_min_size: 4, subgroup_max_size: 64, transient_saves_memory: true }
```

## What you did

I ran the feathers example, highlighted a few characters in the text input, then dragged the color sliders to update it.

## What went wrong

- `editable_text.queue_edit(TextEdit::SelectAll);` failed to highlight all text (even when the `TextEdit::Insert` after it was commented out)
- Adding `editable_text.queue_edit(TextEdit::CollapseSelection);` after the call to `TextEdit::Insert` would also fail to clear the selection
- The example uses a proportional font, so highlighting would look extra wrong when the text was changed programmatically

Image

### PR DESCRIPTION
**Pull request by ickshonpe**
# Objective

Improved change detection for `EditableText`.

Fixes #23793

## Solution

* Remove the `text_edited` field from `EditableText` that was used for manual change detection.
* Use the `PlainEditor`'s `Generation` to track changes.
* New component `EditableTextGeneration`. Newtypes `parley::Generation`. Stores the generation from the last `TextLayoutInfo` update. 
* If `EditableText::editor`'s and `EditableTextGeneration`'s generation values aren't equal, reupdate `TextLayoutInfo`.
* Added support for `TextLayout::justify`.
* Split up `editable_text_system` into two systems `update_editable_text_styles` and `update_editable_text_layout`. The text input's style values need to be updated before layout, so the measure func returns the correct size for the text layout.
* New `EditableText` `testbed_ui` scene.
* Added two numeric inputs to `multiline_text_input` that allow you to set the height of the multiline input and its fontsize.
* Update selection rects on all changes, not just when a text input is focused.

## Testing

```
cargo run --example multiline_text_input
```

The cursor appears to be missing for the numeric inputs in the example but it isn't. The cursor gets clipped because it's at the end of the right aligned input value text. If you press left it comes into view. Cursor and scrolling behaviour needs some adjustments but that's out of the scope of this PR.

### CODE REVIEW

File: crates/bevy_ui/src/widget/text_editable.rs [hunk 1]
```diff
@@ -93,12 +94,92 @@ pub fn update_editable_text_content_size(
...
+    }
+}
+
 /// Updates [`EditableText::editor`] to match e.g. [`TextFont`]
 /// Writes layout to [`TextLayoutInfo`] for rendering
 /// Adds required glyphs to the texture atlas
-// TODO: add change detection logic here to improve performance
-pub fn editable_text_system(
-    fonts: Res<Assets<Font>>,
+pub fn update_editable_text_layout(
```
Comment (alice-i-cecile) [inline crates/bevy_ui/src/widget/text_editable.rs:246]: I really like the split here: this is a sensbile division and it makes these systems easier to understand.

File: crates/bevy_ui/src/widget/text_editable.rs [hunk 2]
```diff
@@ -93,12 +94,92 @@ pub fn update_editable_text_content_size(
     }
 }
 
+pub fn update_editable_text_styles(
```
Comment (alice-i-cecile) [inline crates/bevy_ui/src/widget/text_editable.rs:160]: Doc comments describing the high level task of this system would be nice.

File: crates/bevy_ui/src/widget/text_editable.rs [hunk 3]
```diff
@@ -93,12 +94,92 @@ pub fn update_editable_text_content_size(
...
+    rem_size: Res<RemSize>,
+) {
+    for (mut editable_text, text_font, line_height, target, text_layout) in
+        editable_text_query.iter_mut()
+    {
+        if f32::EPSILON < (target.scale_factor() - editable_text.editor.get_scale()).abs() {
+            editable_text.editor.set_scale(target.scale_factor());
+        }
+
+        if text_font.is_changed()
```
Comment (alice-i-cecile) [inline crates/bevy_ui/src/widget/text_editable.rs:180]: Bug: this doesn't re-apply changes to the font size if the viewport size or rem_size changes.

This is a regression, since the old code unconditionally updated styles :)

File: crates/bevy_text/src/text_editable.rs [hunk 4]
```diff
@@ -231,26 +236,29 @@ impl EditableTextFilter {
...
+            match filter {
+                Some(EditableTextFilter(Some(filter))) => filter.as_ref(),
+                _ => &|_| true,
+            },
+        );
 
+        if **generation != editable_text.editor.generation() {
             commands.trigger(TextEditChange { entity });
         }
     }
```
Comment (alice-i-cecile) [inline crates/bevy_text/src/text_editable.rs:270]: Just below this: the docs for `TextEditChange` are out of date. I don't believe that it's fired on cursor motions anymore.

File: crates/bevy_text/src/text_editable.rs [hunk 5]
```diff
@@ -231,26 +236,29 @@ impl EditableTextFilter {
...
-                &mut font_context.0,
-                &mut layout_context.0,
-                &mut clipboard_text.0,
-                match filter {
-                    Some(EditableTextFilter(Some(filter))) => filter.as_ref(),
-                    _ => &|_| true,
-                },
-            );
+    for (entity, mut editable_text, filter, generation) in query.iter_mut() {
+        editable_text.apply_pending_edits(
```
Comment (alice-i-cecile) [inline crates/bevy_text/src/text_editable.rs]: Nit: we can save a bit of work by avoiding this function call (which creates a driver) if there are no pending edits.

File: crates/bevy_text/src/text_editable.rs [hunk 6]
```diff
@@ -203,19 +208,19 @@ impl EditableText {
         }
     }
 
-    /// Clears the current input and resets the cursor position.
-    pub fn clear(
-        &mut self,
-        font_context: &mut FontContext,
-        layout_context: &mut LayoutContext<TextBrush>,
-    ) {
+    /// Clears the input's text buffer and any pending edits.
```
Comment (alice-i-cecile) [inline crates/bevy_text/src/text_editable.rs:215]: Do we no longer reset the cursor position, or was this not worth including in the docs?

**Review by alice-i-cecile — CHANGES_REQUESTED** [review]
One important bug fix and a few nits. I have a good understanding of this now, and am very much on board in principle.

**Review by viridia — APPROVED** [review]

**Review by Zeophlite — APPROVED** [review]
Really nice

File: crates/bevy_ui/src/widget/text_editable.rs (hunk 3 above)
Comment (ickshonpe) [reply crates/bevy_ui/src/widget/text_editable.rs:180]: oh yeah good catch, it'll be simpler if it just recalculate the text size and compares the values too

File: crates/bevy_text/src/text_editable.rs (hunk 6 above)
Comment (ickshonpe) [reply crates/bevy_text/src/text_editable.rs:215]: It's implied I think, if the buffer is empty the cursor must be at the 0 position.

File: crates/bevy_text/src/text_editable.rs (hunk 5 above)
Comment (ickshonpe) [reply crates/bevy_text/src/text_editable.rs]: `driver` just returns a wrapper around the three arguments that is used to implement some helper methods. But it doesn't hurt to call it conditionally I guess.

File: crates/bevy_text/src/text_editable.rs (hunk 4 above)
Comment (ickshonpe) [reply crates/bevy_text/src/text_editable.rs:270]: It still is, the PlainEditor's generation value is updated on cursor and selection changes not just changes to the text buffer.

**Comment by ickshonpe** [comment]
I think everything is good now. There are some weird CI errors that I don't think are to do with this PR?

**Review by alice-i-cecile — APPROVED** [review]
