### PR TITLE
Ensure consistency between Un/Typed `AssetId` and `Handle`

### LINKED ISSUE #10629: `UntypedAssetId` and `AssetId<A>` have different hashes for the same `Asset`
## Bevy version

0.12

## What you did

1. Created a `Handle` to an `Asset`
2. Cloned that `Handle` and called `untyped()` to get an `UntypedHandle` to the same `Asset`
3. Hashed both values separately with a fixed hasher (e.g., `bevy_utils::AHasher::default()`)
4. Observed the values were not identical.

## What went wrong

I would expect the hash of these two handles to be the same, since they are for the same `Asset`, and are intended to be interoperable types. However, the values differed.

## Additional information

- The difference was caused by `UntypedHandle` including the `TypeId` in the hash, where `Handle` does not. This same issue is present in the `AssetId` and `UntypedAssetId` types.
- I have created #10628 to address this issue.

## Reproduction

```rust
type TestAsset = ();
const UUID: Uuid = Uuid::from_u128(123);

fn hash<T: Hash>(data: &T) -> u64 {
    use std::hash::Hasher;
    let mut hasher = bevy_utils::AHasher::default();
    data.hash(&mut hasher);
    hasher.finish()
}

#[test]
fn hashing() {
    let typed = AssetId::<TestAsset>::Uuid { uuid: UUID };
    let untyped = UntypedAssetId::Uuid {
        type_id: TypeId::of::<TestAsset>(),
        uuid: UUID,
    };

    assert_eq!(hash(&typed), hash(&untyped));
}
```

### PR DESCRIPTION
**Pull request by bushrat011899**
# Objective

- Fixes #10629
- `UntypedAssetId` and `AssetId` (along with `UntypedHandle` and `Handle`) do not hash to the same values when pointing to the same `Asset`. Additionally, comparison and conversion between these types does not follow idiomatic Rust standards.

## Solution

- Added new unit tests to validate/document expected behaviour
- Added trait implementations to make working with Un/Typed values more ergonomic
- Ensured hashing and comparison between Un/Typed values is consistent
- Removed `From` trait implementations that panic, and replaced them with `TryFrom`

---

## Changelog

- Ensured `Handle::<A>::hash` and `UntypedHandle::hash` will produce the same value for the same `Asset`
- Added non-panicing `Handle::<A>::try_typed`
- Added `PartialOrd` to `UntypedHandle` to match `Handle<A>` (this will return `None` for `UntypedHandles` for differing `Asset` types)
- Added `TryFrom<UntypedHandle>` for `Handle<A>`
- Added `From<Handle<A>>` for `UntypedHandle`
- Removed panicing `From<Untyped...>` implementations. These are currently unused within the Bevy codebase, and shouldn't be used externally, hence removal.
- Added cross-implementations of `PartialEq` and `PartialOrd` for `UntypedHandle` and `Handle<A>` allowing direct comparison when `TypeId`'s match.
- Near-identical changes to `AssetId` and `UntypedAssetId`

## Migration Guide

If you relied on any of the panicing `From<Untyped...>` implementations, simply call the existing `typed` methods instead. Alternatively, use the new `TryFrom` implementation instead to directly expose possible mistakes.

## Notes

I've made these changes since `Handle` is such a fundamental type to the entire `Asset` ecosystem within Bevy, and yet it had pretty unclear behaviour with no direct testing. The fact that hashing untyped vs typed versions of the same handle would produce different values is something I expect to cause a very subtle bug for someone else one day.

I haven't included it in this PR to avoid any controversy, but I also believe the `typed_unchecked` methods should be removed from these types, or marked as `unsafe`. The `texture_atlas` example currently uses it, and I believe it is a bad choice. The performance gained by not type-checking before conversion would be entirely dwarfed by the act of actually loading an asset and creating its handle anyway. If an end user is in a tight loop repeatedly calling `typed_unchecked` on an `UntypedHandle` for the entire runtime of their application, I think the small performance drop caused by that safety check is ~~a form of cosmic justice~~ reasonable.

### CODE REVIEW

**Review by KirmesBude — APPROVED** [review]
Can not comment on the implementation, but I ran into this mismatch of (untyped) TypeIds and these changes fix the problem. Thanks :)

Is it possible to separate the underlying change from the breaking changes for potential inclusion in 0.12.1? (Whether that is something actually worth pursuing, I will leave up to someone else, but I would appreciate it :D)

File: crates/bevy_asset/src/handle.rs [hunk 1]
```diff
@@ -249,6 +248,34 @@ impl<A: Asset> PartialEq for Handle<A> {
...
 impl<A: Asset> Eq for Handle<A> {}
 
+impl<A: Asset> From<Handle<A>> for AssetId<A> {
+    #[inline]
+    fn from(value: Handle<A>) -> Self {
+        value.id()
+    }
+}
+
+impl<A: Asset> From<&Handle<A>> for AssetId<A> {
```
Comment (alice-i-cecile) [inline crates/bevy_asset/src/handle.rs:258]: We can replace this and the above with a blanket impl using the `Borrow` trait.

Comment (alice-i-cecile) [reply crates/bevy_asset/src/handle.rs:258]: Same below of course :)

**Review by alice-i-cecile — APPROVED** [review]
I think that cleaning up the trait impls using the `Borrow` trait is nice, but we can do that in a different PR if you prefer.

On board with fixing this, and the code and tests are good.

File: crates/bevy_asset/src/handle.rs (hunk 1 above)
Comment (bushrat011899) [reply crates/bevy_asset/src/handle.rs:258]: I don't think we can, because it appears to conflict with the existing blanket implementation for `From`:

```rust
impl<H> From<H> for UntypedAssetId where H: Borrow<UntypedHandle> {
    #[inline]
    fn from(value: H) -> Self {
        value.id()
    }
}
```

```
error[E0119]: conflicting implementations of trait `From<handle::UntypedHandle>` for type `id::UntypedAssetId`
   --> crates\bevy_asset\src\handle.rs:439:1
    |
432 | impl From<UntypedHandle> for UntypedAssetId {
    | ------------------------------------------- first implementation here
...
439 | impl<H> From<H> for UntypedAssetId where H: Borrow<UntypedHandle> {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ conflicting implementation for `id::UntypedAssetId`
```

I think this is one of those instances where [`impl` specialisation](https://rust-lang.github.io/rfcs/1210-impl-specialization.html) would be required.
