### PR TITLE
register read on DefaultErrorHandler in CombinatorSystem

### LINKED ISSUE #22133: unsound call to default_error_handler
## Bevy version and features

- main branch after #20671 was merged

## What went wrong

This call to default system handler is unsound:
https://github.com/bevyengine/bevy/pull/20671/changes#diff-0e47efcf16c3678b59327508ac55eb70852f97c045dc1c4033aa57d8d3a34b5eR177

`default_system_handler` reads the `DefaultErrorHandler` resource, but `SystemCombinator` doesn't register read access to that resource.

## Potential Fix

- We could register the access in `System::initialize`

### PR DESCRIPTION
**Pull request by janis-bhm**
# Objective
Fixes #22133

## Solution
`CombinatorSystem` now registers a read on the `DefaultErrorHandler` resource in `System::initialize` as @hymm suggested. I've also decided to deny `unsafe_op_in_unsafe_fn` in that method, which I think would have helped me find this beforehand..

## Testing
I've written a test that checks that `CombinatorSystems` can still access the resource mutably, checks that a combinatory system does conflict with a system which mutably accesses the resource, and runs such a schedule to possibly allow miri to catch the error that this PR fixes (this last point doesn't seem to be the true, but afaik that could be due to it not actually being run in parallel even when it's legal for the executor to do so?).

### CODE REVIEW

File: crates/bevy_ecs/src/system/combinator.rs [hunk 1]
```diff
@@ -198,12 +201,15 @@ where
             input,
             &mut PrivateUnsafeWorldCell(world),
             // SAFETY: The world accesses for both underlying systems have been registered,
-            // so the caller will guarantee that no other systems will conflict with `a` or `b`.
+            // so the caller will guarantee that no other systems will conflict with (`a` or `b`) and DEH.
```
Comment (hymm) [inline crates/bevy_ecs/src/system/combinator.rs]:
```suggestion
            // so the caller will guarantee that no other systems will conflict with (`a` or `b`) and the `DefaultErrorHandler` resource.
```

File: crates/bevy_ecs/src/system/combinator.rs [hunk 2]
```diff
@@ -481,11 +492,56 @@ where
...
+        let system = CombinatorSystem::<OrMarker, _, _>::new(
+            IntoSystem::into_system(a),
+            IntoSystem::into_system(b),
+            DebugName::borrowed("a OR b"),
+        );
+
+        // `system` should not conflict with itself by mutably accessing the error handler resource.
+        assert_system_does_not_conflict(system.clone());
 
+        let system = CombinatorSystem::<AndMarker, _, _>::new(
```
Comment (hymm) [inline crates/bevy_ecs/src/system/combinator.rs]: Do we need to construct an `and` system here? It feels like it would be enough to just reuse the `or` system.

**Review by cart — APPROVED** [review]
