### PR TITLE
:bug: Fixes PropagateStop and PropagateOver

### LINKED ISSUE #21620: PropagateStop prevents self from having component
The PropagateStop documentation ([here](https://docs.rs/bevy/latest/bevy/app/struct.PropagateStop.html)) states "Children will not inherit the component."

This implies that the component with PropagateStop should have it.

This appears to not be the case. Based on reading the source, it seems to remove the value on itself.

The tests also do not test whether the propagated component arrives on the holder of PropagateStop, so at a minimum this appears to be a lapse (regardless of which of the behaviors is actually correct).

Is the Documentation Correct? That a PropagateStop<C> as a child of Propagate<C> SHOULD have the inherited C on it?

Looking Closer and updating tests, it seems that maybe even PropagateOver doesn't work at all.

### PR DESCRIPTION
**Pull request by ekwoka**
# Objective

Fixes #21620 

Ensures `PropagateStop` works as documented. At it stands, `PropagateStop<C>` is described as only preventing it's Children from inheriting `C` but in practice that entity itself would not inherit `C`.

Makes `PropagateOver` work. It just plain didn't work at all.

## Solution

Adjusted the flow to prevent recursively inheriting `Inherited` when `PropagateStop` present, as opposed to not accessing `PropagateStop` entities entirely.

Skips applying `C` when `Inherited<C>` and `PropagateOver<C>` are on the entity.

## Testing

I updated the tests first to verify the test cases. They were incomplete and didn't pass once checking for the proper end state.

After verifying those were not functioning, trimmed and adjusted code until it functioned.

## Fuller Explanation

To my understanding of the goals (and my implementation) the idea is that the result of these components would be like

```
(Propagate<C>, Inherited<C>, C)
  (Inherited<C>, C)
    (PropagateOver<C>, Inherited<C>)
      (Inherited<C>, C)
        (PropagateStop<C>, Inherited<C>, C)
```

While the previous (incorrect by my measure) appeared to be

```
(Propagate<C>, Inherited<C>, C)
  (Inherited<C>, C)
    (PropagateOver<C>, Inherited<C>, C)
      (Inherited<C>, C)
        (PropagateStop<C>)
```

So of note: The `PropagateOver<C>` is still getting `Inherited<C>` in this current adjustment. I believe it was doing that before, but I didn't fully understand the reasoning for the `Inherited<C>` at all? I guess it's to properly mark that the `C` is an inherited one, so maybe I do need to remove it on `PropagateOver<C>` as well, to ensure cleanup doesn't also remove any separately applied `C`?

I didn't look closely at what all the other tests are attempting to test (or if they are correctly testing those) to evaluate if other changes need to be made.

if `PropagateOver<C>` doesn't have `Inherited<C>` and is reparented, would it be simple to ensure that its children have their `Inherited<C>` removed/updated properly?

Looking at the code more, chances are this can be simplified a lot with the use of AncestorIter and DescendentIter, but I am not sure if jumping into a fuller refactor makes sense at this moment as opposed to attempting to fix this immediate issue and following up with a bigger refactor?

thoughts?

### CODE REVIEW

**Review by alice-i-cecile — APPROVED** [review]

**Comment by robtfm** [comment]
I actually made propagatestop include the target since sometimes you want to take it on the stopped entity, and you can always add a propagateover as well if you don’t want it on that entity. It’s hard to include the entity otherwise (you’d have to add stop to all your children). 

I’ll check the propagateover behaviour tomorrow. 

Edit to add: if we choose to keep propagating onto the stop entity I definitely agree the docs should be more explicit

**Comment by ekwoka** [comment]
Yes, I figured that was the intent, since that also makes sense to me. Unfortunately that isn't what the code was doing, which gave me some headache where I couldn't tell why this wasn't working in my project.

So this fixes that behavior.

**Comment by ekwoka** [comment]
I added more explanation to the main post to show the expected and intended behavior (as I understand it) as well as some additional comments and questions.

File: crates/bevy_app/src/propagate.rs [hunk 1]
```diff
@@ -219,18 +193,29 @@ pub fn update_reparented<C: Component + Clone + PartialEq, F: QueryFilter, R: Re
 pub fn propagate_inherited<C: Component + Clone + PartialEq, F: QueryFilter, R: Relationship>(
     mut commands: Commands,
     changed: Query<
-        (&Inherited<C>, &R::RelationshipTarget),
-        (Changed<Inherited<C>>, Without<PropagateStop<C>>, F),
```
Comment (robtfm) [inline crates/bevy_app/src/propagate.rs:223]: as far as i can see all these changes to `propagate_inherited` have no effect - in each use you're skipping processing if `maybe_stop.is_some()` which is the same as filtering the query directly? the tests also pass without these changes.

Comment (ekwoka) [reply crates/bevy_app/src/propagate.rs:223]: hmm. There could be a bit mixed up as I approached it different ways late at night.

I'll update some tests and revisit this time while the sun is out.

Comment (ekwoka) [reply crates/bevy_app/src/propagate.rs:223]: Yup, you're right, this wasn't the important part of this.

I pushed some test updates to fix some other tests that didn't test what they said and test some other behavior that I'd expect these components to have.

Will see about making these all work 👍

**Comment by ekwoka** [comment]
Updates tests with more cases and pushed some code to solve those.

It still doesn't handle some other edge cases I can think of (like multiple PropagateOver in a row when one is removed)

**Comment by robtfm** [comment]
sorry for the long delay in reviewing. i agree with all the changes you made, and the extra tests are very helpful.

i think there's still a couple of bugs: 
- if you have Propagate(1) -> Propagate(2), then you remove Propagate(2) from the child, we should end up with 1 -> 1. currently we end up with 1 -> Nothing.
- if an entity is reparented to a parent with `PropagateStop`, we still take the inherited value from the parent

i saw this by trying to simplify / think through each stage based on simpler invariants:

- an entity with `Propagate<C>` has `Inherited<C>`
- an entity without `Propagate<C>` has `Inherited<C>` if and only if it's parent has `Inherited<C>` and does not have `PropagateStop<C>`

and

- an entity with `Inherited<C>` and without `PropagateOver<C>` has `C`
- the only slightly sticky bit: an entity with `Inherited<C>` _removed_ and without `PropagateOver<C>` has `C` _removed_, but entities which are not in an `Inherited<C>` tree can still have `C`

then the scope of each function is clearer, in particular we never need to modify `C` except in `propagate_output`, and we never care about `PropagateOver<C>` except in `propagate_output` and `update_removed_limit`

i submitted a pr on your branch with changes to reflect those invariants (and a couple of extra tests) but i'll leave it up to you, i am happy to merge as is if you don't agree. we could then look at the bugs i mentioned separately.

**Comment by ekwoka** [comment]
Thanks for the help!

Yeah I was definitely getting into a realm of "wow, the edge cases with changing the tree are extensive".

**Comment by alice-i-cecile** [comment]
This caused a failed command during a state transition when respawning cameras: https://discord.com/channels/691052431525675048/692572690833473578/1447777975025008721
