### PR TITLE
Prevent TOCTOU bugs in ComponentsQueuedRegistrator

### LINKED ISSUE #20014: `ComponentsQueuedRegistrator::queue_register_component` does not ensure components are registered only once
## Bevy version

0.16.1

## What you did

```rs
#[derive(Component)]
struct A;

loop {
    let w = World::new();

    std::thread::scope(|s| {
        let c1 = s.spawn(|| w.components_queue().queue_register_component::<A>());
        let c2 = s.spawn(|| w.components_queue().queue_register_component::<A>());

        let (c1, c2) = (c1.join().unwrap(), c2.join().unwrap());
        assert_eq!(c1, c2);
    });
}
```

## What went wrong

After some iterations the `assert_eq` fails.

## Additional information

The issue is a TOCTOU bug in `queue_register_component`: it first acquires and releases a `read` lock to check if the component is registered, then forces a registration of the component if it wasn't already registered. However this ignored the possibility of another thread registering the component inbetween the check and the new registration.

### PR DESCRIPTION
**Pull request by SkiFire13**
# Objective

- Fix #20014

## Solution

- Don't make the `force_register_` family of functions always enqueue of the component/resource; instead have them check again whether it was already queued or not.

## Testing

- I added a small regression test but it's non-deterministic: if the bug is fixed it will always pass, but if the bug is presen then it has a (hopefully small) chance of passing. On my PC it failed after ~100 iterations, so hopefully 1000 is enough in CI (assuming it doesn't have single core runners...)

### CODE REVIEW

File: crates/bevy_ecs/src/component.rs [hunk 1]
```diff
@@ -1232,58 +1232,58 @@ impl<'w> ComponentsQueuedRegistrator<'w> {
...
-    /// Queues this function to run as a component registrator.
+    /// Queues this function to run as a component registrator if the given
+    /// type is not already queued as a component.
     ///
     /// # Safety
     ///
-    /// The [`TypeId`] must not already be registered or queued as a component.
-    unsafe fn force_register_arbitrary_component(
+    /// The [`TypeId`] must not already be registered as a component.
+    unsafe fn register_arbitrary_component(
```
Comment (chescock) [inline crates/bevy_ecs/src/component.rs]: Why remove `force` from the names?  They're still queuing without first checking that the components are registered, which is a kind of "forcing".  

The names `queue_register_component` and `register_arbitrary_component` don't do a great job of communicating the difference, although I suppose `force_register_arbitrary_component` wasn't much better.  

Hmm, I wonder if it would make sense to make a future PR to inline these into their callers so that we don't need two names.

Comment (SkiFire13) [reply crates/bevy_ecs/src/component.rs]: I see your point, but at the same time they are no longer really forcing the registration. They are more like `register_if_not_enqueued` or something like that, but it doesn't sound so good as a name.

File: crates/bevy_ecs/src/component.rs [hunk 2]
```diff
@@ -1232,58 +1232,58 @@ impl<'w> ComponentsQueuedRegistrator<'w> {
...
-                unsafe { QueuedRegistration::new(id, descriptor, func) },
-            );
-        id
+                unsafe { QueuedRegistration::new(self.ids.next(), descriptor, func) }
+            })
+            .id
     }
 
-    /// Queues this function to run as a resource registrator.
+    /// Queues this function to run as a resource registratorif the given
```
Comment (JaySpruce) [inline crates/bevy_ecs/src/component.rs]:
```suggestion
    /// Queues this function to run as a resource registrator if the given
```

**Review by JaySpruce — APPROVED** [review]
