### PR TITLE
normalize joint weights

### LINKED ISSUE #10447: translated skinned mesh weirdness
## Bevy version

0.12

## What you did

loaded [this](http://peer.decentraland.org/content/contents/bafybeifckjgovqokmkh22q36dy2wnfinr3oemky6zun4ci4k5o5jobub7y) skinned mesh and modified it's translation as +1x per second (nb the file needs to be renamed to `something.glb`)

## What went wrong

it mostly works, but a couple of vertices seem to only partly respect the translation.

i see the same behaviour with several other meshes so i don't think it's anything particular about this mesh. i didn't see this problem in 0.11.3.

## Additional information

https://github.com/bevyengine/bevy/assets/50659922/951cda7d-3ce4-4417-9f8f-228cfe165874

the changes i made in scene viewer:
```diff
diff --git a/examples/tools/scene_viewer/main.rs b/examples/tools/scene_viewer/main.rs
index 1f53b5f17..e15278203 100644
--- a/examples/tools/scene_viewer/main.rs
+++ b/examples/tools/scene_viewer/main.rs
@@ -20,6 +20,7 @@ mod camera_controller_plugin;
 mod morph_viewer_plugin;
 mod scene_viewer_plugin;
 
+use bevy_internal::render::view::NoFrustumCulling;
 use camera_controller_plugin::{CameraController, CameraControllerPlugin};
 use morph_viewer_plugin::MorphViewerPlugin;
 use scene_viewer_plugin::{SceneHandle, SceneViewerPlugin};
@@ -86,18 +87,19 @@ fn setup_scene_after_load(
     mut setup: Local<bool>,
     mut scene_handle: ResMut<SceneHandle>,
     asset_server: Res<AssetServer>,
-    meshes: Query<(&GlobalTransform, Option<&Aabb>), With<Handle<Mesh>>>,
+    meshes: Query<(Entity, &GlobalTransform, Option<&Aabb>), With<Handle<Mesh>>>,
 ) {
     if scene_handle.is_loaded && !*setup {
         *setup = true;
         // Find an approximate bounding box of the scene from its meshes
-        if meshes.iter().any(|(_, maybe_aabb)| maybe_aabb.is_none()) {
+        if meshes.iter().any(|(_, _, maybe_aabb)| maybe_aabb.is_none()) {
             return;
         }
 
         let mut min = Vec3A::splat(f32::MAX);
         let mut max = Vec3A::splat(f32::MIN);
-        for (transform, maybe_aabb) in &meshes {
+        for (ent, transform, maybe_aabb) in &meshes {
+            commands.entity(ent).insert(NoFrustumCulling);
             let aabb = maybe_aabb.unwrap();
             // If the Aabb had not been rotated, applying the non-uniform scale would produce the
             // correct bounds. However, it could very well be rotated and so we first convert to
diff --git a/examples/tools/scene_viewer/scene_viewer_plugin.rs b/examples/tools/scene_viewer/scene_viewer_plugin.rs
index 3a41efe06..da3cb89b5 100644
--- a/examples/tools/scene_viewer/scene_viewer_plugin.rs
+++ b/examples/tools/scene_viewer/scene_viewer_plugin.rs
@@ -78,6 +78,7 @@ impl Plugin for SceneViewerPlugin {
                     update_lights,
                     camera_tracker,
                     toggle_bounding_boxes.run_if(input_just_pressed(KeyCode::B)),
+                    move_marked,
                 ),
             );
     }
@@ -87,7 +88,18 @@ fn toggle_bounding_boxes(mut config: ResMut<GizmoConfig>) {
     config.aabb.draw_all ^= true;
 }
 
+
+#[derive(Component)]
+pub struct Marker;
+
+fn move_marked(mut q: Query<&mut Transform, With<Marker>>, time: Res<Time>) {
+    for mut t in q.iter_mut() {
+        t.translation = Vec3::X * 0f32.max(time.elapsed_seconds() - 10.0);
+    }
+}
+
 fn scene_load_check(
+    mut commands: Commands,
     asset_server: Res<AssetServer>,
     mut scenes: ResMut<Assets<Scene>>,
     gltf_assets: Res<Assets<Gltf>>,
@@ -128,8 +140,14 @@ fn scene_load_check(
                             maybe_directional_light.is_some() || maybe_point_light.is_some()
                         });
 
+                let parent = commands.spawn((SpatialBundle {
+                    // transform: Transform::from_translation(Vec3::X * 2000.0),
+                    ..Default::default()
+                },
+                Marker,)).id();
+
                 scene_handle.instance_id =
-                    Some(scene_spawner.spawn(gltf_scene_handle.clone_weak()));
+                    Some(scene_spawner.spawn_as_child(gltf_scene_handle.clone_weak(), parent));
 
                 info!("Spawning scene...");
             }
```

### PR DESCRIPTION
**Pull request by robtfm**
# Objective

allow automatic fixing of bad joint weights.
fix #10447 

## Solution

- remove automatic normalization of vertexes with all zero joint weights.
- add `Mesh::normalize_joint_weights` which fixes zero joint weights, and also ensures that all weights sum to 1. this is a manual call as it may be slow to apply to large skinned meshes, and is unnecessary if you have control over the source assets.

note: this became a more significant problem with 0.12, as weights that are close to, but not exactly 1 now seem to use `Vec3::ZERO` for the unspecified weight, where previously they used the entity translation.

### CODE REVIEW

**Review by alice-i-cecile — APPROVED** [review]

**Review by alice-i-cecile — COMMENTED** [review]
Non-blocking suggestion: could we add a check that the joint weights are normalized when running in debug mode?

**Comment by robtfm** [comment]
> Non-blocking suggestion: could we add a check that the joint weights are normalized when running in debug mode?

i can do this, but the warning becomes unavoidable ... if you load a gltf and once loaded you call `normalize_joint_weights`, then still the mesh is uploaded once to the gpu before the normalization, so the warning is still triggered.

up to you?

**Comment by alice-i-cecile** [comment]
Hmm 🤔 I think we can leave it. The real requirement here is for a general-purpose mesh-validation asset preprocessor IMO.

File: crates/bevy_render/src/mesh/mesh/mod.rs [hunk 1]
```diff
@@ -620,6 +609,28 @@ impl Mesh {
...
+
+    /// Normalize joint weights so they sum to 1.
+    pub fn normalize_joint_weights(&mut self) {
+        if let Some(joints) = self.attribute_mut(Self::ATTRIBUTE_JOINT_WEIGHT) {
+            let VertexAttributeValues::Float32x4(ref mut joints) = joints else {
+                panic!("unexpected joint weight format");
+            };
+
+            for weights in joints.iter_mut() {
+                let sum: f32 = weights.iter().sum();
```
Comment (NthTensor) [inline crates/bevy_render/src/mesh/mesh/mod.rs:621]: Would it be worth verifying the weights are positive first? If someone accidentally uses `with_inserted_attribute` with a mixture of positive and negative floats, this will do weird things.

Comment (robtfm) [reply crates/bevy_render/src/mesh/mesh/mod.rs:624]: negative weights are technically not allowed in the spec, whereas not summing to precisely 1 is allowed due to rounding issues. 

but sure, no reason not to. i arbitrarily chose to clamp negatives to zero, i guess other treatments might be better (like if all are negative, maybe you should just flip the sign?) but since we're in invalid-data territory there's probably no perfect answer. if someone wants a different treatment they can always write their own normalize function.

**Review by NthTensor — APPROVED** [review]
Nice work!
