### PR TITLE
Mitigate stack overflow on large Bundle inserts

### LINKED ISSUE #20571: Stack overflow with large-ish Bundle spawn
[##](url) Bevy version and features

Bevy main, since https://github.com/bevyengine/bevy/issues/20422 was merged in ad36585de 

Using "experimental_bevy_feathers" feature.

[stacktrace.txt](https://github.com/user-attachments/files/21767718/stacktrace.txt)

## \[Optional\] Relevant system information

Windows 11 64 bit.  Standard Rustup setup.

stable-x86_64-pc-windows-msvc
cargo 1.88.0 (873a06493 2025-05-10)
(bug still happens with cargo 1.89.0 (c24e10642 2025-06-23))

## What you did

Run the "feathers" example:

    cargo r --example feathers --features="experimental_bevy_feathers"

~~~
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.35s
     Running `target\debug\examples\feathers.exe`
2025-08-14T06:39:35.039573Z  INFO bevy_diagnostic::system_information_diagnostics_plugin::internal: SystemInfo { os: "Windows 11 Home", kernel: "26100", cpu: "AMD Ryzen 9 9900X3D 12-Core Processor", core_count: "12", memory: "61.6 GiB" }
2025-08-14T06:39:35.260736Z  INFO bevy_render::renderer: AdapterInfo { name: "AMD Radeon RX 7600", vendor: 4098, device: 29824, device_type: DiscreteGpu, driver: "AMD proprietary driver", driver_info: "25.6.1 (LLPC)", backend: Vulkan }
2025-08-14T06:39:35.500139Z  INFO bevy_render::batching::gpu_preprocessing: GPU preprocessing is fully supported on this device.
2025-08-14T06:39:35.522873Z  INFO bevy_winit::system: Creating new window feathers (0v0)

thread 'main' has overflowed its stack
error: process didn't exit successfully: `target\debug\examples\feathers.exe` (exit code: 0xc00000fd, STATUS_STACK_OVERFLOW)
~~~

I used "git bisect" to narrow down where the bug first occurs to commit ad36585deb.

## What went wrong

Expecting: a nice "Feathers" example with various widgets I can play with.
Got: a stack overflow

## Additional information

I was able to get a stack trace from the RustRover debugger, so skip my theorising if you like...  Stack trace attached, **updated** for latest commit d95313bdb8 and to remove my printlns so the line numbers are more accurate,

[stacktrace.txt](https://github.com/user-attachments/files/21767515/stacktrace.txt)

I don't think the color slider code added in this commit causes the problem, except insofar as the "impl Bundle" returned by `demo_root` has grown larger.

The problem does not occur in release mode, nor if I remove some of the nodes added in `demo_root`.  Removing either all the newly-added color sliders, or all the pre-existing widgets and leaving the color sliders intact seems to work.

My theory would be either endless function recursion, or an excessive frame size in a function call.  I am not an expert on Windows or Rust compilation, so I have mostly made progress by adding "println!" macros at various places.  The `setup` system completes but another system set to run straight afterwards never gets to run:

    ...
    app.add_systems(Startup, print_stuff.after(setup));
    ...

    fn print_stuff() {
        println!("stuff!");     // this isn't printed
    }

Adding more printing, it seems that all the individual commands are applied in `apply_or_drop_queued`, but then it's not clear if control ever returns to the caller.  Maybe some Drop code runs and that's where it all goes wrong.

### PR DESCRIPTION
**Pull request by james7132**
# Objective
Fix #20571. 

## Solution
 
 * Avoid passing the bundle by value further than one layer deep, and pass a `MovingPtr<'_, T>` of the Bundle instead.
 * Pass `MovingPtr<'_, Self>` to `DynamicBundle::get_components` and its recursive children.
 * Instead of returning an `BundleEffect`, directly apply the effect from a `MovingPtr<'_, MaybeUninit<Self>>`.
 * Remove the now unused `BundleEffect` trait.

This should avoid most if not all extra stack copies of the bundle and its components. This won't 100% fix stack overflows via bundles, but it does mitigate them until much larger bundles are used.

This started as a subset of the changes made in #20593.

## Testing
Ran `cargo r --example feathers --features="experimental_bevy_feathers"` on Windows, no stack overflow.

Co-Authored By: janis <janis@nirgendwo.xyz>

### CODE REVIEW

File: crates/bevy_ecs/src/bundle/impls.rs [hunk 1]
```diff
@@ -118,34 +128,168 @@ macro_rules! tuple_impl {
...
+    (B14, 14)
+);
+
+// all_tuples!(
+//     tuple_impl,
+//     0,
+//     15,
+//     B,
+//     INDEX
+// );
```
Comment (SkiFire13) [inline crates/bevy_ecs/src/bundle/impls.rs]: Isn't this `all_tuples_enumerated` (but with index and ident swapped)?

File: crates/bevy_ecs/src/bundle/mod.rs [hunk 2]
```diff
@@ -244,7 +244,13 @@ pub trait DynamicBundle {
...
     /// ownership of the component values to `func`.
     #[doc(hidden)]
-    fn get_components(self, func: &mut impl FnMut(StorageType, OwningPtr<'_>)) -> Self::Effect;
+    unsafe fn get_components(ptr: *const Self, func: &mut impl FnMut(StorageType, OwningPtr<'_>));
+
+    // SAFETY:
+    // - Must be called exactly once after `get_components` has been called.
+    // - `ptr` must point to a valid instance of `Self` but does not necessary need to be aligned.
+    #[doc(hidden)]
+    unsafe fn apply_effect(ptr: *const Self, entity: &mut EntityWorldMut);
```
Comment (SkiFire13) [inline crates/bevy_ecs/src/bundle/mod.rs]: I'm not very fond of the `*const Self` API TBH, it sounds very easy to misuse

Comment (SkiFire13) [inline crates/bevy_ecs/src/bundle/mod.rs]: I'm not sure how `ptr` can point to a valid instance of `Self` when calling `apply_effect`. Supposedly most of `Self` will be logicaly moved out in `get_components`, so `ptr` won't point to a valid instance of `Self` here. Rather only the bits that weren't moved out in `get_components` can reasonably still be valid.

Comment (SkiFire13) [inline crates/bevy_ecs/src/bundle/mod.rs]: Is there a reason why `ptr` can be non-aligned here, but nothing about this is stated over `get_components`? Especially considering that the `impl` for `C: Component` of `get_components` require `ptr` to be aligned in order to be sound.

I also don't see a place which can call this method with an unaligned pointer. It seems the idea was to avoid moving commands out of the `CommandQueue`, but this is not being done in PR?

File: crates/bevy_ecs/src/spawn.rs [hunk 3]
```diff
@@ -282,16 +283,26 @@ unsafe impl<R: Relationship, L: SpawnableList<R> + Send + Sync + 'static> Bundle
...
+            <R::RelationshipTarget as RelationshipTarget>::with_capacity(effect.list.size_hint());
+        let target = ManuallyDrop::new(target);
+        let target_ptr = &raw const target;
+        <R::RelationshipTarget as DynamicBundle>::get_components(target_ptr.cast::<R::RelationshipTarget>(), func);
+    }
+
+    unsafe fn apply_effect(ptr: *const Self, entity: &mut EntityWorldMut) {
+        // SAFETY: The caller must ensure that the `ptr` must be valid but not necessarily aligned.
+        let effect = unsafe { ptr.read() };
+        effect.apply(entity);
```
Comment (SkiFire13) [inline crates/bevy_ecs/src/spawn.rs]: This is unsound.

`get_components` is moving `effect.list` to a local variable and then calls a method on it. Even though it takes `&self` it can still modify the local instance by using internal mutability. If this happens then `apply_effect` will read a stale copy of `effect.list`, which should not happen.

You have to either call `size_hint` directly on the instance pointed by `ptr` (assuming it is aligned) or write back `effect.list` to `ptr` after calling `size_hint` on it. Or just don't pick an initial capacity, avoiding the need to read `effect` in `get_components` in the first place.

File: crates/bevy_ecs/src/spawn.rs [hunk 4]
```diff
@@ -311,15 +322,23 @@ impl<R: Relationship, B: Bundle> BundleEffect for SpawnOneRelated<R, B> {
...
-        self
+    ) {
+        let target = <R::RelationshipTarget as RelationshipTarget>::with_capacity(1);
+        let target = ManuallyDrop::new(target);
+        let target_ptr = &raw const target;
+        <R::RelationshipTarget as DynamicBundle>::get_components(target_ptr.cast::<R::RelationshipTarget>(), func);
+    }
+
+    unsafe fn apply_effect(ptr: *const Self, entity: &mut EntityWorldMut) {
+        // SAFETY: The caller must ensure that the `ptr` must be valid and aligned.
```
Comment (SkiFire13) [inline crates/bevy_ecs/src/spawn.rs]: This safety comment is wrong, the documentation for `apply_effect` states that `ptr` is not necessarily aligned

File: crates/bevy_ptr/src/lib.rs [hunk 5]
```diff
@@ -557,6 +569,39 @@ impl<'a, T> From<&'a [T]> for ThinSlicePtr<'a, T> {
     }
 }
 
+/// A newtype around [`NonNull`] that only allows conversion to read-only borrows or pointers.
+///
+/// This type can be thought of as the `*const T` to [`NonNull<T>`]'s `*mut T`.
+#[repr(transparent)]
+pub struct RemoteDropPtr<T: ?Sized>(ConstNonNull<T>);
```
Comment (SkiFire13) [inline crates/bevy_ptr/src/lib.rs]: This documentation looks wrong, `RemoteDropPtr` also drops the `T` it points to.

And unless I'm missing something this is unused?

**Review by SkiFire13 — COMMENTED** [review]
I quickly skimmed through the second half of the PR so something might be missing there. If this PR alone fixes the stack overflow I feel like we shouldn't deal with unaligned pointers then (see all the comments with the issues they create)

File: crates/bevy_ptr/src/lib.rs (hunk 5 above)
Comment (james7132) [reply crates/bevy_ptr/src/lib.rs]: I was making an attempt to use this to make a owned and typed version of a pointer that would drop locally in the scope where a panic occurs. That is until I ran into the need to split the pointer on the move into the ECS and the effect application. I might remove this.

File: crates/bevy_ecs/src/bundle/mod.rs (hunk 2 above)
Comment (james7132) [reply crates/bevy_ecs/src/bundle/mod.rs]: We could make a `MovingPtr<T>` that is owned, typed, potentially lifetimed (?), but unlike `Box<T>` has no allocation tied to it's lifetime, which may work not too differently from the `RemoteDropPtr` that is currently in this PR, but the need to split the pointer along field accesses and across two function calls makes those semantics difficult / impossible to work with.

File: crates/bevy_ecs/src/bundle/impls.rs (hunk 1 above)
Comment (james7132) [reply crates/bevy_ecs/src/bundle/impls.rs]: I swear I've manually implemented this so many times in the past because I keep forgetting that exists. Went ahead and replaced it.

File: crates/bevy_ecs/src/bundle/mod.rs (hunk 2 above)
Comment (james7132) [reply crates/bevy_ecs/src/bundle/mod.rs]: This is an artifact of being based on #20593. I'll go ahead and fix this comment.

File: crates/bevy_ecs/src/spawn.rs (hunk 4 above)
Comment (james7132) [reply crates/bevy_ecs/src/spawn.rs]: This is an artifact of being based on #20593. I'll go ahead and fix this comment.

File: crates/bevy_ecs/src/bundle/mod.rs (hunk 2 above)
Comment (james7132) [reply crates/bevy_ecs/src/bundle/mod.rs]: I hadn't documented this when you commented, but I added an safety invaraint on implementing `DynamicBundle` where each field must be moved out exactly once between `get_components` and `apply_effects`. It's a rather obtuse requirement, but it should be easy enough to verify within a given implementation, at least it is for our current implementations.

I updated the comment to note that not require the entire value to be valid, but explicitly mentions that items moved out of in `get_components` will no longer be valid.

File: crates/bevy_ecs/src/spawn.rs (hunk 3 above)
Comment (james7132) [reply crates/bevy_ecs/src/spawn.rs]: I've changed this to turn the pointer in `get_components` into a borrow, as it fulfills all of the requirements for one.

File: crates/bevy_ecs/src/spawn.rs [hunk 6]
```diff
@@ -282,16 +283,35 @@ unsafe impl<R: Relationship, L: SpawnableList<R> + Send + Sync + 'static> Bundle
...
+            <R::RelationshipTarget as RelationshipTarget>::with_capacity(effect.list.size_hint());
+        let mut target = ManuallyDrop::new(target);
+        let target_ptr = &raw mut target;
+        <R::RelationshipTarget as DynamicBundle>::get_components(
+            target_ptr.cast::<R::RelationshipTarget>(),
+            func,
+        );
+    }
+
+    unsafe fn apply_effect(ptr: *mut Self, entity: &mut EntityWorldMut) {
```
Comment (janis-bhm) [inline crates/bevy_ecs/src/spawn.rs]: I think this should take advantage of the ptr methods because using this, the feather example will still allocate 230kb onto the stack when the first apply_effect() is called in addition to the ~250kb already on the stack because of the copies created by the desending calls in `Commands::spawn`.

File: crates/bevy_ecs/src/world/entity_ref.rs [hunk 7]
```diff
@@ -4633,31 +4664,42 @@ unsafe fn insert_dynamic_bundle<
...
         type Effect = ();
-        fn get_components(self, func: &mut impl FnMut(StorageType, OwningPtr<'_>)) {
-            self.components.for_each(|(t, ptr)| func(t, ptr));
+        unsafe fn get_components(
+            ptr: *mut Self,
+            func: &mut impl FnMut(StorageType, OwningPtr<'_>),
+        ) {
+            // SAFETY: The caller must ensure that `ptr` is pointing to a valid instance of `Self`
+            // but does not necessarily need to be aligned.
+            let bundle = unsafe { ptr.read() };
```
Comment (SkiFire13) [inline crates/bevy_ecs/src/world/entity_ref.rs]: It seems this wasn't updated with the new guarantees given to `get_components`

File: crates/bevy_ecs/src/world/entity_ref.rs [hunk 8]
```diff
@@ -4633,31 +4664,42 @@ unsafe fn insert_dynamic_bundle<
...
-                bundle,
-                mode,
-                caller,
-                relationship_hook_insert_mode,
-            )
-            .0
+        bundle_inserter.insert(
+            entity,
+            location,
+            bundle_ptr.cast::<DynamicInsertBundle<'a, Zip<S, I>>>(),
```
Comment (SkiFire13) [inline crates/bevy_ecs/src/world/entity_ref.rs]: This cast looks very error prone. Can we somehow automatically get the type inside the `ManuallyDrop`?

File: crates/bevy_ecs/src/world/mod.rs [hunk 9]
```diff
@@ -1156,21 +1155,27 @@ impl World {
...
-        self.spawn_with_caller(bundle, MaybeLocation::caller())
+        let mut bundle = ManuallyDrop::new(bundle);
+        let bundle_ptr = &raw mut bundle;
+        // SAFETY: The bundle was passed in by value, `bundle_ptr` thus must be valid.
+        unsafe { self.spawn_with_caller(bundle_ptr.cast::<B>(), MaybeLocation::caller()) }
     }
 
-    pub(crate) fn spawn_with_caller<B: Bundle>(
+    /// #  Safety
+    /// - `bundle_ptr` thus must be pointing to a valid, but not necessarily aligned, instance of `B`
```
Comment (SkiFire13) [inline crates/bevy_ecs/src/world/mod.rs]: This seems to still reference the pointer possibly being non aligned.

File: crates/bevy_ecs/src/bundle/spawner.rs [hunk 10]
```diff
@@ -83,17 +83,22 @@ impl<'w> BundleSpawner<'w> {
 
     /// # Safety
     /// `entity` must be allocated (but non-existent), `T` must match this [`BundleInfo`]'s type
+    ///
+    /// [`apply_effect`] should be called exactly once on `bundle` after this function is
+    /// called, if `T::Effect: !NoBundleEffect.`
+    ///
```
Comment (SkiFire13) [inline crates/bevy_ecs/src/bundle/spawner.rs]: This safety comment should mention something about the validity of the `bundle` pointer.

File: crates/bevy_ecs/src/bundle/spawner.rs [hunk 11]
```diff
@@ -159,21 +164,22 @@ impl<'w> BundleSpawner<'w> {
...
-        (location, after_effect)
+        location
     }
 
     /// # Safety
     /// `T` must match this [`BundleInfo`]'s type
+    ///
+    /// [`apply_effect`] should be called exactly once on `bundle` after this function is
+    /// called, if `T::Effect: !NoBundleEffect.`
+    ///
```
Comment (SkiFire13) [inline crates/bevy_ecs/src/bundle/spawner.rs]: Same here.

File: crates/bevy_ecs/src/world/entity_ref.rs [hunk 12]
```diff
@@ -2034,13 +2034,39 @@ impl<'w> EntityWorldMut<'w> {
...
+                relationship_hook_mode,
+            )
+        };
+        self
+    }
+
+    /// Split into a new function so we can pass the calling location into the function when using
+    /// as a command.
+    #[inline]
+    pub(crate) unsafe fn insert_raw_with_caller<T: Bundle>(
```
Comment (SkiFire13) [inline crates/bevy_ecs/src/world/entity_ref.rs]: This is missing the safety requirements.

File: crates/bevy_ecs/src/world/entity_ref.rs (hunk 8 above)
Comment (janis-bhm) [reply crates/bevy_ecs/src/world/entity_ref.rs]: `MaybeUninit` has a [helper](https://doc.rust-lang.org/std/mem/union.MaybeUninit.html#method.as_mut_ptr) that does this. I think technically `MaybeUninit` is more correct here anyway because after the call to `insert` the bundle shouldn't be touched by the compiler anymore?

File: crates/bevy_ecs/src/bundle/info.rs [hunk 13]
```diff
@@ -228,8 +228,13 @@ impl BundleInfo {
     /// which removes the need to look up the [`ArchetypeAfterBundleInsert`](crate::archetype::ArchetypeAfterBundleInsert)
     /// in the archetype graph, which requires ownership of the entity's current archetype.
     ///
+    /// Regardless of how this is used, [`apply_effect`] should be called exactly once on `bundle` after this function is
```
Comment (chescock) [inline crates/bevy_ecs/src/bundle/info.rs]: It's odd for a safety requirement to say "should".  Should this say "must", or should it be a non-safety doc comment?  

Is failing to call `apply_effect` meant to be unsound, or just a safe leak like `mem::forget`?

File: crates/bevy_ecs/macros/src/lib.rs [hunk 14]
```diff
@@ -164,15 +164,30 @@ pub fn derive_bundle(input: TokenStream) -> TokenStream {
 
     let dynamic_bundle_impl = quote! {
         #[allow(deprecated)]
-        impl #impl_generics #ecs_path::bundle::DynamicBundle for #struct_name #ty_generics #where_clause {
+        // SAFETY:
+        // - Assuming each of the fields implement `DynamciBundle` correctly, each of the implementations for each of
```
Comment (viridia) [inline crates/bevy_ecs/macros/src/lib.rs]:
```suggestion
        // - Assuming each of the fields implement `DynamicBundle` correctly, each of the implementations for each of
```

File: crates/bevy_ecs/src/bundle/impls.rs [hunk 15]
```diff
@@ -118,28 +131,56 @@ macro_rules! tuple_impl {
             reason = "Zero-length tuples won't use any of the parameters."
         )]
         $(#[$meta])*
-        impl<$($name: Bundle),*> DynamicBundle for ($($name,)*) {
+        // SAFETY:
+        // Assuming each of the fields' types implement `DynamciBundle` correctly:
```
Comment (viridia) [inline crates/bevy_ecs/src/bundle/impls.rs]:
```suggestion
        // Assuming each of the fields' types implement `DynamicBundle` correctly:
```

File: crates/bevy_ecs/src/world/entity_ref.rs (hunk 8 above)
Comment (james7132) [reply crates/bevy_ecs/src/world/entity_ref.rs]: Looking at the docs there, it seems correct toe me to pass a `*mut T` into `get_components` and then a `*mut MaybeUninit<T>` into `apply_effect` as only the fields not moved out of in `get_components` still contain a value that has been properly initialized.

File: crates/bevy_ecs/src/spawn.rs [hunk 16]
```diff
@@ -59,12 +80,43 @@ impl<R: Relationship, B: Bundle<Effect: NoBundleEffect>> SpawnableList<R> for Ve
...
+
+    unsafe fn spawn_raw(this: *mut Self, world: &mut World, entity: Entity) {
+        #[track_caller]
+        unsafe fn spawn_raw<B: Bundle, R: Relationship>(
+            this: *mut Spawn<B>,
+            world: &mut World,
+            entity: Entity,
+        ) {
+            let caller = MaybeLocation::caller();
+            let mut r = MaybeUninit::new(R::from(entity));
```
Comment (janis-bhm) [inline crates/bevy_ecs/src/spawn.rs]:
```suggestion
            let mut r = MaybeUninit::new(R::from(entity));
            
            // SAFETY: 
            // - `r` is initialized and a valid bundle
            // - the caller ensures `this` is a valid pointer, so `this.0` must be a valid bundle as well
```

File: crates/bevy_ecs/src/world/entity_ref.rs [hunk 17]
```diff
@@ -2034,13 +2034,39 @@ impl<'w> EntityWorldMut<'w> {
...
+                mode,
+                caller,
+                relationship_hook_mode,
+            )
+        };
+        self
+    }
+
+    /// Split into a new function so we can pass the calling location into the function when using
+    /// as a command.
```
Comment (janis-bhm) [inline crates/bevy_ecs/src/world/entity_ref.rs]:
```suggestion
    /// as a command.
    ///
    /// # Safety
    ///
    /// `bundle` must point to a valid `T` which this function takes ownership of.
```

File: crates/bevy_ecs/src/world/entity_ref.rs (hunk 8 above)
Comment (james7132) [reply crates/bevy_ecs/src/world/entity_ref.rs]: Went ahead with the suggested `MaybeUninit<T>`.

**Comment by alice-i-cecile** [comment]
I'm curious if this improves our benchmarks, but won't block on it. Simply fixing the crash is plenty good enough.

I can't review this effectively myself BTW. I can understand the basic idea here (which is a great idea!), and why it improves performance, but this is beyond my pointer-fu skill level and the safety considerations are quite subtle.

**Comment by james7132** [comment]
> I'm curious if this improves our benchmarks, but won't block on it. Simply fixing the crash is plenty good enough.

I was asking the same question but the results I saw from this morning seems to show this is in the noise for any of our benchmarks. Probably because this all optimizes/inlines out for small enough bundles. The largest bundle we're benching with is ~512 bytes, while the bundle in the example was 30+KB in release mode. Overall I don't think we should be optimizing for those use cases as the complexity of such large entity trees are better serviced by better scene support, or large one-time constructions you only see several times over an app's lifetime.

One upside is that this makes changes like #20593 easier to implement (though equally difficult to review for soundness), which should at least yield some performance improvements for larger commands.

It was mentioned in another comment, but a typed `OwningPtr` variant that acts like a borrow exclusively made for moving owned values would really help prove soundness. Language level support for [in-place construction](https://samuka007.com/blog/05-rust-inplace-construct/), or a crate like [moveit](https://docs.rs/moveit/latest/moveit/) may also help. I tried this in this PR but making it work out well on a case where leaving only parts of a value moved out of is fairly unique, even in languages like C++ with existing in-place construction support, and thus probably out of scope for this PR.

**Comment by janis-bhm** [comment]
While the `*mut MaybeUninit<T>` in `apply_effects` looks quite ugly IMO it does communicate better that the bundle is already partially moved out.

I agree wholeheartedly that a way to track the lifetimes here, e.g. a pointer newtype, would be very nice.

Here's an idea I just had which might make things needlessly complicated:

`get_components` returns a must_use struct that encourages the effect being used/moved out so that the bundle can't be left in a half-dropped state after calling only `get_components`.
This could possibly be an `Option`, too, for `B::Effect: NoBundleEffect`
```rust
#[must_use]
unsafe fn get_components(this: *mut Self, f: &mut impl FnMut(*mut ())) -> ResidualEffect<Self>;

#[must_use]
struct ResidualEffect<B>(*mut MaybeUninit<B>);

impl<B: Bundle> ResidualEffect<B> {
    /// # Safety
    /// `bundle` must point to a partially moved bundle that is valid for use with `B::apply_effect`.
    unsafe fn new(bundle: *mut MaybeUninit<B>) -> Self {
        ResidualEffect(bundle)
    }

    /// # Safety
    /// The caller must ensure that the bundle this was created from is still live.
    unsafe fn apply_effect(self) {
        unsafe {
            <B as Bundle>::apply_effect(self.0 as *mut B);
        }
    }
}
```
in the variadic tuples or bundles which wrap other bundles like `SpawnRelatedBundle` this would have to be explicitly unused
`_ = field.get_components();`

**Review by ickshonpe — COMMENTED** [review]
This fixes the stack overflow with the feathers example on windows for me. But I'm not familiar enough with the ecs internals and unsafe rust to review the changes here otherwise.

**Comment by james7132** [comment]
> I agree wholeheartedly that a way to track the lifetimes here, e.g. a pointer newtype, would be very nice.
> 
> Here's an idea I just had which might make things needlessly complicated:
> 
> `get_components` returns a must_use struct that encourages the effect being used/moved out so that the bundle can't be left in a half-dropped state after calling only `get_components`.

Coincidentally this is very similar to the recent experimentation that is happening within the Rust Project: https://github.com/rust-lang/lang-team/issues/336#issuecomment-3049593105

**Comment by james7132** [comment]
Marking this as https://github.com/bevyengine/bevy/labels/P-Unsound as this contains a soundness fix found in #20877. `derive(Bundle)` types that implement `Drop` may access fields that have already been moved out of. This PR avoids this by just forgetting them.

File: crates/bevy_ecs/src/bundle/mod.rs (hunk 2 above)
Comment (james7132) [reply crates/bevy_ecs/src/bundle/mod.rs]: This has been implemented following #20877.

File: crates/bevy_ptr/src/lib.rs (hunk 5 above)
Comment (james7132) [reply crates/bevy_ptr/src/lib.rs]: This has been removed in favor of `MovingPtr`.

**Comment by james7132** [comment]
I've gone ahead and integrated the `MovingPtr` from #20877. It seems to be working as intended and has made quite a few of its uses safer: dropping some viral invariants and some cases no longer require any unsafe. It passes all of our current miri tests now. This required a few additions (a `MovingPtr` Deref(Mut) impl, a double Drop fix) that were not in #20877.

~~However, a number of examples, including the original example that started this investigation are now encountering some form of undefined behavior. This seems to be stemming from `MovingPtr`'s drop semantics. Commenting out the `Drop` impl seems to resolve the issues.~~

~~As this blocks the 0.17 release and isn't 100% necessary for the stack overflow mitigation, we could forgo those semantics to resolve this issue and kick reenabling the `Drop` impl at a later time, with the immediate term downside that this will cause memory leaks if a insertion triggers a component's Drop impl to panic.~~

EDIT: Found the cause of the UB and fixed it.

File: crates/bevy_ecs/src/spawn.rs [hunk 18]
```diff
@@ -59,12 +75,57 @@ impl<R: Relationship, B: Bundle<Effect: NoBundleEffect>> SpawnableList<R> for Ve
...
+                this.move_field::<B>(offset_of!(Spawn<B>, 0))
+                    .try_into()
+                    .debug_checked_unwrap()
+            };
+
+            // `this` has been moved out of, it should not be dropped.
+            mem::forget(this);
+
+            // SAFETY:
+            // - `bundle` is never accesssd or dropped after this call.
```
Comment (kristoff3r) [inline crates/bevy_ecs/src/spawn.rs]:
```suggestion
            // - `bundle` is never accessed or dropped after this call.
```

File: crates/bevy_ecs/macros/src/lib.rs [hunk 19]
```diff
@@ -163,16 +166,46 @@ pub fn derive_bundle(input: TokenStream) -> TokenStream {
     };
 
     let dynamic_bundle_impl = quote! {
-        #[allow(deprecated)]
-        impl #impl_generics #ecs_path::bundle::DynamicBundle for #struct_name #ty_generics #where_clause {
+        #[doc(hidden)]
+        #[expect(dead_code, reason = "This is a static assertion.")]
+        impl #impl_generics #struct_name #ty_generics #where_clause {
+            // Ensure that the type can be destructured and does not implement `Drop`.
```
Comment (alice-i-cecile) [inline crates/bevy_ecs/macros/src/lib.rs]: Can you explain the mechanism of how this works in a comment? I'm squinting at it but I can't piece it together.

Comment (james7132) [reply crates/bevy_ecs/macros/src/lib.rs]: You can't take ownership from individual fields if a type implements `Drop`, given that `derive(Bundle)` is entirely built on that idea this should fail to compile.

I'll add this to the comment, and we probably should have a UX compile failure test for it as well.

File: crates/bevy_ecs/src/world/entity_ref.rs [hunk 20]
```diff
@@ -2017,20 +2026,28 @@ impl<'w> EntityWorldMut<'w> {
...
-    /// Split into a new function so we can pass the calling location into the function when using
-    /// as a command.
+    /// Adds a [`Bundle`] of components to the entity.
+    ///
+    /// # Safety
+    ///  - The value `bundle` points to will moved out of and should not be accessed or
+    ///    dropped afterwards.
     #[inline]
-    pub(crate) fn insert_with_caller<T: Bundle>(
+    pub(crate) unsafe fn insert_raw_with_caller<T: Bundle>(
```
Comment (janis-bhm) [inline crates/bevy_ecs/src/world/entity_ref.rs]: Does this function have to be unsafe still? `MovingPtr` takes ownership of the value itself and handles the cleanup/dropping; that `bundle` isn't touched is implicit in this function since the `MovingPtr` is moved here and it doesn't implement copy/clone. The unsafe part happens entirely within this function (partially moving for `insert` and `apply_effect`.

Comment (james7132) [reply crates/bevy_ecs/src/world/entity_ref.rs]: That makes sense. You could, strictly speaking, call this with a value MovingPtr::new/from_value and thus still access the original value it points to (without move_as_ptr) or MovingPtr::partial_move, but the safety invariants are on their construction not on this function invocation.

I'll go ahead and make this a safe function.

File: crates/bevy_ecs/src/bundle/mod.rs [hunk 21]
```diff
@@ -233,34 +235,41 @@ pub unsafe trait BundleFromComponents {
...
-    // component being fetched.
-    //
-    /// Calls `func` on each value, in the order of this bundle's [`Component`]s. This passes
-    /// ownership of the component values to `func`.
+    // - Must be called exactly once before `apply_effect`
+    // - The `StorageType` argument passed into [`Bundle::get_components`] must be correct for the
+    //   component being fetched.
+    // - Calls `func` on each component value in the bundle, in the order of this bundle's [`Component`]s.
+    //   This passes ownership of the component values to `func`.
+    // - `apply_effect` must be called exactly once after this has been called if `Effect: !NoBundleEffect`
```
Comment (janis-bhm) [inline crates/bevy_ecs/src/bundle/mod.rs]: I still think this last bound could be expressed through a type, maybe an associated type? Though this might be bike-shedding territory or appropriate for another PR.

File: crates/bevy_ecs/src/bundle/spawner.rs [hunk 22]
```diff
@@ -86,18 +86,25 @@ impl<'w> BundleSpawner<'w> {
     }
 
     /// # Safety
-    /// `entity` must be allocated (but non-existent), `T` must match this [`BundleInfo`]'s type
+    /// - `entity` must be allocated (but non-existent),
+    /// - `T` must match this [`BundleSpawner`]'s type
+    /// - If `T::Effect: !NoBundleEffect.`, then [`apply_effect`] must  be called exactly once on `bundle`
```
Comment (janis-bhm) [inline crates/bevy_ecs/src/bundle/spawner.rs:84]: I don't think this communicates the actual requirement very well: any field not moved by `get_components` that is `Drop` has to be moved still, which canonically `apply_effect` does, but if I read this correctly, `DynamicBundle::Effect` is really only a marker now, and `NoBundleEffect` is not sealed, so there is no guarantee either way that all `T: NoBundleEffect` are `!Drop` or that some implementation of `DynamicBundle` doesn't leave behind any `Drop` fields after `get_components`. This should probably be part of the safety comment on `get_components`.

File: crates/bevy_ecs/src/bundle/spawner.rs [hunk 23]
```diff
@@ -86,18 +86,25 @@ impl<'w> BundleSpawner<'w> {
...
+    ///   after this function returns before returning to safe code.
+    /// - The value pointed to by `bundle` must not be accessed for anything other than [`apply_effect`]
+    ///   or dropped.
+    ///
+    /// [`apply_effect`]: crate::bundle::DynamicBundle::apply_effect
     #[inline]
     #[track_caller]
     pub unsafe fn spawn_non_existent<T: DynamicBundle>(
```
Comment (janis-bhm) [inline crates/bevy_ecs/src/bundle/spawner.rs:92]: I think it's a bit awkward that the `bundle` is moved into this function, yet the caller must potentially call a function on it; maybe `get_components` should return the `MovingPtr<'_, MaybeUninit<T>>` that `partial_move` currently provides?

File: crates/bevy_ecs/src/bundle/spawner.rs (hunk 22 above)
Comment (james7132) [reply crates/bevy_ecs/src/bundle/spawner.rs:84]: > so there is no guarantee either way that all T: NoBundleEffect are !Drop or that some implementation of DynamicBundle doesn't leave behind any Drop fields after get_components. 

This is the safety invariant on `DyanmicBundle` itself and must be upheld by all `DynamicBundle` implementers.

File: crates/bevy_ecs/src/bundle/mod.rs [hunk 24]
```diff
@@ -233,34 +235,41 @@ pub unsafe trait BundleFromComponents {
         Self: Sized;
 }
 
+#[expect(
```
Comment (alice-i-cecile) [inline crates/bevy_ecs/src/bundle/mod.rs]: This needs a corresponding note that manual implementations are not supported.

File: crates/bevy_ecs/src/bundle/spawner.rs (hunk 22 above)
Comment (janis-bhm) [reply crates/bevy_ecs/src/bundle/spawner.rs:84]: Ah I see. I didn't realise this isnt't a user-facing trait, either..

Comment (james7132) [reply crates/bevy_ecs/src/bundle/spawner.rs:84]: Looking back at it, it is a user facing trait, I made a mistake there. This is explicitly for non-Rust component support for bundles. That said, this change does make the trait unsafe and add a new function, so most existing implementations trivially satisfy the requirements.

File: crates/bevy_ecs/macros/src/lib.rs (hunk 19 above)
Comment (james7132) [reply crates/bevy_ecs/macros/src/lib.rs]: Updated the comment and added a UX test.

File: crates/bevy_ecs/src/bundle/mod.rs (hunk 24 above)
Comment (james7132) [reply crates/bevy_ecs/src/bundle/mod.rs]: Revisiting here, this was created for the explicit purpose of supporting non-Rust bundles and components. This needs to be manually implemented by users of the API, unfortunately. Removed the `expect` and made the safety requirements public docs.

File: crates/bevy_ecs/src/bundle/spawner.rs (hunk 23 above)
Comment (james7132) [reply crates/bevy_ecs/src/bundle/spawner.rs:92]: I took a stab at this and this did result some tangled lifetimes in `spawn_with_caller` due the borrow on `self` passed into the `BundleSpawner` being inherited by the created `MovingPtrs` conflicting with the other `self` accesses later in the function. Will try to see if it can be untangled.

File: crates/bevy_ptr/src/lib.rs [hunk 25]
```diff
@@ -517,33 +510,43 @@ impl<'a, T, A: IsAligned> MovingPtr<'_, T, A> {
...
-    ///    let partial_parent = MovingPtr::partial_move(parent_ptr, |parent_ptr| {
-    ///       bevy_ptr::deconstruct_moving_ptr!(parent_ptr, Parent {
-    ///         field_a: FieldAType => { insert(field_a) },
-    ///         field_b: FieldBType => { insert(field_b) },
-    ///       });
-    ///    });
+    /// // Converts `parent` into a `MovingPtr`
+    /// move_as_ptr!(parent);
+    ///
+    /// // SAFETY:
```
Comment (hymm) [inline crates/bevy_ptr/src/lib.rs:516]: this should no longer be a safety comment as partial_move is now safe.

File: crates/bevy_ptr/src/lib.rs [hunk 26]
```diff
@@ -1150,25 +1193,26 @@ impl<T: Sized> DebugEnsureAligned for *mut T {
...
 /// # struct FieldBType(usize);
 /// # struct FieldCType(usize);
 ///
-/// pub struct Parent {
-///   pub field_a: FieldAType,
-///   pub field_b: FieldBType,
-///   pub field_c: FieldCType,
-/// }
+/// # pub struct Parent {
+/// #   pub field_a: FieldAType,
```
Comment (hymm) [inline crates/bevy_ptr/src/lib.rs]:
```suggestion
/// #  pub field_a: FieldAType,
```

File: crates/bevy_ecs/src/world/spawn_batch.rs [hunk 27]
```diff
@@ -66,14 +68,18 @@ where
...
 
     fn next(&mut self) -> Option<Entity> {
         let bundle = self.inner.next()?;
-        // SAFETY: bundle matches spawner type
-        unsafe { Some(self.spawner.spawn(bundle, self.caller).0) }
+        move_as_ptr!(bundle);
+        // SAFETY:
+        // - The spawner matches `I::Item`'s type.
+        // - `I::Item::Effect: NoBundleEffect`, thus [`apply_effect`] does not need to be called.
+        // - `bundle` is not be accessed or dropped after this function call.
```
Comment (hymm) [inline crates/bevy_ecs/src/world/spawn_batch.rs]:
```suggestion
        // - `bundle` is not accessed or dropped after this function call.
```

File: crates/bevy_ecs/src/bundle/mod.rs [hunk 28]
```diff
@@ -234,33 +236,36 @@ pub unsafe trait BundleFromComponents {
...
+/// # Safety
+/// - Each component can only be moved out of the `Bundle` exactly once between both implementations of
+///   `get_components` and `apply_effect`.
+/// - If `Effect: NoBundleEffect`, `apply_effect` must be a no-op.
+pub unsafe trait DynamicBundle: Sized {
     /// An operation on the entity that happens _after_ inserting this bundle.
-    type Effect: BundleEffect;
+    type Effect;
+
     // SAFETY:
```
Comment (hymm) [inline crates/bevy_ecs/src/bundle/mod.rs]: nit: `get_components` and `apply_effect` could use some description of what they should do to help users who are manually implementing the trait.

File: crates/bevy_ecs/src/world/mod.rs [hunk 29]
```diff
@@ -1152,21 +1152,33 @@ impl World {
...
+        // - Between `BundleSpawner::spawn_non_existent` and `B::apply_effect`, each field of `B` will be moved exactly once into
+        //   ECS storage. This means that the bundle must be entirely moved in `spawn_non_existent` and `B::apply_effect` must be a no-op,
+        //   or forgotten inside `spawn_non_existent` and thus f valid to be moved the rest out in `B::apply_effect`.
+        // - The above also means that the fields moved out of in `spawn_non_existent` will not be accessed in `B::apply_effect`.
+        let (bundle, entity_location) = bundle.partial_move(|bundle| {
+            // SAFETY:
+            // - `B` matches `bundle_spawner`'s type
+            // -  `entity` is allocated but non-existent
+            // - `B::Effect` is unconstrained, and `B::apply_effect` is called exactly once on the bundle after this call.
+            // - The caller must ensure that the value pointed to by `bundle` must not be accessed for anything. The value
```
Comment (hymm) [inline crates/bevy_ecs/src/world/mod.rs]: if the caller is doing something to ensure safety doesn't that make `spawn_with_caller` unsafe?

File: crates/bevy_ecs/src/spawn.rs [hunk 30]
```diff
@@ -58,8 +65,39 @@ impl<R: Relationship, B: Bundle<Effect: NoBundleEffect>> SpawnableList<R> for Ve
 }
 
 impl<R: Relationship, B: Bundle> SpawnableList<R> for Spawn<B> {
-    fn spawn(self, world: &mut World, entity: Entity) {
-        world.spawn((R::from(entity), self.0));
```
Comment (hymm) [inline crates/bevy_ecs/src/spawn.rs:62]: why can't this call world spawn anymore?

Comment (james7132) [reply crates/bevy_ecs/src/spawn.rs:62]: This is to explicitly avoid reading the owned value onto the stack. The new implementation makes no such copy, albeit it does need to do a spawn and then an insert. We could get around that by making `MovingPtr<'_, T: Component>: Bundle` but that might affect our current bundle ID mappings.

Comment (janis-bhm) [reply crates/bevy_ecs/src/spawn.rs:62]: `R` is created on the stack here, `spawn_with_caller` still avoids more stack copies but `R` can be expected to be reasonably sized, so using `spawn` to spawn the `R` would likely be fine. I'm not sure what the benefit of using `spawn` over `spawn_with_caller` would be, though.

Comment (james7132) [reply crates/bevy_ecs/src/spawn.rs:62]: It's less about the stack copies but the extra archetype moves and extra bookkeeping to make that round trip. Thinking on this a bit more, this may be an explicit performance regression for these use cases. That impl mentioned above might be added in this PR.

Comment (janis-bhm) [reply crates/bevy_ecs/src/spawn.rs:62]: I think generally having pointers to bundles implement Bundle would be very useful because you could also decide to box bundles when e.g. passing them into commands in order to avoid expensive moves within the queue/commands, either as a user or within bevy. I know there's an issue or pr for `Box<dyn Bundle>: Bundle` too, which is somewhat related. Another thing I've wondered was whether the type name used for the bundle could be a trait method that default impls to the type name of `Self`, but something like `Box<B: Bundle>` would have the same type path as `B`. `C` and `(C,)` are the same archetype but not the same bundle, which I don't think has any implications other than wasting a bundle info/computation.

File: crates/bevy_ecs/macros/src/lib.rs [hunk 31]
```diff
@@ -163,16 +166,48 @@ pub fn derive_bundle(input: TokenStream) -> TokenStream {
...
-        impl #impl_generics #ecs_path::bundle::DynamicBundle for #struct_name #ty_generics #where_clause {
+        #[doc(hidden)]
+        #[expect(dead_code, reason = "This is a static assertion.")]
+        impl #impl_generics #struct_name #ty_generics #where_clause {
+            // Types that implement `Drop` cannot have their fields moved out. The implementation in
+            // `get_componments` avoids this with pointers, so there needs to be a static assertion
+            // that this is a sound thing to do. See https://doc.rust-lang.org/error_codes/E0509.html
+            // for more information.
+            fn check_no_bundle_drop(self) {
+                #( core::hint::black_box(self.#active_field_tokens); )*
```
Comment (alice-i-cecile) [inline crates/bevy_ecs/macros/src/lib.rs:179]:
```suggestion
                // This has no effect, but we need to make sure the compiler doesn't optimize it out
                // black_box is used to do this
                #( core::hint::black_box(self.#active_field_tokens); )*
```

**Comment by james7132** [comment]
> Have you run benches with the MovingPtr changes? I would still expect the changes to be in the noise, but should probably check.

I haven't run benchmarks since https://github.com/bevyengine/bevy/pull/20772#issuecomment-3232038185, but I'm fairly confident for small bundles it's still in the noise. For *very* small bundles (smaller than a pointer), this may be a unnoticeable regression since we're technically moving more on the stack in those cases, but the cost there should be dwarfed by all the metadata shuffling that insertion needs to wrangle.

One thing I should do is run a [`bevy_asm_test`](https://github.com/james7132/bevy_asm_test) check against this PR to see if it tangibly changes any of the compiler output.

File: crates/bevy_ecs/src/bundle/mod.rs (hunk 21 above)
Comment (alice-i-cecile) [reply crates/bevy_ecs/src/bundle/mod.rs]: I'd be interested in seeing that, but I'd like to avoid adding more complexity here.

File: crates/bevy_ptr/src/lib.rs (hunk 25 above)
Comment (james7132) [reply crates/bevy_ptr/src/lib.rs:516]: The `unsafe` block surrounds the inner function as it's required for `deconstruct_moving_ptr`, but the invariant needs to be updated.

File: crates/bevy_ecs/src/spawn.rs (hunk 30 above)
Comment (james7132) [reply crates/bevy_ecs/src/spawn.rs:62]: ~~So I just tried this, and it works, but we need to lift the `static requirement on `Bundle`, which I think makes sense. I'll save this for a follow-up PR.~~

Nevermind, bundles require `TypeId`, which doesn't work for non-'static bundles.

File: crates/bevy_ecs/src/world/mod.rs (hunk 29 above)
Comment (james7132) [reply crates/bevy_ecs/src/world/mod.rs]: Fixed this up.

File: crates/bevy_ptr/src/lib.rs (hunk 25 above)
Comment (james7132) [reply crates/bevy_ptr/src/lib.rs:516]: Went ahead and cleaned those up as well.

**Comment by james7132** [comment]
> One thing I should do is run a [`bevy_asm_test`](https://github.com/james7132/bevy_asm_test) check against this PR to see if it tangibly changes any of the compiler output.

I went ahead and tested this: https://github.com/james7132/bevy_asm_tests/compare/main...stack-overflow-fix. On release, opt-level 3, and fat LTO, there's very little difference. A few extra `mov` instructions are omitted but that shouldn't have a huge impact on the final output. This likely only has perf improvements in non-release builds.

File: crates/bevy_ecs/src/bundle/mod.rs [hunk 32]
```diff
@@ -234,33 +236,58 @@ pub unsafe trait BundleFromComponents {
...
-    // SAFETY:
-    // The `StorageType` argument passed into [`Bundle::get_components`] must be correct for the
-    // component being fetched.
-    //
-    /// Calls `func` on each value, in the order of this bundle's [`Component`]s. This passes
-    /// ownership of the component values to `func`.
-    #[doc(hidden)]
-    fn get_components(self, func: &mut impl FnMut(StorageType, OwningPtr<'_>)) -> Self::Effect;
-}
+    type Effect;
```
Comment (chescock) [inline crates/bevy_ecs/src/bundle/mod.rs:241]: Does it still make sense to have `Effect` as an associated type here?  It doesn't seem like it actually gets used, apart from the `NoBundleEffect` trait bound, which could be moved to `Self`.  We should certainly leave it there for now to make this change smaller, but we may want to remove it as a follow up.

File: crates/bevy_ptr/src/lib.rs [hunk 33]
```diff
@@ -1198,11 +1300,24 @@ impl<T: Sized> DebugEnsureAligned for *mut T {
...
 #[macro_export]
 macro_rules! deconstruct_moving_ptr {
-    ($ptr:ident, $self_type:tt {$($field_name:tt: $field_type:tt => $field_block:block,)*}) => {
-        $(let $field_name = $ptr.move_field::<$field_type>(core::mem::offset_of!($self_type, $field_name));)*
-        // Each field block may panic! Ensure that `parent_ptr` cannot be dropped before
-        // calling them!
+    ($ptr:ident => {$($field_name:ident,)*}) => {
+        $(let $field_name = $ptr.move_field(|f| &raw mut (*f).$field_name);)*
+        core::mem::forget($ptr);
+    };
```
Comment (chescock) [inline crates/bevy_ptr/src/lib.rs]: The only difference between these two branches is whether we use the same or different ident for the field or alias, right?  Would it make sense to combine them like 

```suggestion
    ($ptr:ident => {$($field_name:ident,)*}) => {
        $crate::deconstruct_moving_ptr!($ptr => ($($field_name => $field_name,)*))
    };
```

?

File: crates/bevy_ptr/src/lib.rs [hunk 34]
```diff
@@ -1198,11 +1300,24 @@ impl<T: Sized> DebugEnsureAligned for *mut T {
...
+    ($ptr:ident => ($($field_index:tt => $field_alias:ident,)*)) => {
+        $(let $field_alias = $ptr.move_field(|f| &raw mut (*f).$field_index);)*
+        core::mem::forget($ptr);
+    };
+    ($ptr:ident: MaybeUninit<$self_type:ident> => {$($field_name:tt: $field_type:ident,)*}) => {
```
Comment (chescock) [inline crates/bevy_ptr/src/lib.rs]: It's unfortunate that we need to specify `$self_type` and `$field_type` here.  And it doesn't look like they are actually checked in any way.  Getting the types wrong is just instant UB, right, since the offsets could be out-of-bounds?  

Would it help to create a variant of `move_field` like that works on `MaybeUninit` so that we can use type inference here?  Something like: 

```rust
impl<'a, T, A> MovingPtr<'a, MaybeUninit<T>, A> {
    pub unsafe fn move_field_maybe_uninit<U>(
        &self,
        f: impl Fn(*mut T) -> *mut U,
    ) -> MovingPtr<'a, MaybeUninit<U>, Unaligned> {
```

(And I guess then a `deconstruct_moving_ptr_maybe_uninit!` macro?)

File: crates/bevy_ecs/src/spawn.rs (hunk 30 above)
Comment (cart) [reply crates/bevy_ecs/src/spawn.rs:62]: Yeah this archetype move / redundant bookkeeping is regrettable, but so is reading B on to the stack. This points to us missing some building blocks still. `impl Bundle for MovingPtr` does make some sense.

It doesn't seem like it would _break_ our bundle id mapping logic (this case seems similar to a custom bundle with a single component vs inserting the component itself), but it could result in computing and storing redundant archetype edges. We miiiight be able to get away with somehow sharing a bundleid for `MovingPtr<B>` and `B`, but that would require some thought.

I think the real issue here is that `Bundle: 'static`, which prevents us from implementing it for `MovingPtr<'_, B>`

File: crates/bevy_ecs/src/bundle/mod.rs [hunk 35]
```diff
@@ -234,33 +236,58 @@ pub unsafe trait BundleFromComponents {
...
+    ///
+    /// For implementors:
+    ///  - Implementors of this function must convert `ptr` into pointers to individual components stored within
+    ///    `Self` and call `func` on each of them in exactly the same order as [`Bundle::get_component_ids`] and
+    ///    [`BundleFromComponents::from_components`].
+    ///  - If any part of `ptr` is to be accessed in `apply_effect`, it must *not* be dropped at any point in this
+    ///    function. Calling [`bevy_ptr::deconstruct_moving_ptr`] in this function automatically ensures this.
+    ///
+    /// [`Component`]: crate::component::Component
+    unsafe fn get_components(
```
Comment (cart) [inline crates/bevy_ecs/src/bundle/mod.rs:262]: I think it is worth leaving a note here about why we're using `MovingPtr` here, with a link to the relevant issue.

File: crates/bevy_ecs/src/bundle/mod.rs [hunk 36]
```diff
@@ -234,33 +236,58 @@ pub unsafe trait BundleFromComponents {
...
-}
+    type Effect;
+
+    /// Moves the components out of the bundle.
+    ///
+    /// # Safety
+    /// For callers:
+    /// - Must be called exactly once before `apply_effect`
+    /// - The `StorageType` argument passed into `func` must be correct for the component being fetched.
+    /// - Calls `func` on each component value in the bundle, in the order of this bundle's [`Component`]s.
```
Comment (chescock) [inline crates/bevy_ecs/src/bundle/mod.rs]: You reorganized the safety comments here, but I think  "Calls `func` on each component" was an ordinary doc comment, and doesn't seem to impose any requirement on the caller.  (The safety comments were in a `//` block and this was the `///` block.)

File: crates/bevy_ecs/macros/src/lib.rs [hunk 37]
```diff
@@ -163,16 +166,50 @@ pub fn derive_bundle(input: TokenStream) -> TokenStream {
...
-            fn get_components(
-                self,
+            unsafe fn get_components(
+                ptr: #ecs_path::ptr::MovingPtr<'_, Self>,
                 func: &mut impl FnMut(#ecs_path::component::StorageType, #ecs_path::ptr::OwningPtr<'_>)
             ) {
-                #(<#active_field_types as #ecs_path::bundle::DynamicBundle>::get_components(self.#active_field_tokens, &mut *func);)*
+                use #ecs_path::__macro_exports::DebugCheckedUnwrap;
+
+                #( let #active_field_alias = ptr.move_field(|ptr| &raw mut (*ptr).#active_field_tokens); )*
```
Comment (chescock) [inline crates/bevy_ecs/macros/src/lib.rs:193]: Is this doing the same thing as `deconstruct_moving_ptr!`?  Should we use that here?

File: crates/bevy_ecs/src/spawn.rs (hunk 30 above)
Comment (cart) [reply crates/bevy_ecs/src/spawn.rs:62]: Ah I was replying to an out-of-date version of the thread. Sorry for retreading the same ground.

Comment (cart) [reply crates/bevy_ecs/src/spawn.rs:62]: Just opened https://github.com/bevyengine/bevy/issues/20976

File: crates/bevy_ecs/src/bundle/mod.rs [hunk 38]
```diff
@@ -234,33 +236,58 @@ pub unsafe trait BundleFromComponents {
 }
 
 /// The parts from [`Bundle`] that don't require statically knowing the components of the bundle.
-pub trait DynamicBundle {
+///
+/// # Safety
+/// - Each component can only be moved out of the `Bundle` exactly once between both implementations of
+///   `get_components` and `apply_effect`.
+/// - If `Effect: NoBundleEffect`, `apply_effect` must be a no-op.
+pub unsafe trait DynamicBundle: Sized {
```
Comment (chescock) [inline crates/bevy_ecs/src/bundle/mod.rs]: I'm not sure this trait actually needs to be `unsafe`.  Any nontrivial implementation is likely to perform `unsafe` operations that will themselves need `unsafe` blocks and `SAFETY` comments, but I don't think an implementation of this trait that performs only safe operations can itself cause UB.  

That is, I *think* what these comments are saying is "don't access a field in `apply_effect` if you dropped it in `get_components`".  But `apply_effect` gets a `MovingPtr<MaybeUninit<Self>`, and it's already unsound to access a field in that without any other justification!  The justification is that the caller asserts that the pointer is the same one passed to `get_components`, and that nothing else touched that memory in between, and we know that our implementation left a valid value at that field.  So the safety checks when we read the field in `apply_effect` will be enough to ensure that we left a valid value there.

File: crates/bevy_ecs/src/query/mod.rs [hunk 39]
```diff
@@ -25,7 +25,8 @@ pub use world_query::*;
 /// debug modes if unwrapping a `None` or `Err` value in debug mode, but is
 /// equivalent to `Option::unwrap_unchecked` or `Result::unwrap_unchecked`
 /// in release mode.
-pub(crate) trait DebugCheckedUnwrap {
+#[doc(hidden)]
```
Comment (chescock) [inline crates/bevy_ecs/src/query/mod.rs:28]: This is useful enough that we may want to just include it in the docs!  Although it probably shouldn't be in `query` then, so that should be a follow-up :).

File: crates/bevy_ecs/src/spawn.rs [hunk 40]
```diff
@@ -167,10 +207,9 @@ impl<I> WithRelated<I> {
 }
 
 impl<R: Relationship, I: Iterator<Item = Entity>> SpawnableList<R> for WithRelated<I> {
-    fn spawn(self, world: &mut World, entity: Entity) {
-        world
-            .entity_mut(entity)
-            .add_related::<R>(&self.0.collect::<Vec<_>>());
+    fn spawn(this: MovingPtr<'_, Self>, world: &mut World, entity: Entity) {
+        let related = this.read().0.collect::<Vec<_>>();
```
Comment (chescock) [inline crates/bevy_ecs/src/spawn.rs]: Minor nit, but you can use `impl<I: Iterator> Iterator for &mut I` to avoid the `read()` here: 

```suggestion
    fn spawn(mut this: MovingPtr<'_, Self>, world: &mut World, entity: Entity) {
        let related = (&mut this.0).collect::<Vec<_>>();
```

File: crates/bevy_ecs/src/spawn.rs [hunk 41]
```diff
@@ -88,8 +126,8 @@ pub struct SpawnIter<I>(pub I);
 impl<R: Relationship, I: Iterator<Item = B> + Send + Sync + 'static, B: Bundle> SpawnableList<R>
     for SpawnIter<I>
 {
-    fn spawn(self, world: &mut World, entity: Entity) {
-        for bundle in self.0 {
+    fn spawn(this: MovingPtr<'_, Self>, world: &mut World, entity: Entity) {
+        for bundle in this.read().0 {
```
Comment (chescock) [inline crates/bevy_ecs/src/spawn.rs]: ... and here: 

```suggestion
    fn spawn(mut this: MovingPtr<'_, Self>, world: &mut World, entity: Entity) {
        for bundle in &mut this.0 {
```

File: crates/bevy_ecs/src/world/entity_ref.rs [hunk 42]
```diff
@@ -2036,21 +2037,31 @@ impl<'w> EntityWorldMut<'w> {
...
+        // SAFETY:
+        // - `location` matches current entity and thus must currently exist in the source
+        //   archetype for this inserter and its location within the archetype.
+        // - `T` matches the type used to create the `BundleInserter`.
+        // - `apply_effect` is called exactly once after this function.
+        // - The value pointed at by `bundle` is not accessed for anything other than `apply_effect`
+        //   and the caller ensures that the value is not accessed or dropped after this function
+        //   returns.
+        let (bundle, location) = bundle.partial_move(|bundle| unsafe {
+            bundle_inserter.insert::<T>(
```
Comment (chescock) [inline crates/bevy_ecs/src/world/entity_ref.rs]: `T` can still be inferred here, right?  

```suggestion
            bundle_inserter.insert(
```

(And similarly for the four `cache.inserter.insert::<B>` calls.)

File: crates/bevy_ecs/src/world/entity_ref.rs [hunk 43]
```diff
@@ -4620,31 +4632,49 @@ unsafe fn insert_dynamic_bundle<
...
     {
         type Effect = ();
-        fn get_components(self, func: &mut impl FnMut(StorageType, OwningPtr<'_>)) {
-            self.components.for_each(|(t, ptr)| func(t, ptr));
+        unsafe fn get_components(
+            ptr: MovingPtr<'_, Self>,
+            func: &mut impl FnMut(StorageType, OwningPtr<'_>),
+        ) {
+            let bundle = ptr.read();
+            bundle.components.for_each(|(t, ptr)| func(t, ptr));
```
Comment (chescock) [inline crates/bevy_ecs/src/world/entity_ref.rs]: ... and here: 

```suggestion
            mut ptr: MovingPtr<'_, Self>,
            func: &mut impl FnMut(StorageType, OwningPtr<'_>),
        ) {
            (&mut ptr.components).for_each(|(t, ptr)| func(t, ptr));
```

File: crates/bevy_ecs/src/world/spawn_batch.rs [hunk 44]
```diff
@@ -13,7 +15,7 @@ use core::iter::FusedIterator;
 pub struct SpawnBatchIter<'w, I>
 where
     I: Iterator,
-    I::Item: Bundle,
+    I::Item: Bundle<Effect: NoBundleEffect>,
```
Comment (chescock) [inline crates/bevy_ecs/src/world/spawn_batch.rs:18]: These constraints are a bug fix, because previously the code allowed bundles with effects but ignored the effects, right?

File: crates/bevy_ptr/src/lib.rs [hunk 45]
```diff
@@ -470,6 +465,8 @@ impl<'a, T> MovingPtr<'a, T, Aligned> {
 impl<'a, T, A: IsAligned> MovingPtr<'_, T, A> {
```
Comment (chescock) [inline crates/bevy_ptr/src/lib.rs]: Don't you need to use the `'a` lifetime here?  Otherwise it seems like `move_field` gives an unbound lifetime in the return value.  

```suggestion
impl<'a, T, A: IsAligned> MovingPtr<'a, T, A> {
```

File: crates/bevy_ecs/src/bundle/mod.rs (hunk 35 above)
Comment (james7132) [reply crates/bevy_ecs/src/bundle/mod.rs:262]: Added a few non-doc comments to the trait functions where it's relevant.

File: crates/bevy_ecs/src/world/entity_ref.rs (hunk 42 above)
Comment (james7132) [reply crates/bevy_ecs/src/world/entity_ref.rs]: This was explicitly added when we were still using `*mut T` in this PR before MovingPtr was introduced. I'll go ahead revert those changes.

File: crates/bevy_ecs/src/world/spawn_batch.rs (hunk 44 above)
Comment (james7132) [reply crates/bevy_ecs/src/world/spawn_batch.rs:18]: From a user-facing perspective, no, since this type isn't public and we only used it in spaces where that invariant held anyway, but from the perspective easily provable safety invariants, yes.

File: crates/bevy_ptr/src/lib.rs (hunk 45 above)
Comment (james7132) [reply crates/bevy_ptr/src/lib.rs]: Really good catch! I swear these lifetimes can be easy to miss.

File: crates/bevy_ecs/src/bundle/mod.rs (hunk 32 above)
Comment (james7132) [reply crates/bevy_ecs/src/bundle/mod.rs:241]: Yep, this is borderline vestigial at this point, but those generic constraints are required for user facing APIs for now. @janis-bhm comment in the same PR notes we should probably keep something like it and return it from `get_components` instead of using `partial_move` where we're doing it now, but I ran into a few lifetime tangles along the way trying to implement that. I'll file a separate issue to address this at a later point.

File: crates/bevy_ecs/src/spawn.rs (hunk 40 above)
Comment (james7132) [reply crates/bevy_ecs/src/spawn.rs]: This eventually will have to be reverted for #20593, but I agree this looks better for now.

File: crates/bevy_ecs/src/query/mod.rs (hunk 39 above)
Comment (james7132) [reply crates/bevy_ecs/src/query/mod.rs:28]: I would actually rather this stay as an internal tool. This is purely exported for the Bundle derive macro. There are other crates like `debug_unwraps` that already provide this elsewhere. With #20593, I intend to make this private again.

File: crates/bevy_ecs/src/bundle/info.rs (hunk 13 above)
Comment (james7132) [reply crates/bevy_ecs/src/bundle/info.rs]: You're right. I changed it to say "must" instead of should, but it's a "at most once before returning to user-space safe code".

File: crates/bevy_ecs/macros/src/lib.rs (hunk 37 above)
Comment (james7132) [reply crates/bevy_ecs/macros/src/lib.rs:193]: The macro isn't quite flexible enough to support both normal structts and tuple structs, hence why there's the usage of `active_field_alias`. I'd love to use it here, but lack the flexibility right now with that macro.

File: crates/bevy_ecs/src/bundle/mod.rs (hunk 36 above)
Comment (james7132) [reply crates/bevy_ecs/src/bundle/mod.rs]: Done!

File: crates/bevy_ecs/src/bundle/mod.rs (hunk 38 above)
Comment (james7132) [reply crates/bevy_ecs/src/bundle/mod.rs]: Makes sense to me. Fixed this up and tidied up all of the safety invariant tied to it.

File: crates/bevy_ptr/src/lib.rs (hunk 34 above)
Comment (james7132) [reply crates/bevy_ptr/src/lib.rs]: Man I **really** wish we had better language level support for field projection. This split is so ass.

Went ahead and made the changes you suggested.
