### PR TITLE
Fix: Update the `ExtractedView` & `Frustum` when the `ExtractedPointLight` has changed

### LINKED ISSUE #23997: Example spotlight and rect_light render incorrectly
## Bevy version and features

main

## \[Optional\] Relevant system information

Linux & macOS, windows is too broken by other issues to confirm

## What you did

Run the examples

## What went wrong

Image

Image

### PR DESCRIPTION
**Pull request by kfc35**
# Objective

- Fixes #23997 for `spotlight` (`rect_light` fixed with #24024 already)
- The spotlight example changes the transform of each spotlight, but the `ExtractedView` and the `Frustum` for the spotlight never updates, hence why the light doesn’t look complete for subsequent frames.

## Solution

- For Spot lights (and Point lights since those were also affected), update the `ExtractedView` and the `Frustum` if its corresponding `ExtractedPointLight` has changed.
- AFAIK this isn’t needed for Directional lights because `ExtractedView`s aren’t re-used — they’re made anew in `prepare_lights`

## Testing

- `cargo run --example spotlight` works as desired.
- `cargo run --example async_channel_pattern` works as desired (for PointLight testing)
- @Zeophlite assist with the example runner (was done before the frusta change though)

### CODE REVIEW

File: crates/bevy_pbr/src/lib.rs [hunk 1]
```diff
@@ -439,7 +439,7 @@ impl Plugin for PbrPlugin {
                 shared_shadow_pass::<EARLY_SHADOW_PASS>
                     .after(early_prepass_build_indirect_parameters)
                     .before(early_downsample_depth)
-                    .before(per_view_shadow_pass::<LATE_SHADOW_PASS>),
+                    .before(shared_shadow_pass::<LATE_SHADOW_PASS>),
```
Comment (kfc35) [inline crates/bevy_pbr/src/lib.rs:442]: this seemed like an oversight that I spotted so I just added this, it’s unrelated to the fix. I can remove this if desired but it’s small so I felt OK sneaking it in

**Comment by kfc35** [comment]
Thanks @Zeophlite for the assist with the example runner!

I inspected those results and learned that the frusta need to be included in the components to update, so I included those as well in the most recent commit. I also learned that the `async_channel_pattern` is a great example to observe a transforming `PointLight`.

Now, the `async_channel_pattern` example looks as it should from before the “render spot and point lights once” change. The shadows actually stick to the boxes as the lights rotate around and they don’t disappear weirdly. I’ve got more confidence that this is the right fix.

**Review by Zeophlite — APPROVED** [review]

**Review by alice-i-cecile — APPROVED** [review]
