### PR TITLE
Raise compile error when using non-static lifetimes in `#[derive(Resource)]`

### LINKED ISSUE #20413: `#[derive(Resource)]` doesn't give error despite lifetime issues
## Bevy version

`bevy_ecs` v0.16.1

## What you did

I was trying to store WGPU-related structs in an ECS resource:
```rust
#[derive(Resource)]
pub struct WgpuResource<
    #[expect(single_use_lifetimes, reason = "Deriving from Resource causes this.")]
    #[expect(redundant_lifetimes, reason = "Deriving from Resource causes this.")]
    'window> {
    pub surface: Surface<'window>,
    pub surface_config: SurfaceConfiguration,
    pub window: Arc<Window>,
    pub device: Device,
```

This compiles fine, but later I realized that I couldn't write `ResMut<WgpuResource>` to access the resource, because `ResMut<T>` requires that `T` is a `Resource`, which must be `'static`. If `Resource` must be `'static`, then why didn't it error out when I `derive`d it? I tried expanding the macro and found that this is what it expanded to:
```rust
impl<
    #[expect(single_use_lifetimes, reason = "Deriving from Resource causes this.")]
    #[expect(redundant_lifetimes, reason = "Deriving from Resource causes this.")] 'window,
> bevy_ecs::resource::Resource for WgpuResource<'window>
where
    Self: Send + Sync + 'static,
{
}
```

Because of the `where` clause, this `impl` is skipped for `WgpuResource` because it isn't `'static`. If I remove the `where` clause, then it correctly tells me that the lifetime bound isn't satisfied.

## What went wrong

I expected that the macro wouldn't add that `where` clause, so the user can see the problem sooner.

### PR DESCRIPTION
**Pull request by VasanthakumarV**
# Objective

Fixes #20413 

Adding non-static lifetimes to `#[derive(Resource)]` should not compile.

## Solution

Added a check in the derive macro of `Resource` to ensure all lifetime generics are bound to 'static, if not it raises an error.

## Testing

Added a ui-test for compile error.

### CODE REVIEW

**Review by alice-i-cecile — APPROVED** [review]

**Comment by hukasu** [comment]
is `Resources as components` in the 0.18 todo list? if so, would this be needed?

**Comment by alice-i-cecile** [comment]
Still required: the derive isn't going anywhere.

File: crates/bevy_ecs/compile_fail/tests/ui/resource_derive.rs [hunk 1]
```diff
@@ -0,0 +1,12 @@
...
+
+#[derive(Resource)]
+//~v ERROR: Lifetimes must be 'static
+struct A<'a> {
+    foo: &'a str,
+}
+
+#[derive(Resource)]
+struct B<'a: 'static> {
+    foo: &'a str,
```
Comment (chescock) [inline crates/bevy_ecs/compile_fail/tests/ui/resource_derive.rs:11]: Is there any reason for a lifetime parameter with a `'static` bound?  Wouldn't this be equivalent to

```suggestion
struct B {
    foo: &'static str,
```

?

It might be more clear to simply error on *any* lifetime parameters, without checking their bounds.  The error message could be something like "Resources cannot have lifetime parameters, as they must be `'static`".

File: crates/bevy_ecs/macros/src/component.rs [hunk 2]
```diff
@@ -17,6 +17,21 @@ pub fn derive_resource(input: TokenStream) -> TokenStream {
     let mut ast = parse_macro_input!(input as DeriveInput);
     let bevy_ecs_path: Path = crate::bevy_ecs_path();
 
+    // We want to raise a compile time error when the generic lifetimes
+    // are not bound to 'static lifetime
+    let non_static_lifetime_error: Option<syn::Error> = ast
```
Comment (chescock) [inline crates/bevy_ecs/macros/src/component.rs]: I think this type can be inferred:

```suggestion
    let non_static_lifetime_error = ast
```

File: crates/bevy_ecs/compile_fail/tests/ui/resource_derive.rs (hunk 1 above)
Comment (VasanthakumarV) [reply crates/bevy_ecs/compile_fail/tests/ui/resource_derive.rs:11]: Raising an error on any lifetime parameter will definitely be simpler.

Since `'a: 'static` is valid, I thought I will check the bounds and added an ui-test following this pattern to make it obvious that we cover such cases.

I can definitely remove the lifetime bound checks, if that is the consensus.

**Comment by VasanthakumarV** [comment]
Hi @chescock,

> Note that this will prevent creating types that exist for all lifetimes but only `impl Resource` for `'static`. I think that's acceptable, since users can always create a wrapper type to use as a resource. It is technically a breaking change, though, so this might need a migration guide.

Can you help me understand the valid cases that will fail because of the changes in this PR?

Your response will help me improve the changes, and draft the migration guide.

**Review by chescock — APPROVED** [review]

File: crates/bevy_ecs/compile_fail/tests/ui/resource_derive.rs (hunk 1 above)
Comment (chescock) [reply crates/bevy_ecs/compile_fail/tests/ui/resource_derive.rs:11]: I'd vote for the simpler version, but it's not a big deal and I won't block on it.  Mostly I think it could make the error message more clear, since we could tell the user to remove the parameters.  (Although I suppose a middle ground would be to have the error message say that lifetime parameters aren't allowed, but then still accept parameters bounded by `'static`.)

**Comment by alice-i-cecile** [comment]
> Can you help me understand the valid cases that will fail because of the changes in this PR?

IMO there are no realistic reasons why one might do this, so I'm going ahead and merging this as is :)
