### PR TITLE
Fix embedded asset path manipulation

### LINKED ISSUE #10377: `embedded_asset!` panics on `unwrap` during path manipulation
## Bevy version

0.12.0

## What you did

```rust
pub struct TriplanarMaterialPlugin;

impl Plugin for TriplanarMaterialPlugin {
    fn build(&self, app: &mut App) {
        app.add_plugins(MaterialPlugin::<TriplanarMaterial>::default());

        embedded_asset!(app, "shaders/triplanar.wgsl");
        embedded_asset!(app, "shaders/biplanar.wgsl");
    }
}
```

## What went wrong

```
thread 'main' panicked at src/plugin.rs:11:9:
called `Option::unwrap()` on a `None` value
```

### Root Cause

I believe the root cause it trying to split a path string by "/src/" when the path does not even contain that substring.

Here's the implementation:

```rust
macro_rules! embedded_path {
    ($path_str: expr) => {{
        embedded_path!("/src/", $path_str)
    }};

    ($source_path: expr, $path_str: expr) => {{
        let crate_name = module_path!().split(':').next().unwrap();
        let after_src = file!().split($source_path).nth(1).unwrap();
        let file_path = std::path::Path::new(after_src)
            .parent()
            .unwrap()
            .join($path_str);
        std::path::Path::new(crate_name).join(file_path)
    }};
}
```

This line is where the panic happens:

```rust
        let after_src = file!().split($source_path).nth(1).unwrap();
```

The issue is `$source_path = "/src/"` while `file!() = "src/plugin.rs"`. Splitting will produce only one element from the iterator, so `nth(1)` will be `None`.

### Solution

Generally it's a bad idea to do path manipulation with raw strings when you could use `Path` or `PathBuf` instead, and I recommend eliminating any use of "/" (it's not portable), e.g. in `"/src/"`. So my suggested solution is to convert strings into `PathBuf` as soon as possible and do manipulation after that.

### PR DESCRIPTION
**Pull request by bonsairobo**
# Objective

Fixes #10377

## Solution

Use `Path::strip_prefix` instead of `str::split`. Avoid any explicit "/" characters in path manipulation.

---

## Changelog

- Added: example of embedded asset loading
- Added: support embedded assets in external crates
- Fixed: resolution of embedded assets
- Fixed: unexpected runtime panic during asset path resolution

## Migration Guide

No API changes.

### CODE REVIEW

**Comment by bonsairobo** [comment]
After submitting [this issue][std_file_issue] for `std::file`, I'm wondering if embedded assets will work if the crate is being used as a crates.io dependency. For context:

> If you pass src/lib.rs to rustc as filename and you have a module foo at src/foo.rs, then file!() will return src/foo.rs when invoked inside that module. If you pass /path/to/lib.rs then it will return /path/to/foo.rs when invoked inside the foo module.

I think this means you might try to do this in `src/plugin.rs`:

```rust
embedded_asset!(app, "my_asset.png");

...

let asset = server.load("embedded://my_crate/my_asset.png");
```

And `rustc` is invoked with the source file path as an absolute path `/path/to/crates/my_crate/src/lib.rs`, so the path returned from `file!()` is `/path/to/crates/my_crate/src/plugin.rs`. This wouldn't have a predictable `src/` prefix, so the macro would panic.

I think this is a case where the old behavior could have worked properly (not on Windows).

We might want to add a condition that checks if the `file!()` output is an absolute path.

It might be challenging to test this :sweat: . 

[std_file_issue]: https://github.com/rust-lang/rust/issues/117605#issuecomment-1793839641

**Comment by bonsairobo** [comment]
I've addressed the external crate issue. I was able to test this by creating a git repo with a crate that embeds an asset, loads it, and spawns it. Then I made another local crate that depends on this git repo and adds the plugin. As anticipated, it would fail to load the asset without the 09f2b91 fix. The fix... fixes it.

**Comment by bonsairobo** [comment]
CI failure looks unrelated to my revisions.

**Comment by alice-i-cecile** [comment]
@viridia could I get your review here?

**Comment by viridia** [comment]
> @viridia could I get your review here?

So I guess I'm being brought into this because of the prior discussion about wanting to remove the use of `Path` and `PathBuf` from `AssetPath` and creating our own implementation which will be platform-agnostic. While this PR kind of moves us in the opposite direction (adding another dependency on `Path`), I'm not too concerned about that. As long as there are tests which ensure that the behavior is correct, I'm not worried about replacing the logic later.

As far as the rest, I'm not familiar enough with the details of embedded assets to give a useful opinion. I guess I would ask whether this logic is something that belongs in `AssetPath`?

**Comment by bonsairobo** [comment]
> wanting to remove the use of Path and PathBuf from AssetPath and creating our own implementation which will be platform-agnostic

I'm surprised by this. Isn't the whole point of `std::path` to be platform-agnostic?

**Comment by viridia** [comment]
> I'm surprised by this. Isn't the whole point of `std::path` to be platform-agnostic?

@bonsairobo The problem is that `AssetPaths` aren't really paths - they are URLs. They eventually get converted into filesystem paths (depending on the asset source), but the rules for manipulating and combining asset paths are subtly different than the rules for filesystem paths. `Path` and `PathBuf` understand backslashes and recognize windows drive letters as absolute paths. We actually don't want asset paths to have those behaviors - an asset path which starts with a windows drive letter is meaningless to Bevy.

**Comment by bonsairobo** [comment]
@viridia OK sounds like `AssetPath` is trying to be some pseudo-`Url` such that the `url` crate is presumably not the right abstraction. I'm still coming up to speed on this design, could you share any links to discussions about that?

RE: This PR. Anything we get from `std::file!()` needs to be parsed as an OS-specific path string, which `Path` does for us. I don't think we should try to re-invent this wheel. It makes sense to me that `AssetPath` has a `from_path` method for whenever a local file path needs to be registered with the asset system. I don't know exactly where this boundary should be, but I think as long as we're parsing raw `str`s (or `OsStr`s) that represent OS-specific file paths, we should use `Path`.

**Comment by viridia** [comment]
Sorry for not responding sooner, dealing with some health issues. The latest discussion is #10511.

File: examples/asset/embedded.rs [hunk 1]
```diff
@@ -0,0 +1,53 @@
...
+        // include_bytes! works.
+        embedded_asset!(app, omit_prefix, "bevy_pixel_light.png");
+    }
+}
+
+fn setup(mut commands: Commands, asset_server: Res<AssetServer>) {
+    commands.spawn(Camera2dBundle::default());
+
+    // Each example is its own crate (with name from [[example]] in Cargo.toml).
+    let crate_name = "embedded_asset";
```
Comment (mockersf) [inline examples/asset/embedded.rs:31]: could the examples .rs file be renamed to use the same name?

**Comment by mcobzarenco** [comment]
Is there a workaround in the meantime? I've switched back to `load_internal_asset!` as I couldn't find any directory structure permutation for my shaders that would not cause this bug

**Comment by doonv** [comment]
> Is there a workaround in the meantime?

@mcobzarenco  You can try replacing `embedded_asset!(app, "my_shader.wgsl");` with `embedded_asset!(app, "src/", "toon_shader.wgsl");`. That fixed it for me.

**Comment by alice-i-cecile** [comment]
@shanecelis @doonv could I get a review on this from one or both of you? I'd like to unblock the linked PR.

File: crates/bevy_asset/src/io/embedded/mod.rs [hunk 2]
```diff
@@ -104,20 +104,48 @@ impl EmbeddedAssetRegistry {
...
+    let after_src = loop {
+        let Some(parent) = maybe_parent else {
+            panic!("Failed to find src_prefix {src_prefix:?} in {file_path:?}")
+        };
+        if parent.ends_with(src_prefix) {
+            break file_path.strip_prefix(parent).unwrap();
+        }
+        maybe_parent = parent.parent();
+    };
+    let asset_path = after_src.parent().unwrap().join(asset_path);
```
Comment (doonv) [inline crates/bevy_asset/src/io/embedded/mod.rs:145]: Why are you getting `after_src`'s parent?

**Review by doonv — COMMENTED** [review]
I'm not really a fan of the "double path" thing where you have to first have the path inside the `embedded_asset!` macro, and then the path every time you want to access the asset.

I'd rather have something more similar to what we had earlier with `load_internal_asset!`. Where you stored the handle in a `static` variable.

File: crates/bevy_asset/src/io/embedded/mod.rs [hunk 3]
```diff
@@ -104,20 +104,48 @@ impl EmbeddedAssetRegistry {
...
+///
+/// Returns an embedded asset path, given:
+///   - `crate_name`: name of the crate where the asset is embedded
+///   - `src_prefix`: path prefix of the crate's source directory, relative to the workspace root
+///   - `file_path`: `std::file!()` path of the source file where `embedded_path!` is called
+///   - `asset_path`: path of the embedded asset relative to `file_path`
+#[doc(hidden)]
+pub fn _embedded_asset_path(
+    crate_name: &str,
+    src_prefix: &Path,
```
[the remark this answers is not in the document]
Comment (bonsairobo) [reply crates/bevy_asset/src/io/embedded/mod.rs:131]: I'm not sure I know what you're implying. But you can't unambiguously specify the source directory of a crate with only the name of the directory. For example, if you have both `foo/src` and `bar/src` in your workspace.

File: crates/bevy_asset/src/io/embedded/mod.rs (hunk 2 above)
Comment (bonsairobo) [reply crates/bevy_asset/src/io/embedded/mod.rs:145]: Because `after_src` refers to a source file path (where the macro was invoked). We want to get the path to the directory where it lives, which is what `parent()` does.

**Comment by bonsairobo** [comment]
@doonv 

> I'm not really a fan of the "double path" thing where you have to first have the path inside the `embedded_asset!` macro, and then the path every time you want to access the asset.
> 
> I'd rather have something more similar to what we had earlier with `load_internal_asset!`. Where you stored the handle in a `static` variable.

I think that's out of scope for this PR, which is not changing the public API.

**Comment by shanecelis** [comment]
@doonv Re: Handle vs double path 

I've converted some code from using `load_internal_asset!()` to `embedded_asset!()` and there was a benefit I noted using a path with `embedded_asset!()`. For instance I had this code from [kayak_ui](https://github.com/StarArawn/kayak_ui/blob/main/examples/custom_shader.rs):

```
#[derive(AsBindGroup, Asset, TypePath, Debug, Clone)]
pub struct MyUIMaterial {}
impl MaterialUI for MyUIMaterial {
    fn fragment_shader() -> bevy::render::render_resource::ShaderRef {
        "rainbow_shader.wgsl".into()
    }
}
```

Now [kayak_ui's module](https://github.com/StarArawn/kayak_ui/blob/main/src/render/unified/mod.rs) that has the handles to its shaders as `pub const`, so they're accessible and useable in the trait above. But what if you wanted to dynamically load an asset? You can get the `Handle<Shader>` but where would you put it? In the scenario above `fragment_shader()` doesn't use a `&self`, so you'd need to access some other way, and forgive me but I don't really know a way other than static mut, which seems bad. With the `embedded_asset!()` you can do something that is nearly the same:

```
#[derive(AsBindGroup, Asset, TypePath, Debug, Clone)]
pub struct MyUIMaterial {}
impl MaterialUI for MyUIMaterial {
    fn fragment_shader() -> bevy::render::render_resource::ShaderRef {
        "embedded://custom_shader/rainbow_shader_embed.wgsl".into()
    }
}
```

I thought that was a win for `embedded_asset!()` compared to `load_internal_asset!()`. I also like the assets in general are accessible to the user, without the original provider ensuring that you have access to the handles. However, the double-path issue is real; in fact, you might even call it triple-path.

But I agree the many paths—a file system source path, an asset-path, an embedded://crate-name/asset-path—is confusing, especially at first. One thing I would really like is if `embedded_asset!()` or a variant would return the string that it constructs as the asset's key, e.g., "embedded://crate-name/asset-path". That way a user could add `dbg!(embedded_asset!(...))` if they're running into trouble to see what URI their asset is being keyed to.

File: crates/bevy_asset/src/io/embedded/mod.rs [hunk 4]
```diff
@@ -104,20 +104,48 @@ impl EmbeddedAssetRegistry {
 #[macro_export]
 macro_rules! embedded_path {
     ($path_str: expr) => {{
-        embedded_path!("/src/", $path_str)
+        embedded_path!("src", $path_str)
     }};
 
     ($source_path: expr, $path_str: expr) => {{
         let crate_name = module_path!().split(':').next().unwrap();
```
Comment (shanecelis) [inline crates/bevy_asset/src/io/embedded/mod.rs:111]: While we're here in #11340, I added some code in case this fails. Perhaps it's too defensive if we're certain `module_path!()` will always have a ':' in it. But here it is for your consideration:

```
        let Some(crate_name) = module_path!().split(':').next() else {
            panic!(
                "Could not find crate name. Expected ':' in module path `{}`",
                module_path!()
            );
        };
```

**Comment by shanecelis** [comment]
I added some more tests in a PR https://github.com/bonsairobo/bevy/pull/1 to this PR to exercise its behavior on error conditions. I never provoked an unwrap() None error, so I'm happy with that. And I prefer this to my own PR #11340 which merely reports errors. This PR interrogates the paths as `Path`s, which should alleviate some cross platform woes.

File: crates/bevy_asset/src/io/embedded/mod.rs (hunk 4 above)
Comment (bonsairobo) [reply crates/bevy_asset/src/io/embedded/mod.rs:111]: If the `unwrap` somehow managed to panic, it would be a bug in the compiler (`module_path!` is a compiler built-in), not something the user would be able to fix. So I don't think it's worth adding this message.

File: crates/bevy_asset/src/io/embedded/mod.rs (hunk 3 above)
[the remark this answers is not in the document]
Comment (doonv) [reply crates/bevy_asset/src/io/embedded/mod.rs:131]: src_prefix implies "The prefix of the src folder name". I assume what you actually meant was "The path to the src folder", is that correct?

File: crates/bevy_asset/src/io/embedded/mod.rs (hunk 2 above)
Comment (doonv) [reply crates/bevy_asset/src/io/embedded/mod.rs:145]: Ah ok

File: crates/bevy_asset/src/io/embedded/mod.rs [hunk 5]
```diff
@@ -104,20 +104,48 @@ impl EmbeddedAssetRegistry {
...
+    let mut maybe_parent = file_path.parent();
+    let after_src = loop {
+        let Some(parent) = maybe_parent else {
+            panic!("Failed to find src_prefix {src_prefix:?} in {file_path:?}")
+        };
+        if parent.ends_with(src_prefix) {
+            break file_path.strip_prefix(parent).unwrap();
+        }
+        maybe_parent = parent.parent();
+    };
```
Comment (doonv) [inline crates/bevy_asset/src/io/embedded/mod.rs:144]: Couldn't the loop be replaced with this?
```suggestion
    let after_src = file_path.strip_prefix(src_prefix) else {
        panic!("Failed to find src_prefix {src_prefix:?} in {file_path:?}")
    };
```
This works because `file!()` always returns the directory relative to the MANIFEST_DIR.

Comment (bonsairobo) [reply crates/bevy_asset/src/io/embedded/mod.rs:144]: No. That will fail the unit test `embedded_asset_path_from_external_crate`.

> This works because file!() always returns the directory relative to the MANIFEST_DIR.

That's only true when `cargo` is building a local crate. External crates (like those from git or crates.io dependencies) will give an absolute path.

**Comment by ryanpeach** [comment]
Is this going into the next release?

**Comment by alice-i-cecile** [comment]
Unlikely: it needs two community approvals before it can merged by maintainers. If this interests you, please feel free to leave a code review!

**Comment by bonsairobo** [comment]
> Unlikely: it needs two community approvals before it can merged by maintainers. If this interests you, please feel free to leave a code review!

I wasn't aware of this process. Is there anything blocking approval by @doonv and @shanecelis?

**Comment by shanecelis** [comment]
No, nothing blocking. I’ll be happy to approve. I added some tests and exercised it. It’d be nice for this to make it in. I don’t see the approve button here on mobile. Will search for it on my computer shortly.

**Comment by alice-i-cecile** [comment]
Go to the "Files changed" tab, then "Review changes", then "Approve" :)

**Review by shanecelis — APPROVED** [review]

**Comment by shanecelis** [comment]
Done. Thank you, @alice-i-cecile. Great talk on reflection by the way.
