### PR TITLE
Texture atlas format and conversion

### LINKED ISSUE #553: SpriteSheetComponent crashes when given grayscale PNG
`thread 'Compute Task Pool (0)' panicked at 'range end index 672 out of range for slice of length 576', ~/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_sprite-0.2.1/src/texture_atlas_builder.rs:68:35`

I used code copied from the example [`texture_atlas.rs`](https://github.com/bevyengine/bevy/blob/ad7613c67485ad468d33f1b68452c076b70db826/examples/2d/texture_atlas.rs) and the image is [here](https://github.com/emosenkis/budge/blob/d9ce02c83faee72ebd7f69711b2d63e6b6874b31/lib/bitmaps/heart.png).

### PR DESCRIPTION
**Pull request by mockersf**
fixes #553 

* adds a method to set the texture atlas format
* automatic conversion into target format if needed. This can be disabled, in which case finishing the builder will return an error if there are different texture formats

### CODE REVIEW

File: crates/bevy_sprite/src/texture_atlas_builder.rs [hunk 1]
```diff
@@ -53,6 +62,18 @@ impl TextureAtlasBuilder {
         self
     }
 
+    /// Sets the texture format for textures in the atlas.
+    pub fn format(mut self, format: TextureFormat) -> Self {
+        self.format = format;
+        self
+    }
+
+    /// Control wether the added texture should be converted to the atlas format, if different.
```
Comment (cart) [inline crates/bevy_sprite/src/texture_atlas_builder.rs:71]: nit: whether

**Review by cart — COMMENTED** [review]
Looks good to me! I just pushed a small change to increase code reuse in TextureAtlasBuilder

File: crates/bevy_sprite/src/texture_atlas_builder.rs (hunk 1 above)
Comment (mockersf) [reply crates/bevy_sprite/src/texture_atlas_builder.rs]: oops...
