### PR TITLE
Fix bevy_ui compilation failure without bevy_text

### LINKED ISSUE #8984: `bevy_ui` doesn't compile without the `bevy_text` feature
## Bevy version

main branch: c24520cb72f98

## What you did

```sh
cargo check --package bevy_ui --no-default-features
```

## What went wrong

Compilation error (several)

```
error[E0432]: unresolved import `crate::widget::TextFlags`
 --> crates/bevy_ui/src/node_bundles.rs:4:22
  |
4 |     widget::{Button, TextFlags, UiImageSize},
  |                      ^^^^^^^^^ no `TextFlags` in `widget`

error[E0412]: cannot find type `Without` in this scope
   --> crates/bevy_ui/src/widget/image.rs:137:22
    |
137 |         (With<Node>, Without<UiImage>),
    |                      ^^^^^^^ not found in this scope
    |
help: consider importing one of these items
    |
1   + use bevy_ecs::prelude::Without;
    |
1   + use crate::Without;
    |

error[E0599]: the method `before` exists for fn item `fn(Local<'a, f64>, Query<'b, 'c, &Window, With<...>>, ..., ..., ...) {update_atlas_content_size_system}`, but its trait bounds were not satisfied
   --> crates/bevy_ui/src/lib.rs:163:54
    |
163 |             widget::update_atlas_content_size_system.before(UiSystem::Layout),
    |                                                      ^^^^^^ method cannot be called due to unsatisfied trait bounds
    |
```

## Why it's happening

`bevy_text` is marked as `optional = true` in the `bevy_ui` `Cargo.toml`. And there is several `#[cfg(feature = "bevy_text")]` that indicates it is intended to be possible to run `bevy_ui` without `bevy_text`.

When I use the `--no-default-feature`, `bevy_text` is removed as a dependency, and the feature flag "bevy_text" is also removed.

### PR DESCRIPTION
**Pull request by nicopap**
# Objective

- Fix #8984 

### Solution

- Address compilation errors

I admit: I did sneak it an unrelated mini-refactor. of the `measurment.rs` module. it seemed to me that directly importing `taffy` types helped reduce a lot of boilerplate, so I did it.

### CODE REVIEW

File: crates/bevy_ui/src/measurement.rs [hunk 1]
```diff
@@ -50,33 +51,27 @@ impl Measure for FixedMeasure {
...
-            };
-        self.measure_func = Some(taffy::node::MeasureFunc::Boxed(Box::new(measure_func)));
+        let measure_func = move |size: TaffySize<_>, available: TaffySize<_>| {
+            let size = measure.measure(size.width, size.height, available.width, available.height);
+            TaffySize {
+                width: size.x,
+                height: size.y,
+            }
+        };
+        self.measure_func = Some(MeasureFunc::Boxed(Box::new(measure_func)));
```
Comment (ickshonpe) [inline crates/bevy_ui/src/measurement.rs:67]: This looks much cleaner. We should be using these type aliases in the `layout` module too.

File: crates/bevy_ui/src/widget/image.rs [hunk 2]
```diff
@@ -73,20 +70,20 @@ impl Measure for ImageMeasure {
     }
 }
 
+/// The filter type for `update_image_content_size_system` and `update_atlas_content_size_system`.
+#[cfg(feature = "bevy_text")]
+pub type UpdateImageFilter = (With<Node>, Without<bevy_text::Text>);
+/// The filter type for `update_image_content_size_system` and `update_atlas_content_size_system`.
+#[cfg(not(feature = "bevy_text"))]
+pub type UpdateImageFilter = With<Node>;
```
Comment (ickshonpe) [inline crates/bevy_ui/src/widget/image.rs:78]: This seems like a nice refactor. It's annoying the type aliases need to public though, maybe we could make the systems private and add an `ImageSizeSystem` system set?

**Review by ickshonpe — APPROVED** [review]
Fixes the compilation issues and the refactorings are nice.

File: crates/bevy_ui/src/widget/image.rs (hunk 2 above)
Comment (ickshonpe) [inline crates/bevy_ui/src/widget/image.rs:78]:
```suggestion
/// The filter type for `update_image_content_size_system` and `update_atlas_content_size_system`.
#[cfg(feature = "bevy_text")]
type UpdateImageFilter = (With<Node>, Without<bevy_text::Text>);
/// The filter type for `update_image_content_size_system` and `update_atlas_content_size_system`.
#[cfg(not(feature = "bevy_text"))]
type UpdateImageFilter = With<Node>;
```

There's no need for these to be pub I think?

Comment (nicopap) [reply crates/bevy_ui/src/widget/image.rs:78]: Oooh, yeah looks like it. Nice. I thought it needed to be pub due to being a parameter of a pub functions. Let me update it.

**Review by wilk10 — APPROVED** [review]
I don't mind the sneaky refactor, and the fix for the compilation failure is pretty elegant, imo. Well done!

**Review by mockersf — APPROVED** [review]
