### PR TITLE
bevy_ecs: flush entities after running observers and hooks in despawn

### LINKED ISSUE #14467: Panic when a despawning `Entity`'s observer spawns an `Entity`
## Bevy version

`0.14.0`

## What you did

```rust
use bevy::prelude::*;

fn main() {
    App::new()
        .add_plugins(MinimalPlugins)
        .add_systems(Startup, startup)
        .add_systems(Update, update)
        .run();
}

#[derive(Component)]
struct Marker;

fn startup(mut commands: Commands) {
    commands.spawn(Marker).observe(|_: Trigger<OnRemove, Marker>, mut commands: Commands| {
        commands.spawn_empty();
    });
}

fn update(
    query: Query<Entity, With<Marker>>,
    mut commands: Commands
) {
    for entity in &query {
        commands.entity(entity).despawn();
    }
}
```

### What were you expecting?
1. Entity with `Marker` component gets queued for despawning.
2. Its observer runs and queues the spawning of a new entity.
3. End result is the entity with `Marker` being despawned, and a new empty entity being spawned.
4. App continues to run.
### What actually happened?
```
thread 'main' panicked at F:\packages\cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_ecs-0.14.0\src\entity\mod.rs:582:9:
flush() needs to be called before this operation is legal
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Encountered a panic when applying buffers for system `flush_panic_repro::update`!
Encountered a panic in system `bevy_app::main_schedule::Main::run_main`!
error: process didn't exit successfully: `target\debug\flush_panic_repro.exe` (exit code: 101)
```

## Additional information

#14300 runs into the same panic, but involves component hooks, `MapEntities`, and `DynamicScene`. I don't know enough about Bevy's internals to know if these are ultimately the same bug, or just coincidentally panic in the same spot.

---
If just the `Marker` component is removed without despawning its entity, the observer still runs (as expected) but there is no panic:
```rust
fn update(
    query: Query<Entity, With<Marker>>,
    mut commands: Commands
) {
    for entity in &query {
        commands.entity(entity).remove::<Marker>(); // Does NOT panic.
    }
}
// Rest of code is unchanged.
```

---
Here's what seems like the most relevant part of the panic backtrace:
```
2: bevy_ecs::entity::Entities::verify_flushed
   at F:\packages\cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_ecs-0.14.0\src\entity\mod.rs:582
3: bevy_ecs::entity::Entities::free
   at F:\packages\cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_ecs-0.14.0\src\entity\mod.rs:680
4: bevy_ecs::world::entity_ref::EntityWorldMut::despawn
   at F:\packages\cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_ecs-0.14.0\src\world\entity_ref.rs:1235
5: bevy_ecs::world::World::despawn
   at F:\packages\cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_ecs-0.14.0\src\world\mod.rs:1105
6: bevy_ecs::system::commands::despawn
   at F:\packages\cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_ecs-0.14.0\src\system\commands\mod.rs:1241
```

### PR DESCRIPTION
**Pull request by jrobsonchase**
# Objective

Fixes #14467

Observers and component lifecycle hooks are allowed to perform operations that subsequently require `Entities` to be flushed, such as reserving a new entity. If this occurs during an `on_remove` hook or an `OnRemove` event trigger during an `EntityWorldMut::despawn`, a panic will occur.

## Solution

Call `world.flush_entities()` after running `on_remove` hooks/observers during `despawn`

## Testing

Added a new test that fails before the fix and succeeds afterward.

### CODE REVIEW

**Comment by alice-i-cecile** [comment]
Let me know when this is ready for review :)

**Comment by jrobsonchase** [comment]
@alice-i-cecile Ready!

**Comment by jrobsonchase** [comment]
Ooh, a miri failure. That's a new one for me!

File: crates/bevy_ecs/src/observer/mod.rs [hunk 1]
```diff
@@ -1160,4 +1160,28 @@ mod tests {
...
+        let mut world = World::new();
+
+        // Observe the removal of A - this will run during despawn
+        world.observe(|_: Trigger<OnRemove, A>, mut cmd: Commands| {
+            // Spawn a new entity - this reserves a new ID and requires a flush
+            // afterward before Entities::free can be called.
+            cmd.spawn_empty();
+        });
+
+        world.flush();
```
Comment (alice-i-cecile) [inline crates/bevy_ecs/src/observer/mod.rs:1175]: Comments for why each of these flushes are needed please.

File: crates/bevy_ecs/src/observer/mod.rs [hunk 2]
```diff
@@ -1160,4 +1160,28 @@ mod tests {
         world.flush();
         assert_eq!(vec!["event", "event"], world.resource::<Order>().0);
     }
+
+    #[test]
+    fn observer_on_remove_during_despawn_spawn_empty() {
```
Comment (alice-i-cecile) [inline crates/bevy_ecs/src/observer/mod.rs:1165]: A comment about how prior to this PR this would panic would be helpful to motivate the test since there's no asserts.

**Review by alice-i-cecile — COMMENTED** [review]
Some clarity nits about the test, but I agree with the fix and the test design is good.

**Review by iiYese — APPROVED** [review]
The flushes need explaining but other than that lgtm.

File: crates/bevy_ecs/src/observer/mod.rs (hunk 1 above)
Comment (jrobsonchase) [reply crates/bevy_ecs/src/observer/mod.rs]: Weren't actually necessary to begin with!

File: crates/bevy_ecs/src/observer/mod.rs (hunk 2 above)
Comment (jrobsonchase) [reply crates/bevy_ecs/src/observer/mod.rs:1167]: Done!

**Review by alice-i-cecile — APPROVED** [review]

File: crates/bevy_ecs/src/world/entity_ref.rs [hunk 3]
```diff
@@ -1323,6 +1323,10 @@ impl<'w> EntityWorldMut<'w> {
             world.removed_components.send(component_id, self.entity);
         }
 
+        // Observers and on_remove hooks may reserve new entities, which
+        // requires a flush before Entities::free may be called.
+        world.flush_entities();
```
Comment (chescock) [inline crates/bevy_ecs/src/world/entity_ref.rs:1328]: There's also a call to `world.flush_entities();` at the top of this method.  Do we need both, or did that one just need to get moved down here?  

It looks like prior to #10756 the `flush()` call was right before the `free()` call, and the hooks and observers code got added in between.  The calls to `deferred_world.trigger_on_foo` in `bundle.rs` don't have `flush()` calls.  That makes me think that we don't need to flush before triggering things, and we only need the single call here, right before the `free()`.  

It doesn't look like anything bad can happen if we flush twice, though, so it should be fine to leave both even if they're not both needed.

**Review by chescock — APPROVED** [review]

**Comment by alice-i-cecile** [comment]
Merging; thanks for the careful work and clear explanations :)

**Comment by jrobsonchase** [comment]
Whoops, left an extra line in my test that broke CI. Should be good to go now @alice-i-cecile
