### PR TITLE
Replace `IntoSystemSetConfig` with `IntoSystemSetConfigs`

### LINKED ISSUE #9244: Deprecate `configure_set` & make `configure_sets` work for single params.
## Bevy version
0.11

## What you did
Tried to use `.configure_sets` with a single system set parameter.

## What went wrong
Received a compile error. It seems `configure_set` was not deprecated and `configure_sets` was not changed to support single item calls like other APIs in this family for `0.11`.

### PR DESCRIPTION
**Pull request by geieredgar**
# Objective

- Fixes #9244.

## Solution

- Changed the `(Into)SystemSetConfigs` traits and structs be more like the `(Into)SystemConfigs` traits and structs.
- Replaced uses of `IntoSystemSetConfig` with `IntoSystemSetConfigs`
- Added generic `ItemConfig` and `ItemConfigs` types.
- Changed `SystemConfig(s)` and `SystemSetConfig(s)` to be type aliases to `ItemConfig(s)`.
- Added generic `process_configs` to `ScheduleGraph`.
- Changed `configure_sets_inner` and `add_systems_inner` to reuse `process_configs`.

---

## Changelog

- Added `run_if` to `IntoSystemSetConfigs`
- Deprecated `Schedule::configure_set` and `App::configure_set`
- Removed `IntoSystemSetConfig`

## Migration Guide

- Use `App::configure_sets` instead of `App::configure_set`
- Use `Schedule::configure_sets` instead of `Schedule::configure_set`

### CODE REVIEW

File: crates/bevy_ecs/src/schedule/schedule.rs [hunk 1]
```diff
@@ -661,36 +657,159 @@ impl ScheduleGraph {
...
+            SystemSetConfigs::SystemSetConfig(config) => {
+                let node_id = self.configure_set_inner(config).unwrap();
+                if ancestor_chained {
+                    NodesResult {
+                        densely_chained: true,
+                        nodes: vec![node_id],
+                    }
+                } else {
+                    NodesResult {
+                        densely_chained: true,
```
Comment (alice-i-cecile) [inline crates/bevy_ecs/src/schedule/schedule.rs:678]: I don't understand why this is set to true here.

File: crates/bevy_ecs/src/schedule/schedule.rs [hunk 2]
```diff
@@ -661,36 +657,159 @@ impl ScheduleGraph {
...
+                    let mut previous_result = self.configure_sets_inner(prev, true);
+                    densely_chained = previous_result.densely_chained;
+                    for current in config_iter {
+                        let current_result = self.configure_sets_inner(current, true);
+                        densely_chained = densely_chained && current_result.densely_chained;
+                        match (
+                            previous_result.densely_chained,
+                            current_result.densely_chained,
+                        ) {
+                            // Both groups are "densely" chained, so we can simplify the graph by only
```
Comment (alice-i-cecile) [inline crates/bevy_ecs/src/schedule/schedule.rs:723]: This is a very helpful comment, but more introduction of the concept of "densely chained" would be helpful early in this function.

Comment (geieredgar) [reply crates/bevy_ecs/src/schedule/schedule.rs]: I previously just copied and adjusted the `add_systems_inner` function, but forgot to copy the documentation of `add_systems_inner` for `configure_sets_inner`, which explained what "densely chained" means. I refactored this PR to instead introduce generic `ItemConfig` and `ItemConfigs` types and a generic `process_configs` (a generic version of `add_systems_inner` and `configure_sets_inner`) to remove code duplication and make reviewing easier.

File: crates/bevy_ecs/src/schedule/schedule.rs (hunk 1 above)
Comment (geieredgar) [reply crates/bevy_ecs/src/schedule/schedule.rs]: This is set to true because an empty list of nodes fulfills the requirement of being densely chained, meaning that all nodes are linearly chained in the order they are defined. Since there are no nodes, this is trivially true.

File: crates/bevy_ecs/src/schedule/schedule.rs [hunk 3]
```diff
@@ -499,30 +499,44 @@ impl ScheduleGraph {
...
-    ) -> AddSystemsInnerResult {
+    ) -> ProcessConfigsResult {
+        self.process_configs(configs, ancestor_chained, &mut |this, config| {
+            this.add_system_inner(config).unwrap()
+        })
+    }
+
+    /// Adds the config items to the graph. Returns a vector of all node ids contained in the nested `ItemConfigs`
+    /// if `ancestor_chained` is true. Also returns true if "densely chained", meaning that all nested items
+    /// are linearly chained in the order they are defined
```
Comment (alice-i-cecile) [inline crates/bevy_ecs/src/schedule/schedule.rs:517]:
```suggestion
    /// Adds the config items to the graph. 
    ///
    /// `ancestor_chained` describes whether the provided ancestor are densely chained.
    /// `process_config` is the function by which the `ItemConfigs`  are transformed into `NodeId`.
    ///
    /// The fields on the returned [`ProcessConfigResult`] are:
    /// - `nodes`: a vector of all node ids contained in the nested `ItemConfigs`
    /// - `densely_chained`: a boolean that controls whether all nested items should be linearly chained (with successive `after` system orderings) in the order they are defined
```

**Review by alice-i-cecile — CHANGES_REQUESTED** [review]
I really like the refactor; this is way cleaner and easier to review. I think we can make the doc strings nicer, but as long as you explicitly work in the concept of "chaining == system ordering" I'll be happy to approve.

File: crates/bevy_ecs/src/schedule/schedule.rs [hunk 4]
```diff
@@ -654,43 +668,35 @@ impl ScheduleGraph {
...
-            for set in set_iter {
-                self.configure_set_inner(set).unwrap();
-            }
-        }
+        self.configure_sets_inner(sets.into_configs(), false);
     }
 
-    fn configure_set(&mut self, set: impl IntoSystemSetConfig) {
-        self.configure_set_inner(set).unwrap();
+    /// Adds the system sets to the graph. Returns a vector of all node ids contained in the nested `SystemnSetConfigs`
```
[the remark this answers is not in the document]
Comment (geieredgar) [reply crates/bevy_ecs/src/schedule/schedule.rs]: Done. I've renamed the `ancestor_chained` parameter to the more accurate `collect_nodes` name and also fixed the description of the `densely_chained` field a bit, since it describes whether the nested items are linearly chained and not if they should be linearly chained.

**Review by alice-i-cecile — APPROVED** [review]

File: crates/bevy_ecs/src/schedule/schedule.rs [hunk 5]
```diff
@@ -499,30 +499,53 @@ impl ScheduleGraph {
...
+    /// `process_config` is the function which processes each individual config item and returns a corresponding `NodeId`.
+    ///
+    /// The fields on the returned [`ProcessConfigsResult`] are:
+    /// - `nodes`: a vector of all node ids contained in the nested `ItemConfigs`
+    /// - `densely_chained`: a boolean that is true if all nested items are linearly chained (with successive `after` orderings) in the order they are defined
+    fn process_configs<T>(
+        &mut self,
+        configs: ItemConfigs<T>,
+        collect_nodes: bool,
+        process_config: &mut impl FnMut(&mut Self, ItemConfig<T>) -> NodeId,
```
[the remark this answers is not in the document]
Comment (geieredgar) [reply crates/bevy_ecs/src/schedule/schedule.rs]: Great idea. Done.

File: crates/bevy_ecs/src/schedule/config.rs [hunk 6]
```diff
@@ -47,64 +47,72 @@ impl IntoSystemConfigs<()> for BoxedSystem<(), ()> {
     }
 }
 
-/// Stores configuration for a single system.
-pub struct SystemConfig {
-    pub(crate) system: BoxedSystem,
+/// Stores configuration for a single generic item.
+pub struct ItemConfig<T> {
```
[the remark this answers is not in the document]
Comment (geieredgar) [reply crates/bevy_ecs/src/schedule/config.rs]: Done.
