### PR TITLE
Fix misleading documentation of Main schedule

### LINKED ISSUE #18562: Misleading information in the documentation of the Main schedule
The [documentation](https://docs.rs/bevy/latest/bevy/app/struct.Main.html) of the Main schedule says that on its first run it wil run `PreStartup`, `Startup` and `PostStartup`. Actually, it starts with `StateTransition` as can be seen [here](https://github.com/bevyengine/bevy/blob/main/crates/bevy_state/src/app.rs#L311).

### PR DESCRIPTION
**Pull request by inact1v1ty**
# Objective

Fixes #18562.

## Solution

- Specified that `StateTransition` is actually run before `PreStartup`.
- Specified consequences of this and how to actually run systems before any game logic regardless of state.
- Updated docs of `StateTransition` to reflect that it is run before `PreStartup` in addition to being run after `PreUpdate`.

## Testing

- `cargo doc`
- `cargo test --doc`

### CODE REVIEW

**Review by alice-i-cecile — APPROVED** [review]

File: crates/bevy_app/src/main_schedule.rs [hunk 1]
```diff
@@ -15,6 +15,12 @@ use bevy_ecs::{
 /// By default, it will run the following schedules in the given order:
 ///
 /// On the first run of the schedule (and only on the first run), it will run:
+/// * [`StateTransition`]
+///      * This means that [`OnEnter(ExampleState)`] will be called *before* [`PreStartup`]
+///        if `ExampleState` is the starting state of the app.
```
Comment (benfrankel) [inline crates/bevy_app/src/main_schedule.rs:20]:
```suggestion
///        if `ExampleState` was added to the app with that initial state.
```
"starting state of the app" is confusing because apps are not associated with one global state type.

**Review by benfrankel — CHANGES_REQUESTED** [review]
I'll also note that the `StateTransition` mentions in the docs for the `Main` schedule are technically not entirely correct, because a user could use `bevy_app` without `bevy_state`. However, they were already incorrect before this PR so it's fine.

File: crates/bevy_app/src/main_schedule.rs (hunk 1 above)
Comment (inact1v1ty) [reply crates/bevy_app/src/main_schedule.rs:20]: Hmm. I like your suggestion, but I don't think this wording is correct, too, because of computed states: if a computed state happens to be derived from the initial enum variant of a state, its `OnEnter` would run here, too. Do you have something on your mind that will both capture this case and make the sentence not confusing?

Comment (inact1v1ty) [reply crates/bevy_app/src/main_schedule.rs:20]: I think this is important to highlight here, as it can be a point of confusion. In our game, for example, we make use of `SubStates` and `ComputedStates` extremely heavily, I assume dozens of `ComputedStates` by the moment all features will be implemented - so most of the times it is `OnEnter(SomeComputedState)`.

Comment (benfrankel) [reply crates/bevy_app/src/main_schedule.rs:20]: Sure, maybe change `ExampleState` to `MyState::Foo` and then say "if `MyState::Foo` is the initial value of `MyState`" or similar.

**Comment by inact1v1ty** [comment]
@benfrankel I have reworded according to your suggestion, but adding info about `ComputedStates`, and also left a footnote telling that `StateTransition` comes only with `bevy_state` 🙂

**Review by benfrankel — APPROVED** [review]
