### PR TITLE
Better warnings about invalid parameters

### LINKED ISSUE #15391: Logging for system parameter validation should be configurable
## What problem does this solve or what need does it fill?

Following #15276, systems are now skipped when they cannot run due to missing data, rather than panicking and crashing their app.

While we should 100% warn by default when this happens, some of those logs will be spurious. This behavior might be expected, and users should be able to turn them off.

## What solution would you like?

Allow users to disable this logging by disabling it at the system config level, which should work on both systems and system sets.

It would be nice to be able to change the log level to any of the standard levels: none, debug, info, warn, error, panic, but warn, and ignore are the most important.

## What alternative(s) have you considered?

We could also expose a way to turn off these warnings globally, but this is likely to be a footgun: your systems silently not running is very bad!

We could also add resource / component-level log disabling, but that's more complex. My preferred solution there now is to add opt-in support for reads/writes system sets (based on https://github.com/bevyengine/bevy/pull/5388), and then use the mechanism above to configure them. 

## Additional context

Previously discussed in https://github.com/bevyengine/bevy/issues/15265.

### PR DESCRIPTION
**Pull request by MiniaczQ**
# Objective

System param validation warnings should be configurable and default to "warn once" (per system).

Fixes: #15391

## Solution

`SystemMeta` is given a new `ParamWarnPolicy` field.
The policy decides whether warnings will be emitted by each system param when it fails validation.
The policy is updated by the system after param validation fails.

Example warning:
```
2024-09-30T18:10:04.740749Z  WARN bevy_ecs::system::function_system: System fallible_params::do_nothing_fail_validation will not run because it requested inaccessible system parameter Single<(), (With<Player>, With<Enemy>)>
```

Currently, only the first invalid parameter is displayed.

Warnings can be disabled on function systems using `.param_never_warn()`.
(there is also `.with_param_warn_policy(policy)`)

## Testing

Ran `fallible_params` example.

### CODE REVIEW

**Review by BenjaminBrienen — APPROVED** [review]

**Comment by MiniaczQ** [comment]
I've noticed some problems with this approach, I'll be reworking it

**Comment by MiniaczQ** [comment]
> Have you benchmarked this? Two not taken (predictable) `if`s per system invocation probably aren't measurable and not worth adding a system flag.

Not benchmarked, I'll see if next reviewer agrees or if we'll need benchmarks.

**Comment by MiniaczQ** [comment]
Thank you for your work, I'll remove the flag when im home :)

File: crates/bevy_ecs/src/system/function_system.rs [hunk 1]
```diff
@@ -108,11 +113,111 @@ impl SystemMeta {
...
+}
+
+impl<M, F> WithParamWarnPolicy<M, F> for F
+where
+    M: 'static,
+    F: SystemParamFunction<M>,
+{
+    fn with_param_warn_policy(self, param_warn_policy: ParamWarnPolicy) -> FunctionSystem<M, F> {
+        let mut system = IntoSystem::into_system(self);
+        system.system_meta.param_warn_policy = param_warn_policy;
```
[the remark this answers is not in the document]
Comment (MiniaczQ) [reply crates/bevy_ecs/src/system/function_system.rs:216]: Feature removed, but I'll use the SystemMeta method instead if we ever readd it

File: crates/bevy_ecs/src/system/function_system.rs [hunk 2]
```diff
@@ -108,11 +111,99 @@ impl SystemMeta {
...
+    #[inline]
     pub fn set_has_deferred(&mut self) {
         self.has_deferred = true;
     }
 }
 
+impl SystemMeta {
+    /// Changes the warn policy.
+    #[inline]
+    pub fn set_param_warn_policy(&mut self, warn_policy: ParamWarnPolicy) {
```
Comment (chescock) [inline crates/bevy_ecs/src/system/function_system.rs:123]: Do these need to be `pub`?  Most of the `SystemMeta` stuff is `pub (crate)`.  It looks like `try_warn_param` needs to be `pub` to support warning from third-party `SystemParam` implementations, but I would expect `set_param_warn_policy` and `advance_param_warn_policy` to only be called from within the crate.

File: crates/bevy_ecs/src/system/function_system.rs [hunk 3]
```diff
@@ -108,11 +111,99 @@ impl SystemMeta {
...
+    where
+        P: SystemParam,
+    {
+        if matches!(self, Self::Never) {
+            return;
+        }
+        bevy_utils::tracing::warn!(
+            "System {0} will not run because it requested inaccessible system parameter {1}",
+            name,
+            core::any::type_name::<P>()
```
Comment (chescock) [inline crates/bevy_ecs/src/system/function_system.rs:173]: Would it make sense to use `disqualified::ShortName` here?  I think that would give

```
Single<(), (With<Player>, With<Enemy>)>
```

instead of

```
bevy_ecs::system::query::Single<(), (bevy_ecs::query::filter::With<fallible_params::Player>, bevy_ecs::query::filter::With<fallible_params::Enemy>)>
```

File: crates/bevy_ecs/src/system/function_system.rs [hunk 4]
```diff
@@ -108,11 +111,99 @@ impl SystemMeta {
 
     /// Marks the system as having deferred buffers like [`Commands`](`super::Commands`)
     /// This lets the scheduler insert [`apply_deferred`](`crate::prelude::apply_deferred`) systems automatically.
+    #[inline]
     pub fn set_has_deferred(&mut self) {
         self.has_deferred = true;
     }
 }
 
+impl SystemMeta {
```
[the remark this answers is not in the document]
Comment (MiniaczQ) [reply crates/bevy_ecs/src/system/function_system.rs:120]: Used to be feature gated

File: crates/bevy_ecs/src/system/function_system.rs (hunk 3 above)
Comment (MiniaczQ) [reply crates/bevy_ecs/src/system/function_system.rs:173]: I'll see what I can do, never used that before

File: crates/bevy_ecs/src/schedule/executor/multi_threaded.rs [hunk 5]
```diff
@@ -524,7 +523,7 @@ impl ExecutorState {
     unsafe fn should_run(
         &mut self,
         system_index: usize,
-        system: &BoxedSystem,
+        system: &mut BoxedSystem,
```
[the remark this answers is not in the document]
Comment (MiniaczQ) [reply crates/bevy_ecs/src/schedule/executor/multi_threaded.rs:526]: validate param now takes mutable reference to update the metadata (warn policy)

**Comment by MiniaczQ** [comment]
> if a system has multiple failing parameters, it only warns on the first one, right?

The policy update of a (function) system happens after param validation fails.
But param validation of tuples, etc. currently short circuits, so yes
you will only see the first missing type.

While we can remove the short circuit, this won't patch a hole where missing parameters can change over time and we'll still only get warning about the first one.

I guess we could store the warning per system param??
But then routing all the configuration will be hellish

File: crates/bevy_ecs/src/system/function_system.rs (hunk 3 above)
Comment (MiniaczQ) [reply crates/bevy_ecs/src/system/function_system.rs]: Okay that was very easy to swap in, thanks

File: crates/bevy_ecs/src/system/function_system.rs [hunk 6]
```diff
@@ -108,9 +111,96 @@ impl SystemMeta {
...
+    }
+}
+
+/// State machine for emitting warnings when [system params are invalid](System::validate_param).
+#[derive(Clone, Copy)]
+pub enum ParamWarnPolicy {
+    /// No warning should ever be emitted.
+    Never,
+    /// The warning will be emitted once and status will update to [`Self::Never`].
+    Once,
```
Comment (bushrat011899) [inline crates/bevy_ecs/src/system/function_system.rs:147]: Future PR: Seems reasonable to add an `Always` policy as well:

```rust
/// State machine for emitting warnings when [system params are invalid](System::validate_param).
#[derive(Clone, Copy)]
pub enum ParamWarnPolicy {
    /// No warning should ever be emitted.
    Never,
    /// The warning will be emitted once and status will update to [`Self::Never`].
    Once,
    /// The warning will be emitted each time the system is run.
    Always,
}
```

**Review by bushrat011899 — APPROVED** [review]
Looks good to me, love the idea of giving more meaningful feedback to the user without spamming them needlessly. I have a note about a possible future PR, but definitely doesn't need to be in this PR.

File: crates/bevy_ecs/src/system/function_system.rs (hunk 6 above)
Comment (MiniaczQ) [reply crates/bevy_ecs/src/system/function_system.rs:147]: I had it but removed it as per previous feedback.
I think `Always` will be a bit too annoying, but we could certainly use more complex policies:
- system just stopped running (prev frame valid, this frame invalid)
- invalid params changed

If we get some higher level logging with editor, we can do stuff like:
- system X stopped running at frame N because of invalid param P and is still not running till frame M

File: crates/bevy_ecs/src/system/function_system.rs [hunk 7]
```diff
@@ -108,9 +111,96 @@ impl SystemMeta {
...
+    fn try_warn<P>(&self, name: &str)
+    where
+        P: SystemParam,
+    {
+        if matches!(self, Self::Never) {
+            return;
+        }
+
+        bevy_utils::tracing::warn!(
+            "System {0} will not run because it requested inaccessible system parameter {1}",
```
[the remark this answers is not in the document]
Comment (MiniaczQ) [reply crates/bevy_ecs/src/system/function_system.rs:168]: Can also be a condition, open for suggestions here on the phrasing

**Review by alice-i-cecile — APPROVED** [review]
