### PR TITLE
Fix motion blur on wasm

### LINKED ISSUE #13097: Likely overpadded motion blur struct
## Bevy version

Latest main.

## What you did

Had a look at the newly merged motion blur PR.

## What went wrong

https://github.com/bevyengine/bevy/blob/main/crates/bevy_core_pipeline/src/motion_blur/motion_blur.wgsl#L21

If I'm not mistaken the padding is meant to ensure the fields add up to 16 bytes.

Since there is a `f32` and a `u32` before the padding, the "hole" is 8 bytes, but the padding adds 12 bytes via `vec3<f32>`.

In this case the wgsl should change to `vec2<f32>` as well as the corresponding Rust side `ShaderType` struct.

### PR DESCRIPTION
**Pull request by rparrett**
# Objective

Fixes #13097 and other issues preventing the motion blur example from working on wasm

## Solution

- Use a vec2 for padding
- Fix error initializing the `MotionBlur` struct on wasm+webgl2
- Disable MSAA on wasm+webgl2
- Fix `GlobalsUniform` padding getting added on the shader side for webgpu builds

## Notes

The motion blur example now runs, but with artifacts. In addition to the obvious black artifacts, the motion blur or dithering seem to just look worse in a way I can't really describe. That may be expected.

```
AdapterInfo { name: "ANGLE (Apple, ANGLE Metal Renderer: Apple M1 Max, Unspecified Version)", vendor: 4203, device: 0, device_type: IntegratedGpu, driver: "", driver_info: "", backend: Gl }
```
Screenshot 2024-04-25 at 6 51 21 AM

### CODE REVIEW

File: examples/3d/motion_blur.rs [hunk 1]
```diff
@@ -7,8 +7,13 @@ use bevy::{
 };
 
 fn main() {
-    App::new()
-        .add_plugins(DefaultPlugins)
+    let mut app = App::new();
+
+    // MSAA and Motion Blur together are not compatible on WebGL
+    #[cfg(target_arch = "wasm32")]
+    app.insert_resource(Msaa::Off);
```
Comment (mockersf) [inline examples/3d/motion_blur.rs:14]: if this is just for WebGL2, it should also gate on that to keep it enabled on WebGPU

File: examples/3d/motion_blur.rs [hunk 2]
```diff
@@ -21,9 +26,11 @@ fn setup_camera(mut commands: Commands) {
         // Motion blur requires the depth and motion vector prepass, which this bundle adds.
         // Configure the amount and quality of motion blur per-camera using this component.
         MotionBlurBundle {
+            #[allow(clippy::needless_update)]
```
Comment (IceSentry) [inline examples/3d/motion_blur.rs:29]: why is this needed?

**Comment by rparrett** [comment]
It seems that there are other issues when building with webgpu:

```
The shader uses more bytes of the buffer (16) than the layout's minBindingSize (12).
 - While validating that the entry-point's declaration for @group(0) @binding(5) matches [BindGroupLayout "motion_blur_layout"]
 - While validating the entry-point's compatibility for group 0 with [BindGroupLayout "motion_blur_layout"]
 - While validating fragment stage ([ShaderModule (unlabeled)], entryPoint: fragment).
 - While validating fragment state.
 - While calling [Device].CreateRenderPipeline([RenderPipelineDescriptor "motion_blur_pipeline"]).
 ```

File: examples/3d/motion_blur.rs (hunk 2 above)
Comment (rparrett) [reply examples/3d/motion_blur.rs:29]: I'm using `..default()` to fill in the padding value `MotionBlur`, but the padding field doesn't exist in native builds so this raises an error.

I could do the padding manually and/or gate the `..default()` line with `#[cfg(all(feature = "webgl", target_arch = "wasm32"))]` if that's preferable.

Comment (IceSentry) [reply examples/3d/motion_blur.rs:29]: Ah, got it, makes sense. Maybe using the cfg would make that more explicit yeah and avoid someone potentially removing something that doesn't appear necessary on the surface.

**Review by kristoff3r — APPROVED** [review]
LGTM, just standard annoying webgl2 padding. I tested on Linux and wasm webgl2 and both works.

**Comment by aevyrie** [comment]
Bummer, this was working at one point, but I forgot to re-test closer to final merge. Thanks!

**Review by aevyrie — APPROVED** [review]

File: examples/3d/motion_blur.rs (hunk 2 above)
Comment (Elabajaba) [reply examples/3d/motion_blur.rs]: > ... gate the `..default()` line with `#[cfg(all(feature = "webgl", target_arch = "wasm32"))]` if that's preferable.

Webgpu and webgl2 aren't technically mutually exclusive now (since the wgpu 0.19 upgrade that was pre-bevy 0.13, having both the webgl and webgpu features enabled forces webgpu). If we don't need the padding on webgpu then the cfg should be `#[cfg(all(feature = "webgl", target_arch = "wasm32", not(feature = "webgpu")))]`

**Review by james7132 — APPROVED** [review]
