### PR TITLE
Fix `..` collapsing with other `..` during AssetPath normalization.

### LINKED ISSUE #21875: Assets from relative paths outside the asset folder not loading
## Bevy version 0.17.3

Tested on Arch Linux

Works in 0.17.2 but not in 0.17.3. Likely from this PR: https://github.com/bevyengine/bevy/pull/21643

This has the [flight helmet](https://github.com/bevyengine/bevy/tree/release-0.17.3/assets/models/FlightHelmet) gLTF in both:
`temp/asset_load_test/assets/FlightHelmet/FlightHelmet.gltf`
and
`temp/FlightHelmet/FlightHelmet.gltf`

Both load and are seen on screen in 0.17.2, but only the left one in 0.17.3.

0.17.3 error:
`ERROR bevy_asset::server: Failed to load asset '../../FlightHelmet/FlightHelmet.gltf' with asset loader 'bevy_gltf::loader::GltfLoader': failed to read bytes from an asset path: Path not found: /temp/asset_load_test/assets/FlightHelmet/FlightHelmet.bin`

```rs
use bevy::{asset::UnapprovedPathMode, prelude::*};

fn main() {
    App::new()
        .add_plugins(DefaultPlugins.set(AssetPlugin {
            unapproved_path_mode: UnapprovedPathMode::Allow,
            ..default()
        }))
        .add_systems(Startup, setup)
        .run();
}

fn setup(mut commands: Commands, asset_server: Res<AssetServer>) {
    commands.spawn((
        Camera3d::default(),
        Transform::from_xyz(0.7, 0.7, 1.0).looking_at(Vec3::new(0.0, 0.3, 0.0), Vec3::Y),
    ));

    commands.spawn((DirectionalLight {
        shadows_enabled: true,
        ..default()
    },));

    commands.spawn((
        SceneRoot(
            asset_server
                .load(GltfAssetLabel::Scene(0).from_asset("models/FlightHelmet/FlightHelmet.gltf")),
        ),
        Transform::from_xyz(-1.0, 0.0, 0.0),
    ));

    commands.spawn((
        SceneRoot(
            asset_server
                .load(GltfAssetLabel::Scene(0).from_asset("../../FlightHelmet/FlightHelmet.gltf")),
        ),
        Transform::from_xyz(0.0, 0.0, 0.0),
    ));
}
```

### PR DESCRIPTION
**Pull request by andriyDev**
# Objective

- Fixes #21875.

## Solution

- Make sure that we're not collapsing `..` with itself!

## Testing

- Added a test for this. It failed but after the fix it passes!

### CODE REVIEW

File: crates/bevy_asset/src/path.rs [hunk 1]
```diff
@@ -648,7 +648,12 @@ pub(crate) fn normalize_path(path: &Path) -> PathBuf {
         if elt == "." {
             // Skip
         } else if elt == ".." {
-            if !result_path.pop() {
+            if let Some(file_name) = result_path.file_name()
+                // Don't collapse .. with another ..
+                && file_name != ".."
+            {
+                assert!(result_path.pop());
```
Comment (DGriffin91) [inline crates/bevy_asset/src/path.rs:656]: Does this mean bevy would crash given an invalid path that triggers this?

**Comment by DGriffin91** [comment]
Tried this on my repro from [the issue](https://github.com/bevyengine/bevy/issues/21875) and it seemed to work.

File: crates/bevy_asset/src/path.rs (hunk 1 above)
Comment (andriyDev) [reply crates/bevy_asset/src/path.rs:656]: No - this assert is literally just a sanity check. We already know we have a file name because we did `result_path.file_name()` and made sure it's `Some`. So we know for sure there's something in `result_path` to pop.

**Review by it-me-joda — APPROVED** [review]
Great tests!

**Review by JMS55 — APPROVED** [review]

**Review by mockersf — APPROVED** [review]
