### PR TITLE
bevy_reflect: Disambiguate type bounds in where clauses.

### LINKED ISSUE #8759: Reflect derive macro expansion causes syntax ambiguity with Higher-Kinded Types.
## Bevy version

0.10.1

## System information

Rustc version: 1.69.0 (84c898d65 2023-04-16)
Cargo version: 1.69.0 (6e9a83356 2023-04-12)
Platform: amd64 Windows 11 22H2 (OS Build 22621.1702)

## The bug report

Bit of an edge case that it might be useful to correct: During the expansion of the `Reflect` derive macro on a struct that uses a higher-kinded type directly as one of its field types, the macro expands to some rather ambiguous bounds:

```rust
#[derive(bevy::reflect::Reflect)]
pub struct SingleLineDisplayState {
    #[reflect(ignore)]
    transform: for<'a> fn(&'a str) -> &'a str,
}

fn get_type_registration<T: bevy::reflect::GetTypeRegistration>() {}

fn caller() {
    get_type_registration::<SingleLineDisplayState>(); // error occurs here
}

// auto-generated by derive(Reflect) on SingleLineDisplayState, shown here for example purposes
impl bevy::reflect::GetTypeRegistration for SingleLineDisplayState
where
    for<'a> fn(&'a str) -> &'a str: Any + Send + Sync,
{
    ...
}
```

## What went wrong

Unfortunately, rustc does not interpret this as `where (for<'a> fn(&'a str) -> &'a str): Any` (a higher-kinded bound of `for<'a> fn(&'a str) -> &'a str`), as is intended, but instead `where for<'a> (fn(&'a str) -> &'a str): Any` (a `for<'a>`-bound predicate of the non-higher-kinded type `fn(&'a str) -> &'a str`). This then causes the compiler to be unable to prove that `SingleLineDisplayState` does in fact implement `GetTypeRegistration`, leading to a compilation failure with the rather unhelpful error message "`error: higher-ranked lifetime error`".

## Additional information

The issue arises when attempting to pass `SingleLineDisplayState` to any generic parameter that expects its type to implement `GetTypeRegistration`, as seen in the example above.

This is a simple grammar problem, as merely wrapping the type in parentheses in the struct definition resolves the ambiguity and fixes the problem. Perhaps `Reflect` could be augmented to place parentheses around the trait bounds it outputs, to prevent this ambiguity?

### PR DESCRIPTION
**Pull request by Themayu**
# Objective

It was accidentally found that rustc is unable to parse certain constructs in `where` clauses properly. `bevy_reflect::Reflect`'s habit of copying and pasting the field types in a type's definition to its `where` clauses made it very easy to accidentally run into this behaviour - particularly with the construct
```rust
where
    for<'a> fn(&'a T) -> &'a T: Trait1 + Trait2
```

which was incorrectly parsed as
```rust
where
    for<'a> (fn(&'a T) -> &'a T: Trait1 + Trait2)
            ^                                   ^ incorrect syntax grouping
```

instead of
```rust
where
    (for<'a> fn(&'a T) -> &'a T): Trait1 + Trait2
    ^                          ^ correct syntax grouping
```

Fixes #8759 

## Solution

This commit fixes the issue by inserting explicit parentheses to disambiguate types from their bound lists.

### CODE REVIEW

**Review by alice-i-cecile — CHANGES_REQUESTED** [review]
Can you add a simple test here to prevent regressions :) I like the change itself though.

**Comment by Themayu** [comment]
How would I go about doing that?

**Review by alice-i-cecile — APPROVED** [review]

**Comment by Themayu** [comment]
Fixed a merge conflict that occurred due to unfortunate timing between my PR and another one.

**Review by alice-i-cecile — APPROVED** [review]

File: crates/bevy_reflect/bevy_reflect_derive/src/utility.rs [hunk 1]
```diff
@@ -156,10 +156,10 @@ pub(crate) fn extend_where_clause(
         quote!()
     };
     generic_where_clause.extend(quote! {
```
Comment (MrGVSV) [inline crates/bevy_reflect/bevy_reflect_derive/src/utility.rs:158]: Nit: Could you leave a comment above this line letting future devs know that the parentheses are there to disambiguate certain types (specifically HRTBs)?

**Review by MrGVSV — APPROVED** [review]
Looks good! Just one comment

File: crates/bevy_reflect/src/lib.rs [hunk 2]
```diff
@@ -1426,6 +1426,26 @@ mod tests {
         assert!(info.is::<MyValue>());
     }
 
+    #[test]
+    fn should_permit_higher_ranked_lifetimes() {
```
Comment (MrGVSV) [inline crates/bevy_reflect/src/lib.rs:1430]: Nit: This is totally fine so no need to change it haha, but just wanted to point out that we also have the [bevy_reflect_compile_fail_tests](https://github.com/bevyengine/bevy/tree/main/crates/bevy_reflect_compile_fail_tests) crate to test that things pass or fail build (with `.pass.rs` and `.fail.rs` files).

File: crates/bevy_reflect/bevy_reflect_derive/src/utility.rs (hunk 1 above)
Comment (Themayu) [reply crates/bevy_reflect/bevy_reflect_derive/src/utility.rs:158]: Sure.

File: crates/bevy_reflect/src/lib.rs (hunk 2 above)
Comment (Themayu) [reply crates/bevy_reflect/src/lib.rs:1430]: Information overload led me to narrow my editor's view to `bevy_reflect`, so I missed that crate's existence. Sorry.

File: crates/bevy_reflect/bevy_reflect_derive/src/utility.rs (hunk 1 above)
Comment (Themayu) [reply crates/bevy_reflect/bevy_reflect_derive/src/utility.rs:158]: Now that I look at it, I'm not sure where `parameter_types` is coming from. If it's coming from the user's own type parameters, I should remove the parentheses. But if it's generated as part of the derive, then I should leave it in.

Comment (Themayu) [reply crates/bevy_reflect/bevy_reflect_derive/src/utility.rs:158]: Okay no, they're coming from Bevy. The parentheses remain.

Comment (Themayu) [reply crates/bevy_reflect/bevy_reflect_derive/src/utility.rs:163]: Done and pushed.

File: crates/bevy_reflect/src/lib.rs (hunk 2 above)
Comment (MrGVSV) [reply crates/bevy_reflect/src/lib.rs:1430]: No worries! Just spreading awareness rather than critiquing haha
