### PR TITLE
Avoid bevy_reflect::List::iter wrapping in release mode

### LINKED ISSUE #13230: bevy_reflect::List::iter wraps silently on release
## Bevy version

0.13

## What you did

Iterate over a `ListIter` until overflow of its usize.

## What went wrong

You are back at the beginning.

## Proposed Fix

`ListIter` should only increment its counter when the current index is `Some`. This would fix this behaviour. It does add a branch in a potential hot spot, but I don't think its much worse when you are already reflect-ing all over the place.

## Repro

https://learnbevy.com/playground?share=679a8e4ac4eb4c72a2e1e16114eb8717da4257eb6068becaecd7ce45c51ce2be

```rust
let b = Box::new(vec![1u32]).into_reflect();

let ReflectRef::List(list) = b.reflect_ref() else {
    panic!("Not a list...");
};

let mut iter = list.iter();

let one = iter.next().unwrap();
assert_eq!(one.downcast_ref::<u32>().unwrap(), &1);

for _ in 0..(usize::MAX) {
    assert!(iter.next().is_none());
}

// We wrap around since thats what it does in release

let one = iter.next().unwrap();
assert_eq!(one.downcast_ref::<u32>().unwrap(), &1);

// Oops!

info!("We got {one:?}")
```

### PR DESCRIPTION
**Pull request by rmsthebest**
# Objective
Fixes  #13230

## Solution
Uses solution described in  #13230
They mention a worry about adding a branch, but I'm not sure there is one.

This code
```Rust
#[no_mangle]
pub fn next_if_some(num: i32, b: Option<bool>) -> i32 {
    num + b.is_some() as i32
}
```
produces this assembly with opt-level 3
```asm
next_if_some:
        xor     eax, eax
        cmp     sil, 2
        setne   al
        add     eax, edi
        ret
```

## Testing
Added test from  #13230, tagged it as ignore as it is only useful in release mode and very slow if you accidentally invoke it in debug mode.

---

## Changelog
Iterationg of ListIter will no longer overflow and wrap around

### CODE REVIEW

File: crates/bevy_reflect/src/list.rs [hunk 1]
```diff
@@ -522,4 +523,24 @@ mod tests {
             assert_eq!(index, value);
         }
     }
+    // This test needs to be run in release mode
+    #[test]
```
Comment (alice-i-cecile) [inline crates/bevy_reflect/src/list.rs:527]: This doesn't seem to be marked ignore :)

File: crates/bevy_reflect/src/list.rs [hunk 2]
```diff
@@ -401,7 +401,7 @@ impl<'a> Iterator for ListIter<'a> {
     #[inline]
     fn next(&mut self) -> Option<Self::Item> {
         let value = self.list.get(self.index);
-        self.index += 1;
+        self.index += value.is_some() as usize;
```
Comment (alice-i-cecile) [inline crates/bevy_reflect/src/list.rs:404]: Is this the right behavior? I would expect this to return `None` during an attempted overflow, not return the last item forever.

Comment (rmsthebest) [reply crates/bevy_reflect/src/list.rs:404]: if current value is something go to next, right?

File: crates/bevy_reflect/src/list.rs (hunk 1 above)
Comment (rmsthebest) [reply crates/bevy_reflect/src/list.rs:527]: i must have missed to re-commit

**Comment by Brezak** [comment]
I think you're underestimating how long the test will take.
I've written some code that should just test the increment.
```rust
use std::{hint::black_box, time::Instant};

fn next_if_some(num: u32, b: Option<bool>) -> u32 {
    num + b.is_some() as u32
}

pub fn main() {
    let mut val = 0;
    let start = Instant::now();
    for _ in 0..(u32::MAX) {
        // Both black boxes are needed to so this doesn't get optimized to a no op
        val = black_box(next_if_some(val, black_box(None)))
    }

    let elapsed = start.elapsed();
    println!("Took {:?}", start.elapsed());

    let mut projected = elapsed;
    // Attempt to calculate how long the loop would take if we tested til usize::MAX (on 64 bit cpu)
    for _ in 0..32 {
        projected *= 2;
    }

    println!("Projected for u64 {:?}", projected)
}
```
Running it on my Ryzen 7 78000x3d outputs:
```
Took 1.7983411s
Projected for u64 7723814923.0624768s
```
7723814923.0624768 seconds is 244 years!
The loop in the test might get optimized out, but I don't know if we can rely on this.

File: crates/bevy_reflect/src/list.rs (hunk 2 above)
Comment (Brezak) [reply crates/bevy_reflect/src/list.rs:404]: > Is this the right behavior? I would expect this to return `None` during an attempted overflow, not return the last item forever.

I don't see how this code would return the last element forever.

If we call `get` on the last element, `index` will be incremented one past the last element. The next time `get` is called it will be passed a value one past the last element and it should return a None.

**Comment by Brezak** [comment]
This code won't handle vecs with zsts. One can construct a vector with usize::MAX elements today, like this:
```rust
fn max_zst_vec() -> Vec<()> {
    let mut data: Vec<()> = Vec::new();
    
    // SAFETY: A zst vec has a capacity of usize::MAX
    unsafe { data.set_len(usize::MAX) }
    data
}
```
Your code will:
- Iterate to the last element.
- Get the last element.
- Increment the index.
- The index being usize::MAX overflows into 0.
- Iterator loops forever!

**Comment by Brezak** [comment]
> Maybe I'm stupid but if you have `usize::MAX` capacity the last element index is `usize::MAX-1`?

You're not stupid. I was wrong.

File: crates/bevy_reflect/src/list.rs [hunk 3]
```diff
@@ -522,4 +523,24 @@ mod tests {
             assert_eq!(index, value);
         }
     }
+
+    // This test needs to be run in release mode
+    #[ignore]
```
Comment (soqb) [inline crates/bevy_reflect/src/list.rs:528]: why not `#[cfg(not(debug_assertions))]`?

**Review by soqb — APPROVED** [review]
simple, correct change. LGTM!

File: crates/bevy_reflect/src/list.rs (hunk 3 above)
Comment (rmsthebest) [reply crates/bevy_reflect/src/list.rs]: I had never heard of that option, but it is a good idea! TIL :)

File: crates/bevy_reflect/src/list.rs (hunk 2 above)
Comment (MrGVSV) [inline crates/bevy_reflect/src/list.rs:404]: Non-blocker: While we're doing this, it would be great if we updated the other iterator types in the crate like `MapIter`, `TupleFieldIter`, etc.

File: crates/bevy_reflect/src/list.rs [hunk 4]
```diff
@@ -522,4 +524,23 @@ mod tests {
             assert_eq!(index, value);
         }
     }
+
+    #[cfg(not(debug_assertions))]
```
Comment (MrGVSV) [inline crates/bevy_reflect/src/list.rs:528]: Does CI run tests in release mode? If not, it might be something we raise an issue for such that tests like these can be run.

**Review by MrGVSV — APPROVED** [review]
Looks good! Thanks for writing the test as well!

It would be great if we could do this for the other iterator types as well, but that isn't a blocker for this PR.

File: crates/bevy_reflect/src/list.rs (hunk 2 above)
Comment (rmsthebest) [reply crates/bevy_reflect/src/list.rs:404]: I don't mind doing them now. Is it correct to update the next function in these:
	modified:   src/array.rs
	modified:   src/enums/enum_trait.rs
	modified:   src/map.rs
	modified:   src/struct_trait.rs
	modified:   src/tuple.rs
	modified:   src/tuple_struct.rs
but not in:
 src/path/parse.rs

Comment (MrGVSV) [reply crates/bevy_reflect/src/list.rs:404]: Yep! 😄

File: crates/bevy_reflect/src/array.rs [hunk 5]
```diff
@@ -374,7 +374,7 @@ impl<'a> Iterator for ArrayIter<'a> {
     #[inline]
     fn next(&mut self) -> Option<Self::Item> {
         let value = self.array.get(self.index);
-        self.index += 1;
+        self.index += value.is_some() as usize;
```
Comment (MrGVSV) [inline crates/bevy_reflect/src/array.rs:377]: Awesome! Thanks for adding these as well!

Would also be able to duplicate that test for each of these changes as well?

File: crates/bevy_reflect/src/list.rs (hunk 4 above)
Comment (soqb) [reply crates/bevy_reflect/src/list.rs:528]: [it doesn't](https://github.com/bevyengine/bevy/blob/0dddfa07ab5bdb95b0dcc1041e423678f92e83f7/tools/ci/src/commands/test.rs#L20)...

File: crates/bevy_reflect/src/array.rs (hunk 5 above)
Comment (rmsthebest) [reply crates/bevy_reflect/src/array.rs:377]: I couldnt test the overflow for most of them because I couldnt create an iterator with enough elements.
But the logic of not incrementing past the first None I can test, so I've added tests for that

**Review by MrGVSV — APPROVED** [review]
