### PR TITLE
constrain WorldQuery::init_state argument to ComponentInitializer

### LINKED ISSUE #13358: `WorldQuery::init_state` signature is too generous
> I realized that because `Storages` and `Components` aren't public fields on `World`, and there are no mutable accessor functions, doing the same change likely doesn't work for `init_state`. 
> Adding mutable accessor function does not make sense, because this would allow users to readily cause UB.
Instead we could have a function on `&mut World` that returns an opaque struct on which `init_component`, ... can be called.

_Originally posted by @Victoronz in https://github.com/bevyengine/bevy/issues/13343#issuecomment-2107782171_

### PR DESCRIPTION
**Pull request by Victoronz**
# Objective

In #13343, `WorldQuery::get_state` was constrained from `&World` as the argument to `&Components`, but `WorldQuery::init_state` hasn't yet been changed from `&mut World` to match.

Fixes #13358

## Solution

Create a wrapper around `&mut Components` and `&mut Storages` that can be obtained from `&mut World` with a `component_initializer` method. 
This new `ComponentInitializer` re-exposes the API on `&mut Components` minus the `&mut Storages` parameter where it was present. For the `&Components` API, it simply derefs to its `components` field. 

### Added
The `World::component_initializer` method.
The `ComponentInitializer` struct that re-exposes `Components` API.
### Changed
`WorldQuery::init_state` now takes `&mut ComponentInitializer` instead of `&mut World`.

## Migration Guide
Instead of passing `&mut World` to `WorldQuery::init_state` directly, pass in a mutable reference to the struct returned from `World::component_initializer`.

### CODE REVIEW

File: crates/bevy_ecs/src/component.rs [hunk 1]
```diff
@@ -763,6 +764,74 @@ impl Components {
     }
 }
 
+/// A wrapper over a mutable [`Components`] reference that allows for state initialization.
```
Comment (alice-i-cecile) [inline crates/bevy_ecs/src/component.rs:767]: This should describe how to get one of these on the next line :)

Comment (Victoronz) [reply crates/bevy_ecs/src/component.rs:767]: Added!

**Review by jdm — APPROVED** [review]
This solution makes sense to me!
