### PR TITLE
Fix crash on Linux Nvidia 550 driver

### LINKED ISSUE #12199: Resizing causes a crash on latest stable Nvidia driver 550
## Bevy version

Affects both 0.13 and main (21adeb684261eacd39acecaa8b056e0b9e918268)

## Relevant system information

```
cargo 1.76.0 (c84b36747 2024-01-18)
KDE desktop X11
```
```
AdapterInfo { name: "NVIDIA GeForce RTX 3070 Ti", vendor: 4318, device: 9346, device_type: DiscreteGpu, driver: "NVIDIA", driver_info: "550.54.14", backend: Vulkan }
SystemInfo { os: "Linux rolling EndeavourOS", kernel: "6.7.6-arch1-1", cpu: "AMD Ryzen 7 5800X3D 8-Core Processor", core_count: "8", memory: "31.3 GiB" }
```

## What you did

Run `cargo run --example window_resizing` or pretty much any example. Then drag a window corner to resize.

## What went wrong

Outputs this and crashes.
```
thread 'Compute Task Pool (6)' panicked at crates/bevy_render/src/view/window/mod.rs:357:26:
Error reconfiguring surface: Outdated
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Encountered a panic in system `bevy_render::view::window::prepare_windows`!
thread 'Compute Task Pool (1)' panicked at crates/bevy_render/src/pipelined_rendering.rs:49:67:
called `Result::unwrap()` on an `Err` value: RecvError
```

## Additional information

550 was very recently stabilized (https://www.phoronix.com/news/NVIDIA-550.54.14-Linux-Driver).

Everything starts working again if I downgrade to the 545 driver.

I tested an example from the winit repository `cargo run --example window` and there was no issues. 

Other applications I use aren't affected by this issue, so it might not be Nvidia's fault.

Complete log of the bevy example with backtrace:
```
❯ RUST_BACKTRACE=1 cargo run --example window_resizing
    Finished dev [unoptimized + debuginfo] target(s) in 0.12s
     Running `target/debug/examples/window_resizing`
2024-02-29T12:17:29.654613Z  INFO bevy_winit::system: Creating new window "App" (0v1)
2024-02-29T12:17:29.654883Z  INFO winit::platform_impl::platform::x11::window: Guessed window scale factor: 1.1666666666666667    
2024-02-29T12:17:29.722909Z  INFO bevy_render::renderer: AdapterInfo { name: "NVIDIA GeForce RTX 3070 Ti", vendor: 4318, device: 9346, device_type: DiscreteGpu, driver: "NVIDIA", driver_info: "550.54.14", backend: Vulkan }
2024-02-29T12:17:30.120325Z  INFO gilrs_core::platform::platform::gamepad: Gamepad /dev/input/event9 (Generic X-Box pad) connected.    
2024-02-29T12:17:30.203046Z  INFO bevy_diagnostic::system_information_diagnostics_plugin::internal: SystemInfo { os: "Linux rolling EndeavourOS", kernel: "6.7.6-arch1-1", cpu: "AMD Ryzen 7 5800X3D 8-Core Processor", core_count: "8", memory: "31.3 GiB" }
2024-02-29T12:17:30.215488Z  INFO bevy_input::gamepad: Gamepad { id: 0 } Connected
thread 'Compute Task Pool (6)' panicked at crates/bevy_render/src/view/window/mod.rs:357:26:
Error reconfiguring surface: Outdated
stack backtrace:
   0: rust_begin_unwind
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/result.rs:1649:5
   3: core::result::Result<T,E>::expect
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/result.rs:1030:23
   4: bevy_render::view::window::prepare_windows
             at ./crates/bevy_render/src/view/window/mod.rs:355:33
   5: core::ops::function::FnMut::call_mut
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ops/function.rs:166:5
   6: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ops/function.rs:294:13
   7: <Func as bevy_ecs::system::function_system::SystemParamFunction<fn(F0,F1,F2,F3,F4,F5,F6,F7,F8) .> Out>>::run::call_inner
             at ./crates/bevy_ecs/src/system/function_system.rs:661:21
   8: <Func as bevy_ecs::system::function_system::SystemParamFunction<fn(F0,F1,F2,F3,F4,F5,F6,F7,F8) .> Out>>::run
             at ./crates/bevy_ecs/src/system/function_system.rs:664:17
   9: <bevy_ecs::system::function_system::FunctionSystem<Marker,F> as bevy_ecs::system::system::System>::run_unsafe
             at ./crates/bevy_ecs/src/system/function_system.rs:504:19
  10: bevy_ecs::schedule::executor::multi_threaded::ExecutorState::spawn_system_task::{{closure}}::{{closure}}
             at ./crates/bevy_ecs/src/schedule/executor/multi_threaded.rs:621:26
  11: core::ops::function::FnOnce::call_once
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ops/function.rs:250:5
  12: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panic/unwind_safe.rs:272:9
  13: std::panicking::try::do_call
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:552:40
  14: __rust_try
  15: std::panicking::try
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:516:19
  16: std::panic::catch_unwind
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panic.rs:142:14
  17: bevy_ecs::schedule::executor::multi_threaded::ExecutorState::spawn_system_task::{{closure}}
             at ./crates/bevy_ecs/src/schedule/executor/multi_threaded.rs:614:23
  18: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::future::future::Future>::poll
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panic/unwind_safe.rs:297:9
  19: <futures_lite::future::CatchUnwind<F> as core::future::future::Future>::poll::{{closure}}
             at /home/eero/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-lite-2.2.0/src/future.rs:588:42
  20: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panic/unwind_safe.rs:272:9
  21: std::panicking::try::do_call
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:552:40
  22: __rust_try
  23: std::panicking::try
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:516:19
  24: std::panic::catch_unwind
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panic.rs:142:14
  25: <futures_lite::future::CatchUnwind<F> as core::future::future::Future>::poll
             at /home/eero/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-lite-2.2.0/src/future.rs:588:9
  26: async_executor::Executor::spawn::{{closure}}
             at /home/eero/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-executor-1.8.0/src/lib.rs:158:20
  27: async_task::raw::RawTask<F,T,S,M>::run::{{closure}}
             at /home/eero/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-task-4.7.0/src/raw.rs:550:21
  28: core::ops::function::FnOnce::call_once
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ops/function.rs:250:5
  29: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panic/unwind_safe.rs:272:9
  30: std::panicking::try::do_call
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:552:40
  31: __rust_try
  32: std::panicking::try
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:516:19
  33: std::panic::catch_unwind
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panic.rs:142:14
  34: async_task::raw::RawTask<F,T,S,M>::run
             at /home/eero/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-task-4.7.0/src/raw.rs:549:23
  35: async_task::runnable::Runnable<M>::run
             at /home/eero/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-task-4.7.0/src/runnable.rs:781:18
  36: async_executor::Executor::run::{{closure}}::{{closure}}
             at /home/eero/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-executor-1.8.0/src/lib.rs:254:21
  37: <futures_lite::future::Or<F1,F2> as core::future::future::Future>::poll
             at /home/eero/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-lite-2.2.0/src/future.rs:449:33
  38: async_executor::Executor::run::{{closure}}
             at /home/eero/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-executor-1.8.0/src/lib.rs:261:32
  39: futures_lite::future::block_on::{{closure}}
             at /home/eero/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-lite-2.2.0/src/future.rs:99:19
  40: std::thread::local::LocalKey<T>::try_with
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/thread/local.rs:270:16
  41: std::thread::local::LocalKey<T>::with
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/thread/local.rs:246:9
  42: futures_lite::future::block_on
             at /home/eero/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-lite-2.2.0/src/future.rs:78:5
  43: bevy_tasks::task_pool::TaskPool::new_internal::{{closure}}::{{closure}}::{{closure}}::{{closure}}
             at ./crates/bevy_tasks/src/task_pool.rs:180:37
  44: std::panicking::try::do_call
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:552:40
  45: __rust_try
  46: std::panicking::try
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:516:19
  47: std::panic::catch_unwind
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panic.rs:142:14
  48: bevy_tasks::task_pool::TaskPool::new_internal::{{closure}}::{{closure}}::{{closure}}
             at ./crates/bevy_tasks/src/task_pool.rs:174:43
  49: std::thread::local::LocalKey<T>::try_with
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/thread/local.rs:270:16
  50: std::thread::local::LocalKey<T>::with
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/thread/local.rs:246:9
  51: bevy_tasks::task_pool::TaskPool::new_internal::{{closure}}::{{closure}}
             at ./crates/bevy_tasks/src/task_pool.rs:167:25
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Encountered a panic in system `bevy_render::view::window::prepare_windows`!
thread 'Compute Task Pool (0)' panicked at crates/bevy_render/src/pipelined_rendering.rs:49:67:
called `Result::unwrap()` on an `Err` value: RecvError
stack backtrace:
   0: rust_begin_unwind
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/result.rs:1649:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/result.rs:1073:23
   4: bevy_render::pipelined_rendering::RenderAppChannels::recv::{{closure}}
             at ./crates/bevy_render/src/pipelined_rendering.rs:49:26
   5: bevy_render::pipelined_rendering::update_rendering::{{closure}}::{{closure}}::{{closure}}::{{closure}}
             at ./crates/bevy_render/src/pipelined_rendering.rs:185:60
   6: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::future::future::Future>::poll
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panic/unwind_safe.rs:297:9
   7: <futures_lite::future::CatchUnwind<F> as core::future::future::Future>::poll::{{closure}}
             at /home/eero/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-lite-2.2.0/src/future.rs:588:42
   8: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panic/unwind_safe.rs:272:9
   9: std::panicking::try::do_call
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:552:40
  10: __rust_try
  11: std::panicking::try
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:516:19
  12: std::panic::catch_unwind
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panic.rs:142:14
  13: <futures_lite::future::CatchUnwind<F> as core::future::future::Future>::poll
             at /home/eero/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-lite-2.2.0/src/future.rs:588:9
  14: async_executor::Executor::spawn::{{closure}}
             at /home/eero/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-executor-1.8.0/src/lib.rs:158:20
  15: async_task::raw::RawTask<F,T,S,M>::run::{{closure}}
             at /home/eero/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-task-4.7.0/src/raw.rs:550:21
  16: core::ops::function::FnOnce::call_once
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ops/function.rs:250:5
  17: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panic/unwind_safe.rs:272:9
  18: std::panicking::try::do_call
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:552:40
  19: __rust_try
  20: std::panicking::try
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:516:19
  21: std::panic::catch_unwind
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panic.rs:142:14
  22: async_task::raw::RawTask<F,T,S,M>::run
             at /home/eero/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-task-4.7.0/src/raw.rs:549:23
  23: async_task::runnable::Runnable<M>::run
             at /home/eero/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-task-4.7.0/src/runnable.rs:781:18
  24: async_executor::Executor::run::{{closure}}::{{closure}}
             at /home/eero/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-executor-1.8.0/src/lib.rs:254:21
  25: <futures_lite::future::Or<F1,F2> as core::future::future::Future>::poll
             at /home/eero/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-lite-2.2.0/src/future.rs:449:33
  26: async_executor::Executor::run::{{closure}}
             at /home/eero/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-executor-1.8.0/src/lib.rs:261:32
  27: futures_lite::future::block_on::{{closure}}
             at /home/eero/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-lite-2.2.0/src/future.rs:99:19
  28: std::thread::local::LocalKey<T>::try_with
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/thread/local.rs:270:16
  29: std::thread::local::LocalKey<T>::with
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/thread/local.rs:246:9
  30: futures_lite::future::block_on
             at /home/eero/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-lite-2.2.0/src/future.rs:78:5
  31: bevy_tasks::task_pool::TaskPool::new_internal::{{closure}}::{{closure}}::{{closure}}::{{closure}}
             at ./crates/bevy_tasks/src/task_pool.rs:180:37
  32: std::panicking::try::do_call
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:552:40
  33: __rust_try
  34: std::panicking::try
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:516:19
  35: std::panic::catch_unwind
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panic.rs:142:14
  36: bevy_tasks::task_pool::TaskPool::new_internal::{{closure}}::{{closure}}::{{closure}}
             at ./crates/bevy_tasks/src/task_pool.rs:174:43
  37: std::thread::local::LocalKey<T>::try_with
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/thread/local.rs:270:16
  38: std::thread::local::LocalKey<T>::with
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/thread/local.rs:246:9
  39: bevy_tasks::task_pool::TaskPool::new_internal::{{closure}}::{{closure}}
             at ./crates/bevy_tasks/src/task_pool.rs:167:25
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### PR DESCRIPTION
**Pull request by eero-lehtinen**
# Objective

Fix crashing on Linux with latest stable Nvidia 550 driver when resizing. The crash happens at startup with some setups.

Fixes #12199

I think this would be nice to get into 0.13.1

## Solution

Ignore `wgpu::SurfaceError::Outdated` always on this platform+driver.

It looks like Nvidia considered the previous behaviour of not returning this error a bug:
"Fixed a bug where vkAcquireNextImageKHR() was not returning VK_ERROR_OUT_OF_DATE_KHR when it should with WSI X11 swapchains" (https://www.nvidia.com/Download/driverResults.aspx/218826/en-us/)

What I gather from this is that the surface was outdated on previous drivers too, but they just didn't report it as an error. So behaviour shouldn't change.

In the issue conversation we experimented with calling `continue` when this error happens, but I found that it results in some small issues like bevy_egui scale not updating with the window sometimes. Just doing nothing seems to work better.

## Changelog

- Fixed crashing on Linux with Nvidia 550 driver when resizing the window

### CODE REVIEW

**Comment by eero-lehtinen** [comment]
Looks like I'm also undoing a change from https://github.com/bevyengine/bevy/pull/12055, where `configure_surface` was removed from being called on resize. But looking at the conversation, it was removed to improve linux issues. So this should be fine.

File: crates/bevy_render/src/view/window/mod.rs [hunk 1]
```diff
@@ -304,38 +304,52 @@ pub fn prepare_windows(
...
-                    let frame = surface
-                        .get_current_texture()
-                        .expect("Error reconfiguring surface");
-                    window.set_swapchain_texture(frame);
-                }
-                #[cfg(target_os = "linux")]
-                Err(wgpu::SurfaceError::Timeout) if may_erroneously_timeout() => {
-                    bevy_utils::tracing::trace!(
-                        "Couldn't get swap chain texture. This is probably a quirk \
+            render_device.configure_surface(surface, &surface_data.configuration);
```
Comment (mockersf) [inline crates/bevy_render/src/view/window/mod.rs:327]: this won't work on iOS.

In those case this should have already been called in system `create_surfaces`, could you remove it from here?

Comment (mockersf) [inline crates/bevy_render/src/view/window/mod.rs:327]: this won't work on iOS.

In those cases this should have already been called in system `create_surfaces`, could you remove it from here?

Comment (eero-lehtinen) [reply crates/bevy_render/src/view/window/mod.rs]: Yeah I guess I need to change my approach. This worked on 0.13.0

Comment (eero-lehtinen) [reply crates/bevy_render/src/view/window/mod.rs]: Now it whould be better.

**Comment by eero-lehtinen** [comment]
CI timed out but logs say that test was successful. Is this a real error?

**Comment by WarrenHood** [comment]
Why not just always ignore surface outdated errors?

**Comment by eero-lehtinen** [comment]
> Why not just always ignore surface outdated errors? Rather than only for linux with nvidia 550 drivers

The error is not expected anywhere else. But yeah always ignoring it would reduce the amount of code. I'm not opposed to doing it that way.

**Comment by eero-lehtinen** [comment]
> CI timed out but logs say that test was successful. Is this a real error?

The error was real but now fixed.

**Comment by notverymoe** [comment]
I'm concerned about specifically checked for the 550 driver. This seems to be a "fix" by nvidia, so 560, 570 etc. will contain this behaviour. And given that the error was effectively ignored in versions prior to 550, I think this should be safe to just ignore on Nvidia Linux?

**Comment by eero-lehtinen** [comment]
> I'm concerned about specifically checked for the 550 driver. This seems to be a fix by nvidia, so 560, 570 etc. will contain this behaviour. And given that the error was effectively ignored in versions prior to 550, I think this should be safe to just ignore on Nvidia Linux as a whole?

Yeah it was a panic before so it shouldn't be too bad to ignore it. I'll do that.

**Review by torsteingrindvik — APPROVED** [review]
Not a windowing expert, but cherry-picking these commits solved various crashes I get since I'm on linux + new Nvidia drivers so I'm very happy with this.

**Comment by IceSentry** [comment]
Why did you remove the `not_already_configured` related code? It seems unrelated to me?

**Comment by eero-lehtinen** [comment]
> Why did you remove the `not_already_configured` related code? It seems unrelated to me?

After https://github.com/bevyengine/bevy/pull/12055 both branches do the same thing. I didn't want to copy paste my check for both branches, removed the first. But I guess it's not this PRs job to fix, so I can also make my changes as minimal as possible if needed.

**Review by IQuick143 — APPROVED** [review]
I can't say anything about the changes themselves as I don't understand windowing code, but testing on my machine I can confirm this does resolve the issue. (Void Linux, X.Org, nvidia-550.54.14_1 driver)

**Review by james7132 — COMMENTED** [review]
Silently absorbing the error seems like a future issue waiting to happen. Can we downgrade this to an error or warning log?

**Comment by eero-lehtinen** [comment]
> Silently absorbing the error seems like a future issue waiting to happen. Can we downgrade this to an error or warning log?

I added a debug level log because it happens pretty often there is no way to fix it.

**Comment by james7132** [comment]
> I added a debug level log because it happens pretty often and there is no way to fix it.

An `error_once` or `warn_once` should log it once and then black hole the rest.

**Review by james7132 — APPROVED** [review]

File: crates/bevy_render/src/view/window/mod.rs [hunk 2]
```diff
@@ -304,19 +306,41 @@ pub fn prepare_windows(
                 })
         };
 
+        #[cfg(target_os = "linux")]
+        let is_nvidia = || {
+            render_instance
+                .enumerate_adapters(wgpu::Backends::VULKAN)
+                .iter()
+                .any(|adapter| adapter.get_info().name.starts_with("NVIDIA"))
```
Comment (IceSentry) [inline crates/bevy_render/src/view/window/mod.rs:314]: I'm not sure if `starts_with()` is good enough here. We've had a bug somewhere else because the vendor name wasn't at the start.

Comment (eero-lehtinen) [reply crates/bevy_render/src/view/window/mod.rs:314]: In addition to the `name` field there seems to be `driver` that just says "NVIDIA" and nothing else. Would that be better? I don't have other cards to test with.

Comment (tbvanderwoude) [reply crates/bevy_render/src/view/window/mod.rs:314]: Not sure how quirky these `AdapterInfo` strings can get but maybe just changing it to `name.to_uppercase().contains("NVIDIA")` could work. You could also add a fallback check of the `driver` string to account for cases in which the `name` would not match on an NVIDIA device, no idea if this would be necessary though. This is out of the scope of this PR but the same `starts_with()` method is currently used in defining `may_erroneously_timeout` in the lines above.

Comment (eero-lehtinen) [reply crates/bevy_render/src/view/window/mod.rs:314]: I wouldn't add random extra checks if we don't know what edge case we are handling. This has worked fine for everyone who tested it.

Comment (eero-lehtinen) [reply crates/bevy_render/src/view/window/mod.rs:314]: Checking for vendor id would probably be the best for reliability.

Comment (torsteingrindvik) [reply crates/bevy_render/src/view/window/mod.rs:314]: I can confirm with a little test system that this spams `true`:

```rust
fn vendor_info_hex(adapter: Res<RenderAdapter>) {
    let nvidia = 0x10de;
    let vendor = adapter.get_info().vendor;

    info!("Is nvidia? {}", vendor == nvidia);
}
```

found the ID value here: https://envytools.readthedocs.io/en/latest/hw/pciid.html#introduction

Comment (torsteingrindvik) [reply crates/bevy_render/src/view/window/mod.rs:314]: According to wgpu there might be other bytes non-zero: https://docs.rs/wgpu/latest/wgpu/struct.AdapterInfo.html#structfield.vendor

in the ID, so might need to mask off only the 16 bits we care about

```rust
let vendor = adapter.get_info().vendor & 0xFFFF;
```

Comment (eero-lehtinen) [reply crates/bevy_render/src/view/window/mod.rs]: Thanks for investigating. I made this change. An enum based abstraction for the vendor check would probably be nice and should be used everywhere instead of strings.

File: crates/bevy_render/src/view/window/mod.rs [hunk 3]
```diff
@@ -304,19 +309,41 @@ pub fn prepare_windows(
...
-                .get_current_texture()
-                .expect("Error configuring surface");
-            window.set_swapchain_texture(frame);
+            match surface.get_current_texture() {
+                Ok(frame) => window.set_swapchain_texture(frame),
+                #[cfg(target_os = "linux")]
+                Err(wgpu::SurfaceError::Outdated) if is_nvidia() => {
+                    warn_once!(
+                        "Couldn't get swap chain texture. This often happens with \
+                        the Nvidia 550 driver. It can be safely ignored."
```
Comment (james7132) [inline crates/bevy_render/src/view/window/mod.rs:330]:
```suggestion
                        the NVIDIA drivers on Linux. It can be safely ignored."
```

**Review by IceSentry — APPROVED** [review]
