### PR TITLE
Fix shader import hot reloading on windows

### LINKED ISSUE #10500: Shader hot reloading no longer works for locally imported shaders
## Bevy version 0.12

In 0.11 it was possible to hot reload locally imported shaders. This no longer works in 0.12.

```wgsl
#import "shaders/bar.wgsl"::bar
[...]
let a = bar(frag_coord);
```

If I try to edit `shaders/bar.wgsl` I get:

```wgsl
2023-11-10T21:55:48.695089Z  INFO bevy_asset::server: Reloading shaders\bar.wgsl because it has changed
2023-11-10T21:55:48.707801Z ERROR bevy_render::render_resource::pipeline_cache: failed to process shader:
error: required import '"shaders/bar.wgsl"' not found
   ┌─ shaders/foo.wgsl:83:13
   │
83 │     let a = bar(frag_coord);
   │             ^
   │
   = missing import '"shaders/bar.wgsl"'
```

### PR DESCRIPTION
**Pull request by cart**
# Objective

Hot reloading shader imports on windows is currently broken due to inconsistent `/` and `\` usage ('/` is used in the user facing APIs and `\` is produced by notify-rs (and likely other OS apis).

Fixes #10500

## Solution

Standardize import paths when loading a `Shader`. The correct long term fix is to standardize AssetPath on `/`-only, but this is the right scope of fix for a patch release.

### CODE REVIEW

File: crates/bevy_render/src/render_resource/shader.rs [hunk 1]
```diff
@@ -259,30 +259,24 @@ impl AssetLoader for ShaderLoader {
     ) -> BoxedFuture<'a, Result<Shader, Self::Error>> {
         Box::pin(async move {
             let ext = load_context.path().extension().unwrap().to_str().unwrap();
-
+            let path = load_context.asset_path().to_string();
+            // On windows, the path will inconsistently use \ or /.
+            // TODO: remove this once AssetPath forces cross-platform "slash" consistency
```
Comment (afonsolage) [inline crates/bevy_render/src/render_resource/shader.rs:264]: We already have an issue open for that, or is it tracked inside any existing issue?

I always find a good idea linking also the issue on TODO, to keep track when the TODO should be removed.

Comment (cart) [reply crates/bevy_render/src/render_resource/shader.rs]: Good call! Created the issue and added a reference.

**Comment by cart** [comment]
@DGriffin91 has confirmed that this fixes the issue for them.

**Review by hymm — APPROVED** [review]
Code looks good to me and I trust DGriffin's testing.

File: crates/bevy_render/src/render_resource/shader.rs [hunk 2]
```diff
@@ -259,30 +259,24 @@ impl AssetLoader for ShaderLoader {
     ) -> BoxedFuture<'a, Result<Shader, Self::Error>> {
         Box::pin(async move {
             let ext = load_context.path().extension().unwrap().to_str().unwrap();
-
+            let path = load_context.asset_path().to_string();
+            // On windows, the path will inconsistently use \ or /.
+            // TODO: remove this once AssetPath forces cross-platform "slash" consistency. See #10511
+            let path = path.replace("\\", "/");
```
Comment (mockersf) [inline crates/bevy_render/src/render_resource/shader.rs:265]:
```suggestion
            let path = path.replace(std::path::MAIN_SEPARATOR, "/");
```
should work if someday there's a platform with another kind of separator...

**Review by mockersf — APPROVED** [review]
