### PR TITLE
Fix for 22822 ComputedStates example

### LINKED ISSUE #22822: computed_states example broken
## Bevy version and features

- 0.18.0
- bevy_dev_tools

## What you did

While running the computed_states example, pausing or activating the turbo causes a duplicate sprite to be produced. 

## What went wrong

State transitions for ComputedStates are not idempotent and will trigger OnEnter schedules per underlying state change without their corresponding OnExit schedules.

The provided example for ComputedStates will rerun the setup_game system and produce an additional sprite per pause or turbo switch.

## Additional information

The behavior change occured on Pull Request #21792

On crates/bevy_state/src/state/computed_states.rs:79 
`    /// Whether state transition schedules should be run when the state changes to the same value. Default is `true`.
    const ALLOW_SAME_STATE_TRANSITIONS: bool = true;
`
Setting the flag to false returns the example to 0.17.0 behavior.

I'm very new to Bevy, so I'm unsure if this should be considered a bug in Bevy or an example that needs updated to meet new behavior.

### PR DESCRIPTION
**Pull request by scottgshannon**
# Objective

- Fixes #22822

## Solution

- Adds ALLOW_SAME_STATE_TRANSITIONS = false to ComputedStates in computed_states example

## Testing

- Tested by running example on  x86_64 Linux 4.19 + KDE.  Behavior noted in #22822 no longer occurs.

### CODE REVIEW

File: examples/state/computed_states.rs [hunk 1]
```diff
@@ -54,6 +54,7 @@ impl ComputedStates for InGame {
     // Our computed state depends on `AppState`, so we need to specify it as the SourceStates type.
     type SourceStates = AppState;
 
+    const ALLOW_SAME_STATE_TRANSITIONS: bool = false;
```
Comment (kfc35) [inline examples/state/computed_states.rs:59]: I checked out your branch and for my Mac, and I believe only this line is necessary to resolve the issue where `setup_game` triggers whenever `paused` and `Turbo` are toggled. Are you sure you need the other two `ALLOW_SAME_STATE_TRANSITIONS` as well? I would suggest removing the other two if they are not necessary.

```suggestion
    // This is necessary to prevent `setup_game` from running when the app is already in `AppState::InGame`
    // and only `paused` and `turbo` are changed
    const ALLOW_SAME_STATE_TRANSITIONS: bool = false;
```

File: examples/state/computed_states.rs [hunk 2]
```diff
@@ -80,6 +81,7 @@ struct TurboMode;
 
 impl ComputedStates for TurboMode {
     type SourceStates = AppState;
+    const ALLOW_SAME_STATE_TRANSITIONS: bool = false;
```
Comment (kfc35) [inline examples/state/computed_states.rs:86]: If you verify that you actually don’t need this line:
```suggestion
```

File: examples/state/computed_states.rs [hunk 3]
```diff
@@ -107,6 +109,7 @@ enum IsPaused {
 
 impl ComputedStates for IsPaused {
     type SourceStates = AppState;
+    const ALLOW_SAME_STATE_TRANSITIONS: bool = false;
```
Comment (kfc35) [inline examples/state/computed_states.rs:114]: If you verify that you actually don’t need this line:
```suggestion
```

File: examples/state/computed_states.rs (hunk 2 above)
Comment (scottgshannon) [reply examples/state/computed_states.rs:86]: TurboMode can be re-entered (via activating turbo then pausing).  This produces duplicate UI elements that overlap and thus don't cause visual artifacts.

File: examples/state/computed_states.rs (hunk 3 above)
Comment (scottgshannon) [reply examples/state/computed_states.rs:114]: While IsPaused cannot be re-entered it is tied to an OnEnter system that performs command.spawn calls like the other computed states.  This line could be removed and retain proper behavior but I believe the example is stronger by keeping it.

File: examples/state/computed_states.rs (hunk 2 above)
Comment (kfc35) [reply examples/state/computed_states.rs:86]: Ah I see, I overlooked that, thank you for pointing that out

**Review by mnmaita — APPROVED** [review]
