### PR TITLE
Make default behavior for `BackgroundColor` and `BorderColor` more intuitive

### LINKED ISSUE #13969: Styling regression: ButtonBundle background color
## Bevy version

[v0.14.0-rc.3](https://github.com/bevyengine/bevy/releases/tag/v0.14.0-rc.3)

## What you did

I have styled `ButtonBundle` background colors.

## What went wrong

The `BackgroundColor` component has been removed from the `ButtonBundle`. However, even if one were to add it back in,
the color is _overriden_ by the `UiImage`'s `color`, unless explicitly set to transparent.

## Additional context

This was changed in https://github.com/bevyengine/bevy/pull/11165

### PR DESCRIPTION
**Pull request by alice-i-cecile**
# Objective

In Bevy 0.13, `BackgroundColor` simply tinted the image of any `UiImage`. This was confusing: in every other case (e.g. Text), this added a solid square behind the element. #11165 changed this, but removed `BackgroundColor` from `ImageBundle` to avoid confusion, since the semantic meaning had changed.

However, this resulted in a serious UX downgrade / inconsistency, as this behavior was no longer part of the bundle (unlike for `TextBundle` or `NodeBundle`), leaving users with a relatively frustrating upgrade path.

Additionally, adding both `BackgroundColor` and `UiImage` resulted in a bizarre effect, where the background color was seemingly ignored as it was covered by a solid white placeholder image.

Fixes #13969.

## Solution

Per @viridia's design:

> - if you don't specify a background color, it's transparent.
> - if you don't specify an image color, it's white (because it's a multiplier).
> - if you don't specify an image, no image is drawn.
> - if you specify both a background color and an image color, they are independent.
> - the background color is drawn behind the image (in whatever pixels are transparent)

As laid out by @benfrankel, this involves:

1. Changing the default `UiImage` to use a transparent texture but a pure white tint.
2. Adding `UiImage::solid_color` to quickly set placeholder images.
3. Changing the default `BorderColor` and `BackgroundColor` to transparent.
4. Removing the default overrides for these values in the other assorted UI bundles.
5. Adding `BackgroundColor` back to `ImageBundle` and `ButtonBundle`.
6. Adding a 1x1 `Image::transparent`, which can be accessed from `Assets<Image>` via the `TRANSPARENT_IMAGE_HANDLE` constant.

Huge thanks to everyone who helped out with the design in the linked issue and [the Discord thread](https://discord.com/channels/691052431525675048/1255209923890118697/1255209999278280844): this was very much a joint design.

@cart helped me figure out how to set the UiImage's default texture to a transparent 1x1 image, which is a much nicer fix.

## Testing

I've checked  the examples modified by this PR, and the `ui` example as well just to be sure.

## Migration Guide

- `BackgroundColor` no longer tints the color of images in `ImageBundle` or `ButtonBundle`. Set `UiImage::color` to tint images instead.
- The default texture for `UiImage` is now a transparent white square.  Use `UiImage::solid_color` to quickly draw debug images.
-  The default value for `BackgroundColor` and `BorderColor` is now transparent. Set the color to white manually to return to previous behavior.

### CODE REVIEW

File: crates/bevy_ui/src/ui_node.rs [hunk 1]
```diff
@@ -1819,10 +1821,15 @@ impl Outline {
...
-#[derive(Component, Clone, Debug, Reflect, Default)]
+#[derive(Component, Clone, Debug, Reflect)]
 #[reflect(Component, Default)]
 pub struct UiImage {
-    /// The tint color used to draw the image
+    /// The tint color used to draw the image.
+    ///
+    /// # Warning
+    ///
+    /// This defaults to transparent white,
```
Comment (pablo-lua) [inline crates/bevy_ui/src/ui_node.rs:1831]: I'm a little confused with the word transparent here, as this can be seen as rgba(1, 1, 1, 0) (white but transparent), but in reality its literally white.
And in fact, now both the Color::default and UiImage::default will lead to white, so the image will show up. 
I guess we can warn the user about the fact that the Color here is multiplied with the img, so white will be the original colors and transparent will be nothing.

File: crates/bevy_ui/src/ui_node.rs [hunk 2]
```diff
@@ -1832,14 +1839,43 @@ pub struct UiImage {
...
 }
 
+impl Default for UiImage {
+    /// A solid square, with a transparent white color.
+    fn default() -> Self {
+        UiImage {
+            // This needs to be transparent by default, to avoid covering the background color
+            // This should be white because the tint is multiplied with the image,
+            // so if you set an actual image with default tint you'd want its original colors
+            color: Color::from(LinearRgba::new(1.0, 1.0, 1.0, 0.0)),
```
Comment (pablo-lua) [inline crates/bevy_ui/src/ui_node.rs:1849]: Isn't the Color default already pure white? :thinking:

Comment (alice-i-cecile) [reply crates/bevy_ui/src/ui_node.rs:1849]: It's solid white, not transparent white.

Comment (benfrankel) [inline crates/bevy_ui/src/ui_node.rs:1849]: Ideally the default `color` should be `Color::WHITE`, and the default `texture` should (somehow) be a transparent square. Otherwise `UiImage { texture: my_image, ..default() }` will be invisible. Using `UiImage::new(my_image)` instead does work, at least.

Comment (pablo-lua) [reply crates/bevy_ui/src/ui_node.rs:1849]: Oh yeah, My bad.

**Review by eidloi — APPROVED** [review]
works for me!

File: crates/bevy_ui/src/ui_node.rs (hunk 1 above)
Comment (pablo-lua) [reply crates/bevy_ui/src/ui_node.rs:1831]: Now I understand the part about transparent white, though I need to test how this will go in some example. But how about we have the explanation here so the user know the implication of this color as a field itself?

**Review by benfrankel — COMMENTED** [review]
The examples that were updated to use `UiImage::color` as a solid background for buttons should be reverted back to `BackgroundColor`. This isn't blocking 0.14 release though, so it can be a separate PR.

File: crates/bevy_ui/src/ui_node.rs (hunk 1 above)
Comment (alice-i-cecile) [reply crates/bevy_ui/src/ui_node.rs:1831]: > I'm a little confused with the word transparent here, as this can be seen as rgba(1, 1, 1, 0) (white but transparent), but in reality its literally white.

I'm quite confused by this comment.

File: crates/bevy_ui/src/ui_node.rs (hunk 2 above)
Comment (benfrankel) [reply crates/bevy_ui/src/ui_node.rs:1849]: If this behavior is considered acceptable, I'm fine with approving this PR, since everything else looks good to me.

File: crates/bevy_ui/src/ui_node.rs (hunk 1 above)
Comment (pablo-lua) [reply crates/bevy_ui/src/ui_node.rs:1831]: > > I'm a little confused with the word transparent here, as this can be seen as rgba(1, 1, 1, 0) (white but transparent), but in reality its literally white.
> 
> I'm quite confused by this comment.

Yeah, this was regarding me not seeing that this was transparent white (comment below). You can ignore that part now.

File: crates/bevy_ui/src/ui_node.rs (hunk 2 above)
Comment (alice-i-cecile) [reply crates/bevy_ui/src/ui_node.rs:1849]: Unfortunately changing the default Image to be transparent will be very annoying for sprites, since then spawning a sprite will seemingly nothing by default.

It's also badly breaking in a much more complex way. I don't like this either, but I don't see a better way forward.

Comment (benfrankel) [reply crates/bevy_ui/src/ui_node.rs:1855]: Could there be like `Handle::<Image>::transparent()`?

Comment (alice-i-cecile) [reply crates/bevy_ui/src/ui_node.rs:1855]: This would require us to somehow register this by default during the asset initialization of `Image`. I'm not sure how to do that, and I'm worried about the increased scope.

**Review by pablo-lua — APPROVED** [review]
I think we can follow up with that to the next release, LGTM

File: crates/bevy_render/src/texture/mod.rs [hunk 3]
```diff
@@ -43,6 +43,14 @@ use bevy_app::{App, Plugin};
 use bevy_asset::{AssetApp, Assets, Handle};
 use bevy_ecs::prelude::*;
 
+/// A handle to a 1 x 1 transparent white image.
+///
+/// Like [`Handle<Image>::default`], this is a handle to a fallaback image asset.
```
Comment (benfrankel) [inline crates/bevy_render/src/texture/mod.rs:48]: Minor typo: fallaback -> fallback

File: crates/bevy_render/src/texture/mod.rs [hunk 4]
```diff
@@ -43,6 +43,14 @@ use bevy_app::{App, Plugin};
...
+/// While that handle points to an opaque white 1 x 1 image, this handle points to a 1 x 1 transparent white image.
```
Comment (benfrankel) [inline crates/bevy_render/src/texture/mod.rs:49]: Tiny nit: "1 x 1 transparent white" -> "transparent white 1 x 1" so the two things being compared are parallel.

File: crates/bevy_ui/src/ui_node.rs [hunk 5]
```diff
@@ -1819,27 +1821,67 @@ impl Outline {
...
 }
 
+impl Default for UiImage {
+    /// A transparent 1x1 image with a solid white tint.
+    ///
+    /// # Warning
+    ///
+    /// This will be invisible by default.
+    /// To set this to a visible image, you need to set the `texture` field to a valid image handle,
+    /// or use [`Handle<Image>`]'s default 1x1 solid white texture.
```
Comment (benfrankel) [inline crates/bevy_ui/src/ui_node.rs:1849]: Maybe mention `UiImage::solid_color` here specifically.

**Review by benfrankel — CHANGES_REQUESTED** [review]
Small nits. Approved other than that.

File: crates/bevy_render/src/texture/mod.rs [hunk 6]
```diff
@@ -43,6 +43,14 @@ use bevy_app::{App, Plugin};
...
+// Number randomly selected by fair WolframAlpha query. Totally arbitrary.
```
Comment (eidloi) [inline crates/bevy_render/src/texture/mod.rs:50]: better than a fair dice roll (xkcd)!

File: crates/bevy_render/src/texture/image.rs [hunk 7]
```diff
@@ -531,6 +531,38 @@ impl Image {
         image
     }
 
+    /// A transparent white 1x1x1 image.
+    ///
+    /// Contrast to [`Image::default`], which is opaque.
+    pub fn transparent() -> Image {
+        // We rely on the default texture format being RGBA8UnormSrgb
+        // when constructing a transparent color from bytes.
+        // If this changes, this function will need to be updated.
```
Comment (eidloi) [inline crates/bevy_render/src/texture/image.rs:540]: How will we find out? Will it fail to compile?

File: crates/bevy_ui/src/ui_node.rs [hunk 8]
```diff
@@ -1819,27 +1821,67 @@ impl Outline {
...
+    /// The tint color used to draw the image.
+    ///
+    /// This is multiplied by the color of each pixel in the image.
+    /// The field value defaults to solid white, which will pass the image through unmodified.
     pub color: Color,
-    /// Handle to the texture
+    /// Handle to the texture.
+    ///
+    /// This defaults to a fully transparent 1x1 texture.
     pub texture: Handle<Image>,
```
Comment (eidloi) [inline crates/bevy_ui/src/ui_node.rs:1835]: Maybe note, that using a `Handle::default()` will render solid white?

**Review by eidloi — APPROVED** [review]
Yeah this is a lot more elegant! Thanks!

File: crates/bevy_render/src/texture/mod.rs (hunk 3 above)
Comment (alice-i-cecile) [reply crates/bevy_render/src/texture/mod.rs:48]:
```suggestion
/// Like [`Handle<Image>::default`], this is a handle to a fallback image asset.
```

File: crates/bevy_render/src/texture/mod.rs (hunk 4 above)
Comment (alice-i-cecile) [reply crates/bevy_render/src/texture/mod.rs:49]:
```suggestion
/// While that handle points to an opaque white 1 x 1 image, this handle points to a transparent 1 x 1 white image.
```

File: crates/bevy_ui/src/ui_node.rs (hunk 5 above)
Comment (alice-i-cecile) [reply crates/bevy_ui/src/ui_node.rs:1849]:
```suggestion
    /// or use [`Handle<Image>`]'s default 1x1 solid white texture (as is done in [`UiImage::solid_color`]).
```

File: crates/bevy_render/src/texture/image.rs (hunk 7 above)
Comment (alice-i-cecile) [reply crates/bevy_render/src/texture/image.rs:540]: This will panic when the examples are run :)

File: crates/bevy_ui/src/ui_node.rs [hunk 9]
```diff
@@ -1819,27 +1821,67 @@ impl Outline {
...
-    /// The tint color used to draw the image
+    /// The tint color used to draw the image.
+    ///
+    /// This is multiplied by the color of each pixel in the image.
+    /// The field value defaults to solid white, which will pass the image through unmodified.
     pub color: Color,
-    /// Handle to the texture
+    /// Handle to the texture.
+    ///
+    /// This defaults to a fully transparent 1x1 texture.
```
Comment (alice-i-cecile) [inline crates/bevy_ui/src/ui_node.rs:1834]:
```suggestion
    /// This defaults to a [`TRANSPARENT_IMAGE_HANDLE`], which points to a fully transparent 1x1 texture.
```

**Review by lufog — COMMENTED** [review]
I guess it was missed

https://github.com/bevyengine/bevy/blob/bd7dcd3f6ddd3cf7934c8c76bab2bad624b3e24c/examples/ui/button.rs#L32C17-L32C46

https://github.com/bevyengine/bevy/blob/bd7dcd3f6ddd3cf7934c8c76bab2bad624b3e24c/examples/ui/button.rs#L37

https://github.com/bevyengine/bevy/blob/bd7dcd3f6ddd3cf7934c8c76bab2bad624b3e24c/examples/ui/button.rs#L42
