### PR TITLE
set spawn_despawn on the correct entity when despawning

### LINKED ISSUE #17314: Enable `track_location` tests
## What problem does this solve or what need does it fill?

There are two tests in `bevy_ecs` using the `track_location` feature, however bevy only runs tests [with default features](https://github.com/bevyengine/bevy/blob/5c0e13f29bc6b028a81dcf46f9a234ab53b70d3f/tools/ci/src/commands/test.rs#L22).

## What solution would you like?

Enable the feature for `bevy_ecs` tests (but not benchmarks). Maybe make it clear which features are enabled for tests.

## Additional context

https://github.com/bevyengine/bevy/pull/17264#pullrequestreview-2544017341

### LINKED ISSUE #21293: track_location shows spawn location as despawn location
## Bevy version and features

0.17.0-rc.2

## What you did

Enabled `track_location` feature to debug double-despawn.

## What went wrong

The location pointed to as `despawned by` is actually where entity is spawned.

Minimal reproduction code:

```
    let entity = commands.spawn(()).id(); // line 35
    commands.entity(entity).despawn();  // line 36
    commands.entity(entity).despawn();
```

0.16
```
WARN bevy_ecs::error::handler: Encountered an error in command `<bevy_ecs::system::commands::entity_command::despawn::{{closure}} as bevy_ecs::error::command_handling::CommandWithEntity<core::result::Result<(), bevy_ecs::world::error::EntityMutableFetchError>>>::with_entity::{{closure}}`: The entity with ID 6v1 was despawned by src\main.rs:36:29
```
> despawned by src\main.rs:36:29

0.17
```
WARN bevy_ecs::error::handler: Encountered an error in command `<bevy_ecs::system::commands::entity_command::despawn::{{closure}} as bevy_ecs::error::command_handling::CommandWithEntity<core::result::Result<(), bevy_ecs::world::error::EntityMutableFetchError>>>::with_entity::{{closure}}`: The entity with ID 12v0 was despawned by src\main.rs:35:27

    If you were attempting to apply a command to this entity,
    and want to handle this error gracefully, consider using `EntityCommands::queue_handled` or `queue_silenced`.
```
> despawned by src\main.rs:35:27

### PR DESCRIPTION
**Pull request by janis-bhm**
# Objective

Fixes #21293
Fixes #17314 to ensure that this is tested correctly.

## Solution
when despawning an entity, previously the swapped in (archetype) or moved in entity (table) (which both require extra bookkeeping to update archetype or table rows) were marked as `spawned_or_despawned` by the location and tick that the to-be-removed entity was meant to be marked, while the to-be-removed entity wasn't marked.
As pointed out by @akimakinai in [#19047](https://github.com/bevyengine/bevy/pull/19047), I've re-added the correct `mark_spawn_despawn` call to `despawn_with_caller`.

## Testing

I've added a test `spawned_after_swap_remove` that ensures that despawning an entity by swapping doesn't effect other entities `spawned_or_despawned` location, and that it does effect the despawned entity's index's `spawned_or_despawned` location.

Co-Authored By: waterwhisperer24@qq.com

### CODE REVIEW

**Comment by janis-bhm** [comment]
The test only does anything when track_location is on, which doesn't appear to be the case for the tests in the CI? a bit unfortunate.

**Review by alice-i-cecile — APPROVED** [review]

**Comment by alice-i-cecile** [comment]
@janis-bhm can you incorporate the changes from #21359 into this PR please so we can merge it with passing tests?

**Review by alice-i-cecile — APPROVED** [review]

File: crates/bevy_ecs/src/world/entity_ref.rs [hunk 1]
```diff
@@ -2702,14 +2699,18 @@ impl<'w> EntityWorldMut<'w> {
...
-                    .entities
-                    .mark_spawn_despawn(moved_entity.index(), caller, change_tick);
             }
             world.archetypes[moved_location.archetype_id]
                 .set_entity_table_row(moved_location.archetype_row, table_row);
         }
         world.flush();
+
+        // SAFETY: `self.entity` is a valid entity index
+        unsafe {
```
Comment (chescock) [inline crates/bevy_ecs/src/world/entity_ref.rs:2709]: I'm a little late here, but don't we still need to call `mark_spawn_despawn()` *before* `flush()` so that the value is updated before we run commands queued by any hooks?  

...

Yeah, I just tested it, and it's possible to observe a stale value in a command, or to spawn a new entity that re-uses the index and have its `spawed_by` overwritten.  It's very much an edge case, but let me go make a quick PR to change that ... #21397.
