### PR TITLE
Fix Entity Debug Format

### LINKED ISSUE #12139: Inconsistency between `Debug` and serialized representation of `Entity`
## Bevy version

0.13

## What went wrong

There is an inconsistency between the `Debug` representation of an `Entity`:

```rust
impl fmt::Debug for Entity {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}v{}", self.index(), self.generation())
    }
}
```

And its `Serialize` representation:

```rust
impl Serialize for Entity {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        serializer.serialize_u64(self.to_bits())
    }
}
```

This makes it difficult to debug serialized outputs, since the serialized entity IDs cannot be easily mapped to runtime entities via human inspection. Ideally, these representations should be consistent for easier debugging.

## Additional information

I wanted to just open a PR on this, but I think the issue warrants some discussion. Mainly on two points:

- Which representation is "correct"?
- If we swap to #v# format for serialized data, are we ok with invalidating existing scenes?

### PR DESCRIPTION
**Pull request by Zeenobit**
# Objective

Fixes #12139

## Solution

See this comment on original issue for my proposal:
https://github.com/bevyengine/bevy/issues/12139#issuecomment-2241915791

This PR is an implementation of this proposal.

I modified the implementation of `fmt::Debug` to instead display `0v0#12345` to ensure entity index, generation, and raw bits are all present in the output for debug purposes while still keeping log message concise.

`fmt::Display` remains as is (`0v0`) to offer an even shorter output.

To me, this is the most non-intrusive fix for this issue.

## Testing

Add `fn entity_debug` test

### CODE REVIEW

**Review by alice-i-cecile — APPROVED** [review]
I like this fix: I agree with it being non-intrusive and I think that this is a good compromise.

File: crates/bevy_ecs/src/entity/mod.rs [hunk 1]
```diff
@@ -390,6 +390,18 @@ impl<'de> Deserialize<'de> for Entity {
     }
 }
 
+impl fmt::Debug for Entity {
```
Comment (MrGVSV) [inline crates/bevy_ecs/src/entity/mod.rs:393]: Nit: we could add a doc comment on this impl to specify what the `Debug` output signifies. It's not entirely clear unless you look into the source code

**Review by MrGVSV — APPROVED** [review]
I do prefer `Debug` being verbose (i.e. showing the whole struct), but I think this makes sense for `Entity`. It's supposed to be a sort of opaque identifier and it's used frequently as a key in maps and such as which aren't super readable with a full struct output

**Comment by alice-i-cecile** [comment]
I like the suggestion for a doc comment: once that's done I'm happy to merge this.

**Comment by Zeenobit** [comment]
Added documentation. Forget to fix the commit message! Sorry about that! 😅

File: crates/bevy_ecs/src/entity/mod.rs (hunk 1 above)
Comment (Zeenobit) [reply crates/bevy_ecs/src/entity/mod.rs:413]: Added documentation along with a sample serialized output to help users understand where to look for raw bits.

**Review by BD103 — APPROVED** [review]

File: crates/bevy_ecs/src/entity/mod.rs [hunk 2]
```diff
@@ -390,6 +390,41 @@ impl<'de> Deserialize<'de> for Entity {
...
+/// Example serialized scene data:
+/// ```text
+/// (
+///   ...
+///   entities: {
+///     4294967297: (  <--- Raw Bits
+///       components: {
+///         ...
+///       ),
+///   ...
```
Comment (MrGVSV) [inline crates/bevy_ecs/src/entity/mod.rs:411]: Super minor nit: closing parenthesis
```suggestion
///   ...
/// )
```

**Comment by alice-i-cecile** [comment]
No worries, we're not too precious about commit history / messages around here: it all gets squashed on a per-PR basis and contributor friction has a real cost.
