### PR TITLE
Avoid a "RefCell already borrowed" error with WINIT_WINDOWS

### LINKED ISSUE #21319: Panic "RefCell already borrowed" when closing window immediately after opening
## Bevy version and features

0.17.1

## What you did

1. Ran `cargo run --example mesh2d`
2. Closed the window immediately after it appeared

## What went wrong

```
thread 'main' panicked at C:\Users\kumikaya\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib/rustlib/src/rust\library\std\src\thread\local.rs:559:38:
RefCell already borrowed
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/1159e78c4747b02ef996e55082b704c09b970588/library\std\src\panicking.rs:697
   1: core::panicking::panic_fmt
             at /rustc/1159e78c4747b02ef996e55082b704c09b970588/library\core\src\panicking.rs:75
   2: core::cell::panic_already_borrowed::do_panic::runtime
             at /rustc/1159e78c4747b02ef996e55082b704c09b970588/library\core\src\panic.rs:218
   3: core::cell::panic_already_borrowed
             at /rustc/1159e78c4747b02ef996e55082b704c09b970588/library\core\src\panic.rs:223
   4: core::cell::RefCell<bevy_winit::winit_windows::WinitWindows>::borrow_mut
             at C:\Users\kumikaya\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\cell.rs:1089
   5: std::thread::local::impl$6::with_borrow_mut::closure$0<bevy_winit::winit_windows::WinitWindows,bevy_winit::system::despawn_windows::closure_env$0,tuple$<> >
             at C:\Users\kumikaya\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\thread\local.rs:559
   6: std::thread::local::LocalKey<core::cell::RefCell<bevy_winit::winit_windows::WinitWindows> >::try_with<core::cell::RefCell<bevy_winit::winit_windows::WinitWindows>,std::thread::local::impl$6::with_borrow_mut::closure_env$0<bevy_winit::winit_windows::WinitWi
             at C:\Users\kumikaya\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\thread\local.rs:315
   7: std::thread::local::LocalKey<core::cell::RefCell<bevy_winit::winit_windows::WinitWindows> >::with<core::cell::RefCell<bevy_winit::winit_windows::WinitWindows>,std::thread::local::impl$6::with_borrow_mut::closure_env$0<bevy_winit::winit_windows::WinitWindow
             at C:\Users\kumikaya\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\thread\local.rs:279
   8: std::thread::local::LocalKey<core::cell::RefCell<bevy_winit::winit_windows::WinitWindows> >::with_borrow_mut<bevy_winit::winit_windows::WinitWindows,bevy_winit::system::despawn_windows::closure_env$0,tuple$<> >
             at C:\Users\kumikaya\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\thread\local.rs:559
   9: bevy_winit::system::despawn_windows
             at .\crates\bevy_winit\src\system.rs:262
  10: core::ops::function::FnMut::call_mut<void (*)(bevy_ecs::system::query::Query<bevy_ecs::entity::Entity,bevy_ecs::query::filter::With<bevy_window::window::ClosingWindow> >,bevy_ecs::lifecycle::RemovedComponents<bevy_window::window::Window>,bevy_ecs::system::
             at C:\Users\kumikaya\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\ops\function.rs:168
  11: core::ops::function::impls::impl$3::call_mut<tuple$<bevy_ecs::system::query::Query<bevy_ecs::entity::Entity,bevy_ecs::query::filter::With<bevy_window::window::ClosingWindow> >,bevy_ecs::lifecycle::RemovedComponents<bevy_window::window::Window>,bevy_ecs::sy
             at C:\Users\kumikaya\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\ops\function.rs:301
  12: bevy_ecs::system::function_system::impl$48::run::call_inner<tuple$<>,bevy_ecs::system::query::Query<bevy_ecs::entity::Entity,bevy_ecs::query::filter::With<bevy_window::window::ClosingWindow> >,bevy_ecs::lifecycle::RemovedComponents<bevy_window::window::Win
             at .\crates\bevy_ecs\src\system\function_system.rs:926
  13: bevy_ecs::system::function_system::impl$48::run<tuple$<>,void (*)(bevy_ecs::system::query::Query<bevy_ecs::entity::Entity,bevy_ecs::query::filter::With<bevy_window::window::ClosingWindow> >,bevy_ecs::lifecycle::RemovedComponents<bevy_window::window::Window
             at .\crates\bevy_ecs\src\system\function_system.rs:929
  14: bevy_ecs::system::function_system::impl$12::run_unsafe<void (*)(bevy_ecs::system::query::Query<bevy_ecs::entity::Entity,bevy_ecs::query::filter::With<bevy_window::window::ClosingWindow> >,bevy_ecs::lifecycle::RemovedComponents<bevy_window::window::Window>,
             at .\crates\bevy_ecs\src\system\function_system.rs:711
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Encountered a panic in system `bevy_winit::system::despawn_windows`!
Encountered a panic in system `bevy_app::main_schedule::Main::run_main`!
error: process didn't exit successfully: `D:\build\debug\examples\mesh2d.exe` (exit code: 101)
```

### PR DESCRIPTION
**Pull request by ejrh**
# Objective

Fixes #21319.

## Solution

In the "about_to_wait" state of Bevy's winit event loop, we borrow WINIT_WINDOWS only to check the conditions for a redraw, and perform the call after that check is concluded.

## Testing

Tested by confirming that the RefCell error no longer occurs in my application.  In my application, the error occurred when the `bevy-egui-inspector` crate was used.

I do not know whether the original reporter of #21319 was also using third-party Bevy plugins that might have caused the issue.  It would be good if they could check whether this change fixes it for them.

Tested on Windows 11, where the bug is known to occur.  The code that was changed is only included in Windows builds so there is little need to test on other platforms.

### CODE REVIEW

**Comment by vladbat00** [comment]
I don't understand the `bevy_winit` internals very well but I'm curios on which thread `about_to_wait` is run. It seems to me that by limiting the borrow just to check the condition we successfully avoid the double-borrow, but don't fix the root issue that `WINIT_WINDOWS` ends up being borrowed outside of the main thread?

Or does `redraw_requested` actually end up triggering Bevy scheduler to run all the systems inside or something?

**Comment by dloukadakis** [comment]
> I don't understand the `bevy_winit` internals very well but I'm curios on which thread `about_to_wait` is run. It seems to me that by limiting the borrow just to check the condition we successfully avoid the double-borrow, but don't fix the root issue that `WINIT_WINDOWS` ends up being borrowed outside of the main thread?
> 
> Or does `redraw_requested` actually end up triggering Bevy scheduler to run all the systems inside or something?

`WinitAppRunnerState::redraw_request` runs `app.update()` by calling  `WinitAppRunnerState::run_app_update` which would run the `despawn_windows` system on the main thread while `WINIT_WINDOWS` is still borrowed by `WinitAppRunnerState::about_to_wait`.

File: crates/bevy_winit/src/state.rs [hunk 1]
```diff
@@ -466,24 +466,23 @@ impl<M: Message> ApplicationHandler<M> for WinitAppRunnerState<M> {
...
                         || all_invisible
                         || reactive
                         || self.window_event_received)
-                {
-                    self.redraw_requested(event_loop);
-                }
-            });
+            }) {
+                self.redraw_requested(event_loop);
+            }
```
Comment (dloukadakis) [inline crates/bevy_winit/src/state.rs:485]: We can refactor this further to avoid borrowing in some cases completely, also checking `winit_windows.windows.is_empty()` is redundant since `Iterator::all` returns `true` when the iterator is empty. 
```rust
            fn headless_or_all_invisible() -> bool {
                WINIT_WINDOWS.with_borrow(|winit_windows| {
                    winit_windows
                        .windows
                        .iter()
                        .all(|(_, w)| !w.is_visible().unwrap_or(false))
                })
            }

            if !self.app_exit.is_some()
                    && (self.startup_forced_updates > 0
                        || matches!(self.update_mode, UpdateMode::Reactive { .. })
                        || self.window_event_received
                        || headless_or_all_invisible())
            {
                self.redraw_requested(event_loop);
            }
```

File: crates/bevy_winit/src/state.rs [hunk 2]
```diff
@@ -466,24 +466,23 @@ impl<M: Message> ApplicationHandler<M> for WinitAppRunnerState<M> {
...
         {
-            WINIT_WINDOWS.with_borrow(|winit_windows| {
+            if WINIT_WINDOWS.with_borrow(|winit_windows| {
                 let headless = winit_windows.windows.is_empty();
                 let exiting = self.app_exit.is_some();
                 let reactive = matches!(self.update_mode, UpdateMode::Reactive { .. });
                 let all_invisible = winit_windows
                     .windows
                     .iter()
                     .all(|(_, w)| !w.is_visible().unwrap_or(false));
```
Comment (dloukadakis) [inline crates/bevy_winit/src/state.rs]:
```suggestion
            fn headless_or_all_invisible() -> bool {
                WINIT_WINDOWS.with_borrow(|winit_windows| {
                    winit_windows
                        .windows
                        .iter()
                        .all(|(_, w)| !w.is_visible().unwrap_or(false))
                })
            }

```

File: crates/bevy_winit/src/state.rs [hunk 3]
```diff
@@ -466,24 +466,23 @@ impl<M: Message> ApplicationHandler<M> for WinitAppRunnerState<M> {
...
-                if !exiting
+                !exiting
                     && (self.startup_forced_updates > 0
                         || headless
                         || all_invisible
                         || reactive
                         || self.window_event_received)
```
Comment (dloukadakis) [inline crates/bevy_winit/src/state.rs]:
```suggestion
            if !self.app_exit.is_some()
                && (self.startup_forced_updates > 0
                    || matches!(self.update_mode, UpdateMode::Reactive { .. })
                    || self.window_event_received
                    || headless_or_all_invisible())
```

File: crates/bevy_winit/src/state.rs [hunk 4]
```diff
@@ -466,24 +466,23 @@ impl<M: Message> ApplicationHandler<M> for WinitAppRunnerState<M> {
...
-                {
-                    self.redraw_requested(event_loop);
-                }
-            });
+            }) {
```
Comment (dloukadakis) [inline crates/bevy_winit/src/state.rs]:
```suggestion
            {
```

**Comment by dloukadakis** [comment]
I split the code snippet into 3 suggested changes to enable applying it more easily.

**Review by ejrh — COMMENTED** [review]
Much nicer, thanks

**Review by joshua-holmes — APPROVED** [review]
Great idea! Love it!
