### PR TITLE
fix windows wasm embedded assets

### LINKED ISSUE #14246: `embedded_asset!` is broken on Windows Wasm builds
## Bevy version

`0.14.0`

## Relevant system information

- `rustc --version`: `rustc 1.81.0-nightly (6292b2af6 2024-07-02)`
- Running Windows 11
```ignore
`AdapterInfo { name: "NVIDIA GeForce GTX 1080 Ti", vendor: 4318, device: 6918, device_type: DiscreteGpu, driver: "NVIDIA", driver_info: "555.99", backend: Vulkan }`
```

## What you did

There's a minimal reproduction here: https://github.com/janhohenheim/asset-crash

The relevant code is just this `main.rs`:

```rust
use bevy::{asset::embedded_asset, prelude::*};

fn main() {
    let mut app = App::new();
    app.add_plugins(DefaultPlugins);
    embedded_asset!(app, "splash.png");
    app.run();
}
```
The setup is:
- crate
  - src/
	  - `main.rs`
	  - `splash.png`

## What went wrong

Running this with `cargo run` works.
Running it on Wasm on Windows instead gives me:
```
Failed to find src_prefix "src" in "src\\screen\\splash\\mod.rs"
```

This is the part of the Bevy code that panics: https://github.com/bevyengine/bevy/blob/main/crates/bevy_asset/src/io/embedded/mod.rs#L141
And this is the PR that introduced it: https://github.com/bevyengine/bevy/pull/10383

Note that this is *not* reproducible on Linux

## Additional information

The minimal example has a workaround. Move `crate/src/splash.png` into `crate/assets/splash.png` and embed it with `embedded_asset!(app, "../assets/splash.png");`.
For reasons unknown to me, doing the same workaround on https://github.com/TheBevyFlock/bevy-template does *not* work.

I also tried running the [embedded assets example](https://github.com/bevyengine/bevy/blob/main/examples/asset/embedded_asset.rs) with `cargo build --example ...` and that one works.

Using `load_internal_binary_asset` like this works as well:
```rust
    load_internal_binary_asset!(
        app,
        SPLASH_IMAGE_HANDLE,
        "splash.png",
        |bytes, _path: String| {
            Image::from_buffer(
                bytes,
                ImageType::Extension("png"),
                default(),
                true,
                ImageSampler::linear(),
                RenderAssetUsages::RENDER_WORLD | RenderAssetUsages::MAIN_WORLD,
            )
            .unwrap()
        }
    );
```

### PR DESCRIPTION
**Pull request by atlv24**
# Objective

- Fix #14246

## Solution

- If building for wasm windows, add a bit of code that replaces `\\` with `/` in the `file!()` arg

## Testing

- Used MRE https://github.com/janhohenheim/asset-crash

### CODE REVIEW

**Review by andriyDev — APPROVED** [review]
Thanks for doing this!!

**Review by andriyDev — CHANGES_REQUESTED** [review]
Welp it's a good thing you suggested I test this myself. It looks like it's still broken for me? I still get an error even when including your PR.

**Comment by andriyDev** [comment]
I now understand this issue much more deeply. The `file!()` on Windows returns the path to the current file using `\\` file separators. However on `cfg!(target_family = "wasm")` `Path` just doesn't have any machinery to deal with `\\` so the paths are mucked. Unfortunately, rustc doesn't seem to have a `cfg` flag for whether the code is being built **on** Windows. Only what platform the code is being built **for**. Note that `cfg!(windows)` seems to be just shorthand for `cfg!(target_family = "windows")`. The way this fix has been written, it will actually never trigger since you are either targetting WASM or Windows, not both.

I wonder if maybe we should just say heck it and unconditionally replace `\\` with `/` on WASM? According to https://www.wikiwand.com/en/articles/Filename#Comparison_of_filename_limitations there are file systems that support `\\` in the filename, including EXT4 which is big on Linux. To be fair, a backslash in a path on Linux feels malicious, so I'm tempted to just say we don't support it.

Someone on the original issue was saying that this doesn't happen for library crates? I will try testing that out. If it works, we could ship this for internal bevy, but users wouldn't be able to reuse this for shaders in their binary crates.

I think technically this isn't exactly a "rustc bug" - more just a design decision. `file!()` is doing what it's supposed to do: it printed the path of the original source file. WASM just has this very unfortunate edge case.

**Comment by atlv24** [comment]
Amended it, thanks for testing! I had a feeling i did something wrong.

File: crates/bevy_asset/src/io/embedded/mod.rs [hunk 1]
```diff
@@ -168,6 +168,12 @@ pub fn _embedded_asset_path(
     file_path: &Path,
     asset_path: &Path,
 ) -> PathBuf {
+    let file_path = if cfg!(target_family = "wasm") {
+        // Work around bug: https://github.com/bevyengine/bevy/issues/14246
```
Comment (andriyDev) [inline crates/bevy_asset/src/io/embedded/mod.rs:172]: Can we add an explicit comment here saying we know this will break any paths on Linux/Mac with "\\"? Definitely an edge case, but if someone hunts a panic here I want them to see this is something we considered.

**Review by andriyDev — CHANGES_REQUESTED** [review]

**Comment by andriyDev** [comment]
P.S., I tested this again with the updated code and it works in the general case!

**Review by andriyDev — APPROVED** [review]

File: crates/bevy_asset/src/io/embedded/mod.rs [hunk 2]
```diff
@@ -168,6 +168,13 @@ pub fn _embedded_asset_path(
     file_path: &Path,
     asset_path: &Path,
 ) -> PathBuf {
+    let file_path = if cfg!(target_family = "wasm") {
```
Comment (mockersf) [inline crates/bevy_asset/src/io/embedded/mod.rs:171]:
```suggestion
    let file_path = if cfg!(not(target_family = "windows")) {
```
The bug is more general than wasm, it happens whenever you cross compile from windows to a system with forward slash. most often happens with wasm and android

**Review by ItsDoot — APPROVED** [review]
Could consider making the `file_path` parameter be `&str` so you can avoid the additional unwrap that can't ever fail in practice.

Not hugely important though: good enough for me.

**Review by superdump — APPROVED** [review]
