### PR TITLE
fix freezes on AppExit on macos

### LINKED ISSUE #23313: AppExit::Success causes app freeze on macOS when sent programmatically from a system
## Bevy version and features

Bevy 0.18.1, default features (no custom feature flags).

## Relevant system information

- Rust 1.94.0-nightly, edition 2024
- macOS 26.2 (kernel 25.2.0)
- `AdapterInfo { name: "Apple M4 Max", vendor: 0, device: 0, device_type: IntegratedGpu, driver: "", driver_info: "", backend: Metal }`

## What you did

Called `app_exit.write(AppExit::Success)` from two pause menu systems using `MessageWriter<AppExit>`:

```rust
pub fn pause_menu_mouse_interaction(
    mut interaction_query: Query<
        (
            &Interaction,
            &mut BackgroundColor,
            Option<&ResumeButton>,
            Option<&QuitButton>,
        ),
        (Changed<Interaction>, With<Button>),
    >,
    mut next_state: ResMut<NextState<GameState>>,
    mut app_exit: MessageWriter<AppExit>,
    mut menu_state: ResMut<PauseMenuState>,
) {
    for (interaction, mut color, is_resume, is_quit) in &mut interaction_query {
        match *interaction {
            Interaction::Pressed => {
                *color = BUTTON_PRESSED.into();
                if is_resume.is_some() {
                    next_state.set(GameState::Playing);
                } else if is_quit.is_some() {
                    app_exit.write(AppExit::Success);
                }
            }
            // ...
        }
    }
}

pub fn pause_menu_keyboard_navigation(
    keyboard: Res<ButtonInput<KeyCode>>,
    mut menu_state: ResMut<PauseMenuState>,
    mut next_state: ResMut<NextState<GameState>>,
    mut app_exit: MessageWriter<AppExit>,
) {
    // ...
    if keyboard.just_pressed(KeyCode::Enter) || keyboard.just_pressed(KeyCode::Space) {
        match menu_state.selected {
            0 => next_state.set(GameState::Playing),
            1 => {
                app_exit.write(AppExit::Success);
            }
            _ => {}
        }
    }
}
```

Both systems run in `Update`, gated by `run_if(in_state(GameState::Paused))`.

Taken from examples:
https://github.com/bevyengine/bevy/blob/2b760d979ff0d85beb95157f58b8bf07404c3c95/examples/games/game_menu.rs#L705-L707

## What went wrong

**Expected:** The app exits cleanly.

**Actual:** The app hard-freezes on macOS. The window stays visible but is completely unresponsive. Even Ctrl+C in the terminal does not work the process must be force-killed.

The OS window close button (X) exits cleanly using the exact same app. Only the programmatic `AppExit` path is broken.

### Logs

**In-game quit via `AppExit::Success`** - hard freeze, Ctrl+C unresponsive:

```
2026-03-11T15:03:40.612432Z  INFO bevy_diagnostic::system_information_diagnostics_plugin::internal: SystemInfo { os: "macOS 26.2", kernel: "25.2.0", cpu: "Apple M4 Max", core_count: "14", memory: "36.0 GiB" }
2026-03-11T15:03:40.666167Z  INFO bevy_render::renderer: AdapterInfo { name: "Apple M4 Max", vendor: 0, device: 0, device_type: IntegratedGpu, driver: "", driver_info: "", backend: Metal }
2026-03-11T15:03:40.910601Z  INFO bevy_render::batching::gpu_preprocessing: GPU preprocessing is fully supported on this device.
2026-03-11T15:03:40.945192Z  INFO bevy_winit::system: Creating new window Breakout (0v0)
^C^C^C^C
```

**X button** - clean exit for comparison:

```
2026-03-11T15:01:37.076220Z  INFO bevy_winit::system: Creating new window Breakout (0v0)
2026-03-11T15:02:50.778147Z  INFO bevy_window::system: No windows are open, exiting
```

**CMD+Q** - quits but no shutdown log is printed (bypasses the ECS event loop entirely, see #9499).

### Theories

- Ctrl+C not working suggests the macOS event loop is locked hard enough that SIGINT cannot interrupt it, consistent with a deadlock.

### Workaround

Despawn the `PrimaryWindow` entity instead. This triggers Bevy's built-in `exit_on_primary_closed` system, re-entering the native winit close path:

```rust
pub fn pause_menu_mouse_interaction(
    mut interaction_query: Query<
        (
            &Interaction,
            &mut BackgroundColor,
            Option<&ResumeButton>,
            Option<&QuitButton>,
        ),
        (Changed<Interaction>, With<Button>),
    >,
    mut next_state: ResMut<NextState<GameState>>,
    mut commands: Commands,
    mut menu_state: ResMut<PauseMenuState>,
    window_query: Query<Entity, With<PrimaryWindow>>,
) {
    for (interaction, mut color, is_resume, is_quit) in &mut interaction_query {
        match *interaction {
            Interaction::Pressed => {
                *color = BUTTON_PRESSED.into();
                if is_resume.is_some() {
                    next_state.set(GameState::Playing);
                } else if is_quit.is_some()
                    && let Ok(window) = window_query.single()
                {
                    commands.entity(window).despawn();
                }
            }
            // ...
        }
    }
}

pub fn pause_menu_keyboard_navigation(
    keyboard: Res<ButtonInput<KeyCode>>,
    mut menu_state: ResMut<PauseMenuState>,
    mut next_state: ResMut<NextState<GameState>>,
    mut commands: Commands,
    window_query: Query<Entity, With<PrimaryWindow>>,
) {
    // ...
    if keyboard.just_pressed(KeyCode::Enter) || keyboard.just_pressed(KeyCode::Space) {
        match menu_state.selected {
            0 => next_state.set(GameState::Playing),
            1 => {
                if let Ok(window) = window_query.single() {
                    commands.entity(window).despawn();
                }
            }
            _ => {}
        }
    }
}
```

Clean exit with workaround:

```
2026-03-11T15:05:07.106963Z  INFO bevy_winit::system: Creating new window Breakout (0v0)
2026-03-11T15:05:10.554192Z  INFO bevy_window::system: No windows are open, exiting
2026-03-11T15:05:10.555256Z  INFO bevy_winit::system: Closing window 0v0
2026-03-11T15:05:10.561522Z  WARN bevy_winit::state: Skipped event Destroyed for unknown winit Window Id WindowId(41468956416)
2026-03-11T15:05:10.566094Z  INFO bevy_window::system: No windows are open, exiting
```

### Related issues

- #9499 and #20316 are about CMD+Q bypassing the ECS event loop, a different problem. This is about the documented programmatic API itself deadlocking when called from a system.

### PR DESCRIPTION
**Pull request by mockersf**
# Objective

- Fix #23313
- On macOS, sending `AppExit` sometimes freezes the app

## Solution

- This was caused by a race condition between the main thread and the render thread both holding an `Arc` to the window
- Make sure more things drop on the main thread in the correct order

## Testing

- Ran the repro a few times, it used to freezes before, it doesn't after

### CODE REVIEW

**Review by alice-i-cecile — APPROVED** [review]

File: crates/bevy_winit/src/system.rs [hunk 1]
```diff
@@ -270,13 +270,19 @@ pub(crate) fn despawn_windows(
         }
     }
 
-    // On macOS, when exiting, we need to tell the rendering thread the windows are about to
-    // close to ensure that they are dropped on the main thread. Otherwise, the app will hang.
+    // On macOS, many things need to be dropepd on the main thread, or the app will hang:
```
Comment (kfc35) [inline crates/bevy_winit/src/system.rs]:
```suggestion
    // On macOS, many things need to be dropped on the main thread, or the app will hang:
```

**Review by kfc35 — APPROVED** [review]
