### PR TITLE
Fix fetching assets in Web Workers

### LINKED ISSUE #12125: Fetching assets is broken in web workers
## Bevy version
0.13

## Relevant system information
WebAssembly/Web Worker

## What you did
Ran Bevy in a Web Worker with an OffscreenCanvas and routed events over postMessage.

## What went wrong
Everything was working nicely until I had to fetch a GLTF asset and I kept getting a panic. Turns out that `HttpWasmAssetReader::fetch_bytes` from `bevy_asset` assumes at [wasm.rs#41](https://github.com/bevyengine/bevy/blob/release-0.13.0/crates/bevy_asset/src/io/wasm.rs#L41) that it is running in a window and not in a worker.

Note that gloo-net used to have a similar issue but resolved the issue by probing the global object to see whether it was a `web_sys::Window` or a `web_sys::WorkerGlobalScope` in [request.rs#323](https://github.com/rustwasm/gloo/blob/0.9.0/crates/net/src/http/request.rs#L323-L338).

## Additional information
This issue could be resolved by either adding a dependency on gloo-net or duplicating its logic into bevy_asset. For the latter approach, it might also be an idea to then add an option field to the `HttpWasmAssetReader` that contains the probed global object type once it has been "resolved".

### PR DESCRIPTION
**Pull request by allsey87**
# Objective

This PR fixes #12125

## Solution

The logic in this PR was borrowed from gloo-net and essentially probes the global Javascript context to see if we are in a window or a worker before calling `fetch_with_str`.

### CODE REVIEW

**Comment by allsey87** [comment]
Not sure what the procedure/rules are here, but I would like to suggest that this be added to the 0.13.1 milestone.

**Review by mockersf — APPROVED** [review]

**Comment by mockersf** [comment]
unblocks your use case, not a breaking change, and it works 👍

**Comment by allsey87** [comment]
@mockersf do I need to rebase this PR onto the release-0.13.1 branch?

**Comment by mockersf** [comment]
no, once this PR has been approved by someone else, we'll merge it to main then cherry pick to the release branch

File: crates/bevy_asset/src/io/wasm.rs [hunk 1]
```diff
@@ -38,8 +38,27 @@ fn js_value_to_err<'a>(context: &'a str) -> impl FnOnce(JsValue) -> std::io::Err
 
 impl HttpWasmAssetReader {
     async fn fetch_bytes<'a>(&self, path: PathBuf) -> Result<Box<Reader<'a>>, AssetReaderError> {
-        let window = web_sys::window().unwrap();
-        let resp_value = JsFuture::from(window.fetch_with_str(path.to_str().unwrap()))
+        let global = js_sys::global();
+        let maybe_window = Reflect::get(&global, &JsValue::from_str("Window"))
```
Comment (cart) [inline crates/bevy_asset/src/io/wasm.rs:42]: This seems unnecessarily "stringy". Is there a reason to not do this instead?

```rust
let global: Global = js_sys::global().unchecked_into();

if !global.window().is_undefined() {
    let window: Window = global.unchecked_into();
} else if !global.worker().is_undefined() {
    let worker: WorkerGlobalScope = global.unchecked_into();
} 
```

Comment (cart) [reply crates/bevy_asset/src/io/wasm.rs:42]: Ahhhh because we don't have a Global type

Comment (cart) [reply crates/bevy_asset/src/io/wasm.rs:42]: That was defined in the project I got the snippet from.

Comment (cart) [reply crates/bevy_asset/src/io/wasm.rs:42]: In theory we could add it ourselves / generate it via wasm_bindgen:

https://github.com/PWhiddy/wgpu-hackdown/blob/d7296ac30b7948d6d111ffe201d7c47c246d16cd/wgpu/src/backend/web.rs#L993C1-L1002C2

Comment (cart) [reply crates/bevy_asset/src/io/wasm.rs:42]: Generating the bindings _feels_ like it would be more efficient, but I don't have the expertise here to say with certainty.

Comment (allsey87) [reply crates/bevy_asset/src/io/wasm.rs:42]: We could add a Global type, which project did you get it from? The PR here is based on the [solution used in gloo-net](https://github.com/rustwasm/gloo/blob/master/crates/net/src/http/request.rs#L323-L338).

Comment (allsey87) [reply crates/bevy_asset/src/io/wasm.rs:42]: > Generating the bindings feels like it would be more efficient

I was thinking about that but then I realised that the next step is to do a HTTP fetch which is probably 100000x slower than anything involving converting strings back and forth between Js and Rust...

Comment (allsey87) [reply crates/bevy_asset/src/io/wasm.rs:42]: @daxpedda any thoughts?

Comment (daxpedda) [reply crates/bevy_asset/src/io/wasm.rs:42]: > > Generating the bindings feels like it would be more efficient
> 
> I was thinking about that but then I realised that the next step is to do a HTTP fetch which is probably 100000x slower than anything involving converting strings back and forth between Js and Rust...

True.

> @daxpedda any thoughts?

Generating custom bindings is the way this is usually done, it would probably make more sense Bevy had a centralized place to make these bindings if they are used elsewhere.

So my 2¢: if this is the only occurrence, leave it as-is, if not, make bindings like suggested in https://github.com/bevyengine/bevy/pull/12134/files#r1505095751.

Comment (allsey87) [reply crates/bevy_asset/src/io/wasm.rs:42]: I feel this code almost belongs in wasm-bindgen itself, so far some variant of this logic has been replicated in gloo-timers, gloo-net, wgpu, and now we considering putting it into bevy_assets.

I do not have a strong opinion but I am happy to create the relevants PRs. The two open questions are then:
1. Should we add a binding for the `Global` object (I feel like we are leaning towards "yes")
2. Where should that binding go? (1) wasm.rs at file scope, (2) wasm.rs at function scope (inside fetch_bytes), (3) somewhere else in Bevy, (4) in wasm-bindgen.

Comment (daxpedda) [reply crates/bevy_asset/src/io/wasm.rs:42]: > I feel this code almost belongs in wasm-bindgen itself, so far some variant of this logic has been replicated in gloo-timers, gloo-net, wgpu, and now we are considering putting it into bevy_assets.

I don't believe this should be done in `wasm-bindgen`, as its only purpose is to provide bindings and nothing else. It might be more appropriate in `gloo`. That said, `wasm-bindgen` needs a general mechanism to query the availability of a binding, which would probably solve this problem as well.

Comment (allsey87) [reply crates/bevy_asset/src/io/wasm.rs:42]: > I don't believe this should be done in `wasm-bindgen`

Indeed, I meant to say inside of `js_sys`

Comment (daxpedda) [reply crates/bevy_asset/src/io/wasm.rs:42]: > > I don't believe this should be done in `wasm-bindgen`
> 
> Indeed, I meant to say inside of `js_sys`

Same answer really, `js-sys` is also bindings only. But a general purpose solution to this problem would probably live in `web-sys`? Probably off-topic to discuss here.

**Comment by BD103** [comment]
> I noticed that the check "validation jobs / run-examples-on-wasm (pull_request)" was skipped, is there any reason for this? It seems like a relevant check for this PR.

`run-examples-on-wasm` does not run until this PR gets added to the merge queue. You can ignore it for now :)

**Review by daxpedda — APPROVED** [review]
To reduce the amount of FFI calls you could cache the current global context in a `thread_local`. Keep in mind that this might or might not be worth it considering we are doing a HTTP request here.

Otherwise LGTM!

File: crates/bevy_asset/src/io/wasm.rs [hunk 2]
```diff
@@ -5,10 +5,22 @@ use bevy_log::error;
...
 use std::path::{Path, PathBuf};
-use wasm_bindgen::{JsCast, JsValue};
+use wasm_bindgen::{prelude::wasm_bindgen, JsCast, JsValue};
 use wasm_bindgen_futures::JsFuture;
 use web_sys::Response;
 
+/// Represents the global object in the JavaScript context
+#[wasm_bindgen]
+extern "C" {
+    type Global;
```
Comment (bushrat011899) [inline crates/bevy_asset/src/io/wasm.rs:15]:
```suggestion
    /// The [Global](https://developer.mozilla.org/en-US/docs/Glossary/Global_object) object.
    type Global;
```

File: crates/bevy_asset/src/io/wasm.rs [hunk 3]
```diff
@@ -5,10 +5,22 @@ use bevy_log::error;
...
+
+    #[wasm_bindgen(method, getter, js_name = Window)]
```
Comment (bushrat011899) [inline crates/bevy_asset/src/io/wasm.rs:17]:
```suggestion
    /// The [window](https://developer.mozilla.org/en-US/docs/Web/API/Window) global object.
    #[wasm_bindgen(method, getter, js_name = Window)]
```

File: crates/bevy_asset/src/io/wasm.rs [hunk 4]
```diff
@@ -5,10 +5,22 @@ use bevy_log::error;
...
+    fn window(this: &Global) -> JsValue;
+
+    #[wasm_bindgen(method, getter, js_name = WorkerGlobalScope)]
```
Comment (bushrat011899) [inline crates/bevy_asset/src/io/wasm.rs:20]:
```suggestion
    /// The [WorkerGlobalScope](https://developer.mozilla.org/en-US/docs/Web/API/WorkerGlobalScope) global object.
    #[wasm_bindgen(method, getter, js_name = WorkerGlobalScope)]
```

File: crates/bevy_asset/src/io/wasm.rs [hunk 5]
```diff
@@ -38,8 +50,21 @@ fn js_value_to_err<'a>(context: &'a str) -> impl FnOnce(JsValue) -> std::io::Err
 
 impl HttpWasmAssetReader {
     async fn fetch_bytes<'a>(&self, path: PathBuf) -> Result<Box<Reader<'a>>, AssetReaderError> {
-        let window = web_sys::window().unwrap();
-        let resp_value = JsFuture::from(window.fetch_with_str(path.to_str().unwrap()))
+        let global: Global = js_sys::global().unchecked_into();
```
Comment (bushrat011899) [inline crates/bevy_asset/src/io/wasm.rs:53]:
```suggestion
        // The JS global scope includes a self-reference via a specialising name, which can be used to determine the type of global context available.
        let global: Global = js_sys::global().unchecked_into();
```

**Review by bushrat011899 — APPROVED** [review]
Nice catch and a simple fix! I've just added some comments as a suggestion to help explain some of the JS weirdness, and link back to MDN documentation as well.
