### PR TITLE
Move `SUPPORTED_FILE_EXTENSIONS` to `ImageLoader` and remove unsupported formats.

### LINKED ISSUE #15730: WARN Duplicate AssetLoader preregistered for Asset type `bevy_image::image::Image` with extensions `["hdr"]`. when run breakout example
## Bevy version

The release number or commit hash of the version you're using.

```
git log -1
commit 4bf647ff3b0ca7c8ca47496db9cfe03702328473 (HEAD -> main, origin/main, origin/HEAD)
```

## \[Optional\] Relevant system information

If you cannot get Bevy to build or run on your machine, please include:

- the Rust version you're using (you can get this by running `cargo --version`)
```
cargo --version
cargo 1.81.0 (2dbb1af80 2024-08-20)
```
  - Bevy relies on the "latest stable release" of Rust
  - nightly should generally work, but there are sometimes regressions: please let us know!
- the operating system or browser used, including its version
  - Windows 11 23H2

If your bug is rendering-related, copy the adapter info that appears when you run Bevy.

```ignore
`INFO bevy_render::renderer: AdapterInfo { name: "NVIDIA GeForce RTX 4050 Laptop GPU", vendor: 4318, device: 10465, device_type: DiscreteGpu, driver: "NVIDIA", driver_info: "560.94", backend: Vulkan }`
```

You should also consider testing the examples of our upstream dependencies to help isolate any setup-specific issue:

- [`wgpu`](https://github.com/gfx-rs/wgpu) for rendering problems
- [`winit`](https://github.com/rust-windowing/winit) for input and window management
- [`gilrs`](https://docs.rs/gilrs/latest/gilrs/) for gamepad inputs

## What you did
 ` cargo run --example breakout`

## What went wrong

If it's not clear, break this out into:

- what were you expecting?
- Run successfully
- what actually happened?

```
cargo run --example breakout
...
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 51.48s
     Running `target\debug\examples\breakout.exe`
2024-10-08T07:58:04.636297Z  INFO bevy_diagnostic::system_information_diagnostics_plugin::internal: SystemInfo { os: "Windows 11 Home China", kernel: "22631", cpu: "Intel(R) Core(TM) i7-14650HX", core_count: "16", memory: "15.7 GiB" }
2024-10-08T07:58:05.580350Z  INFO bevy_render::renderer: AdapterInfo { name: "NVIDIA GeForce RTX 4050 Laptop GPU", vendor: 4318, device: 10465, device_type: DiscreteGpu, driver: "NVIDIA", driver_info: "560.94", backend: Vulkan }
2024-10-08T07:58:05.701200Z  WARN bevy_asset::server::loaders: Duplicate AssetLoader preregistered for Asset type `bevy_image::image::Image` with extensions `["hdr"]`. Loader must be specified in a .meta file in order to load assets of this type with these extensions.
2024-10-08T07:58:06.496605Z  INFO bevy_winit::system: Creating new window "App" (0v1#4294967296)
2024-10-08T07:58:06.585224Z  INFO breakout::stepping: Bevy was compiled without stepping support. Run with `--features=bevy_debug_stepping` to enable stepping.
2024-10-08T07:58:07.158131Z  WARN bevy_ecs::system::function_system: bevy_pbr::render::mesh_view_bindings::prepare_mesh_view_bind_groups did not run because it requested inaccessible system parameter Res<OitBuffers>
2024-10-08T07:58:11.091470Z  INFO bevy_window::system: No windows are open, exiting
2024-10-08T07:58:11.094472Z  INFO bevy_winit::system: Closing window 0v1#4294967296
2024-10-08T07:58:11.124012Z  INFO bevy_window::system: No windows are open, exiting
```

## Additional information

Other information that can be used to further reproduce or isolate the problem.
This commonly includes:

- screenshots
- logs
- theories about what might be going wrong
- workarounds that you used
- links to related bugs, PRs or discussions

### PR DESCRIPTION
**Pull request by andriyDev**
# Objective

Fixes #15730.

## Solution

As part of #15586, we made a constant to store all the supported image formats. However since the `ImageFormat` does actually include Hdr and OpenExr, it also included the `"hdr"` and `"exr"` file extensions. These are supported by separate loaders though: `HdrTextureLoader` and `ExrTextureLoader`. This led to a warning about duplicate asset loaders.

Therefore, instead of having the constant for `ImageFormat`, I made the constant just for `ImageLoader`. This lets us correctly remove `"hdr"` and `"exr"` from the image formats supported by `ImageLoader`, returning us to having a single asset loader for every image format.

Note: we could have just removed `hdr` and `exr` from `ImageFormat::SUPPORTED_FILE_EXTENSIONS`, but this would be very confusing. Then the list of `ImageFormat`s would not match the list of supported formats!

## Testing

- I ran the `sprite` example and got no warning! I also replaced the sprite in that example with an HDR file and everything worked as expected.

### CODE REVIEW

File: crates/bevy_image/src/image_loader.rs [hunk 1]
```diff
@@ -12,6 +12,135 @@ pub struct ImageLoader {
...
+        }
+        #[cfg(feature = "webp")]
+        {
+            count += 1;
+        }
+        count
+    };
+
+    /// Full list of supported formats.
+    pub const SUPPORTED: &'static [ImageFormat] = &[
```
Comment (tychedelia) [inline crates/bevy_image/src/image_loader.rs:82]: Nit: just "supported" isn't as clear in relation to `ImageLoader` versus `ImageFormat`.

```suggestion
    pub const SUPPORTED_FORMATS: &'static [ImageFormat] = &[
```

Comment (andriyDev) [reply crates/bevy_image/src/image_loader.rs]: Great point! Done.

**Review by BenjaminBrienen — APPROVED** [review]

**Comment by andriyDev** [comment]
I rebased since Github was saying there were changes (but the rebase was totally clean so idk).

File: crates/bevy_image/src/image_loader.rs [hunk 2]
```diff
@@ -12,6 +12,135 @@ pub struct ImageLoader {
...
+        #[cfg(feature = "tiff")]
+        {
+            count += 1;
+        }
+        #[cfg(feature = "webp")]
+        {
+            count += 1;
+        }
+        count
+    };
```
Comment (bushrat011899) [inline crates/bevy_image/src/image_loader.rs:79]:
```suggestion
    const COUNT: usize = Self::SUPPORTED_FORMATS.len();
```

Currently we have 1 feature flag for 1 format, so the length of `SUPPORTED_FORMATS` will be exactly `COUNT`.

**Review by bushrat011899 — APPROVED** [review]
Sensible change! I do have a comment around simplifying one of the constants, but it's not blocking.

File: crates/bevy_image/src/image_loader.rs (hunk 2 above)
Comment (andriyDev) [reply crates/bevy_image/src/image_loader.rs:79]: @bushrat011899 I think we should handle this in a separate PR, it's not clear to me why this can't be a loop that just sums all the file extension lengths. 

Regardless I'd like to keep the diff small, and `COUNT` is private so fixing it later won't affect our API.
