### PR TITLE
Remove `InstanceId` when Scene Despawn

### LINKED ISSUE #12746: Memory Leak When Loading Scenes
## Bevy version

bevy = "0.13.0"

## \[Optional\] Relevant system information

- cargo 1.78.0-nightly (7065f0ef4 2024-03-12)
- MacOS 14.4 (23E214)
- Apple M1 CPU
-  `AdapterInfo { name: "Apple M1", vendor: 0, device: 0, device_type: IntegratedGpu, driver: "", driver_info: "", backend: Metal }`
- Also tested on Wasm in Firefox with the same result.

## What you did

I have been having a problem with a memory leak in my app. Here is a minimal example that reproduces the bug.

```rust

use bevy::prelude::*;

fn main() {
    App::new()
        .add_plugins(DefaultPlugins)
        .insert_resource(Objects::default())
        .add_systems(Startup, setup)
        .add_systems(Update, update)
        .run();
}

#[derive(Resource, Default)]
struct Objects {
    mesh: Handle<Mesh>,
    material: Handle<StandardMaterial>,
    scene: Handle<Scene>,
}

#[derive(Component)]
struct Piece;

fn setup(
    mut commands: Commands,
    mut objects: ResMut<Objects>,
    mut meshes: ResMut<Assets<Mesh>>,
    mut materials: ResMut<Assets<StandardMaterial>>,
    asset_server: Res<AssetServer>,
) {
    commands.spawn(Camera3dBundle {
        transform: Transform::from_xyz(7., 15., -9.5).looking_at(Vec3::ZERO, Vec3::Y),
        camera: Camera {
            clear_color: ClearColorConfig::Custom(Color::rgb(0., 0.7, 0.89)),
            ..default()
        },
        ..default()
    });

    objects.mesh = meshes.add(Cuboid::new(1.0, 1.0, 1.0));
    objects.material = materials.add(Color::rgb_u8(124, 144, 255));
    objects.scene = asset_server.load(format!("tree_1.glb#Scene0"));
}

fn update(mut commands: Commands, objects: Res<Objects>, delete_query: Query<Entity, With<Piece>>) {
    for entity in delete_query.iter() {
        commands.entity(entity).despawn_recursive();
    }

    for i in 1..1000 {
        commands
            .spawn(PbrBundle {
                mesh: objects.mesh.clone(),
                material: objects.material.clone(),
                transform: Transform::from_xyz(0.0, 0.0, i as f32),
                ..default()
            })
            .insert(Piece);

        // The previous expression doesn't seem to have an effect
        // but the memory steadily increases when the following expression is included.
        commands
            .spawn(SceneBundle {
                scene: objects.scene.clone(),
                transform: Transform::from_xyz(0.0, 1., i as f32).with_scale(Vec3::splat(0.05)),
                ..Default::default()
            })
            .insert(Piece);
    }
}
```

In other words, entities are cleared and then added again, repeatedly. The problem still happens if there is some time between runs (e.g. once every second) but it just happens a bit slower.

## What went wrong

The app memory usage steadily increases.

## Additional information

It may be that some part of the loaded scene is not being properly deleted. I am not sure.

Potentially related to #9035 but it seems to not be an exclusively MacOS issue, given that I tried it on Wasm as well.

### PR DESCRIPTION
**Pull request by 341101**
# Objective

- Fix #12746
- When users despawn a scene, the `InstanceId` within `spawned_scenes` and `spawned_dynamic_scenes` is not removed, causing a potential memory leak

## Solution

- `spawned_scenes` field was never used, and I removed it
- Add a component remove hook for `Handle<DynamicScene>`, and when the `Handle<DynamicScene>` component is removed, delete the corresponding `InstanceId` from `spawned_dynamic_scenes`

### CODE REVIEW

**Comment by Brezak** [comment]
Fixex one leak. We still leak in `spawned_instances`. You'll have to pass the instance id into `SceneSpawner::despawn_instance`.

**Comment by 341101** [comment]
> * Handle<DynamicScene>

If calling `SceneSpawner::despawn_instance`, the user removing the `Handle<DynamicScene>` component would cause the entity to be despawned, and I'm not sure if this is appropriate.

**Comment by Brezak** [comment]
It shouldn't `despawn_instance` will eventually through `despawn_queued_instances` will despawn the scene instance. It shouldn't despawn the parent entity itself. If you're removing the scene handle from an entity you're likely trying to despawn the scene.

**Comment by 341101** [comment]
> It shouldn't. `despawn_instance` will eventually through `despawn_queued_instances` despawn the scene instance. It shouldn't despawn the parent entity itself. If you're removing the scene handle from an entity you're likely trying to despawn all the entities in said scene.

Additionally, if the user calls `despawn_recursive`, it could lead to a repeated `despawn` action, resulting in a warning.

**Comment by Brezak** [comment]
We will still leak in `spawned_instances` when we're removing normal scene handles. Another suggestion I have. If there are no more instances of a dynamic scene we should despawn it.

**Comment by Brezak** [comment]
> > It shouldn't. `despawn_instance` will eventually through `despawn_queued_instances` despawn the scene instance. It shouldn't despawn the parent entity itself. If you're removing the scene handle from an entity you're likely trying to despawn all the entities in said scene.
> 
> Additionally, if the user calls `despawn_recursive`, it could lead to a repeated `despawn` action, resulting in a warning.

The just remove the instance from `spawned_instances`. Don't forget to do the same for normal scenes.

File: crates/bevy_scene/src/lib.rs [hunk 1]
```diff
@@ -59,6 +59,30 @@ impl Plugin for ScenePlugin {
...
+                    scene_spawner.despawn_instance(scene_instance);
+                }
+            });
+
+        // Register component hooks for Scene
+        app.world
+            .register_component_hooks::<Handle<Scene>>()
+            .on_remove(|mut world, entity, _| {
+                if let Some(&SceneInstance(scene_instance)) = world.get::<SceneInstance>(entity) {
+                    let mut scene_spawner = world.resource_mut::<SceneSpawner>();
```
Comment (james7132) [inline crates/bevy_scene/src/lib.rs:82]: Let's not panic if the resource is not found for whatever reason. If it's missing, there's no reason to be crashing the entire app. Use `world.get_resource_mut` and ignore it if it's `None` for whatever reason.

**Review by james7132 — APPROVED** [review]

**Review by alice-i-cecile — APPROVED** [review]

File: crates/bevy_scene/src/lib.rs [hunk 2]
```diff
@@ -59,6 +59,37 @@ impl Plugin for ScenePlugin {
...
+        // Register component hooks for DynamicScene
+        app.world
+            .register_component_hooks::<Handle<DynamicScene>>()
+            .on_remove(|mut world, entity, _| {
+                let Some(handle) = world.get::<Handle<DynamicScene>>(entity) else {
+                    return;
+                };
+                let id = handle.id();
+                if let Some(&SceneInstance(scene_instance)) = world.get::<SceneInstance>(entity) {
+                    let Some(mut scene_spawner) = world.get_resource_mut::<SceneSpawner>() else {
```
Comment (kristoff3r) [inline crates/bevy_scene/src/lib.rs:72]: Extremely minor nit, but is there a reason that one of these is `if let` and the other one is `let ... else`, instead of both being `let ... else`?

**Review by kristoff3r — APPROVED** [review]

File: crates/bevy_scene/src/lib.rs (hunk 2 above)
Comment (341101) [reply crates/bevy_scene/src/lib.rs:72]: Looks like using `let ... else` consistently would be better. The reason for the inconsistency between the two is that in a later commit, I changed `resource_mut` to `get_resource_mut`, but I didn't notice that the `if let` expression needed to correspond to it.

**Comment by mockersf** [comment]
removing from the 0.13.2 milestone as this use components hooks from https://github.com/bevyengine/bevy/pull/10756 which are not available in the 0.13
