### PR TITLE
Fix query transmute from table to archetype iteration unsoundness

### LINKED ISSUE #14348: Unsoundness in dynamic queries: sparse filters are ignored if the typed query is dense
## Bevy version

Both 0.14.0 and af865e76a323fc87dd16157e7f4d7593d02c2b95

## What you did

```rs
#[derive(Component)]
struct Dense;

#[derive(Component)]
#[component(storage = "SparseSet")]
struct Sparse;

let mut world = World::new();

world.spawn(Dense);
world.spawn((Dense, Sparse));

// How this is not working as intended:
let mut query = QueryBuilder::<&Dense>::new(&mut world)
    .without::<Sparse>()
    .build();
// Prints 2 but only 1 entity should be matched.
dbg!(query.iter(&world).count());

// How this is unsound:
fn sys(q1: Query<&mut Dense, With<Sparse>>, q2: Query<(Entity, &mut Dense)>) {
    for (entity, _) in &q2 {
        assert!(!q1.contains(entity));
    }
}
SystemBuilder::<(Query<&mut Dense, With<Sparse>>,)>::new(&mut world)
    .builder::<Query<(Entity, &mut Dense)>>(|builder| {
        builder.without::<Sparse>();
    })
    .build(sys)
    .run((), &mut world);
```

## What went wrong

In the simple demonstration the query contains 2 entities, but only 1 should match all the filters. The reason both are yielded is because the static part of the query is dense and so the dense iteration optimization kick in and iterates over the table matching it. But doing so completly ignores the filter on the sparse component.

In the soundness issue this is exploited in a dynamic system where the sparse filter is used to make the two queries disjoint, which is however broken by the bug just showed.

### LINKED ISSUE #14528: Unsoundness in QueryState::transmute_filtered
## Bevy version

It's unsound to transmute a query state if D::DENSE or F::DENSE changed

## What you did

```rust
use bevy::prelude::*;

#[derive(Component)]
struct Table;
#[derive(Component)]
#[component(storage = "SparseSet")]
struct Sparse;
#[allow(unsafe_code)]
fn main() {
    let mut world = World::new();
    world.spawn(Sparse);
    world.spawn((Table, Sparse));
    let query = QueryState::<(&Table, &Sparse)>::new(&mut world);
    let mut new_query = query.transmute_filtered::<(Entity, &Table), ()>(world.components());
    for e in new_query.iter(&mut world) {
        println!("{:?}", e.0);
    }
}

````

## What went wrong

process didn't exit successfully: `target\release\examples\hello_world.exe` (exit code: 0xc0000005, STATUS_ACCESS_VIOLATION)

### PR DESCRIPTION
**Pull request by SkiFire13**
# Objective

- Fixes #14348 
- Fixes #14528
- Less complex (but also likely less performant) alternative to #14611

## Solution

- Add a `is_dense` field flag to `QueryIter` indicating whether it is dense or not, that is whether it can perform dense iteration or not;
- Check this flag any time iteration over a query is performed.

---

It would be nice if someone could try benching this change to see if it actually matters.

~Note that this not 100% ready for mergin, since there are a bunch of safety comments on the use of the various `IS_DENSE` for checks that still need to be updated.~ This is ready modulo benchmarks

### CODE REVIEW

File: crates/bevy_ecs/src/query/state.rs [hunk 1]
```diff
@@ -505,10 +520,16 @@ impl<D: QueryData, F: QueryFilter> QueryState<D, F> {
...
+        // The dense-ness of the transmuted query depends on the dense-ness of the original filters
+        // and the dense-ness of the new accessed data.
+        let is_dense = NewD::IS_DENSE && NewF::IS_DENSE && self.is_dense;
+
         QueryState {
             world_id: self.world_id,
             archetype_generation: self.archetype_generation,
+            // TODO: This is unsound, since the dense-ness may have changed.
             matched_storage_ids: self.matched_storage_ids.clone(),
+            is_dense,
```
Comment (SkiFire13) [inline crates/bevy_ecs/src/query/state.rs:532]: Before merging there's this issue to solve. 

This could be done by removing all the `NewD::IS_DENSE && NewF::IS_DENSE &&` checks, thus allowing the static filters to be sparse while iteration still happens in a dense way. This however feels very sketchy and I would prefer to avoid doing this, but it seems to be sound, or at least I can't find an instance that passes the previous checks and then breaks with dense iteration (this does not fully convince me though, the lack of counterexamples doesn't make a theorem true!)

Alternatively we could change the query to iterate over the subsets of archetypes/tables actually matched by `NewD`/`NewF` (fixing #14628 in the process), but this would require an additional `&Archetypes` parameter (which would also suffer from #14629)

**Comment by SkiFire13** [comment]
I finally took the time to do a couple of benchmarks. My machine is pretty noisy, so don't expect them to be very accurate. It does show some small percent slowdown here and there, though they don't seem too bad, especially considering these are synthetic benchmarks.

```
group                                         main                                   pr
-----                                         ----                                   --
heavy_compute/base                            1.00    248.9±4.47µs        ? ?/sec    1.01    251.2±6.62µs        ? ?/sec
iter_fragmented(4096)_empty/foreach_sparse    1.00     12.6±0.33µs        ? ?/sec    1.00     12.6±0.22µs        ? ?/sec
iter_fragmented(4096)_empty/foreach_table     1.00      3.9±0.11µs        ? ?/sec    1.01      3.9±0.12µs        ? ?/sec
iter_fragmented/base                          1.00    430.1±7.49ns        ? ?/sec    1.00    428.1±4.77ns        ? ?/sec
iter_fragmented/foreach                       1.00    352.3±9.03ns        ? ?/sec    1.00    352.9±8.20ns        ? ?/sec
iter_fragmented/foreach_wide                  1.00      3.5±0.06µs        ? ?/sec    1.00      3.5±0.10µs        ? ?/sec
iter_fragmented/wide                          1.00      3.6±0.07µs        ? ?/sec    1.00      3.6±0.09µs        ? ?/sec
iter_fragmented_sparse/base                   1.00     11.7±0.16ns        ? ?/sec    1.00     11.6±0.17ns        ? ?/sec
iter_fragmented_sparse/foreach                1.00     11.7±0.23ns        ? ?/sec    1.00     11.6±0.28ns        ? ?/sec
iter_fragmented_sparse/foreach_wide           1.01     69.2±0.97ns        ? ?/sec    1.00     68.8±0.57ns        ? ?/sec
iter_fragmented_sparse/wide                   1.00     46.5±1.69ns        ? ?/sec    1.00     46.5±1.47ns        ? ?/sec
iter_simple/base                              1.00     10.0±0.14µs        ? ?/sec    1.00      9.9±0.13µs        ? ?/sec
iter_simple/foreach                           1.00      2.3±0.04µs        ? ?/sec    1.08      2.4±0.27µs        ? ?/sec
iter_simple/foreach_hybrid                    1.01     11.4±0.25µs        ? ?/sec    1.00     11.3±0.23µs        ? ?/sec
iter_simple/foreach_sparse_set                1.00     22.4±3.90µs        ? ?/sec    1.05     23.6±5.20µs        ? ?/sec
iter_simple/foreach_wide                      1.00     11.9±0.64µs        ? ?/sec    1.05     12.5±0.50µs        ? ?/sec
iter_simple/foreach_wide_sparse_set           1.00    113.8±1.59µs        ? ?/sec    1.00    114.1±2.20µs        ? ?/sec
iter_simple/sparse_set                        1.00     24.2±4.03µs        ? ?/sec    1.05     25.3±5.05µs        ? ?/sec
iter_simple/system                            1.01      9.9±0.18µs        ? ?/sec    1.00      9.9±0.13µs        ? ?/sec
iter_simple/wide                              1.00     45.7±0.63µs        ? ?/sec    1.00     45.5±0.86µs        ? ?/sec
iter_simple/wide_sparse_set                   1.01    121.1±2.03µs        ? ?/sec    1.00    120.4±3.74µs        ? ?/sec
par_iter_simple/with_0_fragment               1.00     35.2±3.12µs        ? ?/sec    1.01     35.7±3.74µs        ? ?/sec
par_iter_simple/with_1000_fragment            1.00     49.6±5.58µs        ? ?/sec    1.02     50.8±5.19µs        ? ?/sec
par_iter_simple/with_100_fragment             1.01     36.6±4.09µs        ? ?/sec    1.00     36.3±3.03µs        ? ?/sec
par_iter_simple/with_10_fragment              1.00     36.2±3.47µs        ? ?/sec    1.00     36.1±3.48µs        ? ?/sec
```

**Comment by hymm** [comment]
The for_each slowdowns are concerning. Might not be autovectorizing anymore.

**Comment by re0312** [comment]
> The for_each slowdowns are concerning. Might not be autovectorizing anymore.

10% more like a noise, if Auto-vectorization no longer works ,the loss may reach more than 50% ,I did some profiling ,it seems still works(windows).

maybe rust compiler already gets the ability to optimize this case.

here is my benchmark 
image

**Comment by SkiFire13** [comment]
> The for_each slowdowns are concerning. Might not be autovectorizing anymore.

I would expect them to be mainly noise since the changes don't really affect the inner loop over tables, which is the one that should be autovectorized. If there's any slowdown I would expect it to be for benchmarks that use plain `for` loops.

File: crates/bevy_ecs/src/query/builder.rs [hunk 2]
```diff
@@ -68,6 +69,18 @@ impl<'w, D: QueryData, F: QueryFilter> QueryBuilder<'w, D, F> {
...
+    pub(super) fn is_dense(&self) -> bool {
+        // Note: `component_id` comes from the user in safe code, so we cannot trust it to
+        // exist. If it doesn't exist we pessimistically assume it's sparse.
+        let is_dense = |component_id| {
+            self.world()
+                .components()
+                .get_info(component_id)
+                .map_or(false, |info| info.storage_type() == StorageType::Table)
+        };
+        self.access.with_filters().all(is_dense) && self.access.without_filters().all(is_dense)
```
Comment (NiseVoid) [inline crates/bevy_ecs/src/query/builder.rs:81]: Is the name of this function misleading or are we missing checks on the data that is being read? :thinking:

Comment (SkiFire13) [reply crates/bevy_ecs/src/query/builder.rs:81]: AFAIK it's not possible to get read/write access to some data without it being in the `with` filters somehow. I can extend the check just to be safe though.

**Review by NiseVoid — APPROVED** [review]

**Review by maniwani — APPROVED** [review]
