### PR TITLE
fix: reparenting perf

### LINKED ISSUE #23155: `update_reparented` performs an `O(n)` table scan over all entities with parents
## Problem

[`update_reparented`](https://github.com/bevyengine/bevy/blob/54b217b9a2d72ff4facb5caa8253e18078546630/crates/bevy_app/src/propagate.rs#L186) performs a change detection scan over every entity with a `ChildOf` component.

This is slow at high entity count!

>  On 0.18 update_reparented has a pretty gnarly perf issue. I have almost no ui, but I am paying 8ms every frame to run that system because I have 4m entities. 
> system{name="bevy_app::propagate::update_reparented<bevy_ui::ui_node::ComputedUiTargetCamera, (), bevy_ecs::hierarchy::ChildOf>"}
system{name="bevy_app::propagate::update_reparented<bevy_ui::ui_node::ComputedUiRenderTargetInfo, (), bevy_ecs::hierarchy::ChildOf>"}

As [reported](https://discord.com/channels/691052431525675048/743663673393938453/1476455464462975050) by @aevyrie

### PR DESCRIPTION
**Pull request by aevyrie**
# Objective

`HierarchyPropagatePlugin` contains a system `update_reparented` that scans every entity with the relationship component `R` every frame to test for `Changed<R>`. This means iterating over every child entity every frame, even when nothing has changed. This is a significant per-frame cost that scales linearly with child entity population.

Fixes #23155 

# Solution

Replace the `update_reparented` system and its `Changed<R>` query with two reactive lifecycle observers:

- **`on_r_inserted`**: registered on `On<Insert, R>`, fires only when `R` is actually inserted onto an entity. Copies `Inherited<C>` from the new parent if it has one, otherwise removes it from the entity.
- **`on_r_removed`**: registered on `On<Remove, R>`, fires only when `R` is actually removed from an entity. Removes `Inherited<C>` if the entity had inherited one.

This replaces an O(n) per-frame scan with O(1) per-event reactions.

## What about mutations?

`Changed<R>` also detects direct mutations to `R`, while `On<Insert, R>` does not. 

From what I can tell, this is safe to drop; **please review this logic for correctness!**

Relationship components like `ChildOf` must only be changed via `insert`, never by direct mutation. This is because `R` carries bookkeeping semantics enforced by component hooks. Inserting a new value triggers hooks that remove the entity from the old parent's `RelationshipTarget` and add it to the new one. Direct mutation via `Mut<R>` bypasses these hooks entirely, leaving the `RelationshipTarget` of both the old and new parent in an inconsistent state. Any app doing this already has a bug. `On<Insert, R>` fires for **both** first-time additions and replacements (re-inserts with a new value), which covers every valid way a relationship can change:

| Case | Old (`Changed<R>`) | New (`On<Insert, R>` / `On<Remove, R>`) |
|---|---|---|
| New child spawned with `R` | ✅ | ✅ via `On<Insert, R>` |
| Entity reparented (`insert(R)`) | ✅ | ✅ via `On<Insert, R>` |
| `R` removed (entity orphaned) | ✅ via `orphaned` query | ✅ via `On<Remove, R>` |
| `R` mutated directly via `Mut<R>` | ✅ | ❌ unsupported: breaks relationship invariants |

# Testing

All existing propagation tests pass, including:
- `test_reparented`: entity moved to a non-propagating parent loses `Inherited<C>`
- `test_reparented_with_prior`: entity moved between two propagating parents picks up the new value
- `test_remove_orphan`: entity with `R` removed loses `Inherited<C>`

### CODE REVIEW

**Comment by aevyrie** [comment]
This needs benchmarking to verify it works as advertised; although theoretically we are not doing the table scan any more, and using hooks seems correct for anything relationship-y.

**Comment by robtfm** [comment]
the logic looks sound: it moves the recalculation of moved children's `Inherited<C>` out of the SystemSet which currently contains all of the logic, but doesn't change the observable results since the `Inherited<C> -> C` write still happens in that SystemSet.

originally i suggested using a filter on parents of `(Changed<Children>, With<Inherited<C>>)` to write down the tree and avoid paying any cost on moves which don't involve any `Inherited<C>` components on the new parent or the child. 

I didn't realise then that `Changed<Children>` would involve a full table scan ... but i think that way would still be preferable since the tables being scanned would be limited to archetypes with `Inherited<C>` - so you only pay any cost if your entities are using the functionality. this way we still have a cost on every move (whether there is any inherited component or not).

that said, it is clearly better than the current state where we have a cost even for non-moving entities.

File: crates/bevy_app/src/propagate.rs [hunk 1]
```diff
@@ -166,7 +168,7 @@ pub fn update_source<C: Component + Clone + PartialEq, F: QueryFilter, R: Relati
             .try_insert(Inherited(source.0.clone()));
     }
 
-    // set `Inherited::<C>` based on ancestry when `Propagate::<C>` is removed
+    // set `Inherited::<C>` base d on ancestry when `Propagate::<C>` is removed
```
Comment (alice-i-cecile) [inline crates/bevy_app/src/propagate.rs]:
```suggestion
    // set `Inherited::<C>` based on ancestry when `Propagate::<C>` is removed
```

**Comment by alice-i-cecile** [comment]
@kfc35, I've removed the `S-Needs-Benchmarking` tag. While I'm usually strongly in favor of this for performance oriented PRs, this change is ultimately about the algorithmic complexity involved (to avoid paying irrelevant costs for very large scenes). As a result, the required properties can and should be verified by inspection / analysis.

File: crates/bevy_app/src/propagate.rs [hunk 2]
```diff
@@ -182,23 +184,35 @@ pub fn update_source<C: Component + Clone + PartialEq, F: QueryFilter, R: Relati
...
-        }
+    let Ok((relation, maybe_inherited)) = query.get(event.entity) else {
+        return;
+    };
+    if let Ok(inherited) = relations.get(relation.get()) {
+        commands.entity(event.entity).try_insert(inherited.clone());
+    } else if maybe_inherited.is_some() {
+        commands.entity(event.entity).try_remove::<Inherited<C>>();
     }
+}
```
Comment (janhohenheim) [inline crates/bevy_app/src/propagate.rs:206]: Changed `Option<&T>` to `Has<T>`
```suggestion
pub fn on_r_inserted<
    C: Component + Clone + PartialEq,
    F: QueryFilter + 'static,
    R: Relationship,
>(
    event: On<Insert, R>,
    mut commands: Commands,
    query: Query<(&R, Has<Inherited<C>>), (Without<Propagate<C>>, F)>,
    relations: Query<&Inherited<C>, Without<PropagateStop<C>>>,
) {
    let Ok((relation, is_inherited)) = query.get(event.entity) else {
        return;
    };
    if let Ok(inherited) = relations.get(relation.get()) {
        commands.entity(event.entity).try_insert(inherited.clone());
    } else if is_inherited.is_some() {
        commands.entity(event.entity).try_remove::<Inherited<C>>();
    }
}
```

File: crates/bevy_app/src/propagate.rs [hunk 3]
```diff
@@ -302,9 +316,10 @@ pub fn propagate_output<C: Component + Clone + PartialEq, F: QueryFilter>(
         commands.entity(entity).try_insert(inherited.0.clone());
     }
 
-    for removed in removed.read() {
-        if skip.get(removed).is_err() {
-            commands.entity(removed).try_remove::<C>();
+    for inherited_removed in inherited_removed.read() {
+        // Skip removal if propagation components were re-added this update
```
Comment (janhohenheim) [inline crates/bevy_app/src/propagate.rs:320]: I don't get this change, help

Comment (aevyrie) [reply crates/bevy_app/src/propagate.rs:320]: Copied from discord:

> so, if any of those components is re-added, we need to skip the removal process 
I also changed the naming a bit to try and make it a bit more clear and remove double-negation
so looking at the bottom there, that if statement is ensuring we only remove the component if those propagation components are actually removed

File: crates/bevy_app/src/propagate.rs [hunk 4]
```diff
@@ -182,23 +184,35 @@ pub fn update_source<C: Component + Clone + PartialEq, F: QueryFilter, R: Relati
...
+/// Add/remove [`Inherited::<C>`] when an entity gains or changes its `R` relationship
+pub fn on_r_inserted<
+    C: Component + Clone + PartialEq,
+    F: QueryFilter + 'static,
+    R: Relationship,
+>(
+    event: On<Insert, R>,
     mut commands: Commands,
-    moved: Query<(Entity, &R, Option<&Inherited<C>>), (Changed<R>, Without<Propagate<C>>, F)>,
+    query: Query<(&R, Has<&Inherited<C>>), (Without<Propagate<C>>, F)>,
```
Comment (alice-i-cecile) [inline crates/bevy_app/src/propagate.rs]:
```suggestion
    query: Query<(&R, Has<Inherited<C>>), (Without<Propagate<C>>, F)>,
```
