### PR TITLE
Fix TAA on camera with viewport

### LINKED ISSUE #14526: Crash when using `TemporalAntiAliasBundle` and `Viewport` together
## Bevy version

0.14.0

## Relevant system information

```ignore
`AdapterInfo { name: "Apple M3 Max", vendor: 0, device: 0, device_type: IntegratedGpu, driver: "", driver_info: "", backend: Metal }`
```

## What you did

Using `Viewport` with a resolution set to a value that does not match the window resolution leads to a crash if `TemporalAntiAliasBundle` is enabled. Below is a minimal example:

````rust
use bevy::{
    core_pipeline::experimental::taa::{TemporalAntiAliasBundle, TemporalAntiAliasPlugin},
    prelude::*,
    render::camera::Viewport,
    window::WindowResolution,
};

fn main() {
    App::new()
        .add_plugins(DefaultPlugins.set(WindowPlugin {
            primary_window: Some(Window {
                title: "TemporalAntiAlias and Viewport minimal example".to_string(),
                resolution: WindowResolution::new(1920., 1080.),
                ..default()
            }),
            ..default()
        }))
        .add_plugins(TemporalAntiAliasPlugin)
        .add_systems(Startup, camera)
        .run();
}

pub fn camera(mut commands: Commands) {
    commands
        .spawn(Camera3dBundle {
            camera: Camera {
                viewport: Some(Viewport {
                    physical_position: UVec2::new(0, 0),
                    physical_size: UVec2::new(1024, 768),
                    ..default()
                }),
                ..Default::default()
            },
            ..default()
        })
        .insert(TemporalAntiAliasBundle::default());
}
````

## What went wrong
````
thread '<unnamed>' panicked
wgpu error: Validation Error

Caused by:
    In a RenderPass
      note: encoder = `<CommandBuffer-(1, 1, Metal)>`
    In a pass parameter
      note: command buffer = `<CommandBuffer-(1, 1, Metal)>`
    Attachments have differing sizes: the color attachment at index 0's texture view has extent (1920, 1080, 1) but is followed by the color attachment at index 1's texture view which has (1024, 768, 1)
````

### PR DESCRIPTION
**Pull request by tychedelia**
# Objective

Closes #14526 

## Solution

The history texture was being created incorrectly with the viewport size rather than target size. When viewport < target, this meant that the render attachments would differer in size which causes a wgpu validation error.

## Testing

Example in linked issue works.

### CODE REVIEW

**Review by killercup — APPROVED** [review]
Reproduced the bug on main, and this fixes it 👍

File: crates/bevy_core_pipeline/src/taa/mod.rs [hunk 1]
```diff
@@ -410,7 +410,7 @@ fn prepare_taa_history_textures(
     views: Query<(Entity, &ExtractedCamera, &ExtractedView), With<TemporalAntiAliasSettings>>,
 ) {
     for (entity, camera, view) in &views {
-        if let Some(physical_viewport_size) = camera.physical_viewport_size {
+        if let Some(physical_viewport_size) = camera.physical_target_size {
```
Comment (IceSentry) [inline crates/bevy_core_pipeline/src/taa/mod.rs:413]: can you also update the variable name in the `Some()`

**Review by IceSentry — APPROVED** [review]

**Review by JMS55 — APPROVED** [review]
Don't know if this is enough to get TAA working broadly with multiple viewports/targets, but the logic is fine and it fixes a bug according to users, so I'm good with approving it.
