### PR TITLE
Fix horizontal scrolling in scroll example for macOS

### LINKED ISSUE #15401: Horizontal scroll does not work in `scroll` example
## Bevy version

main

## Relevant system information

```
SystemInfo { os: "MacOS 14.5 ", kernel: "23.5.0", cpu: "Apple M1 Max", core_count: "10", memory: "64.0 GiB" }
AdapterInfo { name: "Apple M1 Max", vendor: 0, device: 0, device_type: IntegratedGpu, driver: "", driver_info: "", backend: Metal }
```

## What you did

`cargo run --example scroll`

- Hover over horizontal scroll pane
- Hold left shift and use scroll wheel

## What went wrong

No scrolling occurs.

## Additional information

It seems that the scroll axis is already being changed when the shift key is used at the OS or possibly winit level.

Commenting out https://github.com/bevyengine/bevy/blob/55dddaf72e9c14bf044b3ff2114aac8a92e9fb30/examples/ui/scroll.rs#L394-L397 makes the behavior correct.

### PR DESCRIPTION
**Pull request by Piefayth**
# Objective
Fixes #15401

## Solution
Changes the scroll inversion hotkey in the example from Shift to Control.

Shift is idiomatic for this. Since we cannot use Shift per #15401, I picked another modifier arbitrarily. A production app would handle this in a platform specific way until the platform behaviors are unified upstream, but no point here.

## Testing
I don't have a mac readily available for testing, if someone wouldn't mind testing. I would also appreciate confirmation that trackpad is working nicely.

### CODE REVIEW

**Review by alice-i-cecile — APPROVED** [review]

File: examples/ui/scroll.rs [hunk 1]
```diff
@@ -391,7 +391,8 @@ pub fn update_scroll_position(
             MouseScrollUnit::Pixel => (mouse_wheel_event.x, mouse_wheel_event.y),
         };
 
-        if keyboard_input.pressed(KeyCode::ShiftLeft) || keyboard_input.pressed(KeyCode::ShiftRight)
+        if keyboard_input.pressed(KeyCode::ControlLeft)
+            || keyboard_input.pressed(KeyCode::ControlLeft)
```
Comment (chompaa) [inline examples/ui/scroll.rs:395]:
```suggestion
            || keyboard_input.pressed(KeyCode::ControlRight)
```

Comment (Piefayth) [reply examples/ui/scroll.rs]: 🤦‍♂️ thank you
