### PR TITLE
Fix `AnimationTargetId` collisions

### LINKED ISSUE #22842: `AnimationTargetId` hash collisions
While looking through `bevy_animations` I noticed that the hashing of `AnimationTargetId`s will produce unwanted collisions.

[This is the relevant code](https://github.com/bevyengine/bevy/blob/f1a954430af1ae123704acbca53da6fa7938b5d8/crates/bevy_animation/src/lib.rs#L1269)

Example collisions:

 - `["bone", "head"]`
 - `["bonehead"]`
 - `["bon", "ehe", "ad"]`

Semantically these are different paths addressing different targets, but they'll all produce the same UUID, because the hashing function just concatenates the names.

This can be fixed by either using a separator or length prefix. I recommend length prefix, because with a separator you'd need to make sure it doesn't appear in names.

Suggested fix:

```rust
    pub fn from_names<'a>(names: impl Iterator<Item = &'a Name>) -> Self {
        let mut blake3 = blake3::Hasher::new();
        blake3.update(ANIMATION_TARGET_NAMESPACE.as_bytes());
        for name in names {
            // added this line
            blake3.update(&(name.len() as u64).to_be_bytes());

            blake3.update(name.as_bytes());
        }
        let hash = blake3.finalize().as_bytes()[0..16].try_into().unwrap();
        Self(*uuid::Builder::from_sha1_bytes(hash).as_uuid())
    }
```

I apologize for not making a pull request. I might make one later :)

### PR DESCRIPTION
**Pull request by greeble-dev**
## Objective

Fixes #22842. TLDR: `AnimationTargetId::from_iter` wrongly returns the same id for `["ab"]` and `["a", "b"]`.

## Solution

As suggested in the issue, add the length of each string to the hash. The original suggestion used `to_be_bytes`, but I used `to_le_bytes` on the assumption that most users are targeting LE and this will be more efficient.

- There's probably a way to break it with maliciously crafted names, but I can't imagine a case where that's a problem.
- I considered hashing `0xffu8` after each string instead of the length.
  - That would be more efficient, and should be safe since it's not a valid UTF8 character.
  - But I wasn't quite confident enough.
- I also refactored `AnimationTargetId::from_names` to reuse `AnimationTargetId::from_iter`.

## Testing

```sh
cargo test -p bevy_animation
cargo run --example animated_mesh
cargo run --example animated_mesh_events
cargo run --example animation_masks
```

### CODE REVIEW

File: crates/bevy_animation/src/lib.rs [hunk 1]
```diff
@@ -1664,4 +1661,47 @@ mod tests {
...
+        for (li, lp) in paths.iter().enumerate() {
+            for rp in paths.iter().skip(li + 1) {
+                let lt = AnimationTargetId::from_iter(lp.iter());
+                let rt = AnimationTargetId::from_iter(rp.iter());
+
+                assert!(lt != rt, "{:?} and {:?} collided. {:?} ", lp, rp, lt);
+            }
+        }
+
+        // Test that `from_iter` is equivalent to `from_names`.
```
Comment (greeble-dev) [inline crates/bevy_animation/src/lib.rs:1694]: This test might not be justified. I originally added it because `from_iter` and `from_names` had different implementations. But later on I refactored them to share the same implementation.

**Comment by hukasu** [comment]
instead of `0xffu8`, maybe any other control character since they would cause problems in actual strings?

**Comment by greeble-dev** [comment]
> instead of `0xffu8`, maybe any other control character since they would cause problems in actual strings?

I think that would be less safe, although only slightly. It's difficult to construct a `str` with an invalid character (i.e. `str::from_utf8(&[0xffu8])` is an error), but it can contain control characters. Kinda unlikely anyone would make a joint name with a control character, but I've seen stranger things.
