### PR TITLE
Fix beta CI

### LINKED ISSUE #12905: Main branch fails to compile on Rust beta.
## Weekly CI run has failed.
[The offending run.]($FAILED_RUN)

### PR DESCRIPTION
**Pull request by BD103**
# Objective

- Fixes #12905.

## Solution

- Use proper code `` tags for `TaskPoolBuilder::thread_name`.
- Remove leftover documentation in `TaskPool` referencing the deleted `TaskPoolInner` struct.
  - It may be possible to rephrase this, but I do not know enough about the task pool to write something. (cc @james7132 who made the change removing `TaskPoolInner`.)
- Ignore a buggy rustdoc lint that thinks `App` is already in scope for `UpdateMode` doc. (Extracted from #12692.)

### CODE REVIEW

**Comment by BD103** [comment]
cc @Brezak :)

**Review by james7132 — APPROVED** [review]

**Comment by mockersf** [comment]
> a buggy rustdoc lint 

Do you know if that's tracked on rust side?

**Review by mockersf — APPROVED** [review]

File: crates/bevy_tasks/src/task_pool.rs [hunk 1]
```diff
@@ -106,14 +106,10 @@ impl TaskPoolBuilder {
...
-    ///
-    /// This has to be separate from TaskPoolInner because we have to create an `Arc<Executor>` to
-    /// pass into the worker threads, and we must create the worker threads before we can create
-    /// the `Vec<Task<T>>` contained within `TaskPoolInner`
+    /// The executor for the pool.
     executor: Arc<async_executor::Executor<'static>>,
 
-    /// Inner state of the pool
+    // The inner state of the pool.
     threads: Vec<JoinHandle<()>>,
```
Comment (Brezak) [inline crates/bevy_tasks/src/task_pool.rs:113]: `threads` is documented with a normal comment while `executor` is documented with a doc comment. It would be a good idea to pick one type of comment and stick with it. Note that doc comments on private fields don't seem to show up  in the documentation even when `--document-private-items` is used.

**Review by Brezak — CHANGES_REQUESTED** [review]

File: crates/bevy_tasks/src/task_pool.rs (hunk 1 above)
Comment (Brezak) [reply crates/bevy_tasks/src/task_pool.rs:113]: Note that doc comments on private fields don't seem to show up in the documentation even when `--document-private-items` is used.

Comment (BD103) [reply crates/bevy_tasks/src/task_pool.rs:113]: > You seem to have accidentally changed the `threads` doc comment into a normal comment.

This was intentional. The comment used to refer to a single field, `TaskPoolInner`, but later was split into two separate fields. Instead of duplicating the doc comment, I chose to make it a regular one.

**Review by Brezak — APPROVED** [review]
