### PR TITLE
FIX: iOS Simulator not rendering due to missing CUBE_ARRAY_TEXTURES

### LINKED ISSUE #11978: iOS Simulator not rendering due to missing CUBE_ARRAY_TEXTURES capability
Seems like the iOS Simulator uses an MTLFeatureSet not including CUBE_ARRAY_TEXTURES so currently nothing gets rendered with this error message:

```
2024-02-19T14:59:34.896266Z ERROR bevy_render::render_resource::pipeline_cache: failed to create shader module: Validation Error

Caused by:
    In Device::create_shader_module
    
Shader validation error: 


    Type [40] '' is invalid
    Capability Capabilities(CUBE_ARRAY_TEXTURES) is required
```

Saw that this was discussed in #10266 and that it might lead to a potential issue. Any pointers on how this could be fixed?

I'm open to work on it and make a PR for it, simply just using the DownLevel flags don't seem to work as it will just lead to a downstream error in naga_oil instead.

## Bevy version

0.13

## Relevant system information

XCode 15.2.0 - iOS 17.2 Simulator - iPhone 15 Pro

```ignore
`AdapterInfo { name: "Apple iOS simulator GPU", vendor: 0, device: 0, device_type: DiscreteGpu, driver: "", driver_info: "", backend: Metal }`
```

### PR DESCRIPTION
**Pull request by sampettersson**
This PR closes #11978

# Objective

Fix rendering on iOS Simulators.

iOS Simulator doesn't support the capability CUBE_ARRAY_TEXTURES, since 0.13 this started to make iOS Simulator not render anything with the following message being outputted:

```
2024-02-19T14:59:34.896266Z ERROR bevy_render::render_resource::pipeline_cache: failed to create shader module: Validation Error

Caused by:
    In Device::create_shader_module
    
Shader validation error: 


    Type [40] '' is invalid
    Capability Capabilities(CUBE_ARRAY_TEXTURES) is required
```

## Solution

- Split up NO_ARRAY_TEXTURES_SUPPORT into both NO_ARRAY_TEXTURES_SUPPORT and NO_CUBE_ARRAY_TEXTURES_SUPPORT and correctly apply NO_ARRAY_TEXTURES_SUPPORT for iOS Simulator using the cfg flag introduced in #10178.

---

### Fixed
- Rendering on iOS Simulator due to missing CUBE_ARRAY_TEXTURES support.

### CODE REVIEW

File: crates/bevy_pbr/src/render/light.rs [hunk 1]
```diff
@@ -1210,16 +1210,18 @@ pub fn prepare_lights(
                 .create_view(&TextureViewDescriptor {
                     label: Some("point_light_shadow_map_array_texture_view"),
                     format: None,
-                    #[cfg(any(
-                        not(feature = "webgl"),
-                        not(target_arch = "wasm32"),
-                        feature = "webgpu"
+                    #[cfg(all(
+                        not(ios_simulator),
```
Comment (james7132) [inline crates/bevy_pbr/src/render/light.rs:1214]: A comment on why this is necessary should be added here in case this changes in the future.

Comment (sampettersson) [reply crates/bevy_pbr/src/render/light.rs:1216]: Yeah, hopefully Apple eventually adds support for this, so good idea to add a comment. Fixed!

**Review by mockersf — APPROVED** [review]

**Review by james7132 — APPROVED** [review]
