### PR TITLE
Make TrackedRenderPass::set_vertex_buffer aware of slice size

### LINKED ISSUE #14841: TrackedRenderPass::set_vertex_buffer does not update if the size of sliced buffer changed
## Bevy version

0.14.1

## What you did

In #14721, I set a slice of seemingly correct size as a vertex buffer and got errors like `Instance 555 extends beyond limit 554 imposed by the buffer in slot 3`.

## What went wrong

In this case, the same underlying buffer is used as vertex buffer with the same offset but different sizes (`slice(item_size..)` vs `slice(item_size..buf_size)`) from two draw functions. 
It looks like `TrackedRenderPass::set_vertex_buffer` returns without updating the vertex buffer if `buffer` and `offset` matches, ignoring its size.

https://github.com/bevyengine/bevy/blob/6e2f96f2224032e04e77b993ad4c06d76d49039f/crates/bevy_render/src/render_phase/draw_state.rs#L190-L203

https://github.com/bevyengine/bevy/blob/6e2f96f2224032e04e77b993ad4c06d76d49039f/crates/bevy_render/src/render_phase/draw_state.rs#L76-L82

### PR DESCRIPTION
**Pull request by akimakinai**
# Objective

- Fixes #14841

## Solution

- Compute BufferSlice size manually and use it for comparison in `TrackedRenderPass`

## Testing

- Gizmo example does not crash with #14721 (without system ordering), and `slice` computes correct size there

---

## Migration Guide

- `TrackedRenderPass::set_vertex_buffer` function has been modified to update vertex buffers when the same buffer with the same offset is provided, but its size has changed. Some existing code may rely on the previous behavior, which did not update the vertex buffer in this scenario.

### CODE REVIEW

File: crates/bevy_render/src/render_phase/draw_state.rs [hunk 1]
```diff
@@ -21,13 +21,14 @@ use wgpu::{IndexFormat, QuerySet, RenderPass};
...
     bind_groups: Vec<(Option<BindGroupId>, Vec<u32>)>,
-    vertex_buffers: Vec<Option<(BufferId, u64)>>,
+    // BufferId, offset, size
+    vertex_buffers: Vec<Option<(BufferId, u64, u64)>>,
     index_buffer: Option<(BufferId, u64, IndexFormat)>,
 }
 
 impl DrawState {
     /// Marks the `pipeline` as bound.
-    pub fn set_pipeline(&mut self, pipeline: RenderPipelineId) {
```
Comment (tychedelia) [inline crates/bevy_render/src/render_phase/draw_state.rs:30]: Just a note to other reviewers, it seems like this was a CI suggestion, and makes sense because DrawState is itself private to `TrackedRenderPass`.

**Review by tychedelia — APPROVED** [review]
Looks good to me. Wish this code was easier to test. The previous assumption was obviously that an immutable slice itself can't change, but didn't anticipate slicing the same part of the buffer differently. Thanks for tracking this down!

File: crates/bevy_render/src/render_phase/draw_state.rs [hunk 2]
```diff
@@ -21,13 +21,14 @@ use wgpu::{IndexFormat, QuerySet, RenderPass};
 struct DrawState {
     pipeline: Option<RenderPipelineId>,
     bind_groups: Vec<(Option<BindGroupId>, Vec<u32>)>,
-    vertex_buffers: Vec<Option<(BufferId, u64)>>,
+    // BufferId, offset, size
+    vertex_buffers: Vec<Option<(BufferId, u64, u64)>>,
```
Comment (bushrat011899) [inline crates/bevy_render/src/render_phase/draw_state.rs:25]:
```suggestion
    /// List of vertex buffers by [`BufferId`], offset, and size. See [`DrawState::buffer_slice_key`]
    vertex_buffers: Vec<Option<(BufferId, u64, u64)>>,
```

Might as well make this a documentation so that it appears as a tooltip in most IDEs.

**Review by bushrat011899 — APPROVED** [review]
Looks good, just a small note around helper documentation.
