### PR TITLE
Fix unhandled null characters in Android logs

### LINKED ISSUE #12728: Android logging may need reencoding of the logged values or may be unsound
Found in #12684. The call into `android_log_sys::__android_log_write` may be unsound here: 

https://github.com/bevyengine/bevy/blob/31d91466b4fb99786a8c61b82417372a42a3f531/crates/bevy_log/src/android_tracing.rs#L88-L95

This unsafe call is undocumented and casts two UTF-8 encoded strings as if they were using the OS encoding. They're properly null-terminated, but probably should be converted into `OsString` or `CString` before passing into the function.

### PR DESCRIPTION
**Pull request by james7132**
# Objective
Fix #12728.  Fix unsoundnesss from unhandled null characters in Android logs.

## Solution
Use `CString` instead of using formatted Strings. Properly document the safety invariants of the FFI call.

### CODE REVIEW

File: crates/bevy_log/src/android_tracing.rs [hunk 1]
```diff
@@ -85,13 +88,15 @@ impl<S: Subscriber + for<'a> LookupSpan<'a>> Layer<S> for AndroidLayer {
             Level::WARN => android_log_sys::LogPriority::WARN,
             Level::ERROR => android_log_sys::LogPriority::ERROR,
         };
-        let message = format!("{}\0", recorder);
-        let tag = format!("{}\0", meta.name());
+        let message = CString::new(recorder).expect("message contained null character.");
+        let tag = CString::new(meta.name()).expect("tag contained null character.");
```
Comment (Kanabenki) [inline crates/bevy_log/src/android_tracing.rs:92]: Would it be better to filter out any null char before creating the `CString`? That way the log behavior would match the rust side if the passed strings contain any null byte (they would just be skipped when printing).

Comment (BD103) [reply crates/bevy_log/src/android_tracing.rs:92]: I agree with this eventual approach, any null bytes should be converted to [the replacement character](https://doc.rust-lang.org/stable/std/primitive.char.html#associatedconstant.REPLACEMENT_CHARACTER). This might need benching, though.

I think this PR should be merged as-is any probably marked for 0.13.2, then we can create a follow-up PR that removes panicking.

File: crates/bevy_log/src/android_tracing.rs [hunk 2]
```diff
@@ -85,13 +88,15 @@ impl<S: Subscriber + for<'a> LookupSpan<'a>> Layer<S> for AndroidLayer {
...
+        // SAFETY: Called only on Android platforms. priority is guaranteed to be in range of c_int.
+        // The provided tag and message are null terminated properly.
         unsafe {
             android_log_sys::__android_log_write(
                 priority as android_log_sys::c_int,
-                tag.as_ptr() as *const android_log_sys::c_char,
-                message.as_ptr() as *const android_log_sys::c_char,
+                tag.as_c_str().as_ptr(),
```
Comment (BD103) [inline crates/bevy_log/src/android_tracing.rs:98]:
```suggestion
                tag.as_ptr(),
```

It's not necessary to convert to a `CStr` before extracting the pointer, since `CString` implements `Deref`. :)

**Review by BD103 — CHANGES_REQUESTED** [review]

File: crates/bevy_log/src/android_tracing.rs (hunk 1 above)
Comment (james7132) [reply crates/bevy_log/src/android_tracing.rs]: Done. The allocation needs iteration anyway. This should be identical other than using memcpy vs byte-by-byte checks here. This will be slower for big strings, but this shouldn't be a performance critical path in many apps.

**Review by BD103 — APPROVED** [review]

**Review by Kanabenki — APPROVED** [review]

**Review by matiqo15 — APPROVED** [review]
