### PR TITLE
Fix failed sub-asset loads getting stuck in `LoadState::Loading`

### LINKED ISSUE #22607: Failed sub-asset loads can get stuck in `LoadState::Loading`
## Bevy version

0.18

## What you did

```rust
// Load a labeled sub-asset that doesn't exist.
let handle = asset_server.load::<AssetType>("asset#non_existent_subasset");

// Or does exist, but is not of type `WrongAssetType`.
let handle = asset_server.load::<WrongAssetType>("asset#subasset");

// Or where the asset loader returns an error.
let handle = asset_server.load::<AssetType>("malformed_asset#subasset");
```

## What went wrong

I expected `AssetServer::get_load_state(handle)` to eventually return `LoadState::Failed` with an appropriate error. But instead it gets stuck in `LoadState::Loading`.

### PR DESCRIPTION
**Pull request by greeble-dev**
## Objective

Fix #22607. Also add a test that reproduces the issues.

If it makes things clearer, I can split this into an "add a test" PR and a separate "fix the bug" PR.

## Solution

There are three additions to `AssetServer::load_internal` that each fix a separate case. In source code order:

### Case 1

```rust
// Sub-asset exists, but is not of type `WrongAssetType`.
asset_server.load::<WrongAssetType>("asset#subasset");
```

Previously this would silently fail - the asset would successfully load, but the handle can't actually resolve to that asset so it's stuck in limbo.

Fixed by adding a type check, then sending a `AssetLoadError::RequestedHandleTypeMismatch` event and returning it as an error.

Note that this doesn't prevent someone loading the asset with the correct type - the error is only associated with the `<WrongAssetType>` handle.

### Case 2

```rust
// Sub-asset doesn't exist.
asset_server.load::<AssetType>("asset#non_existent_subasset");
```

Previously this was detected and would return a `AssetLoadError::MissingLabel` error from `load_internal`, but the load status for the handle wasn't set.

Fixed by sending an `InternalAssetEvent::Failed`.

### Case 3
```rust
// Asset loader returns an error.
asset_server.load::<AssetType>("malformed_asset#subasset");
```

Previously this was detected, but the event was sent with the root asset's id (`base_asset_id`) so it wasn't associated with the sub-asset's handle.

Fixed by using the sub-asset's id.

### Notes

Some of the events are only sent if `asset_id` is set. This might seem odd, but I think it's correct - `asset_id` can only be unset when using `load_untyped` with a sub-asset path, in which case there's no handle to associate with the error, and so there's no handle to pass to `get_load_status`.

## Testing

```sh
cargo test -p bevy_asset
cargo test -p bevy_asset --features "multi_threaded"
```

### CODE REVIEW

File: crates/bevy_asset/src/lib.rs [hunk 1]
```diff
@@ -2904,4 +2906,169 @@ mod tests {
...
+        let handle = asset_server.load::<A>(path);
+        let mut load_state = TestLoadState::NotLoaded;
+
+        for _ in 0..LARGE_ITERATION_COUNT {
+            app.update();
+            load_state = asset_server.get_load_state(&handle).unwrap().into();
+            if load_state == expected_load_state {
+                break;
+            }
+        }
```
Comment (andriyDev) [inline crates/bevy_asset/src/lib.rs:3006]: Should we just use run_app_until here instead?

Comment (greeble-dev) [reply crates/bevy_asset/src/lib.rs:3006]: I did this initially, but found that it made debugging test failures harder - `run_app_until` will panic without any information about what failed. Doing it manually lets me print a clear "did X, expected Y, got Z".

I do think there's room for improvement. Maybe adding a `run_app_until` variant with more options, or even better a way to say "run until all loads have resolved". But don't think that would fit in this PR.
