### PR TITLE
Descriptive error message for circular required components recursion

### LINKED ISSUE #16645: Cycles in required components produce inscrutable error messages
## Bevy version

0.15, main

## What you did

```rust
use bevy::prelude::*;

#[derive(Component, Default)]
#[require(A)]
struct A;

#[derive(Component, Default)]
#[require(C)]
struct B;
#[derive(Component, Default)]
#[require(B)]
struct C;

fn main() {
    App::new()
        .add_plugins(DefaultPlugins)
        .add_systems(Startup, setup)
        .run();
}

fn setup(mut commands: Commands) {
    commands.spawn(A);
    //commands.spawn(B);
}
```

## What went wrong

```
thread 'main' panicked at examples/cycles.rs:9:10:
attempt to add with overflow
```

Digging a bit deeper, we get some hints, and it's probably fairly clear what's going on.

```
thread 'main' panicked at examples/cycles.rs:9:10:
attempt to add with overflow
stack backtrace:
   0: rust_begin_unwind
             at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/std/src/panicking.rs:665:5
   1: core::panicking::panic_fmt
             at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/core/src/panicking.rs:74:14
   2: core::panicking::panic_const::panic_const_add_overflow
             at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/core/src/panicking.rs:181:21
   3: <cycles::B as bevy_ecs::component::Component>::register_required_components
             at ./examples/cycles.rs:9:10
   4: <cycles::C as bevy_ecs::component::Component>::register_required_components
             at ./examples/cycles.rs:12:10
```

But here's a case from "the wild" where I accidentally introduced a case like `A` above, and it wasn't so clear.

```rust
#[derive(Component, Default)]
#[require(Sprite, HitPoints, TilePos, MovingProgress, Speed, WorkCooldown, Worker)]
pub struct Worker;
```

<details>
<summary>Expand large backtrace</summary>

```
thread 'main' panicked at /Users/me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_transform-0.15.0/src/components/transform.rs:43:12:
attempt to add with overflow
stack backtrace:
   0: rust_begin_unwind
             at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/std/src/panicking.rs:665:5
   1: core::panicking::panic_fmt
             at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/core/src/panicking.rs:74:14
   2: core::panicking::panic_const::panic_const_add_overflow
             at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/core/src/panicking.rs:181:21
   3: <bevy_transform::components::transform::Transform as bevy_ecs::component::Component>::register_required_components
             at /Users/me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_transform-0.15.0/src/components/transform.rs:43:12
   4: <bevy_sprite::sprite::Sprite as bevy_ecs::component::Component>::register_required_components
             at /Users/me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_sprite-0.15.0/src/sprite.rs:13:10
   5: <entytd::worker::Worker as bevy_ecs::component::Component>::register_required_components
             at ./src/worker.rs:39:10
   6: bevy_ecs::component::Components::register_component
             at /Users/me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.15.0/src/component.rs:917:13
   7: bevy_ecs::world::World::register_component
             at /Users/me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.15.0/src/world/mod.rs:272:9
   8: <bevy_ecs::query::filter::With<T> as bevy_ecs::query::world_query::WorldQuery>::init_state
             at /Users/me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.15.0/src/query/filter.rs:194:15
   9: <(F0,F1,F2) as bevy_ecs::query::world_query::WorldQuery>::init_state
             at /Users/me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.15.0/src/query/world_query.rs:228:20
  10: bevy_ecs::query::state::QueryState<D,F>::new_uninitialized
             at /Users/me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.15.0/src/query/state.rs:188:28
  11: bevy_ecs::query::state::QueryState<D,F>::new_with_access
             at /Users/me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.15.0/src/query/state.rs:168:25
  12: <bevy_ecs::system::query::Query<D,F> as bevy_ecs::system::system_param::SystemParam>::init_state
             at /Users/me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.15.0/src/system/system_param.rs:298:21
  13: <(P0,P1,P2,P3) as bevy_ecs::system::system_param::SystemParam>::init_state
             at /Users/me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.15.0/src/system/system_param.rs:1913:21
  14: <bevy_ecs::system::function_system::FunctionSystem<Marker,F> as bevy_ecs::system::system::System>::initialize
             at /Users/me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.15.0/src/system/function_system.rs:779:37
  15: bevy_ecs::schedule::schedule::ScheduleGraph::initialize
             at /Users/me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.15.0/src/schedule/schedule.rs:1057:21
  16: bevy_ecs::schedule::schedule::Schedule::initialize
             at /Users/me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.15.0/src/schedule/schedule.rs:406:13
  17: bevy_ecs::schedule::schedule::Schedule::run
             at /Users/me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.15.0/src/schedule/schedule.rs:382:9
  18: bevy_ecs::world::World::try_run_schedule::{{closure}}
             at /Users/me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.15.0/src/world/mod.rs:3720:55
  19: bevy_ecs::world::World::try_schedule_scope
             at /Users/me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.15.0/src/world/mod.rs:3653:21
  20: bevy_ecs::world::World::try_run_schedule
             at /Users/me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.15.0/src/world/mod.rs:3720:9
  21: bevy_app::main_schedule::Main::run_main::{{closure}}
             at /Users/me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_app-0.15.0/src/main_schedule.rs:279:31
  22: bevy_ecs::world::World::resource_scope
             at /Users/me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.15.0/src/world/mod.rs:2824:22
  23: bevy_app::main_schedule::Main::run_main
             at /Users/me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_app-0.15.0/src/main_schedule.rs:277:9
  24: core::ops::function::FnMut::call_mut
             at /Users/me/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/function.rs:166:5
  25: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
             at /Users/me/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/function.rs:294:13
  26: <Func as bevy_ecs::system::exclusive_function_system::ExclusiveSystemParamFunction<fn(F0) .> Out>>::run::call_inner
             at /Users/me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.15.0/src/system/exclusive_function_system.rs:245:21
  27: <Func as bevy_ecs::system::exclusive_function_system::ExclusiveSystemParamFunction<fn(F0) .> Out>>::run
             at /Users/me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.15.0/src/system/exclusive_function_system.rs:248:17
  28: <bevy_ecs::system::exclusive_function_system::ExclusiveFunctionSystem<Marker,F> as bevy_ecs::system::system::System>::run::{{closure}}
             at /Users/me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.15.0/src/system/exclusive_function_system.rs:129:23
  29: bevy_ecs::world::World::last_change_tick_scope
             at /Users/me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.15.0/src/world/mod.rs:3187:9
  30: <bevy_ecs::system::exclusive_function_system::ExclusiveFunctionSystem<Marker,F> as bevy_ecs::system::system::System>::run
             at /Users/me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.15.0/src/system/exclusive_function_system.rs:121:9
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Encountered a panic in system `bevy_app::main_schedule::Main::run_main`!
```
</details>

## Additional information

I haven't looked at the required components code, but it feels like case `A` should be detectable. And it might be possible to improve case `B` by introducing a smaller recursion limit and a prettier error.

### PR DESCRIPTION
**Pull request by SpecificProtagonist**
# Objective

Fixes #16645

## Solution

Keep track of components in callstack when registering required components.

## Testing

Added a test checking that the error fires.

---

## Showcase

```rust
#[derive(Component, Default)]
#[require(B)]
struct A;

#[derive(Component, Default)]
#[require(A)]
struct B;
World::new().spawn(A);
```

```
thread 'main' panicked at /home/vj/workspace/rust/bevy/crates/bevy_ecs/src/component.rs:415:13:
Recursive required components detected: A → B → A
```

### CODE REVIEW

**Comment by AlexAegis** [comment]
Why not just ignore the circle and just stop the recursion when encountering one already processed? Is there a reason why it must be treated as a hard error?

**Comment by AlexAegis** [comment]
I hadn't thought of that! Maybe it would be worth mentioning in the error message that "maybe you want to merge these two components into one?"

File: crates/bevy_ecs/macros/src/component.rs [hunk 1]
```diff
@@ -138,9 +142,14 @@ pub fn derive_component(input: TokenStream) -> TokenStream {
                 storages: &mut #bevy_ecs_path::storage::Storages,
                 required_components: &mut #bevy_ecs_path::component::RequiredComponents,
                 inheritance_depth: u16,
+                recursion_check_stack: &mut Vec<#bevy_ecs_path::component::ComponentId>
             ) {
+                #bevy_ecs_path::component::enforce_no_required_components_recursion(components, recursion_check_stack);
```
Comment (chescock) [inline crates/bevy_ecs/macros/src/component.rs:147]: I think doing this check before the `push` means you have one more level of recursion than is necessary.  

Like, if you register a component that requires itself, then the first time this is called the stack will be empty, and the second time it will have one element that it binds to `requiree` but an empty `check` list.  So it will pass on the second call, even though it had enough information to detect the error!  

The simplest thing to do might be to pass `self_id` to `enforce_no_required_components_recursion` so that it doesn't need to do `split_last()`.

File: crates/bevy_ecs/src/component.rs [hunk 2]
```diff
@@ -401,6 +403,41 @@ pub trait Component: Send + Sync + 'static {
...
+pub fn enforce_no_required_components_recursion(
+    components: &Components,
+    recursion_check_stack: &[ComponentId],
+) {
+    if let Some((&requiree, check)) = recursion_check_stack.split_last() {
+        if let Some(direct_recursion) = check
+            .iter()
+            .rev()
+            .enumerate()
+            .find_map(|(index, &id)| (id == requiree).then_some(index == 0))
```
Comment (chescock) [inline crates/bevy_ecs/src/component.rs:419]: Just a nit, but this could be a little shorter using `rposition`

```suggestion
            .rposition(|&id| id == requiree)
            .map(|index| index == 0)
```

File: crates/bevy_ecs/src/component.rs [hunk 3]
```diff
@@ -401,6 +403,41 @@ pub trait Component: Send + Sync + 'static {
...
+        {
+            panic!(
+                "Recursive required components detected: {}\nhelp: {}",
+                recursion_check_stack
+                    .iter()
+                    .map(|id| components.get_name(*id).unwrap())
```
Comment (chescock) [inline crates/bevy_ecs/src/component.rs:425]: Do you want to use `ShortName` here, as well?  

```suggestion
                    .map(|id| ShortName(components.get_name(*id).unwrap()))
```

File: crates/bevy_ecs/src/lib.rs [hunk 4]
```diff
@@ -2552,6 +2552,20 @@ mod tests {
         assert_eq!(to_vec(required_z), vec![(b, 0), (c, 1)]);
     }
 
+    #[test]
+    #[should_panic = "Recursive required components detected: bevy_ecs::tests::required_components_recursion_errors::A → bevy_ecs::tests::required_components_recursion_errors::B → bevy_ecs::tests::required_components_recursion_errors::A\nhelp: If this is intentional, consider merging the components."]
```
Comment (chescock) [inline crates/bevy_ecs/src/lib.rs:2556]: Oh, I bet this message will change now that you're using `ShortName`.

File: crates/bevy_ecs/src/component.rs [hunk 5]
```diff
@@ -401,6 +403,41 @@ pub trait Component: Send + Sync + 'static {
...
+// This exists as a standalone function instead of being inlined into the component derive macro so as
+// to reduce the amount of generated code.
+#[doc(hidden)]
+pub fn enforce_no_required_components_recursion(
+    components: &Components,
+    recursion_check_stack: &[ComponentId],
+) {
+    if let Some((&requiree, check)) = recursion_check_stack.split_last() {
+        if let Some(direct_recursion) = check
+            .iter()
```
[the remark this answers is not in the document]
Comment (chescock) [reply crates/bevy_ecs/src/component.rs:416]: Yeah, I think you're right that the chains will be small, so an extra check wouldn't be worth the complexity.

**Review by chescock — APPROVED** [review]

**Review by alice-i-cecile — APPROVED** [review]
Great comments :) It's good to improve the messages here.
