### PR TITLE
`MeasureFunc` improvements

### LINKED ISSUE #8516: Intrinsically sized UI nodes
## Bevy version

Main [ee697f8](https://github.com/bevyengine/bevy/commit/ee697f820c0b164cf2825b9c8e932fc8cee24a2c)

## What you did

```rust
use bevy::prelude::*;
use bevy::ui::AvailableSpace;
use bevy::ui::CalculatedSize;
use bevy::ui::Measure;

fn main() {
    App::new()
        .add_plugins(DefaultPlugins)
        .add_systems(Startup, setup)
        .run();
}

#[derive(Clone)]
pub struct TestMeasure;

impl Measure for TestMeasure {
    fn measure(
        &self,
        _: Option<f32>,
        _: Option<f32>,
        _: AvailableSpace,
        _: AvailableSpace,
    ) -> Vec2 {
        Vec2::new(500., 0.)
    }

    fn dyn_clone(&self) -> Box<dyn Measure> {
        Box::new(self.clone())
    }
}


fn setup(mut commands: Commands) {
    commands.spawn(Camera2dBundle::default());
        commands.spawn((NodeBundle {
            style: Style {
                max_size: Size::width(Val::Px(0.)),
                ..Default::default()
            },
            background_color: Color::GREEN.into(),
            ..default()
        },
        CalculatedSize { measure: Box::new(TestMeasure) }
    ));
    commands.spawn(NodeBundle {
        style: Style {
            size: Size::width(Val::Percent(100.)),
            ..Default::default()
        },
        background_color: Color::RED.into(),
        ..Default::default()
    });
}
```

## What went wrong

Capture-size

The green NodeBundle with the calculated size has a max-width constraint of 0., so it takes up no space in the layout as expected. But the red NodeBundle doesn't grow to fill 100% of the width of the window and leaves an empty space.

## Additional Information

Looked obviously like it must be a bug in Taffy, but couldn't reproduce it. Instead, it was definitely introduced by #7779 but I'm not sure how as #7779 doesn't modify any of the layout calculations except for changing how scale factor is applied, but this doesn't seem like a scale factor related bug.

### PR DESCRIPTION
**Pull request by ickshonpe**
# Objective

fixes #8516

* Give `CalculatedSize` a more specific and intuitive name.

* `MeasureFunc`s should only be updated when their `CalculatedSize` is modified by the systems managing their content.

  For example, suppose that you have a UI displaying an image using an `ImageNode`. When the window is resized, the node's  `MeasureFunc` will be updated even though the dimensions of the texture contained by the node are unchanged.

* Fix the `CalculatedSize` API so that it no longer requires the extra boxing and the `dyn_clone` method.

## Solution

* Rename `CalculatedSize` to `ContentSize`

* Only update `MeasureFunc`s on `CalculatedSize` changes.

* Remove the `dyn_clone` method from `Measure` and move the `Measure` from the `ContentSize` component rather than cloning it.

* Change the measure_func field of `ContentSize` to type `Option<taffy::node::MeasureFunc>`. Add a `set` method that wraps the given measure appropriately.

---

## Changelog

* Renamed `CalculatedSize` to `ContentSize`.
* Replaced `upsert_leaf` with a function `update_measure` that only updates the node's `MeasureFunc`.
* `MeasureFunc`s are only updated when the `ContentSize` changes and not when the layout changes.
* Scale factor is no longer applied to the size values passed to the `MeasureFunc`.
* Remove the `ContentSize` scaling in `text_system`.
* The `dyn_clone` method has been removed from the `Measure` trait.
* `Measure`s are moved from the `ContentSize` component instead of cloning them.
* Added `set` method to `ContentSize` that replaces the `new` function.

## Migration Guide

* `CalculatedSize` has been renamed to `ContentSize`.
* The `upsert_leaf` function has been removed from `UiSurface` and replaced with `update_measure` which updates the `MeasureFunc` without node insertion.
* The `dyn_clone` method has been removed from the `Measure` trait.
* The new function of `CalculatedSize` has been replaced with the method `set`.

### CODE REVIEW

**Comment by nicoburns** [comment]
@ickshonpe If Taffy is being passed scaled physical styles, then don't the measure_func's also need to be working in physical-sizes? Or are these values already scaled?

**Comment by ickshonpe** [comment]
> @ickshonpe If Taffy is being passed scaled physical styles, then don't the measure_func's also need to be working in physical-sizes? Or are these values already scaled?

They are already scaled.

**Review by nicoburns — APPROVED** [review]
This change looks good to me. The only thing that confused me was the name of `CalculatedSize`, because (at least in the case of text) it does not actually contain a calculated size, but a `MeasureFunc`. I wonder if it ought to be renamed to `MeasureFunction` or `IntrinsicSize` or `ContentSize` or something like that?

**Comment by ickshonpe** [comment]
Yeah, the name `CalculatedSize` doesn't make sense anymore. I was going to change it to `IntrinsicSize` in the text-system-split PR but decided it had enough breaking changes already.

`ContentSize` might be good, I think users would it find more intuitive than `InstrinsicSize` or `MeasureFunction` probably.

File: crates/bevy_ui/src/layout/mod.rs [hunk 1]
```diff
@@ -90,15 +90,12 @@ impl UiSurface {
...
+    pub fn update_measure(
         &mut self,
         entity: Entity,
-        style: &Style,
         calculated_size: &CalculatedSize,
-        context: &LayoutContext,
     ) {
-        let taffy = &mut self.taffy;
-        let taffy_style = convert::from_style(context, style);
+
```
Comment (mockersf) [inline crates/bevy_ui/src/layout/mod.rs:98]:
```suggestion
```

**Comment by mockersf** [comment]
there is a small style issue, a merge issue, and I would be for renaming. `ContentSize` sounds good 👍

**Review by mockersf — APPROVED** [review]

**Comment by ickshonpe** [comment]
very artificial benchmark:

`cargo run --profile stress-test --features trace_tracy --example many_buttons recompute-layout`

update_content_size

**Comment by ickshonpe** [comment]
Since a `MeasureFunc` doesn't ever need to reupdated by `ui_layout_system`, the `MeasureFunc` can just be moved from the `ContentSize` component instead of cloning and that annoying `dyn_clone` method can be got rid of.

**Comment by nicoburns** [comment]
> Since a `MeasureFunc` doesn't ever need to be reupdated by `ui_layout_system`, the `MeasureFunc` can just be moved from the `ContentSize` component instead of cloning and that annoying `dyn_clone` method can be got rid of as well.

How does that interact with change detection on the `ContentSize` component? Wouldn't moving out of the component change it?

**Comment by ickshonpe** [comment]
> > Since a `MeasureFunc` doesn't ever need to be reupdated by `ui_layout_system`, the `MeasureFunc` can just be moved from the `ContentSize` component instead of cloning and that annoying `dyn_clone` method can be got rid of as well.
> 
> How does that interact with change detection on the `ContentSize` component? Wouldn't moving out of the component change it?

`ContentSize` isn't queried for change detection anymore, `ui_layout_system` just takes the `Measure` out of an option. 

`bypass_change_detection` can always be used if it was needed for some reason.

**Comment by ickshonpe** [comment]
It might seem a bit odd to move the `MeasureFunc` through an option like this but I tried a lot of approaches and they all had issues. The `MeasureFunc` can't be added to `UiSurface` before its corresponding Taffy node has been created and it needs to be automatically deleted when either the UI node entity is despawned or its `ContentSize` component is removed.

**Comment by ickshonpe** [comment]
Also fixes #8516, not sure why. Might be some problem in `UiSurface` not setting the needs measure or dirty flags correctly.

**Comment by nicoburns** [comment]
@ickshonpe Would you now consider this PR ready for review? I've been waiting for you to stop committing to it to re-review.

**Comment by ickshonpe** [comment]
Yes this is ready to go.

**Review by nicoburns — APPROVED** [review]
This looks good to me. Also seems to work with a quick test locally.
