### PR TITLE
`QuerySingle` family of system params

### LINKED ISSUE #15391: Logging for system parameter validation should be configurable
## What problem does this solve or what need does it fill?

Following #15276, systems are now skipped when they cannot run due to missing data, rather than panicking and crashing their app.

While we should 100% warn by default when this happens, some of those logs will be spurious. This behavior might be expected, and users should be able to turn them off.

## What solution would you like?

Allow users to disable this logging by disabling it at the system config level, which should work on both systems and system sets.

It would be nice to be able to change the log level to any of the standard levels: none, debug, info, warn, error, panic, but warn, and ignore are the most important.

## What alternative(s) have you considered?

We could also expose a way to turn off these warnings globally, but this is likely to be a footgun: your systems silently not running is very bad!

We could also add resource / component-level log disabling, but that's more complex. My preferred solution there now is to add opt-in support for reads/writes system sets (based on https://github.com/bevyengine/bevy/pull/5388), and then use the mechanism above to configure them. 

## Additional context

Previously discussed in https://github.com/bevyengine/bevy/issues/15265.

### PR DESCRIPTION
**Pull request by MiniaczQ**
# Objective

Add the following system params:
- `QuerySingle<D, F>` - Valid if only one matching entity exists,
- `Option<QuerySingle<D, F>>` - Valid if zero or one matching entity exists.

As @chescock pointed out, we don't need `Mut` variants.

Fixes: #15264

## Solution

Implement the type and both variants of system params.
Also implement `ReadOnlySystemParam` for readonly queries.

Added a new ECS example `fallible_params` which showcases `SingleQuery` usage.
In the future we might want to add `NonEmptyQuery`, `NonEmptyEventReader` and `Res` to it (or maybe just stop at mentioning it).

## Testing

Tested with the example.
There is a lot of warning spam so we might want to implement #15391.

### CODE REVIEW

**Comment by MiniaczQ** [comment]
Not super happy with unpacking ergonomics
```rs
let (ref mut player_transform, ref player) = &mut *player;
```
I wonder if that can be improved

File: examples/ecs/falliable_params.rs [hunk 1]
```diff
@@ -0,0 +1,130 @@
+//! This example demonstrates how falliable parameters can prevent systems from running
```
Comment (alice-i-cecile) [inline examples/ecs/falliable_params.rs:1]: `fallible`, not `falliable` in English :)

File: crates/bevy_ecs/src/system/system_param.rs [hunk 2]
```diff
@@ -356,6 +356,244 @@ fn assert_component_access_compatibility(
...
+        state: &'s mut Self::State,
+        system_meta: &SystemMeta,
+        world: UnsafeWorldCell<'w>,
+        change_tick: Tick,
+    ) -> Self::Item<'w, 's> {
+        state.validate_world(world.id());
+        // SAFETY: State ensures that the components it accesses are not mutably accessible elsewhere
+        // and the query is read only.
+        let result = unsafe {
+            state.as_readonly().get_single_unchecked_manual(
```
[the remark this answers is not in the document]
Comment (MiniaczQ) [reply crates/bevy_ecs/src/system/system_param.rs:390]: that does make sense yeah, i focused too much on resources

File: crates/bevy_ecs/src/system/query.rs [hunk 3]
```diff
@@ -1629,3 +1633,51 @@ impl<'w, 'q, Q: QueryData, F: QueryFilter> From<&'q mut Query<'w, '_, Q, F>>
...
+
+/// [System parameter] that provides readonly access to single entity's components, much like [`Query::single`].
+///
+/// This [`SystemParam`](crate::system::SystemParam) fails validation if zero or more than one matching entity exists.
+/// This will cause systems that use it to be skipped.
+///
+/// Use [`Option<QuerySingle<D, F>>`] instead if zero or one matching entities can exist.
+///
+/// See [`Query`] for meaning behind the generic arguments.
+pub struct QuerySingle<'w, D: ReadOnlyQueryData, F: QueryFilter = ()> {
```
[the remark this answers is not in the document]
Comment (MiniaczQ) [reply crates/bevy_ecs/src/system/query.rs:1645]: Sure, I don't think there are many uses cases, but it'd be there for completeness

**Review by chescock — APPROVED** [review]

File: crates/bevy_ecs/src/system/system_param.rs [hunk 4]
```diff
@@ -356,6 +356,139 @@ fn assert_component_access_compatibility(
...
+        state: &'s mut Self::State,
+        system_meta: &SystemMeta,
+        world: UnsafeWorldCell<'w>,
+        change_tick: Tick,
+    ) -> Self::Item<'w, 's> {
+        state.validate_world(world.id());
+        // SAFETY: State ensures that the components it accesses are not accessible somewhere elsewhere.
+        let result =
+            unsafe { state.get_single_unchecked_manual(world, system_meta.last_run, change_tick) };
+        let single = result.unwrap();
```
Comment (ItsDoot) [inline crates/bevy_ecs/src/system/system_param.rs:391]: Could this be `.debug_checked_unwrap()`?

File: crates/bevy_ecs/src/system/system_param.rs [hunk 5]
```diff
@@ -356,6 +356,139 @@ fn assert_component_access_compatibility(
...
+        state: &'s mut Self::State,
+        system_meta: &SystemMeta,
+        world: UnsafeWorldCell<'w>,
+        change_tick: Tick,
+    ) -> Self::Item<'w, 's> {
+        state.validate_world(world.id());
+        // SAFETY: State ensures that the components it accesses are not accessible somewhere elsewhere.
+        let result =
+            unsafe { state.get_single_unchecked_manual(world, system_meta.last_run, change_tick) };
+        let single = result.debug_checked_unwrap();
```
Comment (ItsDoot) [inline crates/bevy_ecs/src/system/system_param.rs:391]: Hm, actually I'm not sure this can be `debug_checked_unwrap` because `validate_param` isn't required to be called before calling `get_param`.

Comment (MiniaczQ) [reply crates/bevy_ecs/src/system/system_param.rs:391]: Yeah, we should stay with `unwrap` unless we decide to make a contract between `validate_param` and `get_param` in the future

Comment (ItsDoot) [reply crates/bevy_ecs/src/system/system_param.rs]: Is there a point where the normal `unwrap` can panic?

Comment (MiniaczQ) [reply crates/bevy_ecs/src/system/system_param.rs]: Umm yeah, currently observers don't respect `validate_param` (#15394)

**Review by ItsDoot — APPROVED** [review]

File: crates/bevy_ecs/src/system/system_param.rs (hunk 4 above)
Comment (SkiFire13) [inline crates/bevy_ecs/src/system/system_param.rs:391]: This should panic with a better error message.

It should not use `.debug_checked_unwrap()` as the other comment suggested, because `get_param` can still be called when `validate_param` would return `false`, so it can happen that `result` is an `Err`.

File: crates/bevy_ecs/src/system/system_param.rs [hunk 6]
```diff
@@ -356,6 +356,139 @@ fn assert_component_access_compatibility(
...
+            )
+        };
+        result.is_ok()
+    }
+}
+
+// SAFETY: Relevant query ComponentId and ArchetypeComponentId access is applied to SystemMeta. If
+// this Query conflicts with any prior access, a panic will occur.
+unsafe impl<'a, D: QueryData + 'static, F: QueryFilter + 'static> SystemParam
+    for Option<QuerySingle<'a, D, F>>
```
Comment (SkiFire13) [inline crates/bevy_ecs/src/system/system_param.rs:421]: I wonder if now that we have `validate_param` we could use it to write a generic `impl<S: SystemParam> SystemParam for Option<S>`. This could be tackled in a separate PR though.

File: crates/bevy_ecs/src/system/system_param.rs [hunk 7]
```diff
@@ -356,6 +356,139 @@ fn assert_component_access_compatibility(
...
+        world: UnsafeWorldCell,
+    ) -> bool {
+        state.validate_world(world.id());
+        // SAFETY: State ensures that the components it accesses are not mutably accessible elsewhere
+        // and the query is read only.
+        let result = unsafe {
+            state.as_readonly().get_single_unchecked_manual(
+                world,
+                system_meta.last_run,
+                world.change_tick(),
```
Comment (SkiFire13) [inline crates/bevy_ecs/src/system/system_param.rs:411]: Are we sure this is the change tick that will be used for calling `get_param`, or an equivalent one for what matters to it? If so could you write a comment explaining why that's the case?

File: crates/bevy_ecs/src/system/system_param.rs (hunk 6 above)
Comment (MiniaczQ) [reply crates/bevy_ecs/src/system/system_param.rs:421]: Not evert `Option<P>` makes sense, like `Option<Query>`

File: crates/bevy_ecs/src/system/system_param.rs (hunk 7 above)
Comment (MiniaczQ) [reply crates/bevy_ecs/src/system/system_param.rs:411]: Practically yes, executors work that way, but this is not a strict contract.
I think I can provide the exact `change_tick` that will be used for `run`, but I'll do that in another PR, is that fine?

File: crates/bevy_ecs/src/system/system_param.rs (hunk 4 above)
Comment (MiniaczQ) [reply crates/bevy_ecs/src/system/system_param.rs:391]: I'll add an expect with a better message then

File: crates/bevy_ecs/src/system/system_param.rs (hunk 7 above)
Comment (MiniaczQ) [reply crates/bevy_ecs/src/system/system_param.rs:411]: Practically yes, this happens to be the exact tick that is received by `get_param`, but there are not validation mechanisms/contract for that.

Currently only executors use `validate_param` and since the validation and running happens one after another, this is the correct change tick.
For `run_systems` and observers this also shouldn't be a problem.

While I can make `validate_param` accept a `change_tick`, the problem is that the tick used by `get_param` is generated inside `run_unsafe`, so we'd still need to uphold this "contract" of calling them back-to-back.

Comment (MiniaczQ) [reply crates/bevy_ecs/src/system/system_param.rs:411]: I'm open for docs/mechanisms on making this better, I'm not sure how to go about it

Comment (chescock) [reply crates/bevy_ecs/src/system/system_param.rs:411]: It won't always be exactly the same tick, because the multi-threaded executor will call `validate_param` and then spawn a task to run the system and call `get_param` at some later point.  Another system could start in between and increment the current tick.  

I think it will be equivalent, though.  Any components read by this param can't be written by another system in between the calls, so they can't have an `added` or `changed` tick in between the two `change_tick` values.

Comment (MiniaczQ) [reply crates/bevy_ecs/src/system/system_param.rs:411]: Okay, I'll try to thoroughly document this in `validate_param`

File: crates/bevy_ecs/src/system/system_param.rs (hunk 6 above)
Comment (MiniaczQ) [reply crates/bevy_ecs/src/system/system_param.rs:421]: Also, infinitely nested `Option`s

Comment (SkiFire13) [reply crates/bevy_ecs/src/system/system_param.rs:431]: Right, though maybe this could be solved with a marker trait for those system parameters for which `Option` can make sense.

Comment (MiniaczQ) [reply crates/bevy_ecs/src/system/system_param.rs:431]: If there is a decent way to derive it I'm down.
There are some cases where `Option` needs some specialized code, like in `QuerySingle`

File: crates/bevy_ecs/src/system/system_param.rs [hunk 8]
```diff
@@ -356,6 +365,140 @@ fn assert_component_access_compatibility(
     panic!("error[B0001]: Query<{query_type}, {filter_type}> in system {system_name} accesses component(s){accesses} in a way that conflicts with a previous system parameter. Consider using `Without<T>` to create disjoint Queries or merging conflicting Queries into a `ParamSet`. See: https://bevyengine.org/learn/errors/b0001");
 }
 
+// SAFETY: Relevant query ComponentId and ArchetypeComponentId access is applied to SystemMeta. If
+// this Query conflicts with any prior access, a panic will occur.
+unsafe impl<'a, D: QueryData + 'static, F: QueryFilter + 'static> SystemParam
+    for QuerySingle<'a, D, F>
+{
+    type State = QueryState<D, F>;
+    type Item<'w, 's> = QuerySingle<'w, D, F>;
```
Comment (alice-i-cecile) [inline crates/bevy_ecs/src/system/system_param.rs:374]: Why isn't this just `<D as QueryData>::Item`? I think that would improve the ergonomics and complexity quite a bit?

Comment (MiniaczQ) [reply crates/bevy_ecs/src/system/system_param.rs:374]: The ergonomics comment got removed, CI told me to remove unnecessary syntax which made it way better.

`<D as WorldQuery>::Item` is not a `SystemParam` so that's one issue with this.
Another would be, if `SystemParam` returns anything else than itself with changed lifetimes, it won't fit as the system argument.
```rs
fn my_system(q: QuerySingle<Entity>) { ... }

// imaginary executor code
let q: <Entity as WorldQuery>::Item = QuerySingle<Entity>::get_param(world);
system(q); // Expected `QuerySingle` got `<Entity as WorldQuery>::Item`
```

**Review by alice-i-cecile — APPROVED** [review]

**Comment by alice-i-cecile** [comment]
Thank you to everyone involved with the authoring or reviewing of this PR! This work is relatively important and needs release notes! Head over to https://github.com/bevyengine/bevy-website/issues/1701 if you'd like to help out.
