### PR TITLE
System param validation for observers, system registry and run once

### LINKED ISSUE #15394: Respect `SystemParam::validate_param` for observers and other non-executor system runners
## What problem does this solve or what need does it fill?

Currently only schedule executors respect the `SystemParam::validate_param` to prevent panics when running systems with unavailable resources.
As a follow up to #15276 this should be implemented for other places that run systems like:
- observers,
- manually executed systems through `&mut World`

## What solution would you like?

Check `validate_param` directly before running the systems and if it fails, don't run them.

### PR DESCRIPTION
**Pull request by MiniaczQ**
# Objective

Fixes #15394

## Solution

Observers now validate params.

System registry has a new error variant for when system running fails due to invalid parameters.

Run once now returns a `Result<Out, RunOnceError>` instead of `Out`.
This is more inline with system registry, which also returns a result.

I'll address warning messages in #15500.

## Testing

Added one test for each case.

---

## Migration Guide

- `RunSystemOnce::run_system_once` and `RunSystemOnce::run_system_once_with` now return a `Result<Out>` instead of just `Out`

### CODE REVIEW

File: crates/bevy_ecs/src/system/builder.rs [hunk 1]
```diff
@@ -386,7 +386,7 @@ mod tests {
             .build_state(&mut world)
             .build_system(local_system);
 
-        let result = world.run_system_once(system);
+        let result = world.run_system_once(system).unwrap();
```
Comment (alice-i-cecile) [inline crates/bevy_ecs/src/system/builder.rs:389]: Nit: these tests will be clearer if we rename `result` to `output` or something. It's a bit confusing to call the output of unwrapping a `Result` `result` 😜

File: crates/bevy_ecs/src/system/system.rs [hunk 2]
```diff
@@ -340,14 +341,34 @@ impl RunSystemOnce for &mut World {
...
+            Err(RunSystemError::InvalidParams(system.name()))
+        }
+    }
+}
+
+/// Running system failed.
+#[derive(Error)]
+pub enum RunSystemError {
+    /// System could not run due to invalid parameters.
+    #[error("System {0:?} has invalid parameters")]
```
Comment (alice-i-cecile) [inline crates/bevy_ecs/src/system/system.rs:363]:
```suggestion
    #[error("The data required by the system {0:?} was not found in the world.")]
```

File: crates/bevy_ecs/src/system/builder.rs (hunk 1 above)
Comment (MiniaczQ) [reply crates/bevy_ecs/src/system/builder.rs:389]: Ah, didn't consider that, just mindlessly unwrapped, good catch

File: crates/bevy_ecs/src/system/system.rs [hunk 3]
```diff
@@ -340,14 +341,34 @@ impl RunSystemOnce for &mut World {
...
+        } else {
+            Err(RunSystemError::InvalidParams(system.name()))
+        }
+    }
+}
+
+/// Running system failed.
+#[derive(Error)]
+pub enum RunSystemError {
+    /// System could not run due to invalid parameters.
```
Comment (alice-i-cecile) [inline crates/bevy_ecs/src/system/system.rs:362]:
```suggestion
    /// System could not be run due to parameters that failed validation.
    ///
    /// This can occur because the data required by the system was not present in the world.
```

File: crates/bevy_ecs/src/system/system_registry.rs [hunk 4]
```diff
@@ -595,6 +599,9 @@ pub enum RegisteredSystemError<I: SystemInput = (), O = ()> {
     /// A system tried to remove itself.
     #[error("System {0:?} tried to remove itself")]
     SelfRemove(SystemId<I, O>),
+    /// System could not run due to invalid parameters.
```
Comment (alice-i-cecile) [inline crates/bevy_ecs/src/system/system_registry.rs:602]: Same suggestions on the doc comments and error message here.

**Review by alice-i-cecile — COMMENTED** [review]
Simple and effective; I'm pleased that adapting these to the new system param validation framework was so easy.

I have some feedback on docs / error messages that I'd like to resolve before we merge if possible.

**Review by alice-i-cecile — APPROVED** [review]

File: crates/bevy_ecs/src/observer/mod.rs [hunk 5]
```diff
@@ -1190,4 +1190,24 @@ mod tests {
...
+        #[derive(Resource)]
+        struct ResA;
+
+        #[derive(Resource)]
+        struct ResB;
+
+        let mut world = World::new();
+        world.observe(|_: Trigger<EventA>, _: Res<ResA>, mut commands: Commands| {
+            commands.insert_resource(ResB);
+        });
```
Comment (bushrat011899) [inline crates/bevy_ecs/src/observer/mod.rs:1208]:
```suggestion
        // This fails because `ResA` is not present in the world
        world.observe(|_: Trigger<EventA>, _: Res<ResA>, mut commands: Commands| {
            commands.insert_resource(ResB);
        });
```

File: crates/bevy_ecs/src/system/system.rs [hunk 6]
```diff
@@ -415,7 +438,19 @@ mod tests {
...
     }
+
+    #[test]
+    fn run_system_once_invalid_params() {
+        struct T;
+        impl Resource for T {}
+        fn system(_: Res<T>) {}
+
+        let mut world = World::default();
+        let result = world.run_system_once(system);
```
Comment (bushrat011899) [inline crates/bevy_ecs/src/system/system.rs:452]:
```suggestion
        // This fails because `T` has not been added to the world yet.
        let result = world.run_system_once(system);
```

File: crates/bevy_ecs/src/system/system_registry.rs [hunk 7]
```diff
@@ -913,4 +923,22 @@ mod tests {
...
+    fn run_system_invalid_params() {
+        use crate::system::RegisteredSystemError;
+
+        struct T;
+        impl Resource for T {}
+        fn system(_: Res<T>) {}
+
+        let mut world = World::new();
+        let id = world.register_system_cached(system);
+        let result = world.run_system(id);
```
Comment (bushrat011899) [inline crates/bevy_ecs/src/system/system_registry.rs:937]:
```suggestion
        // This fails because `T` has not been added to the world yet.
        let result = world.run_system(id);
```

**Review by bushrat011899 — APPROVED** [review]
Nice change! I've suggested a handful of comments to help with understanding _why_ the new tests should fail (resource not available in the world). On first glance I missed that was the cause of the failure and was quite confused!
