### PR TITLE
Fix observers' access to relationship data during `despawn_related`

### LINKED ISSUE #20106: `despawn_related` removes relationship before calling observers and hooks
## Bevy version

0.16.1 release

## What you did

In my application I have a tree structure, built with relationships. When nodes in the tree get dropped, I need to do some cleanup, involving moving up the tree.

## What went wrong

The problem is, when running the `OnReplace` observer, the `Relationship` component is already gone.

## Reproduction example

```rust
App::new()
    .add_systems(Startup, test)
    .add_observer(on_my_component_replace)
    .run();

#[derive(Component)]
struct MyComponent;

fn test(mut commands: Commands) {
    let root = commands.spawn(children![MyComponent]).id();

    commands.entity(root).despawn_related::<Children>();
}

fn on_my_component_replace(
    trigger: Trigger<OnReplace, MyComponent>,
    has_relationship: Query<Has<ChildOf>>,
) {
    assert!(
        has_relationship.get(trigger.target()).unwrap(),
        "Entity should have a ChildOf relationship"
    );
}
```

## Additional information

The problem is that `despawn_related` calls `EntityWorldMut::take<S>` to get the `RelationshipTarget` component, which removes the component. This triggers the component hooks on the `RelationshipTarget`, which then remove the relationship from all children. Only after all that, the children are actually despawned and the observers and hooks associated to their components are called.

https://github.com/bevyengine/bevy/blob/f1eace62f04940224ee8f6a4a98cb57b1d3c8226/crates/bevy_ecs/src/relationship/related_methods.rs#L299-L312

The simplest solution is to replace `take` with `get` and copying all children into a temporary vector:

```rust
if let Some(sources) = self.get::<S>() {
    let sources = sources.iter().collect::<Vec<_>>();
    self.world_scope(|world| {
        for entity in sources {
            if let Ok(entity_mut) = world.get_entity_mut(entity) {
                entity_mut.despawn();
            };
        }
    });
}
```

### PR DESCRIPTION
**Pull request by muddxyii**
# Objective

- Fix issue where observers cannot access relationship data during `despawn_related`
- Fixes #20106

## Solution

- Changed `despawn_related` to use `get()` instead of `take()` to preserve relationship components during the despawn process
- Collect entities into a vector before despawning to ensure the relationship data remains accessible to observers and hooks

## Testing

- Added test `despawn_related_observers_can_access_relationship_data` that reproduces the issue scenario

### CODE REVIEW

File: crates/bevy_ecs/src/relationship/related_methods.rs [hunk 1]
```diff
@@ -299,12 +299,13 @@ impl<'w> EntityWorldMut<'w> {
     /// Despawns entities that relate to this one via the given [`RelationshipTarget`].
     /// This entity will not be despawned.
     pub fn despawn_related<S: RelationshipTarget>(&mut self) -> &mut Self {
-        if let Some(sources) = self.take::<S>() {
+        if let Some(sources) = self.get::<S>() {
+            let sources = sources.iter().collect::<Vec<_>>();
```
Comment (alice-i-cecile) [inline crates/bevy_ecs/src/relationship/related_methods.rs:305]:
```suggestion
            // We have to collect here to defer removal, allowing observers and hooks to see this data
            // before it is finally removed.
            let sources = sources.iter().collect::<Vec<_>>();
```

**Review by Trashtalk217 — APPROVED** [review]
