### PR TITLE
Make bevy_math's `libm` feature use `libm` for all `f32`methods with unspecified precision

### LINKED ISSUE #14474: bevy_math's `libm` feature should probably apply to bevy_math's internal code
## What's wrong?

Right now, the `libm` feature flag of bevy_math basically just serves to pass through the same flag to glam. It should probably cause bevy_math itself to use the libm versions of functions as well. 

## What should be done?

We should follow in glam's footsteps here and have a `math` module (or whatever) inside bevy_math which is compiled to either the platform defaults (e.g. `f32::sqrt`) or the libm versions (`libm::sqrtf`) depending on the feature flag. Then our internals would be refactored to use (for example) `math::sqrt` instead of `f32::sqrt` directly. 

This is a fairly substantial undertaking, even if it is basically a trivial matter of finding things and replacing them.

Another concern that I have about this is that it's unlikely that literally all relevant math in bevy is actually self-contained in the bevy_math module (e.g. bevy_transform and bevy_color also do some math), so it seems like this is bound to be "leaky" regardless. On the other hand, this could be useful for library authors depending on bevy_math to get access to additional determinacy guarantees. See #11238 for context.

### PR DESCRIPTION
**Pull request by mweatherley**
# Objective

Closes #14474

Previously, the `libm` feature of bevy_math would just pass the same feature flag down to glam. However, bevy_math itself had many uses of floating-point arithmetic with unspecified precision. For example, `f32::sin_cos` and `f32::powi` have unspecified precision, which means that the exact details of their output are not guaranteed to be stable across different systems and/or versions of Rust. This means that users of bevy_math could observe slightly different behavior on different systems if these methods were used. 

The goal of this PR is to make it so that the `libm` feature flag actually guarantees some degree of determinacy within bevy_math itself by switching to the libm versions of these functions when the `libm` feature is enabled.

## Solution

bevy_math now has an internal module `bevy_math::ops`, which re-exports either the standard versions of the operations or the libm versions depending on whether the `libm` feature is enabled. For example, `ops::sin` compiles to `f32::sin` without the `libm` feature and to `libm::sinf` with it.

This approach has a small shortfall, which is that `f32::powi` (integer powers of floating point numbers) does not have an equivalent in `libm`. On the other hand, this method is only used for squaring and cubing numbers in bevy_math. Accordingly, this deficit is covered by the introduction of a trait `ops::FloatPow`:
```rust
pub(crate) trait FloatPow {
    fn squared(self) -> Self;
    fn cubed(self) -> Self;
}
```

Next, each current usage of the unspecified-precision methods has been replaced by its equivalent in `ops`, so that when `libm` is enabled, the libm version is used instead. The exception, of course, is that `.powi(2)`/`.powi(3)` have been replaced with `.squared()`/`.cubed()`.

Finally, the usage of the plain `f32` methods with unspecified precision is now linted out of bevy_math (and hence disallowed in CI). For example, using `f32::sin` within bevy_math produces a warning that tells the user to use the `ops::sin` version instead. 

## Testing

Ran existing tests. It would be nice to check some benchmarks on NURBS things once #14677 merges. I'm happy to wait until then if the rest of this PR is fine.

---

## Discussion

In the future, it might make sense to actually expose `bevy_math::ops` as public if any downstream Bevy crates want to provide similar determinacy guarantees. For now, it's all just `pub(crate)`. 

This PR also only covers `f32`. If we find ourselves using `f64` internally in parts of bevy_math for better robustness, we could extend the module and lints to cover the `f64` versions easily enough.

I don't know how feasible it is, but it would also be nice if we could standardize the bevy_math tests with the `libm` feature in CI, since their success is currently platform-dependent (e.g. 8 of them fail on my machine when run locally).

### CODE REVIEW

**Comment by mweatherley** [comment]
Marking this as contentious because of increased maintenance burden and potential confusion for new contributors, but I think that doing something like this is a good idea if we actually want to support the `libm` feature.

File: crates/bevy_math/src/bounding/bounded3d/primitive_impls.rs [hunk 1]
```diff
@@ -461,7 +462,10 @@ mod tests {
 
         let bounding_sphere = polyline.bounding_sphere(isometry);
         assert_eq!(bounding_sphere.center, translation.into());
-        assert_eq!(bounding_sphere.radius(), 1.0_f32.hypot(1.0).hypot(1.0));
+        assert_eq!(
+            bounding_sphere.radius(),
+            ops::hypot(ops::hypot(1.0, 1.0), 1.0)
```
Comment (IQuick143) [inline crates/bevy_math/src/bounding/bounded3d/primitive_impls.rs:467]: These chained hypots are pretty cursed, but I guess it's fine inside a test.

File: crates/bevy_math/src/common_traits.rs [hunk 2]
```diff
@@ -256,7 +256,7 @@ pub trait StableInterpolate: Clone {
     /// object_position.smooth_nudge(&target_position, decay_rate, delta_time);
     /// ```
     fn smooth_nudge(&mut self, target: &Self, decay_rate: f32, delta: f32) {
-        self.interpolate_stable_assign(target, 1.0 - f32::exp(-decay_rate * delta));
+        self.interpolate_stable_assign(target, 1.0 - ops::exp(decay_rate * delta));
```
Comment (IQuick143) [inline crates/bevy_math/src/common_traits.rs:259]: The minus sign from the exponent disappeared.
```suggestion
        self.interpolate_stable_assign(target, 1.0 - ops::exp(-decay_rate * delta));
```

Comment (mweatherley) [reply crates/bevy_math/src/common_traits.rs:259]: Good catch! That's embarrassing, hahaha.

File: crates/bevy_math/src/ops.rs [hunk 3]
```diff
@@ -0,0 +1,291 @@
...
+//
+// Additionally, the following nightly API functions are not presently integrated
+// into this, but they would be candidates once standardized:
+// - `f32::gamma`
+// - `f32::ln_gamma`
+
+#[cfg(not(feature = "libm"))]
+mod std_ops {
+    #[inline(always)]
+    pub(crate) fn powf(x: f32, y: f32) -> f32 {
```
Comment (IQuick143) [inline crates/bevy_math/src/ops.rs:26]: Just me wondering:
Could this be done with something like:
```
mod std_ops {
    pub use f32::powf; ///etc...
}
```
or would that not work??

File: crates/bevy_math/src/bounding/bounded3d/primitive_impls.rs (hunk 1 above)
Comment (mweatherley) [reply crates/bevy_math/src/bounding/bounded3d/primitive_impls.rs:467]: Yeah, I had the same thought...

File: crates/bevy_math/src/ops.rs (hunk 3 above)
Comment (mweatherley) [reply crates/bevy_math/src/ops.rs:26]: I'm not sure, but it also fails to unify the naming of the std and libm versions, which differ in many (most?) cases.

File: crates/bevy_math/src/primitives/dim2.rs [hunk 4]
```diff
@@ -1031,7 +1034,7 @@ impl Rhombus {
     #[inline(always)]
     pub fn from_side(side: f32) -> Self {
         Self {
-            half_diagonals: Vec2::splat(side.hypot(side) / 2.0),
+            half_diagonals: Vec2::splat(ops::hypot(side, side) / 2.0),
```
Comment (IQuick143) [inline crates/bevy_math/src/primitives/dim2.rs:1037]: Not sure when I missed this, but this simplifies down to:
```
hypot(side, side) / 2.0 -> side * 1/sqrt(2)
```
Not the fault of this PR tho.

Comment (mweatherley) [reply crates/bevy_math/src/primitives/dim2.rs:1037]: You're still missing a `sqrt` on `side` I think, but otherwise yeah

File: crates/bevy_math/src/sampling/shape_sampling.rs [hunk 5]
```diff
@@ -624,7 +627,7 @@ mod tests {
         for _ in 0..5000 {
             let point = circle.sample_boundary(&mut rng);
 
-            let angle = f32::atan(point.y / point.x) + PI / 2.0;
+            let angle = ops::atan(point.y / point.x) + PI / 2.0;
```
Comment (IQuick143) [inline crates/bevy_math/src/sampling/shape_sampling.rs:630]: Seems like a prime candidate for `atan2`.

**Review by IQuick143 — APPROVED** [review]

File: crates/bevy_math/src/ops.rs (hunk 3 above)
Comment (Jondolf) [reply crates/bevy_math/src/ops.rs:26]: You can do `pub use libm::sqrtf as sqrt` and so on

File: crates/bevy_math/src/primitives/dim2.rs (hunk 4 above)
Comment (IQuick143) [reply crates/bevy_math/src/primitives/dim2.rs:1037]: Nope, hypot first squares and then square roots.
hypot(x,x) -> sqrt(x^2 + x^2) -> sqrt(2x^2) -> sqrt(2) * sqrt(x^2) -> sqrt(2) * abs(x)
So I suppose there is a difference for negative values, however a negative side length is a nonsensical input anyway.

File: crates/bevy_math/src/ops.rs (hunk 3 above)
Comment (IQuick143) [reply crates/bevy_math/src/ops.rs:26]: You could do `pub use libm::thingf as thing`, I think.

Comment (mweatherley) [reply crates/bevy_math/src/ops.rs:26]: True! Do you know if that would dodge the lints? I just organized them this way because it's how glam does it.

File: crates/bevy_math/src/primitives/dim2.rs (hunk 4 above)
Comment (mweatherley) [reply crates/bevy_math/src/primitives/dim2.rs:1037]: I somehow forgot about the inner squares in `hypot`; you're right. Hahaha

File: crates/bevy_math/src/ops.rs [hunk 6]
```diff
@@ -0,0 +1,291 @@
...
+pub(crate) use libm_ops::*;
+#[cfg(not(feature = "libm"))]
+pub(crate) use std_ops::*;
+
+/// This extension trait covers shortfall in determinacy from the lack of a `libm` counterpart
+/// to `f32::powi`. Use this for the common small exponents.
+pub(crate) trait FloatPow {
+    fn squared(self) -> Self;
+    fn cubed(self) -> Self;
+}
```
Comment (Jondolf) [inline crates/bevy_math/src/ops.rs:280]: Would it make sense to make these public? It would be useful at least for me in Avian and some other libs.

File: crates/bevy_math/src/ops.rs (hunk 3 above)
Comment (Jondolf) [reply crates/bevy_math/src/ops.rs:26]: Hmm, not sure. If it breaks the lints, then it's not worth it and should be kept how it is now

**Review by Jondolf — APPROVED** [review]
Looks good! I think it's very important to ensure that the core math library can be made fully cross-platform deterministic, and I like the lints to enforce this.

Things to consider for follow-ups:

- I would really like these ops to be public. I have similar needs for my physics engine, collision detection stuff, and some other libraries, and it would be great if I didn't have to duplicate everything.
- f64 versions would be valuable.
- We could consider extending this to some other Bevy crates that may have an impact on determinism. Not sure if there's a need yet though...

File: crates/bevy_math/src/sampling/shape_sampling.rs (hunk 5 above)
Comment (mweatherley) [reply crates/bevy_math/src/sampling/shape_sampling.rs:630]: I agree, but it's currently written with the angle lying in the range [0, PI] in mind, so changing it to `atan2` basically requires rewriting it, which I'd rather not do right now.

File: crates/bevy_math/src/ops.rs (hunk 3 above)
Comment (mweatherley) [reply crates/bevy_math/src/ops.rs:26]: Hmm; I tried it and it literally just doesn't work, but maybe I'm just being silly. i.e., `pub use f32::powf;` in a module literally just doesn't compile. I dunno how much this is worth fussing over anyway; if these later become public then the whole module thing will probably have to be reorganized regardless.
