### PR TITLE
Fix point light shadow glitches

### LINKED ISSUE #18945: Regression: PointLight shadows glitch out in 0.16
## Bevy version

Bevy "0.16" via cargo

## \[Optional\] Relevant system information

cargo 1.86

SystemInfo { os: "Windows 11 Home", kernel: "26100", cpu: "AMD Ryzen 9 7950X 16-Core Processor", core_count: "16", memory: "63.2 GiB" }    
AdapterInfo { name: "NVIDIA GeForce RTX 4070 SUPER", vendor: 4318, device: 10115, device_type: DiscreteGpu, driver: "NVIDIA", driver_info: "572.70", backend: Vulkan }
GPU preprocessing is fully supported on this device.

## What you did

Point Light shadows completely wrong after looking away.  Only initially occurs when camera is outside of the lights `range` and pointed away, but is not fixed by re-entering the `range`.

## What went wrong

expected: shadows like normal, same as 0.15.3 or if I don't get too far and/or don't look away from the light
what happened: shadows are wrong - see video

## Additional information

changing bevy to "0.15.3" results in not seeing the issue.

Initial Problem:

https://github.com/user-attachments/assets/e3470439-45ce-4197-ad16-ee4d73cfd785

I made a minimal repro (less visually crazy, but the cubes shadows will disappear and reappear when looking away and back (only if far enough away, a bit past the edge of the disk or so)

Cargo.toml
```
[package]
name = "glitch"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.16"
```

src/main.rs
```
use bevy::prelude::*;

fn main() {
    App::new()
        .add_plugins(DefaultPlugins)
        .insert_resource(ClearColor(Color::BLACK))
        .add_systems(Startup, startup)
        .add_systems(Update, update)
        .run();
}

fn startup(
    mut commands: Commands,
    mut meshes: ResMut<Assets<Mesh>>,
    mut materials: ResMut<Assets<StandardMaterial>>,
) {
    commands.spawn((Camera3d::default(), Transform::from_xyz(0.0, 5.0, 8.0)));
    commands.spawn((
        Transform::from_xyz(0.0, 0.0, 0.0),
        Mesh3d(meshes.add(Cylinder::new(20.0, 0.5))),
        MeshMaterial3d(materials.add(Color::WHITE)),
    ));
    for i in 0..10 {
        commands.spawn((
            Mesh3d(meshes.add(Cuboid::from_length(1.0))),
            MeshMaterial3d(materials.add(Color::srgb(0.2, 0.3, 0.8))),
            Transform::from_xyz(0.0, 2.5 + (i as f32 * 2.0), -2.0 - (i as f32 * 0.5)),
        ));
    }
    commands.spawn((
        PointLight {
            shadows_enabled: true,
            ..Default::default()
        },
        Transform::from_xyz(0.0, 8.0, 0.0),
    ));
}

fn update(
    time: Res<Time>,
    camera: Single<&mut Transform, With<Camera3d>>,
    keyboard_input: Res<ButtonInput<KeyCode>>,
) {
    let delta_time = time.delta_secs();
    let mut camera_transform = camera.into_inner();

    if keyboard_input.pressed(KeyCode::KeyQ) {
        camera_transform.rotate_y(3.0 * delta_time);
    }
    if keyboard_input.pressed(KeyCode::KeyE) {
        camera_transform.rotate_y(-3.0 * delta_time);
    }

    let mut dir = Vec3::ZERO;
    if keyboard_input.pressed(KeyCode::KeyW) {
        dir.z -= 1.0;
    }
    if keyboard_input.pressed(KeyCode::KeyS) {
        dir.z += 1.0;
    }
    if keyboard_input.pressed(KeyCode::KeyA) {
        dir.x -= 1.0;
    }
    if keyboard_input.pressed(KeyCode::KeyD) {
        dir.x += 1.0;
    }

    let dir = camera_transform.rotation * dir;
    camera_transform.translation += dir * 12.0 * delta_time;
}
```

Video of minimal repro:

https://github.com/user-attachments/assets/4c8901b1-bce5-4126-b6b5-6b682a38908b

### PR DESCRIPTION
**Pull request by eero-lehtinen**
# Objective

Fixes #18945

## Solution

Entities that are not visible in any view (camera or light), get their render meshes removed. When they become visible somewhere again, the meshes get recreated and assigned possibly different ids.

Point/spot light visible entities weren't cleared when the lights themseves went out of view, which caused them to try to queue these fake visible entities for rendering every frame.  The shadow phase cache usually flushes non visible entites, but because of this bug it never flushed them and continued to queue meshes with outdated ids.

The simple solution is to every frame clear all visible entities for all point/spot lights that may or may not be visible. The visible entities get repopulated directly afterwards. I also renamed the `global_point_lights` to `global_visible_clusterable` to make it clear that it includes only visible things.

## Testing

- Tested with the code from the issue.

### CODE REVIEW

**Review by atlv24 — APPROVED** [review]

File: crates/bevy_pbr/src/render/light.rs [hunk 1]
```diff
@@ -276,6 +279,16 @@ pub fn extract_lights(
     if directional_light_shadow_map.is_changed() {
         commands.insert_resource(directional_light_shadow_map.clone());
     }
+
+    // Clear previous visible entities for all cubemapped lights as they might not be in the
+    // `global_visible_clusterable` list anymore.
+    commands.try_insert_batch(
```
Comment (tychedelia) [inline crates/bevy_pbr/src/render/light.rs:285]: Not sure this matters much in practice, but we could instead check the view visibility component and either remove  the component or default insert for just the ones that aren't visible.

**Review by tychedelia — APPROVED** [review]

File: crates/bevy_pbr/src/render/light.rs (hunk 1 above)
Comment (eero-lehtinen) [reply crates/bevy_pbr/src/render/light.rs:285]: I was also confused by that, but it seems that the `ViewVisibility` is only updated based on the user selected visibility. The info of being visible to any camera is in the `global_visible_clusterable`.

Comment (eero-lehtinen) [reply crates/bevy_pbr/src/render/light.rs:285]: I did try filtering based on view visibility here but everything was always marked visible so that didn't work.

Comment (tychedelia) [reply crates/bevy_pbr/src/render/light.rs:285]: Hmm, okay, interesting. That makes sense, thanks for looking more deeply into it.

Comment (eero-lehtinen) [reply crates/bevy_pbr/src/render/light.rs:283]: Actually it looks like I forgot the `ViewVisibility` part in the query. Let me remove it.

**Review by superdump — APPROVED** [review]
