### PR TITLE
Update camera_system to fix issue with late camera addition.

### LINKED ISSUE #476: Camera2dComponents spawned after frame 3 no more display anything.
I reproduced the issue by modifying the sprite.rs example to not spawn on startup, but after X frames.
If X >=3 the bevy logo no more appear.

Is there something that needs to be done to have the 2d camera work when spawned later in the life of the application ?

```rust
use bevy::prelude::*;
fn main() {
    App::build()
        .add_default_plugins()
        .add_resource(1u32)
        .add_system(setup.system())
        .run();
}

const FRAME_SPAWN: u32 = 3;

fn setup(
    mut commands: Commands,
    count: Res<u32>,
    asset_server: Res<AssetServer>,
    mut materials: ResMut<Assets<ColorMaterial>>,
) {
    if *count <= FRAME_SPAWN {
        println!("FRAME {}", *count);
        if *count == FRAME_SPAWN {
            let texture_handle = asset_server.load("assets/branding/icon.png").unwrap();
            commands.spawn(Camera2dComponents::default());
            commands.spawn(SpriteComponents {
                material: materials.add(texture_handle.into()),
                ..Default::default()
            });
            println!("Camera spawned");
        }
        commands.insert_resource(*count + 1);
    }
}
```

### PR DESCRIPTION
**Pull request by Bobox214**
This aims to fix #476.
Not sure if this is the best implementation for the fix.
As there is no AddedMut I was not able to do a standalone second query for added camera and their projection.

This version is solving the issue, I have checked with the modified sprite.rs/3d_scene.rs and my personal code.

Added an entry in the CHANGELOG

### CODE REVIEW

File: crates/bevy_render/src/camera/camera.rs [hunk 1]
```diff
@@ -67,9 +68,9 @@ pub fn camera_system<T: CameraProjection + Component>(
         changed_window_ids.push(event.id);
     }
 
-    for (mut camera, mut camera_projection) in &mut query.iter() {
+    for (entity, mut camera, mut camera_projection) in &mut query.iter() {
         if let Some(window) = windows.get(camera.window) {
-            if changed_window_ids.contains(&window.id) {
+            if changed_window_ids.contains(&window.id) || query_added.entity(entity).is_ok() {
```
Comment (cart) [inline crates/bevy_render/src/camera/camera.rs:73]: While this does "work" in that it ensures the camera gets updated, It doesn't work as expected because afaik it will run every frame. This happens for two reasons:

1) `query.entity()` returns a QueryOne (if the query matches the entity archetype), it doesn't actually run the query on the given entity.
2. even if we were to run `query_one.get()` (to run the query) it wouldn't actually take into account the `Added<T>` filter. This is a bug in QueryOne as far as I'm concerned. Inside `query_one.get()` we also need to run `.should_skip()` before calling `.next()`

Would you be open to fixing that problem too? It would amount to returning None here if `fetch.should_skip()` is true: https://github.com/bevyengine/bevy/blob/afe86b4b3a5bfd3a9a7f71375f4ad25296e6ba68/crates/bevy_ecs/hecs/src/query_one.rs#L47

**Review by cart — CHANGES_REQUESTED** [review]

File: crates/bevy_render/src/camera/camera.rs (hunk 1 above)
Comment (Bobox214) [reply crates/bevy_render/src/camera/camera.rs:73]: Yes, I’ll look into that also. Thanks for the catch !

**Comment by Bobox214** [comment]
I can't use the get() because then I ends up in "bevy_render::camera::camera::Camera already borrowed uniquely"
I have proposed another way to fix this, not sure if there is a better.
I'll look at the query_one.get() issue with Added separately.

**Review by cart — APPROVED** [review]
