### PR TITLE
Fix Gizmos not drawing `On<Pointer<Drag>>`, Observers generally, and Triggered Systems

### LINKED ISSUE #14566: Gizmos do not show from a triggered system
## Bevy version

- bevy 0.14
- current commit (at time of posting) `bevy = { git = "https://github.com/bevyengine/bevy.git", rev = "0685d2d" }`

## \[Optional\] Relevant system information

- window 10
- cargo 1.79.0 (ffa9cf99a 2024-06-03)
```ignore
AdapterInfo { name: "NVIDIA GeForce GTX 1080", vendor: 4318, device: 7040, device_type: DiscreteGpu, driver: "NVIDIA", driver_info: "551.86", backend: Vulkan }
```

## What you did

I can display gizmos just fine, but when I do it from a system that was triggered by app.observe, it doesn't work.

Minimal example:

```rust
use bevy::{
    color::palettes::css::{BLUE, RED},
    prelude::*,
};

fn main() {
    App::new()
        .add_plugins(DefaultPlugins)
        .add_systems(Startup, init_camera)
        // drawing a blue gizmo works as expected
        .add_systems(Update, regular_gizmo)
        // we trigger the DrawRedGizmo event on each frame
        .add_systems(Update, trigger_red_gizmo)
        // we try to draw a gizmo from this callback
        .observe(on_red_gizmo_triggered)
        .run();
}

#[derive(Event)]
struct DrawRedGizmo;

fn init_camera(mut cmd: Commands) {
    cmd.spawn(Camera2dBundle::default());
}

fn regular_gizmo(mut gizmos: Gizmos) {
    gizmos.circle_2d(Vec2::new(-50.0, 0.0), 40.0, BLUE);
}

fn trigger_red_gizmo(mut cmd: Commands) {
    cmd.trigger(DrawRedGizmo);
}

fn on_red_gizmo_triggered(_trigger: Trigger<DrawRedGizmo>, mut gizmos: Gizmos) {
    // that gizmo isn't shown.
    gizmos.circle_2d(Vec2::new(50.0, 0.0), 40.0, RED);
}
```

You can check the repository I made there:
https://github.com/cark/bevy-gizmo-bug

It contains a branch for bevy 0.14 and one for the current (at time of this post) bevy commit.

## What went wrong

- what were you expecting? 
  - I was expecting to see a red and a blue gizmo
- what actually happened? 
  - only the blue gizmo was visible

### LINKED ISSUE #19119: Gizmos will not render from a registered system
## Bevy version

v 0.16.0

## What you did

I used a 
```
use bevy::{ecs::system::SystemId, prelude::*};

fn main() {
    let mut app = App::new();
    app.add_plugins(DefaultPlugins);
    app.add_systems(Startup, startup);
    app.add_systems(Update, run_sys);
    app.run();
}

#[derive(Resource)]
struct SysId(SystemId<(), ()>);

fn startup(mut cmds: Commands) {
    cmds.spawn(Camera3d::default());

    let reg_sys_id = cmds.register_system(draw_sys);
    cmds.insert_resource(SysId(reg_sys_id));
}

fn draw_sys(mut gizmos: Gizmos) {
    gizmos.line(
        Vec3::new(-0.5, 0.0, -1.0),
        Vec3::new(0.5, 0.0, -1.0),
        Color::WHITE
    );
}

fn run_sys(ids: Res<SysId>, mut cmds: Commands) {
    let id = ids.0.clone();
    cmds.run_system(id);
}
```

## What went wrong

When I run this example app, the gizmo line doesn't render. However, if I add the `draw_sys` system to the `Update` schedule, it does renders.

I was expecting to get the same rendered result in both cases.

## Additional information

I also tried the following:
 - Spawning entities using `Commands` inside the registered system. This works the same as it would in a scheduled system.
 - Calling the registered system with `&mut World` instead of `Commands`. This has the same outcome.

In bevy v0.15.3, gizmos do render as expected using the above code. So the issue is caused by a change between those two versions.

### LINKED ISSUE #22485: Pointer<Drag> observers do not render gizmos
##  Relevant system information
kubuntu 24.04

```ignore
`AdapterInfo { name: "NVIDIA GeForce RTX 3070", vendor: 4318, device: 9348, device_type: DiscreteGpu, driver: "NVIDIA", driver_info: "580.95.05", backend: Vulkan }`
```

## What you did

Minimal repro example:
```rust
use bevy::prelude::*;

fn main() -> AppExit {
    App::new()
        .add_plugins((DefaultPlugins))
        .add_systems(Startup, setup)
        .add_observer(|src: On<Pointer<Drag>>, mut gizmos: Gizmos| {
            use bevy::color::palettes::css::*;
            info!("DRAG!");
            gizmos.rect_2d(Isometry2d::IDENTITY, Vec2::splat(60.), WHITE);
        })
        .run()
}
fn setup(mut commands: Commands) {
    commands.spawn(Camera2d);
}
```

## What went wrong

I would expect that during pointer drag, I would see a white bordered square dead center in the view port.
Instead, I get nothing, but I do see the `info!` printed to console.

## Additional information

Other information that can be used to further reproduce or isolate the problem.
This commonly includes:

- screenshots
- logs
- theories about what might be going wrong
- workarounds that you used
- links to related bugs, PRs or discussions

### PR DESCRIPTION
**Pull request by kfc35**
# Objective

- Fixes #22485 
- Fixes #14566 
- Fixes #19119 

## Solution

- Implement `queue()` for the `Gizmos` `SystemParam`.
- After much debugging, I discovered that the `Gizmos` system parameter never had `apply()` called on it when it was being used within an observer, which was why its internal `SystemBuffer` (`GizmoBuffer`) kept growing indefinitely. I saw that `SystemParam`’s also have a `queue()` function and was curious whether that was being called instead… and it was! So, I just implemented `queue()` in the same way that `apply()` was (after making sure it was OK to use a `DeferredWorld` in that way… and seems like it is OK?), and it solves the issue.
- Edit: I guess this problem has been described before in #14597 , where the solution described there as well is to implement `apply()`
- Disclaimer: Not an ECS master, so someone with ECS mastery can make sure what I wrote makes sense.

## Testing

The reproduction example in #22485 works now. A white square gizmo is drawn in the center if you drag inside the window.
I also tested against the examples in #14566 (both of them) and #19119 and the missing gizmos are drawn.

### CODE REVIEW

File: crates/bevy_gizmos/src/gizmos.rs [hunk 1]
```diff
@@ -224,6 +224,14 @@ where
         GizmosState::<Config, Clear>::apply(&mut state.state, system_meta, world);
     }
 
+    #[expect(
+        unused_mut,
+        reason = "The `world` parameter is unused for zero-length tuples; however, it must be mutable for other lengths of tuples."
+    )]
+    fn queue(state: &mut Self::State, system_meta: &SystemMeta, mut world: DeferredWorld) {
```
Comment (chescock) [inline crates/bevy_gizmos/src/gizmos.rs]: I think you can fix the `expect` by removing the `mut`: 

```suggestion
    fn queue(state: &mut Self::State, system_meta: &SystemMeta, world: DeferredWorld) {
```

File: crates/bevy_gizmos/src/gizmos.rs [hunk 2]
```diff
@@ -354,6 +362,14 @@ where
         storage.strip_positions.append(&mut self.strip_positions);
         storage.strip_colors.append(&mut self.strip_colors);
     }
+
+    fn queue(&mut self, _system_meta: &SystemMeta, mut world: DeferredWorld) {
```
Comment (chescock) [inline crates/bevy_gizmos/src/gizmos.rs:373]: You can convert `&mut World` to `DeferredWorld`, so I think you can share the implementation here by doing

```rust
    fn apply(&mut self, system_meta: &SystemMeta, world: &mut World) {
        self.queue(system_meta, world.into());
    }
```

**Comment by kfc35** [comment]
I addressed comments and checked that the repro examples are still fixed with the changes

After this builds, this should be ready to go @alice-i-cecile 🙏

File: crates/bevy_gizmos/src/gizmos.rs [hunk 3]
```diff
@@ -348,6 +352,10 @@ where
     Clear: 'static + Send + Sync,
 {
     fn apply(&mut self, _system_meta: &SystemMeta, world: &mut World) {
+        self.queue(_system_meta, world.into());
```
Comment (mockersf) [inline crates/bevy_gizmos/src/gizmos.rs]:
```suggestion
fn apply(&mut self, system_meta: &SystemMeta, world: &mut World) {
        self.queue(system_meta, world.into());
```

**Comment by kfc35** [comment]
Fixing conflicts!

**Comment by kfc35** [comment]
I resolved conflicts.

But this makes me wonder, since the change for the `SystemBuffer` stuff was merged first and placed in milestone 0.19 (as it should since it is potentially a breaking change), the change to implement `queue()` on `SystemBufferr` are not considered “changes” anymore in this pull request onto main. That makes sense, but I’m just hoping that that part of the fix is also put into 0.18.1 somehow.

I made a separate branch off `release-0.18.1` with the specific changes and will be watching the release-0.18.1 branch to open a pull request after merging this, in case it is needed.

**Comment by alice-i-cecile** [comment]
> I made a separate branch off release-0.18.1 with the specific changes and will be watching the release-0.18.1 branch to open a pull request after merging this, in case it is needed.

Perfect; that would be quite helpful.
