### PR TITLE
Fix culling for negative sized UI elements

### LINKED ISSUE #22906: UI fails to render when perfectly upside down
## Bevy version and features 

Bevy 0.18 (reproduced on 48ec375)

## Relevant system information

Rust 1.92

```ignore
AdapterInfo { name: "AMD Radeon RX 5500 XT (RADV NAVI14)", vendor: 4098, device: 29504, device_type: DiscreteGpu, driver: "radv", driver_info: "Mesa 25.3.5-arch1.1", backend: Vulkan }
```

## What you did

Can be reproduced with by adding a line to the ui_transform example:
```diff
diff --git a/examples/ui/ui_transform.rs b/examples/ui/ui_transform.rs
index b559c938f..0c919138f 100644
--- a/examples/ui/ui_transform.rs
+++ b/examples/ui/ui_transform.rs
@@ -173,6 +173,7 @@ fn setup(mut commands: Commands, asset_server: Res<AssetServer>) {
                         height: px(300),
                         ..default()
                     },
+                    UiTransform::from_rotation(Rot2::PI),
                     BackgroundColor(DARK_GRAY.into()),
                     TargetNode,
                     children![
```

## What went wrong
Expected: 
Image
Result:
Image

## Additional information

The other upside down elements in the example use `Rot2::radians(f32::consts::FRAC_PI_2)` which (due to floating point precision) is not exactly `Rot2{cos: -1.0, sin: 0.0}` that `Rot2::PI` provides.

### PR DESCRIPTION
**Pull request by GiantBlargg**
# Objective

Fixes #22906

## Solution

A similar solution had already been implemented for glyphs so I just copied that.

## Testing

See #22906 for a reproduction of the bug. After applying this fix, the result matches the expected.

### CODE REVIEW

File: crates/bevy_ui_render/src/lib.rs [hunk 1]
```diff
@@ -1581,9 +1581,10 @@ pub fn prepare_uinodes(
                         // This does not properly handles all rotations on all axis
                         if transform.x_axis[1] == 0.0 {
                             // Cull nodes that are completely clipped
-                            if positions_diff[0].x - positions_diff[1].x >= transformed_rect_size.x
+                            if positions_diff[0].x - positions_diff[1].x
+                                >= transformed_rect_size.x.abs()
                                 || positions_diff[1].y - positions_diff[2].y
-                                    >= transformed_rect_size.y
+                                    >= transformed_rect_size.y.abs()
```
Comment (ickshonpe) [inline crates/bevy_ui_render/src/lib.rs]: It would be less fragile if we assigned the absolute value to `transform_rect_size` before the if statement I think. 

The `box_shadow`, `gradient`, `uimaterial_pipeline`, and `ui_texture_slice_pipeline` all have the same bug too, if you want to fix those as well while you are here 😅

Comment (GiantBlargg) [reply crates/bevy_ui_render/src/lib.rs]: I did it this way because it's how glyphs did it, and also it's (maybe) a micro-optimization to avoid the second abs.

If I'm fixing the other pipelines too though, may as well do it early everywhere. (It's probably not really an optimization)

**Comment by GiantBlargg** [comment]
Added fix to other pipelines as well. Feels like a lot of duplicated code though. I wonder if some parts could be consolidated.

**Comment by GiantBlargg** [comment]
> RE: code deduplication, I personally think it can be spun out into a different issue to evaluate what code in those various `prepare` functions should be consolidated

Yeah, no I wasn't suggesting to do it here. Somebody else can handle that.

**Comment by ickshonpe** [comment]
> Added fix to other pipelines as well. Feels like a lot of duplicated code though. I wonder if some parts could be consolidated.

The main problem is the UI renderer is just really behind rest of Bevy's rendering and needs a complete overhaul. I've held back from doing big refactors here because it felt like adding any more abstractions or optimisations might not really achieve anything in the long term except to make migration to a better architecture more awkward.
