### PR TITLE
invert face culling for negatively scaled gltf nodes

### LINKED ISSUE #4738: Meshes with negative scale transforms are not rendered correctly
## Bevy version

0.7

## Operating system & version

Windows 10

## What you did

edit: this was discovered via gltf loading, however a simple way to reproduce it is to modify the `3d_scene` example an apply a negative scale to the cube transform.

I downloaded Kenney Car Kit from https://kenney.nl/assets/car-kit and loaded the `Models/GLTF format/suv.glb#Scene0` asset in a bevy project.

When examining the vehicle in bevy, the wheels on the left of the car are not visible and the wheel on the back of the car is partially visible.

I opened up this asset in Blender and found that the nodes that we not rendering were using negative scale on the x axis to mirror the wheel.

If you load this asset up in the scene viewer example it is a bit clearer there, the negative scale nodes are rendered, but it looks like back face culling is inverted or something.

```
cargo run --example scene_viewer suv.glb
```

## What you expected to happen

Negative scaled objects should be rendered correctly.

## What actually happened

Negative scaled objects were not rendered correctly.

## Additional information

bevy:

bevy

blender:

blender

### LINKED ISSUE #7901: Lighting of GLTF models with negative scale is inverted
**Update**
https://github.com/bevyengine/bevy/issues/7901#issuecomment-1454984501

## Bevy version

0.9.1 / `main` branch at `f87de368436a1a65aecb8e0088d93244dd5a467c`

## Relevant system information

```ignore
AdapterInfo { name: "NVIDIA GeForce GTX 1080 Ti", vendor: 4318, device: 6918, device_type: DiscreteGpu, driver: "NVIDIA", driver_info: "528.49", backend: Vulkan }
```

## What you did

I made a model in Blender, exported it to GLTF and imported it inside my Bevy application using `SceneBundle`:

```rust
let box_dude = assets.load("box_dude.glb#Scene0");

commands.spawn(SceneBundle {
    scene: box_dude,
    ..default()
});

commands.spawn(Camera3dBundle {
    transform: Transform::from_xyz(12.0, 36.0, 12.0).looking_at(Vec3::ZERO, Vec3::Y),
    ..default()
});

commands.spawn(PointLightBundle {
    transform: Transform::from_xyz(4.0, 2.0, 4.0),
    point_light: PointLight {
        color: Color::WHITE,
        shadows_enabled: true,
        ..Default::default()
    },
    ..Default::default()
});
```

## What went wrong

Outside faces of `box_dude` are not lit up:
image

If you zoom in, you can see that the *edge* of the face is kinda lit up, but I guess this is just some bleeding due to the camera being far away and it's actually the inside that's lit up.

If I move the `box_dude` to be inside the point light, you can see that his head's outside faces are lit up, which is incorrect.
image

**I tried flipping the normals and re-exporting, but it does not change anything.**

The same file looks correct in online GLTF viewers:
image

## Additional information

Here's the `.glb` file I used:
https://www80.zippyshare.com/v/4UrsUvvL/file.html

### PR DESCRIPTION
**Pull request by robtfm**
# Objective

according to [khronos](https://github.com/KhronosGroup/glTF/issues/1697), gltf nodes with inverted scales should invert the winding order of the mesh data. this is to allow negative scale to be used for mirrored geometry.

## Solution

in the gltf loader, create a separate material with `cull_mode` set to `Face::Front` when the node scale is negative.

note/alternatives:
this applies for nodes where the scale is negative at gltf import time. that seems like enough for the mentioned use case of mirrored geometry. it doesn't help when scales dynamically go negative at runtime, but you can always set double sided in that case.

i don't think there's any practical difference between using front-face culling and setting a clockwise winding order explicitly, but winding order is supported by wgpu so we could add the field to StandardMaterial/StandardMaterialKey and set it directly on the pipeline descriptor if there's a reason to. it wouldn't help with dynamic scale adjustments anyway, and would still require a separate material. 

fixes #4738, probably fixes #7901.

### CODE REVIEW

**Comment by robtfm** [comment]
tested and seems fine with examples from https://github.com/KhronosGroup/glTF-Asset-Generator/blob/master/Output/Positive/Node_NegativeScale/README.md.

i had to generate indices to get the normal maps to load (#8862)

File: crates/bevy_gltf/src/loader.rs [hunk 1]
```diff
@@ -734,10 +741,13 @@ fn load_node(
     node_index_to_entity_map: &mut HashMap<usize, Entity>,
     entity_to_skin_index_map: &mut HashMap<Entity, usize>,
     active_camera_found: &mut bool,
+    parent_transform: &Transform,
 ) -> Result<(), GltfError> {
     let transform = gltf_node.transform();
     let mut gltf_error = None;
     let transform = Transform::from_matrix(Mat4::from_cols_array_2d(&transform.matrix()));
+    let world_transform = *parent_transform * transform;
+    let is_scale_inverted = world_transform.scale.is_negative_bitmask().count_ones() & 1 == 1;
```
Comment (JMS55) [inline crates/bevy_gltf/src/loader.rs:750]: Can we get a small comment here on what this line does?
Also a link to the GLTF spec about negative scaling.

**Review by JMS55 — CHANGES_REQUESTED** [review]

**Review by JMS55 — APPROVED** [review]

**Comment by rparrett** [comment]
I believe this should fix #4738 and possibly #7901.

**Comment by robtfm** [comment]
> I believe this should fix #4738 and possibly #7901. 

It’ll definitely fix the first. I’ve also found lighting works correctly with inverse scaled meshes so probably the second too - I can’t check though as the file link is dead.

File: crates/bevy_gltf/src/loader.rs [hunk 2]
```diff
@@ -734,10 +741,19 @@ fn load_node(
     node_index_to_entity_map: &mut HashMap<usize, Entity>,
     entity_to_skin_index_map: &mut HashMap<Entity, usize>,
     active_camera_found: &mut bool,
+    parent_transform: &Transform,
 ) -> Result<(), GltfError> {
     let transform = gltf_node.transform();
     let mut gltf_error = None;
     let transform = Transform::from_matrix(Mat4::from_cols_array_2d(&transform.matrix()));
+    let world_transform = *parent_transform * transform;
```
Comment (devil-ira) [inline crates/bevy_gltf/src/loader.rs:749]: `Transform * Transform` is a lossy operation. I'm concerned the determinant might end up incorrect in some transform hierarchies.
I suggest passing a `GlobalTransform` around instead to be certain.

Comment (robtfm) [reply crates/bevy_gltf/src/loader.rs:749]: i'm happy to do this. it'll be slower, but this isn't a hot code path.

in the [gltf spec](https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.html#transformations) it says that you can either use a translation + scale + rotation, or a matrix which must decompose into those parts, and explicitly cannot skew or shear. 

since we only care about the scale, and the scales are just Vec3-multiplied at each step, i'm pretty sure this is safe. i guess i could pass the scale down as a Vec3 instead of the whole transform if that would be clearer / avoid potential future misuse.

Comment (devil-ira) [reply crates/bevy_gltf/src/loader.rs:749]: > in the [gltf spec](https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.html#transformations) it says that you can either use a translation + scale + rotation, or a matrix which must decompose into those parts, and explicitly cannot skew or shear.

I think that implementation note is referring purely to the local transform stored in the gltf format, but the note is unfortunately not making that very clear.

> since we only care about the scale, and the scales are just Vec3-multiplied at each step, i'm pretty sure this is safe.

I don't have the math intuition to know whether the loss of skew and shear still keeps the determinant the same 🤷

Comment (robtfm) [reply crates/bevy_gltf/src/loader.rs:749]: > I think that implementation note is referring purely to the local transform stored in the gltf format, but the note is unfortunately not making that very clear.

yes, but that's all we're dealing with here. at this point the gltf isn't part of the world heirarchy, we just initialize the transform to IDENTITY at the gltf root node.

File: crates/bevy_gltf/src/loader.rs [hunk 3]
```diff
@@ -734,10 +741,19 @@ fn load_node(
...
+    // according to https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.html#instantiation,
+    // if the determinant of the transform is negative we must invert the winding order of 
+    // triangles in meshes on the node. 
+    // instead we equivalently test if the global scale is inverted by checking if the number 
+    // of negative scale factors is odd. if so we will assign a copy of the material with face 
+    // culling inverted, rather than modifying the mesh data directly.
```
Comment (mockersf) [inline crates/bevy_gltf/src/loader.rs:755]:
```suggestion
    // if the determinant of the transform is negative we must invert the winding order of
    // triangles in meshes on the node.
    // instead we equivalently test if the global scale is inverted by checking if the number
    // of negative scale factors is odd. if so we will assign a copy of the material with face
    // culling inverted, rather than modifying the mesh data directly.
```

**Comment by mockersf** [comment]
This doesn't work if the same material is used by 2 meshes, one with positive scale, one with negative scale

**Review by mockersf — APPROVED** [review]
