### PR TITLE
don't attempt to set cursor relative position for zero sized nodes

### LINKED ISSUE #12007: Interactivity regression in bevy_ui
## Bevy version

0.13

## What you did

Upgraded to bevy 0.13

## What went wrong

Absolutely positioned UI nodes over regular nodes capture interactivity when they are visible but `Display::None` (but `FocusPolicy::Block`). Issue seems to be from the explicit combination of `Display::None`, and `Visibility::Visible` or `Visibility::Inherited`. The `Display::None` element blocks a rectangle from the top left corner of the window to the top left corner of it's parent. The example below draws three boxes, the gray one changes color when hovered, however the top left corner is not interactive when the red box is `Display::None` and `Visiblity::Visible`. Use the `v` key to toggle visibility and the `d` key to toggle the display property.

## Additional information

*might* be related to https://github.com/bevyengine/bevy/pull/10454 or an update on taffy.

## Reproduce with

``` rust
use bevy::prelude::*;

fn main() {
    App::new().add_plugins(ProblemPlugin).run();
}

pub struct ProblemPlugin;

impl Plugin for ProblemPlugin {
    fn build(&self, app: &mut App) {
        app.add_plugins(DefaultPlugins.set(WindowPlugin {
            primary_window: Some(Window {
                resolution: (320., 320.).into(),
                ..default()
            }),
            ..default()
        }))
        .add_systems(Startup, setup)
        .add_systems(Update, (update_bg_on_hover, update_foreground_box));
    }
}

#[derive(Component)]
pub struct MainCamera;

#[derive(Component)]
pub struct BackgroundBox;

#[derive(Component)]
pub struct ForegroundBox;

fn update_bg_on_hover(
    mut q_node: Query<
        (&mut BackgroundColor, &Interaction),
        (Changed<Interaction>, With<BackgroundBox>),
    >,
) {
    for (mut bg, interaction) in &mut q_node {
        match *interaction {
            Interaction::Pressed => bg.0 = Color::rgb(0.7, 0.7, 0.7),
            Interaction::Hovered => bg.0 = Color::rgb(0.5, 0.7, 0.7),
            Interaction::None => bg.0 = Color::GRAY,
        }
    }
}

fn update_foreground_box(
    mut q_foreground: Query<(&mut Visibility, &mut Style), With<ForegroundBox>>,
    r_input: Res<ButtonInput<KeyCode>>,
) {
    if r_input.just_pressed(KeyCode::KeyV) {
        let (mut visibility, _) = q_foreground.single_mut();
        *visibility = match *visibility {
            Visibility::Inherited => Visibility::Hidden,
            Visibility::Hidden => Visibility::Visible,
            Visibility::Visible => Visibility::Inherited,
        };
        info!("Visibility is now: {:?}", *visibility);
    }

    if r_input.just_pressed(KeyCode::KeyD) {
        let (_, mut style) = q_foreground.single_mut();
        style.display = match style.display {
            Display::Flex => Display::None,
            Display::Grid => Display::None,
            Display::None => Display::Flex,
        };
        info!("Display is now: {:?}", style.display);
    }
}

fn setup(mut commands: Commands) {
    let box_size = 2.0;
    let box_thickness = 0.15;
    let box_offset = (box_size + box_thickness) / 2.0;

    // ambient light
    commands.insert_resource(AmbientLight {
        color: Color::WHITE,
        brightness: 0.02,
    });

    commands.spawn(DirectionalLightBundle {
        directional_light: DirectionalLight {
            illuminance: 10000.0,
            ..default()
        },
        transform: Transform::from_rotation(Quat::from_rotation_x(-std::f32::consts::PI / 2.0)),
        ..Default::default()
    });

    // camera
    commands.spawn((
        Camera3dBundle {
            camera: Camera {
                order: 0,
                ..default()
            },
            transform: Transform::from_xyz(0.0, box_offset, 4.0)
                .looking_at(Vec3::new(0.0, box_offset, 0.0), Vec3::Y),
            ..Default::default()
        },
        MainCamera,
    ));

    commands
        .spawn(NodeBundle::default())
        .with_children(|builder| {
            builder.spawn((
                NodeBundle {
                    style: Style {
                        position_type: PositionType::Absolute,
                        width: Val::Px(200.),
                        height: Val::Px(200.),
                        ..default()
                    },
                    focus_policy: bevy::ui::FocusPolicy::Block,
                    ..default()
                },
                BackgroundBox,
                Interaction::default(),
            ));
            builder
                .spawn((
                    NodeBundle {
                        style: Style {
                            position_type: PositionType::Absolute,
                            left: Val::Px(100.),
                            top: Val::Px(100.),
                            width: Val::Px(200.),
                            height: Val::Px(200.),
                            ..default()
                        },
                        background_color: Color::DARK_GRAY.into(),
                        focus_policy: bevy::ui::FocusPolicy::Block,
                        ..default()
                    },
                    Interaction::default(),
                ))
                .with_children(|builder| {
                    builder.spawn((
                        NodeBundle {
                            style: Style {
                                position_type: PositionType::Absolute,
                                top: Val::Px(20.),
                                left: Val::Px(20.),
                                width: Val::Px(50.),
                                height: Val::Px(50.),
                                display: Display::None,
                                ..default()
                            },
                            background_color: Color::RED.into(),
                            focus_policy: bevy::ui::FocusPolicy::Block,
                            ..default()
                        },
                        ForegroundBox,
                        Interaction::default(),
                    ));
                });
        });
}
```

### PR DESCRIPTION
**Pull request by robtfm**
# Objective

fix #12007

## Solution

when node size is zero on either axis, set `RelativeCursorPosition::normalized` to None.

### CODE REVIEW

File: crates/bevy_ui/src/focus.rs [hunk 1]
```diff
@@ -252,9 +252,13 @@ pub fn ui_focus_system(
...
             // (0., 0.) is the top-left corner, (1., 1.) is the bottom-right corner
             // Coordinates are relative to the entire node, not just the visible region.
-            let relative_cursor_position = camera_cursor_positions
-                .get(&camera_entity)
-                .map(|cursor_position| (*cursor_position - node_rect.min) / node_rect.size());
+            let relative_cursor_position =
+                camera_cursor_positions
+                    .get(&camera_entity)
+                    .and_then(|cursor_position| {
+                        (node_rect.size().cmpgt(Vec2::ZERO).all())
```
Comment (alice-i-cecile) [inline crates/bevy_ui/src/focus.rs:259]: A comment on this line explaining why this is needed (maybe with a link to this PR) would be great.

**Review by alice-i-cecile — APPROVED** [review]

**Review by james7132 — APPROVED** [review]
