### PR TITLE
Optional override for global spatial scale

### LINKED ISSUE #10414: Spatial Audio Functional Regression - different spatial scaling factor for each object
## What problem does this solve or what need does it fill?

I want to scale spatial audio differently for each effect. This is so I can have some "far away" effects (low volume, low distance scaling) mixed together with some "close up" effects (high volume, high distance scaling).

For example, explosions - when they happen far away, https://freesound.org/people/rhapsodize/sounds/255111/

When they happen close up, https://freesound.org/people/juskiddink/sounds/108641/

Both effects need to live at the same time with different spatial scales, because the camera can quickly move closer/further away from the audio source.

I would also want this to work on multiple listeners at the same time: one main camera for 80% volume, and a few extra cameras for 20% volume each.

This was trivial under Bevy 0.11 (in the old update positions system), but now is impossible with bevy_audio 0.12:

> https://bevyengine.org/learn/migration-guides/0.11-0.12/#more-ergonomic-spatial-audio
> If you were manually scaling emitter/listener positions, you can use the spatial_scale field of AudioPlugin instead.

But the `AudioPlugin` is a global, so all objects must share the same spatial scale.

## What solution would you like?

Extra field `spatial scale` for each Spatial Audio Source

## What alternative(s) have you considered?

- in a system, manually change the `RelativeVolume` component based on distance and some formula
  - problem: doesn't work with multiple listeners, because the volume is set per-effect not per-listener
- swap out bevy_audio for one of the external plugins

### PR DESCRIPTION
**Pull request by rparrett**
# Objective

Fixes #10414.

That issue and its comments do a great job of laying out the case for this.

## Solution

Added an optional `spatial_scale` field to `PlaybackSettings`, which overrides the default value set on `AudioPlugin`.

## Changelog

- `AudioPlugin::spatial_scale` has been renamed to `default_spatial_scale`.
- `SpatialScale` is no longer a resource and is wrapped by `DefaultSpatialScale`.
- Added an optional `spatial_scale` to `PlaybackSettings`.

## Migration Guide

`AudioPlugin::spatial_scale` has been renamed to `default_spatial_scale` and the default spatial scale can now be overridden on individual audio sources with `PlaybackSettings::spatial_scale`.

If you were modifying or reading `SpatialScale` at run time, use `DefaultSpatialScale` instead.

```rust
// before
app.add_plugins(DefaultPlugins.set(AudioPlugin {
    spatial_scale: SpatialScale::new(AUDIO_SCALE),
    ..default()
}));

// after
app.add_plugins(DefaultPlugins.set(AudioPlugin {
    default_spatial_scale: SpatialScale::new(AUDIO_SCALE),
    ..default()
}));
```

### CODE REVIEW

File: crates/bevy_audio/src/audio_output.rs [hunk 1]
```diff
@@ -136,8 +132,10 @@ pub(crate) fn play_queued_audio_system<Source: Asset + Decodable>(
                     );
                 }
 
+                // XXX scale seems jacked here.
```
Comment (Ixentus) [inline crates/bevy_audio/src/audio_output.rs:135]: What is meant by this?

File: examples/audio/spatial_audio_2d.rs
Comment (Ixentus) [inline examples/audio/spatial_audio_2d.rs:1]: AudioPlugin can be removed now

**Review by Ixentus — APPROVED** [review]
Ran the changed example and it worked as expected.

The changes makes sense and the code looks good. LGTM

File: crates/bevy_audio/src/audio_output.rs (hunk 1 above)
Comment (rparrett) [reply crates/bevy_audio/src/audio_output.rs]: No idea. I think this must be an artifact of the refactoring process. There doesn't seem to be an issue. Deleting.

**Comment by rparrett** [comment]
I will try to rebase this soon.

**Comment by rparrett** [comment]
> Maybe we also want to add a DefaultSpatialScale setting? I felt like doing this would be sort of ugly -- maybe requiring spatial_scale to be an Option<SpatialScale>, so I didn't do that.

Three months later, I feel like this might be worth the effort? Anyone have an opinion?

**Comment by Ixentus** [comment]
> > Maybe we also want to add a DefaultSpatialScale setting? I felt like doing this would be sort of ugly -- maybe requiring spatial_scale to be an Option, so I didn't do that.
> 
> Three months later, I feel like this might be worth the effort. Anyone have an opinion?

DefaultSpatialScale sounds like a good idea. Setting a ton of entities to the same value would be painful. Would it just be a Resource who's value would be used if `.with_spatial(true)` is used without `.with_spatial_scale()`? Where does the Option come in?

**Comment by rparrett** [comment]
Yeah, I guess things would work more or less like before this PR for configuring the default scale, but `PlaybackSettings` would need to use an `Option<SpatialScale>` to make

> used if `.with_spatial(true)` is used without `.with_spatial_scale()`

doable.

**Comment by rparrett** [comment]
It was easier to just re-implement the changes than it was to fix merge conflicts, so I did that and added `DefaultSpatialScale`. That wasn't a super small change, so I'd appreciate a re-review.

**Comment by Ixentus** [comment]
Much more convenient. Went through it again and it looks great. Let's get this merged!

You might want to update the opening post, especially the changelog and migration guide since they get included in the release info.

**Comment by rparrett** [comment]
Thanks for the reminder. The PR description should be up-to-date now. While updating the migration guide I found an opportunity to make this slightly less breaking by taking a `SpatialScale` instead of `DefaultSpatialScale` in `AudioPlugin`.

I wonder if the `From<SpatialScale>` impl is still useful?

**Comment by Ixentus** [comment]
> Thanks for the reminder. The PR description should be up-to-date now. While updating the migration guide I found an opportunity to make this slightly less breaking by taking a `SpatialScale` instead of `DefaultSpatialScale` in `AudioPlugin`.

Very clean! 

> I wonder if the `From<SpatialScale>` impl is still useful?

Since users never need to construct a `DefaultSpatialScale` it doesn't seem useful anymore.

**Review by alice-i-cecile — APPROVED** [review]
