### PR TITLE
fix missed examples in WebGPU update

### LINKED ISSUE #8556: `texture_binding_array` example no longer runs on main
## Bevy version: main d319910d36e65fe6b7537ca40e4e44f81d8e6bba

71842c5ac92dc61b0c73446a233078d5285ecf7c broke the `texture_binding_array` example:

thread 'main' panicked at 'Requested resource `bevy_render::renderer::render_device::RenderDevice` does not exist in the `World`. 
                Did you forget to add it using `app.insert_resource` / `app.init_resource`?
                Resources are also implicitly added via `app.add_event`,
                and can be added by plugins.', examples/shader/texture_binding_array.rs:20:35

### LINKED ISSUE #8620: post_processing example crashes when trying to run
## Bevy version
tested on: https://github.com/bevyengine/bevy/commit/1da726e046b378f347eb72b072fac2509c5367e6

I ran the example and it immediately crashes.

## Additional information
example:  `examples/shader/post_processing.rs`

compiler output: 
```
thread 'main' panicked at 'Requested resource bevy_render::renderer::render_device::RenderDevice does not exist in the `World`. 
                Did you forget to add it using `app.insert_resource` / `app.init_resource`? 
                Resources are also implicitly added via `app.add_event`,
                and can be added by plugins.', examples/shader/post_processing.rs:243:35
```

### PR DESCRIPTION
**Pull request by mockersf**
# Objective

- I missed a few examples in #8336 
- fixes #8556 
- fixes #8620

## Solution

- Update them

### CODE REVIEW

File: examples/shader/post_processing.rs [hunk 1]
```diff
@@ -97,6 +95,17 @@ impl Plugin for PostProcessPlugin {
                 ],
             );
     }
+
+    fn finish(&self, app: &mut App) {
+        // We need to get the render app from the main app
+        let Ok(render_app) = app.get_sub_app_mut(RenderApp) else {
+                    return;
+                };
```
Comment (rparrett) [inline examples/shader/post_processing.rs:103]: Formatting

**Comment by rparrett** [comment]
Same issue with `anti_aliasing`?

(And maybe a separate issue with `without_winit`?)

File: examples/shader/texture_binding_array.rs [hunk 2]
```diff
@@ -47,7 +32,21 @@ fn setup(
     mut meshes: ResMut<Assets<Mesh>>,
     mut materials: ResMut<Assets<BindlessMaterial>>,
     asset_server: Res<AssetServer>,
+    render_device: Res<RenderDevice>,
 ) {
+    // check if the device support the required feature
```
Comment (rparrett) [inline examples/shader/texture_binding_array.rs:37]: If I recall correctly, this was in main partially as a way of demonstrating graceful handling of feature detection.

But now with wasm/webgl2 at least, we get a panic before this code gets a chance to run.

Is this code even useful anymore?

```
sm.js:387 panicked at 'wgpu error: Validation Error

Caused by:
    In Device::create_bind_group_layout
      note: label = `bindless_material_layout`
    Binding 0 entry is invalid
    Features Features(TEXTURE_BINDING_ARRAY) are required but not enabled on the device

', /Users/me/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.16.0/src/backend/direct.rs:3019:5
```

Comment (JMS55) [reply examples/shader/texture_binding_array.rs:37]: That should really be moved to main, after the default plugin is setup and before the custom material is setup.

Comment (mockersf) [reply examples/shader/texture_binding_array.rs:37]: > But now with wasm/webgl2 at least, we get a panic before this code gets a chance to run.

Oh that gives the correct log in wasm/WebGPU, but not in wasm/WebGL2...

> That should really be moved to main(), after the default plugin is setup and before the custom material is setup.

That's not possible anymore, the renderer is not available before the winit event loop is started.

Comment (JMS55) [reply examples/shader/texture_binding_array.rs:37]: Is it only the device that needs to be created in finish()? Can we create a queue in the main plugin build, and use that to check for feature support?

Comment (mockersf) [reply examples/shader/texture_binding_array.rs:37]: Getting the adapter is async: https://docs.rs/wgpu/latest/wgpu/struct.Instance.html#method.request_adapter
Getting the device is async: https://docs.rs/wgpu/latest/wgpu/struct.Adapter.html#method.request_device

Comment (JMS55) [reply examples/shader/texture_binding_array.rs:37]: For context, I need this pattern of checking whether a feature is supported before loading a plugin for my own crates. It's important that we find a way to solve it nicely :). It's not something we can just let an example crash if not supported.

Comment (mockersf) [reply examples/shader/texture_binding_array.rs:37]: A more complete fix would be to introduce a "fake" plugin in the example that just does the check, but nothing else from what's expected from a plugin

Comment (mockersf) [reply examples/shader/texture_binding_array.rs]: @JMS55 would https://github.com/bevyengine/bevy/pull/8553/files#diff-86a9f1eba7a2e2bcb940a56d71acb7675c9c24ab6981ed7f221a10f9117514f0R32 work for you?

Comment (JMS55) [reply examples/shader/texture_binding_array.rs]: I'm not sure. What I need is the ability to add a plugin only if certain features are supported. Here's an example: https://github.com/JMS55/bevy/blob/solari/crates/bevy_solari/src/lib.rs#L45-L62.

Comment (mockersf) [reply examples/shader/texture_binding_array.rs]: That's not going to be possible like that, without putting all the app initialisation as async.

What you can do is add your plugins, but have them do nothing if the feature are not available.

**Review by james7132 — APPROVED** [review]

File: examples/shader/texture_binding_array.rs (hunk 2 above)
Comment (JMS55) [reply examples/shader/texture_binding_array.rs]: I don't love this solution, but I guess it'll have to do :(

**Review by coreh — APPROVED** [review]

**Review by IceSentry — APPROVED** [review]
