### PR TITLE
Make buffer binding arrays emit bind group layout entries and bindless resource descriptors again.

### LINKED ISSUE #18124: Example `shader_material_bindless` crashes
## Bevy version

Since #17965 (5d7a60592df05ffac3a8523b2f596041d6df33d6)

## \[Optional\] Relevant system information

```
2025-03-03T02:14:32.889785Z  INFO bevy_diagnostic::system_information_diagnostics_plugin::internal: SystemInfo { os: "Linux (NixOS 24.11)", kernel: "6.6.69", cpu: "Intel(R) Core(TM) i7-14700KF", core_count: "20", memory: "31.2 GiB" }    
2025-03-03T02:14:33.028432Z  INFO bevy_render::renderer: AdapterInfo { name: "NVIDIA GeForce RTX 4060 Ti", vendor: 4318, device: 10243, device_type: DiscreteGpu, driver: "NVIDIA", driver_info: "565.77", backend: Vulkan }
```

## What you did

`cargo run --example shader_material_bindless`

## What went wrong

Crash

## Additional information

May be linux exclusive as reported by https://thebevyflock.github.io/bevy-example-runner/

Full log
```
2025-03-03T02:14:32.889785Z  INFO bevy_diagnostic::system_information_diagnostics_plugin::internal: SystemInfo { os: "Linux (NixOS 24.11)", kernel: "6.6.69", cpu: "Intel(R) Core(TM) i7-14700KF", core_count: "20", memory: "31.2 GiB" }    
2025-03-03T02:14:32.969335Z ERROR wgpu_hal::gles::egl: EGL 'eglCreateSyncKHR' code 0x3004: EGL_BAD_ATTRIBUTE error: In eglCreateSyncKHR: EGL_SYNC_NATIVE_FENCE_FD_ANDROID specified valid fd butEGL_SYNC_STATUS is also being set
    
2025-03-03T02:14:33.028432Z  INFO bevy_render::renderer: AdapterInfo { name: "NVIDIA GeForce RTX 4060 Ti", vendor: 4318, device: 10243, device_type: DiscreteGpu, driver: "NVIDIA", driver_info: "565.77", backend: Vulkan }
2025-03-03T02:14:33.451764Z  INFO bevy_winit::system: Creating new window App (0v1)
2025-03-03T02:14:33.451828Z  INFO winit::platform_impl::linux::x11::window: Guessed window scale factor: 1
2025-03-03T02:14:33.575263Z ERROR bevy_pbr::material_bind_groups: Binding array wasn't present for buffer at index BindlessIndex(0)

thread 'Compute Task Pool (13)' panicked at /home/hukasu/Code/bevy_fork/crates/bevy_pbr/src/material_bind_groups.rs:765:13:
An allocation into an empty slab should always succeed
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Encountered a panic in system `bevy_render::render_asset::prepare_assets<bevy_pbr::material::PreparedMaterial<shader_material_bindless::BindlessMaterial>>`!

thread 'Compute Task Pool (13)' panicked at /home/hukasu/Code/bevy_fork/crates/bevy_pbr/src/material_bind_groups.rs:1214:18:
Bindings buffer must exist
Encountered a panic in system `bevy_pbr::material::prepare_material_bind_groups<shader_material_bindless::BindlessMaterial>`!
```

### PR DESCRIPTION
**Pull request by pcwalton**
PR #17965 mistakenly made the `AsBindGroup` macro no longer emit a bind group layout entry and a resource descriptor for buffers. This commit adds that functionality back, fixing the `shader_material_bindless` example.

Closes #18124.

### CODE REVIEW

**Comment by JMS55** [comment]
I don't know enough about AsBindGroup to review this, sorry.

File: crates/bevy_render/macros/src/as_bind_group.rs [hunk 1]
```diff
@@ -161,6 +161,29 @@ pub fn derive_as_bind_group(ast: syn::DeriveInput) -> Result<TokenStream> {
                             }
                             _ => {}
                         }
+
+                        let binding_array_binding = binding_array_binding.unwrap_or(0);
```
Comment (superdump) [inline crates/bevy_render/macros/src/as_bind_group.rs:165]: 0? Why is 0 implicitly correct? I thought the data is automatically serialised into a buffer at binding 0?

Comment (pcwalton) [reply crates/bevy_render/macros/src/as_bind_group.rs:165]: It's not. I just need a dummy value to insert into `bindless_binding_layouts`, because we populate that array anyway even in the non-bindless case, for simplicity. Maybe that should be refactored though.

**Review by tychedelia — APPROVED** [review]
Tested on macOS.

**Review by IceSentry — APPROVED** [review]
