### PR TITLE
Fix transform propagation of orphaned entities

### LINKED ISSUE #7263: The `GlobalTransform` did not get updated when `Parent` was removed
## What problem does this solve or what need does it fill?

The `GlobalTransform` did not get updated (it should be) when `Parent` was removed.

## What solution would you like?

- Always recalculate the new `GlobalTransform` then `set_if_neq`.
```rust
if transform_changed {
    *global_transform = GlobalTransform::from(*transform);
} else {
    global_transform.set_if_neq(GlobalTransform::from(*transform));
}
```

-  Or use `RemovedComponents<Parent>`, _which may have poor performance_ if there have so many entities without `Transform`.

-  Or use `Removed` change detection, _but does not exist currently_.
```rust
Query<(&Transform, &mut GlobalTransform, Removed<Parent>)>
```
```rust
if parent_removed || transform_changed {
  *global_transform = GlobalTransform::from(*transform);
}
```

## What alternative(s) have you considered?
none

## Additional context
none

### PR DESCRIPTION
**Pull request by nicopap**
# Objective

- Fix #7263

This has nothing to do with #7024. This is for the case where the
user opted to **not** keep the same global transform on update.

## Solution

- Add a `RemovedComponent<Parent>` to `propagate_transforms`
- Add a `RemovedComponent<Parent>` and `Local<Vec<Entity>>` to `sync_simple_transforms`
- Add test to make sure all of this works.

### Performance note

This should only incur a cost in cases where a parent is removed.

A minimal overhead (one look up in the `removed_components`
sparse set) per root entities without children which transform didn't
change. A `Vec` the size of the largest number of entities removed
with a `Parent` component in a single frame, and a binary search on
a `Vec` per root entities.

It could slow up considerably in situations where a lot of entities are
orphaned consistently during every frame, since
`sync_simple_transforms` is not parallel. But in this situation,
it is likely that the overhead of archetype updates overwhelms everything.

---

## Changelog

- Fix the `GlobalTransform` not getting updated when `Parent` is removed

## Migration Guide

- If you called `bevy_transform::systems::sync_simple_transforms` and `bevy_transform::systems::propagate_transforms` (which is not re-exported by bevy) you need to account for the additional `RemovedComponents<Parent>` parameter.

### CODE REVIEW

File: crates/bevy_transform/src/systems.rs [hunk 1]
```diff
@@ -30,16 +46,19 @@ pub fn propagate_transforms(
...
+    let mut orphaned = orphaned.iter().collect::<Vec<_>>();
+    orphaned.sort_unstable();
     root_query.par_for_each_mut(
         // The differing depths and sizes of hierarchy trees causes the work for each root to be
         // different. A batch size of 1 ensures that each tree gets it's own task and multiple
         // large trees are not clumped together.
         1,
         |(entity, children, transform, mut global_transform)| {
-            let changed = transform.is_changed();
+            let changed = transform.is_changed() || orphaned.binary_search(&entity).is_ok();
```
Comment (james7132) [inline crates/bevy_transform/src/systems.rs:61]: It may actually be faster to do a sparse set `contains` check here than do the binary search. It'd also avoid the allocation and sort.

File: crates/bevy_transform/src/systems.rs [hunk 2]
```diff
@@ -19,6 +20,21 @@ pub fn sync_simple_transforms(
         *global_transform = GlobalTransform::from(*transform);
     });
 }
+/// Update [`GlobalTransform`] component of entities that aren't in the hierarchy
+/// and lost their parent last frame.
+///
+/// Third party plugins should use [`transform_propagate_system_set`](crate::transform_propagate_system_set)
+/// to propagate transforms correctly.
+pub fn sync_simple_transforms_orphaned(
```
Comment (james7132) [inline crates/bevy_transform/src/systems.rs:28]: Could this just be incorporated into sync_simple_transforms? Thus cannot parallelize with it anyway due to the queries not being disjoint.

**Review by james7132 — CHANGES_REQUESTED** [review]

File: crates/bevy_transform/src/systems.rs (hunk 1 above)
Comment (nicopap) [reply crates/bevy_transform/src/systems.rs:61]: How would this look? `RemovedComponents` only exposes the `iter()` method. all other fields private. I guess the best way would be to add a method on `RemovedComponents` to allow sparse set contains checks.

File: crates/bevy_transform/src/systems.rs (hunk 2 above)
Comment (nicopap) [reply crates/bevy_transform/src/systems.rs:28]: Specifically because they are not disjoint it makes it difficult to merge the two. I could use a `ParamSet`, but then I felt like a distinct system was better.

If there was a `NotChanged<Foo>` filter, it could allow running the two systems in parallel though.

Comment (lewiszlw) [inline crates/bevy_transform/src/systems.rs:28]: This should be added in `transform_propagate_system_set` for third party plugin use.

Comment (nicopap) [reply crates/bevy_transform/src/systems.rs:28]: @james7132 would you find a `ParamSet` in a single system an acceptable stop gap? I feel this PR shouldn't be blocked on the hypothetical addition of `NotChanged`.

File: crates/bevy_transform/src/systems.rs (hunk 1 above)
Comment (nicopap) [reply crates/bevy_transform/src/systems.rs:61]: Looks like the entities in `World::removed_components` are stored in a `Vec`. It's unlikely that it's possible to outperform sorting + binary search. I expect the `Vec` to be always relatively small and not spill out of cache.

File: crates/bevy_transform/src/systems.rs (hunk 2 above)
Comment (rparrett) [reply crates/bevy_transform/src/systems.rs:28]: As of #7097, you could do

```rs
pub fn sync_simple_transforms_orphaned(
    mut query: Query<(Ref<Transform>, &mut GlobalTransform), Without<Children>>,
    orphaned: RemovedComponents<Parent>,
) {
    let mut iter = query.iter_many_mut(orphaned.iter());
    while let Some((transform, mut global_transform)) = iter.fetch_next() {
        if transform.is_changed() {
            continue;
        }
        *global_transform = GlobalTransform::from(*transform);
    }
}
```

File: crates/bevy_transform/src/systems.rs (hunk 1 above)
Comment (nicopap) [reply crates/bevy_transform/src/systems.rs:57]: This is non-actionable. If performance is a concern, could you point to ways of benchmarking testing for regression?

Since  the current transform benchmarks do not have parent/child removal/addition, I doubt it would help find any differences.

File: crates/bevy_transform/src/systems.rs [hunk 3]
```diff
@@ -10,16 +11,29 @@ use bevy_hierarchy::{Children, Parent};
...
     query
+        .p0()
         .par_iter_mut()
         .for_each_mut(|(transform, mut global_transform)| {
             *global_transform = GlobalTransform::from(*transform);
         });
+    // updated orphaned entities
+    let mut query = query.p1();
+    let mut iter = query.iter_many_mut(orphaned.iter());
+    while let Some((transform, mut global_transform)) = iter.fetch_next() {
```
Comment (james7132) [inline crates/bevy_transform/src/systems.rs:32]:
```suggestion
    for (transform, mut global_transform) in iter {
```
Why are we using `fetch_next` over `Iterator::next` here?

**Review by james7132 — APPROVED** [review]
LGTM other than this one nit.

File: crates/bevy_transform/src/systems.rs (hunk 3 above)
Comment (nicopap) [reply crates/bevy_transform/src/systems.rs:32]: It's because `QueryManyIter` only implements `Iterator` if the items are `ReadOnly`, and here we need mutable access to `GlobalTransform`. The `iter_many_mut` kinda implies that without saying why https://dev-docs.bevyengine.org/bevy/ecs/system/struct.Query.html#method.iter_many_mut

Check out `impl QueryManyIter` and `impl Iterator for QueryManyIter` for an explanation. Not sure the restriction is actually correctly justified, but I think that would out of scope for this PR.

Comment (devil-ira) [reply crates/bevy_transform/src/systems.rs:32]: If the list of entities given to `iter_many_mut` contains duplicate entities then an `Iterator` could mutably alias (eg. using `collect()`), so we return our own 'lending' iterator instead that only allows access to one item at a time

File: crates/bevy_transform/src/systems.rs (hunk 1 above)
Comment (JoJoJet) [reply crates/bevy_transform/src/systems.rs:56]: > Another option is to store `orphaned` in a `Local` to avoid allocation at each frame. Of course, since the iterator returned by `RemovedComponents::iter` is `Cloned<slice::Iter<Entity>>`, I don't expect it to allocate when it's empty. And storing the `Vec` in a `Local` smells memory leak.

This would be a nice (but not necessary) optimization. It would just allow the system to reuse a single allocation, it shouldn't cause a memory leak or anything bad.

File: crates/bevy_transform/src/systems.rs [hunk 4]
```diff
@@ -165,6 +183,59 @@ mod test {
...
+        let child = commands.spawn(offset_transform(5.5)).id();
+        commands.entity(parent).set_parent(root);
+        commands.entity(child).set_parent(parent);
+        command_queue.apply(&mut world);
+        schedule.run(&mut world);
+
+        assert_ne!(
+            world.get::<GlobalTransform>(parent).unwrap(),
+            &GlobalTransform::from(Transform::IDENTITY)
+        );
```
Comment (JoJoJet) [inline crates/bevy_transform/src/systems.rs:212]: I don't understand why this check passes. This is after transform propagation has been run for the first time, but before `parent`'s parent has been removed. Shouldn't `parent`'s translation be `3.3 + 4.4`?

**Review by JoJoJet — COMMENTED** [review]
Good fix, there's something I'm not sure about yet though.

File: crates/bevy_transform/src/systems.rs (hunk 1 above)
Comment (nicopap) [reply crates/bevy_transform/src/systems.rs:56]: My worry is that orphaning happens in bursts (think of unloading/loading scenes), so we end up with reserved memory for the worst case while the `Vec` is only fully used one frame every minutes/hours.

I think a cool thing bevy could provide is some sort of smart `Local<Vec<T>>` that clears intelligently. I think it would benefit the engine itself already.

File: crates/bevy_transform/src/systems.rs (hunk 4 above)
Comment (nicopap) [reply crates/bevy_transform/src/systems.rs:212]: This tests that when I run `schedule.run(&mut world)`, the `GlobalTransform` is indeed updated (ie: the propagation systems have run) so that the following assertions are not just an accident due to transform never changing. I had to think about this a bit, it is indeed really weird.

File: crates/bevy_transform/src/systems.rs [hunk 5]
```diff
@@ -2,23 +2,38 @@ use crate::components::{GlobalTransform, Transform};
...
+    mut query: ParamSet<(
+        Query<
+            (&Transform, &mut GlobalTransform),
+            (Changed<Transform>, Without<Parent>, Without<Children>),
+        >,
+        Query<(Ref<Transform>, &mut GlobalTransform), Without<Children>>,
+    )>,
+    mut orphaned: RemovedComponents<Parent>,
 ) {
     query
```
Comment (JoJoJet) [inline crates/bevy_transform/src/systems.rs:23]:
```suggestion
    // Update changed entities.
    query
```

File: crates/bevy_transform/src/systems.rs [hunk 6]
```diff
@@ -2,23 +2,38 @@ use crate::components::{GlobalTransform, Transform};
...
+        .p0()
         .par_iter_mut()
         .for_each_mut(|(transform, mut global_transform)| {
             *global_transform = GlobalTransform::from(*transform);
         });
+    // updated orphaned entities
```
Comment (JoJoJet) [inline crates/bevy_transform/src/systems.rs:29]:
```suggestion
    // Update orphaned entities.
```

**Review by JoJoJet — APPROVED** [review]

**Review by devil-ira — APPROVED** [review]
