### PR TITLE
don't panic on unknown ambiguity

### LINKED ISSUE #7949: Panic in bevy_ecs, probably related to windowing
The following code causes bevy to panic
```rust
use bevy::prelude::*;

fn main() {
    App::new()
        .add_plugins(DefaultPlugins.set(WindowPlugin {
            primary_window: Some(Window::default()),
            exit_condition: bevy::window::ExitCondition::OnPrimaryClosed,
            close_when_requested: true,
        }))
        .run();
}
```

```
2023-03-07T15:16:55.444347Z  INFO bevy_winit::system: Creating new window "Bevy App" (0v0)
2023-03-07T15:16:55.445151Z  INFO winit::platform_impl::platform::x11::window: Guessed window scale factor: 1
2023-03-07T15:16:55.483296Z  INFO bevy_render::renderer: AdapterInfo { name: "AMD Radeon RX 480 Graphics (RADV POLARIS10)", vendor: 4098, device: 26591, device_type: DiscreteGpu, driver: "radv", driver_info: "Mesa 23.0.0", backend: Vulkan }
2023-03-07T15:16:56.321835Z  INFO bevy_diagnostic::system_information_diagnostics_plugin::internal: SystemInfo { os: "Linux rolling Arch Linux", kernel: "6.2.2-arch1-1", cpu: "Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz", core_count: "4", memory: "31.3 GiB" }
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_ecs-0.10.0/src/schedule/schedule.rs:1146:56
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

In Cargo.toml, set dependencies to only `bevy = "0.10.0"` and start with `cargo run`

### PR DESCRIPTION
**Pull request by mockersf**
# Objective

- Fixes #7949
- don't panic

## Solution

- #7949 happens because the `exit_on_all_closed` system is used to declare an ambiguity with another, but it isn't added if the exit condition is not `OnPrimaryClosed`
- while we could fix all cases in Bevy, having ambiguities with unknown systems can be something that happens with optional / third party plugins
- allow ambiguity with things that don't exist

### CODE REVIEW

**Review by alice-i-cecile — APPROVED** [review]
Yeah I'm happy to make that a little less twitchy.

File: crates/bevy_ecs/src/schedule/schedule.rs [hunk 1]
```diff
@@ -1138,18 +1138,18 @@ impl ScheduleGraph {
                     ambiguous_with_flattened.add_edge(lhs, rhs, ());
                 }
                 (NodeId::Set(_), NodeId::System(_)) => {
-                    for &lhs_ in set_systems.get(&lhs).unwrap() {
+                    for &lhs_ in set_systems.get(&lhs).unwrap_or(&vec![]) {
```
Comment (james7132) [inline crates/bevy_ecs/src/schedule/schedule.rs:1141]: It's unclear if this allocates or not. Could we use `&Vec::new()` instead?

**Review by james7132 — CHANGES_REQUESTED** [review]

File: crates/bevy_ecs/src/schedule/schedule.rs (hunk 1 above)
Comment (nicoburns) [reply crates/bevy_ecs/src/schedule/schedule.rs:1141]: FWIW, `vec![]` with no parameters expands to `Vec::new()` and therefore doesn't allocate (see https://doc.rust-lang.org/src/alloc/macros.rs.html#42) (but by all means change it if you think it's clearer).

Comment (alice-i-cecile) [reply crates/bevy_ecs/src/schedule/schedule.rs:1141]:
```suggestion
                    for &lhs_ in set_systems.get(&lhs).unwrap_or(&Vec::new()) {
```

I think this is slightly clearer but I super don't care :p

Comment (mockersf) [reply crates/bevy_ecs/src/schedule/schedule.rs]: 🤷

**Review by james7132 — APPROVED** [review]
