### PR TITLE
AssetMetaMode

### LINKED ISSUE #10157: Asset loading on the Web produces many 404 errors for `.meta` files
## Bevy version

5733d2403

## What you did

Ran any example that loads assets under WASM / WebGL with:

```bash
cargo run -p build-wasm-example -- $EXAMPLE_NAME_HERE && python3 -m http.server --directory examples
/wasm
```

## What went wrong

Got barraged with 404 error messages in the web inspector with the page trying to load `.meta` files for every asset loaded.

## Additional information

image

- Looks like with #8624 we now look for `.meta` files for every asset that we load
- On native this is a non issue, however on the web we do a bunch of requests, which both spam the console with 404 errors and also potentially slow down loading of the files that actually exist

### PR DESCRIPTION
**Pull request by cart**
# Objective

Fixes #10157

## Solution

Add `AssetMetaCheck` resource which can configure when/if asset meta files will be read:

```rust
app
  // Never attempts to look up meta files. The default meta configuration will be used for each asset.
  .insert_resource(AssetMetaCheck::Never)
  .add_plugins(DefaultPlugins)
```

This serves as a band-aid fix for the issue with wasm's `HttpWasmAssetReader` creating a bunch of requests for non-existent meta, which can slow down asset loading (by waiting for the 404 response) and creates a bunch of noise in the logs. This also provides a band-aid fix for the more serious issue of itch.io deployments returning 403 responses, which results in full failure of asset loads.

If users don't want to include meta files for all deployed assets for web builds, and they aren't using meta files at all, they should set this to `AssetMetaCheck::Never`.

If users do want to include meta files for specific assets, they can use `AssetMetaCheck::Paths`, which will only look up meta for those paths.

Currently, this defaults to `AssetMetaCheck::Always`, which makes this fully non-breaking for the `0.12.1` release. _**However it _is_ worth discussing making this `AssetMetaCheck::Never` by default**_, given that I doubt most people are using meta files without the Asset Processor enabled. This would be a breaking change, but it would make WASM / Itch deployments work by default, which is a pretty big win imo. The downside is that people using meta files _without_ processing would need to manually enable `AssetMetaCheck::Always`, which is also suboptimal.

When in `AssetMetaCheck::Processed`, the meta check resource is ignored, as processing requires asset meta files to function. 

In general, I don't love adding this knob as things should ideally "just work" in all cases. But this is the reality of the current situation.

---

## Changelog

- Added `AssetMetaCheck` resource, which can configure when/if asset meta files will be read

### CODE REVIEW

**Comment by alice-i-cecile** [comment]
> Currently, this defaults to AssetMetaMode::Always, which makes this fully non-breaking for the 0.12.1 release. However it is worth discussing making this AssetMetaMode::Never by default, given that I doubt most people are using meta files without the Asset Processor enabled. This would be a breaking change, but it would make WASM / Itch deployments work by default, which is a pretty big win imo. The downside is that people using meta files without processing would need to manually enable AssetMetaMode::Always, which is also suboptimal.

IMO the strategy here is to put the correct config in the Bevy template used for the jam, but keep the existing default behavior. I don't think changing this is the right choice long-term, otherwise I'd be more okay with swapping the default now.

File: crates/bevy_asset/src/server/mod.rs [hunk 1]
```diff
@@ -811,44 +825,57 @@ impl AssetServer {
...
-                    AssetActionMinimal::Process { .. } => {
-                        return Err(AssetLoadError::CannotLoadProcessedAsset {
-                            path: asset_path.clone_owned(),
-                        })
-                    }
-                    AssetActionMinimal::Ignore => {
-                        return Err(AssetLoadError::CannotLoadIgnoredAsset {
+        let read_meta = match &self.data.meta_mode {
+            AssetMetaMode::Always => true,
+            AssetMetaMode::Paths(paths) => paths.contains(asset_path),
```
Comment (robojeb) [inline crates/bevy_asset/src/server/mod.rs:830]: Requiring a `HashSet` containing all the exact paths of assets you want `.meta` files for feels incredibly cumbersome. 

It feels like this would want to support something like [`globset`](https://crates.io/crates/globset) or similar.  

An alternative would be to just expose this at the `AssetSource` level, and expose a new source `metaless://` (bikeshedding required). Then all the configuration for which Assets need `.meta` files moves to the asset use location instead of when the loader is configured. This reduces the chance of forgetting to add something to the set.

Comment (robojeb) [reply crates/bevy_asset/src/server/mod.rs:830]: Bike shedding my own comment if `AssetSources` could take parameters you could have `source+meta://` and `source-meta://` for explicit use and then allow global default configuration at the plugin level (Always vs Never mode)

File: crates/bevy_asset/src/lib.rs [hunk 2]
```diff
@@ -75,6 +76,8 @@ pub struct AssetPlugin {
     pub watch_for_changes_override: Option<bool>,
     /// The [`AssetMode`] to use for this server.
     pub mode: AssetMode,
+    /// How meta files should be accessed. This will be ignored for processed assets, as this mode require meta files.
+    pub meta_mode: AssetMetaMode,
```
Comment (SludgePhD) [inline crates/bevy_asset/src/lib.rs:80]: Adding a field to a struct that isn't marked `#[non_exhaustive]` is a breaking change. The signature change of `AssetServer::new` is also breaking. Perhaps this should be an overridable `Resource` instead?

File: crates/bevy_asset/src/lib.rs [hunk 3]
```diff
@@ -101,13 +104,26 @@ pub enum AssetMode {
     Processed,
 }
 
+/// Configures how asset meta will be used.
+#[derive(Debug, Default, Clone)]
+pub enum AssetMetaMode {
+    /// Always assume assets have meta files.
+    #[default]
+    Always,
```
Comment (mockersf) [inline crates/bevy_asset/src/lib.rs:112]: this should then crash if the meta file is missing instead of defaulting

File: crates/bevy_asset/src/server/mod.rs (hunk 1 above)
Comment (cart) [reply crates/bevy_asset/src/server/mod.rs:830]: I almost didn't include the hashset at all. This is intended to be a "roughly non-breaking patch fix". The idea behind the hashset is not to be a perfect / recommended solution, but rather a simple short term "break glass" solution for cases that absolutely need it.

General theory is that at this point, most people are either using no meta files, or they are using asset processing (and therefore everything has meta files). The hashset covers the middle ground case (only needed on WASM) while we sort out the right long term fix.

Comment (robojeb) [reply crates/bevy_asset/src/server/mod.rs:830]: That seems reasonable, I somehow glossed over the "patch fix" information in the description. 

I'd be happy to circle back around on the topic if/when you look at `.meta` file configuration again in the future.

**Comment by DGriffin91** [comment]
Will the `AssetMetaMode::Paths` also work on wasm / itch.io? Is it planned (or already the case) that meta files are usable on the web?

**Comment by cart** [comment]
> Will the AssetMetaMode::Paths also work on wasm / itch.io? Is it planned (or already the case) that meta files are usable on the web?

Yup this works on wasm / thats why it exists in the first place (as this workaround isn't needed if you aren't deploying to wasm / trying to prevent logspam / trying to avoid errors on platforms like itch that return non 404 error messages).

File: crates/bevy_asset/src/lib.rs (hunk 3 above)
Comment (cart) [reply crates/bevy_asset/src/lib.rs:112]: Fair point. Imo crashing isn't the desired behavior here. The "opt in meta file" pattern is very nice. I'll adjust the name and docs to indicate that it will always _check_.

File: crates/bevy_asset/src/lib.rs (hunk 2 above)
Comment (cart) [reply crates/bevy_asset/src/lib.rs]: Hmmm yeah fair points. A bit regrettable that we need to break the people adopting this feature (which doesn't yet exist) in 0.13, but thats _probably_ better than breaking someone in a patch release.

**Comment by cart** [comment]
Per the discussion above, I have made this non breaking by switching the meta check AssetPlugin field to a resource. I've also added a new AssetServer constructor to avoid breaking changes to the existing constructor.

**Comment by cart** [comment]
@P13L0v3r I've just added a usage example to the description. Hope that helps!

**Comment by miketwenty1** [comment]
For anyone else who is still getting 404's after this change, make sure you put `app.insert_resource(AssetMetaCheck::Never)` before the default plugins when configuring the app like in the description example. I didn't realize ordering mattered 🙃

**Comment by alice-i-cecile** [comment]
#1255 strikes again :(

**Comment by janhohenheim** [comment]
As someone who just lost quite a bit of time to this while trying to upload to itch.io, I second the suggestion to make this the default for 0.13 (if it isn't already). 
The main issue for me was that the fix is currently hard to google. In the end, I had to search for "png.meta" in the Discord to find this PR :/

**Comment by benlloyd50** [comment]
If you're like me you may have noticed AssetMetaCheck in bevy `v0.16.0+` is no longer a resource. So just, 
```
app.add_plugins((
    DefaultPlugins
        .set(AssetPlugin { meta_check: AssetMetaCheck::Never, ..default() }
));
```
