### PR TITLE
fix `insert_reflect` panic caused by `clone_value`

### LINKED ISSUE #10590: `insert_reflect` panics when inserting component
## Bevy version

0.12.0

## What you did

Registered a type, create it from somewhere and then send it by event.
```rust
bullet_ec.insert_reflect(event.bullet_type.clone_value());
```

## What went wrong

```
thread 'main' panicked at T:\packages\cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_ecs-0.12.0\src\reflect\entity_commands.rs:197:9:
Could not get type registration (for component type bevy_reflect::DynamicStruct) because it doesn't exist in the TypeRegistry.
```

## Additional information

You won't always get the real type path from `reflect_type_path`. The `clone_value()` overrides type info into "bevy_reflect::DynamicStruct". 

```rust
println!("origin: {:?}, cloned: {:?}", bullet_type.reflect_type_path(), bullet_type.clone_value().reflect_type_path());

// prints
// origin: "rogue_shooting::bullets::LaneShot", cloned: "bevy_reflect::DynamicStruct"
```

One feasible workaround is [dyn-clone](https://docs.rs/dyn-clone/latest/dyn_clone/). 
```rust
trait CloneReflect: Reflect + DynClone {}
dyn_clone::clone_trait_object!(CloneReflect);
```
Implement this for your component. They will be perfectly cloned now by using `.clone()`.

### PR DESCRIPTION
**Pull request by hxYuki**
# Objective

- `insert_reflect` relies on `reflect_type_path`, which doesn't gives the actual type path for object created by `clone_value`, leading to an unexpected panic. This is a workaround for it.
- Fix #10590 

## Solution

- Tries to get type path from `get_represented_type_info` if get failed from `reflect_type_path`.

---

## Defect remaining

- `get_represented_type_info` implies a shortage on performance than using `TypeRegistry`.

### CODE REVIEW

File: crates/bevy_ecs/src/reflect/entity_commands.rs [hunk 1]
```diff
@@ -193,7 +193,12 @@ fn insert_reflect(
     let Some(mut entity) = world.get_entity_mut(entity) else {
         panic!("error[B0003]: Could not insert a reflected component (of type {}) for entity {entity:?} because it doesn't exist in this World.", component.reflect_type_path());
     };
-    let Some(type_registration) = type_registry.get_with_type_path(type_info) else {
+    let Some(type_registration) = type_registry.get_with_type_path(type_info).or_else(|| {
```
Comment (Shatur) [inline crates/bevy_ecs/src/reflect/entity_commands.rs:196]: I would suggest to just use `get_represented_type_info` in line 192.

**Review by Shatur — CHANGES_REQUESTED** [review]
Encountered this bug too, thanks for the fix.

File: crates/bevy_ecs/src/reflect/entity_commands.rs (hunk 1 above)
Comment (hxYuki) [reply crates/bevy_ecs/src/reflect/entity_commands.rs:196]: After a bench I found that it doesn't make much influence in performance using `get_represented_type_info` in this case. Cloning costs time much more.
For 10k iters
No cloning: `reflect_type` 22 μs, `get_represented_type_info` 39 μs
dyn clone: `reflect_type` 365 μs, `get_represented_type_info` 379 μs
clone_value: 1,177 μs

It should be OK just using `get_represented_type_info`.

File: crates/bevy_ecs/src/reflect/entity_commands.rs [hunk 2]
```diff
@@ -189,15 +189,15 @@ fn insert_reflect(
     type_registry: &TypeRegistry,
     component: Box<dyn Reflect>,
 ) {
-    let type_info = component.reflect_type_path();
+    let type_info = component.get_represented_type_info().expect("Could not get type information for component type because it doesn't represent any type.").type_path();
```
Comment (Shatur) [inline crates/bevy_ecs/src/reflect/entity_commands.rs:192]: Let's use [recommended panic message style](https://doc.rust-lang.org/std/result/enum.Result.html#recommended-message-style) and rename into `type_path`. Also could you inline `type_path` into messages like this: "{type_path}"?
```suggestion
    let type_path = component.get_represented_type_info().expect("component should represend a type").type_path();
```

File: crates/bevy_ecs/src/reflect/entity_commands.rs [hunk 3]
```diff
@@ -189,15 +189,18 @@ fn insert_reflect(
     type_registry: &TypeRegistry,
     component: Box<dyn Reflect>,
 ) {
-    let type_info = component.reflect_type_path();
+    let type_path = component
+        .get_represented_type_info()
+        .expect("component should represent a type.")
+        .type_path();
```
Comment (Shatur) [inline crates/bevy_ecs/src/reflect/entity_commands.rs:195]: One last suggestion. Let's split into two variables: `type_info` and `type_path`.

**Review by Shatur — APPROVED** [review]

**Review by cart — APPROVED** [review]
