### PR TITLE
Fix https / http asset loader on WASM

### LINKED ISSUE #21280: WebAssetPlugin does not build on wasm32-unknown-unknown
> i've encountered compilation errors trying to use WebAssetPlugin when compiling for wasm32-unknown-unknown on the release-0.17.0 branch (this is also true on main tho):
> 
> [this line](https://github.com/bevyengine/bevy/blob/release-0.17.0/crates/bevy_asset/src/io/web.rs#L7) unconditionally imports blocking::unblock but blocking [is configured out](https://github.com/bevyengine/bevy/blob/release-0.17.0/crates/bevy_asset/Cargo.toml#L95) when target_arch = "wasm32"
> 
> there's also a reference to a temporary value returned [here](https://github.com/bevyengine/bevy/blob/release-0.17.0/crates/bevy_asset/src/io/web.rs#L121)

Courtesy of `@nesyt` [on Discord](https://discord.com/channels/691052431525675048/749332104487108618/1422220775993114726).

### PR DESCRIPTION
**Pull request by alice-i-cecile**
# Objective

Our `web_asset` example does not build on Wasm. Ironic.

As reported in #21280, there are a few problems:

1. Imports are broken: one hard error and a few warnings.
2. `HttpWasmAssetReader` needs a `+ use<'>` to conform to the Rust 2024 edition (unreported, but discovered)
3. We're returning a reference to a temporary value, which is ultimately caused by 2

## Solution

1. Move the imports into the correct feature-gated block.
2. Slap some `+ use<'>` on the function definition like the compiler told me to. This fixes the "returning a reference to a temporary value" problem, as we're no longer implicitly capturing.

Fixes #21280.

Special thanks to @kristoff3r for pointing out my mistake!

## Testing

I've tested this PR using `bevy run --features https --example web_asset web` via the bevy_cli. Because of changes to `getrandom`, this was non-trivial to build for web manually.

### CODE REVIEW

**Comment by alice-i-cecile** [comment]
@mrchantey, do you have any suggestions on the correct fix here?

File: crates/bevy_asset/src/io/wasm.rs [hunk 1]
```diff
@@ -53,7 +53,10 @@ fn js_value_to_err(context: &str) -> impl FnOnce(JsValue) -> std::io::Error + '_
 
 impl HttpWasmAssetReader {
     // Also used by [`WebAssetReader`](crate::web::WebAssetReader)
-    pub(crate) async fn fetch_bytes(&self, path: PathBuf) -> Result<impl Reader, AssetReaderError> {
+    pub(crate) async fn fetch_bytes(
+        &self,
+        path: PathBuf,
+    ) -> Result<impl Reader + use<'_>, AssetReaderError> {
```
Comment (kristoff3r) [inline crates/bevy_asset/src/io/wasm.rs]: Using `use<'_>` elides the lifetime to match that of `&self`, but here self is a stack variable which makes borrow checking fail. Instead you need an empty `use<>`.

```suggestion
    ) -> Result<impl Reader + use<>, AssetReaderError> {
```

**Review by mockersf — APPROVED** [review]

**Review by kristoff3r — APPROVED** [review]
