### PR TITLE
Don't auto create assets folder

### LINKED ISSUE #11208: AssetPlugin always creates empty assets directory
## Bevy version

0.12.1 and [b6da40c](https://github.com/bevyengine/bevy/commit/b6da40cfe6d3686ef01b8708dc8e6f5c66229bdc)

## What you did

```rust
App::new().add_plugins(AssetPlugin::default());
```
## What went wrong

Merely adding AssetPlugin to an app creates an assets directory. Projects that don't load assets from the file system are left with an empty folder. This folder was not auto created in 0.11.

## Additional information

Looks like this behavior was added in #8624.
The folder is created [here](https://github.com/bevyengine/bevy/blob/3f535d54eb125130a79cbd5d7e5cd76fe13e18df/crates/bevy_asset/src/io/file/mod.rs#L48-L53).

### PR DESCRIPTION
**Pull request by nvdaz**
# Objective

- Don't automatically create an assets folder
- resolves #11208

## Solution

- Removes directory creation from file reader.
- Clearer panic when using file watcher and asset folder doesn't exist

### CODE REVIEW

File: crates/bevy_asset/src/io/source.rs [hunk 1]
```diff
@@ -43,7 +43,7 @@ impl<'a> AssetSourceId<'a> {
     }
 
     /// Returns [`None`] if this is [`AssetSourceId::Default`] and [`Some`] containing the
-    /// the name if this is [`AssetSourceId::Name`].  
+    /// the name if this is [`AssetSourceId::Name`].
```
Comment (alice-i-cecile) [inline crates/bevy_asset/src/io/source.rs:46]:
```suggestion
    /// name if this is [`AssetSourceId::Name`].
```

**Review by alice-i-cecile — CHANGES_REQUESTED** [review]
Should we document that `FileAssetReader::new` does not create a directory?

**Comment by nvdaz** [comment]
I feel it's probably unnecessary since I personally wouldn't expect a file _reader_ to do create anything. It is much more surprising as it is right now IMO–creating a directory undocumented.

**Review by alice-i-cecile — APPROVED** [review]

**Comment by alice-i-cecile** [comment]
@thepackett, could you review this little PR? Does this make sense with your understanding of the asset lifecycle?

**Review by thepackett — CHANGES_REQUESTED** [review]
Honestly I can't say I support this change for a couple reasons. 

I think creating the asset directory is the appropriate default behavior, since if it didn't create the asset directory automatically then you would manually have to create the folder and work your way through any possible errors or misunderstandings along the way.

Secondly, this behavior can be disabled. When the AssetPlugin [starts](https://github.com/bevyengine/bevy/blob/cc2a77b5c5517ad1d93325ae31c4638fe4ffc5b4/crates/bevy_asset/src/lib.rs#L150) it checks to see if any `AssetSourceBuilder`s are in the `AssetSourceBuilders` resource, and if there aren't any then it uses the default AssetSources, which includes the file source. Thus you can disable this by providing your own `AssetSourceBuilder`s before adding the Asset Plugin as per this [example](https://github.com/bevyengine/bevy/blob/cf70f53227a1f83298a1c031364cbe373805bf51/examples/asset/custom_asset_reader.rs#L50).

As for the documentation and panic error message, this is good and I will always approve of better error messages and documentation.

**Comment by nvdaz** [comment]
I see what you're saying, and I might even agree if `FileAssetReader` wasn't the default, that way creating the folder would be explicitly opt-in. But it's not and I think the current behavior is  _really_ unexpected for those who aren't aware that Bevy automatically does this. I discovered this because there was an empty folder in my project directory, so I naturally tried deleting it to no avail... I originally hadn't even suspected Bevy because in my head, a library doesn't update the file system unless I explicitly ask.

In my opinion, automatically creating an assets folder without context isn't very helpful either. It wouldn't be obvious to a new user why the folder exists or how to import assets just from it existing. They would still have to discover `AssetServer::load`, which helpfully tells the user the full asset path searched for if not found.

And just to clarify since I think it might be unclear: this doesn't cause a panic with just the default features and no assets folder. Bevy runs just fine without an assets folder. The updated panic message only happens if the user enables the `file_watcher` feature, so it would be pretty odd if they did this without having an assets folder (though the panic would tell them it was  caused by this feature and the assets folder not being found).

I would definitely agree, though, that better documentation would be useful. I just feel it wouldn't be very helpful here as beginners would probably not look at the internals. There should probably be a section on asset loading in The Bevy Book. I could add a comment here though, if required, just feels a little superfluous to say that a file reader does not create a directory.

**Comment by AxiomaticSemantics** [comment]
I'm a vote for the panic behaviour as is. A potential follow-up could be having bevy_assets use a build.rs and allowing to opt out.

File: crates/bevy_asset/src/io/source.rs [hunk 2]
```diff
@@ -486,7 +486,7 @@ impl AssetSource {
                     sender,
                     file_debounce_wait_time,
                 )
-                .unwrap(),
+                .unwrap_or_else(|e| panic!("Failed to create file watcher: {}", e)),
```
Comment (nicopap) [inline crates/bevy_asset/src/io/source.rs:489]: This does the same, but is shorter <https://doc.rust-lang.org/stable/std/result/enum.Result.html#method.expect>
```suggestion
                .expect("Failed to create file watcher"),
```

**Review by nicopap — APPROVED** [review]
I'd prefer if bevy did not silently create file directories, so I'm in favor of merging this.

**Comment by thepackett** [comment]
I know I'm somewhat repeating myself here, but I don't believe that the defaults for plugins are unreasonable. Bevy is built to be as modular and as flexible as possible so that you can really dig into the engine and modify and configure it however you want. However, that flexibility comes at the price of complexity for the developer.  The purpose of the default behavior is to provide a decent starting point for the majority of users so they can get up and running as quickly as possible without having to spend hours configuring every plugin they use in every project they create. I think that the AssetPlugin using the File AssetSource by default is reasonable, and creating the directory that all assets must be placed in for the File AssetSource to work by default is also reasonable.

File: crates/bevy_asset/src/io/source.rs (hunk 2 above)
Comment (nvdaz) [reply crates/bevy_asset/src/io/source.rs]: thanks!

**Comment by nvdaz** [comment]
While I acknowledge the reasoning behind this, I'd contend that it extends beyond what one might reasonably expect, especially when Bevy is installed as a dependency via Cargo (since it does not own the project and thus shouldn't make assumptions imo). Such behavior might be more fitting for a standalone Bevy editor (i.e. like Unreal/Unity), where ownership is clear.

I think my previous comment made my perspective clear beyond that. It ultimately boils down to weighing the cost of silently creating the assets folder against the convenience of it always being there by default.

**Comment by thepackett** [comment]
> "I think my previous comment made my perspective clear beyond that. It ultimately boils down to weighing the cost of silently creating the assets folder against the convenience of it always being there by default."

Agreed. We've both made our case and it really comes down to the core vision for bevy, which is probably why this has been tagged as controversial. This means that Cart (or two SMEs, which I don't believe we have for Bevy Asset) needs to take a look at this to decide.

**Comment by nvdaz** [comment]
Yep. I interpreted the behavior as a bug since it didn't happen in 0.11 or previous and the change wasn't documented. Hadn't intended to comment on Bevy's philosophy, but I guess that's where this wound up!

In case it's decided that this should be the new default, I'd like to see a warning because it's still unexpected.

It would be great if @cart could comment, especially since the behavior was added in https://github.com/bevyengine/bevy/commit/5eb292dc10b99e13c6f606b7d9f0018f59052574.

**Comment by mockersf** [comment]
I would be for not creating the asset folder. This should be created by the project template / editor, or by the user explicitly

**Review by mockersf — APPROVED** [review]

**Comment by cart** [comment]
> I would be for not creating the asset folder. This should be created by the project template / editor, or by the user explicitly

Agreed!

**Review by cart — APPROVED** [review]
