### PR TITLE
Quality-of-life updates for running CI locally

### LINKED ISSUE #12206: Don't abort CI checks on first error
## What problem does this solve or what need does it fill?

When working on complex PRs like #12163, it's frustrating to fix all of the errors reported by CI, only to be met with another round of failures in a follow-up crate.

## What solution would you like?

Pass the `--keep-going` flag to CI. See https://github.com/rust-lang/cargo/issues/10496 for the tracking issue. Apparently this is now stable as of Rust 1.74: https://doc.rust-lang.org/cargo/commands/cargo-build.html#option-cargo-build---keep-going

It looks like for `cargo test`, we also need to pass in `--no-fail-fast`: https://doc.rust-lang.org/cargo/commands/cargo-test.html#options

## What alternative(s) have you considered?

Always run CI repeatedly locally.

### PR DESCRIPTION
**Pull request by mweatherley**
# Objective

- Make running CI locally relatively less painful by allowing continuation after failure
- Fix #12206 

## Solution

Previously, `ci` would halt after encounting a failure (or shortly thereafter). For instance, if you ran `cargo run -p ci` and a single test within a CI check failed somewhere in the middle, you would never even reach many of the other tests within the check and certainly none of the CI checks that came afterward. This was annoying; if I am fixing issues with CI tests, I want to just see all of the issues up-front instead of having to rerun CI every time I fix something to see the next error. 

Furthermore, it is not infrequent (because of subtle configuration/system differences) to encounter spurious CI failures locally; previously, when these occurred, they would make the process of running CI largely pointless, since you would have to push your branch in order to see your actual CI failures from the automated testing service. 

Now, when running `ci` locally, we have a couple new tools to ameliorate these and provide a smoother experience:
- Firstly, there is a new optional flag `--keep-going` that can be passed while calling `ci` (e.g. `cargo run -p ci -- doc --keep-going`). It has the following effects:
    - It causes the `--keep-going` flag to be passed to the script's `cargo doc` and `cargo check` invocations, so that they do not stop when they encounter an error in a single module; instead, they keep going (!) and find errors subsequently.
    - It causes the `--no-fail-fast` flag to be passed to the script's `cargo test` invocations, to similar effect.
    - Finally, it causes `ci` itself not to abort after a single check fails; instead, it will run every check that was invoked.

Thus, for instance, `cargo run -p ci -- --keep-going` will run every CI check even if it encounters intermediate failures, and every such check will itself be run to completion.

- Secondly, we now allow multiple ordinary arguments to be passed to `ci`. For instance, `cargo -p ci -- doc test` now executes both the 'doc' checks and the 'test' checks. This allows the caller to run the tests they care about with fewer invocations of `ci`.

As of this PR, automated testing will remain unchanged. 

---

## Changelog

- tools/ci/src/main.rs refactored into staging and execution steps, since the previous control flow did not naturally support continuing after failure.
- Added "--keep-going" flag to `ci`.
- Added support for invoking `ci` with multiple arguments.

---

### Design considerations

I had originally split this into separate flags that controlled:
1. whether `--keep-going`/`--no-fail-fast` would be passed to the constituent commands
2. whether `ci` would continue after a component test failed

However, I decided to merge these two behaviors, since I think that, if you're in the business of seeing all the errors, you'll probably want to actually see all of the errors. One slightly annoying thing, however, about the new behavior with `--keep-going`, is that you will sometimes find yourself wishing that the script would pause or something, since it tends to fill the screen with a lot of junk. I have found that sending stdout to /dev/null helps quite a bit, but I don't think `cargo fmt` or `cargo clippy` actually write to stderr, so you need to be cognizant of that (and perhaps invoke the lints separately). 

~~Next, I'll mention that I feel somewhat strongly that the current behavior of `ci` for automated testing should remain the same, since its job is more like detecting that errors exist rather than finding all of them.~~ (I was convinced this could have value.) Orthogonally, there is the question of whether or not we might want to make this (or something similar) actually the default behavior and make the automated test script invoke some optional flags — it doesn't have to type with its hands, after all. I'm not against that, but I don't really want to rock the boat much more with this PR, since anyone who looks at the diff might already be a little incensed.

### CODE REVIEW

**Comment by alice-i-cecile** [comment]
I'd like to use --keep-going in the automated CI too :) It would be very helpful, both as an author who (occasionally!) makes mistakes, and as a reviewer trying to get PRs through with as few rounds of revision as possible.

**Review by alice-i-cecile — APPROVED** [review]
I'm happy with this in its current form: up to you if we enable --keep-going for CI in this PR or a follow-up.

**Comment by mweatherley** [comment]
> I'd like to use --keep-going in the automated CI too :) It would be very helpful, both as an author who (occasionally!) makes mistakes, and as a reviewer trying to get PRs through with as few rounds of revision as possible.

It is so! 

Also, now that that's the case, it might also be worth rewriting this a little so that --keep-going becomes the default behavior, but I suppose I'd prefer to do that in a follow-up.

**Comment by BD103** [comment]
> One slightly annoying thing, however, about the new behavior with `--keep-going`, is that you will sometimes find yourself wishing that the script would pause or something, since it tends to fill the screen with a lot of junk.

Would it be worth adding a `--quiet` flag that would hide all non-errors, to reduce this issue? (Separate PR, though, to not block this one.) Or perhaps `--message-format short` to make error messages single lines?

**Comment by mweatherley** [comment]
> Would it be worth adding a `--quiet` flag that would hide all non-errors, to reduce this issue? (Separate PR, though, to not block this one.) Or perhaps `--message-format short` to make error messages single lines?

I had the same thought; I haven't tried `--message-format short`, but I think that `--quiet` could be a great idea.

File: tools/ci/src/main.rs [hunk 1]
```diff
@@ -44,125 +61,300 @@ fn main() {
...
+            panic!("{failure_message}");
+        }
+    }
+
+    for (check, battery) in test_suite.into_iter() {
+        for ci_test in battery {
+            // Ensure that necessary environment variables are set
+            for (k, v) in ci_test.env_vars {
+                std::env::set_var(k, v);
+            }
```
Comment (BD103) [inline tools/ci/src/main.rs:335]: This will cause environmental variables to "leak" into other test suites. If for instance `PATH=../path/to/exe` was set for one test suite, it may mess up other test suites that also use the path.

Comment (mweatherley) [reply tools/ci/src/main.rs:335]: This is a good point! The original implementation did this too, but I should probably do better if I'm going to the effort of refactoring it. I'll throw in a little drop-hook abstraction to take care of this.

Comment (BD103) [reply tools/ci/src/main.rs]: You may be interested in [`Command::env`], which only sets the environmental variable for the child process. That way you don't have to worry about accidentally clearing one for the CI program.

[`Command::env`]: https://doc.rust-lang.org/stable/std/process/struct.Command.html#method.env

Comment (mweatherley) [reply tools/ci/src/main.rs]: Looks like xshell even lifts that command to `Cmd::env`, which should make using it a breeze! I'll switch my solution to use that later today (probably).

File: tools/ci/src/main.rs [hunk 2]
```diff
@@ -44,125 +61,295 @@ fn main() {
...
+            if !existing_fail_message.is_empty() {
+                existing_fail_message.push('\n');
+            }
+            existing_fail_message.push_str(failure_message);
+        } else {
+            panic!("{failure_message}");
+        }
+    }
+
+    for (check, battery) in test_suite.into_iter() {
```
Comment (BD103) [inline tools/ci/src/main.rs:330]:
```suggestion
    for (check, battery) in test_suite {
```

`into_iter()` is implied by the `for`-loop :)

**Review by BD103 — CHANGES_REQUESTED** [review]
I promise this is my final round of reviews :P

Overall, this code looks really good. I have a few requests and logic issues to point out, but very solid contribution.

File: tools/ci/src/main.rs (hunk 2 above)
Comment (mweatherley) [reply tools/ci/src/main.rs:330]: Hahaha, I have a bad habit of using `.iter()` and then changing it to `.into_iter()` when I actually want move semantics. I'm actually surprised the lints don't catch this!

**Comment by mockersf** [comment]
The goal of CI is to fail fast in a case of errors, and to not do extra works when possible.

Changing that would need more changes, to reduce dependency between jobs, to not cancel everything on the first job failed

And it seems not related to the PR title

File: tools/ci/src/main.rs [hunk 3]
```diff
@@ -44,125 +61,295 @@ fn main() {
...
-                    .map(|(s, _)| s)
-                    .fold(arguments[0].0.to_owned(), |c, v| c + ", " + v)
-            );
-            return;
+    let flag_arguments = [("--keep-going", Flag::KEEP_GOING)];
+
+    let (mut checks, mut flags) = (Check::empty(), Flag::empty());
+    for arg in std::env::args().skip(1) {
+        if let Some((_, flag)) = flag_arguments.iter().find(|(flag_arg, _)| *flag_arg == arg) {
+            flags.insert(*flag);
```
[the remark this answers is not in the document]
Comment (mweatherley) [reply tools/ci/src/main.rs:69]: I thought about this, but it didn't really seem like it was worth handling to me (at least for the regular arguments); I don't think it's not worth crashing over, at least. I guess my intuition here is that the regular arguments only ever add things to the test suite, so overspecifying doesn't ever do anything bad. And even if we added a redundancy warning of some kind, there are cases like `-- compile example-check` which are redundant in a more subtle way (and much more complex to deal with in general).

**Comment by mweatherley** [comment]
> The goal of CI is to fail fast in a case of errors, and to not do extra works when possible.
> 
> Changing that would need more changes, to reduce dependency between jobs, to not cancel everything on the first job failed
> 
> And it seems not related to the PR title

In that case, perhaps we should just not use `--keep-going` in automated testing for the time being, so that this can be litigated elsewhere?

File: tools/ci/src/main.rs [hunk 4]
```diff
@@ -44,125 +61,295 @@ fn main() {
...
+            checks.insert(*check);
+            continue;
+        }
+        println!(
+            "Invalid argument: {arg:?}.\nEnter one of: {}.",
+            arguments[1..]
+                .iter()
+                .map(|(s, _)| s)
+                .fold(arguments[0].0.to_owned(), |c, v| c + ", " + v)
+        );
```
[the remark this answers is not in the document]
Comment (mweatherley) [reply tools/ci/src/main.rs:82]: Glad you caught this! I meant to do that.

File: tools/ci/src/main.rs [hunk 5]
```diff
@@ -44,125 +61,295 @@ fn main() {
...
-                arguments[1..]
-                    .iter()
-                    .map(|(s, _)| s)
-                    .fold(arguments[0].0.to_owned(), |c, v| c + ", " + v)
-            );
-            return;
+    let flag_arguments = [("--keep-going", Flag::KEEP_GOING)];
+
+    let (mut checks, mut flags) = (Check::empty(), Flag::empty());
+    for arg in std::env::args().skip(1) {
```
[the remark this answers is not in the document]
Comment (mweatherley) [reply tools/ci/src/main.rs:67]: I'll leave some comments on this; certainly we should think about changing that in the future if any of the options themselves have parameters.

**Review by BD103 — APPROVED** [review]
Awesome, thank you!

**Comment by alice-i-cecile** [comment]
@mockersf I think this is no longer controversial: do you agree?

**Review by mockersf — APPROVED** [review]

**Comment by mockersf** [comment]
yes! thanks
