### PR TITLE
`animated_ui`: Animate `UiTransform::scale`, not `TextFont::font_size`

### LINKED ISSUE #22626: `AnimatedUi` example is broken
## Bevy version and features

bevy main

## What you did

```
cargo run --example animated_ui
```

## What went wrong

Nothing happens, just get a blank screen.

## Diagnosis

Suspect recent rendering changes mean the new font atlas image isn't ready the frame the layout is regenerated,  and then the next frame the layout is regenerated again with another new atlas image, and so on. Nothing ever gets rendered as long as it's a new font size.

### PR DESCRIPTION
**Pull request by ickshonpe**
# Objective

The animated_ui example interpolates the font size of the animated text entity, which rapidly generates gigabytes of font atlases.

Also, on main the text isn't even visible (and it still generates infinity font atlases). 

Fixes #22626, #22647

## Solution

Spawn the text with its font size set to the maximum value from the old animation curve. Then scale the text by interpolating the `UiTransform::scale` field, instead of the font size.

## Testing

```cargo run --example animated_ui```

The text should be visible and the memory usage should be stable.

### CODE REVIEW

File: examples/animation/animated_ui.rs [hunk 1]
```diff
@@ -110,7 +110,7 @@ fn setup(
         target_id: animation_target_id,
         graph: animation_graph,
         node_index: animation_node_index,
-    } = AnimationInfo::create(&mut animation_graphs, &mut animation_clips);
+    } = AnimationInfo::create(animation_graphs.as_mut(), animation_clips.as_mut());
```
Comment (ickshonpe) [inline examples/animation/animated_ui.rs:114]: Not sure why I had to change this, coercion suddenly isn't working?

**Comment by alice-i-cecile** [comment]
@ickshonpe can you tackle the merge conflicts quick?

**Comment by ickshonpe** [comment]
> @ickshonpe can you tackle the merge conflicts quick?

should be ready now, assuming the checks pass this time
