### PR TITLE
Fix(input focus): Bypass change detection in `process_recorded_focus_changes`

### LINKED ISSUE #23759: New FocusGained and FocusLost caused text cursor to stop blinking
## Bevy version and features

- 0.19-dev main branch 5330b01
- Using feature experimental_bevy_feathers

## \[Optional\] Relevant system information

- macOS Tahoe 26.3.1
- rustc 1.94.1

## What went wrong

The blinking cursor for text input in the feathers example stopped blinking.

I narrowed the cause down to commit ffa4b0e8d from PR #23723

### PR DESCRIPTION
**Pull request by kfc35**
# Objective

- Fixes #23759 
- `Res<InputFocus>` has `is_changed()` returning true every frame because `process_recorded_focus_changes` mutates it every frame now. Other systems that were relying on `InputFocus.is_changed()` for when the `current_focus` changes are no longer working as intended because of that change.

## Solution

- Bypass change detection whenever `ResMut<InputFocus>` is accessed in `process_recorded_focus_changes`.

## Testing

- `cargo run --example feathers --features=“experimental_bevy_feathers”`: text cursor now blinks correctly again
- `cargo run --example directional_navigation` verified via `println!` statement in `update_focus_display` that the system isn’t running on every frame (since it has a run condition `.run_if(|input_focus: Res<InputFocus>| input_focus.is_changed())`)

### CODE REVIEW

**Comment by kfc35** [comment]
Strange, there seems to have been an error uploading the screenshots and that’s why the pixel-eagle comment is there:
https://github.com/bevyengine/bevy/actions/runs/24297815059/job/70945786727
"jq: parse error: Invalid numeric literal at line 1, column 10”

Anyway, it can probably be ignored?

File: crates/bevy_input_focus/src/lib.rs [hunk 1]
```diff
@@ -107,11 +107,11 @@ pub struct InputFocus {
     /// The set of input focus changes that have been recorded since the last time [`FocusGained`] and [`FocusLost`] events were sent.
     ///
     /// These are stored in a first-in-first-out manner, so the most recent change is at the end of the vector.
-    recorded_changes: Vec<Option<Entity>>,
+    pub(crate) recorded_changes: Vec<Option<Entity>>,
```
Comment (alice-i-cecile) [inline crates/bevy_input_focus/src/lib.rs]: Why did this need to be made pub(crate)? It looks like we were accessing it before just fine.

**Comment by alice-i-cecile** [comment]
Aha, that's why!

File: crates/bevy_input_focus/src/lib.rs (hunk 1 above)
Comment (kfc35) [reply crates/bevy_input_focus/src/lib.rs]: oh wait this is a brain fart moment, I shall remove the `pub(crate)`s in a moment

File: crates/bevy_input_focus/src/lib.rs [hunk 2]
```diff
@@ -107,11 +107,11 @@ pub struct InputFocus {
     /// The set of input focus changes that have been recorded since the last time [`FocusGained`] and [`FocusLost`] events were sent.
     ///
     /// These are stored in a first-in-first-out manner, so the most recent change is at the end of the vector.
-    recorded_changes: Vec<Option<Entity>>,
```
Comment (alice-i-cecile) [inline crates/bevy_input_focus/src/lib.rs:110]: This is currently fully private, not `pub`. I think that's what your PR description thought they were? I'd prefer if even other parts of the crate cannot access this.

File: crates/bevy_input_focus/src/gained_and_lost.rs [hunk 3]
```diff
@@ -28,10 +28,16 @@ pub struct FocusLost {
...
+    // what is exposed to the user via `InputFocus::get`. Other fields are not exposed.
+    // So, we `bypass_change_detection` when accessing `focus` to avoid false signaling
+    // that we changed the `current_focus`. That is what users would care about if
+    // they were to be checking `focus.is_changed()`.
+
     // We need to track the previous focus as we go,
     // so we can send the correct FocusLost events when focus changes.
-    let mut previous_focus = focus.original_focus;
-    for change in focus.recorded_changes.drain(..) {
+    let mut previous_focus = focus.bypass_change_detection().original_focus;
```
Comment (alice-i-cecile) [inline crates/bevy_input_focus/src/gained_and_lost.rs]:
```suggestion
    let mut previous_focus = focus.original_focus;
```

Comment (alice-i-cecile) [reply crates/bevy_input_focus/src/gained_and_lost.rs]: This is a normal dereference, not a mutable one, so we're not triggering change detection :)

**Review by alice-i-cecile — APPROVED** [review]

**Review by JMS55 — APPROVED** [review]
