### PR TITLE
Don't leak SEND resource, even if thread is panicking.

### LINKED ISSUE #15144: Resource doesn't get dropped on panic in system. Is this expected?
## Bevy version
0.14.2
debug build.

## What you did
```
use bevy_ecs::system::{Resource, RunSystemOnce};
#[derive(Resource)]
struct DropyResource(pub u8);
impl Drop for DropyResource {
    fn drop(&mut self) {
        println!("dropy {} dropped.", self.0);
    }
}
fn panicy_system() { panic!("ima panicing"); }
fn main() {
    let d = DropyResource(1);
    let mut world = bevy_ecs::world::World::new();
    world.insert_resource(DropyResource(2));
    world.run_system_once(panicy_system);
}
```

Output:
```
thread 'main' panicked at src/main.rs:9:22:
ima panicing
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
dropy 1 dropped.
```
## What went wrong
DropyResource added to world didn't get "Dropped".

- what were you expecting?
I was expecting to see 
dropy 1 dropped.
dropy 2 dropped.

- what actually happened?

only "dropy 1 dropped."  was printed.

### PR DESCRIPTION
**Pull request by navneetankur**
# Objective
Currently the resource doesn't get dropped if thread panics. This is presumably to prevent !SEND resource from being dropped by wrong thread.
But, this logic is not needed for SEND resources. So we don't need this check for SEND resource.

Fixes #15144 

## Solution

We check if resource is !SEND before, validating that correct thread is dropping the resource.

## Testing

- Did you test these changes? If so, how?
I did run cargo test on bevy.
- Are there any parts that need more testing?
No
- How can other people (reviewers) test your changes? Is there anything specific they need to know?
Nothing special
- If relevant, what platforms did you test these changes on, and are there any important ones you can't test?
x86_64 desktop

### CODE REVIEW

**Review by kristoff3r — APPROVED** [review]
This makes sense, the current logic tries to prevent double panic which cannot happen when SEND is true.

File: crates/bevy_ecs/src/storage/resource.rs [hunk 1]
```diff
@@ -25,7 +25,7 @@ pub struct ResourceData<const SEND: bool> {
 
 impl<const SEND: bool> Drop for ResourceData<SEND> {
     fn drop(&mut self) {
-        if self.is_present() {
+        if !SEND && self.is_present() {
```
Comment (alice-i-cecile) [inline crates/bevy_ecs/src/storage/resource.rs:28]: Comment here please explaining the logic.

**Review by alice-i-cecile — CHANGES_REQUESTED** [review]
I agree with this change; once there's a small comment added I'll approve and merge :) Thanks!

File: crates/bevy_ecs/src/storage/resource.rs (hunk 1 above)
Comment (navneetankur) [reply crates/bevy_ecs/src/storage/resource.rs:31]: Added the comment.

**Review by alice-i-cecile — APPROVED** [review]
