### PR TITLE
gizmo plugin lag bugfix

### LINKED ISSUE #9156: `GizmoPlugin`: AABBs are rendered with one frame lag
## Bevy version

0.11.0

## What went wrong

AABBs are rendered with one frame lag, which is noticeable when objects are moving.

## Additional information

`GizmoPlugin` is not configuring `draw_aabb` and `draw_all_aabbs` systems properly. They read `GlobalTransform` and thus should run after `TransformSystem::TransformPropagate`

### PR DESCRIPTION
**Pull request by wpederzoli**
# Objective
Fixes #9156

### CODE REVIEW

**Review by Selene-Amanita — APPROVED** [review]

**Comment by Selene-Amanita** [comment]
I honestly don't know why the "run-examples" check was canceled, I guess a maintainer can relaunch it?

**Comment by wpederzoli** [comment]
> I honestly don't know why the "run-examples" check was canceled, I guess a maintainer can relaunch it?

It exceeded the 30 min time limit and it got automatically canceled. But you're right, a maintainer can re-run it.
Thanks!

**Comment by mockersf** [comment]
relaunched! usually that job takes 15 to 20 minutes to run, the limit at 30 minutes should be enough...

**Review by mockersf — APPROVED** [review]

**Review by mockersf — CHANGES_REQUESTED** [review]
`TransformPropagate` is in schedule `PostUpdate`, those systems are in `Update`

File: crates/bevy_gizmos/src/lib.rs [hunk 1]
```diff
@@ -89,7 +92,8 @@ impl Plugin for GizmoPlugin {
                 (
                     draw_aabbs,
                     draw_all_aabbs.run_if(|config: Res<GizmoConfig>| config.aabb.draw_all),
-                ),
+                )
+                    .after(TransformSystem::TransformPropagate),
```
Comment (nicopap) [inline crates/bevy_gizmos/src/lib.rs:96]: So, instead of adding the `draw_aabbs` systems in `Update`, you should add them to `PostUpdate`. Otherwise this fixes nothing.

**Review by nicopap — CHANGES_REQUESTED** [review]
This doesn't fix the issue, as mockersf mentioned, this can't be merged before the comments are addressed.

Also please add "Fixes #9156" to the PR description, so that github automatically closes the issue when this gets merged.

File: crates/bevy_gizmos/src/lib.rs (hunk 1 above)
Comment (wpederzoli) [reply crates/bevy_gizmos/src/lib.rs:96]: updated

**Comment by nicopap** [comment]
@mockersf ping. Is this ready to merge?

**Comment by mockersf** [comment]
> @mockersf ping. Is this ready to merge?

Technically the two other approvals than yours were when it was not fixed, so...

Did anyone check that it was fixed or is it just approval "in theory"?

**Review by devil-ira — APPROVED** [review]
Verified the fix by enabling aabb gizmos in the `update_gltf_scene` example.

**Review by Selene-Amanita — APPROVED** [review]
Tested with custom code it does fix the bug

**Review by mockersf — APPROVED** [review]

**Review by james7132 — APPROVED** [review]
