### PR TITLE
DespawnOnExit / DespawnOnEnter fix log spam 

### LINKED ISSUE #21832: `DespawnOnExit` / `DespawnOnEnter` causes log spam when despawning hierarchies
## What problem does this solve or what need does it fill?

When you use `DespawnOnExit`, you need to ensure it is only used on the top level parents and is the only thing despawning the items.

Failing to do this will fill your logs with warnings while not a huge issue, it can bury other actual problems.

I would like a `TryDespawnOnExit` that will ignore despawned entities, as semantically I am saying "you should ensure it is despawned" rather then "You must be the one to despawn the entities".

Saves having to filter out logs that may contain more valuable information.

## What solution would you like?

Either modifying `DespawnOnExit` or adding `TryDespawnOnExit`

## What alternative(s) have you considered?

Using Tracing to filter out logs.
Making my own despawn component and activating on state transition.

I am currently marking components to not despawn.

### PR DESCRIPTION
**Pull request by Pronoiai**
if entity was despawned such as in a hierachy

# Objective

- DespawnOnExit / DespawnOnEnter logs errors with despawning. 
    Most if not all use cases don't care if the item is already despawned.
    The user is typically saying "Ensure it is despawned" rather then "You should be the one to despawn"
- Fixes #21832

## Solution

- Changes the state_scoped code to use try despawn

## Testing

- I updated example state_scoped to include children with DespawnOnExit/DespawnOnEnter and added a brief explanation then I ran the examples

### CODE REVIEW

**Review by alice-i-cecile — APPROVED** [review]

**Comment by alice-i-cecile** [comment]
CI has found a couple of spelling errors for you :)

**Comment by Pronoiai** [comment]
> CI has found a couple of spelling errors for you :)

Fixed!

File: crates/bevy_state/src/state_scoped.rs [hunk 1]
```diff
@@ -67,6 +67,7 @@ where
 
 /// Despawns entities marked with [`DespawnOnExit<S>`] when their state no
 /// longer matches the world state.
+/// If the entity has already been despawned no warning will be emitted
```
Comment (mgi388) [inline crates/bevy_state/src/state_scoped.rs]:
```suggestion
///
/// If the entity has already been despawned no warning will be emitted.
```

File: crates/bevy_state/src/state_scoped.rs [hunk 2]
```diff
@@ -133,6 +134,7 @@ pub struct DespawnOnEnter<S: States>(pub S);
 
 /// Despawns entities marked with [`DespawnOnEnter<S>`] when their state
 /// matches the world state.
+/// If the entity has already been despawned no warning will be emitted
```
Comment (mgi388) [inline crates/bevy_state/src/state_scoped.rs]:
```suggestion
///
/// If the entity has already been despawned no warning will be emitted.
```

File: examples/ecs/state_scoped.rs [hunk 3]
```diff
@@ -3,6 +3,9 @@
 //!
 //! This pattern is useful for managing menus, levels, or other state-specific
 //! content that should only exist during certain states.
+//!
+//! If the entity was already despawned then no error will be logged
+//! This means that you don't have to worry about duplicating in a hierarchy
```
Comment (mgi388) [inline examples/ecs/state_scoped.rs]:
```suggestion
//! If the entity was already despawned then no error will be logged. This means
//! that you don't have to worry about duplicate [`DespawnOnExit`] and
//! [`DespawnOnEnter`] components deep in your hierarchy.
```

File: examples/ecs/state_scoped.rs [hunk 4]
```diff
@@ -65,6 +69,10 @@ fn on_a_exit(mut commands: Commands) {
             left: px(500),
             ..default()
         },
+        // You can apply this even when the parent has a state scope
+        // It is unnecessary but in complex hierarchies
+        // it saves you from having to mentally track which components are found at the top level
```
Comment (mgi388) [inline examples/ecs/state_scoped.rs]:
```suggestion
        // You can apply this even when the parent has a state scoped component.
        // It is unnecessary but in complex hierarchies it saves you from having to
        // mentally track which components are found at the top level.
```

**Review by mgi388 — APPROVED** [review]
LGTM. I left suggestions for nits on doc comment formatting for consistency with what is there. Feel free to apply the suggestions yourself, I just did it with the PR reviewer so hopefully I got the suggestions right.

**Comment by Pronoiai** [comment]
> LGTM. I left suggestions for nits on doc comment formatting for consistency with what is there. Feel free to apply the suggestions yourself, I just did it with the PR reviewer so hopefully I got the suggestions right.

Thank you changes applied.

**Review by mgi388 — APPROVED** [review]

**Review by janhohenheim — APPROVED** [review]
Oh yes, I've run into this plenty of times. Thanks!

**Review by mnmaita — APPROVED** [review]
Been dealing with this lately and I appreciate the change and the added docs.
