### PR TITLE
Skip empty spans when updating text buffers

### LINKED ISSUE #16521: Nested text spans are not rendered if the `default_font` feature is disabled
## Bevy version

`0.15.0-rc.3`, also current main

## Relevant system information

```
SystemInfo { os: "MacOS 14.5 ", kernel: "23.5.0", cpu: "Apple M1 Max", core_count: "10", memory: "64.0 GiB" }
AdapterInfo { name: "Apple M1 Max", vendor: 0, device: 0, device_type: IntegratedGpu, driver: "", driver_info: "", backend: Metal }
```

## What you did

- Disable `default-features`
- Decline to enable `default_font` feature
- Use nested text spans where the (empty) root node uses `TextFont::default()` either by omission of the component, or by explicitly setting it to that value.

https://github.com/rparrett/bevy-default-font-bug

```
git clone https://github.com/rparrett/bevy-default-font-bug
cd bevy-default-font-bug
cargo run
```

## What went wrong

No text is displayed

## Additional Information

Relevant snippet pasted here for convenience

```rust
let font = asset_server.load("FiraSans-Bold.ttf");
commands
    .spawn((
        Text::default(),
        // Uncommenting this makes things work
        // TextFont {
        //     font: font.clone(),
        //     ..default()
        // },
    ))
    .with_children(|parent| {
        parent.spawn((
            TextSpan::new("span, should be visible"),
            TextFont { font, ..default() },
        ));
    });
```

### PR DESCRIPTION
**Pull request by cart**
# Objective

Fixes #16521

## Solution

If an empty span is encountered (such as the default `Text` value), we skip it entirely when updating buffers. This prevents unnecessarily bailing when the font doesn't exist (ex: when the default font is disabled)

### CODE REVIEW

File: crates/bevy_text/src/pipeline.rs [hunk 1]
```diff
@@ -223,6 +226,7 @@ impl TextPipeline {
     ) -> Result<(), TextError> {
         layout_info.glyphs.clear();
         layout_info.size = Default::default();
+        println!("QUEUED");
```
Comment (UkoeHB) [inline crates/bevy_text/src/pipeline.rs:229]: Leftover?

File: crates/bevy_text/src/pipeline.rs [hunk 2]
```diff
@@ -107,6 +107,9 @@ impl TextPipeline {
         computed.entities.clear();
 
         for (span_index, (entity, depth, span, text_font, color)) in text_spans.enumerate() {
+            if span.is_empty() {
+                continue;
+            }
```
Comment (UkoeHB) [inline crates/bevy_text/src/pipeline.rs:112]: For correct indexing, this should go after `computed.entities.push(TextEntity { entity, depth });`.

**Review by UkoeHB — CHANGES_REQUESTED** [review]

File: crates/bevy_text/src/pipeline.rs (hunk 1 above)
Comment (cart) [reply crates/bevy_text/src/pipeline.rs:229]: YUUUP

File: crates/bevy_text/src/pipeline.rs (hunk 2 above)
Comment (cart) [reply crates/bevy_text/src/pipeline.rs:115]: Ah yeah. I thought I tested this properly, but it was setting the wrong span and I didn't know because the colors were the same. Sure enough, giving the spans different colors surfaced an indexing problem, and the reorder fixes it.

Comment (cart) [reply crates/bevy_text/src/pipeline.rs:115]: Nice catch!

**Review by UkoeHB — APPROVED** [review]

**Review by viridia — APPROVED** [review]
