### PR TITLE
Fix floating point math

### LINKED ISSUE #15236: `bevy_color`'s operations are not stable across all hardware due to use of trigonometric float methods
## Bevy version

Commit 87afa98167b67e09d5701e49b02e185c8f09439d

## \[Optional\] Relevant system information

[DxDiag.txt](https://github.com/user-attachments/files/17007220/DxDiag.txt)

Lenovo Thinkbook Pro Gen 3
Razer Core X Chroma with an RTX 2060
Samsung Odyssey Neo G9 54"

## What you did

Ran cargo run -p ci -- test

## What went wrong

```
---- oklcha::tests::test_to_from_srgba_2 stdout ----
thread 'oklcha::tests::test_to_from_srgba_2' panicked at crates\bevy_color\src\oklcha.rs:415:13:
gray: Oklcha { lightness: 0.5981808, chroma: 2.3841858e-7, hue: 0.0, alpha: 1.0 } != Oklcha { lightness: 0.5981807, chroma: 9.424322e-8, hue: 18.434948, alpha: 1.0 }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

failures:
    oklcha::tests::test_to_from_srgba_2

## Additional information

This is not on main. It is on https://github.com/BenjaminBrienen/bevy/tree/rename-add-to-enqueue

### PR DESCRIPTION
**Pull request by BenjaminBrienen**
# Objective

- Fixes #15236

## Solution

- Use bevy_math::ops instead of std floating point operations.

## Testing

- Did you test these changes? If so, how?
Unit tests and `cargo run -p ci -- test`

- How can other people (reviewers) test your changes? Is there anything specific they need to know?
Execute `cargo run -p ci -- test` on Windows.

- If relevant, what platforms did you test these changes on, and are there any important ones you can't test?
Windows

## Migration Guide

- Not a breaking change
- Projects should use bevy math where applicable

### CODE REVIEW

**Comment by BenjaminBrienen** [comment]
This is incomplete because the test still fails :)

File: crates/bevy_color/src/oklcha.rs [hunk 1]
```diff
@@ -191,9 +191,9 @@ impl Luminance for Oklcha {
 impl EuclideanDistance for Oklcha {
     #[inline]
     fn distance_squared(&self, other: &Self) -> f32 {
-        (self.lightness - other.lightness).powi(2)
-            + (self.chroma - other.chroma).powi(2)
-            + (self.hue - other.hue).powi(2)
+        FloatPow::squared(self.lightness - other.lightness)
+            + FloatPow::squared(self.chroma - other.chroma)
+            + FloatPow::squared(self.hue - other.hue)
```
Comment (IQuick143) [inline crates/bevy_color/src/oklcha.rs:196]: I think it'd be nicer to use `.squared()`. (I believe the type inferrence works here.)

File: crates/bevy_color/src/lcha.rs [hunk 2]
```diff
@@ -274,9 +274,9 @@ impl From<Laba> for Lcha {
         }: Laba,
     ) -> Self {
         // Based on http://www.brucelindbloom.com/index.html?Eqn_Lab_to_LCH.html
-        let c = (a.powf(2.0) + b.powf(2.0)).sqrt();
+        let c = (powf(a, 2.0) + powf(b, 2.0)).sqrt();
```
Comment (IQuick143) [inline crates/bevy_color/src/lcha.rs:277]: This is just `hypot(a, b)`, if I'm not mistaken.

File: crates/bevy_pbr/src/fog.rs [hunk 3]
```diff
@@ -462,7 +462,7 @@ impl FogFalloff {
     /// - <https://en.wikipedia.org/wiki/Visibility>
     /// - <https://www.biral.com/wp-content/uploads/2015/02/Introduction_to_visibility-v2-2.pdf>
     pub fn koschmieder(v: f32, c_t: f32) -> f32 {
-        -c_t.ln() / v
+        ln(-c_t) / v
```
Comment (IQuick143) [inline crates/bevy_pbr/src/fog.rs:465]: Pretty sure this is wrong, `.ln()` precedes negation.
The doc comment agrees that was the intention.
```suggestion
        -ln(c_t) / v
```

File: crates/bevy_render/src/camera/camera.rs [hunk 4]
```diff
@@ -136,7 +136,7 @@ impl Exposure {
     /// <https://google.github.io/filament/Filament.md.html#imagingpipeline/physicallybasedcamera/exposure>
     #[inline]
     pub fn exposure(&self) -> f32 {
-        (-self.ev100).exp2() / 1.2
+        exp2(-self.ev100) / 1.2
```
Comment (IQuick143) [inline crates/bevy_render/src/camera/camera.rs:139]: Looks correct here.

File: examples/3d/motion_blur.rs [hunk 5]
```diff
@@ -304,12 +305,12 @@ fn race_track_pos(offset: f32, t: f32) -> Vec2 {
...
-    let dx = x_tweak * (x_tweak * t).cos();
-    let dy = y_tweak * -(y_tweak * t).sin();
-    let x = x0 + offset * dy / (dx.powi(2) + dy.powi(2)).sqrt();
-    let y = y0 - offset * dx / (dx.powi(2) + dy.powi(2)).sqrt();
+    let x0 = sin(x_tweak * t);
+    let y0 = cos(y_tweak * t);
+    let dx = x_tweak * cos(x_tweak * t);
+    let dy = y_tweak * -sin(y_tweak * t);
+    let x = x0 + offset * dy / (FloatPow::squared(dx) + FloatPow::squared(dy)).sqrt();
+    let y = y0 - offset * dx / (FloatPow::squared(dx) + FloatPow::squared(dy)).sqrt();
```
Comment (IQuick143) [inline examples/3d/motion_blur.rs:313]: Again, should be refactorable to `hypot`.
```suggestion
    let dl = hypot(dx, dy);
    let x = x0 + offset * dy / dl;
    let y = y0 - offset * dx / dl;
```

File: examples/shader/custom_post_processing.rs [hunk 6]
```diff
@@ -365,9 +366,9 @@ fn rotate(time: Res<Time>, mut query: Query<&mut Transform, With<Rotates>>) {
 // Change the intensity over time to show that the effect is controlled from the main world
 fn update_settings(mut settings: Query<&mut PostProcessSettings>, time: Res<Time>) {
     for mut setting in &mut settings {
-        let mut intensity = time.elapsed_seconds().sin();
+        let mut intensity = sin(time.elapsed_seconds());
         // Make it loop periodically
-        intensity = intensity.sin();
+        intensity = sin(intensity);
```
Comment (IQuick143) [inline examples/shader/custom_post_processing.rs:371]: Wtf is this code lol. Two sines in a row is a sign something is off, and the comment doesn't fill me with confidence either.

I suppose it's not a fault of this PR though.

File: examples/stress_tests/many_cubes.rs [hunk 7]
```diff
@@ -439,7 +439,7 @@ const EPSILON: f64 = 0.36;
 fn fibonacci_spiral_on_sphere(golden_ratio: f64, i: usize, n: usize) -> DVec2 {
     DVec2::new(
         PI * 2. * (i as f64 / golden_ratio),
-        (1.0 - 2.0 * (i as f64 + EPSILON) / (n as f64 - 1.0 + 2.0 * EPSILON)).acos(),
+        acos((1.0 - 2.0 * (i as f64 + EPSILON) / (n as f64 - 1.0 + 2.0 * EPSILON)) as f32) as f64,
```
Comment (IQuick143) [inline examples/stress_tests/many_cubes.rs:442]: The loss of precision here is not great, the method basically pretends to be an f64 methods while being an f32 one.

Do we have a double precision version somewhere?

Comment (IQuick143) [reply examples/stress_tests/many_cubes.rs:442]: (Of acos I meant)

**Review by IQuick143 — CHANGES_REQUESTED** [review]
The `-ln` needs fixing, I left some other comments, but those aren't all that blocking.

Someone else please take a thorough look, cause there's a lot of code touched so I may have missed smth.

File: examples/stress_tests/many_cubes.rs (hunk 7 above)
Comment (BenjaminBrienen) [reply examples/stress_tests/many_cubes.rs:442]: > (Of acos I meant)

I looked and I didn't see one in bevy_math::ops or ops::f64.

Comment (BenjaminBrienen) [reply examples/stress_tests/many_cubes.rs:442]: I now see acos_approx in glam

Comment (BenjaminBrienen) [reply examples/stress_tests/many_cubes.rs:442]: f64 wasn't banned, so I should just put it back

**Comment by BenjaminBrienen** [comment]
The test now passes on my pc, confirming that the issue is solved.

File: crates/bevy_math/Cargo.toml [hunk 8]
```diff
@@ -36,7 +36,7 @@ bevy_math = { path = ".", version = "0.15.0-dev", features = ["approx"] }
 glam = { version = "0.28", features = ["approx"] }
 
 [features]
-default = ["rand", "bevy_reflect"]
+default = ["rand", "bevy_reflect", "libm"]
```
Comment (IQuick143) [inline crates/bevy_math/Cargo.toml:39]: I think this will be a very controversial change.

Other than that this PR looks good to me now. (But I want someone else to take a thorough look too, because I'm not sure I haven't missed something.)

File: examples/stress_tests/many_cubes.rs (hunk 7 above)
Comment (IQuick143) [reply examples/stress_tests/many_cubes.rs]: Given that it's example code, I don't think this will break anything down the line.

**Comment by BenjaminBrienen** [comment]
Let me know if I should change the disallow in clippy to be `bevy::math::_` instead of `bevy_math::_`.

File: crates/bevy_math/Cargo.toml (hunk 8 above)
Comment (BenjaminBrienen) [reply crates/bevy_math/Cargo.toml:39]: We should measure the performance impact

**Comment by alice-i-cecile** [comment]
> Let me know if I should change the disallow in clippy to recommend bevy::math::_ instead of bevy_math::_.

Either one is fine; I think `bevy_math` is slightly better since it can be used standalone.

**Review by alice-i-cecile — COMMENTED** [review]
LGTM once we remove `libm` from the default features of `bevy_math`.

File: crates/bevy_math/Cargo.toml (hunk 8 above)
Comment (alice-i-cecile) [reply crates/bevy_math/Cargo.toml:39]:
```suggestion
default = ["rand", "bevy_reflect"]
```

**Review by alice-i-cecile — APPROVED** [review]

**Review by IQuick143 — APPROVED** [review]

**Review by Jondolf — COMMENTED** [review]
Some clean-up and optimization comments. Most of these issues were present before as well however, so fixing them isn't blocking.

More broadly, I'm not sure if we want to use these `ops` in documentation and examples. I think we'd first want to decide *if* users should even be encouraged to use them by default in their own apps instead of using `std` ops directly, and if so, have clear documentation on *why* that is. A user looking at the examples here might be left to wonder why the code is using e.g. the re-exported version of `sin` instead of just using `foo.sin()` like they're used to, and right now, there is no good documentation on this. Documenting it in every example isn't viable either.

Personally, I would use the `ops` in internal code, but use the standard Rust functions in user-facing docs and examples. Of course there could (and should!) be some cross-platform determinism example that specifically showcases libm and math determinism, along with good docs on how to achieve determinism.

(Note: [`bevy_math::ops`](https://dev-docs.bevyengine.org/src/bevy_math/ops.rs.html) does have very brief module-level docs, but the module is currently private, as it just re-exports the functions.)

File: crates/bevy_gizmos/src/arcs.rs [hunk 9]
```diff
@@ -114,7 +114,7 @@ fn arc_2d_inner(arc_angle: f32, radius: f32, resolution: u32) -> impl Iterator<I
     (0..=resolution)
         .map(move |n| arc_angle * n as f32 / resolution as f32)
         .map(|angle| angle + FRAC_PI_2)
-        .map(f32::sin_cos)
+        .map(sin_cos)
         .map(|(sin, cos)| Vec2::new(cos, sin))
```
Comment (IQuick143) [inline crates/bevy_gizmos/src/arcs.rs:118]: Following Jondolf's suggestions, this could be
```suggestion
        .map(Vec2::from_angle)
```

File: crates/bevy_pbr/src/fog.rs [hunk 10]
```diff
@@ -207,7 +207,7 @@ pub enum FogFalloff {
     /// The fog intensity for a given point in the scene is determined by the following formula:
     ///
     /// ```text
-    /// let fog_intensity = 1.0 - 1.0 / (distance * density).powi(2).exp();
+    /// let fog_intensity = 1.0 - 1.0 / FloatPow::squared(distance * density).exp();
```
[the remark this answers is not in the document]
Comment (janhohenheim) [reply crates/bevy_pbr/src/fog.rs:210]: Since this is not even code, but a generic formula, I'd use `(distance * density)²` instead

**Comment by BenjaminBrienen** [comment]
I'll fix this up and apply the feedback soon. Tonight most likely.

File: crates/bevy_render/src/mesh/primitives/dim3/torus.rs [hunk 11]
```diff
@@ -100,15 +100,15 @@ impl MeshBuilder for TorusMeshBuilder {
...
+                    sin(theta) * (self.torus.major_radius + self.torus.minor_radius * cos(phi)),
                 );
 
                 let center = Vec3::new(
-                    self.torus.major_radius * theta.cos(),
+                    self.torus.major_radius * cos(theta),
                     0.,
-                    self.torus.major_radius * theta.sin(),
+                    self.torus.major_radius * sin(theta),
                 );
```
[the remark this answers is not in the document]
Comment (BenjaminBrienen) [reply crates/bevy_render/src/mesh/primitives/dim3/torus.rs:112]: It would be really nice if it did optimize it

**Comment by BenjaminBrienen** [comment]
This is in a good state for now, but I'm waiting for conclusive feedback on exactly how explicit we should make the calls to bevy_math trig functions, especially in documentation and examples.

**Comment by BenjaminBrienen** [comment]
If anyone would like to suggest a different name for `bevy_math::ops` before it is made public, now is a good time. To me, `ops` kind of implies the traits like `Add` and `Mul` (for bevy, maybe instead for matrices and vector operations).

**Comment by alice-i-cecile** [comment]
`ops` is fine IMO :)

**Comment by alice-i-cecile** [comment]
> This is in a good state for now, but I'm waiting for conclusive feedback on exactly how explicit we should make the calls to bevy_math trig functions, especially in documentation and examples.

Stick it in the prelude, but use only the method names please.

**Comment by IQuick143** [comment]
Oh wow, this ended up being quite an undertaking, props for the work.
