### PR TITLE
Refs #8975 -- Add return to RenderDevice::poll()

### LINKED ISSUE #8975: `RenderDevice::poll()` drops the return value for `wgpu::Device::poll()`
## Bevy version

0.10.1

## What you did

Attempted to use `RenderDevice::poll()` to check whether my compute shader had finished running.

## What went wrong

`RenderDevice::poll()` has no return value, and thus doesn't inform me whether it's finished. Which is surprising, as it's just a passthrough on `wgpu::Device::poll()`, which DOES have a return value.

## Additional information

Per the docs for [`wgpu::Device::poll()`](https://docs.rs/wgpu/latest/wgpu/struct.Device.html#method.poll), it both checks for work to do, and then returns a boolean telling you if there is no work remaining. The `RenderDevice::poll()` function drops that return value.

It's trivial to work around this by calling `RenderDevice::wgpu_device().poll()`, which is what I'm doing for now. But that shouldn't be necessary.

### PR DESCRIPTION
**Pull request by Skovrup1**
# Objective
Fixes #8975

## Solution
Return the value from wgpu::device::poll().

---

## Changelog
In render_device.rs
- RenderDevice::Poll()

### CODE REVIEW

File: crates/bevy_render/src/renderer/render_device.rs [hunk 1]
```diff
@@ -52,8 +52,8 @@ impl RenderDevice {
     ///
     /// no-op on the web, device is automatically polled.
```
Comment (alice-i-cecile) [inline crates/bevy_render/src/renderer/render_device.rs:53]: Can you describe what the return value means here?

Comment (Skovrup1) [reply crates/bevy_render/src/renderer/render_device.rs:59]: Sure thing! Added the description about the return value from the wgpu docs.

**Review by alice-i-cecile — APPROVED** [review]

**Review by IceSentry — APPROVED** [review]
