### PR TITLE
Fix global wireframe behavior not being applied on new meshes

### LINKED ISSUE #11782: `WireframeConfig` change affects only currently spawned meshes
## Bevy version

0.12.1

## What you did

Set `global` in [`WireframeConfig`](https://docs.rs/bevy/latest/bevy/pbr/wireframe/struct.WireframeConfig.html) to `true`.

## What went wrong

It affected only current meshes. All newly spawned meshes won't have a rendered wireframe.

I would expect the global configuration to affect all meshes.

### PR DESCRIPTION
**Pull request by Kanabenki**
# Objective

- Fixes #11782.

## Solution

- Remove the run condition for `apply_global_wireframe_material`, since it prevent detecting when meshes are added or the `NoWireframe` marker component is removed from an entity. Alternatively this could be done by using a run condition like "added `Handle<Mesh>` or removed `NoWireframe` or `WireframeConfig` changed" but this seems less clear to me than directly letting the queries on `apply_global_wireframe_material` do the filtering.

### CODE REVIEW

**Comment by Kanabenki** [comment]
Putting in draft since there is some potential edge cases with `NoWireframe` I'd like to fix.

File: crates/bevy_pbr/src/wireframe.rs [hunk 1]
```diff
@@ -46,7 +46,9 @@ impl Plugin for WireframePlugin {
                     global_color_changed.run_if(resource_changed::<WireframeConfig>),
                     wireframe_color_changed,
                     apply_wireframe_material,
-                    apply_global_wireframe_material.run_if(resource_changed::<WireframeConfig>),
+                    // Run after `apply_wireframe_material` so that the global wireframe setting is applied
+                    // to a mesh on the same frame its wireframe marker component is removed.
+                    apply_global_wireframe_material.after(apply_wireframe_material),
```
Comment (Shatur) [inline crates/bevy_pbr/src/wireframe.rs:51]: I would suggest to use `chain`: `(apply_wireframe_material, apply_global_wireframe_material).chain()`

**Review by Shatur — CHANGES_REQUESTED** [review]
Minor suggestion, otherwise looks good!

**Review by Shatur — APPROVED** [review]

**Comment by Shatur** [comment]
@alice-i-cecile may I suggest this PR for your merge train?

**Review by alice-i-cecile — APPROVED** [review]
