### PR TITLE
Deprecate dynamic plugins

### LINKED ISSUE #4843: Unloading/reloading dynamic plugins
## What problem does this solve or what need does it fill?

Currently bevy supports the loading of plugins at runtime. By adding support for unloading/reloading will allow gamedevs to make changes to a module and test it without restarting the game process and resetting state. Shortening the feedback loop to test gameplay changes makes dev faster.
 
## What solution would you like?

Add `unload` and `reload` methods to `App` via `DynamicExt` trait. I am happy to explore and flesh this out further but would like to get some feedback on the idea first. Is this even possible? How much work would it be?

## What alternative(s) have you considered?
None

## Additional context
None

### LINKED ISSUE #11969: Deprecate current `bevy_dynamic_plugin` implementation
## What problem does this solve or what need does it fill?

[`bevy_dynamic_plugin`] is likely unsound, or at the very least so dangerous that it should not be an officially sanctioned crate. It currently works by deriving `bevy_app::DynamicPlugin` onto a unit struct that implements `Plugin`. The code can then be built as a `cdylib` and loaded with `bevy_dynamic_plugin::dynamically_load_plugin`.

[`bevy_dynamic_plugin`]: https://github.com/bevyengine/bevy/tree/main/crates/bevy_dynamic_plugin

There are a few potential footguns / problems with this approach:

- It works by loading and executing foreign code, which is drastically unsafe.
  - Loading a library could run [`ctor`] code unconditionally, without calling any functions.
- Plugins must be built with the exact same Bevy and Rust versions.
  - This prevents plugins from taking advantage of new optimizations in the compiler and important bug fixes in Bevy.
  - `#[derive(DynamicPlugin)]` creates `_bevy_create_plugin`, which returns `&'static dyn Plugin`. `dyn` references are fat pointers, where the metadata is a VTable. VTable layouts are not guaranteed.
- Lots of Bevy uses generics and type-level code, especially in `App`.
  - I don't believe Rust provides any guarantees with how generics / types are generated, even across compiles with the same version. (This needs fact-checked.)
  - There's also a lot of `TypeId` usage. `TypePath` somewhat fixes this, but it's not used everywhere.

[`ctor`]: https://lib.rs/crates/ctor

## What solution would you like?

Mark `dynamically_load_plugin` and `DynamicPluginExt::load_plugin` as deprecated for Bevy 0.14. In Bevy 0.15, they will be removed and `bevy_dynamic_plugin` will be turned into an empty crate likely moved to [`bevy-crate-reservations`].

[`bevy-crate-reservations`]: https://github.com/bevyengine/bevy-crate-reservations

I think the current implementation is just too unsafe to continue in the main Bevy library. As [mentioned by Alice], it may be worth recommending [`dextrous_developer`] in the module or deprecation notes.

[mentioned by Alice]: https://elk.zone/mastodon.gamedev.place/@alice_i_cecile/111919126897119034
[`dextrous_developer`]: https://github.com/lee-orr/dexterous_developer

## What alternative(s) have you considered?

Try to fix the above issues by exclusively using `TypePath` instead of `TypeId` and manually recreating the VTable struct. ctor is unavoidable, we just have to hope it won't be encountered in practice.

## Additional context

Some discussion [on Discord] on `bevy_dynamic_plugin`, while I was working on #11622.

[on Discord]: https://discord.com/channels/691052431525675048/692572690833473578/1201958798307369020

I think there is promise is dynamically loading plugins, so I would not be opposed to `bevy_dynamic_plugin` being re-introduced in the future, but I don't think the current implementation should be kept.

### LINKED ISSUE #13073: User-mode data execution prevention (DEP) violation when loading Dynamic Plugins
## Bevy version

0.13.2

## \[Optional\] Relevant system information
OS: Windows 11 Pro for Workstations - 23H2 - 22631.3447
CPU: AMD Ryzen 7 4800H with Radeon Graphics 2.90 GHz
GPU: NVIDIA GeForce GTX 1650Ti for Laptop
RAM: 64GB
Rust Version: rustc 1.77.2 (25ef9e3d8 2024-04-09)
Cargo Version: cargo 1.77.2 (e52e36006 2024-03-26)

## What you did

I am tring to test whether Bevy can share component type throuth different dynamic plugins(i.e. System in one dylib can detect component spawned by System in another dylib).
So I create three crates inside the main project. One defines Components, Others depend this static lib and run Systems. In main.rs of this project, I enable bevy's "bevy_dynamic_plugin" feature then invoke load_plugin()

## What went wrong

Whether test success or fail, dynamic_plugin should built successfully, but I encountered `Exception: Exception 0xc0000005 encountered at address 0x000000: User-mode data execution prevention (DEP) violation at location 0x00000000` and then bevy crashed.

## Additional information

I debug the application several times. I'm sure that dlls are successfully loaded.
The last step before exception is as follows:
a9b4a057e0373f86602bab2a9a00ff3e
then, it crashes:
afcc0b6bf2ef46794b42fc215e007d81
The top of trace stack is:
725f8d3a50268044c9ed7cc6876356af

It appears that the address of `self` is 0x0 or 0x4 or many other address nearby 0x0, but actually `self` has its own address. What happend when app calls `plugin.build(self)`?
I switched lib type to cdylib, but it makes nonsense.
The content of dll is quite simple(This problem exists whether these lines are commented or not ):
```rust
use bevy::app::DynamicPlugin;
use bevy::prelude::{App, Commands, Component, Plugin, Query, Startup, Update};
use xk_python::Test1;

#[derive(DynamicPlugin)]
pub struct XkUiplugin;

impl Plugin for XkUiplugin {
    fn build(&self, app: &mut App) {
        // println!("build ui");
        // app.add_systems(Update, test_ui);
    }
}
```
same to main.rs
```rust
pub mod prelude;

use bevy::prelude::*;
use std::env;

pub fn main() {
    unsafe {
        println!("{}", String::from(env::current_dir().unwrap().to_str().unwrap()) + "\\xk_ui.dll");
        App::new()
            .load_plugin( "D:\\WorkSpace\\Project\\FormalProject\\XKGIS\\XKGIS-Core\\target\\debug\\xk_ui.dll")
            .load_plugin("D:\\WorkSpace\\Project\\FormalProject\\XKGIS\\XKGIS-Core\\target\\debug\\xk_show_screen.dll")
            .add_plugins(MinimalPlugins)
            .run();
    }
}

```
My friend helped me checked dll content with IDA, he says the dll files I used are completely normal.
Debugger of RustRover gives me assembly code, I don't know whether it can help.
```asm
bevy_dynamic_plugin::loader::impl$0::load_plugin<ref$<str$> >(*mut bevy_app::app::App,ref$<str$>):
	pushq  %rbp                     
	subq   $0xe0, %rsp              
	leaq   0x80(%rsp), %rbp         
	movq   $-0x2, 0x58(%rbp)        
	movq   %rcx, -0x50(%rbp)        
	movq   %rcx, 0x18(%rbp)         
	movq   %rdx, 0x20(%rbp)         
	movq   %r8, 0x28(%rbp)          
	movb   $0x0, 0x17(%rbp)         
	leaq   -0x18(%rbp), %rcx        
	callq  0x140002cb0                ; bevy_dynamic_plugin::loader::dynamically_load_plugin<ref$<str$> >(ref$<str$>) at loader.rs:29
	cmpq   $0x2, -0x18(%rbp)        
	je     0x140001852                ; <+130> [inlined] enum2$<core::result::Result<tuple$<libloading::safe::Library,alloc::boxed::Box<dyn$<bevy_app::plugin::Plugin>,alloc::alloc::Global> >,enum2$<bevy_dynamic_plugin::loader::DynamicPluginLoadError> > >::unwrap(enum2$<core::result::Result<tuple$<libloading::safe::Library,alloc::boxed::Box<dyn$<bevy_app::plugin::Plugin>,alloc::alloc::Global> >,enum2$<bevy_dynamic_plugin::loader::DynamicPluginLoadError> > >,*mut core::panic::location::Location) + 77 at loader.rs:59
	movq   0x8(%rbp), %rax          
	movq   %rax, 0x50(%rbp)         
	movups -0x18(%rbp), %xmm0       
	movups -0x8(%rbp), %xmm1        
	movaps %xmm1, 0x40(%rbp)        
	movaps %xmm0, 0x30(%rbp)        
	leaq   0x3d8c95(%rip), %rcx     
	movq   %rsp, %rax               
	movq   %rcx, 0x20(%rax)         
	leaq   0x3d8bc7(%rip), %rcx     
	leaq   0x3d8bf0(%rip), %r9        ; impl$<enum2$<bevy_dynamic_plugin::loader::DynamicPluginLoadError>, core::fmt::Debug>::vtable$
	movl   $0x2b, %edx              
	leaq   0x30(%rbp), %r8          
	callq  0x1403d9830                ; core::result::unwrap_failed() at result.rs:1648
	jmp    0x140001850                ; <+128> [inlined] enum2$<core::result::Result<tuple$<libloading::safe::Library,alloc::boxed::Box<dyn$<bevy_app::plugin::Plugin>,alloc::alloc::Global> >,enum2$<bevy_dynamic_plugin::loader::DynamicPluginLoadError> > >::unwrap(enum2$<core::result::Result<tuple$<libloading::safe::Library,alloc::boxed::Box<dyn$<bevy_app::plugin::Plugin>,alloc::alloc::Global> >,enum2$<bevy_dynamic_plugin::loader::DynamicPluginLoadError> > >,*mut core::panic::location::Location) + 75 at loader.rs:59
	ud2                             
	movq   (%rbp), %rax             
	movq   %rax, -0x20(%rbp)        
	movups -0x10(%rbp), %xmm0       
	movaps %xmm0, -0x30(%rbp)       
	movb   $0x1, 0x17(%rbp)         
	movq   -0x30(%rbp), %rax        
	movq   %rax, -0x48(%rbp)        
	movq   -0x28(%rbp), %rcx        
	movq   -0x20(%rbp), %rax        
	movq   %rcx, -0x40(%rbp)        
	movq   %rax, -0x38(%rbp)        
	movb   $0x0, 0x17(%rbp)         
	movq   -0x48(%rbp), %rcx        
	callq  0x140002810                ; core::mem::forget<libloading::safe::Library>(libloading::safe::Library) at mod.rs:148
	jmp    0x14000188d                ; <+189> at loader.rs:61
	movq   -0x50(%rbp), %rdx        
	movq   -0x40(%rbp), %rcx        
	movq   -0x38(%rbp), %rax        
	movq   0x50(%rax), %rax         
	callq  *%rax                    
	jmp    0x1400018a1                ; <+209> at loader.rs:63
	leaq   -0x40(%rbp), %rcx        
	callq  0x1400c4bf0                ; core::ptr::drop_in_place<alloc::boxed::Box<dyn$<bevy_app::plugin::Plugin>,alloc::alloc::Global> >(*mut alloc::boxed::Box<dyn$<bevy_app::plugin::Plugin>,alloc::alloc::Global>) at mod.rs:507
	jmp    0x1400018ac                ; <+220> at loader.rs:63
	movq   -0x50(%rbp), %rax        
	movb   $0x0, 0x17(%rbp)         
	addq   $0xe0, %rsp              
	popq   %rbp                     
	retq                            
	nopl   (%rax)                   
	movq   %rdx, 0x10(%rsp)         
	pushq  %rbp                     
	subq   $0x30, %rsp              
	leaq   0x80(%rdx), %rbp         
	leaq   0x30(%rbp), %rcx         
	callq  0x140001dc0                ; core::ptr::drop_in_place<enum2$<bevy_dynamic_plugin::loader::DynamicPluginLoadError> >(*mut enum2$<bevy_dynamic_plugin::loader::DynamicPluginLoadError>) at mod.rs:507
	nop                             
	addq   $0x30, %rsp              
	popq   %rbp                     
	retq                            
	nopw   %cs:(%rax,%rax)          
	movq   %rdx, 0x10(%rsp)         
	pushq  %rbp                     
	subq   $0x30, %rsp              
	leaq   0x80(%rdx), %rbp         
	leaq   -0x40(%rbp), %rcx        
	callq  0x1400c4bf0                ; core::ptr::drop_in_place<alloc::boxed::Box<dyn$<bevy_app::plugin::Plugin>,alloc::alloc::Global> >(*mut alloc::boxed::Box<dyn$<bevy_app::plugin::Plugin>,alloc::alloc::Global>) at mod.rs:507
	nop                             
	addq   $0x30, %rsp              
	popq   %rbp                     
	retq                            
	nopw   %cs:(%rax,%rax)          
	movq   %rdx, 0x10(%rsp)         
	pushq  %rbp                     
	subq   $0x30, %rsp              
	leaq   0x80(%rdx), %rbp         
	testb  $0x1, 0x17(%rbp)         
	jne    0x14000193f                ; <+367> at loader.rs:63
	jmp    0x140001939                ; <+361> at loader.rs:57
	addq   $0x30, %rsp              
	popq   %rbp                     
	retq                            
	leaq   -0x48(%rbp), %rcx        
	callq  0x1400100b0                ; core::ptr::drop_in_place<libloading::safe::Library>(*mut libloading::safe::Library) at mod.rs:507
	jmp    0x140001939                ; <+361> at loader.rs:57
```
As I reruned the app, I found that addresses in vtable of dyn Plugin changed unnormally.
fc61644124a060bd6268cbb2ce3724e8

### PR DESCRIPTION
**Pull request by BD103**
# Objective

- The current implementation for dynamic plugins is unsound. Please see #11969 for background and justification.
- Closes #11969 and closes #13073 and closes #4843.

## Solution

- Deprecate all dynamic plugin items for Bevy 0.14, with plans to remove them for Bevy 0.15.

## Discussion

One thing I want to make clear is that I'm not opposed to dynamic plugins _in general_. I think they can be handy, especially for DLC and modding, but I think the current system is the wrong approach. It's too much of a footgun for the meager benefit is provides.

---

## Changelog

- Deprecated the current dynamic plugin system.
  - Dynamic plugins will be removed in Bevy 0.15. For now you can continue using them by marking your code with `#[allow(deprecated)]`.

## Migration Guide

If possible, remove all usage of dynamic plugins.

```rust
// Old
#[derive(DynamicPlugin)]
pub struct MyPlugin;

App::new()
    .load_plugin("path/to/plugin")
    .run();

// New
pub struct MyPlugin;

App::new()
    .add_plugins(MyPlugin)
    .run();
```

If you are unable to do that, you may temporarily silence the deprecation warnings.

```rust
#[allow(deprecated)]
```

Please note that the current dynamic plugin system will be removed by the next major Bevy release, so you will have to migrate eventually. You may be interested in these safer alternatives:

- [Bevy Assets - Scripting]: Scripting and modding libraries for Bevy
- [Bevy Assets - Development tools]: Hot reloading and other development functionality
- [`stabby`]: Stable Rust ABI

[Bevy Assets - Scripting]: https://bevyengine.org/assets/#scripting
[Bevy Assets - Development tools]: https://bevyengine.org/assets/#development-tools
[`stabby`]: https://github.com/ZettaScaleLabs/stabby

### CODE REVIEW

**Comment by BD103** [comment]
I've added the "needs release notes" label, though I can be convinced that its impact is so small that it does not warrant them.

**Comment by alice-i-cecile** [comment]
Previously attempted in https://github.com/bevyengine/bevy/pull/3893

See https://github.com/bevyengine/bevy/pull/3893#issuecomment-1055247308 for Cart's opinion at the time.

My position remains about the same as it was then:

1. Improving this crate is a poor use of our organizational time currently
2. There have been approximately 0 meaningful PRs to the crate ever
3. It presents a misleading and unsafe rabbit hole for new users

**Review by alice-i-cecile — APPROVED** [review]

**Comment by mockersf** [comment]
maybe the deprecated comment could redirect to something like "go comment on this pr if you see this message" to encourage potential users to report back

File: crates/bevy_derive/src/lib.rs [hunk 1]
```diff
@@ -19,8 +19,15 @@ use proc_macro::TokenStream;
 use quote::format_ident;
 
 /// Generates a dynamic plugin entry point function for the given `Plugin` type.
+///
+/// This is deprecated since 0.14. The current dynamic plugin system is unsound and will be removed in 0.15.
```
Comment (BD103) [inline crates/bevy_derive/src/lib.rs:23]: Just as a note, the `deprecated` attribute for proc macros does not work, which is why I'm also including the comment.

**Comment by BD103** [comment]
> maybe the deprecated comment could redirect to something like "go comment on this pr if you see this message" to encourage potential users to report back

I added a deprecation notice in 1b97d99575e322998ec4582cfc16573f4abb4b2e. Hopefully if the alternatives listed do not support someone's use-case, they will comment here. (It may help designing a new API!)

**Review by mockersf — APPROVED** [review]

**Review by soqb — APPROVED** [review]
yeah, this makes sense. working with this crate requires a lot of finesse, and from my woes a few years :eyes: ago, once you have the conceptual understanding needed to *use* this crate, its really not very much work to implement it from scratch yourself.

**Comment by nerdachse** [comment]
I am sorry, how again is this controversial? I haven't seen any comment indicating such.

**Comment by NthTensor** [comment]
This was controversial the last time it was tried, which makes this sort of controversial-by-default.

**Comment by BD103** [comment]
> I am sorry, how again is this controversial? I haven't seen any comment indicating such.

@cart disagreed with this change last time it was attempted. (https://github.com/bevyengine/bevy/pull/3893#issuecomment-1055247308) No one has picked up dynamic plugins and tried to improve it since deprecating it was last attempted.

Furthermore, I think `bevy_dynamic_plugin` even _existing_ in the main Bevy project is encouraging users to use it instead of making their own, better alternatives. As someone mentioned on Discord, Bevy has a reputation for reliability (partially due to being written in Rust). I would argue that dynamic plugins are quite _unreliable_, hurting this reputation. They are simple enough that if someone wanted to use them, they could just copy the code. I think they should do this, because it puts the responsibility on _them_ and not _us_.

**Review by cart — APPROVED** [review]
I relent. A bit bummed that we're removing useful baseline functionality, but I agree that using it soundly is hard and that exposes people to risk. I won't fight this anymore :)

**Comment by alice-i-cecile** [comment]
Thank you to everyone involved with the authoring or reviewing of this PR! This work is relatively important and needs release notes! Head over to https://github.com/bevyengine/bevy-website/issues/1321 if you'd like to help out.

**Comment by bjorn3** [comment]
> It is disappointing to see that dynamic plugins are deprecated and unavailable

You can still do dynamic plugins. If necessary by literally copying the code that was removed here into your own code.

> this is the absolute most important feature we need for a proper bevy editor. Without this, bevy editor plugins need to be hardcoded in the TOML file (correct?) which seems like a bad solution.

The code that was removed here doesn't help much for a bevy editor I would think. It fundamentally requires you to link against the exact same libbevy_dynamic.so (and all .rmeta files for all (in)direct dependencies of bevy) compiled by the exact same rustc version, which you can basically only guarantee if you compile the editor yourself, at which point editing Cargo.toml for the editor wouldn't be much worse. Having actually usable editor plugins would require reflection and either something like stabby or wasm, neither of which would be able to benefit from the code that was removed in this PR anyway.

Disclaimer: This is my personal opinion and not representing that of any of the Bevy developers.

**Comment by BD103** [comment]
Agreed with @bjorn3. If we _truly_ want dynamic plugins for the editor, there are better ways to accomplish that than this removed code.

(For example, what if editor plugins were distributed as WASM files? We could load and run them in a safe, sandboxed runtime with greater protections than dynamic linking.)
