### PR TITLE
Replace all labels with interned labels

### LINKED ISSUE #5569: Revisit labels again
## What problem does this solve or what need does it fill?

#4957 made labels much cheaper, but also made them much less capable. By nature, the design moves away from using `Hash` and `PartialEq` impls to using `(TypeId, &'static str)` tuples for comparisons. (#5377 recovers constant-time performance by adding a `u64`, so the `&'static str` or formatter can just be there for log/debug purposes).

Beyond simple fieldless enum variants, this change basically prevents using different *values* to mean different labels, e.g. `MyLabel(T)`, which I think is a big ergonomics hit.

Under bevyengine/rfcs#45, the plan for state machines is to facilitate linking each state to a pair of on-enter and on-exit schedules, which would run from within an exclusive system handling state transitions. The implementation for this in #4391 was looking extremely simple.

```rust
pub struct CurrentState(pub S);
pub struct NextState(pub S);
pub struct PrevState(pub S);

#[derive(SystemLabel)]
pub struct OnEnter<S: State>(pub S);

#[derive(SystemLabel)]
pub struct OnExit<S: State>(pub S);

pub fn apply_state_transition<S: State>(world: &mut World) {
    world.resource_scope(|world, mut state: Mut<CurrentState<S>>| {
        if world.resource::<NextState<S>>().0.is_some() {
            let new_state = world.resource_mut::<NextState<S>>().0.take().unwrap();
            let old_state = std::mem::replace(&mut state.0, new_state.clone());
            world.resource_mut::<PrevState<S>>().0 = Some(old_state.clone());
            run_schedule(OnExit(old_state), world);
            run_schedule(OnEnter(new_state), world);
        }
    });
}
```

```rust
pub fn run_schedule(system_set: impl SystemLabel, world: &mut World) {
    let systems = world.resource_mut::<Systems>();
    let schedule = systems.take_schedule(&system_set));
    
    schedule.run(world);

    let systems = world.resource_mut::<Systems>();
    systems.return_schedule(&system_set, schedule);
}
```

The `apply_state_transition` system just reads the state resources, then loads and runs their appropriate schedules (if they exist). What was really nice was that it was just a convenient export of something users could do on their own.

However, this is no longer possible, and I'm not sure how to adapt it for the current 0.8 build. Since I don't know `S`, I don't know how to produce a unique `&'static str` / `u64` for each label value. There's probably some way to do it, but having to do a special manual impl for a simple wrapper type feels ridiculous. As one of its main authors, I believe that what's coming with stageless will lead to apps having more labels, so increasing friction here by reducing what users can do with even POD types seems counterproductive.

It's true that schedule construction had too much boxing, but those costs were infrequent, basically once at startup, so I'm skeptical the tradeoff we made was worth it.

## What solution would you like?

I haven't figured out an obvious solution yet, but the essence of the problem is that:

1. bevy wants plain integers for efficient schedule construction
2. user wants names for logging/debugging

All the boxing happened in the [descriptor API methods][1], where we had to collect all `SystemLabel` trait objects into a struct before handing it to the `SystemStage`, so we ended up boxing each and every use of a label.

(edit) Removing that excessive boxing seems to have been the main reason people supported the new scheme.

Since `add_system` is a method on `SystemStage`, could we add a `HashMap<SystemLabelId, Box<dyn SystemLabel>>` field and somehow pass a `&mut` reference to it into the descriptor process? If we can do that, we'd only box each label once and different values could mean different labels again. The `*LabelId` types can just wrap `(type_id, value_hash)` tuples (currently same size as a `u128`).

## What alternative(s) have you considered?

1. Same solution as above, except initialize the map as a static variable, e.g. using a `OnceCell`, and have the descriptor methods access that. It's fine for a system label value to have the same ID, program-wide.
2. Revert the changes. Slightly faster schedule construction isn't all that important if it only happens once or twice.
3. Stay the course and add some magic macro attributes to enable some common patterns.

[1]: https://github.com/bevyengine/bevy/blob/b1c3e9862d06f5d8ec0fca3ce20d7318cff2d456/crates/bevy_ecs/src/schedule/system_descriptor.rs

### LINKED ISSUE #9335: `ScheduleLabel` proc macro produces code that requires additional dependency apart from its originating crate
## Bevy version

0.11 and/or main branch

## What you did

Put
```rust
use bevy_ecs::schedule::ScheduleLabel;

#[derive(ScheduleLabel, Clone, Debug, PartialEq, Eq, Hash)]
pub struct Render;
```

in my bevy mod/plugin project

## What went wrong

```
error[E0433]: failed to resolve: use of undeclared crate or module `bevy_utils`
 --> src\render_schedule.rs:3:10
  |
3 | #[derive(ScheduleLabel, Clone, Debug, PartialEq, Eq, Hash)]
  |          ^^^^^^^^^^^^^ use of undeclared crate or module `bevy_utils`
  |
  = note: this error originates in the derive macro `ScheduleLabel` (in Nightly builds, run with -Z macro-backtrace for more info)
```

The code generated by the macro contains
```rust
fn as_dyn_eq(&self) -> &dyn bevy_utils::label::DynEq {
    self
}
```
but I don't have `bevy_utils` in scope or even as a dependency. It's unclear to me why a derive from `bevy_ecs` should produce code that requires an entirely different crate to work. Typically if macros require types from other crates to work, they re-export them and refer to them by their re-exported path.

## Additional information

My Cargo.toml only has
```toml
# Same thing happens with Bevy's git@main
bevy_app = { version = "0.11" }
bevy_ecs = { version = "0.11" }
```
because those are the only bits of Bevy my crate needs. Or so I thought, anyway.

### PR DESCRIPTION
**Pull request by geieredgar**
# Objective

First of all, this PR took heavy inspiration from #7760 and #5715. It intends to also fix #5569, but with a slightly different approach.

This also fixes #9335 by reexporting `DynEq`.

## Solution

The advantage of this API is that we can intern a value without allocating for zero-sized-types and for enum variants that have no fields. This PR does this automatically in the `SystemSet` and `ScheduleLabel` derive macros for unit structs and fieldless enum variants. So this should cover many internal and external use cases of `SystemSet` and `ScheduleLabel`.  In these optimal use cases, no memory will be allocated.

- The interning returns a `Interned<dyn SystemSet>`, which is just a wrapper around a `&'static dyn SystemSet`.
- `Hash` and `Eq` are implemented in terms of the pointer value of the reference, similar to my first approach of anonymous system sets in #7676.
- Therefore, `Interned<T>` does not implement `Borrow<T>`, only `Deref`. 
- The debug output of `Interned<T>` is the same as the interned value.

Edit: 
- `AppLabel` is now also interned and the old `derive_label`/`define_label` macros were replaced with the new interning implementation.
- Anonymous set ids are reused for different `Schedule`s, reducing the amount of leaked memory.

### Pros
- `InternedSystemSet` and `InternedScheduleLabel` behave very similar to the current `BoxedSystemSet` and `BoxedScheduleLabel`, but can be copied without an allocation.
- Many use cases don't allocate at all.
- Very fast lookups and comparisons when using `InternedSystemSet` and `InternedScheduleLabel`.
- The `intern` module might be usable in other areas.
- `Interned{ScheduleLabel, SystemSet, AppLabel}` does implement `{ScheduleLabel, SystemSet, AppLabel}`, increasing ergonomics.

### Cons
- Implementors of `SystemSet` and `ScheduleLabel` still need to implement `Hash` and `Eq` (and `Clone`) for it to work.

### Added

- Added `intern` module to `bevy_utils`.
- Added reexports of `DynEq` to `bevy_ecs` and `bevy_app`.

### Changed

- Replaced `BoxedSystemSet` and `BoxedScheduleLabel` with `InternedSystemSet` and `InternedScheduleLabel`.
- Replaced `impl AsRef<dyn ScheduleLabel>` with `impl ScheduleLabel`.
- Replaced `AppLabelId` with `InternedAppLabel`.
- Changed `AppLabel` to use `Debug` for error messages.
- Changed `AppLabel` to use interning.
- Changed `define_label`/`derive_label` to use interning. 
- Replaced `define_boxed_label`/`derive_boxed_label` with `define_label`/`derive_label`.
- Changed anonymous set ids to be only unique inside a schedule, not globally. 
- Made interned label types implement their label trait. 

### Removed

- Removed `define_boxed_label` and `derive_boxed_label`. 

## Migration guide

- Replace `BoxedScheduleLabel` and `Box<dyn ScheduleLabel>` with `InternedScheduleLabel` or `Interned<dyn ScheduleLabel>`.
- Replace `BoxedSystemSet` and `Box<dyn SystemSet>` with `InternedSystemSet` or `Interned<dyn SystemSet>`.
- Replace `AppLabelId` with `InternedAppLabel` or `Interned<dyn AppLabel>`.
- Types manually implementing `ScheduleLabel`, `AppLabel` or `SystemSet` need to implement:
  - `dyn_hash` directly instead of implementing `DynHash`
  - `as_dyn_eq`
- Pass labels to `World::try_schedule_scope`, `World::schedule_scope`, `World::try_run_schedule`. `World::run_schedule`, `Schedules::remove`, `Schedules::remove_entry`, `Schedules::contains`, `Schedules::get` and `Schedules::get_mut` by value instead of by reference.

### CODE REVIEW

**Comment by alice-i-cecile** [comment]
Neat! I've added Controversial to all three of these PRs, to make sure the ECS SMEs consciously choose between them.

File: crates/bevy_ecs/src/schedule/set.rs [hunk 1]
```diff
@@ -34,7 +39,37 @@ pub trait SystemSet: DynHash + Debug + Send + Sync + 'static {
     }
 
     /// Creates a boxed clone of the label corresponding to this system set.
-    fn dyn_clone(&self) -> Box<dyn SystemSet>;
+    fn dyn_leak(&self) -> &'static dyn SystemSet;
+    fn dyn_intern(&self) -> Interned<dyn SystemSet>
+    where
+        Self: Sized,
```
Comment (JoJoJet) [inline crates/bevy_ecs/src/schedule/set.rs:45]: Doesn't requiring `Self: Sized` contradict the `dyn_` part of this function's name?

**Review by JoJoJet — COMMENTED** [review]
I've scanned over this quickly, and it definitely seems like a promising approach. Very similar to #7760 but potentially preferable.

Just for clarity, what are the differences between `SystemSet::dyn_intern`, `Intern::intern`, and `IntoInterned::into_interned`? Is it possible to simplify or combine these methods some way?

**Comment by geieredgar** [comment]
@JoJoJet I've replaced `SystemSet::dyn_intern` `Intern::intern` and `IntoInterned::into_interned` with the standard `Into<Interned<T>>::into`.

The functions that took `impl AsRef<dyn ScheduleLabel>` as parameter now take `impl Into<InternedScheduleLabel>`, which is implemented by the derive-macro for `ScheduleLabel` for `T` and `&T`, so it almost works the same as before.

I've also introduced a new trait and method `StaticRef::static_ref` which can be used to provide a consistent static reference to a value equal to `self`. This is used to further optimize the interning process, since interning a value for which a static reference can be provided doesn't need to lock the internal hash set anymore.

File: crates/bevy_ecs/src/schedule/set.rs (hunk 1 above)
Comment (geieredgar) [reply crates/bevy_ecs/src/schedule/set.rs]: You are right, I have chosen this name because I didn't want an conflict between `Intern::intern` (which is implemented by `dyn SystemSet`) and this method. 

Since this was only a convenience method to be able to write `x.dyn_intern()` instead of `(&x as &dyn SystemSet).intern()`, I removed it.

File: crates/bevy_utils/src/intern.rs [hunk 2]
```diff
@@ -0,0 +1,310 @@
...
+    ///         (Some(x), Some(y)) => std::ptr::eq(x, y),
+    ///         _ => false,
+    ///     }
+    /// }
+    /// ```
+    fn static_ref(&self) -> Option<&'static Self>;
+}
+
+/// An optimized [`Interner`] for  types that implement [`StaticRef`].
+pub struct OptimizedInterner<T: ?Sized + 'static>(Interner<T>);
```
Comment (JoJoJet) [inline crates/bevy_utils/src/intern.rs:178]: This is a good optimization, but why is `OptimizedInterner` separate from `Interner`? I can't imagine why you'd want an interner that doesn't perform this optimization. Would it be possible to further simplify this by combining these types, and potentially also combining `StaticRef` with `Leak`?

File: crates/bevy_app/src/app.rs [hunk 3]
```diff
@@ -379,9 +379,10 @@ impl App {
         schedule: impl ScheduleLabel,
         systems: impl IntoSystemConfigs<M>,
     ) -> &mut Self {
+        let schedule: InternedScheduleLabel = (&schedule as &dyn ScheduleLabel).into();
```
Comment (JoJoJet) [inline crates/bevy_app/src/app.rs:382]:
```suggestion
        let schedule = InternedScheduleLabel::from(&schedule as &dyn ScheduleLabel);
```

Not super important, but I think this syntax is preferable. Same for all of the other places this is used.

**Review by JoJoJet — COMMENTED** [review]
Can you also switch `AppLabel` to use interned labels? It still uses pseudo-stringly typed labels, and I'd rather not leave that relic around.

File: crates/bevy_ecs/src/schedule/set.rs [hunk 4]
```diff
@@ -30,8 +33,55 @@ pub trait SystemSet: DynHash + Debug + Send + Sync + 'static {
     fn is_anonymous(&self) -> bool {
         false
     }
+
     /// Creates a boxed clone of the label corresponding to this system set.
     fn dyn_clone(&self) -> Box<dyn SystemSet>;
```
Comment (JoJoJet) [inline crates/bevy_ecs/src/schedule/set.rs:38]: This method should probably be removed.

File: crates/bevy_utils/src/intern.rs [hunk 5]
```diff
@@ -0,0 +1,310 @@
...
+    ///
+    /// where `ptr_eq` is defined as :
+    /// ```
+    /// fn ptr_eq<T>(x: Option<&'static T>, y: Option<&'static T>) -> bool {
+    ///     match (x, y) {
+    ///         (Some(x), Some(y)) => std::ptr::eq(x, y),
+    ///         _ => false,
+    ///     }
+    /// }
+    /// ```
```
Comment (JoJoJet) [inline crates/bevy_utils/src/intern.rs:173]:
```suggestion
    /// The following invariant must be hold:
    ///
    /// `ptr_eq(a.static_ref(), b.static_ref()) == true` only if `a == b`
    ///
    /// where `ptr_eq` is defined as :
    /// ```
    /// fn ptr_eq<T>(x: Option<&'static T>, y: Option<&'static T>) -> bool {
    ///     match (x, y) {
    ///         (Some(x), Some(y)) => std::ptr::eq(x, y),
    ///         _ => false,
    ///     }
    /// }
    /// ```
```

I believe the "if and only if" choice of words is slightly incorrect here. If `static_ref` returns `None`, then `ptr_eq` well evaluate to `false`, but `a` can still be equal to `b`.

File: crates/bevy_app/src/app.rs (hunk 3 above)
Comment (geieredgar) [reply crates/bevy_app/src/app.rs]: I agree. Changed all places this was used.

File: crates/bevy_ecs/src/schedule/set.rs (hunk 4 above)
Comment (geieredgar) [reply crates/bevy_ecs/src/schedule/set.rs:38]: We cannot remove this, it is used for leaking when `dyn_static_ref` returns `None`.

File: crates/bevy_utils/src/intern.rs (hunk 5 above)
Comment (geieredgar) [reply crates/bevy_utils/src/intern.rs]: You are right, but the invariants are a bit more complex:

Basically, if we return `None` we are always safe. In the cases we return `Some`, we not only need to make sure that the pointer is identical for all equal values but also that the pointer is different for unequal values. 
And we cannot mix `Some` and `None` for equal values.

I resolved this by splitting the invariant into two parts.

File: crates/bevy_utils/src/intern.rs (hunk 2 above)
Comment (geieredgar) [reply crates/bevy_utils/src/intern.rs]: I actually started with `static_ref` being a part of `Leak`, but then I realized that the invariant needs to be hold over all implementations of `Leak` and is therefore a property of the interned type and not of the `Leak` implementation.
Therefore I am against combining `StaticRef` with `Leak`.

Regarding the separation of `OptimizedInterner` and `Interner`, my thought was that it might be useful to create an interner for types that do not implement `StaticRef`, which could be the case for foreign types. But this is more of a hypothetical scenario, so I am open to combining those. If we later want to have an Interner for `str` we could also implement `StaticRef` for `str` instead.

**Comment by geieredgar** [comment]
@JoJoJet Regarding `AppLabel`, is it okay if I do the switch in a follow-up PR?

**Comment by JoJoJet** [comment]
I guess that's fine, but is there a reason not to do it now? As far as I know, you'd just have to change a `define_label!` to `define_interned_label!`, and update some callsites.

**Comment by geieredgar** [comment]
OK, after giving it a second thought, I've decided to the `AppLabel` switch inside this PR. 

I also changed `AnonymousSet` to not use globally unique ids, and use ids only unique inside the given `Schedule`.  This means that we are not increasing the leaked memory indefinitely when the user creates `Schedules` repeatedly. Instead the amount of memory leaked by `AnonymousSet`s depends now on the `Schedule` that contained the most anonymous sets.

File: crates/bevy_utils/src/intern.rs (hunk 2 above)
Comment (geieredgar) [reply crates/bevy_utils/src/intern.rs]: I've merged the `OptimizedInterner` into `Interner`.

**Comment by JoJoJet** [comment]
Thank you for implementing my suggestions. I'll try to review this more closely today.

**Comment by JoJoJet** [comment]
I finally got around to this. I have a couple more ideas for how the API can be refined. Rather than going back-and-forth, I opened a PR to your branch: https://github.com/geieredgar/bevy/pull/1.

As always, feel free to voice any concerns you have with my suggestions.

File: crates/bevy_utils/src/intern.rs [hunk 6]
```diff
@@ -0,0 +1,291 @@
...
+///
+/// For details on interning, see [the module level docs](self).
+///
+/// # Implementation details
+///
+/// This is just a reference to a value with an `'static` lifetime.
+//
+// This implements [`Copy`], [`Clone`], [`PartialEq`], [`Eq`] and [`Hash`] regardles of what `T`
+// implements, because it only uses the pointer to the value and not the value itself.
+// Therefore it MUST NEVER implement [`Borrow`](`std::borrow::Borrow`).
```
Comment (JoJoJet) [inline crates/bevy_utils/src/intern.rs:27]:
```suggestion
/// # Comparisons
/// 
/// Interned values use reference equality, meaning they implement [`Eq`]
/// and [`Hash`] regardless of whether `T` implements these traits.
/// Two interned values will only compare equal if they were interned using
/// the same [`Interner`] instance.
// NOTE: This type must NEVER implement Borrow since it does not obey that trait's invariants.
///
/// ```
/// # use bevy_utils::intern::*;
/// #[derive(PartialEq, Eq, Hash)]
/// struct Value(i32);
/// impl Leak for Value {
///     // ...
/// # fn leak(&self) -> &'static Self { Box::leak(Box::new(Value(self.0))) }
/// }
/// let interner_1 = Interner::new();
/// let interner_2 = Interner::new();
/// // Even though both values are identical, their interned forms do not
/// // compare equal as they use different interner instances.
/// assert_ne!(interner_1.intern(&Value(42)), interner_2.intern(&Value(42)));
/// ```
```

I think this behavior is important to document and test for. Feel free to tweak the phrasing.

**Review by JoJoJet — APPROVED** [review]
I think this PR is in a good state now! I just have a minor documentation suggestion.

**Comment by JoJoJet** [comment]
> Interned<dyn SystemSet> does and probably should not implement SystemSet, I think for the same reasons that Box<dyn SystemSet> doesn't, but I haven't looked up all the discussions about that. Generally, Interned(x) and x should not be treated as the same thing when it comes to hash values and comparisons.

This can be removed from the cons list, and added to the pros.

File: crates/bevy_utils/src/intern.rs [hunk 7]
```diff
@@ -0,0 +1,306 @@
...
+
+/// An interned value. Will stay valid until the end of the program and will not drop.
+///
+/// For details on interning, see [the module level docs](self).
+///
+/// # Comparisons
+///
+/// Interned values use reference equality, meaning they implement [`Eq`]
+/// and [`Hash`] regardless of whether `T` implements these traits.
+/// Two interned values will only compare equal if they were interned using
```
Comment (JoJoJet) [inline crates/bevy_utils/src/intern.rs:25]:
```suggestion
/// Two interned values are only guaranteed to compare equal if they were interned using
```

A slight correction to this phrasing I wrote. Type that implement `static_ref` will compare equal regardless of the interner used.

File: crates/bevy_macro_utils/src/lib.rs [hunk 8]
```diff
@@ -184,7 +184,47 @@ pub fn derive_boxed_label(input: syn::DeriveInput, trait_path: &syn::Path) -> To
...
+                        use_fallback_variant = true;
+                        None
+                    }
+                })
+                .collect();
+            if use_fallback_variant {
+                quote! {
+                    match self {
+                        #(#variants)*
+                        _ => quote! { std::option::Option::None }
```
Comment (JoJoJet) [inline crates/bevy_macro_utils/src/lib.rs:215]: Is it right for there to be a `quote!` inside of a `quote!` like this? Is this branch covered by any test cases?

Comment (geieredgar) [reply crates/bevy_macro_utils/src/lib.rs]: No, this wasn't right. I should have added tests for the derive macros sooner, sorry. Now all types of structs and enum variants are tested.

**Review by nicopap — APPROVED** [review]
I think this approach is sound. Pretty neat.

I think it's possible to extend this so that it doesn't require leaking and a global `HashSet` for stuff like `OnEnter(state)`. But as-is I think the PR works.

I see a 1% perf increase on the `1000_schedule` benchmark, but I wouldn't put too much weight on it.

The only blocker for me is the duplicate code in macros & doc comment.

To summarize the approach taken here:

This pretty much defines a `static` reference per value added as label.
   * `Leak::leak`, despite the name, most of the time won't leak anything, but instead return a reference to a constant value). When the value can't be known at compile time, `leak` does leak using `Box::leak`.
   * The comparison of labels is fast because it only checks reference equality (`Interned<dyn Foo>` is a `&'static dyn Foo` and the `eq` impl compares the reference). this is a single `u64` comparison vs a trait object method call in the previous implementation.
   * Interestingly, each label type has its own `Interned<T>` type, and you can access the underlying `T`.
   * This is how `Debug` is implemented, it's a fairly natural extension of the implementation.

File: crates/bevy_ecs/macros/src/set.rs [hunk 9]
```diff
@@ -21,12 +25,65 @@ pub fn derive_set(input: syn::DeriveInput, trait_path: &syn::Path) -> TokenStrea
...
+                        _ => std::option::Option::None
+                    }
+                }
+            } else {
+                quote! {
+                    match self {
+                        #(#variants)*
+                    }
+                }
+            }
```
[the remark this answers is not in the document]
Comment (JoJoJet) [reply crates/bevy_ecs/macros/src/set.rs:65]: I'd remove `use_fallback_variant` flag altogether:

```rust
quote! {
    match self {
        #(#variatns)*
        #[allow(unreachable_patterns)]
        _ => None,
    }
}
```

File: crates/bevy_utils/src/intern.rs [hunk 10]
```diff
@@ -0,0 +1,306 @@
...
+}
+
+/// A thread-safe interner which can be used to create [`Interned<T>`] from `&T`
+///
+/// For details on interning, see [the module level docs](self).
+///
+/// The implementation ensures that two equal values return two equal [`Interned<T>`] values.
+///
+/// To use an [`Interner<T>`], `T` must implement [`Leak`], [`Hash`] and [`Eq`].
+pub struct Interner<T: ?Sized + 'static>(OnceLock<RwLock<HashSet<&'static T>>>);
```
[the remark this answers is not in the document]
Comment (JoJoJet) [reply crates/bevy_utils/src/intern.rs:148]: That was essentially the approach used in #4957. It ended up being too restrictive, since it forbade `OnEnter()` schedule labels (see #5569).

File: crates/bevy_utils/src/label.rs [hunk 11]
```diff
@@ -95,124 +94,98 @@ macro_rules! define_boxed_label {
...
+            fn dyn_static_ref(&self) -> Option<&'static dyn $label_trait_name> {
+                None
             }
-        }
 
-        impl Clone for Box<dyn $label_trait_name> {
-            fn clone(&self) -> Self {
-                self.dyn_clone()
+            /// Returns an [`Interned`](bevy_utils::intern::Interned) value corresponding to `self`.
+            fn intern(&self) -> ::bevy_utils::intern::Interned<dyn $label_trait_name>
```
[the remark this answers is not in the document]
Comment (geieredgar) [reply crates/bevy_utils/src/label.rs]: Fixed.

File: crates/bevy_macro_utils/src/lib.rs [hunk 12]
```diff
@@ -196,127 +236,13 @@ pub fn derive_boxed_label(input: syn::DeriveInput, trait_path: &syn::Path) -> To
...
-            }
-            .into();
-        }
-    };
-
-    (quote! {
-        impl #impl_generics #trait_path for #ident #ty_generics #where_clause {
-            fn as_str(&self) -> &'static str {
-                #as_str
+            fn dyn_static_ref(&self) -> std::option::Option<&'static dyn #trait_path> {
```
[the remark this answers is not in the document]
Comment (geieredgar) [reply crates/bevy_macro_utils/src/lib.rs]: I prefixed (hopefully) all occurrences of `std` with `::`. Thanks for pointing this out.

File: crates/bevy_derive/src/lib.rs [hunk 13]
```diff
@@ -203,10 +203,10 @@ pub fn derive_enum_variant_meta(input: TokenStream) -> TokenStream {
 ///
 /// This works only for unit structs, or enums with only unit variants.
 /// You may force a struct or variant to behave as if it were fieldless with `#[app_label(ignore_fields)]`.
```
[the remark this answers is not in the document]
Comment (geieredgar) [reply crates/bevy_derive/src/lib.rs]: Yes, it was wrong. Fixed that.

File: crates/bevy_ecs/macros/src/set.rs (hunk 9 above)
[the remark this answers is not in the document]
Comment (geieredgar) [reply crates/bevy_ecs/macros/src/set.rs]: I've changed the code to use
```rust
let fallback_variant = if variants.len() < data.variants.len() {
    quote!(_ => ::std::option::Option::None,)
} else {
    quote!()
};
quote! {
    match self {
        #(#variants)*
        #fallback_variant
    }
}
```

File: crates/bevy_macro_utils/src/lib.rs [hunk 14]
```diff
@@ -184,7 +184,47 @@ pub fn derive_boxed_label(input: syn::DeriveInput, trait_path: &syn::Path) -> To
...
+                }
+            } else {
+                quote! {
+                    match self {
+                        #(#variants)*
+                    }
+                }
+            }
+        }
+        syn::Data::Union(_) => quote! { std::option::Option::None },
```
[the remark this answers is not in the document]
Comment (geieredgar) [reply crates/bevy_macro_utils/src/lib.rs]: I've extracted the code into a `static_ref_impl` function inside `bevy_macro_utils`.

File: crates/bevy_utils/src/label.rs [hunk 15]
```diff
@@ -95,124 +94,98 @@ macro_rules! define_boxed_label {
...
-        impl ::std::convert::AsRef<dyn $label_trait_name> for dyn $label_trait_name {
-            #[inline]
-            fn as_ref(&self) -> &Self {
-                self
+            /// Returns a static reference to a value equal to `self`, if possible.
+            /// This method is used to optimize [interning](bevy_utils::intern).
+            ///
+            /// # Invariant
+            ///
+            /// The following invariants must be hold:
```
[the remark this answers is not in the document]
Comment (geieredgar) [reply crates/bevy_utils/src/label.rs]: Fixed. Thank you for spotting those.

File: crates/bevy_utils/src/label.rs [hunk 16]
```diff
@@ -95,124 +94,98 @@ macro_rules! define_boxed_label {
...
+            ///     match (x, y) {
+            ///         (Some(x), Some(y)) => !std::ptr::eq(x, y),
+            ///         (None, None) => true,
+            ///         _ => false,
+            ///     }
+            /// }
+            /// ```
+            ///
+            /// # Provided implementation
+            ///
```
[the remark this answers is not in the document]
Comment (geieredgar) [reply crates/bevy_utils/src/label.rs]: I also removed the headings in `SystemSet` and `Leak`.

File: crates/bevy_ecs/macros/src/set.rs [hunk 17]
```diff
@@ -21,12 +25,65 @@ pub fn derive_set(input: syn::DeriveInput, trait_path: &syn::Path) -> TokenStrea
...
+        }
+        syn::Data::Union(_) => quote! { std::option::Option::None },
```
[the remark this answers is not in the document]
Comment (geieredgar) [reply crates/bevy_ecs/macros/src/set.rs]: I agree, the derive macros will now fail again for unions.

File: crates/bevy_utils/src/intern.rs (hunk 10 above)
[the remark this answers is not in the document]
Comment (geieredgar) [reply crates/bevy_utils/src/intern.rs:146]: We need this to support e.g.  `OnEnter`, `OnExit` or `AnonymousSet`. Note that we only have one `Interner` for `dyn SystemSet` and not for every type `T` that implements `SystemSet`.

[the remark this answers is not in the document]
Comment (nicopap) [reply crates/bevy_utils/src/intern.rs:146]: Yeah. I think it is out of scope for this PR. I understand better now why it's not trivial to accomplish.

File: crates/bevy_ecs/src/schedule/set.rs [hunk 18]
```diff
@@ -202,14 +312,173 @@ mod tests {
...
         assert!(world.resource::<Flag>().0);
 
         world.insert_resource(Flag(false));
-        world.run_schedule(boxed);
+        world.run_schedule(interned);
         assert!(world.resource::<Flag>().0);
     }
+
+    #[test]
+    fn test_derive_schedule_label() {
```
[the remark this answers is not in the document]
Comment (geieredgar) [reply crates/bevy_ecs/src/schedule/set.rs:325]: Done.

File: crates/bevy_ecs/macros/src/set.rs (hunk 9 above)
[the remark this answers is not in the document]
Comment (geieredgar) [reply crates/bevy_ecs/macros/src/set.rs]: Ok, I've switched to @JoJoJet's suggestion. I didn't see the comment before posting my own and refreshing the page.

File: crates/bevy_ecs/src/schedule/set.rs [hunk 19]
```diff
@@ -202,14 +310,197 @@ mod tests {
...
```
Comment (JoJoJet) [inline crates/bevy_ecs/src/schedule/set.rs:325]: Can you add test cases for non-unit fieldless structs and enums?

```rust
struct WeirdUnit1 { }

struct WeirdUnit2();

enum WeirdUnitEnum {
   Variant1 {},
    Variant2()
}
```

Comment (geieredgar) [reply crates/bevy_ecs/src/schedule/set.rs:325]: I've added test cases for empty struct and tuple variants, both standalone and as part of an enum. I had to adjust `static_ref_impl` for it to work and stumbled across some weird behavior that is only present in the current stable channel, preventing me from using `&Self::EmptyTuple()` and having to use `&EnumLabel::EmptyTuple()` instead.  

On the Rust playground, [this](https://play.rust-lang.org/?version=stable&mode=release&edition=2021&gist=c544fa6b762881a53a46c8aae4e702a6) compiles, but [this](https://play.rust-lang.org/?version=stable&mode=release&edition=2021&gist=39468824e70ec79869792d83900d95f6) doesn't. Both versions work on the current beta channel.

Comment (JoJoJet) [reply crates/bevy_ecs/src/schedule/set.rs:325]: You should be able to just do `&Self {}`, which would work for unit structs, as well as tuple and named structs with no fields.

Comment (geieredgar) [reply crates/bevy_ecs/src/schedule/set.rs:325]: Ah, you're right. That's very useful to know.

File: crates/bevy_macro_utils/src/static_ref.rs [hunk 20]
```diff
@@ -0,0 +1,40 @@
...
+        }
+        syn::Data::Enum(data) => {
+            let variants: Vec<_> = data
+                .variants
+                .iter()
+                .filter_map(|variant| {
+                    let span = variant.span();
+                    let variant_ident = variant.ident.clone();
+                    if variant.fields.is_empty() {
+                        Some(quote_spanned! { span => Self::#variant_ident{} => ::std::option::Option::Some(&Self::#variant_ident{}), })
```
Comment (nicopap) [inline crates/bevy_macro_utils/src/static_ref.rs:22]: Do we know for sure that

1. Those are unique per variant
2. Two different instances of `Foo::Bar.dyn_static_ref()` always return the same `&'static` reference? It's important since the whole point is to compare the reference instead of the type+value.

It seems like it, given we pass the tests, but we are relying on an implicit behavior.

Comment (geieredgar) [reply crates/bevy_macro_utils/src/static_ref.rs]: Regarding the second point, you are right, I was relying on implicit behavior. [The Rust Reference](https://doc.rust-lang.org/reference/items/constant-items.html#constant-items) states that 

> References to the same constant are not necessarily guaranteed to refer to the same memory address.

Therefore I changed the implementation to use [static items](https://doc.rust-lang.org/reference/items/static-items.html#static-items) instead, which solves this issue, because

> All references to the static refer to the same memory location.

Regarding the first point, I don't see a reason why two variants should share the same reference / memory address, since their representation in memory is different. Of course two different ZSTs can have the same memory address, but the cast to `&dyn` will yield different vtable pointers for different types, so they would not be considered equal.

Comment (geieredgar) [reply crates/bevy_macro_utils/src/static_ref.rs]: Also, because of the restrictions on [generics for static items](https://doc.rust-lang.org/reference/items/static-items.html#statics--generics), types with generic type or const parameters will not have the `static_ref` optimization and have to go through the `Interner`, but will still not cause an allocation if they are ZST.

**Comment by JoJoJet** [comment]
Does this fix #9335?

**Comment by geieredgar** [comment]
> Does this fix #9335?

It does now, but with the cost of having to reexport `DynEq`. The second approach mentioned [here](https://github.com/bevyengine/bevy/issues/9335#issuecomment-1662022284) does not work with making `Interned<dyn T>` implementing `T` without running into the same issues again that were fixed by #8436.

**Comment by JoJoJet** [comment]
Can you add Fixes #9335 to the PR description?

File: crates/bevy_ecs/src/schedule/set.rs [hunk 21]
```diff
@@ -2,57 +2,52 @@ use std::any::TypeId;
...
+
+define_label!(
+    /// Types that identify logical groups of systems.
+    SystemSet,
+    SYSTEM_SET_INTERNER,
+    {
+        /// Returns `Some` if this system set is a [`SystemTypeSet`].
+        fn system_type(&self) -> Option<TypeId> {
+            None
+        }
```
Comment (JoJoJet) [inline crates/bevy_ecs/src/schedule/set.rs:29]:
```suggestion
define_label!(
    /// Types that identify logical groups of systems.
    SystemSet,
    SYSTEM_SET_INTERNER,
    extra_methods: {
        /// Returns `Some` if this system set is a [`SystemTypeSet`].
        fn system_type(&self) -> Option<TypeId> {
            None
        }
```

This suggestion won't compile as-is, but to make it more clear what's happening here, can you add names to these blocks like `extra_methods` and `extra_methods_impl`?

Comment (geieredgar) [reply crates/bevy_ecs/src/schedule/set.rs]: Done. Also rebased the PR on main again.

**Review by JoJoJet — APPROVED** [review]

**Comment by alice-i-cecile** [comment]
@geieredgar I'm pushing to have this in 0.12: are you able to resolve conflicts for us?

**Review by nicopap — COMMENTED** [review]
I've had the time to think about it. And I'm still ambivalent. I don't think the idea is sound. Rust does not guarantee that different static addresses of ZSTs are different. This hinges on ZSTs static references being different if I'm not mistaken

Could we add tests to check that two different interned ZSTs do indeed not compare equal?

Something like

```rust
assert_ne!(UnitLabel1.intern(), UnitLabel2.intern());
```

**Comment by Diddykonga** [comment]
Adding these here:
https://www.reddit.com/r/rust/comments/zfi61k/comment/izc2guh/?utm_source=share&utm_medium=web2x&context=3
https://www.reddit.com/r/rust/comments/zfi61k/comment/izceo6f/?utm_source=share&utm_medium=web2x&context=3

**Comment by geieredgar** [comment]
@nicopap After finding https://github.com/rust-lang/rust/issues/106447 I think you are correct that this approach was unsound, because two equal labels could yield two different pointers. Therefore I removed the `static_ref` optimization completely, so interning will always go through the internal HashMap, guaranteeing that equal labels always return equal pointers.  

I also agree that two different labels cannot yield the same fat pointer when leaking, because then `a.dyn_eq(b)` would return `true`. And currently `ptr::eq` does compare both the address and the metadata, so it should work. However, as shown in https://github.com/rust-lang/rust/issues/106447 this behavior could change in the future.

**Comment by geieredgar** [comment]
I've replaced the use of `std::ptr::eq` with a custom equality comparison, which first checks for equal type ids and then for equal data pointers. Therefore, we don't rely on the vtable pointers anymore.

**Comment by alice-i-cecile** [comment]
@geieredgar this is in the milestone for 0.12, slated for this Saturday. I'm going to do a full review now, but I'm hopeful we can get this in and ship it. Can your resolve merge conflicts?

**Review by alice-i-cecile — APPROVED** [review]
Really cool stuff! The changes in `schedule.rs` and `intern.rs` are the only non-trivial changes: focus your review efforts there.

The breaking changes are acceptable and well-documented, the motivation is sound, I basically understand how this works, and this is incredibly well-tested. I'm comfortable approving this!

**Comment by geieredgar** [comment]
Conflicts are resolved.

**Review by cart — APPROVED** [review]
I'm happy with this approach!

File: crates/bevy_utils/src/intern.rs [hunk 22]
```diff
@@ -0,0 +1,286 @@
...
+}
+
+impl Internable for str {
+    fn leak(&self) -> &'static Self {
+        let str = self.to_owned().into_boxed_str();
+        Box::leak(str)
+    }
+
+    fn ref_eq(&self, other: &Self) -> bool {
+        self.len() == other.len() && self.as_ptr() == other.as_ptr()
```
[the remark this answers is not in the document]
Comment (cart) [reply crates/bevy_utils/src/intern.rs]: Just pushed as I doubt this will be controversial (and in the interest of moving forward).

[the remark this answers is not in the document]
Comment (cart) [reply crates/bevy_utils/src/intern.rs]: I'll leave this open in case anyone wants to discuss.
