### PR TITLE
Allow ordering variable timesteps around fixed timesteps

### LINKED ISSUE #14873: Bevy has no clear schedule for updating a camera's `Transform` when using a fixed time step
## What problem does this solve or what need does it fill?

I'm writing primarily first-person 3D games. My physics engine of choice, Avian, has recently switched from their custom fixed update schedule that ran after `Update` to the real Bevy `FixedMain` schedule, which runs *before* `Update`. Running before update makes sense, as you want to set rendering transforms *after* running the physics.

Now this results in an issue. In first person games, many things are dependent on the current camera rotation. For example, I am currently writing a plugin for picking up props. These want to be as close to the center of the screen as possible while held. This means that I need to update my camera's transform *before* running the physics. So, my order becomes:

1. Read the player's inputs
2. Rotate the camera
3. Run physics

Let's think schedules. The physics need to run in fixed update. The camera rotation *could* run there as well, but ideally, if your framerate allows it, a player should be allowed to update their camera more often. So it needs to be in a variable timestep schedule before fixed update. Hmm, the only one available is `PreUpdate`. But that one also populates the resources needed to read inputs. It's also a popular place to run networking. This means we need to be really careful about our system ordering. Meh. Also, its description says the following:
> [PreUpdate](https://docs.rs/bevy/latest/bevy/app/struct.PreUpdate.html) exists to do “engine/plugin preparation work” that ensures the APIs consumed in [Update](https://docs.rs/bevy/latest/bevy/app/struct.Update.html) are “ready”. [PreUpdate](https://docs.rs/bevy/latest/bevy/app/struct.PreUpdate.html) abstracts out “pre work implementation details”.

The player's camera being rotated while moving the mouse is definitely more than just "pre work implemention details"! In fact, it is part of the core gameplay experience! 
This means that we have no good place to rotate our camera in while following best practices using a very popular camera style.

-----

Bonus issue: what if our physics need to react to `just_pressed` to e.g. shoot a gun when clicking? The fixed update loop will only sometimes catch these events, as it may happen to run 0 times on the frame when we clicked. This means we need to cache the `just_pressed` event somewhere. In which schedule do we do that? `PreUpdate` is more correct for this, as it is "pre work implementation details", but we still need to be careful about ordering.

## What solution would you like?

There are many possibilities. One of them is to add a new schedule between `StateTransition` and `RunFixedMainLoop` called `PreFixedMainLoop` for this use-case.
See @alice-i-cecile's comment below for other options.

## What alternative(s) have you considered?

Leave it as-is and force users to manually add such a schedule.
This is a bit of an issue for me, as I'm trying to write minimal use-case examples for my libraries. If they happen to be first-person and use physics, I need to somehow deal with the fact that I need systems rotating the camera and reading `just_pressed` events. 
I can currently only handle these cleanly by introducing extremely distracting boilerplate to the example or bypassing the issue by letting everything lag one frame behind, which would be teaching the user an antipattern.

## Additional context

See the discussion [started on Discord](https://discord.com/channels/691052431525675048/1124043933886976171/1275886728309375001) and the [continuation](https://discord.com/channels/691052431525675048/749335865876021248/1276190908458598401) for the full context.

In particular, here is a side-by-side demonstration of what happens when you ignore all of this nuance and simply update the camera's transform in `Update`, as I think most people's instinct would be. Left is the version updating stuff correctly as described above, right is the one updating the camera in `Update`:

https://github.com/user-attachments/assets/e569118b-c7fb-4093-b422-e3130b386779

The very noticeable jitter is due to the camera being "one step ahead" of the physics.

### PR DESCRIPTION
**Pull request by janhohenheim**
# Objective

- Fixes #14873, see that issue for a whole lot of context

## Solution

- Add a blessed system set for this stuff. See [this Discord discussion](https://discord.com/channels/691052431525675048/749335865876021248/1276262931327094908).

Note that the gizmo systems, [LWIM](https://github.com/Leafwing-Studios/leafwing-input-manager/pull/522/files#diff-9b59ee4899ad0a5d008889ea89a124a7291316532e42f9f3d6ae842b906fb095R154) and now a new plugin I'm working on are all already ordering against `run_fixed_main_schedule`, so having a dedicated system set should be more robust and hopefully also more discoverable.

---

## ~~Showcase~~

~~I can add a little video of a smooth camera later if this gets merged :)~~
Apparently a release note is not needed, so I'll leave it out. See the changes in the fixed timestep example for usage showcase and the video in #14873 for a more or less accurate video of the effect (it does not use the same solution though, so it is not quite the same)

## Migration Guide

[run_fixed_main_schedule](https://docs.rs/bevy/latest/bevy/time/fn.run_fixed_main_schedule.html) is no longer public. If you used to order against it, use the new dedicated `RunFixedMainLoopSystem` system set instead. You can replace your usage of `run_fixed_main_schedule` one for one by `RunFixedMainLoopSystem::FixedMainLoop`, but it is now more idiomatic to place your systems in either `RunFixedMainLoopSystem::BeforeFixedMainLoop` or `RunFixedMainLoopSystem::AfterFixedMainLoop`

Old:
```rust
app.add_systems(
    RunFixedMainLoop,
    some_system.before(run_fixed_main_schedule)
);
```

New:
```rust
app.add_systems(
    RunFixedMainLoop,
    some_system.in_set(RunFixedMainLoopSystem::BeforeFixedMainLoop)
);
```

### CODE REVIEW

File: crates/bevy_app/src/main_schedule.rs [hunk 1]
```diff
@@ -352,3 +366,38 @@ impl FixedMain {
...
+///   .add_systems(
+///     RunFixedMainLoop,
+///     update_camera_rotation.in_set(AroundFixedMainLoopSystem::Before))
+///   .add_systems(FixedMain, update_physics);
+///
+/// # fn update_camera_rotation() {}
+/// # fn update_physics() {}
+/// ```
+#[derive(Debug, Hash, PartialEq, Eq, Clone, SystemSet)]
+pub enum AroundFixedMainLoopSystem {
```
Comment (alice-i-cecile) [inline crates/bevy_app/src/main_schedule.rs:398]: Actually, a smarter idea: add a third variant for `run_fixed_main_loop` itself!

File: crates/bevy_app/src/main_schedule.rs [hunk 2]
```diff
@@ -352,3 +366,38 @@ impl FixedMain {
...
+    /// Runs before the fixed update logic
```
Comment (alice-i-cecile) [inline crates/bevy_app/src/main_schedule.rs:399]: Suggestions for camera movement logic here would be good.

File: crates/bevy_app/src/main_schedule.rs [hunk 3]
```diff
@@ -352,3 +366,38 @@ impl FixedMain {
...
+    Before,
+    /// Runs after the fixed update logic
```
Comment (alice-i-cecile) [inline crates/bevy_app/src/main_schedule.rs:401]: Suggest putting interpolation logic here.

File: crates/bevy_app/src/main_schedule.rs (hunk 1 above)
Comment (janhohenheim) [reply crates/bevy_app/src/main_schedule.rs:398]: I considered it, but wouldn't you realistically want to schedule things inside `FixedUpdate` and friends instead? Adding this variant seems a bit like a footgun.

Comment (NiseVoid) [reply crates/bevy_app/src/main_schedule.rs:398]: It would be nice for any logic that's "I want it to run after all the other before things but before `FixedMain`", without needing to mention the specific system (which is also easy to get wrong since there's two systems with roughly the same name

Comment (janhohenheim) [reply crates/bevy_app/src/main_schedule.rs:398]: @NiseVoid ah, that's a good point, thanks! I'll implement that later then.

**Comment by janhohenheim** [comment]
Addressed all replies. I made [`run_fixed_main_schedule`](https://docs.rs/bevy/latest/bevy/time/fn.run_fixed_main_schedule.html) private as it is no longer needed, given that we have a proper system set now. I also showcase the new set with its intended usage in the fixed timestep example.

File: crates/bevy_app/src/main_schedule.rs [hunk 4]
```diff
@@ -352,3 +366,94 @@ impl FixedMain {
...
+    /// # fn update_physics() {}
+    /// ```
+    FixedMainLoop,
+    /// Runs after the fixed update logic.
+    ///
+    /// A good example of a system that fits here
+    /// is a system that interpolates the [`Transform`] of an entity between the last and current fixed update.
+    /// See the [fixed timestep example] for more details.
+    ///
+    /// [`Transform`]: https://docs.rs/bevy/latest/bevy/prelude/struct.Transform.html
```
Comment (alice-i-cecile) [inline crates/bevy_app/src/main_schedule.rs:442]: IMO just cut the link and use "transform" generically.

**Review by alice-i-cecile — APPROVED** [review]

File: crates/bevy_app/src/main_schedule.rs (hunk 4 above)
Comment (janhohenheim) [reply crates/bevy_app/src/main_schedule.rs]: [`e9498de` (#14881)](https://github.com/bevyengine/bevy/pull/14881/commits/e9498de5ce354185ee57a770748c56674ae2cbb8)

**Comment by chescock** [comment]
It might be worth noting in the doc comments that the `RunFixedMainLoop` schedule uses `ExecutorKind::SingleThreaded`, so nothing scheduled using these sets will have system-level parallelism.  That's unusual for built-in schedules that users add systems to.

**Comment by janhohenheim** [comment]
@chescock the ordering comes from `foo.after(FixedMainLoop).before(AfterFixedMainLoop)`.
Bottom line is that using multiple variants is cleaner as you get a definitive place to use `.in_set` with. Plus, this won't break in the unlikely case where we split `FixedMainLoop` into multiple system sets.

As for the single-threaded stuff: good point, definitely worth noting or even changing entirely

**Comment by alice-i-cecile** [comment]
IMO we shouldn't change it, but it *should* be noted in the docs for the schedule.

File: crates/bevy_app/src/main_schedule.rs [hunk 5]
```diff
@@ -352,3 +369,96 @@ impl FixedMain {
...
+/// will run exactly once per frame, regardless of the number of fixed updates.
+/// They will also run under a variable timestep.
+///
+/// This is useful for handling things that need to run every frame, but
+/// also need to be read by the fixed update logic. See the individual variants
+/// for examples of what kind of systems should be placed in each.
+///
+/// Note that in contrast to most other Bevy schedules, systems added directly to
+/// [`RunFixedMainLoop`] will *not* be parallelized between each other.
+#[derive(Debug, Hash, PartialEq, Eq, Clone, SystemSet)]
```
Comment (bash) [inline crates/bevy_app/src/main_schedule.rs:384]:
```suggestion
#[derive(Debug, Hash, PartialEq, Eq, Copy, Clone, SystemSet)]
```

**Review by bash — APPROVED** [review]
