### PR TITLE
Fix bubbling of runtime requirements for `#[require(...)]` attribute

### LINKED ISSUE #16406: Runtime required components do not work correctly for components added through `#[require(...)]`
## Bevy version

Bevy 0.15.0-rc.3

## What you did

I have a component, let's say `A`, that requires another component `B` using `#[require(B)]`. `B` then requires another component `C`, but the requirement is registered in a plugin using `app.register_required_components::<B, C>()`.

## What went wrong

When I spawn an entity with `A`, `C` is not added!

Here's a simple test that fails:

```rust
#[test]
fn runtime_required_components() {
    // `A` requires `B` directly.
    #[derive(Component)]
    #[require(B)]
    struct A;

    #[derive(Component, Default)]
    struct B;

    #[derive(Component, Default)]
    struct C;

    let mut world = World::new();

    // `B` requires `C` with runtime registration.
    // This *fails*, but not when using `#[require(C)]` for `B`.
    world.register_required_components::<B, C>();

    // Adding runtime registration for `A -> B` also doesn't help if done after `B -> C`,
    // but it *does* work if done before.
    let _ = world.try_register_required_components::<A, B>();

    let entity = world.spawn(A).id();
    assert!(world.entity(entity).get::<C>().is_some());
}
```

If the entity is spawned with `B` directly, it *does* work:

```rust
#[test]
fn runtime_required_components_2() {
    #[derive(Component)]
    #[require(B)]
    struct A;

    #[derive(Component, Default)]
    struct B;

    #[derive(Component, Default)]
    struct C;

    let mut world = World::new();

    world.register_required_components::<B, C>();

    let _ = world.try_register_required_components::<A, B>();

    let id = world.spawn(B).id();
    assert!(world.entity(id).get::<C>().is_some());
}
```

This implies that the problem is related to runtime requirements not being properly propagated up the inheritance tree if the higher levels use `#[require(...)]`, or if the higher level requirement is added after the lower level requirement.

### PR DESCRIPTION
**Pull request by Jondolf**
# Objective

Fixes #16406.

Currently, the `#[require(...)]` attribute internally registers component requirements using `register_required_components_manual`. This is done recursively in a way where every requirement in the "inheritance tree" is added into a flat `RequiredComponents` hash map with component constructors and inheritance depths stored.

However, this does not consider runtime requirements: if a plugin has already registered `C` as required by `B`, and a component `A` requires `B` through the macro attribute, spawning an entity with `A` won't add `C`. The `required_by` hash set for `C` doesn't have `A`, and the `RequiredComponents` of `A` don't have `C`.

Intuitively, I would've thought that the macro attribute's requirements were always added *before* runtime requirements, and in that case I believe this shouldn't have been an issue. But the macro requirements are based on `Component::register_required_components`, which in a lot of cases (I think) is only called *after* the first time a bundle with the component is inserted. So if a runtime requirement is defined *before* this (as is often the case, during `Plugin::build`), the macro may not take it into account.

## Solution

Register requirements inherited from the `required` component in `register_required_components_manual_unchecked`.

## Testing

I added a test, essentially the same as in #16406, and it now passes. I also ran some of the tests in #16409, and they seem to work as expected. All the existing tests for required components pass.

### CODE REVIEW

File: crates/bevy_ecs/src/component.rs [hunk 1]
```diff
@@ -1232,6 +1230,27 @@ impl Components {
...
+        for (id, component) in required {
+            // Register the inherited required components for the requiree.
+            // The inheritance depth is increased by `1` since this is a component required by the original required component.
+            required_components.register_dynamic(
+                id,
+                component.constructor.clone(),
+                component.inheritance_depth + 1,
+            );
+            self.get_required_by_mut(id).unwrap().insert(requiree);
+        }
```
Comment (Jondolf) [inline crates/bevy_ecs/src/component.rs:1253]: I tried to make this use `register_inherited_required_components` since the logic is pretty much duplicated, but this needs to use the `&mut RequiredComponents`, and the existing method can't take it as an argument nicely because of borrowing issues

**Review by BenjaminBrienen — APPROVED** [review]

**Review by mockersf — APPROVED** [review]

File: crates/bevy_ecs/src/component.rs (hunk 1 above)
Comment (alice-i-cecile) [reply crates/bevy_ecs/src/component.rs:1253]: I've opened an issue for this :)
