### PR TITLE
send Unused event when asset is actually unused

### LINKED ISSUE #12344: Asset will wrongly unload while strong handle is alive under certain circumstances
## Bevy version
0.13

## What you did
In my tests the app has two states(A and B), and an entity with a sprite. when switching states, this entity will be despawned in `OnExit(State::A)`, and spawn a new one entity is identical to the prior one in `OnEnter(State::B)`.

## What went wrong

When respawning it, the sprite will disappear(actually it is there, but the sprite is empty).

This didn't happen in 0.12 version.

## Additional information

Here is my test code(need a custom image as `test.png`):
``` rust
use bevy::prelude::*;
use bevy::render::camera::ScalingMode;

#[derive(Component)]
struct Marker;

#[derive(States, Default, Debug, PartialEq, Eq, Hash, Clone, Copy)]
enum State {
    #[default]
    A,
    B,
}

fn main() {
    App::new()
        .add_plugins((DefaultPlugins.set(WindowPlugin {
            primary_window: Some(Window {
                resolution: (960.0, 540.0).into(),
                resizable: false,
                ..default()
            }),
            ..default()
        }),))
        .init_state::<State>()
        .add_systems(Startup, setup)
        .add_systems(OnExit(State::A), exit_a)
        .add_systems(OnEnter(State::B), enter_b)
        .add_systems(Update, switch)
        //.add_plugin(EditorPlugin::default())
        .run();
}

fn setup(mut cmd: Commands, asset_server: Res<AssetServer>) {
    cmd.spawn(Camera2dBundle {
        projection: OrthographicProjection {
            scaling_mode: ScalingMode::AutoMin {
                min_width: 960.,
                min_height: 540.,
            },
            ..Camera2dBundle::default().projection
        },
        ..default()
    });
    cmd.spawn((
        SpriteBundle {
            texture: asset_server.load("sprites/test.png"),
            ..default()
        },
        Marker,
    ));
}

fn switch(mouse: Res<ButtonInput<MouseButton>>, mut next_state: ResMut<NextState<State>>) {
    if mouse.just_pressed(MouseButton::Left) {
        next_state.set(State::B)
    }
}

fn exit_a(mut cmd: Commands, q: Query<Entity, With<Marker>>) {
    cmd.entity(q.single()).despawn();
}

fn enter_b(mut cmd: Commands, asset_server: Res<AssetServer>) {
    cmd.spawn((SpriteBundle {
        sprite: Sprite {
            custom_size: Some((960., 540.).into()),
            ..default()
        },
        texture: asset_server.load("sprites/test.png"),
        ..default()
    },));
}
```

After click state will switch, and the sprite entity will "disappear".

My assumption is that image asset unloaded the sprite in `OnExit(State::A)`, but it didn't load it again in `OnEnter(State::B)`.

### PR DESCRIPTION
**Pull request by robtfm**
# Objective

fix #12344

## Solution

use existing machinery in track_assets to determine if the asset is unused before firing Asset::Unused event

~~most extract functions use `AssetEvent::Removed` to schedule deletion of render world resources. `RenderAssetPlugin` was using `AssetEvent::Unused` instead.
`Unused` fires when the last strong handle is dropped, even if a new one is created. `Removed` only fires when a new one is not created.
as far as i can see, `Unused` is the same as `Removed` except for this "feature", and that it also fires early if all handles for a loading asset are dropped (`Removed` fires after the loading completes). note that in that case, processing based on `Loaded` won't have been done anyway.
i think we should get rid of `Unused` completely, it is not currently used anywhere (except here, previously) and i think using it is probably always a mistake.
i also am not sure why we keep loading assets that have been dropped while loading, we should probably drop the loader task as well and remove immediately.~~

### CODE REVIEW

**Comment by mockersf** [comment]
this was added in https://github.com/bevyengine/bevy/pull/10520 to allow removing assets from the cpu side and keeping them on the gpu side

**Comment by robtfm** [comment]
@JMS55 on discord: 
> That doesn't seem right. The whole point was I added unused in 0.13 specifically so we would know when to drop a render asset without using removed, as we'll remove it even though it's still in use by the GPU ...

i missed that `Removed` is also fired on extract when RenderAssetUsages is `!MAIN_WORLD`.

so instead we can use the existing logic for processing the automatic removal (in `track_assets`) to determine whether to send the `Unused` event, as well as whether to attempt to unload the asset.

File: crates/bevy_asset/src/assets.rs [hunk 1]
```diff
@@ -549,9 +549,7 @@ impl<A: Asset> Assets<A> {
         while let Ok(drop_event) = assets.handle_provider.drop_receiver.try_recv() {
             let id = drop_event.id.typed();
 
-            assets.queued_events.push(AssetEvent::Unused { id });
-
-            let mut remove_asset = true;
+            let mut asset_unused = true;
 
             if drop_event.asset_server_managed {
                 let untyped_id = drop_event.id.untyped(TypeId::of::<A>());
```
Comment (bushrat011899) [inline crates/bevy_asset/src/assets.rs:555]:
```suggestion
                let untyped_id = id.untyped();
```

A typed `id` is already available from line 550, so might as well use it for a cleaner API.

File: crates/bevy_asset/src/assets.rs [hunk 2]
```diff
@@ -561,9 +559,10 @@ impl<A: Asset> Assets<A> {
                         continue;
                     }
                 }
-                remove_asset = infos.process_handle_drop(untyped_id);
+                asset_unused = infos.process_handle_drop(untyped_id);
```
Comment (bushrat011899) [inline crates/bevy_asset/src/assets.rs:562]: Minor nit: instead of a mutable `asset_unused`, have this `if` statement return line 562, and `true` on the `else` branch.

**Review by bushrat011899 — COMMENTED** [review]
Mostly just some minor style suggestions. Otherwise, makes sense!

**Comment by robtfm** [comment]
i think the resending of `not_ready` events might break this. i reworked it to use a local instead of resending, but that requires DropEvent to be `pub` or track_assets to be `pub(crate)` - is it a breaking change to make a type public?

**Review by alice-i-cecile — APPROVED** [review]

**Comment by robtfm** [comment]
> i think the resending of `not_ready` events might break this. i reworked it to use a local instead of resending, but that requires DropEvent to be `pub` or track_assets to be `pub(crate)` - is it a breaking change to make a type public?

nope, the code is fine, sorry. i think this is good as is

**Review by djeedai — APPROVED** [review]

**Comment by JMS55** [comment]
Tbh I'm having a hard time reviewing this, as the code is a bit confusing. I'm not quite sure I understand the implications of moving it around like this.

**Comment by robtfm** [comment]
> Tbh I'm having a hard time reviewing this, as the code is a bit confusing. I'm not quite sure I understand the implications of moving it around like this.

Have a look at the related issue. the important thing is that the process_handle_drop call checks whether new handles have been created since the drop event was fired, before removing the asset. We now perform that check before sending the unused event as well.

File: crates/bevy_asset/src/assets.rs [hunk 3]
```diff
@@ -549,23 +549,23 @@ impl<A: Asset> Assets<A> {
...
                         continue;
                     }
                 }
-                remove_asset = infos.process_handle_drop(untyped_id);
-            }
-            if remove_asset {
-                assets.remove_dropped(id);
+
+                if !infos.process_handle_drop(untyped_id) {
+                    // a new handle has been created, or the asset doesn't exist
```
Comment (JMS55) [inline crates/bevy_asset/src/assets.rs:562]: Can we expand this comment a bit with the context you put in your last comment to me? That this is a check to see if a new handle has been created in the same frame after the last one was dropped, meaning it's not _actually_ unused.

Also, what does "or the asset doesn't exist" mean here?

**Review by JMS55 — APPROVED** [review]
Thanks that clears it up for me. Approved, but I'd like some more verbose doc comments.

File: crates/bevy_asset/src/assets.rs (hunk 3 above)
Comment (robtfm) [reply crates/bevy_asset/src/assets.rs:563]: it's what the comment in the process_handle_drop function says. i don't know a scenario where it would happen.
