### PR TITLE
Fix panic when focused entity is despawned

### LINKED ISSUE #20057: `dispatch_focused_input` not checking whether the focused entity is alive or not.
## Bevy version

main

## What you did

Run the following code and try to press some key.
```rust
use bevy::{
    ecs::entity::Entities,
    input::keyboard::KeyboardInput,
    input_focus::{FocusedInput, InputDispatchPlugin, InputFocus, set_initial_focus},
    prelude::*,
};

fn main() {
    App::new()
        .add_plugins((DefaultPlugins, InputDispatchPlugin))
        .add_systems(PostStartup, setup.after(set_initial_focus))
        .add_observer(on_keyboard_input)
        .run();
}

fn setup(mut input_focus: ResMut<InputFocus>, mut commands: Commands) {
    let entity = commands.spawn_empty().id();
    input_focus.0 = Some(entity);
    commands.entity(entity).despawn();
}

fn on_keyboard_input(trigger: Trigger<FocusedInput<KeyboardInput>>, entities: &Entities) {
    assert!(entities.contains(trigger.target()));
}
```

## What went wrong

It's should not crash. Bevy should check the entity is alive or not. If not the event should be triggered on window entity.

## Additional information

None.

### PR DESCRIPTION
**Pull request by muddxyii**
# Objective

- Fix panic when input dispatch system tries to trigger events on a despawned focused entity
- Fixes #20057

## Solution

- Added entity validity check in `dispatch_focused_input` function using `entities.contains(focused_entity)`
- If the focused entity no longer exists, the focus is cleared and the event is dispatched to the window instead

## Testing

- Added test `dispatch_clears_focus_when_focused_entity_despawned` that reproduces the issue scenario

### CODE REVIEW

File: crates/bevy_input_focus/src/lib.rs [hunk 1]
```diff
@@ -254,21 +256,37 @@ pub fn set_initial_focus(
...
+                    commands.trigger_targets(
+                        FocusedInput {
+                            input: ev.clone(),
+                            window,
+                        },
+                        focused_entity,
+                    );
+                }
+            } else {
+                // If the focused entity no longer exists, clear focus and dispatch to window
```
Comment (alice-i-cecile) [inline crates/bevy_input_focus/src/lib.rs:282]: This behavior should be called out in the doc comments for the system.

**Review by viridia — APPROVED** [review]

File: crates/bevy_input_focus/src/lib.rs (hunk 1 above)
Comment (nikolaspadilla) [reply crates/bevy_input_focus/src/lib.rs:282]: Good point, updated the doc comments to clarify this behavior.

**Review by Aceeri — APPROVED** [review]
