### PR TITLE
Unify `FixedTime` and `Time` while fixing several problems

### LINKED ISSUE #7439: `FixedTime` API should match `Time` directly
## What problem does this solve or what need does it fill?

(This issue discusses a post-#7267 Bevy: follow that PR for context.)

Migrating systems between `CoreSet::Update` and `CoreSchedule::FixedUpdate` should be painless.
In particular, `Time` and `FixedTime` should be one-for-one drop in replacements for each other.

## What solution would you like?

Fully synchronize the methods available between `Time` and `FixedTime`.
Every method on one should be represented on the other wherever possible.

This can probably just be done manually to start.

## What alternative(s) have you considered?

We could use a trait here, but I'm not sure the indirection / complexity is worth it.

### LINKED ISSUE #8543: `FixedUpdate` schedules that take too long enter a cascading failure mode
## Bevy version

0.10

## What you did

Run a fixed time schedule that takes longer to complete than the allocated time.

## What went wrong

As the schedule took longer than the `FixedTime::period`, the accumulated time increases.

The next time we need to run the fixed update schedule, we must run it *more* times in order to catch up.

This puts us even further behind, worsening the problem...

### LINKED ISSUE #8800: `time.delta()` not compatible with `.run_if()` and timer conditions
## Bevy version

`0.10.1`

## What you did
```Rust
use bevy::{
    prelude::*,
    utils::Duration,
    time::{common_conditions::*},
};
use text_colorizer::*;

fn main() {
    App::new()
        .add_plugins(DefaultPlugins)
        .add_system(system_foo.run_if(on_timer(Duration::from_secs_f32(2.5))))
        .run();    
}

fn system_foo(time: Res<Time>) {
    println!("{}: Seconds since last update: {}","foo".blue() , time.delta().as_secs_f64());
    println!("FPS: {}", 1.0 / time.delta().as_secs_f64());
}
```

## What went wrong
Maybe this is expected behavior, but in the given example
`time.delta()` shows the wrong delta, but visually the console output appears correctly every ~2.5 seconds.
I would expect `time.delta()` to be close to the configured 2.5 seconds, too.

In my case the console outputs:
```
foo: Seconds since last update: 0.00117275
FPS: 852.6966531656363
foo: Seconds since last update: 0.001393651
FPS: 717.5397570840906
```

### PR DESCRIPTION
**Pull request by nakedible**
# Objective

Current `FixedTime` and `Time` have several problems. This pull aims to fix many of them at once.

- If there is a longer pause between app updates, time will jump forward a lot at once and fixed time will iterate on `FixedUpdate` for a large number of steps. If the pause is merely seconds, then this will just mean jerkiness and possible unexpected behaviour in gameplay. If the pause is hours/days as with OS suspend, the game will appear to freeze until it has caught up with real time.
- If calculating a fixed step takes longer than specified fixed step period, the game will enter a death spiral where rendering each frame takes longer and longer due to more and more fixed step updates being run per frame and the game appears to freeze.
- There is no way to see current fixed step elapsed time inside fixed steps. In order to track this, the game designer needs to add a custom system inside `FixedUpdate` that calculates elapsed or step count in a resource.
- Access to delta time inside fixed step is `FixedStep::period` rather than `Time::delta`. This, coupled with the issue that `Time::elapsed` isn't available at all for fixed steps, makes it that time requiring systems are either implemented to be run in `FixedUpdate` or `Update`, but rarely work in both.
- Fixes #8800 
- Fixes #8543 
- Fixes #7439
- Fixes #5692

## Solution

- Create a generic `Time<T>` clock that has no processing logic but which can be instantiated for multiple usages. This is also exposed for users to add custom clocks.
- Create three standard clocks, `Time<Real>`, `Time<Virtual>` and `Time<Fixed>`, all of which contain their individual logic.
- Create one "default" clock, which is just `Time` (or `Time<()>`), which will be overwritten from `Time<Virtual>` on each update, and `Time<Fixed>` inside `FixedUpdate` schedule. This way systems that do not care specifically which time they track can work both in `Update` and `FixedUpdate` without changes and the behaviour is intuitive.
- Add `max_delta` to virtual time update, which limits how much can be added to virtual time by a single update. This fixes both the behaviour after a long freeze, and also the death spiral by limiting how many fixed timestep iterations there can be per update. Possible future work could be adding `max_accumulator` to add a sort of "leaky bucket" time processing to possibly smooth out jumps in time while keeping frame rate stable.
- Many minor tweaks and clarifications to the time functions and their documentation.

## Changelog

- `Time::raw_delta()`, `Time::raw_elapsed()` and related methods are moved to `Time<Real>::delta()` and `Time<Real>::elapsed()` and now match `Time` API
- `FixedTime` is now `Time<Fixed>` and matches `Time` API. 
- `Time<Fixed>` default timestep is now 64 Hz, or 15625 microseconds.
- `Time` inside `FixedUpdate` now reflects fixed timestep time, making systems portable between `Update ` and `FixedUpdate`.
- `Time::pause()`, `Time::set_relative_speed()` and related methods must now be called as `Time<Virtual>::pause()` etc.
- There is a new `max_delta` setting in `Time<Virtual>` that limits how much the clock can jump by a single update. The default value is 0.25 seconds.
- Removed `on_fixed_timer()` condition as `on_timer()` does the right thing inside `FixedUpdate` now.

## Migration Guide

- Change all `Res<Time>` instances that access `raw_delta()`, `raw_elapsed()` and related methods to `Res<Time<Real>>` and `delta()`, `elapsed()`, etc.
- Change access to `period` from `Res<FixedTime>` to `Res<Time<Fixed>>` and use `delta()`.
- The default timestep has been changed from 60 Hz to 64 Hz. If you wish to restore the old behaviour, use `app.insert_resource(Time::<Fixed>::from_hz(60.0))`.
- Change `app.insert_resource(FixedTime::new(duration))` to `app.insert_resource(Time::<Fixed>::from_duration(duration))`
- Change `app.insert_resource(FixedTime::new_from_secs(secs))` to `app.insert_resource(Time::<Fixed>::from_seconds(secs))`
- Change `system.on_fixed_timer(duration)` to `system.on_timer(duration)`. Timers in systems placed in `FixedUpdate` schedule automatically use the fixed time clock.
- Change `ResMut<Time>` calls to `pause()`, `is_paused()`, `set_relative_speed()`  and related methods to `ResMut<Time<Virtual>>` calls. The API is the same, with the exception that `relative_speed()` will return the actual last ste relative speed, while `effective_relative_speed()` returns 0.0 if the time is paused and corresponds to the speed that was set when the update for the current frame started.

## Todo

- [x] Update pull name and description
- [x] Top level documentation on usage
- [x] Fix examples
- [x] Decide on default `max_delta` value
- [x] Decide naming of the three clocks: is `Real`, `Virtual`, `Fixed` good?
- [x] Decide if the three clock inner structures should be in prelude
- [x] Decide on best way to configure values at startup: is manually inserting a new clock instance okay, or should there be config struct separately?
- [x] Fix links in docs
- [x] Decide what should be public and what not
- [x] Decide how `wrap_period` should be handled when it is changed
- [x] ~~Add toggles to disable setting the clock as default?~~ No, separate pull if needed.
- [x] Add tests
- [x] Reformat, ensure adheres to conventions etc.
- [x] Build documentation and see that it looks correct

## Contributors

Huge thanks to @alice-i-cecile and @maniwani while building this pull. It was a shared effort!

### CODE REVIEW

File: crates/bevy_time/src/fixed.rs [hunk 1]
```diff
@@ -0,0 +1,311 @@
...
+/// frame. Any [`overstep()`](Time::overstep) present in the accumulator will be
+/// processed according to the new [`timestep()`](Time::timestep) value.
+#[derive(Debug, Copy, Clone, Reflect)]
+pub struct Fixed {
+    timestep: Duration,
+    overstep: Duration,
+}
+
+impl Time<Fixed> {
+    const DEFAULT_TIMESTEP: Duration = Duration::from_nanos(16_666_666);
```
Comment (alice-i-cecile) [inline crates/bevy_time/src/fixed.rs:61]:
```suggestion
    /// Corresponds to 60 Hz, to align with the standard 60 FPS.
    const DEFAULT_TIMESTEP: Duration = Duration::from_nanos(16_666_666);
```

File: crates/bevy_time/src/fixed.rs [hunk 2]
```diff
@@ -0,0 +1,311 @@
...
+    }
+
+    /// Return new fixed time clock with given timestep seconds as `f64`
+    pub fn from_seconds(seconds: f64) -> Self {
+        let mut ret = Self::default();
+        ret.set_timestep_seconds(seconds);
+        ret
+    }
+
+    /// Return new fixed time clock with given timestep frequency as `f64`
```
Comment (alice-i-cecile) [inline crates/bevy_time/src/fixed.rs:78]:
```suggestion
    /// Return new fixed time clock with given timestep frequency in Hertz (1/seconds)
```

File: crates/bevy_time/src/time.rs [hunk 3]
```diff
@@ -1,218 +1,300 @@
...
+/// and `f64` for consistency. The wrap period is by default 1 hour, and can be
+/// set by [`set_wrap_period()`](Time::set_wrap_period).
+///
+/// # Accessing clocks
+///
+/// By default, any systems requiring current [`delta()`](Time::delta) or
+/// [`elapsed()`](Time::elapsed) should use `Res<Time>` to access the default
+/// time configured for the program. By default, this refers to
+/// [`Time<Virtual>`](crate::virt::Virtual) except during
+/// [`FixedUpdate`](bevy_app::FixedUpdate) when it refers to
```
Comment (alice-i-cecile) [inline crates/bevy_time/src/time.rs:47]:
```suggestion
/// the [`FixedUpdate`](bevy_app::FixedUpdate) schedule when it refers to
```

File: crates/bevy_time/src/time.rs [hunk 4]
```diff
@@ -1,218 +1,300 @@
...
+/// [`Time<Fixed>`](crate::fixed::Fixed). This makes your system compatible to
```
Comment (alice-i-cecile) [inline crates/bevy_time/src/time.rs:48]:
```suggestion
/// [`Time<Fixed>`](crate::fixed::Fixed). This ensures your system can
```

File: crates/bevy_time/src/virt.rs [hunk 5]
```diff
@@ -0,0 +1,423 @@
...
+#[derive(Debug, Copy, Clone, Reflect)]
+pub struct Virtual {
+    max_delta: Duration,
+    paused: bool,
+    relative_speed: f64,
+    effective_speed: f64,
+}
+
+impl Time<Virtual> {
+    const DEFAULT_MAX_DELTA: Duration = Duration::from_millis(333); // XXX: better value
```
Comment (alice-i-cecile) [inline crates/bevy_time/src/virt.rs:80]:
```suggestion
    const DEFAULT_MAX_DELTA: Duration = Duration::from_millis(250);
```

File: crates/bevy_time/src/virt.rs [hunk 6]
```diff
@@ -0,0 +1,423 @@
...
+    /// update.
+    ///
+    /// This ensures that even if there are no updates scheduled for an extended
+    /// amount of time, there won't be a huge update at once for the clock. This
+    /// also limits the number of fixed time ticks that will be evaluated at
+    /// maximum per a single update.
+    ///
+    /// The default value is 0.333 seconds **FIXME**.
+    #[inline]
+    pub fn max_delta(&self) -> Duration {
```
Comment (alice-i-cecile) [inline crates/bevy_time/src/virt.rs:104]:
```suggestion
    pub const fn max_delta(&self) -> Duration {
```

Comment (alice-i-cecile) [reply crates/bevy_time/src/virt.rs:104]: And so on throughtout this PR. It's nice to make methods const where possible, especially when we never expect to need to break that guarantee.

File: crates/bevy_time/src/virt.rs [hunk 7]
```diff
@@ -0,0 +1,423 @@
...
+        self.context().paused
+    }
+
+    /// Returns `true` if the clock was paused at the start of this update.
+    #[inline]
+    pub fn was_paused(&self) -> bool {
+        self.context().effective_speed == 0.0
+    }
+
+    fn advance_with_raw_delta(&mut self, raw_delta: Duration) {
```
Comment (alice-i-cecile) [inline crates/bevy_time/src/virt.rs:218]:
```suggestion
    /// Updates the elapsed duration of `self` by `raw_delta`, up to the `max_delta`.
    fn advance_with_raw_delta(&mut self, raw_delta: Duration) {
```

Doc strings on private items are nice for contributors IME.

File: crates/bevy_time/src/virt.rs [hunk 8]
```diff
@@ -0,0 +1,423 @@
...
+        Self {
+            max_delta: Time::<Virtual>::DEFAULT_MAX_DELTA,
+            paused: false,
+            relative_speed: 1.0,
+            effective_speed: 1.0,
+        }
+    }
+}
+
+pub fn virtual_time_system(
```
Comment (alice-i-cecile) [inline crates/bevy_time/src/virt.rs:257]:
```suggestion
/// Advances [`Time<Virtual>`] and [`Time>`] based on the elapsed [`Time<Real>`].
///
/// The virtual time will be advanced up to the provided `max_delta`.
pub fn virtual_time_system(
```

**Review by alice-i-cecile — COMMENTED** [review]
A few cleanup comments to address, but I really like this design! Top notch docs too!

The generic with a default `()` is a clever approach, and I like the contextual "automatically grab the right time" without the limitations on advanced users (and extreme cleverness) that the "swap the Time resource" approach implied.

**Comment by maniwani** [comment]
Still reviewing. Most things look good. However:

> `Time::set_wrap_period` no longer accepts wrap periods with a subsecond component. It is very unlikely anybody uses those.

I've commented on #8912, but this change does not belong here. I disagree that the "complexity" of the modulo calculation is an issue. Imposing a user-facing limit to "fix" an internal implementation detail is an issue though.

File: crates/bevy_time/src/virt.rs (hunk 6 above)
Comment (nakedible) [reply crates/bevy_time/src/virt.rs:107]: Decided against this, discussion was in Discord

File: crates/bevy_time/src/time.rs [hunk 9]
```diff
@@ -1,218 +1,288 @@
...
 #[reflect(Resource, Default)]
-pub struct Time {
-    startup: Instant,
-    first_update: Option<Instant>,
-    last_update: Option<Instant>,
-    // pausing
-    paused: bool,
-    // scaling
-    relative_speed: f64, // using `f64` instead of `f32` to minimize drift from rounding errors
+pub struct Time<T: Default = ()> {
```
Comment (B-head) [inline crates/bevy_time/src/time.rs:188]: Generics are used only for code decoration. In such cases, codes are simpler without generics.

If you want to make some common code, you can provide default implementations in the trait.

File: crates/bevy_time/src/time.rs [hunk 10]
```diff
@@ -1,218 +1,288 @@
...
-    raw_delta_seconds: f32,
-    raw_delta_seconds_f64: f64,
-    raw_elapsed: Duration,
-    raw_elapsed_seconds: f32,
-    raw_elapsed_seconds_f64: f64,
-    // wrapping
-    wrap_period: Duration,
     elapsed_wrapped: Duration,
     elapsed_seconds_wrapped: f32,
     elapsed_seconds_wrapped_f64: f64,
```
Comment (B-head) [inline crates/bevy_time/src/time.rs:199]: Since this cache is recalculated whenever time advances, no performance improvement can be expected. It is okay to retain only the pre-calculated value.

File: crates/bevy_time/src/time.rs [hunk 11]
```diff
@@ -1,218 +1,288 @@
...
+        self.wrap_period = wrap_period;
     }
 
-    /// Returns how much time has advanced since the last [`update`](#method.update), as a [`Duration`].
+    /// Returns how much time has advanced since the last [`update`](#method.update), as a
+    /// [`Duration`].
     #[inline]
     pub fn delta(&self) -> Duration {
         self.delta
     }
```
Comment (B-head) [inline crates/bevy_time/src/time.rs:275]: This does not seem usable well when updates are done asynchronously. I want a function like [`Instant::duration_since`](https://doc.rust-lang.org/std/time/struct.Instant.html#method.duration_since).

**Review by B-head — CHANGES_REQUESTED** [review]
I want to merge quickly for integration with #9034 so will do the review.

I think codes still needs many improvements, but I look forward to seeing it merged. 👍

**Comment by B-head** [comment]
I prefer not to have variants like `Time::delta_seconds` that only do type conversions, as they might make unnecessary type conversions. 🛡️

```rust
let x = Duration::from_secs_f32(time.delta_seconds()); // I know they wouldn't do this
``` 

What do you all think about this?

**Comment by maniwani** [comment]
> I prefer not to have variants like `Time::delta_seconds` that only do type conversions, as they might make unnecessary type conversions.

Caching is the point. Convert a `Duration` into  an `f32`/`f64` is not free. There's a few arithmetic instructions involved. The cost is negligible, but 
last I checked (w/ godbolt) the compiler didn't figure out it could elide multiple `time.delta_seconds()` calls if you don't cache the value.

IMO there's no reason to do that work every single time `time.delta_seconds()` is called, or making you assign it to a local variable when we can just cache it internally.

File: crates/bevy_time/src/fixed.rs [hunk 12]
```diff
@@ -0,0 +1,320 @@
...
+/// generic [`Time`] resource during [`FixedUpdate`](bevy_app::FixedUpdate)
+/// schedule processing.
+///
+/// The fixed timestep game clock runs at a regular interval and is extremely
+/// useful for steady, frame-rate independent gameplay logic and physics.
+///
+/// The default [`timestep()`](Time::timestep) is 64 hertz, or 15625
+/// microseconds. The reason this value is chosen is that it is relatively close
+/// to a standard monitor refresh rate of 60 hertz, but is accurately
+/// representable as a 32-bit and 64-bit floating point number.
```
[the remark this answers is not in the document]
Comment (maniwani) [reply crates/bevy_time/src/fixed.rs:24]: It's not related to framerate. 64Hz was chosen because it's a power-of-two, which means `time.delta_seconds()` will be an exact value instead of an approximation. That makes doing math in `FixedUpdate` more accurate. 

```rust
position += velocity * time.delta_seconds();
```

If you integrate time like this and `time.delta_seconds()` is 15.625ms, rounding errors are minimized.

There's no benefit to matching the timestep to a common monitor refresh rate. That doesn't help things look smoother.

**Comment by nakedible** [comment]
I personally think it's super annoying to have the API blow up just because we want multiple different types of the same value, and just for caching reasons. I considered making PrecomputedDuration as well, which would share 100% of the Duration API, but just would ensure that Duration.as_secs_f32() would be precomputed and saved (or lazily computed if that ends up being a performance win).

However, I didn't want to touch that discussion with this pull. I'm simply preserving what was the behaviour in the previous version, and I'd suggest a new pull is made to clean up all the usages of `duration_seconds` etc. if we decide to get rid of them.

File: crates/bevy_time/src/fixed.rs (hunk 12 above)
[the remark this answers is not in the document]
Comment (nakedible) [reply crates/bevy_time/src/fixed.rs:24]: The problem with 60 Hz is that it may become a pathological case of running an alternating sequence of 0 and 2 fixed updates.

There would be a point in making the fixed timestep be something like 4x the framerate, so 256 Hz (or 240 Hz if not caring about division accuracy). That way if some frames have 3 fixed updates and some have 5, the results will not be as jarring as with zero and 2. But that might be a worse default as it's not usually done by engines that way.

But ultimately – it's just some number as some number has to be picked as the default. Unity default is 50 Hz for the fixed update.

File: crates/bevy_time/src/time.rs (hunk 10 above)
Comment (nakedible) [reply crates/bevy_time/src/time.rs:199]: Comments in pull discussion on this as well. I'd be happy to remove precalculated cache, and even happer would be to get rid of the overly duplicated API, but I didn't want to make that decision in this pull, since it's also controversial.

File: crates/bevy_time/src/time.rs (hunk 11 above)
Comment (nakedible) [reply crates/bevy_time/src/time.rs:275]: I talked in Discord how time could be tracked per system – so `time.delta()` in that system would calculate the delta since the last time that system was run. However, that was deemed too complex. 

Explicitly tracking time deltas requires the user to store the previous `time.elapsed()` value somewhere. `Instant::duration_since` equivalent is simply `time.elapsed() - since`. `Time::elapsed` is the `Instant` equivalent inside Bevy, one that isn't platform specific mess like Instant, and `duration_since` is just substraction. Also `checked_sub` and `saturating_sub` are available for Durations if there's a need for specific underflow behaviour.

**Comment by maniwani** [comment]
> I personally think it's super annoying to have the API blow up just because we want multiple different types of the same value, and just for caching reasons.

> I considered making a `PrecomputedDuration` as well, which would share 100% of the `Duration` API but would keep `Duration.as_secs_f32()` [cached] (or lazily computed if that ends up being a performance win).

I do see where you're coming from.

Yes, we could use our own variant of `Duration` with internal caching to remove the cost of `time.delta().as_secs_f32()`, but yeah I think you should try that in a separate PR. Also, it doesn't have to be a follow-up, it could be merged before this one is.

(I'd also suggest the name be `CachedDuration` or `CachedFloatDuration` though.)

Even then, I'm not sure if we should remove the `time.delta_seconds()` method in favor of `time.delta().as_secs_f32()`. The `f32` value is the most commonly used, and such a change would make getting it less ergonomic. I think you should do a separate PR and ask cart to review that one.

File: crates/bevy_time/src/time.rs (hunk 11 above)
Comment (maniwani) [reply crates/bevy_time/src/time.rs:275]: > I talked in Discord how time could be tracked per system – so `time.delta()` in that system would calculate the delta since the last time that system was run. However, that was deemed too complex.

For a few reasons.

1. We can't actually auto-update `Time` with this per-system value. `Time` can't even be used inside `bevy_ecs` because `bevy_time` depends on `bevy_ecs`.
2. Using a unique `Δt` per system is not even a valid way to intergrate time. The same sequence of logic would get different results depending on how many systems it was split into. It's super suspect that different components on the same entity could be integrated by different amounts of time.
3. It's too different from how everyone knows "delta time". It'd break unity with fixed update, which is counterproductive.

File: crates/bevy_time/src/fixed.rs (hunk 12 above)
[the remark this answers is not in the document]
Comment (maniwani) [reply crates/bevy_time/src/fixed.rs:24]: 60Hz is a nice default value because no one will question it. It's the defacto minimum frame rate, and every player device is expected to handle running logic 60 times a second. 2x and 4x? Not so much.

But 60Hz is just a convention. There's no benefit to having the tick rate match the average FPS. The number of ticks per frame will actually oscillate the most when that happens.

The thing for users to recognize is you can't get smooth rendering reliably without interpolation (or extrapolation), and having that will make any tick rate look smooth. So frame and tick rates are independent, games have just settled on "stuff should run at least 60 times a second" to reduce input lag.

64Hz is just the closest power-of-two to 60Hz, but it's also pretty common (e.g. Counter Strike). And again, the reason to use a power-of-two as the default is they don't cause rounding errors.

[the remark this answers is not in the document]
Comment (B-head) [reply crates/bevy_time/src/fixed.rs:24]: > ```rust
> position += velocity * time.delta_seconds();
> ```
> 
> If you integrate time like this and `time.delta_seconds()` is 15.625ms (64Hz), rounding errors are minimized.

That is correct, but even if the value is not `power-of-two`, the rounding error will be within half of [ULP](https://en.wikipedia.org/wiki/Unit_in_the_last_place). That is not 0 but quite small.

> There's no benefit to matching the timestep to a common monitor refresh rate. That doesn't help things look smoother.

That is true without VSync or when #9034 is merged, but not with VSync. With VSync, two ticks are run a frame, which causes periodic game speed jumps. Also, the maximum CPU usage is limited to half to prevent lag spikes.

The disadvantages outweigh the advantages of using 64hz. Unless #9034 has been merged.

Well, but if #9034 is merged I will set the default value to 125hz. This value is consistent with the polling rate for typical input devices, thus optimizing input responsiveness.

> The problem with 60 Hz is that it may become a pathological case of running an alternating sequence of 0 and 2 fixed updates.

I think this can be avoided by buffering the updates. If 2 updates are needed, 1 update and 1 buffer. If 3 updates are needed, update 2 and buffer 1. If 0 updates are needed, then update if buffered.

File: crates/bevy_time/src/time.rs (hunk 10 above)
Comment (B-head) [reply crates/bevy_time/src/time.rs:199]: The difference is so very small that it cannot be measured in the benchmark, so no one will notice if you change this silently. 🏃 

The current code computes `6 * 3` times per frame, which may be slower than not caching.

File: crates/bevy_time/src/time.rs (hunk 11 above)
Comment (B-head) [reply crates/bevy_time/src/time.rs:275]: Maybe that's right. This was probably not good idea.

File: crates/bevy_time/src/time.rs (hunk 9 above)
Comment (B-head) [reply crates/bevy_time/src/time.rs:188]: This is pending because the solution is different depending on whether to cache or not.

File: crates/bevy_time/src/fixed.rs (hunk 12 above)
[the remark this answers is not in the document]
Comment (maniwani) [reply crates/bevy_time/src/fixed.rs:24]: > The disadvantages outweigh the advantages of using 64hz. Unless #9034 has been merged.

Just because some users can get lucky by enabling VSync on a 60Hz monitor, that's not a good reason to set the tick rate at 60Hz. That isn't an endorsable solution.

The closest thing to an official position has always been "interpolation or sub-stepping are the only robust ways to render fixed stuff smoothly".

> I will set the default value to 125hz. This value is consistent with the polling rate for typical input devices, thus optimizing input responsiveness.

You can do as you like, but we are going
in the direction of decoupling the `winit` event loop from the app updates.

Input events cannot be observed in realtime because the `winit` loop is blocked when the app updates, but that'll change with #9122. Once we merge #9122, it'll be possible for `FixedUpdate` to receive input events in a framerate-independent way.

The frame rate, tick rate, and input "polling" rate will all be decoupled.

File: crates/bevy_time/src/time.rs (hunk 11 above)
Comment (nakedible) [reply crates/bevy_time/src/time.rs:275]: Per system delta time that will track delta time from the last time that specific system was run:
```rust
fn my_system(time: Res<Time>, mut last: Local<Duration>) {
    let delta = time.elapsed() - last;
    last = time.elapsed();
    ...
}
```
Could probably make a SystemParam and implement some convenience method on it to make it even nicer to use.

But I do believe we want to keep `time.delta()` as is, as that matches what people expect from it.

File: crates/bevy_time/src/time.rs (hunk 10 above)
Comment (nakedible) [reply crates/bevy_time/src/time.rs:199]: There's four choices:
1. Leave as is, figure out something in another pull if it feels meaningful.
2. Remove precomputation, but keep the same API, so `delta_seconds()` will return `f32`, just calculated on every request.
3. Create `CachedDuration` which keeps precomputation, and change API to return only `CachedDuration`, forcing every user to change `time.delta_seconds()` to `time.delta().as_secs_f32()` but keeping same performance "advantage".
4. Remove precomputation and change API to return only `Duration`. Every user needs to switch from `time.delta_seconds()` to `time.delta().as_secs_f32()`, but it will be the Rust standard `Duration` class so it should be quite obvious. (Not sure what to do about wrapped time here...)

In a way, I do understand the precomputation – even if there's `6 * 3` computation per frame to get the values, most of which will not be used, it's still a meaningless amount of time. Where as if there is one `time.delta_seconds()` call in a system which does collision detection, for example, then that's easily millions of conversions to float per frame... if the compiler for some reason doesn't optimize it outside the loops.

But I think what you are proposing is number two? I'm fine with switching this pull to do that, if I can count on not having to revert my changes in a few days :-)

File: crates/bevy_time/src/fixed.rs (hunk 12 above)
[the remark this answers is not in the document]
Comment (nakedible) [reply crates/bevy_time/src/fixed.rs:24]: Even if fixed timestep is 60 Hz, and display refresh is 60 Hz, it will not mean that there will always be exactly one fixed update per frame. Display clock frequency never matches system clock frequency exactly – no two clocks ever do – so they will diverge if the game runs against the system clock.

The only way to avoid this is to tie the game `elapsed` and `delta` etc. to the display refresh clock. But we don't want to do that (even if VSync is enabled), because display clocks vary (59.997 Hz and 59.940 Hz being explicit examples of intentionally not being 60 Hz) and an important point of fixed timestep is to ensure the game behaves consistently regardless of frame rate - and regardless of the computer the game is run on.

As for input events... IMHO, input events should be tagged with `Instant`, which then needs to be translated to virtual game time (by scaling it between last update and this update, can discuss this more why I believe this is right), and then made visible to the game if the virtual game time is past the instant of the input (in addition exposing the virtual timestap of the input event directly to the game as well, if the game wants to do sub-frame accuracy for inputs). Frame rate should not enter into it in any way. If there's a need to poll inputs because they don't arrive as an event stream natively, then this polling loop should have nothing to do with the game loop, as it's only purpose is to fetch inputs, timestamp them with instant and put them in a queue.

And as for doing ticks where nothing is rendered... How I see it is that the only meaningful output of a game is when it displays something (not true for networked games, dedicated servers, etc.), and the point of running systems is to compute what needs to be shown. For "perfect" games, just running Update schedule will run any amount of game logic with exact results – but most games are not "perfect", but instead use a fixed timestep to ensure their logic is run in discrete chunks regardless of the rate of updates. Running any of this update logic without rendering serves no direct purpose, as only the outputs matter – the only benefit being that if calculating the next state takes long, then the more that can be calculated before rendering the better because it means the actual render pass will be shorter which means there will be less latency from "we can start rendering a frame" to "frame is rendered". Concretely this would mean that as soon as it is clear that no more inputs will be arriving that would affect the next fixed update step, the next fixed update step should be calculated. However, there should be exactly zero behaviour impact from this – the only impact being that we might use the time between frames more efficiently by splitting up the computation, reducing latency for the actual frame rendering. This would be a reduction of latency of probably less than 10 milliseconds in real world, so not sure if it's worth the complexity.

All that said though, I'd be happy to put 125 Hz as the fixed update timestep. The only reason why I didn't suggest a "much higher than refresh" value to start with is that Bevy used to have 60 Hz as the fixed timestep, and Unity has 50 Hz as the fixed timestep, so doubling the default rate (or more) is probably disruptive for a bunch of existing games and a cause of surprise for new users. But if someone else makes that judgement call, I'm not complaining as I think that's a better default ultimately.

[the remark this answers is not in the document]
Comment (nakedible) [reply crates/bevy_time/src/fixed.rs:24]: And separately... buffering is probably just weird. If the refresh Hz is above fixed timestep, it will be just normal behaviour of no buffering – basically a sequence of `0, 1, 1, 1, 1 ... 1, 0, 1, 1, 1, 1 ...` over and over again. If the refresh Hz is below fixed timestep (like 60 Hz vs 64 Hz), then it will go to a sequence of `1, 1, 1, 1 ... 1, 2, 1, 1, 1, 1 ...` with the 2 updates being run if *three* updates would really be queued. It does smooth out bumps in the framerate... but this makes the time run on average with 1.5 frame lag compared to virtual game time, which is silly but also really problematic as the whole point of this exercise is to ensure that time inside fixed timestep is never desynced from time outside fixed timestep. If we ever "buffer" frames, be it via "max ticks per update" or some other method, then `Time<Fixed>` cannot be trusted to be between the previous `Time<Virtual>` and the next `Time<Virtual>`. And this is an approach that I do not agree with, so it means someone else has to finish the pull.

[the remark this answers is not in the document]
Comment (maniwani) [reply crates/bevy_time/src/fixed.rs:24]: > input events should be tagged with an `Instant`
> that is then be translated into virtual game time
> and then the event should be made visible to the game if the virtual time is past that time

You don't need to convince the maintainers. This has been the goal for a long time, but it's blocked on merging a solution like #9122. If we tried to timestamp inputs right now, they'd all just be aliased to the `Instant` a frame starts.

> 125 Hz

I'm happy to volunteer to make the judgement call. 

100+Hz is too much. Games normally target 60[^1] ticks/sec. That's the minimum players expect today, and it's still what most games aim for in 2023. If the default is set significantly higher than 60Hz, too many users will have to lower it for their games to have acceptable performance. 

A default is supposed to be serve most users so they don't need to change it, not show off how good something can be in especially well-optimized cases. So 60Hz is the minimum value[^2], and raising it higher makes it worse as a default.

64Hz hits a sweet spot of being barely above 60Hz while giving some practical accuracy benefits. So, with all that said, 60Hz and 64Hz are the only acceptable choices. And if it'll end the debate, just go with 60 lol. 

[^1]: 60Hz does come from the lowest common denominator in screen refresh rates, but setting the minimum expectation is as far as that relationship goes.

**Comment by nakedible** [comment]
It's been quiet for a while... how should I proceed?

File: crates/bevy_time/src/virt.rs [hunk 13]
```diff
@@ -0,0 +1,430 @@
...
+    /// single update, as [`Duration`](std::time::Duration).
+    ///
+    /// This is the maximum value [`Self::delta()`] will return and also to
+    /// maximum time [`Self::elapsed()`] will be increased by in a single
+    /// update.
+    ///
+    /// This ensures that even if there are no updates scheduled for an extended
+    /// amount of time, there won't be a huge update at once for the clock. This
+    /// also limits the number of fixed time ticks that will be evaluated at
+    /// maximum per a single update.
```
Comment (maniwani) [inline crates/bevy_time/src/virt.rs:103]:
```suggestion
    /// This ensures that even if there are no updates scheduled for an extended
    /// amount of time, there won't be a huge update at once for the clock. This
    /// also indirectly limits the maximum number of fixed update steps that can
    /// run in a single update.
```

File: crates/bevy_time/src/virt.rs [hunk 14]
```diff
@@ -0,0 +1,430 @@
...
+    /// update.
+    ///
+    /// This is used to ensure that even if the game freezes for a few seconds,
+    /// or is suspended for hours or even days, the virtual clock doesn't
+    /// suddenly jump forward for that full amount, which would likely cause
+    /// gameplay bugs or having to suddenly simulate all the intervening time.
+    ///
+    /// re are no updates scheduled for an extended amount of time, there won't
+    /// be a huge update at once for the clock. This also limits the number of
+    /// fixed time ticks that will be evaluated at maximum per a single update.
```
Comment (maniwani) [inline crates/bevy_time/src/virt.rs:125]:
```suggestion
    /// If no updates happen for an exceptionally large amount of time, this limit
    /// prevents having a sudden, huge advance all at once. This also indirectly limits
    /// the maximum number of fixed update steps that can run in a single update.
```

File: crates/bevy_time/src/virt.rs [hunk 15]
```diff
@@ -0,0 +1,430 @@
...
+    ///
+    /// The default value is 0.25 seconds. If you want to disable this feature,
```
Comment (maniwani) [inline crates/bevy_time/src/virt.rs:127]:
```suggestion
    /// The default value is 250 milliseconds. If you want to disable this feature,
```

**Review by maniwani — COMMENTED** [review]
The logic seems correct to me. I just have some suggestions and fixes for the documentation.

**Comment by alice-i-cecile** [comment]
I'm back from vacation, so I'll try to get a proper review in for you. Once we have an approval from me, we'll either need an approval from @cart, or one from a second maintainer.

I think this is far enough outside of ECS that Joy can't merge this as an SME-ECS 🤔

**Comment by nakedible** [comment]
> The logic seems correct to me. I just have some suggestions and fixes for the documentation.

Thanks for the doc comments, there were quite on point.

**Review by maniwani — APPROVED** [review]
Yep, this is outside of ECS, but LGTM once you get CI passing.

You and I have spent a lot of time going over the different ways of implementing this in depth, and I think this is the cleanest one (and most idiomatic as far as Rust is concerned).

**Comment by nakedible** [comment]
CI was passing earlier already, so I'll fix it as soon as I get a review from @alice-i-cecile

**Comment by nakedible** [comment]
Only remaining build error is not relevant for this pull – `Cargo.toml` is modified only to add an example, not to touch deps.

File: crates/bevy_time/src/fixed.rs [hunk 16]
```diff
@@ -0,0 +1,321 @@
...
+    }
+
+    /// Sets the amount of virtual time that must pass before the fixed timestep
+    /// schedule is run again, as frequency.
+    ///
+    /// The timestep value is set to `1 / hz`, converted to a
+    /// [`Duration`](std::time::Duration) which has fixed nanosecond resolution.
+    ///
+    /// Takes effect immediately on the next run of the schedule, respecting
+    /// what is currently in [`Self::overstep`].
```
Comment (alice-i-cecile) [inline crates/bevy_time/src/fixed.rs:141]: Missing `#Panics` seciton here and elsewhere: those asserts would not be fun to hit suddenly.

File: crates/bevy_time/src/fixed.rs [hunk 17]
```diff
@@ -0,0 +1,321 @@
...
+    timestep: Duration,
+    overstep: Duration,
+}
+
+impl Time<Fixed> {
+    /// Corresponds to 64 Hz.
+    const DEFAULT_TIMESTEP: Duration = Duration::from_micros(15625);
+
+    /// Return new fixed time clock with given timestep as
+    /// [`Duration`](std::time::Duration)
```
Comment (alice-i-cecile) [inline crates/bevy_time/src/fixed.rs:72]: `Panics` docs will need to be propagated to these methods too.

**Review by alice-i-cecile — CHANGES_REQUESTED** [review]
Missing panics docs are important enough to block on, but code quality and tests look good and I'm on board with this design.

We've spent a lot of time debating this, and I think we should ship this for 0.12.

**Comment by cart** [comment]
Cool I'll add this to the review pile. The Time API is something I care a lot about as it is highly trafficked. I'd like to do a full review.

**Review by alice-i-cecile — APPROVED** [review]

**Comment by nakedible** [comment]
> The Time API is something I care a lot about as it is highly trafficked.

I'll be happy to rework this exactly as you want the API to be, as almost all the choices there are judgement calls that can solved in many ways and it's important to keep the same feel across all APIs. I'm personally doubting a bit if the use of generics is too gimmicky, but it feels like it gives an intuitive understanding to the user that time comes in many flavors and they need to pick the right flavor if they need something specific, or just go with generic if they don't.

**Comment by Telov** [comment]
I think it isn't a good idea to introduce API For Time<Fixed> because this behaviour should remain dictated by the schedule the system is added to. Not sure if it's how it's supposed to be used in real world according to this PR, but in the provided example you insert time yourself which I think shouldn't be a concern of an end user. Not clear why in the example file you add system with Res<Time<Real>> to PreUpdate schedule.

**Comment by nakedible** [comment]
> I think it isn't a good idea to introduce API For `Time<Fixed>` because used `Time<>` should remain dictated by the schedule the system is added to. Not sure if it's how it's supposed to be used in real world according to this PR, but in the provided example you insert time yourself which I think shouldn't be a concern of an end user. Not clear why in the example file you add system with `Res<Time<Real>>` to `PreUpdate `schedule.

`Res<Time<Fixed>>` is required if one wants to access the last fixed update timestep inside `Update`. This isn't an outlandish use case, although the common case is for the user to just use `Res<Time>` which is dictated by the schedule system as explained in the documentation. In the way this pull is written, explicitly saying `Time<Fixed>` is also needed if one wants to get or set the parameters of the fixed timestep, like step duration.

Adding `Res<Time<Real>>` to `PreUpdate` and not `Update` in the example is to get it printing before the fixed time updates, and also because input handling (which often requires `Time<Real>`) is suited for `PreUpdate`.

Reading the documentation on `Time` might clarify these things even more: https://github.com/bevyengine/bevy/blob/7858e709b1c9ba81cb5a6cc579770932be61a5e2/crates/bevy_time/src/time.rs#L5-L185

**Comment by alice-i-cecile** [comment]
Can you fix up the merge conflicts to prepare for a final review pass in time for 0.12?

**Comment by nakedible** [comment]
Sure! I'd just rather not do that 10 times in a row if it's not going anywhere so I haven't done it so far.

**Comment by nakedible** [comment]
Now all cleaned up for @cart, on the off-chance that he'd want to merge this without changes. The failing "check bans" is a spurious failure irrelevant of this pull as this doesn't change dependencies in any way. It adds one example which triggers the check for `Cargo.toml` modifications.

**Review by djeedai — COMMENTED** [review]
A bit hesitant to Approve here, not because of the content which I think finally converges on some reasonable time API, but because it's one more PR that refactors that entire time API, and I'm worried about these being a bit too frequent (the current merged code was already a large refactor PR that changed everything). Hopefully @cart can review and provide guidance here so we finally settle on a design and stop changing it. But otherwise no objection to merge.

File: crates/bevy_time/src/fixed.rs [hunk 18]
```diff
@@ -0,0 +1,345 @@
...
+/// [`set_relative_speed()`](Time::set_relative_speed) and
+/// [`set_max_delta()`](Time::set_max_delta) from virtual time. If the virtual
+/// clock is paused, the [`FixedUpdate`](bevy_app::FixedUpdate) schedule will
+/// not run. It is guaranteed that the [`elapsed()`](Time::elapsed) time in
+/// `Time<Fixed>` is always between the previous `elapsed()` and the next
+/// `elapsed()` value in `Time<Virtual>`, so the values are compatible.
+///
+/// Changing the timestep size while the game is running should not normally be
+/// done, as having a regular interval is the point of this schedule, but it may
+/// be necessary for effects like "bullet-time" if the normal granularity of the
```
[the remark this answers is not in the document]
Comment (rlidwka) [reply crates/bevy_time/src/fixed.rs:52]: Does `Time<Fixed>` have meaningful `set_relative_speed`?

**Comment by alice-i-cecile** [comment]
> A bit hesitant to Approve here, not because of the content which I think finally converges on some reasonable time API, but because it's one more PR that refactors that entire time API, and I'm worried about these being a bit too frequent (the current merged code was already a large refactor PR that changed everything). Hopefully @cart can review and provide guidance here so we finally settle on a design and stop changing it. But otherwise no objection to merge.

This was basically the shape of the final API we had in mind during the Schedulev3 work: it was just too big to pull of as part of that process.

File: crates/bevy_time/src/fixed.rs [hunk 19]
```diff
@@ -0,0 +1,345 @@
...
+        let mut ret = Self::default();
+        ret.set_timestep(timestep);
+        ret
+    }
+
+    /// Return new fixed time clock with given timestep seconds as `f64`
+    ///
+    /// # Panics
+    ///
+    /// Panics if `seconds` is negative or not finite.
```
[the remark this answers is not in the document]
Comment (maniwani) [reply crates/bevy_time/src/fixed.rs:87]: Good catch. The asserts and the documentation needs to be corrected. It would have still panicked on zero though, see [`set_timestep`][1].

[1]: https://github.com/bevyengine/bevy/blob/95234cfb401fd5875a4cc67c5e204b76278c44e8/crates/bevy_time/src/fixed.rs#L123

File: crates/bevy_time/src/fixed.rs [hunk 20]
```diff
@@ -0,0 +1,345 @@
...
+    #[inline]
+    pub fn overstep(&self) -> Duration {
+        self.context().overstep
+    }
+
+    /// Returns the amount of overstep time accumulated toward new steps, as an
+    /// [`f32`] fraction of the timestep.
+    #[inline]
+    pub fn overstep_percentage(&self) -> f32 {
+        self.context().overstep.as_secs_f32() / self.context().timestep.as_secs_f32()
```
[the remark this answers is not in the document]
Comment (maniwani) [reply crates/bevy_time/src/fixed.rs:184]: No, it's dividing two `Duration` values to get an `f32`. We would need [`Duration::div_duration_f32`][1], but that API only exists on nightly.

[1]: https://doc.rust-lang.org/stable/std/time/struct.Duration.html#method.div_duration_f32

File: crates/bevy_time/src/fixed.rs [hunk 21]
```diff
@@ -0,0 +1,345 @@
...
+    }
+
+    /// Returns the amount of overstep time accumulated toward new steps, as an
+    /// [`f64`] fraction of the timestep.
+    #[inline]
+    pub fn overstep_percentage_f64(&self) -> f64 {
+        self.context().overstep.as_secs_f64() / self.context().timestep.as_secs_f64()
```
[the remark this answers is not in the document]
Comment (maniwani) [reply crates/bevy_time/src/fixed.rs:191]: Also no, it's dividing two `Duration` values to get an `f64`. We would need [`Duration::div_duration_f64`][1], but that API only exists on nightly.

[1]: https://doc.rust-lang.org/stable/std/time/struct.Duration.html#method.div_duration_f64

File: crates/bevy_time/src/fixed.rs (hunk 18 above)
[the remark this answers is not in the document]
Comment (maniwani) [reply crates/bevy_time/src/fixed.rs:52]: > not enough for physics to look right

IIRC it's about responsiveness. `set_relative_speed(0.1)` slows things down 10x. So 60 ticks/sec would drop to 6 ticks/sec. If you want a player to move within bullet time, 6 times a second isn't much.

If you change the timestep itself, then yeah, the math is different, but you can maintain the same tick rate.

File: crates/bevy_time/src/fixed.rs [hunk 22]
```diff
@@ -0,0 +1,345 @@
...
+/// iteration.
+///
+/// The fixed timestep clock follows the [`Time<Virtual>`](Virtual) clock, which
+/// means it is affected by [`pause()`](Time::pause),
+/// [`set_relative_speed()`](Time::set_relative_speed) and
+/// [`set_max_delta()`](Time::set_max_delta) from virtual time. If the virtual
+/// clock is paused, the [`FixedUpdate`](bevy_app::FixedUpdate) schedule will
+/// not run. It is guaranteed that the [`elapsed()`](Time::elapsed) time in
+/// `Time<Fixed>` is always between the previous `elapsed()` and the next
+/// `elapsed()` value in `Time<Virtual>`, so the values are compatible.
```
[the remark this answers is not in the document]
Comment (nakedible) [reply crates/bevy_time/src/fixed.rs:48]: Changed it thus.

File: crates/bevy_time/src/fixed.rs (hunk 19 above)
[the remark this answers is not in the document]
Comment (nakedible) [reply crates/bevy_time/src/fixed.rs]: Thanks for spotting, fixed the docstring, also for `set_timestep_seconds`.

File: crates/bevy_time/src/fixed.rs (hunk 18 above)
[the remark this answers is not in the document]
Comment (nakedible) [reply crates/bevy_time/src/fixed.rs:52]: If there's something that can be added to the doc string to make the intention even clearer.

The only cases where timestep might have to be modified when the game is running is if the relative speed of the game gets slowed down so much that the orginal timestamp results in jerky physics (objects reacting to collisions at 6 FPS for example) or if the relative speed is sped up so much (like 8192x acceleration in submarine games) that simulating with the original timestep would be prohibitively expensive to do.

File: crates/bevy_time/src/fixed.rs (hunk 20 above)
[the remark this answers is not in the document]
Comment (djeedai) [reply crates/bevy_time/src/fixed.rs:184]: ...and so in the meantime at least use `div_f32()` for lack of a better API.

[the remark this answers is not in the document]
Comment (djeedai) [reply crates/bevy_time/src/fixed.rs:184]: Ah sorry missed the return `f32` when `div_f32()` returns `Duration`.

File: crates/bevy_time/src/fixed.rs (hunk 21 above)
[the remark this answers is not in the document]
Comment (djeedai) [reply crates/bevy_time/src/fixed.rs:191]: Same remark. I know those APIs are nightly I didn't mention them.

**Review by cart — APPROVED** [review]
I quite like these changes! The `Time` overriding behavior is a _bit_ implicit. But I do agree that making systems usable across contexts is useful. And it means 99% of users can just consume `Time::delta` in any context and it will "just work". This does make the system slightly harder to "fully grasp" as a result. I think some users will think they are consuming _the exact same value_ in both contexts. But I think the tradeoff is worth it. For users that need to care, you wrote really nice docs explaining everything. I cannot conceive of a better system.

Great work!

(I just have one comment on the default fixed timestep value)

File: crates/bevy_time/src/fixed.rs [hunk 23]
```diff
@@ -0,0 +1,345 @@
...
+/// [`Time<Virtual>`](Virtual). The fixed clock is automatically set as the
+/// generic [`Time`] resource during [`FixedUpdate`](bevy_app::FixedUpdate)
+/// schedule processing.
+///
+/// The fixed timestep clock advances in fixed-size increments, which is extremely useful for
+/// writing logic (like physics) that should have consistent behavior, regardless of framerate.
+///
+/// The default [`timestep()`](Time::timestep) is 64 hertz, or 15625
+/// microseconds. This value was chosen for being a power of two,
+/// which losslessly convert into [`f32`] and [`f64`], while only being
```
[the remark this answers is not in the document]
Comment (maniwani) [reply crates/bevy_time/src/fixed.rs:23]: > Is this lossless `f32` / `f64` conversion really necessary? Have we shown that it solves a real problem? 

No, but the product of another float and a power-of-two is also free of rounding errors, which is nice. People will often repeatedly multiply by `time.delta_seconds()` for integration, and having no drift with the default setting is just nice. 

`FixedUpdate` exists for accurate and stable math as much as it does to get a handle on performance.

> I think we can't / shouldn't do less than the framerate / 60hz by default, as without interpolation that will result in less than framerate-smooth physics.

The case you're using as an example is not smooth. If you set the tick rate to match the expected framerate, then most frames will run either 0 or 2 fixed updates (if your frame times are stable), because the duration of any frame will never quite exactly equal the fixed timestep. It's a degenerate case in a sense.

There is no default we can choose that can effectively substitute for actual smoothing.[^1]

> But doing this also means we're doing more work per frame than will likely be necessary for most games.

Not quite. 64 TPS @ 60 FPS would actually most likely result in _fewer_ frames having to run 2 fixed updates. The vast majority of frames (assuming stable frame times) would run 1.

> One commonality is that fixed update Hz are generally less than or equal to the frame time update Hz.

I think part of what you're asking is "Do other engines have specific reasons for their defaults that we may be discounting?" and I think the answer to that is "No."

The most compelling reasoning I can think of is that if an engine only samples inputs on a new frame, then if most monitors refresh at 60Hz, not updating more than the monitor refreshes and not ticking more than input is collected might feel like a natural conclusion.

But we don't sample inputs.
(It just so happens that we _alias_ input events to a frame, but we're working on improving that, see #9087). 

> Unity defaults to 50Hz.

I can't find it anymore, but I remember reading through a Unity thread where a Unity employee asked around internally and reported that nobody remembered why it's 50Hz. It's not a particularly "interesting" value anyway. Sometimes Unity users complain about it not being 60Hz [because they think it being 60Hz will make things look smoother][1]. (It won't!)

(If I find the thread, I will link it here for posterity.)

> Unreal seems to use "sub stepping", which breaks the normal update delta into X "substeps".

Unreal doesn't have an equivalent of `FixedUpdate`. Without sub-stepping, it's just variable delta time. With sub-stepping enabled, frames longer than the _max_ step size are subdivided into steps `<=` that step size. But the vast majority of them will advance by variable amounts smaller than that step size.

> Godot defaults to 60Hz.

I assume it's just because it's the most familiar choice. It's still the most common refresh rate, and you can point at plenty of games that feature that rate, whereas Counter Strike and Valorant are the only two I can name off the top that feature power-of-two tick rates.

> What is the cost of doing exactly 60Hz?

There is nothing actually special about 60Hz. It is a good default, because it's pretty responsive. But it's just a familiar number. I feel the general preference partly comes from the pretty pervasive misunderstanding about what results in smooth rendering.

64Hz has nicer properties (properties more relevant to why you'd use a fixed timestep) while being negligibly higher than 60Hz. That's why [I have been strongly advocating for it as the default][2].

[^1]: You can maybe [fuzz things to lock onto a preset framerate][3], but that strategy does not generalize.

[1]: https://forum.unity.com/threads/digital-foundry-unity-fixedtimestep-callout.1178485/
[2]: https://github.com/bevyengine/bevy/pull/8964#discussion_r1258949625
[3]: https://medium.com/@tglaiel/how-to-make-your-game-run-at-60fps-24c61210fe75

[the remark this answers is not in the document]
Comment (maniwani) [reply crates/bevy_time/src/fixed.rs:23]: Having said all that, it'd be fine if 60Hz was the default. Most users wouldn't think twice about it, which is also nice in a way.

I just don't think it should be treated as something beneficial for rendering. The fixed timestep is supposed to be decoupled from the framerate.

[the remark this answers is not in the document]
Comment (nakedible) [reply crates/bevy_time/src/fixed.rs:23]: @maniwani Feels stronger about this than I do, but I'll give my take as well.

> Is this lossless f32 / f64 conversion really necessary? Have we shown that it solves a real problem?

I don't think it is strictly necessary, or that we would have shown that it solves a real problem. It's more just a nice bonus for an arbitrary value that is >60 Hz. Anybody who needs lossless division can set it themselves.

> What is the cost of doing exactly 60Hz?

Doing "exactly" 60 Hz may have a pathological failure case where every other frame has two fixed updates and every other frame has zero. I also personally dislike cases where something works okay most of the time, but then suddenly sometimes there is a missed physics update frame or doubled update frame and the game developer doesn't fix this because it's not visible enough. I'd much rather have something that shows up every frame so they have to fix it.

Ultimately, I have no strong opinions on the default value - 50, 60, 62, 64, 120, 144, 240, 360, anything goes - so feel free to put anything you feel best there, and I don't think it is a significantly worse choice.

[the remark this answers is not in the document]
Comment (alice-i-cecile) [reply crates/bevy_time/src/fixed.rs:23]: I've seen this pathological 0/2 behavior in my games when using a 60hz fixed timestep: I think it's one of the worst defaults we could pick as a result. 64 Hz is fine, but mostly arbitrary beyond avoiding that problem.

[the remark this answers is not in the document]
Comment (maniwani) [reply crates/bevy_time/src/fixed.rs:23]: IMO, the default has to be 64Hz or 60Hz.

> I think we can't / shouldn't do less than the framerate / 60Hz by default without interpolation that will result in less than framerate-smooth physics.

I share cart's conclusion that less than 60Hz is no good, but I think so for a different reason.

I don't think a number less than 60Hz can be reasonably justified. Users just expect 60Hz or better from games, in terms of responsiveness (input delay), so that's the minimum.

[the remark this answers is not in the document]
Comment (cart) [reply crates/bevy_time/src/fixed.rs:23]: Ok I'm convinced, provided the doc here is updated to include the arguments here (namely the "pathological 0/2 behavior of 60" ).

**Comment by alice-i-cecile** [comment]
@nakedible let me know if you want a hand with those docs. Once those are written, we'll do a quick pass of review and then I can merge this in for you :)

**Comment by nakedible** [comment]
Nah, I'll handle the doc change later today, thanks though!

**Comment by nakedible** [comment]
Some extra doc lint checks were added in the meantime, so cleaned up those too so that tests pass again. Should be merge ready from my side.

**Review by alice-i-cecile — APPROVED** [review]

**Comment by rlidwka** [comment]
Can you give an advice on how I can create a custom `Time` specialization?

In my own crate, I can't add `impl Time<MyTime> {}`, because it gives the following error:

```rust
error[E0116]: cannot define inherent `impl` for a type outside of the crate where the type is defined
  |
3 | impl Time<MyTime> {
  | ^^^^^^^^^^^^^^^^^ impl for type defined outside of crate.
  |
  = note: define and implement a trait or new type instead
```

But I'd like users to have the same interface (e.g. `Time<MyTime>::from_seconds`) as bevy core times do.

Is a custom trait (that people have to explicitly import) the only option here?

**Comment by rlidwka** [comment]
@nakedible, why did you decide to go with:

```rs
pub struct Time<T> { ... }
pub struct Fixed;

fn system(time: Res<Time<Fixed>>) {}
```

as opposed to this?:

```rs
pub struct Time {...}

#[derive(Deref, DerefMut)]
pub struct FixedTime(Time);

fn system(time: Res<FixedTime>) {}
```

I.e. why `Time` wraps specialization struct, and not the other way around?

**Comment by djeedai** [comment]
I think because this allows `Time` == `Time<()>` syntax which is more compact and looks like the previous version.

**Comment by nakedible** [comment]
In the design phase I got some opposition to doing this with `Deref`, as it was felt to be too implicit. Also, even though Bevy differs in many places already, from Rust docs:

> Implementing Deref for smart pointers makes accessing the data behind them convenient, which is why they implement Deref. On the other hand, the rules regarding Deref and [DerefMut](https://doc.rust-lang.org/std/ops/trait.DerefMut.html) were designed specifically to accommodate smart pointers. Because of this, **Deref should only be implemented for smart pointers to avoid confusion.**

Honestly could've gone either way. `Deref` is more "traditional", where as wrapping the specialization makes it more explicit. If this final design would be converted to `Deref`, I'm not sure the initial opposition to `Deref` would still hold.

**Comment by maniwani** [comment]
> Can you give an advice on how I can create a custom `Time` specialization?
>
> In my own crate, I can't add `impl Time<MyTime> {}`, because [of the orphan rule].

It's a little clunky, but you could implement the specialized methods using a trait.

```rust
pub trait MyTrait {
    /* ... */
}

impl MyTrait for Time<MyTime> {
    /* ... */
}
```

**Comment by regnarock** [comment]
There seems to be a slight mistake in the migration guide:
> Change system.on_fixed_timer(duration) to system.on_timer(duration). Timers in systems placed in FixedUpdate schedule automatically use the fixed time clock.

Should instead say:

- Change `system.on_fixed_timer(duration)` to **`system.run_if(on_timer(duration))`**. Timers in systems placed in `FixedUpdate` schedule automatically use the fixed time clock.

This mistake also appears in the [migration guide](https://bevyengine.org/learn/migration-guides/0.11-0.12/#unify-fixedtime-and-time-while-fixing-several-problems)
