### PR TITLE
Disable irradiance volumes on WebGL and WebGPU.

### LINKED ISSUE #11885: WebGL2 support broken: index out of bounds
## Bevy version fe777d5c3fba64bec250b8ced3a6ba98fbd07a64

The deferred rendering example is broken on WebGL2 (And will also be broken on WebGPU, I expect).

The issue was introduced at https://github.com/bevyengine/bevy/commit/4c15dd0fc52a539a9bd41452cdae7fd07ec77134 with https://github.com/bevyengine/bevy/pull/10268

```
panicked at [...]\.cargo\registry\src\index.crates.io-6f17d22bba15001f\wgpu-hal-0.19.1\src\gles\command.rs:749:21:
index out of bounds: the len is 16 but the index is 16
```

### PR DESCRIPTION
**Pull request by pcwalton**
They cause the number of texture bindings to overflow on those platforms. Ultimately, we shouldn't unconditionally disable them, but this fixes a crash blocking 0.13.

Closes #11885.

### CODE REVIEW

**Review by cart — APPROVED** [review]
Tested on both WebGL and WebGPU and it works as expected. Thanks for the quick fix!

File: crates/bevy_pbr/src/render/mesh.rs [hunk 1]
```diff
@@ -825,7 +827,7 @@ impl SpecializedMeshPipeline for MeshPipeline {
             shader_defs.push("ENVIRONMENT_MAP".into());
         }
 
-        if key.contains(MeshPipelineKey::IRRADIANCE_VOLUME) {
+        if key.contains(MeshPipelineKey::IRRADIANCE_VOLUME) && IRRADIANCE_VOLUMES_ARE_USABLE {
             shader_defs.push("IRRADIANCE_VOLUME".into());
```
Comment (IceSentry) [inline crates/bevy_pbr/src/render/mesh.rs:831]: Why not just reuse this shader_def instead of using a separate one?

Comment (cart) [reply crates/bevy_pbr/src/render/mesh.rs:831]: I think there are two reasons:

1. MeshPipelineKey::IRRADIANCE_VOLUME is currently getting set in scenes like `deferred_rendering.rs`, even when irradiance volumes aren't used.
2. IRRADIANCE_VOLUMES_ARE_USABLE is used in a few places unconditionally outside of the context of shader defs.

Comment (cart) [reply crates/bevy_pbr/src/render/mesh.rs:831]: I think for now we merge as-is. This isn't hurting anything and we're likely to improve this situation in the future.
