### PR TITLE
Using Cas instead of CAS #14341

### LINKED ISSUE #14341: Types related to Contrast Adaptive Sharpening should be `Cas*` instead of `CAS*`
## Bevy version

main

## What you did

Stumbled upon this out-of-place casing for [`CASPlugin`](https://docs.rs/bevy/latest/bevy/core_pipeline/contrast_adaptive_sharpening/struct.CASPlugin.html).

## What went wrong

Every other plugin beginning with an acronym uses the style of e.g. [`PbrPlugin`](https://docs.rs/bevy/latest/bevy/pbr/struct.PbrPlugin.html), which is the official [rust naming convention](https://rust-lang.github.io/api-guidelines/naming.html#casing-conforms-to-rfc-430-c-case).

## Additional information

I didn't see any discussion about this one way or another in #7422.

### PR DESCRIPTION
**Pull request by Cioraz**
# Objective

- Replacing CAS with Cas in CASPlugin
- Closes #14341

## Solution

- Simple replace

### CODE REVIEW

**Review by mockersf — APPROVED** [review]

**Comment by mockersf** [comment]
this doesn't close #14341, there are other types using `CAS` instead of `Cas`: found `DenoiseCAS`, `CASUniform`, `CASNode`, `CASPipeline`, `CASPipelineKey`, `ViewCASPipeline` with a quick search.

Could you also change those?

File: crates/bevy_core_pipeline/src/contrast_adaptive_sharpening/mod.rs [hunk 1]
```diff
@@ -23,14 +23,14 @@ use bevy_render::{
 
 mod node;
 
-pub use node::CASNode;
+pub use node::CasNode;
 
-/// Applies a contrast adaptive sharpening (CAS) filter to the camera.
+/// Applies a contrast adaptive sharpening (Cas) filter to the camera.
```
Comment (mockersf) [inline crates/bevy_core_pipeline/src/contrast_adaptive_sharpening/mod.rs:28]: in doc it should stay CAS

File: crates/bevy_core_pipeline/src/contrast_adaptive_sharpening/mod.rs [hunk 2]
```diff
@@ -183,29 +183,29 @@ impl FromWorld for CASPipeline {
                 (
                     texture_2d(TextureSampleType::Float { filterable: true }),
                     sampler(SamplerBindingType::Filtering),
-                    // CAS Settings
-                    uniform_buffer::<CASUniform>(true),
+                    // Cas Settings
```
Comment (janhohenheim) [inline crates/bevy_core_pipeline/src/contrast_adaptive_sharpening/mod.rs:186]:
```suggestion
                    // CAS Settings
```

**Review by janhohenheim — CHANGES_REQUESTED** [review]

**Review by mockersf — APPROVED** [review]
