### PR TITLE
Fix swapped docs for `Rot2::rotation_to/from_y`

### LINKED ISSUE #14301: Wildly inconsistent documentation on Dir2 <-> Rot2 conversion methods.
## How can Bevy's documentation be improved?

https://github.com/bevyengine/bevy/blob/d7080369a7471e6aa9747bad41a4469092f9967b/crates/bevy_math/src/direction.rs#L219-L245

```rust
    /// Get the rotation that rotates this direction to the Y-axis.
    #[inline]
    pub fn rotation_from_y(self) -> Rot2 {
```
This docstring is imho completely backwards to what it should say, notably, it is backwards to what the docstring for `rotation_from_x` says.

## Solution

Figure out which way the methods *actually* go, and update the docstrings appropriately. (Imo the semantics on the x-axis functions are correct, and the doc strings on the y-axis functions are wrong.)

### PR DESCRIPTION
**Pull request by mweatherley**
# Objective

Fixes #14301 

## Solution

Swap them so that they are no longer swapped.

### CODE REVIEW

**Review by alice-i-cecile — APPROVED** [review]

File: crates/bevy_math/src/direction.rs [hunk 1]
```diff
@@ -229,7 +229,7 @@ impl Dir2 {
         self.rotation_from_x().inverse()
     }
 
-    /// Get the rotation that rotates this direction to the Y-axis.
+    /// Get the rotation that rotates the Y-axis to this direction.
```
Comment (MrGVSV) [inline crates/bevy_math/src/direction.rs:232]: Question: would it be clearer and/or easier to remember if we used the term "from" in the docs?
```suggestion
    /// Get the rotation that rotates to this direction from the Y-axis.
```

**Review by MrGVSV — APPROVED** [review]

File: crates/bevy_math/src/direction.rs (hunk 1 above)
Comment (mweatherley) [reply crates/bevy_math/src/direction.rs:232]: Good idea!

Comment (mweatherley) [reply crates/bevy_math/src/direction.rs:232]: I tried this out, but I found that it makes the wording a little weird between the `to/from` method docs, so I think I'm going to leave it alone for now.
