### PR TITLE
Disable clustered decals on Metal.

### LINKED ISSUE #17553: macos: Resource limit exceeded errors since clustered decals
## Bevy version

main, bisected to fc831c390d565d4a0111c3ab5d4ea84183800007

## Relevant system information

SystemInfo { os: "macOS 14.5 Sonoma", kernel: "23.5.0", cpu: "Apple M1 Max", core_count: "10", memory: "64.0 GiB" }    
AdapterInfo { name: "Apple M1 Max", vendor: 0, device: 0, device_type: IntegratedGpu, driver: "", driver_info: "", backend: Metal }

(Also failing on GH macos runner)

## What you did

Some fancier rendering examples are crashing. This may not be exhaustive, but these are the ones that failed in CI.

`cargo run --example depth_of_field`
`cargo run --example mixed_lighting`
`cargo run --example lightmaps`

## What went wrong

```
2025-01-27T04:20:11.810801Z ERROR wgpu_hal::metal::device: Resource limit exceeded: StageInfo { stage: Fragment, counters: ResourceData { buffers: 14, textures: 47, samplers: 17 }, pc_buffer: None, pc_limit: 0, sizes_buffer: Some(13), need_sizes_buffer: true, resources: {ResourceBinding { group: 0, binding: 0 }: BindTarget { buffer: Some(0), texture: None, sampler: None, binding_array_size: None, mutable: false }, ResourceBinding { group: 0, binding: 1 }: BindTarget { buffer: Some(1), texture: None, sampler: None, binding_array_size: None, mutable: false }, ResourceBinding { group: 0, binding: 2 }: BindTarget { buffer: None, texture: Some(0), sampler: None, binding_array_size: None, mutable: false }, ResourceBinding { group: 0, binding: 3 }: BindTarget { buffer: None, texture: None, sampler: Some(Resource(0)), binding_array_size: None, mutable: false }, ResourceBinding { group: 0, binding: 5 }: BindTarget { buffer: None, texture: Some(1), sampler: None, binding_array_size: None, mutable: false }, ResourceBinding { group: 0, binding: 6 }: BindTarget { buffer: None, texture: None, sampler: Some(Resource(1)), binding_array_size: None, mutable: false }, ResourceBinding { group: 0, binding: 8 }: BindTarget { buffer: Some(2), texture: None, sampler: None, binding_array_size: None, mutable: false }, ResourceBinding { group: 0, binding: 9 }: BindTarget { buffer: Some(3), texture: None, sampler: None, binding_array_size: None, mutable: false }, ResourceBinding { group: 0, binding: 10 }: BindTarget { buffer: Some(4), texture: None, sampler: None, binding_array_size: None, mutable: false }, ResourceBinding { group: 0, binding: 11 }: BindTarget { buffer: Some(5), texture: None, sampler: None, binding_array_size: None, mutable: false }, ResourceBinding { group: 0, binding: 12 }: BindTarget { buffer: Some(6), texture: None, sampler: None, binding_array_size: None, mutable: false }, ResourceBinding { group: 0, binding: 13 }: BindTarget { buffer: Some(7), texture: None, sampler: None, binding_array_size: None, mutable: false }, ResourceBinding { group: 0, binding: 15 }: BindTarget { buffer: Some(8), texture: None, sampler: None, binding_array_size: None, mutable: false }, ResourceBinding { group: 0, binding: 16 }: BindTarget { buffer: None, texture: Some(2), sampler: None, binding_array_size: None, mutable: false }, ResourceBinding { group: 0, binding: 17 }: BindTarget { buffer: None, texture: Some(3), sampler: None, binding_array_size: Some(8), mutable: false }, ResourceBinding { group: 0, binding: 18 }: BindTarget { buffer: None, texture: Some(11), sampler: None, binding_array_size: Some(8), mutable: false }, ResourceBinding { group: 0, binding: 19 }: BindTarget { buffer: None, texture: None, sampler: Some(Resource(2)), binding_array_size: None, mutable: false }, ResourceBinding { group: 0, binding: 20 }: BindTarget { buffer: Some(9), texture: None, sampler: None, binding_array_size: None, mutable: false }, ResourceBinding { group: 0, binding: 21 }: BindTarget { buffer: None, texture: Some(19), sampler: None, binding_array_size: Some(8), mutable: false }, ResourceBinding { group: 0, binding: 22 }: BindTarget { buffer: None, texture: None, sampler: Some(Resource(3)), binding_array_size: None, mutable: false }, ResourceBinding { group: 0, binding: 23 }: BindTarget { buffer: Some(10), texture: None, sampler: None, binding_array_size: None, mutable: false }, ResourceBinding { group: 0, binding: 24 }: BindTarget { buffer: None, texture: Some(27), sampler: None, binding_array_size: Some(8), mutable: false }, ResourceBinding { group: 0, binding: 25 }: BindTarget { buffer: None, texture: None, sampler: Some(Resource(4)), binding_array_size: None, mutable: false }, ResourceBinding { group: 0, binding: 26 }: BindTarget { buffer: None, texture: Some(35), sampler: None, binding_array_size: None, mutable: false }, ResourceBinding { group: 0, binding: 27 }: BindTarget { buffer: None, texture: None, sampler: Some(Resource(5)), binding_array_size: None, mutable: false }, ResourceBinding { group: 0, binding: 32 }: BindTarget { buffer: None, texture: Some(36), sampler: None, binding_array_size: None, mutable: false }, ResourceBinding { group: 0, binding: 33 }: BindTarget { buffer: None, texture: None, sampler: Some(Resource(6)), binding_array_size: None, mutable: false }, ResourceBinding { group: 1, binding: 0 }: BindTarget { buffer: Some(11), texture: None, sampler: None, binding_array_size: None, mutable: false }, ResourceBinding { group: 1, binding: 4 }: BindTarget { buffer: None, texture: Some(37), sampler: None, binding_array_size: Some(4), mutable: false }, ResourceBinding { group: 1, binding: 5 }: BindTarget { buffer: None, texture: None, sampler: Some(Resource(7)), binding_array_size: Some(4), mutable: false }, ResourceBinding { group: 2, binding: 0 }: BindTarget { buffer: Some(12), texture: None, sampler: None, binding_array_size: None, mutable: false }, ResourceBinding { group: 2, binding: 1 }: BindTarget { buffer: None, texture: Some(41), sampler: None, binding_array_size: None, mutable: false }, ResourceBinding { group: 2, binding: 2 }: BindTarget { buffer: None, texture: None, sampler: Some(Resource(11)), binding_array_size: None, mutable: false }, ResourceBinding { group: 2, binding: 3 }: BindTarget { buffer: None, texture: Some(42), sampler: None, binding_array_size: None, mutable: false }, ResourceBinding { group: 2, binding: 4 }: BindTarget { buffer: None, texture: None, sampler: Some(Resource(12)), binding_array_size: None, mutable: false }, ResourceBinding { group: 2, binding: 5 }: BindTarget { buffer: None, texture: Some(43), sampler: None, binding_array_size: None, mutable: false }, ResourceBinding { group: 2, binding: 6 }: BindTarget { buffer: None, texture: None, sampler: Some(Resource(13)), binding_array_size: None, mutable: false }, ResourceBinding { group: 2, binding: 7 }: BindTarget { buffer: None, texture: Some(44), sampler: None, binding_array_size: None, mutable: false }, ResourceBinding { group: 2, binding: 8 }: BindTarget { buffer: None, texture: None, sampler: Some(Resource(14)), binding_array_size: None, mutable: false }, ResourceBinding { group: 2, binding: 9 }: BindTarget { buffer: None, texture: Some(45), sampler: None, binding_array_size: None, mutable: false }, ResourceBinding { group: 2, binding: 10 }: BindTarget { buffer: None, texture: None, sampler: Some(Resource(15)), binding_array_size: None, mutable: false }, ResourceBinding { group: 2, binding: 11 }: BindTarget { buffer: None, texture: Some(46), sampler: None, binding_array_size: None, mutable: false }, ResourceBinding { group: 2, binding: 12 }: BindTarget { buffer: None, texture: None, sampler: Some(Resource(16)), binding_array_size: None, mutable: false }} }    
2025-01-27T04:20:11.811237Z ERROR wgpu::backend::wgpu_core: Handling wgpu errors as fatal by default    
thread 'Compute Task Pool (0)' panicked at /Users/met/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-23.0.1/src/backend/wgpu_core.rs:1034:18:
wgpu error: Validation Error

Caused by:
  In Device::create_pipeline_layout
    Not enough memory left.


note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Encountered a panic in system `bevy_render::render_resource::pipeline_cache::PipelineCache::process_pipeline_queue_system`!
thread '<unnamed>' panicked at /Users/met/src/bevy/crates/bevy_render/src/render_resource/pipeline_cache.rs:577:28:
index out of bounds: the len is 0 but the index is 13
Encountered a panic in system `bevy_render::renderer::render_system`!
```

### PR DESCRIPTION
**Pull request by pcwalton**
Unfortunately, Apple platforms don't have enough texture bindings to properly support clustered decals. This should be fixed once `wgpu` has first-class bindless texture support. In the meantime, we disable them.

Closes #17553.

### CODE REVIEW

File: examples/3d/clustered_decals.rs [hunk 1]
```diff
@@ -13,6 +14,7 @@ use bevy::{
     prelude::*,
     render::render_resource::{AsBindGroup, ShaderRef},
 };
+use bevy_render::renderer::{RenderAdapter, RenderDevice};
```
Comment (IceSentry) [inline examples/3d/clustered_decals.rs:17]:
```suggestion
use bevy::render::renderer::{RenderAdapter, RenderDevice};
```

**Review by IceSentry — APPROVED** [review]

File: crates/bevy_pbr/src/decal/clustered.rs [hunk 2]
```diff
@@ -367,3 +367,16 @@ fn upload_decals(
 
     decals_buffer.write_buffer(&render_device, &render_queue);
 }
+
+/// Returns true if clustered decals are usable on the current platform or false
+/// otherwise.
```
Comment (alice-i-cecile) [inline crates/bevy_pbr/src/decal/clustered.rs:372]:
```suggestion
/// otherwise.
///
/// Clustered decals are currently disabled on MacOS and iOS due to insufficient texture bindings and limited bindless support in wgpu.
```

Putting this rationale in the docs helps users who are trying to piece this together without opening up the source code.
