### PR TITLE
Cascaded shadow maps: Fix prepass ortho depth clamping

### LINKED ISSUE #8645: Directional light shadows disappear when camera is rotated
## Bevy version
0.10.1,
main [(f76b3c4)](https://github.com/bevyengine/bevy/commit/f76b3c4230e890e3cdeb01c26809cf4bde8d26f4)

## Relevant system information
- SteamOS 3.4.6
`AdapterInfo { name: "AMD Custom GPU 0405 (RADV VANGOGH)", vendor: 4098, device: 5695, device_type: IntegratedGpu, driver: "radv", driver_info: "Mesa 22.2.5", backend: Vulkan }`

## What you did

- Spawn two horizontal planes above each other
- Spawn directional light and a camera between the planes
- Rotate camera

See somewhat minimal example [here](https://gist.github.com/GitGhillie/349873973418e3d2c548ef73b2310c7f).

## What went wrong
Depending on the distance and angle of the camera some shadows partially disappear. As seen [here](https://github.com/bevyengine/bevy/discussions/8571) it can quickly ruin a scene.

In the example code I gave only rectangular shadows should be possible but when you spawn in it looks like this:
bevy_shadow
Move around the camera with the mouse and you will see the shadow change shape.

## Additional information
Same issue on my Windows 10 desktop (tested with Bevy 0.10.1) but I'm currently abroad so I cannot check the exact `AdapterInfo`. It has an AMD Vega 56 gpu and uses the Vulkan backend as well.

### PR DESCRIPTION
**Pull request by danchia**
# Objective

- Fixes #8645

## Solution

Cascaded shadow maps use a technique commonly called shadow pancaking to enhance shadow map resolution by restricting the orthographic projection used in creating the shadow maps to the frustum slice for the cascade. The implication of this restriction is that shadow casters can be closer than the near plane of the projection volume.

Prior to this PR, we address clamp the depth of the prepass vertex output to ensure that these shadow casters do not get clipped, resulting in shadow loss. However, a flaw / bug of the prior approach is that the depth that gets written to the shadow map isn't quite correct - the depth was previously derived by interpolated the clamped clip position, resulting in depths that are further than they should be. This creates artifacts that are particularly noticeable when a very 'long' object intersects the near plane close to perpendicularly.

The fix in this PR is to propagate the unclamped depth to the prepass fragment shader and use that depth value directly.

A complementary solution would be to use [DEPTH_CLIP_CONTROL](https://docs.rs/wgpu/latest/wgpu/struct.Features.html#associatedconstant.DEPTH_CLIP_CONTROL) to request `unclipped_depth`. However due to the relatively low support of the feature on Vulkan (I believe it's ~38%), I went with this solution for now to get the broadest fix out first.

---

## Changelog

- Fixed: Shadows from directional lights were sometimes incorrectly omitted when the shadow caster was partially out of view.

### CODE REVIEW

**Comment by cart** [comment]
Thanks for the quick fix! This does mean that in a directional light shadow pass we're now running the prepass fragment shader of every mesh seen by a directional light right? That seems like a high price to pay for a fix, although I don't have a better solution.

**Comment by cart** [comment]
Also no clue if this was an issue prior to CSM, but even after this fix there are a few corner cases that get clipped for me (although you really need to hunt for them and they go away with even slight perspective changes):
image

**Comment by danchia** [comment]
> Thanks for the quick fix! This does mean that in a directional light shadow pass we're now running the prepass fragment shader of every mesh seen by the directional light right? That seems like a high price to pay for a fix, although I don't have a better solution.

It does, and I too don't see an easy way out of this :(
Using the `unclipped_depth` flag I described in the PR description would allow us to avoid it on most desktop / native platforms.

That said, I wonder if the GPU side of shadow draws is more draw count / vertex bound and less fragment bound?

File: crates/bevy_pbr/src/prepass/mod.rs [hunk 1]
```diff
@@ -385,6 +385,7 @@ where
         ));
         if key.mesh_key.contains(MeshPipelineKey::DEPTH_CLAMP_ORTHO) {
             shader_defs.push("DEPTH_CLAMP_ORTHO".into());
+            shader_defs.push("PREPASS_FRAGMENT".into());
```
Comment (cart) [inline crates/bevy_pbr/src/prepass/mod.rs:388]: Can you add a `// PERF:` comment here explaining that this will force the prepass fragment shader to run for things like directional lights, and link to this PR?

This seems like the kind of thing that would be very easy to forget.

Comment (cart) [reply crates/bevy_pbr/src/prepass/mod.rs:394]: Resolved!

Comment (danchia) [reply crates/bevy_pbr/src/prepass/mod.rs:394]: Thanks @cart!

**Comment by danchia** [comment]
@cart did you mean to push all the GPU counter commits as well?

**Comment by cart** [comment]
Haha nope (I was profiling the change). Fixed :)

**Comment by danchia** [comment]
> Haha nope (I was profiling the change). Fixed :)

Find anything interesting in the profiles?

**Review by cart — APPROVED** [review]
My profiling couldn't detect a meaningful performance difference in the directional light shadow pass from this change (many_cubes example, but fixed to a specific camera view). Its possible that with more (or different) entities (or more directional lights) this could get more pronounced, but this seems like a reasonable fix for now.

**Comment by JMS55** [comment]
@danchia wgpu 0.17 will come with https://github.com/gfx-rs/wgpu/pull/3892, will that improve anything?
