### PR TITLE
Fix WebGL mode for Adreno GPUs

### LINKED ISSUE #8047: WASM WebGL examples crash "wgpu error: Validation Error"
## Bevy version

0.10.0 (or whichever version is currently used in the bevy WASM examples).

## Relevant system information

Android 12 Chrome (v110.0) on pixel 3a, and android 13 Firefox (v110.1) on pixel 4a.

```ignore
`AdapterInfo { name: "Adreno (TM) 615", vendor: 20803, device: 0, device_type: IntegratedGpu, driver: "", driver_info: "", backend: Gl }`
```

## What you did

Opened the https://bevyengine.org/examples/3d/3d-scene/

## What went wrong

The 3d scene does not load.

## Additional information

I am not sure whether the error is in gfx-rs/naga or bevy's usage of it (through gfx-rs/wgpu). The string `Assertion failed: false && "Unknown named pointer type or missing metadata"` also appears in https://github.com/google/filament/issues/6355 .

My own bevy application that uses PbrBundles also had this problem in the WASM build. Then while looking for a cause I noticed that the example also does not run. Removing all PbrBundles or rolling back to bevy 0.9.1 both cause the error to disappear.

chrome on android console log:

2023-03-11-220834_1152x813_scrot

```ignore
3d_scene.js:368 INFO crates/bevy_winit/src/system.rs:51 Creating new window "Bevy App" (0v0)
3d_scene.js:368 INFO crates/bevy_render/src/renderer/mod.rs:128 AdapterInfo { name: "Adreno (TM) 615", vendor: 20803, device: 0, device_type: IntegratedGpu, driver: "", driver_info: "", backend: Gl }
3d_scene.js:1069 The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu
(anonymous) @ 3d_scene.js:1069
handleError @ 3d_scene.js:238
imports.wbg.__wbg_newwithcontextoptions_6c6a79a71ed7efa3 @ 3d_scene.js:1068
$web_sys::features::gen_AudioContext::AudioContext::new_with_context_options::ha94b89a135bed2d1 @ 0579948a:0xe75281
$<cpal::host::webaudio::Device as cpal::traits::DeviceTrait>::build_output_stream_raw::hcf4f90d02fcc6b21 @ 0579948a:0x2c8e37
$<cpal::platform::platform_impl::Device as rodio::stream::CpalDeviceExt>::new_output_stream_with_format::ha1c184b5890ab365 @ 0579948a:0x284651
$<cpal::platform::platform_impl::Device as rodio::stream::CpalDeviceExt>::try_new_output_stream_config::h7b6caeb12e8a238d @ 0579948a:0x5a73dc
$rodio::stream::OutputStream::try_from_device_config::hcdb3f909034fc80a @ 0579948a:0x76caad
$rodio::stream::OutputStream::try_default::h5128867b7c029c9b @ 0579948a:0x5478d9
$<T as bevy_ecs::world::FromWorld>::from_world::h407da30cb0f34772 @ 0579948a:0xa94164
$bevy_app::app::App::init_resource::h7afb885464a4de8c @ 0579948a:0x6a672f
$<bevy_audio::AudioPlugin as bevy_app::plugin::Plugin>::build::h7b56af866cce7f92 @ 0579948a:0xe71466
$bevy_app::app::App::add_boxed_plugin::h2210e446ce8b74b4 @ 0579948a:0x3a91fc
$bevy_app::plugin_group::PluginGroupBuilder::finish::hc518d27aa582e36e @ 0579948a:0x52fef9
$_3d_scene::main::hac1f03664ce5a2e6 @ 0579948a:0x2ff921
$std::sys_common::backtrace::__rust_begin_short_backtrace::h7d6950ad3cf8e90f @ 0579948a:0xeef88f
$std::rt::lang_start::{{closure}}::hbac199d3774bc2e9 @ 0579948a:0xe93865
$std::rt::lang_start_internal::h47a582f19b98cc9f @ 0579948a:0xc11383
$main @ 0579948a:0xe8c766
$__wbindgen_start @ 0579948a:0xee7564
finalizeInit @ 3d_scene.js:1847
init @ 3d_scene.js:1879
await in init (async)
(anonymous) @ (index):286
3d_scene.js:1085 The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu
(anonymous) @ 3d_scene.js:1085
handleError @ 3d_scene.js:238
imports.wbg.__wbg_resume_72fe7cd3e68b861a @ 3d_scene.js:1084
$web_sys::features::gen_AudioContext::AudioContext::resume::h8f55082cd0d59b8d @ 0579948a:0xe75356
$<cpal::host::webaudio::Stream as cpal::traits::StreamTrait>::play::hd14c42327a9fc2bd @ 0579948a:0x7f20c3
$<cpal::platform::platform_impl::Stream as cpal::traits::StreamTrait>::play::h2cf8e833296a4838 @ 0579948a:0xeeda19
$rodio::stream::OutputStream::try_from_device_config::hcdb3f909034fc80a @ 0579948a:0x76cb83
$rodio::stream::OutputStream::try_default::h5128867b7c029c9b @ 0579948a:0x5478d9
$<T as bevy_ecs::world::FromWorld>::from_world::h407da30cb0f34772 @ 0579948a:0xa94164
$bevy_app::app::App::init_resource::h7afb885464a4de8c @ 0579948a:0x6a672f
$<bevy_audio::AudioPlugin as bevy_app::plugin::Plugin>::build::h7b56af866cce7f92 @ 0579948a:0xe71466
$bevy_app::app::App::add_boxed_plugin::h2210e446ce8b74b4 @ 0579948a:0x3a91fc
$bevy_app::plugin_group::PluginGroupBuilder::finish::hc518d27aa582e36e @ 0579948a:0x52fef9
$_3d_scene::main::hac1f03664ce5a2e6 @ 0579948a:0x2ff921
$std::sys_common::backtrace::__rust_begin_short_backtrace::h7d6950ad3cf8e90f @ 0579948a:0xeef88f
$std::rt::lang_start::{{closure}}::hbac199d3774bc2e9 @ 0579948a:0xe93865
$std::rt::lang_start_internal::h47a582f19b98cc9f @ 0579948a:0xc11383
$main @ 0579948a:0xe8c766
$__wbindgen_start @ 0579948a:0xee7564
finalizeInit @ 3d_scene.js:1847
init @ 3d_scene.js:1879
await in init (async)
(anonymous) @ (index):286
3d_scene.js:368 ERROR  Shader translation error for stage VERTEX | FRAGMENT | VERTEX_FRAGMENT: Assertion failed: false && "Unknown named pointer type or missing metadata"
```

### LINKED ISSUE #8506: Fog crashes on certain mobile devices in WASM
## Bevy version

670f3f0dce2ced27388b10672d30594d399434e1

## Relevant system information

```ignore
`AdapterInfo { name: "Adreno (TM) 660", vendor: 20803, device: 0, device_type: IntegratedGpu, driver: "", driver_info: "", backend: Gl }`
```

## What you did

I ran a basic 3D Shapes example on WASM on my phone. 

## What went wrong

I expected the example the example to run like it did on my computer but instead it crashes with the error
```ignore
Shader translation error for stage VERTEX | FRAGMENT | VERTEX_FRAGMENT:  log.target = "wgpu::backend::direct";log.module_path = "wgpu::backend::direct";
```
```ignore
panicked at 'wgpu error: Validation Error

Caused by:
    In Device::create_render_pipeline
      note: label = `pbr_opaque_mesh_pipeline`
    Internal error in VERTEX | FRAGMENT | VERTEX_FRAGMENT shader: 
```

## Additional information

I first asked about it on your discord [here](https://discord.com/channels/691052431525675048/1100763202201075773).

Using `git bisect` I was able to find the commit that introduced the bug which is 1a96d820fdfd0bb303b2555169cd45a6a194195e. 

Further by removing the lines
```wgsl
    if (fog.mode != FOG_MODE_OFF && (material.flags & STANDARD_MATERIAL_FLAGS_FOG_ENABLED_BIT) != 0u) {
        output_color = apply_fog(output_color, in.world_position.xyz, view.world_position.xyz);
    }
```
in `pbr.wgsl`, in `bevy_pbr`, the example once again runs on my phone.

What is interesting however is that my colleague ran it on his phone without issue, his adapter info is the following.
```ignore
AdapterInfo { name: "Mali-G78", vendor: 5045, device: 0, device_type: IntegratedGpu, driver: "", driver_info: "", backend: Gl }
```

Furthermore I tried running it on my tablet which also crashes, I unfortunately cannot read logs from the tablet but it uses the `Adreno 619` GPU.

### PR DESCRIPTION
**Pull request by TotalKrill**
# Objective

- This fixes a crash when loading shaders, when running an Adreno GPU and using WebGL mode. 
- Fixes #8506 
- Fixes #8047

## Solution

- The shader pbr_functions.wgsl, will fail in apply_fog function, trying to access values that are null on Adreno chipsets using WebGL, these devices are commonly found in android handheld devices.

### CODE REVIEW

**Review by alice-i-cecile — APPROVED** [review]
I can't verify this myself, but the comments are good and the fix is reasonable.

File: crates/bevy_pbr/src/render/light.rs [hunk 1]
```diff
@@ -216,7 +216,14 @@ pub struct GpuLights {
 
 // NOTE: this must be kept in sync with the same constants in pbr.frag
 pub const MAX_UNIFORM_BUFFER_POINT_LIGHTS: usize = 256;
+
+//NOTE: When running bevy on Adreno GPU chipsets in WebGL, any value above 1 will result in a crash
+// when loading the wgsl "pbr_functions.wgsl" in the function apply_fog.
+#[cfg(feature = "webgl")]
+pub const MAX_DIRECTIONAL_LIGHTS: usize = 1;
```
Comment (superdump) [inline crates/bevy_pbr/src/render/light.rs:223]: Hmm, is this the case for _all_ WebGL2? Or just with some Adreno GPU drivers?

**Review by superdump — CHANGES_REQUESTED** [review]

File: crates/bevy_pbr/src/render/light.rs (hunk 1 above)
Comment (Elabajaba) [reply crates/bevy_pbr/src/render/light.rs:223]: I don't think it's possible if we're using a const here, since you have to query the gpu driver at runtime.

**Comment by mockersf** [comment]
so the question is, do we want to reduce functionality for all webgl2 app for a few android devices?

**Comment by Elabajaba** [comment]
> so the question is, do we want to reduce functionality for all webgl2 app for a few android devices?

If we set this CPU side, it's possible to detect the driver at runtime using https://github.com/gfx-rs/wgpu/blob/2571af9557eeba59f00f69649ae6bcd9d5a62392/wgpu-types/src/lib.rs#L1303

**Comment by TotalKrill** [comment]
> so the question is, do we want to reduce functionality for all webgl2 app for a few android devices?

Yeah, I agree, its not the ideal solution. And getting a feature to start tweaking rendering paths depending on which adaptor is detected, will probably be the best solution. 

But then again, this is at least a third of all android devices (Adreno marketshare is approx 33% from what I can tell), not really only a few.

**Comment by TotalKrill** [comment]
In addition to this, I also do not think that more directional lights works as intended on WebGL regardless, from what I can tell, shadows does not seem to work at least on my computer.

**Review by cart — APPROVED** [review]
> If we make this not a const, it's possible to detect the driver at runtime using https://github.com/gfx-rs/wgpu/blob/2571af9557eeba59f00f69649ae6bcd9d5a62392/wgpu-types/src/lib.rs#L1303

I briefly poked around with this. Making it non-const is non-trivial and will require a bit of elbow grease.

I do think thats the best long-term strategy though. We should investigate it. I created #8992 to track that.

I just resolved merge conflicts.

File: crates/bevy_pbr/src/render/light.rs [hunk 2]
```diff
@@ -216,6 +216,12 @@ pub struct GpuLights {
...
+#[cfg(not(feature = "webgl"))]
```
Comment (mockersf) [inline crates/bevy_pbr/src/render/light.rs:224]: with how webgl is now set up, this needs to check too that it's not building for wasm

```suggestion
#[cfg(all(feature = "webgl", target_arch = "wasm32"))]
pub const MAX_DIRECTIONAL_LIGHTS: usize = 1;
#[cfg(any(not(feature = "webgl"), not(target_arch = "wasm32")))]
```

Comment (mockersf) [reply crates/bevy_pbr/src/render/light.rs:224]: as we want to keep webgl2 as the default wasm platform and there are no per platform default features, the webgl feature is now enabled by default on all platforms

Comment (cart) [reply crates/bevy_pbr/src/render/light.rs]: Nice catch!
