### PR TITLE
Fix `AssetChanged<A>` UB

### LINKED ISSUE #23057: Potential for UB in systems using `AssetChanged`
## Bevy version and features

`08a3f24` (main)

## What you did

I ran the following test in `bevy_asset/src/asset_changed.rs`.
```rust
#[test]
#[should_panic]
fn should_conflict() {
    // should conflict, doesn't.
    fn system(
        q1: Query<&Foo, AssetChanged<MyComponent>>,
        q2: Query<&mut AssetChanges<MyAsset>, bevy_ecs::query::Without<Foo>>,
    ) {
    }
   assert_is_system(system);
}
```
It failed.

## What went wrong

`q1`, through `AssetChanged` places a read access on `AssetChanges<MyAsset>`. Meanwhile, `q2` writes to `AssetChanges<MyAsset>`, and so the two queries should conflict. Yet they don't. This is potentially a source of UB.

## Additional information

While the situation where one `SystemParam` tries to access both an entity and a resource is rare, this only became UB after #20934. Currently, this has zero impact, because `AssetChanges<MyAsset>` is `pub(crate)` and we never create a `Query<&mut AssetChanges<A>>` query. However, if we remove resources from `Access`, this problem can also be triggered through `ResMut<AssetChanges<A>>`. Such a query *does* exist in the bevy codebase now, and as such this issue blocks #22910.

There are several solutions. 
- The most promising is #21557, which allows queries to query multiple different entities. 
- #22939 might also be a solution, but I haven't had time to look at how that redesign is going to work.
- A very ugly solution would be to wrap `AssetChanges` in an `Arc<RwLock<...>>` somehow, so conflicts don't matter.

### PR DESCRIPTION
**Pull request by Trashtalk217**
# Objective

Fixes #23057.

## Solution

Uses Nested Queries from #21557 to also register the resource entity to the access set.

## Testing

Added an extra test.

### CODE REVIEW

**Comment by alice-i-cecile** [comment]
Regression test please :)

**Comment by Trashtalk217** [comment]
I did. That's the extra test I added.

**Comment by alice-i-cecile** [comment]
Ah sorry, missed that!

File: crates/bevy_asset/src/asset_changed.rs [hunk 1]
```diff
@@ -235,7 +237,38 @@ unsafe impl<A: AsAssetId> WorldQuery for AssetChanged<A> {
...
+    // In order to access two different entities we implement init_nested_access.
+    fn init_nested_access(
+        state: &Self::State,
+        system_name: Option<&str>,
+        component_access_set: &mut FilteredAccessSet,
+        _world: UnsafeWorldCell,
+    ) {
+        let combined_access = component_access_set.combined_access();
+        assert!(
+            !combined_access.has_resource_write(state.resource_id),
```
Comment (chescock) [inline crates/bevy_asset/src/asset_changed.rs:251]: (I think this first check is redundant since the check below also checks resource access.  But since you're working on getting rid of resource access entirely, let's just merge this now and then rip it out later.)

File: crates/bevy_asset/src/asset_changed.rs [hunk 2]
```diff
@@ -324,6 +357,21 @@ mod tests {
         }
     }
 
+    #[test]
+    #[should_panic]
+    fn should_conflict() {
+        #[derive(Component)]
+        struct Foo;
+
+        // should conflict, doesn't.
```
Comment (chescock) [inline crates/bevy_asset/src/asset_changed.rs]: It does now, though, right?  

```suggestion
```

File: crates/bevy_asset/src/asset_changed.rs [hunk 3]
```diff
@@ -235,7 +236,38 @@ unsafe impl<A: AsAssetId> WorldQuery for AssetChanged<A> {
...
+        assert!(
+            !combined_access.has_resource_write(state.resource_id),
+            "error[B0002]: AssetChanged<{}> in system {:?} conflicts with a previous system param. Consider removing the duplicate access. See: https://bevy.org/learn/errors/b0002",
+            DebugName::type_name::<A>(),
+            system_name,
+        );
+
+        let mut filter = FilteredAccess::default();
+        filter.add_component_read(state.resource_id);
+        filter.add_resource_read(state.resource_id);
```
Comment (andriyDev) [inline crates/bevy_asset/src/asset_changed.rs:259]: Why do we need both a component read and resource read?

Comment (Trashtalk217) [reply crates/bevy_asset/src/asset_changed.rs:259]: This ensures that this correctly conflicts with `FilteredResources`, which only uses resource accesses, and `Query<&mut MyResource>`, which only uses component accesses. This is fixed in #22910, which comes right after this PR.
