### PR TITLE
single `detect_text_needs_rerender` system

### LINKED ISSUE #19437: Text change detection discriminator bug
## Bevy version 

0.16

## What is wrong
The `detect_text_needs_rerender` use the `Text` and `Text2d` components to discriminate between UI and 2d root text nodes. But both query for all `TextSpan`s, this causes two problems:
* All `TextSpan`s are checked twice for changes.
* If there is an error with a `TextSpan`  `detect_text_needs_rerender::<Root>` reports the type of the current root discriminator:
```
            once!(warn!("found entity {} with a TextSpan that has a TextLayout, which should only be on root \
                text entities (that have {}); this warning only prints once",
                entity, core::any::type_name::<Root>()));
```
But since the system checks all `TextSpan`s for both roots the reported root `Text` or `Text2d` is determined by the system order, not the type of the root the `TextSpan` belongs to.

### PR DESCRIPTION
**Pull request by ickshonpe**
# Objective

`detect_text_needs_rerender` should only handle change detection for `TextSpan` entities.

Fixes #19437

## Solution

* Remove the generic type parameter from `detect_text_needs_rerender`. 
* Add `detect_text_needs_rerender` to `PostUpdate` in `TextPlugin`'s builder.
* Remove the scheduling of `detect_text_needs_rerender` from the `Text` and `Text2d` plugin builders.
* Check `Text` for changes in `measure_text` and `Text2d` for changes in `update_text2d_layout`.

This doesn't improve performance, the cost of doing the change detection in the text implementation specific systems balances out the savings by only runing `detect_text_needs_rerender` once. But combined with #23188, we should see a significant improvement.

## Testing

Text examples and tests still okay.

### CODE REVIEW

**Review by alice-i-cecile — APPROVED** [review]

File: crates/bevy_sprite/src/lib.rs [hunk 1]
```diff
@@ -87,14 +89,12 @@ impl Plugin for SpritePlugin {
         #[cfg(feature = "bevy_text")]
         app.add_systems(
             PostUpdate,
-            (
-                bevy_text::detect_text_needs_rerender::<Text2d>,
-                update_text2d_layout.after(bevy_camera::CameraUpdateSystems),
-            )
+            (update_text2d_layout.after(bevy_camera::CameraUpdateSystems),)
                 .chain()
+                .after(detect_text_needs_rerender)
```
Comment (kfc35) [inline crates/bevy_sprite/src/lib.rs:94]: A non blocking question:
Is this necessary to specify when `load_font_assets_into_font_collection` and `detect_text_needs_rerender` are already chained in `bevy_text`? Would it just suffice to have `after` `load_font_assets_into_font_collection` here? Just trying to understand the subtleties of the scheduling commands
