### PR TITLE
Fix system param validation for piped systems

### LINKED ISSUE #18755: `Single` causes piped systems to panic
## Bevy version

Bevy main (ce5a82b2bfc64d8ca9b75a44ea0153124f5120bf) which is around 0.16-rc.3 tag.

## What you did

I tried to run the following code:

```rust
use bevy::prelude::*;

#[derive(Component)]
struct Selected;

fn main() {
    App::new()
        .add_systems(Update, system_a.pipe(system_b))
        .run();
}

fn system_a() -> i32 {
    123
}

fn system_b(_: In<i32>, _: Single<Entity, With<Selected>>) {}
```

## What went wrong

This code panics due to `Single` not matching any entities in the piped system. This behavior differs from using `Single` in a regular system, where it will instead just skip system execution.

<details>
<summary>Panic Message</summary>

```
thread 'TaskPool (6)' panicked at ~/Projects/bevy/crates/bevy_ecs/src/system/system_param.rs:445:14:
The query was expected to contain exactly one matching entity.: NoEntities("bevy_ecs::system::query::Query<bevy_ecs::entity::Entity, bevy_ecs::query::filter::With<hello_world::Selected>>")
stack backtrace:
   0: rust_begin_unwind
             at /rustc/4eb161250e340c8f48f66e2b929ef4a5bed7c181/library/std/src/panicking.rs:692:5
   1: core::panicking::panic_fmt
             at /rustc/4eb161250e340c8f48f66e2b929ef4a5bed7c181/library/core/src/panicking.rs:75:14
   2: core::result::unwrap_failed
             at /rustc/4eb161250e340c8f48f66e2b929ef4a5bed7c181/library/core/src/result.rs:1704:5
   3: core::result::Result<T,E>::expect
             at ~/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/result.rs:1061:23
   4: <bevy_ecs::system::query::Single<D,F> as bevy_ecs::system::system_param::SystemParam>::get_param
             at ./crates/bevy_ecs/src/system/system_param.rs:443:22
   5: <(P,) as bevy_ecs::system::system_param::SystemParam>::get_param
             at ./crates/bevy_ecs/src/system/system_param.rs:2144:20
   6: <bevy_ecs::system::function_system::FunctionSystem<Marker,F> as bevy_ecs::system::system::System>::run_unsafe
             at ./crates/bevy_ecs/src/system/function_system.rs:734:22
   7: <bevy_ecs::system::combinator::PipeSystem<A,B> as bevy_ecs::system::system::System>::run_unsafe
             at ./crates/bevy_ecs/src/system/combinator.rs:407:9
   8: <bevy_ecs::system::schedule_system::InfallibleSystemWrapper<S> as bevy_ecs::system::system::System>::run_unsafe
             at ./crates/bevy_ecs/src/system/schedule_system.rs:64:9
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Encountered a panic in system `Pipe(hello_world::system_a, hello_world::system_b)`!
Encountered a panic in system `bevy_app::main_schedule::Main::run_main`!
```

</details>

### PR DESCRIPTION
**Pull request by alice-i-cecile**
# Objective

- Piped systems are an edge case that we missed when reworking system parameter validation.
- Fixes #18755.

## Solution

- Validate the parameters for both systems, ~~combining the errors if both failed validation~~ by simply using an early out.
- ~~Also fix the same bug for combinator systems while we're here.~~

## Testing

I've added a large number of tests checking the behavior under various permutations. These are separate tests, rather than one mega test because a) it's easier to track down bugs that way and b) many of these are `should_panic` tests, which will halt the evaluation of the rest of the test!

I've also added a test for exclusive systems being pipeable because we don't have one and I was very surprised that that works!

### CODE REVIEW

File: crates/bevy_ecs/src/system/combinator.rs [hunk 1]
```diff
@@ -421,8 +421,30 @@ where
...
+            (Err(err_a), Ok(_)) => Err(err_a),
+            (Err(err_a), Err(err_b)) => {
+                // Combine the errors from both systems, using the most severe outcome.
+                // TODO: consider combining the error strings in a more intelligible way
+                // but be mindful of the possibility of multiple piped systems!
+                Err(SystemParamValidationError {
+                    // Only skip if both systems should be skipped.
+                    // Panicking systems should not be skipped!
+                    skipped: err_a.skipped && err_b.skipped,
+                    message: err_a.message + err_b.message,
```
Comment (MrGVSV) [inline crates/bevy_ecs/src/system/combinator.rs:442]: Should we add a test to check the message is formatted legibly (i.e. no weird spacing issues)? Or is that juice not worth the squeeze?

File: crates/bevy_ecs/src/schedule/executor/mod.rs [hunk 2]
```diff
@@ -408,4 +411,161 @@ mod tests {
         schedule.add_systems(look_for_missing_resource);
         schedule.run(&mut world);
     }
+
+    #[test]
```
Comment (MrGVSV) [inline crates/bevy_ecs/src/schedule/executor/mod.rs:415]: I really like how you split up these tests btw!

File: crates/bevy_ecs/src/system/combinator.rs (hunk 1 above)
Comment (alice-i-cecile) [reply crates/bevy_ecs/src/system/combinator.rs:442]: Not worth the squeeze IMO: way too fragile. That said, I'll toss in some spaces, free of charge!

File: crates/bevy_ecs/src/system/combinator.rs [hunk 3]
```diff
@@ -421,8 +421,30 @@ where
...
+
+        // SAFETY: Delegate to the `System` implementation for `b`.
+        let b_validation = unsafe { self.b.validate_param_unsafe(world) };
+
+        match (a_validation, b_validation) {
+            (Ok(()), Ok(())) => Ok(()),
+            (Ok(_), Err(err_b)) => Err(err_b),
+            (Err(err_a), Ok(_)) => Err(err_a),
+            (Err(err_a), Err(err_b)) => {
+                // Combine the errors from both systems, using the most severe outcome.
```
Comment (chescock) [inline crates/bevy_ecs/src/system/combinator.rs:435]: We decided to short circuit for tuples, per https://github.com/bevyengine/bevy/pull/18504#discussion_r2011030275.  Why not short circuit here, as well?  That's a shorter implementation (using `?`), more consistent with multi-parameter systems, and doesn't allocate strings.

**Comment by chescock** [comment]
Won't doing eager validation like this re-introduce the issues from https://github.com/bevyengine/bevy/pull/16638#issuecomment-2526191119?  If a user pipes a system that inserts a resource into a system with `Res`, then that will succeed today but would fail under this change.  (And if they pipe a system that invalidates a `Single` into one that uses it, then the second system will fail instead of skipping, but that's no worse than now.)

**Comment by alice-i-cecile** [comment]
> Won't doing eager validation like this re-introduce the issues from https://github.com/bevyengine/bevy/pull/16638#issuecomment-2526191119? If a user pipes a system that inserts a resource into a system with Res, then that will succeed today but would fail under this change

I was going to say that this is quite unlikely, since all of our existing validated parameters requires structural changes to invalidate, but system piping doesn't work for exclusive systems. I wrote a test: turns out at some point that changed!

That said, I think this is a better tradeoff for now: piping exclusive systems or doing custom validated system params that are affected by an earlier system in the pipe feels quite rare. By contrast, the existing bug breaks a relatively common pattern (using validated params in a piped system) by changing the "everything is fine" behavior into a confusing panic.

**Review by MrGVSV — APPROVED** [review]
Not an ECS dev but the changes look good to me and has really solid tests.
