### PR TITLE
Normalization anchor for sprite slice in dimensions of this slice

### LINKED ISSUE #12408: Rotating a sliced sprite around off-center Anchor behaves erratic
## Bevy version
bevy main f0a98645d

## What you did

I rotated a sliced and custom sized sprite around an off-center anchor

## What went wrong

I expected the sprite to be correctly scaled and rotated, 
but the sliced parts leave gaps and do not seem to behave correctly. See the below screenshot:

image

## Additional information

I just modified the sprite_slice example, you can inspect [the changed example code in my fork](https://github.com/lennart/bevy/blob/bug/rotated-sliced-sprite/examples/2d/sprite_slice.rs#L89)

Am I misusing the TextureSlicer here? Should I actually be rotating something else, like a parent entity instead of the sliced sprite entity?

### LINKED ISSUE #12680: Sliced scaling does not play well with `Anchor`
## Bevy version

v0.13.1

## What you did

I was upgrading my RPG textboxes to use the new 9-slicing feature, but creating a sliced sprite with an anchor not set to `Anchor::Center` does not work right.

## What went wrong

Creating the textbox background with `Anchor::Center` works fine, and looks like this: 

image

Created with this code:

```rust
let sprite_child = commands
    .spawn(SpriteBundle {
        sprite: Sprite {
            custom_size: Some(vec2(296.5, 83.5)),
            ..default()
        },
        transform: Transform {
            translation: Vec3::new(0.0, -77.75, 4.9),
            rotation: Quat::IDENTITY,
            scale: Vec3::splat(1.0),
        },
        texture: asset_server.load("textbox.png"),
        ..default()
    })
    .insert(ImageScaleMode::Sliced(TextureSlicer {
        border: BorderRect::square(13.0),
        max_corner_scale: 1.0,
        ..default()
    }))
    .id();
```

Creating the textbox background with `Anchor::TopLeft` (with position adjusted correspondingly) does *not* work fine, and looks like this: 

image

Created with this code:
```rust
let sprite_child = commands
    .spawn(SpriteBundle {
        sprite: Sprite {
            anchor: Anchor::TopLeft,
            custom_size: Some(vec2(296.5, 83.5)),
            ..default()
        },
        transform: Transform {
            translation: Vec3::new(-148.25, -36.0, 4.9),
            rotation: Quat::IDENTITY,
            scale: Vec3::splat(1.0),
        },
        texture: asset_server.load("textbox.png"),
        ..default()
    })
    .insert(ImageScaleMode::Sliced(TextureSlicer {
        border: BorderRect::square(13.0),
        max_corner_scale: 1.0,
        ..default()
    }))
    .id();

```

## Additional information

My guess is that the anchor is being taken into consideration when scaling the center of the sliced texture, but not for the other parts.

### PR DESCRIPTION
**Pull request by bugsweeper**
# Objective

Fixes #12408 .
Fixes #12680.

## Solution

- Recaclulated anchor from dimensions of sprite to dimension of each part of it (each part contains its own anchor)

### CODE REVIEW

**Comment by james7132** [comment]
Have you tested if this fixes #12680 too?

**Comment by bugsweeper** [comment]
> Have you tested if this fixes #12680 too?

No, I didn't, but the problem looks the same. If issue author provides full example I can test it. Or author could test it from my repo or after PR merge

**Comment by james7132** [comment]
@Cyborus04 mind testing this change to see if #12680 is fixed for you?

File: crates/bevy_sprite/src/texture_slice/computed_slices.rs [hunk 1]
```diff
@@ -53,10 +53,21 @@ impl ComputedTextureSlices {
...
+                anchor: Self::redepend_anchor_from_sprite_to_slice(sprite, slice),
             }
         })
     }
+
+    fn redepend_anchor_from_sprite_to_slice(sprite: &Sprite, slice: &TextureSlice) -> Vec2 {
+        let sprite_size = sprite
+            .custom_size
+            .unwrap_or(sprite.rect.unwrap_or_default().size());
+        if sprite_size != Vec2::ZERO {
```
Comment (lennart) [inline crates/bevy_sprite/src/texture_slice/computed_slices.rs:65]: maybe flip the test around so that we don't have _yoda logic_, i.e. if the `sprite_size == Vec2::Zero` then anchor is unaltered, otherwise....

**Review by lennart — APPROVED** [review]
looks good to me, as far as I can see...

**Comment by bugsweeper** [comment]
@alice-i-cecile May I ask for a review?

**Review by alice-i-cecile — APPROVED** [review]
Looks good to me, although I'd be thrilled to see a few tests here to avoid regression.

**Comment by bugsweeper** [comment]
I don't know how to write such kind of test, because key moment of calculation is in bevy_sprite::render::prepare_sprites which runs at Render stage in RenderSet::PrepareBindGroups

**Comment by lennart** [comment]
I also was wondering how (and maybe to also clarify what) to test. Looking at the [existing tests for bevy_sprite](https://github.com/bevyengine/bevy/blob/5caf085dacf74bf553a0428a5eb7f4574a9bb99c/crates/bevy_sprite/src/lib.rs#L238) they test for the changed bounding box.

I was wondering if we could—building upon this test—ensure that the resulting bounding box of the rotated sliced sprite is _correct_. (I would assume the resulting bounding box, before this PR's fix, would be different). But this is just a guess...

The general idea for a test would be to not test the specific calculation of the anchors, but the result in form a correctly rotated sprite entity, no?

**Comment by bugsweeper** [comment]
Anchor breaked sprite slicing even with no rotation. I think correct test should check every slice of sprite for correct bounds, I mean there should be no gaps between them. So what should test do? Calculate all corners for every slice, and depending on uv coordinates match cases:

1. both u and v has integer values (0 or 1): that corner has same coords as one of corners of whole sprite (four cases of one sprite)
2. one of u or v has integer value: that corner is on whole sprite border, two sprite slices should contain corner with such coords (eight cases of one sprite)
3. both u or v are not integer value: that corner is inside of whole sprite, four sprite slices should contain corner with such coords (four cases of one sprite)
But i don't know how to run render stages (may be on mock render device) to get this slices in same way as in real applications.

**Comment by alice-i-cecile** [comment]
Merging as is; I can't immediately think of a clean testing strategy either. Thanks!
