### PR TITLE
Fix unbatchable meshes.

### LINKED ISSUE #18550: Some meshes not rendering in 0.16-rc.1
## Bevy version

0.16-rc.1

## \[Optional\] Relevant system information

Linux, wayland (sway) and maybe also xwayland, intel gpu
```ignore
2025-03-25T20:49:12.292198Z  INFO bevy_diagnostic::system_information_diagnostics_plugin::internal: SystemInfo { os: "Linux (Arch Linux rolling)", kernel: "6.13.8-arch1-1", cpu: "Intel(R) Core(TM) i7-8650U CPU @1.90GHz", core_count: "4", memory: "23.2 GiB" }
2025-03-25T20:49:12.634849Z  INFO bevy_render::renderer: AdapterInfo { name: "Intel(R) UHD Graphics 620 (KBL GT2)", vendor: 32902, device: 22807, device_type: IntegratedGpu, driver: "Intel open-source Mesa driver", driver_info: "Mesa 25.0.2-arch1.2", backend: Vulkan }
```

## What you did

Updated to 0.16

## What went wrong

After updating to 0.16 some meshes from gltf models began to intermittently appear and disappear. I also saw some other glitches (#18542 ) which may or may not have the same root cause. In my full game the flickering meshes seem to respond to camera motion. They will be present when the camera is in one position and absent in another. Changing window size also seems to trigger the flicker. In the attached minimal example there is no camera motion but the missing meshes are repeatably missing. In my full game I have seen this issue when running directly on wayland and also under xwayland but in the minimal example I have only gotten it to reproduce when running directly in wayland.

## Additional information

Image

This screenshot demonstrates the issue. All the eyes are the same gltf model, the only difference is the x-y coordinates they were spawned at. There is a clear pattern in which ones are missing the eyelids and which ones aren't which wasn't noticable in the program this was extracted from, likely because things in that version are spawned in a more or less random order.

A minimal example that reproduces the issue for me when run on wayland is attached.

[example.zip](https://github.com/user-attachments/files/19456911/example.zip)

### PR DESCRIPTION
**Pull request by tychedelia**
# Objective

Fixes #18550.

Because bin state for unbatchable meshes wasn't being cleared each frame, the buffer indices for unbatchable meshes would demote from sparse to dense storage and aggressively leak memory, with all kinds of weird consequences downstream, namely supplying invalid instance ranges for render.

## Solution

Clear out the unbatchable mesh bin state when we start a new frame.

### CODE REVIEW

**Comment by greeble-dev** [comment]
I'm not confident enough to review the code, but can confirm this fixes the stress in #18536 breaking when meshes are frustum culled (Win10/Vulkan/Nvidia).

**Comment by mockersf** [comment]
I've pushed this fix to a branch on top of the 0.16.0-rc.3 if anyone want to test it before merging: https://github.com/mockersf/bevy/tree/16.0-rc.3-with-18761

**Review by mockersf — APPROVED** [review]

**Comment by extrawurst** [comment]
Tested against my issue in #18736 and happy to report this is fixing it even with the gltf using shape-keys! Thank you so much!

**Review by JMS55 — APPROVED** [review]
Not really familiar with the code, but it looks fine and was shown to fix the problem.

File: crates/bevy_render/src/render_phase/mod.rs [hunk 1]
```diff
@@ -1325,6 +1330,10 @@ impl UnbatchableBinnedEntityIndexSet {
                 // but let's go ahead and do the sensible thing anyhow: demote
                 // the compressed `NoDynamicOffsets` field to the full
                 // `DynamicOffsets` array.
+                warn!(
```
Comment (pcwalton) [inline crates/bevy_render/src/render_phase/mod.rs:1333]: I'd just make this an `error!`

**Review by pcwalton — APPROVED** [review]
Thanks for the fix. The sparse/dense stuff is some of my least favorite parts of the renderer and can be removed once we drop WebGL 2.
