### PR TITLE
Re-add `Out` to `ExtractComponent`

### LINKED ISSUE #22863: Removing component from main world doesn't remove all related components from render world
## Bevy version and features

- `main` since https://github.com/bevyengine/bevy/commit/bbcc1e660110e0f0adb1c580b396cd1cccace7aa

## What you did

Tried running the OIT example and toggling OIT off

## What went wrong

WGPU validation errors

## Additional information

https://github.com/bevyengine/bevy/commit/bbcc1e660110e0f0adb1c580b396cd1cccace7aa changed the logic in `SyncComponentPlugin` and `entity_sync_system` so that it no longer despawns and respawns the corresponding render world entity when a component is removed from the main world entity, and instead only removes the components specified in `SyncComponent::Out`. This means some components added elsewhere might remain and systems that assume those components always exist together will break.

For example if you remove `OrderIndependentTransparancySettings`, the extracted camera entity still has `OitResolvePipelineId` and `OrderIndependentTransparencySettingsOffset` (these were added by calling `EntityCommands::insert`), which means `oit_resolve` still tries to run the OIT resolve pass and the `SetMeshViewBindGroup` render command adds a dynamic offset that does not match the bind group layout since it thinks OIT is still being used.

In the OIT case those two functions could be changed to check `Has<OrderIndependentTransparancySettings>` and it would work again, but I think there may be many other other cases where render world logic assumes certain components exist together without checking because that was fine before.

### LINKED ISSUE #22999: A crash occurs when removing `ScreenSpaceReflections` in the `ssr` example.
## Bevy version and features

- main branch

## \[Optional\] Relevant system information

- the Rust version you're using
  - rustc 1.92.0 (ded5c06cf 2025-12-08)
- the operating system or browser used, including its version
  - Windows 11 Home, kernel: "22631"
 
```ignore
`2026-02-17T09:12:51.340485Z  INFO bevy_render::renderer: AdapterInfo { name: "NVIDIA GeForce RTX 4060 Laptop GPU", vendor: 4318, device: 10400, device_type: DiscreteGpu, device_pci_bus_id: "0000:01:00.0", driver: "NVIDIA", driver_info: "591.74", backend: Vulkan, subgroup_min_size: 32, subgroup_max_size: 32, transient_saves_memory: false }`
```

## What you did

I encountered a crash in the ‘ssr’ example when I tried to disable the SSR effect.

## What went wrong

``` 
2026-02-17T10:20:50.655628Z  INFO bevy_render::renderer: AdapterInfo { name: "NVIDIA GeForce RTX 4060 Laptop GPU", vendor: 4318, device: 10400, device_type: DiscreteGpu, device_pci_bus_id: "0000:01:00.0", driver: "NVIDIA", driver_info: "591.74", backend: Vulkan, subgroup_min_size: 32, subgroup_max_size: 32, transient_saves_memory: false }
2026-02-17T10:20:51.893735Z  INFO bevy_render::batching::gpu_preprocessing: GPU preprocessing is fully supported on this device.
2026-02-17T10:20:51.902804Z  INFO bevy_winit::system: Creating new window Bevy Screen Space Reflections Example (65v0)
2026-02-17T10:20:52.291256Z  WARN bevy_pbr::render::mesh_view_bindings: Too many textures in mesh pipeline view layout, this might cause us to hit `wgpu::Limits::max_sampled_textures_per_shader_stage` in some environments.
2026-02-17T10:21:00.939648Z ERROR bevy_render::error_handler: Caught DeviceLost error: Unknown Unexpected error variant (driver implementation is at fault)

thread 'Compute Task Pool (4)' (16776) panicked at crates\bevy_render\src\view\window\mod.rs:309:17:
Couldn't get swap chain texture, operation unrecoverable: Acquiring a texture failed with a generic error. Check error callbacks for more information
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Encountered a panic in system `<Enable the debug feature to see the name>`!

thread 'Compute Task Pool (4)' (16776) panicked at D:\CodeGroup\bevy\crates\bevy_render\src\render_resource\uniform_buffer.rs:312:18:
called `Option::unwrap()` on a `None` value

thread 'Compute Task Pool (2)' (5600) panicked at D:\CodeGroup\bevy\crates\bevy_render\src\render_resource\uniform_buffer.rs:312:18:
called `Option::unwrap()` on a `None` value
Encountered a panic in system `
thread 'main' (14264) panicked at crates\bevy_render\src\render_resource\uniform_buffer.rs:312:18:
called `Option::unwrap()` on a `None` value

thread 'Compute Task Pool (3)' (15544) panicked at C:\Users\genCode\.cargo\registry\src\index.crates.io-1949cf8c6b5b557f\wgpu-28.0.0\src\backend\wgpu_core.rs:2231:18:
Error in Buffer::get_mapped_range: Validation Error

Caused by:
  Buffer with 'thickness_buffer' label is invalid


thread 'Compute Task Pool (0)' (29512) panicked at C:\Users\genCode\.cargo\registry\src\index.crates.io-1949cf8c6b5b557f\wgpu-28.0.0\src\backend\wgpu_core.rs:2231:18:
Error in Buffer::get_mapped_range: Validation Error

Caused by:
  Buffer with '' label is invalid

<Enable the debug feature to see the name>
thread 'Compute Task Pool (5)' (22152) panicked at D:\CodeGroup\bevy\crates\bevy_render\src\render_resource\uniform_buffer.rs:312:18:
called `Option::unwrap()` on a `None` value
`!

thread 'Compute Task Pool (1)' (10512) panicked at D:\CodeGroup\bevy\crates\bevy_render\src\render_resource\uniform_buffer.rs:312:18:
called `Option::unwrap()` on a `None` value
Encountered a panic in system `
thread 'Compute Task Pool (4)' (16776) panicked at D:\CodeGroup\bevy\crates\bevy_render\src\render_resource\uniform_buffer.rs:312:18:
called `Option::unwrap()` on a `None` value
<Enable the debug feature to see the name>`!
Encountered a panic in system `<Enable the debug feature to see the name>`!
Encountered a panic in system `
thread 'main' (14264) panicked at D:\CodeGroup\bevy\crates\bevy_render\src\render_resource\uniform_buffer.rs:312:18:
called `Option::unwrap()` on a `None` value
<Enable the debug feature to see the name>
thread 'Compute Task Pool (2)' (5600) panicked at D:\CodeGroup\bevy\crates\bevy_render\src\render_resource\uniform_buffer.rs:312:18:
called `Option::unwrap()` on a `None` value
`!
Encountered a panic in system `<Enable the debug feature to see the name>`!
Encountered a panic in system `<Enable the debug feature to see the name>`!
Encountered a panic in system `<Enable the debug feature to see the name>`!
Encountered a panic in system `<Enable the debug feature to see the name>`!
Encountered a panic in system `<Enable the debug feature to see the name>`!
Encountered a panic in system `<Enable the debug feature to see the name>`!
Encountered a panic in system `<Enable the debug feature to see the name>`!
error: process didn't exit successfully: `target\debug\examples\ssr.exe` (exit code: 2173)
```

## Additional information

Relevant Code:
```rust
for camera in cameras.iter_mut() {
    if app_settings.ssr_on {
        commands.entity(camera).insert(ScreenSpaceReflections {
            min_perceptual_roughness: app_settings.min_perceptual_roughness.clone(),
            max_perceptual_roughness: app_settings.max_perceptual_roughness.clone(),
            edge_fadeout: app_settings.edge_fadeout.clone(),
            ..default()
        });
    } else {
        commands.entity(camera).remove::<ScreenSpaceReflections>();
    }
}
```

I wonder if this issue is specific to my machine.

### LINKED ISSUE #23142: Bloom + transmission bug
## Bevy version and features

- Latest main

## What you did

`cargo run --example transmission` then press H

## What went wrong

Validation error + stops rendering and screen goes magenta after a while on mac

## Additional information

```
2026-02-23T21:41:05.225615Z ERROR queue_submit{count=12}: bevy_render::error_handler: Caught rendering error: Validation Error

Caused by:
  In Queue::submit
    In a set_pipeline command
      Render pipeline targets are incompatible with render pass
        Incompatible color attachments at indices [0]: the RenderPass uses textures with formats [Some(Rgba8UnormSrgb)] but the RenderPipeline with 'bloom_upsampling_pipeline' label uses attachments with formats [Some(Rgba16Float)]
```

### PR DESCRIPTION
**Pull request by beicause**
# Objective

Fixes #22863. Fixes #22999. Fixes #23142.

## Solution

1. Re-add `Out` type to `ExtractComponent`. Rename `SyncComponent::Out` to `SyncComponent::Target`, which is used to clean up components when removing, so that the output of extraction can be different from `SyncComponent::Target`.
2. Add `#[extract_component_sync_target]` attribute for `#[derive(ExtractComponent)]` to specify `SyncComponent::Target`.

## Testing

Tested `ssr` and `order_independent_transparency` examples.
There may be other places where derived components need to be cleaned up, but finding them is somewhat challenging.

### CODE REVIEW

File: crates/bevy_render/src/extract_component.rs [hunk 1]
```diff
@@ -46,8 +47,13 @@ pub trait ExtractComponent<F = ()>: SyncComponent<F> {
     type QueryData: ReadOnlyQueryData;
     /// Filters the entities with additional constraints.
     type QueryFilter: QueryFilter;
+    /// The output from extraction.
```
Comment (alice-i-cecile) [inline crates/bevy_render/src/extract_component.rs]: Can we beef up these docs here? It's not clear from reading this exactly what this type does and why it's needed.

Comment (beicause) [reply crates/bevy_render/src/extract_component.rs]: It's the output of `extract_component`, which can be different from the components cleaned by `SyncComponent`.

**Comment by beicause** [comment]
Also fixed #23142 by removing both `Bloom` and `Hdr` components in `transmission` example.

But there is still an issue with `ExtractComponent::QueryFilter`: if an entity's component is extracted and then filtered out by `ExtractComponent::QueryFilter` in the next frame (e.g. `Hdr` is removed or `Camera` is removed), the extracted components cannot be cleared.

**Comment by Zeophlite** [comment]
> Also this will massively collide with #22852. We should make a decision about which one we want merged first.

Definitely this one should merge first

File: examples/3d/transmission.rs [hunk 2]
```diff
@@ -461,9 +461,11 @@ fn example_control_system(
 
     if input.just_pressed(KeyCode::KeyH) {
         if hdr {
-            commands.entity(camera_entity).remove::<Hdr>();
+            commands.entity(camera_entity).remove::<(Bloom, Hdr)>();
```
Comment (atlv24) [inline examples/3d/transmission.rs]: If I understand correctly, this does mean that the Out change doesn't really fix this issue. I'm in favor of this PR as a whole, but this is kinda papering over this specific problem imo. This is caused by required components, right?

Comment (beicause) [reply examples/3d/transmission.rs]: I think this issue is actually related to QueryFilter, not required component.

Bloom will be filtered out and not extracted if Hdr is removed, but the extracted BloomUniforms will still exist. The same applies to other ExtractComponents that use QueryFilter.

**Comment by atlv24** [comment]
Can you also update the migration guide that removed Out this cycle so that we're not claiming it was removed when we actually added it back please?

**Review by alice-i-cecile — APPROVED** [review]
