### PR TITLE
bevy_reflect: Fix ignored/skipped field order

### LINKED ISSUE #5101: bevy_reflect: ignored fields are not ignored by `FromReflect`
**bevy version**:  main as of 1bd33ca

When deriving `FromReflect` on tuple structs, the field index of fields declared after a field marked with `#[reflect(ignore)]` are not as one would expect them.

Here is an example:
```rust
#[derive(Reflect, FromReflect)]
struct Foo(
  u32, // :0
  #[reflect(ignore)]
  f32, // :1
  String, // :2
);

let mut tuple_struct = DynamicTupleStruct::default();
tuple_struct.set_name("Foo".to_owned());
tuple_struct.insert(22_u32);
tuple_struct.insert(3432423234234_i128);
tuple_struct.insert("hello world".to_owned());

let foo = Foo::from_reflect(&tuple_struct).unwrap();

println!(
    "tuple_struct\n[0]: {:?}\n[1]: {:?}\n[2]: {:?}\n",
    tuple_struct.field(0),
    tuple_struct.field(1),
    tuple_struct.field(2),
);
println!(
    "foo\n[0]: {:?}\n[1]: {:?}\n[2]: {:?}\n",
    foo.field(0),
    foo.field(1),
    foo.field(2).
);
```

Prints the following:
```
tuple_struct
[0]: Some(22)
[1]: Some(3432423234234)
[2]: Some("hello world")

foo
[0]: Some(22)
[1]: Some("hello world")
[2]: None
```

The unexpected behavior is here:
```rust
let mut tuple_struct = DynamicTupleStruct::default();
tuple_struct.set_name("Foo".to_owned());
tuple_struct.insert(22_u32);
// vvv required, otherwise Foo::from_reflect returns None
tuple_struct.insert(3432423234234_i128);
tuple_struct.insert("hello world".to_owned());

let foo = Foo::from_reflect(&tuple_struct).unwrap();
```

You'd expect to be able to build `Foo` from a `DynamicTupleStruct` with exactly **two** fields, not three. The correct behavior would be to account for it in the `FromReflect` implementation.

### PR DESCRIPTION
**Pull request by MrGVSV**
# Objective

Fixes #5101
Alternative to #6511

## Solution

Corrected the behavior for ignored fields in `FromReflect`, which was previously using the incorrect field indexes.

Similarly, fields marked with `#[reflect(skip_serializing)]` no longer break when using `FromReflect` after deserialization. This was done by modifying `SerializationData` to store a function pointer that can later be used to generate a default instance of the skipped field during deserialization.

The function pointer points to a function generated by the derive macro using the behavior designated by `#[reflect(default)]` (or just `Default` if none provided). The entire output of the macro is now wrapped in an [unnamed constant](https://doc.rust-lang.org/stable/reference/items/constant-items.html#unnamed-constant) which keeps this behavior hygienic.

#### Rationale

The biggest downside to this approach is that it requires fields marked `#[reflect(skip_serializing)]` to provide the ability to create a default instance— either via a `Default` impl or by specifying a custom one. While this isn't great, I think it might be justified by the fact that we really need to create this value when using `FromReflect` on a deserialized object. And we need to do this _during_ deserialization because after that (at least for tuples and tuple structs) we lose information about which field is which: _"is the value at index 1 in this `DynamicTupleStruct` the actual value for index 1 or is it really the value for index 2 since index 1 is skippable...?"_

#### Alternatives

An alternative would be to store `Option<Box<dyn Reflect>>` within `DynamicTuple` and `DynamicTupleStruct` instead of just `Box<dyn Reflect>`. This would allow us to insert "empty"/"missing" fields during deserialization, thus saving the positional information of the skipped fields. However, this may require changing the API of `Tuple` and `TupleStruct` such that they can account for their dynamic counterparts returning `None` for a skipped field. In practice this would probably mean exposing the `Option`-ness of the dynamics onto implementors via methods like `Tuple::drain` or `TupleStruct::field`.

Personally, I think requiring `Default` would be better than muddying up the API to account for these special cases. But I'm open to trying out this other approach if the community feels that it's better.

---

#### Fixed

- The behaviors of `#[reflect(ignore)]` and `#[reflect(skip_serializing)]` are no longer dependent on field order

#### Changed

- Fields marked with `#[reflect(skip_serializing)]` now need to either implement `Default` or specify a custom default function using `#[reflect(default = "path::to::some_func")]`
- Deserializing a type with fields marked `#[reflect(skip_serializing)]` will now include that field initialized to its specified default value
- `SerializationData::new` now takes the new `SkippedField` struct along with the skipped field index
- Renamed `SerializationData::is_ignored_field` to `SerializationData::is_field_skipped`

#### Added

- Added `SkippedField` struct
- Added methods `SerializationData::generate_default` and `SerializationData::iter_skipped`

#### Changed

- Replaced `members_to_serialization_denylist` and `BitSet<u32>` with `SerializationDataDef`
- The `Reflect` derive is more hygienic as it now outputs within an [unnamed constant](https://doc.rust-lang.org/stable/reference/items/constant-items.html#unnamed-constant)
- `StructField::index` has been split up into `StructField::declaration_index` and `StructField::reflection_index`

#### Removed

- Removed `bitset` dependency

## Migration Guide

* Fields marked `#[reflect(skip_serializing)]` now must implement `Default` or specify a custom default function with `#[reflect(default = "path::to::some_func")]`
    ```rust
    #[derive(Reflect)]
    struct MyStruct {
      #[reflect(skip_serializing)]
      #[reflect(default = "get_foo_default")]
      foo: Foo, // <- `Foo` does not impl `Default` so requires a custom function
      #[reflect(skip_serializing)]
      bar: Bar, // <- `Bar` impls `Default`
    }
    
    #[derive(Reflect)]
    struct Foo(i32);
    
    #[derive(Reflect, Default)]
    struct Bar(i32);
    
    fn get_foo_default() -> Foo {
      Foo(123)
    }
    ```
* `SerializationData::new` has been changed to expect an iterator of `(usize, SkippedField)` rather than one of just `usize`
    ```rust
    // BEFORE
    SerializationData::new([0, 3].into_iter());
    
    // AFTER
    SerializationData::new([
      (0, SkippedField::new(field_0_default_fn)),
      (3, SkippedField::new(field_3_default_fn)),
    ].into_iter());
    ```
* `Serialization::is_ignored_field` has been renamed to `Serialization::is_field_skipped`
* Fields marked `#[reflect(skip_serializing)]` are now included in deserialization output. This may affect logic that expected those fields to be absent.

### CODE REVIEW

**Comment by MrGVSV** [comment]
Rebased. Not sure about the `check-bans` failure, but this should be ready for review again!

**Comment by mockersf** [comment]
> Not sure about the check-bans failure

You can ignore it, Bevy is a little late in a few dependencies and the config file should be updated after more crates are up-to-date.

> Similarly, fields marked with #[reflect(skip_serializing)] no longer break when using FromReflect after deserialization. This was done by modifying SerializationData to store a function pointer that can later be used to generate a default instance of the skipped field during deserialization.

I disagree that `skip_serializing` should impact deserialization. serve has `skip`, `skip_serializing` and `skip_deserializing`. Deserializing should require the field even if it's marked as `skip_serializing`, to make it use a default value it should be marked as `skip_deserializing` too. If we want to indicate both, I think we should use a different name for that attribute.

**Comment by MrGVSV** [comment]
> > Similarly, fields marked with #[reflect(skip_serializing)] no longer break when using FromReflect after deserialization. This was done by modifying SerializationData to store a function pointer that can later be used to generate a default instance of the skipped field during deserialization.
> 
> I disagree that `skip_serializing` should impact deserialization. serde has `skip`, `skip_serializing` and `skip_deserializing`. Deserializing should require the field even if it's marked as `skip_serializing`, to make it use a default value it should be marked as `skip_deserializing` too. If we want to indicate both, I think we should use a different name for that attribute.

Yeah that makes sense and would again be further aligned with `serde` so users have an easier time making the switch or at least conceptualizing the similarities.

That being said, I think it should be considered out of scope for this PR. This fixes a pretty longstanding and annoying bug, and shouldn't be blocked by the naming of the attribute used. We can probably create a separate ticket for that.

In fact, maybe I can work on splitting up the attributes while this PR gets reviewed so that we can hopefully be able to merge that change pretty soon before/after this one.

**Comment by cart** [comment]
Moving this to 0.12 as we didn't get it reviewed in time.

**Comment by MrGVSV** [comment]
I've removed the `AssociatedData` stuff. While that may be useful in the future, it wasn't really needed for this PR. I think when I originally wrote this, I was unaware that a non-capturing closure can also satisfy the function pointer type 😅.

File: crates/bevy_reflect/bevy_reflect_derive/src/serialization.rs [hunk 1]
```diff
@@ -0,0 +1,85 @@
...
+/// Collected field data used to generate a `SkippedField` type.
+pub(crate) struct SkippedFieldDef {
+    /// The default function for this field.
+    ///
+    /// This is of type `fn() -> Box<dyn Reflect>`.
+    default_fn: proc_macro2::TokenStream,
+}
+
+impl SkippedFieldDef {
+    pub fn new(field: &StructField<'_>) -> Result<Self, syn::Error> {
```
Comment (soqb) [inline crates/bevy_reflect/bevy_reflect_derive/src/serialization.rs:77]: considering this is the only constructor, does this respect `#[reflect(default = "my_func")]`?

it might be helpful to add something to the test [here](https://github.com/bevyengine/bevy/blob/d8edc81ac9b1c2011e6a9b64ca7c58d7f9f26412/crates/bevy_reflect/src/lib.rs#L803C1-L803C1).

File: crates/bevy_reflect/src/tuple_struct.rs [hunk 2]
```diff
@@ -398,6 +399,15 @@ impl Debug for DynamicTupleStruct {
...
 
+impl From<DynamicTuple> for DynamicTupleStruct {
+    fn from(value: DynamicTuple) -> Self {
+        Self {
+            represented_type: None,
+            fields: Box::new(value).drain(),
+        }
+    }
+}
+
```
Comment (soqb) [inline crates/bevy_reflect/src/tuple_struct.rs:410]: yet another place where we might be better off merging `Tuple` and `TupleStruct` :thinking:

File: crates/bevy_reflect/bevy_reflect_derive/src/lib.rs [hunk 3]
```diff
@@ -201,8 +202,10 @@ pub fn derive_reflect(input: TokenStream) -> TokenStream {
     };
 
     TokenStream::from(quote! {
-        #reflect_impls
-        #from_reflect_impl
+        const _: () = {
+            #reflect_impls
+            #from_reflect_impl
+        };
```
Comment (soqb) [inline crates/bevy_reflect/bevy_reflect_derive/src/lib.rs:208]: should we apply this treatment to all the macros defined in this file?

**Review by soqb — APPROVED** [review]
overall looks like excellent improvement; a couple nits and one question for correctness.

**Review by alice-i-cecile — APPROVED** [review]
Thorough and well-tested, fixes an important bug. Code is clear and well-documented, as always <3

File: crates/bevy_reflect/bevy_reflect_derive/src/serialization.rs (hunk 1 above)
Comment (MrGVSV) [reply crates/bevy_reflect/bevy_reflect_derive/src/serialization.rs:77]: I'm testing this now and it looks like I forgot to account for this (or at least broke it during a rebase). Nice catch, I'll update!

File: crates/bevy_reflect/bevy_reflect_derive/src/lib.rs (hunk 3 above)
Comment (MrGVSV) [reply crates/bevy_reflect/bevy_reflect_derive/src/lib.rs:208]: Fair, I'll add it!

File: crates/bevy_reflect/src/tuple_struct.rs (hunk 2 above)
Comment (MrGVSV) [reply crates/bevy_reflect/src/tuple_struct.rs:401]: Personally, I still think we should keep the concepts separate, both for user clarity and the potential to allow their definitions to diverge as needed. If anything, we might try to reduce some code duplication by making better use of macro_rules.

**Comment by alice-i-cecile** [comment]
@MrGVSV, are you ready for this to be merged now?

**Comment by MrGVSV** [comment]
> @MrGVSV, are you ready for this to be merged now?

@alice-i-cecile should be good to go!
