### PR TITLE
Fix gizmos in WebGPU

### LINKED ISSUE #8908: 2d_gizmos and 3d_gizmos are broke in WebGPU
## Bevy version

main 910f984709fb58cddbb7393c948634a2540e8d72

## Relevant system information
cargo 1.70.0 (ec8a8a0ca 2023-04-25)

SystemInfo { os: "MacOS 13.4 ", kernel: "22.5.0", cpu: "Apple M1", core_count: "8", memory: "8.0 GiB" }
AdapterInfo { name: "", vendor: 0, device: 0, device_type: Other, driver: "", driver_info: "", backend: BrowserWebGpu }

Chrome: Version 114.0.5735.133 (Official Build) (arm64)

## What you did

I run the examples 2d_gizmos and 3d_gizmos with WebGPU in Chrome
## What went wrong

The example don't show, only a black screen
Screenshot 2023-06-20 at 19 42 50

## Additional information

```
127.0.0.1/:1 Attribute offset (12) with format VertexFormat::Float32x3 (size: 12) doesn't fit in the vertex buffer stride (12).
 - While validating attributes[1].
 - While validating buffers[0].
 - While validating vertex state.
 - While calling [Device].CreateRenderPipeline([RenderPipelineDescriptor "LineGizmo Pipeline 2D"]).
 ```

```
[Invalid RenderPipeline "LineGizmo Pipeline 2D"] is invalid.
 - While encoding [RenderPassEncoder "main_pass_2d"].SetPipeline([Invalid RenderPipeline "LineGizmo Pipeline 2D"]).
```

```
[Invalid RenderPipeline "LineGizmo Pipeline"] is invalid.
 - While encoding [RenderPassEncoder "main_transparent_pass_3d"].SetPipeline([Invalid RenderPipeline "LineGizmo Pipeline"]).
 ```

### PR DESCRIPTION
**Pull request by devil-ira**
# Objective

Fix #8908.

## Solution

Assign the vertex buffers twice with a single item offset instead of setting the array_stride lower than the vertex layout's size for linestrips.

### CODE REVIEW

File: crates/bevy_gizmos/src/lib.rs [hunk 1]
```diff
@@ -468,42 +478,84 @@ impl<P: PhaseItem> RenderCommand<P> for DrawLineGizmo {
...
-        // Positions
-        VertexBufferLayout {
-            array_stride: Float32x3.size() * stride_multiplier,
-            step_mode: VertexStepMode::Instance,
-            attributes: vec![
-                VertexAttribute {
+    if strip {
+        vec![
+            // Positions
+            VertexBufferLayout {
```
Comment (IceSentry) [inline crates/bevy_gizmos/src/lib.rs:485]: I'd suggest extracting those to a variable to not repeat it. Alternatively you could create the vec with only 2 elements and  use insert to add the padding

File: crates/bevy_gizmos/src/lib.rs [hunk 2]
```diff
@@ -468,42 +478,55 @@ impl<P: PhaseItem> RenderCommand<P> for DrawLineGizmo {
...
+                position_layout
+            },
+            color_layout.clone(),
+            {
+                color_layout.attributes[0].shader_location = 3;
+                color_layout
+            },
+        ]
+    } else {
+        position_layout.array_stride *= 2;
```
Comment (IceSentry) [inline crates/bevy_gizmos/src/lib.rs:516]: I didn't even realize this was different. Now it's way more obvious 😆

**Review by IceSentry — APPROVED** [review]
LGTM

**Review by mockersf — APPROVED** [review]
works for me in webgpu, webgl2 and native
