### PR TITLE
Flush commands after every mutation in `WorldEntityMut`

### LINKED ISSUE #14621: `Commands` apply at unexpected times with exclusive `World` access
## Bevy version

`0.14.0` and `main` (c1c003d3c7c0d12dcd1af09fb57a246e1b401a10)

## What you did

`world.commands().add(...)` from within another command. Take the following example:

```rust
let mut world = World::new();

let mut cmd = world.commands();

// Command 1
cmd.add(|world: &mut World| {
    let entity_1 = world.spawn_empty().id();

    println!("A");

    // Command 3
    world.commands().add(|world: &mut World| {
        println!("BUZZ!");
    });

    println!("B");

    world.entity_mut(entity_1).insert(A);

    let a = world.get::<A>(entity_1);

    println!("C");

    world.spawn(A);

    println!("D");

    world.flush();

    println!("E");
});

// Command 2
cmd.add(|_: &mut World| {
    println!("F");
});

world.flush();
```

When does `BUZZ!` get printed?

## What went wrong

It ends up being in the place I would *least* expect, which is why I'm calling this a bug rather than simply lacking documentation.

Loosely ordered by where I would expect it to occur:

* After F? If the `&mut World` passed to each command is the same world as the outermost, then I would expect `world.commands()` to always refer to the same queue, so Command 1 is added, Command 2 is added, Command 1 runs, it pushes Command 3 into the queue, Command 2 runs, Command 3 runs.
* After D or E? If each command gets a new "nested" queue that's flushed after it finishes, then it would happen between Command 1 and Command 2. But we're also calling `world.flush()`, and the docs for `world.commands()` says they'll run after a call to `World::flush`. So it should be after D.
* After A? We have exclusive `World` access, so `Commands` are a bit redundant. If we ignore the bit about `World::flush` in the `World::commands` docs, then maybe we'll guess that they simply execute immediately, and `World::commands` is just for convenience when you have something that accepts a `Commands` argument. Or maybe they flush when the `Commands` is immediately dropped after our `add`?
* After B? Maybe there's an implicit `World::flush` any time we actually mutate the world or when we read the result of a mutation.
* After C? If it's none of the above, this is the only option left, apart from "never".

And the winner is... after C! It comes down to `World::flush` being implicit in some methods, but not others. There isn't any mention of this in any of their docs. Even if it was called out explicitly in the docs for each method if it does a flush, I wouldn't want to have to keep that context in my head when reasoning about when a command will run. 

To me, the only three possibilities for when a command should run given exclusive world access are:
1. At the end of the outermost command queue
2. Immediately after the parent command
3. Immediately after being added, or at least before any other world access. No explicit flushing or "will they/won't they" implicit flushing.

## Additional information

This comes out of my attempts to get lifecycle `Observer`s to behave the way I want, and they make things even harder to reason about. Specifically, the `OnAdd` trigger will occur immediately upon component addition, but if you add commands to the queue in the trigger, they'll be executed whenever the command that did the component addition does a flush, which can be wildly unpredictable. For example, what if the command pre-spawns a bunch of entities, then adds components? Your observer's commands will run at the end of that command after *all* components have been added. What if instead, it interleaves entity spawning and component adding? Then you'll get a flush before each new entity, and your observer's commands will occur midway through the command that triggered it.

### LINKED ISSUE #16034: Commands queued by component hooks are not applied during exclusive world access
# Problem

When an entity is spawned (or other structural changes occur) as part of exclusive world access, commands to apply changes via hooks are generated, but are not immediately applied.

In order to apply these commands, we must call `world.flush`, as demonstrated [here](https://github.com/Leafwing-Studios/i-cant-believe-its-not-bsn/blob/8e5783dd164f99960f6c33cc3f83b99174c84ce2/src/maybe.rs#L150).

This allows users to accidentally observe the state of the world *before* component lifecycle hooks are applied, but *only* when working with exclusive world access. As a result, we must be extremely careful if we are relying on hooks for soundness.

## Bevy version

0.14.1

## Additional context

This is related to #14621, but is intended as a clearer demonstration of a specific problem.

#12235 may end up being blocked on this, as otherwise we could get UB by calling unsafe code on an invalid entity hierarchy.

### LINKED ISSUE #16212: `observe` on `WorldEntityMut` may cause the reference to be invalidated
## Bevy version

0.15.0-rc.2 (present in 0.14.0) as well

## What you did

```rust
    #[derive(Event)]
    struct Boom;

    #[derive(Event)]
    struct BoomTomorrow;

    fn boom(trigger: Trigger<Boom>, mut commands: Commands) {
        println!("boom, despawning entity: {:?}", trigger.entity());
        commands.entity(trigger.entity()).despawn();
    }

    fn boom_tomorrow(trigger: Trigger<Boom>, mut commands: Commands) {
        // boom tomorrow
    }

    #[test]
    fn test_boom() {
        let mut app = App::new();

        let mut id = app.world_mut().spawn(Name::new("a")).observe(boom).id();
        let mut id2 = app.world_mut().spawn(Name::new("b")).id();
        
        app.world_mut().flush();
        println!("flushed");
        
        let mut a = app.world_mut().entity_mut(id);
        a.trigger(Boom);
        a.observe(boom_tomorrow);
        let name = a.get::<Name>().unwrap();
        assert_eq!(name.as_str(), "b");
    }
```

Result

```
test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 2 filtered out; finished in 0.00s
```

## What went wrong
 
- `WorldEntityMut` depends on the fact that the `EntityLocation` it caches does not change while it is alive, or changes when it itself expects it to.
- This means that there must be no way to flush the command queue while `WorldEntityMut` lives, as this might cause queued despawns to be run. 
- `observe` internally calls `world.spawn()`.
- `world.spawn()` implicitly has a `flush()` in it, as evidenced in bug report #14621.
- Hence, entity gets despawned while `WorldEntityMut` exists, which means any accesses will use outdated `EntityLocation`

## Additional information

Also related as context #16034.

### PR DESCRIPTION
**Pull request by nakedible**
# Objective

- Currently adding observers spawns an entity which implicitly flushes the command queue, which can cause undefined behaviour if the `WorldEntityMut` is used after this
- The reason `WorldEntityMut` attempted to (unsuccessfully) avoid flushing commands until finished was that such commands may move or despawn the entity being referenced, invalidating the cached location.
- With the introduction of hooks and observers, this isn't sensible anymore as running the commands generated by hooks immediately is required to maintain correct ordering of operations and to not expose the world in an inconsistent state
- Objective is to make command flushing deterministic and fix the related issues
- Fixes #16212
- Fixes #14621 
- Fixes #16034

## Solution

- Allow `WorldEntityMut` to exist even when it refers to a despawned entity by allowing `EntityLocation` to be marked invalid
- Add checks to all methods to panic if trying to access a despawned entity
- Flush command queue after every operation that might trigger hooks or observers
- Update entity location always after flushing command queue

## Testing

- Added test cases for currently broken behaviour
- Added test cases that flushes happen in all operations
- Added test cases to ensure hooks and commands are run exactly in correct order when nested

---

Todo:

- [x] Write migration guide
- [x] Add tests that using `EntityWorldMut` on a despawned entity panics
- [x] Add tests that commands are flushed after every operation that is supposed to flush them
- [x] Add tests that hooks, observers and their spawned commands are run in the correct order when nested

---

## Migration Guide

Previously `EntityWorldMut` triggered command queue flushes in unpredictable places, which could interfere with hooks and observers. Now the command queue is flushed always immediately after any call in `EntityWorldMut` that spawns or despawns an entity, or adds, removes or replaces a component. This means hooks and observers will run their commands in the correct order.

As a side effect, there is a possibility that a hook or observer could despawn the entity that is being referred to by `EntityWorldMut`. This could already currently happen if an observer was added while keeping an `EntityWorldMut` referece and would cause unsound behaviour. If the entity has been despawned, calling any methods which require the entity location will panic. This matches the behaviour that `Commands` will panic if called on an already despawned entity. In the extremely rare case where taking a new `EntityWorldMut` reference or otherwise restructuring the code so that this case does not happen is not possible, there's a new `is_despawned` method that can be used to check if the referred entity has been despawned.

### CODE REVIEW

**Comment by alice-i-cecile** [comment]
Yes please, I'd like a small note here.

**Review by maniwani — COMMENTED** [review]
Yes, this is pretty much what I was thinking. I assume branch prediction should hide any overhead from this since the condition should basically never be true.

I think hitting this case should issue a warning. And we might want to have a `#[track_caller]` on the affected `EntityWorldMut` methods so that anyone who sees the warning knows where to start looking.

Something like...
```rust
#[inline(never)]
#[cold]
fn on_entity_invalid(entity: Entity, caller: &'static Location) {
    warn!("error[B<insert-error-number-here>]: {caller} tried to modify the entity {:?}, but it no longer exists. See: https://bevyengine.org/learn/errors/b<insert-error-number-here>", entity);
}
```

**Comment by maniwani** [comment]
Ah, wait. Since `EntityWorldMut` can be converted into the other kinds of entity references, we may need to add the invalid location check to them as well (or make the conversion fallible).

Some of the `UnsafeEntityCell` methods those references use probably assume its location is valid.

**Comment by Maximetinu** [comment]
Hello! 👋 

I lack context about the changes in this PR, but by [petition](https://discord.com/channels/691052431525675048/742569353878437978/1303418282065526875) of @alice-i-cecile , I checked out this branch to see if I can still reproduce the crash of `flush() needs to be called before this operation is legal` that I was hitting in my code

The answer is that no, I cannot.

The thing is, I can't repro it in bevy main neither, so this bug must have been fixed at some point between Bevy 0.14.2 (the version where I encountered) and current Bevy main atow

Here, for reference:

----

this is my minimal reproduceable example, on top of Bevy 0.14.2: 

https://github.com/Maximetinu/bevy/commits/minimal-reproduceable-bug-on-remove-hook/

see changes in latest commit

running that modified example does reproduce the bug

notice that the cause is just spawning an empty entity during a on_remove hook

----

This is my minimal reproduceable example cherry-picked to this branch: 

https://github.com/Maximetinu/bevy/commits/world-entity-mut-flushes-checking-if-panic-keeps-happening/

see changes in latest commit, they are the same as in the branch above

running that modified example does **not** reproduce the bug

so, this branch works 🥳 

----

However, bevy main also works:

https://github.com/Maximetinu/bevy/commits/reproducing-on-remove-hook-panic-on-bevy-main/

which means that, well, this branch does not fix per se this bug, because it is already fixing on Bevy main

but at least it means that it's not re-introducing it neither 🙂 

----

Maybe [my minimal reproduceable example ](https://github.com/Maximetinu/bevy/blob/world-entity-mut-flushes-checking-if-panic-keeps-happening/examples/ecs/component_hooks.rs)can help to write a test covering from this specific scenario

I hope this helps!

**Comment by alice-i-cecile** [comment]
I'd love to see that turned into a test, either in this PR or separately :)

**Comment by Maximetinu** [comment]
> I'd love to see that turned into a test, either in this PR or separately :)

I have made a test for this, that fails at 0.14.2 but passes in current bevy main, so it should cover from this regression

```rs
#[test]
fn test_spawn_entities_during_on_remove_hook() {
    #[derive(Component)]
    struct MyComponent;

    App::new()
        .add_plugins(MinimalPlugins)
        .add_systems(Startup, |world: &mut World| {
            world.register_component_hooks::<MyComponent>().on_remove(
                |mut world, _entity, _component_id| {
                    world.commands().spawn_empty();
                },
            );
        })
        .add_systems(
            Update,
            |mut commands: Commands,
                my_component_q: Query<Entity, With<MyComponent>>,
                mut exit_event: EventWriter<AppExit>,
                mut after_first_frame: Local<bool>| {
                for entity in &my_component_q {
                    commands.entity(entity).despawn();
                }

                commands.spawn(MyComponent);

                if *after_first_frame {
                    exit_event.send(AppExit::Success);
                }

                *after_first_frame = true;
            },
        )
        .run();
}
```

It's a bit of an unusual test (I'm not even sure if `MinimalPlugins` can be used in a test like this). It's more an integration test rather than a unit test. I don't know if there is some place inside Bevy repo where more of these tests exist. If so, I can open a PR to add it.

**Comment by alice-i-cecile** [comment]
Let's spin this out into a new issue :)

**Comment by nakedible** [comment]
@maniwani Updated design (just quick notes for now):
- Handle also `UnsafeEntityCell`
- Instead of setting location entirely to invalid, instead set both `archetype_id` and `table_id` to "empty", but keep `archetype_row` and `table_row` as invalid. That allows us to behave more like an empty entity for most APIs.

**Comment by nakedible** [comment]
I changed this pull to instead panic rather than warn and try to behave if nothing is wrong. The reason for this is that if we only try to warn, there's a quite wide ranging knock-off effect into `UnsafeEntityCell` and a lot of other places which store `EntityLocation`. If we instead panic, the effects (and the extra runtime check) are limited to just `WorldEntityMut`. Also, Bevy already opts to panicing if using commands to modify an entity that has been despawned (https://bevyengine.org/learn/errors/b0003/) so this is similar behaviour. There should be nobody depending on this behaviour currently as calling any of the methods after the entity has been despawned by hooks would have already been unsound in the past – so if it happens, then the panics will reveal places where there has been already been a bug.

**Comment by nakedible** [comment]
@alice-i-cecile @maniwani I'd love to get feedback if the new panicing approach is good or bad. Also, is it reasonable to add a panics section to all the methods which might panic for this. It should truly be a corner case when this happens, so I'm not sure if it's sensible to spam it everywhere (and it cannot be put into some of the non-fallible `From` conversions).

**Comment by nakedible** [comment]
Implementation of panic is still placeholderish, just to note.

**Comment by alice-i-cecile** [comment]
> Also, Bevy already opts to panicing if using commands to modify an entity that has been despawned

For what it's worth, this behavior is widely hated :)

I think I'm broadly on board with panicking here though, especially as a first pass. This really is an edge case, and I think that trying to figure out better ways to prevent this bad state from ever arising is more useful than bubbling the error up.

**Comment by nakedible** [comment]
If #16499 gets merged before this one, one of the test cases will break, as it should when the ordering of hooks and observers is changed.

**Comment by nakedible** [comment]
@alice-i-cecile -S-Waiting-on-Author +S-Needs-Review 🙇

**Review by alice-i-cecile — APPROVED** [review]
Excellent tests and good analysis. I'd like to clean up the (very niche) panics here by swapping to results, but that's best left for follow-up.

File: crates/bevy_ecs/src/world/entity_ref.rs [hunk 1]
```diff
@@ -860,21 +860,39 @@ pub struct EntityWorldMut<'w> {
...
+    #[inline(never)]
+    #[cold]
+    fn panic_despawned(&self) -> ! {
+        panic!("Entity {} has been despawned, possibly by hooks or observers, so must not be accessed through EntityWorldMut after despawn.", self.entity);
+    }
+
+    #[inline(always)]
+    #[track_caller]
+    fn assert_not_despawned(&self) {
+        if self.location.archetype_id == ArchetypeId::INVALID {
```
Comment (chescock) [inline crates/bevy_ecs/src/world/entity_ref.rs:873]: This could use the `is_despawned()` method if you wanted.  

```suggestion
        if self.is_despawned() {
```

**Review by chescock — APPROVED** [review]
I don't entirely understand what `world.flush()` does, but I do believe this PR calls `assert_not_despawned();` before every read or write of the entity or its components and calls `world.flush()` and `update_location()` after every write, so `self.location` should always be correct.  

The one exception is that the `world_scope()` method calls `update_location()` but not `world.flush()`.  Should that call `world.flush()` as well?

**Comment by hymm** [comment]
An alternative to checking in every method if the entity has been despawned would be to panic after calling world.flush instead of checking in each method. This would disallow despawning the entity in hooks, but I think that makes sense that you wouldn't be able to despawn the EntityWorldMut while holding it.

**Comment by nakedible** [comment]
> I don't entirely understand what `world.flush()` does, but I do believe this PR calls `assert_not_despawned();` before every read or write of the entity or its components and calls `world.flush()` and `update_location()` after every write, so `self.location` should always be correct.  
> 
> The one exception is that the `world_scope()` method calls `update_location()` but not `world.flush()`.  Should that call `world.flush()` as well?  

World flush runs any `Command`s that have been queued. Commands are queued by hooks and observers if they want to do archetype changes, as they only get a `DeferredWorld`.

The `world_scope` function just allows a function to run with the world, but it doesn't necessarily queue any commands. If it does, it's the responsibility of the function to flush if necessary.

There has been talk of having commands apply immediately when holding a `&mut World`, like in this `world_scope` function, which would solve the whole issue of asking the user to flush.

**Comment by nakedible** [comment]
> An alternative to checking in every method if the entity has been despawned would be to panic after calling world.flush instead of checking in each method. This would disallow despawning the entity in hooks, but I think that makes sense that you wouldn't be able to despawn the EntityWorldMut while holding it.

It would be an alternative, but instead the aim is to go to another direction, to make the methods fallible instead.

Also, there are two other reasons.

First, there aren't any other ways to make archetype changes to entities but to take `WorldEntityMut` via `world.entity_mut(ent)`. So if despawning the current entity would be totally disallowed, then there would not be a way to safely trigger such a change as you can't not hold a reference while doing it.

Second, you can't really prevent hooks and observers from making these types of changes in some special cases. So there isn't a workaround for that. Where as just dropping a `WorldEntityMut` after an archetype mutation operation is a trivial thing to do by the user.

**Comment by NthTensor** [comment]
FWIW i think panicking is fine here; there's similar stuff in the engine that already works this way. We can reconsider it in a broader review of bevy's error handling. But especially for guarding invariant going into async code, panicking is probably the way to go.
