### PR TITLE
Fix linux nvidia + xwayland freeze at startup

### LINKED ISSUE #16122: NVIDIA drivers on Linux can cause an intermittent failure to render under X11
> Maybe we could rethink the `Couldn't get swap chain texture. This often happens with the NVIDIA drivers on Linux. It can be safely ignored.` error to somehow force update the window on startup. It seems that it infact can't be safely ignored. 

 _Originally posted by @eero-lehtinen in [#16120](https://github.com/bevyengine/bevy/issues/16120#issuecomment-2440215274)_

### PR DESCRIPTION
**Pull request by eero-lehtinen**
# Objective

- Fixes #16122

When the wayland feature is not enabled, xwayland is used on wayland. Nvidia drivers are somewhat bugged on linux and return outdated surfaces on xwayland for seemingly no reason. Oftentimes at startup we get into an infine loop where the surface is permanently outdated and nothing (or sometimes only the first frame) is drawn on the screen.

## Solution

After experimenting I found that we can safely call configure again and the issue seems to resolve itsef. After this change I couldn't reproduce the original issue after many tries. More testing is probably needed though.

The main issue is that `get_current_texture` fails sometimes because the surface remains outdated even after configuring. It would be better to just properly handle and never panic when `get_current_texture` fails. This way we always call configure when outdated and bail when getting the swapchain fails instead of crashing. The number of special cases is also reduced.

## Testing

I tested the example "rotation" manually by trying to move around.

It works with X11 and Xwayland and the non panicing code paths didn't change so other platforms aren't affected.

### CODE REVIEW

**Comment by alice-i-cecile** [comment]
@Frost2779 can you test this for me? This should help with what you were seeing in #16120.

File: crates/bevy_render/src/view/window/mod.rs [hunk 1]
```diff
@@ -280,6 +280,7 @@ pub fn prepare_windows(
                 }
                 #[cfg(target_os = "linux")]
                 Err(wgpu::SurfaceError::Outdated) if is_nvidia() => {
+                    render_device.configure_surface(surface, &surface_data.configuration);
```
Comment (alice-i-cecile) [inline crates/bevy_render/src/view/window/mod.rs:283]: Comment please!

File: crates/bevy_render/src/view/window/mod.rs [hunk 2]
```diff
@@ -280,6 +280,7 @@ pub fn prepare_windows(
...
                     warn_once!(
                         "Couldn't get swap chain texture. This often happens with \
```
Comment (alice-i-cecile) [inline crates/bevy_render/src/view/window/mod.rs:285]: Can we remove this warning now?

**Comment by Frost2779** [comment]
@alice-i-cecile I tested with the MRE from the original issue thread with 10 separate launches and did not encounter the unexpected behavior. Sprite rendered and systems seemed to function as expected.

**Comment by richchurcher** [comment]
> @alice-i-cecile I tested with the MRE from the original issue thread with 10 separate launches and did not encounter the unexpected behavior. Sprite rendered and systems seemed to function as expected.

Just out of curiosity, did you test with `wayland` feature on or off?

**Comment by eero-lehtinen** [comment]
I don't really get why we even have this if-else here when the two cases are identical except the else case handles extra stuff that already never happens in the first.

File: crates/bevy_render/src/view/window/mod.rs [hunk 3]
```diff
@@ -431,5 +405,7 @@ pub fn create_surfaces(
             };
             render_device.configure_surface(&data.surface, &data.configuration);
         }
+
+        window_surfaces.configured_windows.insert(window.entity);
```
Comment (eero-lehtinen) [inline crates/bevy_render/src/view/window/mod.rs:409]: I thought marking windows configured would fit after configuring them instead of in the next system where they are configured only when outdated.

**Review by BenjaminBrienen — APPROVED** [review]

File: crates/bevy_render/src/view/window/mod.rs [hunk 4]
```diff
@@ -250,60 +249,35 @@ pub fn prepare_windows(
...
+                window.set_swapchain_texture(frame);
+            }
+            Err(wgpu::SurfaceError::Outdated) => {
+                render_device.configure_surface(surface, &surface_data.configuration);
+                let frame = match surface.get_current_texture() {
+                    Ok(frame) => frame,
+                    Err(err) => {
+                        // This is a common occurrence on X11 and Xwayland with NVIDIA drivers
+                        // when opening and resizing the window.
+                        warn!("Couldn't get swap chain texture after configuring. Cause: '{err}'");
```
[the remark this answers is not in the document]
Comment (eero-lehtinen) [reply crates/bevy_render/src/view/window/mod.rs:264]: We don't have any platforms that instantly panic when spawning a window or resizing, so this doesn't functionally change anything. Also it is better to handle errors instead of just panicing in general, clearly just having an outdated surface isn't fatal. It's also completely possible that some other platform also returns an error here in the future.

[the remark this answers is not in the document]
Comment (tychedelia) [reply crates/bevy_render/src/view/window/mod.rs:264]: Okay, that's good enough for me. Thanks!

**Comment by eero-lehtinen** [comment]
> I don't really get why we even have this if-else here when the two cases are identical except the else case handles extra stuff that already never happens in the first.
> 
> #12542 here I also wanted to remove the if-else but didn't because people didn't want to review too much code, but I really do think it's better that way.

It looks like here https://github.com/bevyengine/bevy/pull/12055/files#diff-b0a34efd7fd2e03ca78f181d1ecce355b927f07669a75501af11498f8b9ec3adL343 we did something extra in the if statement, but now it's not useful anymore.
