### PR TITLE
Remove prepasses from the render world when they're removed from the main world.

### LINKED ISSUE #16679: Forward rendering seems broken
## Bevy version
72f096c91ea1056c41f2da821d310765c4482c00

## Relevant system information

```
2024-12-06T04:20:17.216608Z  INFO bevy_diagnostic::system_information_diagnostics_plugin::internal: SystemInfo { os: "Windows 11 Home", kernel: "22631", cpu: "AMD Ryzen 7 5800X 8-Core Processor", core_count: "8", memory: "15.9 GiB" }
2024-12-06T04:20:17.720519Z  INFO bevy_render::renderer: AdapterInfo { name: "NVIDIA GeForce RTX 3080", vendor: 4318, device: 8710, device_type: DiscreteGpu, driver: "NVIDIA", driver_info: "560.94", backend: Vulkan }
```

## What you did

Run the deferred_rendering example

## What went wrong

Forward rendering seems broken (forward + prepass is fine)

* POM seems broken on the cube
* Normal maps seem to be missing from the flight helmet

### PR DESCRIPTION
**Pull request by pcwalton**
This makes switching rendering modes in `deferred_rendering` work again.

Closes #16679.

### CODE REVIEW

**Comment by pcwalton** [comment]
This is a partial fix for #16679

**Comment by pcwalton** [comment]
This should be ready now. It fixes #16679.

**Review by tychedelia — APPROVED** [review]
Would love to have a better pattern around how we handle these to avoid these kinds of bugs in the future. Thanks for tracking this down!

File: crates/bevy_pbr/src/deferred/mod.rs [hunk 1]
```diff
@@ -462,11 +460,19 @@ pub fn prepare_deferred_lighting_pipelines(
         dither,
         shadow_filter_method,
         (ssao, ssr, distance_fog),
-        (normal_prepass, depth_prepass, motion_vector_prepass),
+        (normal_prepass, depth_prepass, motion_vector_prepass, deferred_prepass),
         has_environment_maps,
         has_irradiance_volumes,
     ) in &views
     {
+        // If there is no deferred prepass, remove the old pipeline if there was
```
Comment (JMS55) [inline crates/bevy_pbr/src/deferred/mod.rs:468]: I wonder if there's the same bug in meshlets... Feel free to ignore that for this PR though, the entire CPU-side of meshlets needs redoing once the GPU side is finished.

**Review by JMS55 — APPROVED** [review]
